### ISSUE TITLE
Klarna doesn't appear inside payment sheet

### ISSUE THREAD

**Issue by minuitagency** [stripe/stripe-react-native#1002]
Hi, 

We're trying to add Klarna to our mobile app, we added it as payment option from the console in test and production, added id inside our nodeJS backend :

```

    const paymentIntent = await stripe.paymentIntents.create({
      amount: (canPayLater ? totalPrice : arrhes + platformFees) * 100,
      currency: 'eur',
      confirmation_method: 'automatic',
      receipt_email: mail,
      customer: stripeCustomerID,
      shipping: {
        name: 'Jane Doe',
        address: {
          state: 'Texas',
          city: 'Houston',
          line1: '1459  Circle Drive',
          postal_code: '77063',
          country: 'US',
        },
      },
      payment_method_types: ['card', 'klarna'],
    });
```

Added in the mobile app inside the presentPaymentSheet function : 

```
          const {error: errorSheet} = await presentPaymentSheet({
            clientSecret: client_secret,
            allowsDelayedPaymentMethods: canPayLater,
          });
```

But Klarna doesn't appear: 

![image](https://user-images.githubusercontent.com/38316888/174582864-50856e48-2fb5-4a90-a0eb-f480876c50db.png)

Any idea? 

Thanks, 

Théo

**Comment by professorkolik** [comment]
Make sure you configured step 5 
https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet

**Comment by charliecruzan-stripe** [comment]
Hi! We have all our docs for paying with Klarna [here](https://stripe.com/docs/payments/klarna). 

I know you said you did this, but it's worth double checking to make sure your account is eligible for Klarna by navigating to your [Dashboard payment method settings](https://dashboard.stripe.com/settings/payments). 

What version of stripe-react-native are you using?

**Comment by ag91** [comment]
@minuitagency any success with this? If not, have you tried setting `allowsDelayedPaymentMethods` as a config of initPaymentSheet? From your example, it seems you are setting it too late (presentPaymentSheet) according to docs

**Comment by ag91** [comment]
in our case it wasn't showing because:
1. of a very outdated version of stripe-react-native (< 0.4)
2. redirectURL wasn't set
3. the backend wasn't adding the right `payment_method_types`
