### ISSUE TITLE
App crashes and Hang on clicking continue after entering the card details on payment screen on real Device but not on simulator

### ISSUE THREAD

**Issue by ShobhitGalaxy2021** [stripe/stripe-react-native#1006]
**Describe the bug**
When user enters the card detail, and clicks continue, the App Hangs and crashes on real device. But the issue doesn't come on simulator and works perfectly.

**To Reproduce**
1. Go to Payment Page
2. Enter the card details and inputs
3. Scroll down to continue button and click on it
4. Once the continue button is clicked, the loader continues to operate for a long period of time. Sometimes the app too get crashes on real device only.

**Expected behavior**
A smooth transition of payment section should occur once the continue/submit button is pressed.

**Smartphone (please complete the following information):**
 - OS: Android/iOS
 - Version : Android version 12

**Comment by charliecruzan-stripe** [comment]
Can you provide a reproducible example? What `stripe-react-native` functions are called when the user clicks your Continue button?

**Comment by charliecruzan-stripe** [comment]
Closing for now for no reproducible demo, will reopen if one is provided
