### ISSUE TITLE
cardStyle in CardForm component is not working in android

### ISSUE THREAD

**Issue by skjangid** [stripe/stripe-react-native#1017]
I am using following code for add stripe form in my react native app.

<StripeProvider
          publishableKey="**********"
          merchantIdentifier="merchant.identifier"
        >
          <CardForm
            postalCodeEnabled={false}
            onFormComplete={(cardDetails) => {
              console.log('card details', cardDetails);
            }}
            onCardChange={(cardDetails) => {
              console.log('onCardChange cardDetails', cardDetails);
            }}
            cardStyle={{
              backgroundColor: '#ffffff',
              borderColor: '#000000',
              borderWidth: 1,
              borderRadius: 2,
              fontSize: 12,
              placeholderColor: '#000000',
              textColor: '#000000',
              textErrorColor: '#000000'
            }}
            style={{
              width: '100%',
              height: 200,
              marginVertical: 30,
            }}
          />
        </StripeProvider>

But the cardStyle in CardForm component is not working for me.
![processed-f7e6d290-2d54-4039-acdb-d4ae16b075c5_733lDZeD](https://user-images.githubusercontent.com/4602467/175526009-2b60928f-a600-4f63-9a23-0f22bc945b39.jpeg)

**Comment by charliecruzan-stripe** [comment]
What version of `@stripe/stripe-react-native`? This is working for me with your code: 
<img width="349" alt="Screen Shot 2022-06-24 at 9 33 20 AM" src="https://user-images.githubusercontent.com/97612659/175546601-9e6d9a96-2df3-4b75-a787-682da4f0efb3.png">

**Comment by charliecruzan-stripe** [comment]
Ah okay, this was added in v0.8.0- https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#080---2022-04-27

**Comment by skjangid** [comment]
Ok, but 0.8.0 is not working with my code.

**Comment by skjangid** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/4602467/175759314-4b538dbc-e22f-43ce-8cdc-146889b6d03c.png">

Pod not working with v0.8.0

**Comment by charliecruzan-stripe** [comment]
It's not that the pod isn't working, it looks like you need to bump your deployment target in Xcode. Make sure to look through the changelog changes (especially breaking ones) when upgrading
