### ISSUE TITLE
CardField needs an `onBlur` event too

### ISSUE THREAD

**Issue by pvinis** [stripe/stripe-react-native#102]
**Describe the bug**
It already has an `onFocus` which is great, but we should have an `onBlur` to complement it.

**Expected behavior**
`onBlur` to exist, alongside `onFocus`.

**Comment by thorsten-stripe** [comment]
@pvinis unfortunately we do not have the ability to detect onBlur on Android atm. Can you outline what your need is for this?

**Comment by pvinis** [comment]
It's pretty useful for forms and error showing etc, so that we only show/trigger them onBlur.

**Comment by pvinis** [comment]
If it's not doable now, maybe it can be a non-blocker, but I think this should be there, at some point.

**Comment by aganov** [comment]
Also if possible to add `CardField` methods `blur` `focus` `clear`

```js
const ref = useRef(null);

<Wrapper onEvent={() => ref.current?.blur()}>
  <CardField ref={ref} />
</Wrapper>
```

Draft implementation for iOS: https://gist.github.com/aganov/eaffbb691848299458df449a58de3979

**Comment by thorsten-stripe** [comment]
Copying these ideas over from https://github.com/stripe/stripe-react-native/issues/222#issuecomment-856520915

> I have shuffled things around so if someone presses another element while the CardField is in focus, that removes our tracking of the field being in focus (it also prevents the normal behaviour when pressing those elements). This let me work around a lack of onBlur, but it would be a lot cleaner if that existed.

> Even cleaner would be some way (maybe prop driven) to make it so if you press outside of the keyboard (and maybe check they aren't pressing the field component?), the keyboard is dismissed without the press doing anything else. I think I could do this purely in RN by putting up some kind transparent View on top of the entire screen based on the field having focus, but I don't know how I would still let the user press into the different sub-fields of the CardField component

**Comment by arekkubaczkowski** [comment]
https://github.com/stripe/stripe-react-native/pull/337
thanks @aganov for providing the approach
