### ISSUE TITLE
Save card

### ISSUE THREAD

**Issue by december1990** [stripe/stripe-react-native#1026]
In my application i need to implement a screen to just save cards or remove them, but in documentation i didnt find anything regarding that and as I understand saving card is only possible by making a payment and saving the card after the payment is successful. Is there anyway to securely save card or edit them without making payment ? Thanks

**Comment by charliecruzan-stripe** [comment]
hi! these are the docs you're looking for: https://stripe.com/docs/payments/save-and-reuse

**Comment by december1990** [comment]
Hi, the doc you shared says that

" The [Setup Intents API](https://stripe.com/docs/api/setup_intents) lets you save a customer’s card without an initial payment. This is helpful if you want to onboard customers now, set them up for payments, and charge them in the future—when they’re offline.
Use this integration to set up recurring payments or to create one-time payments with a final amount determined later, often after the customer receives your service."

I don't want to charge the customers when they are offline or after they have used my service. to be precise I'm developing a food ordering app and I want the customers to be able to see and save cards from profile section of the app and when they place an order later they should see and select one of the saved cards from the list in payment sheet. Should I still use setup intents for that ?

**Comment by charliecruzan-stripe** [comment]
yep, you can still use setup intents for that case.

Just curious- why do you want customers saving their cards first (in their profile settings), before the checkout flow starts?

**Comment by jaydeep-kumbhani-tech4biz** [comment]
@december1990  find the solution because I have to same flow for react native application. can you share the step to me how can i do this.
