### ISSUE TITLE
Get payment id when the confirmPaymentSheetPayment resolves with success

### ISSUE THREAD

**Issue by december1990** [stripe/stripe-react-native#1028]
hi, confirmPaymentSheetPayment resolves with an error and by checking that we decide if the payment was successful or not. the question is how can I get payment id when the payment is successful, in order to call a backend api to record them in database. thanks

**Comment by december1990** [comment]
I mean when the transaction is done I need to send the transaction id to the backend to save it, but all we get from confirmPayment is error or success, payment intent id would work I guess, thanks. On stripe integration docs for react native it's only recommended to use webhooks.

**Comment by charliecruzan-stripe** [comment]
we recommend webhooks generally, but if you're looking for docs on a flow _without_ webhooks, see [here](https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native)
