### ISSUE TITLE
Product - Archive failed with: Command CopyPNGFile failed with a nonzero exit code

### ISSUE THREAD

**Issue by Effimero86** [stripe/stripe-react-native#1029]
Hello,
I'm trying to build a release version of our app with Product -> Archive command, but after a few second the build stopped with the following error:

CopyPNGFile /Users/marcocastaldini/Library/Developer/Xcode/DerivedData/CocaiTemplate-dcgafrjhxmiwanaqvorxsipwlkxi/Build/Intermediates.noindex/ArchiveIntermediates/CocaiTemplate/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/StripeFinancialConnections.bundle/close@3x.png /Users/marcocastaldini/TEST-IOS/CocaiTemplate/ios/Pods/StripeFinancialConnections/StripeFinancialConnections/StripeFinancialConnections/Resources/Images/close@3x.png (in target 'StripeFinancialConnections-StripeFinancialConnections' from project 'Pods')
    cd /Users/marcocastaldini/TEST-IOS/CocaiTemplate/ios/Pods
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk
    export TOOLCHAINS\=
    /Applications/Xcode.app/Contents/Developer/usr/bin/copypng -compress -strip-PNG-text /Users/marcocastaldini/TEST-IOS/CocaiTemplate/ios/Pods/StripeFinancialConnections/StripeFinancialConnections/StripeFinancialConnections/Resources/Images/close@3x.png /Users/marcocastaldini/Library/Developer/Xcode/DerivedData/CocaiTemplate-dcgafrjhxmiwanaqvorxsipwlkxi/Build/Intermediates.noindex/ArchiveIntermediates/CocaiTemplate/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/StripeFinancialConnections.bundle/close@3x.png

Can't exec "xcrun": No such file or directory at /Applications/Xcode.app/Contents/Developer/usr/bin/copypng line 17.
Use of uninitialized value $PNGCRUSH in scalar chomp at /Applications/Xcode.app/Contents/Developer/usr/bin/copypng line 18.
sh: dirname: command not found
Use of uninitialized value $args[0] in system at /Applications/Xcode.app/Contents/Developer/usr/bin/copypng line 89.
Can't exec "": No such file or directory at /Applications/Xcode.app/Contents/Developer/usr/bin/copypng line 89.
Use of uninitialized value $args[0] in join or string at /Applications/Xcode.app/Contents/Developer/usr/bin/copypng line 91.
ERROR: Failed to run  -q -iphone -f 0 -rem text /Users/marcocastaldini/TEST-IOS/CocaiTemplate/ios/Pods/StripeFinancialConnections/StripeFinancialConnections/StripeFinancialConnections/Resources/Images/close@3x.png /Users/marcocastaldini/Library/Developer/Xcode/DerivedData/CocaiTemplate-dcgafrjhxmiwanaqvorxsipwlkxi/Build/Intermediates.noindex/ArchiveIntermediates/CocaiTemplate/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/StripeFinancialConnections.bundle/close@3x.png
Command CopyPNGFile failed with a nonzero exit code

How to reproduce:

Run from your terminal in your home folder:
  npx react-native init Template --template react-native-template-typescript
Install @stripe/stripe-react-native from command line in vs code.
From terminal in ios folder launch pod install.
Open ios folder in xcode, change iOS Deployment Target in project and pod folder to 13.0.
Go to Product -> Scheme -> Edit Scheme then set the Build Configuration dropdown to Release.
Make sure to set the device to "Any iOS Device (arm64)".
Click on Product -> Archive.

Mac OSX: 12.4
XCode: 13.4.1

from package.json:
  "dependencies": {
    "@stripe/stripe-react-native": "^0.14.0",
    "react": "18.0.0",
    "react-native": "0.69.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.69.1",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.70.3",
    "react-test-renderer": "18.0.0",
    "typescript": "^4.4.4"
  },

**Comment by charliecruzan-stripe** [comment]
hi @Effimero86 , do you have the Xcode command line tools installed? You might want to investigate the contents of `/Applications/Xcode.app/Contents/Developer/usr/bin/`. That line number it's referencing assigns `PNGCRUSH` to ``xcrun -f pngcrush``

You could run `xcrun -f pngcrush` from your terminal and see what the output is

**Comment by rmcclellan-izo** [comment]
This was unrelated to the library, but wanted to chime in here since this has a high google ranking for the error message - this error occurs when the `PATH` environment variable from `launchd` doesn't include `xcrun`.  A possible cause of this is a corrupt value for the `PathEnvironmentVariable` in the `/private/var/db/com.apple.xpc.launchd/config/user.plist` plist, which can be fixed with `sudo defaults delete /private/var/db/com.apple.xpc.launchd/config/user.plist PathEnvironmentVariable`

**Comment by shahbazmustafa-invozone** [comment]
@any one find it solution i am still facing this issue?

**Comment by mehdico** [comment]
Same!

```
Command CopyPNGFile emitted errors but did not return a nonzero exit code to indicate failure
```

`xcrun -f pngcrush` output:

```
sh: line 1: 76443 Bus error: 10           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -find pngcrush 2> /dev/null
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -find pngcrush 2> /dev/null' failed with exit code 35328: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "pngcrush", not a developer tool or in PATH
```

**Comment by charliecruzan-stripe** [comment]
You might need to change the path: https://developer.apple.com/forums/thread/116552

**Comment by himmat-g-hh** [comment]
any working solution for this

**Comment by nikitph** [comment]
if anyone runs into this. It would be worth deleting the derived data folder and archiving again. That fixed it for us.
