### ISSUE TITLE
Execution failed for task ':@stripe_stripe-react-native:compileDebugKotlin'.

### ISSUE THREAD

**Issue by thanhnguyenmkd** [stripe/stripe-react-native#1030]
**Describe the bug**
I try to install stripe-react-native but got the error Execution failed for task ':@stripe_stripe-react-native:compileDebugKotlin'

**To Reproduce**
1. npm install @stripe/stripe-react-native
2. react-native run-android

**Desktop (please complete the following information):**
 - OS: Window 10
 - tool: Visual code
 - Android studio for Virtual android device
 - react native ver: 0.60.5  
 - Node: 12.22.12

**This is gradle file**
![image](https://user-images.githubusercontent.com/106788510/177270759-c195db4e-a884-4233-9a10-808d985fb557.png)

**Error **
![image](https://user-images.githubusercontent.com/106788510/177270536-19dfa7fa-a955-4f3d-8f8b-0f6744d1c219.png)

Any way to fix it?
Thanks!!!

**Comment by charliecruzan-stripe** [comment]
hi! it looks like your react native version is pretty old, and `@stripe/stripe-react-native` (as of v0.8.0) only supports RN 0.64 and above. I would recommend upgrading your React Native version (or, using an older version of this library, although that I recommend **far** less 😅 )

**Comment by AstrOOnauta** [comment]
Into `android/build.gradle`, I just updated my `kotlinVersion` and `kotlin_version` from `1.6.21` to `1.8.0`.

My project is RN Cli:
 - React Native v0.71.13;
 - @stripe/stripe-react-native v 0.35.0.
