### ISSUE TITLE
BECS Direct Debit option not presenting as payment option on PaymentSheet

### ISSUE THREAD

**Issue by P-Russell** [stripe/stripe-react-native#1031]
**Describe the bug**
The option to pay using BECS Direct Debit is not available to users

**To Reproduce**

1. Set up the payment sheet as per the documentation https://stripe.com/docs/payments/accept-a-payment?platform=react-native

2. Create a setupIntent like so:
```javascript
const setupIntent = await this.stripe.setupIntents.create({
      customer: customerId,
      payment_method_types: ['card', 'au_becs_debit'],
    })
```

3. Initialise the payment sheet like so
```javascript
    const { error } = await initPaymentSheet({
      customerId: stripeUserId,
      customerEphemeralKeySecret: paymentSetupData.ephemeralKey,
      setupIntentClientSecret: paymentSetupData.clientSecret,
      allowsDelayedPaymentMethods: true,
      returnURL: paymentSetupData.returnUrl,
      merchantDisplayName: 'Our Company Name',
      applePay: await isApplePaySupported(),
      merchantCountryCode: 'AU',
      googlePay: false,
      currencyCode: 'AUD',
      testEnv: !isProductionEnvironment,
    });
```

4. Call present payment sheet:
```javascipt
    const { error } = await presentPaymentSheet();
```

**Expected behavior**
An option to pay using BECS Direct Debit will be available

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2022-07-05 at 17 27 10](https://user-images.githubusercontent.com/16173883/177363551-86140962-905d-46ef-8da2-d2fcd4f3914d.png)

**Smartphone (please complete the following information):**
 - Device:  iPhone8
 - OS: iOS 15.4
 - Version 0.14.0

**Additional context**

**Comment by charliecruzan-stripe** [comment]
What version of `@stripe/stripe-react-native` are you using?

**Comment by charliecruzan-stripe** [comment]
are you using Expo?

**Comment by P-Russell** [comment]
Nope. Just the normal bare workflow

**Comment by charliecruzan-stripe** [comment]
Ah I see, you're using setup intents here- unfortunately, [stripe-ios doesnt support AU BECS with setup intents in the payment sheet right now. ](https://github.com/stripe/stripe-ios/blob/671be35be6775c5a203e3a1ede4bf6fc45b3311f/Stripe/PaymentSheet%2BPaymentMethodAvailability.swift#L57)
