### ISSUE TITLE
InvalidVectorPath error on pay_with_googlepay_button_content.xml

### ISSUE THREAD

**Issue by imajindev** [stripe/stripe-react-native#1039]
**Describe the bug**
lintDebug error prevent android gradle build

**To Reproduce**
1. Go to 'android' folder
5. run ./gradle clean build
6. error: node_modules/@stripe/stripe-react-native/android/src/main/res/drawable-bg-night/pay_with_googlepay_button_content.xml:2: Error: Use -0.009 instead of -.009 to avoid crashes on some devices [InvalidVectorPath]

**Expected behavior**
should build successfully

 - Device: macbook pro
 - OS: macos x86
 - RN version: 0.69.1
 - Library Version: 0.14.0

**Comment by charliecruzan-stripe** [comment]
what version of Gradle are you using?

**Comment by imajindev** [comment]
this is if u run from a RN app, 
but i realise we dont need to run this gradlew clean build at all if we just want to run it in RN,
was busy debugging issues, i thought this could be one of the reason why its not working
anyway for future developers who got stuck on this path, this path is not it. the issue is somewhere else
