### ISSUE TITLE
Updating stripe-react-native leads to failed build due to cycle in Stripe dependency

### ISSUE THREAD

**Issue by nmehlei** [stripe/stripe-react-native#1040]
**Describe the bug**
After updating a React Native project from `@stripe/stripe-react-native` `0.8.0` to `0.14.0`, I got the following output during `pod install` invocation:

```
[!] CocoaPods could not find compatible versions for pod "Stripe":
  In snapshot (Podfile.lock):
    Stripe (= 22.0.0, ~> 22.0.0)

  In Podfile:
    stripe-react-native (from `../node_modules/@stripe/stripe-react-native`) was resolved to 0.14.0, which depends on
      Stripe (~> 22.5.1)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Stripe` inside your development pod `stripe-react-native`.
   You should run `pod update Stripe` to apply changes you've made.
```
After invoking `pod install --repo-update` as suggested, attempts to build the react native app fail due to a Stripe-related cycle in dependencies:
```
error: Cycle in dependencies between targets 'MyExampleApp' and 'StripeCore'; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
Cycle path: MyExampleApp → StripeFinancialConnections → StripeCore → MyExampleApp
Cycle details:
→ Target 'MyExampleApp': CodeSign /Users/nmehlei/Library/Developer/Xcode/DerivedData/MyExampleApp-dvpuxmapogpzvtciswkgrtbmdjtr/Build/Products/Debug-iphonesimulator/MyExampleApp.app
○ Target 'MyExampleApp': ProcessProductPackaging  /Users/nmehlei/Library/Developer/Xcode/DerivedData/MyExampleApp-dvpuxmapogpzvtciswkgrtbmdjtr/Build/Intermediates.noindex/MyExampleApp.build/Debug-iphonesimulator/MyExampleApp.build/MyExampleApp.app.xcent
→ Target 'StripeFinancialConnections' has target dependency on Target 'StripeCore'
→ Target 'StripeCore' has compile command for Swift source files
○ That command depends on command in Target 'StripeCore': script phase “Copy generated compatibility header”
```

**Expected behavior**
Updating stripe-react-native should not break compilation

**Screenshots**
Does not apply

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version: 12.3.1

**Smartphone (please complete the following information):**
iPhone simulator, various versions

**Comment by charliecruzan-stripe** [comment]
Could you try cleaning the Xcode build folder & your pods, and reinstalling?

**Comment by nmehlei** [comment]
While I tried to reinstall pods before without any effect, moving back to my master branch (with npm i + pod install) and switching back to these changes fixed the issue for some reason. Cleaning the xcode build might've helped as well. Apologies, this bug report was therefore baseless and can be ignored. Thank you for your help!

**Comment by Seanmclem** [comment]
I'm getting this issue on a fresh install today

**Comment by juancsaenz** [comment]
`pod update` fixes the error for me.

**Comment by airowe** [comment]
Seeing this issue as well. `pod update` not fixing

**Comment by jeffaburt** [comment]
Saw the same thing this morning after updating to `stripe-react-native 0.19.0`. Running the following resolved the issue for me:

```shell
pod update Stripe StripeFinancialConnections
```

**Comment by deflexable** [comment]
any update on this, also experiencing this issue on xcode 🫤

**Comment by deflexable** [comment]
> Seeing this issue as well.
> 
> * `pod update` not fixing
> * Cleaning build directory didn't fix
> * Deleting Derived Data did fix it for me

this works for me thanks
