### ISSUE TITLE
CardField issue on Android with 0.14.0 when postal code is disabled

### ISSUE THREAD

**Issue by jonasbark** [stripe/stripe-react-native#1041]
As seen here:
https://github.com/flutter-stripe/flutter_stripe/issues/817

In short: when postal code is disabled for the CardField and the user enters correct information then:
- card brand shows an error icon
- last4 is missing
- brand is missing

The behavior is correct when postal code is enabled.

![image](https://user-images.githubusercontent.com/1151304/179013740-33751dbb-45d6-4f7e-ba1f-471d5883914e.png)

**Comment by jonasbark** [comment]
Actually, it seems that the problematic combination is:
- enablePostalCode is false
- countryCode is e.g. 'US'

If countryCode is removed then it works as expected. I confirmed that this issue still exists with 0.15.0.

**Comment by charliecruzan-stripe** [comment]
@jonasbark I'm not able to reproduce this, please share a reproducible demo:

```
      <CardField
        postalCodeEnabled={false}
        onCardChange={(cardDetails) => {
          console.log('cardDetails', cardDetails);
        }}
        cardStyle={inputStyles}
        style={styles.cardField}
        countryCode="US"
      />
```

<img width="326" alt="Screen Shot 2022-07-15 at 9 17 51 AM" src="https://user-images.githubusercontent.com/97612659/179264868-e133f68e-a2ac-4981-857f-e950026c862d.png">

```
 LOG  cardDetails {"brand": "Visa", "complete": true, "expiryMonth": 4, "expiryYear": 24, "last4": "4242", "validCVC": "Valid", "validExpiryDate": "Valid", "validNumber": "Valid"}
```

**Comment by jonasbark** [comment]
Thanks for checking - you are right indeed!

I was able to pinpoint and fix the issue on our side. We called setCountryCode before calling setPostalCodeEnabled, which caused the issue:
https://github.com/flutter-stripe/flutter_stripe/commit/93a291f50d03786f38f5b1133dd4b5d550c0d2f7
