### ISSUE TITLE
SEPA payments/change payment method with PaymentSheet (off_session)

### ISSUE THREAD

**Issue by projectnatz** [stripe/stripe-react-native#1046]
**Is your feature request related to a problem? Please describe.**
Our app uses the suggested PaymentSheet to change. a customer payment method or to process a payment.
Our application uses the off_session options because it may required an automatic payment later on.
It makes no sense that the suggested method does not support SEPA payments when the off_session option is on.

**Describe the solution you'd like**
The simplest solution would be to enable SEPA payments when the off_session option is active anyway.

**Describe alternatives you've considered**
I considered using the TextInput approach but:
1. the official guide suggests the PaymentSheet and it's kinda nonsense that this preferred method is not able to handle a very common use case;
2. using a TextInput means you are not using a component made for this kind of thing. If a custom component were present in the stripe-react-native library then maybe we would have considered it (like the CardForm), but using a standard TextInput makes no sense.

Obviously this requests only makes sense if this is not a bug or if I missed something.
I'm also attaching a couple of screenshots of how we initialize the PaymentSheet and PaymentIntent and how this should be sufficient for SEPA payments with the PaymentSheet.

![Screenshot 2022-07-18 at 09 15 13](https://user-images.githubusercontent.com/6991307/179461654-adc516f8-2b57-49dc-a234-54c48c98f992.png)
![Screenshot 2022-07-18 at 09 16 38](https://user-images.githubusercontent.com/6991307/179461663-362559bf-0e4a-4348-8ca8-9cfbfefc0b3d.png)

Thank you for reading this.

**Comment by charliecruzan-stripe** [comment]
Unfortunately, setting `setup_future_usage` for PaymentIntents that will be used with Payment Sheet is not supported for SEPA Debit. We're working on that, but for now you'd have to use the `confirmPayment` function instead (with `paymentMethodType: 'SepaDebit'`)

**Comment by charliecruzan-stripe** [comment]
It's still not supported, and the `stripe-ios` and `stripe-android` repositories are relevant for that particular work. I don't have a PR for you to track, unfortunately. We are tracking this internally, but i can't provide any timelines at the moment

**Comment by VolkerLieber** [comment]
@charliecruzan-stripe Do you have an update on this situation or could tell me if this can be fixed by the community?

**Comment by charliecruzan-stripe** [comment]
No update yet, and this isn't something that can be addressed just in the open source repositories @VolkerLieber
