### ISSUE TITLE
Add support for additional apple pay,  pay networks

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#1052]
**Is your feature request related to a problem? Please describe.**

In #430  JCB was added as additional payment network to apple pay. It would be great if we can create a feature to appe pay where users can add additional pay networks something like: `additionalEnabledApplePayNetworks : [interac]`

A user of our repo stated as well that the Stripe dev team pointed this solution to him but I do not see any support for this in the current library. For reference see:  https://github.com/flutter-stripe/flutter_stripe/issues/845 .

**Additional context**
[Apple official docs](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentrequest/1916122-supportednetworks)

**Comment by charliecruzan-stripe** [comment]
Will include this in the scoping of the next apple pay revamp 👍
