### ISSUE TITLE
Card corrupt when saving more than 4 credit/debit cards

### ISSUE THREAD

**Issue by vimukthinuclei** [stripe/stripe-react-native#1056]
When saving more than 4 cards from CardField, saved cards get corrupted. Can't use the cards after saving more than 4 cards. But when delete some cards and get the list back to 4 cards, it'll start to work.

If any one getting this issue? Are there some solution?

**Comment by charliecruzan-stripe** [comment]
Please follow the Github issue template @vimukthinuclei

**Comment by charliecruzan-stripe** [comment]
Closing because we require bug reports to follow the issue template we provide. Happy to reopen if you can edit the above to provide all the information we ask for in our issue template!
