### ISSUE TITLE
Scheme used in CardForm doesn't match the app one (Expo)

### ISSUE THREAD

**Issue by wcastand** [stripe/stripe-react-native#1057]
**Describe the bug**
When using `CardForm` in my expo app (managed), in my app.config i have `userInterfaceStyle: 'light',` but the phone in dark mode will make the `CardForm` unreadable.

I'm guessing it's because stripe use native component, which use the os style and not the one defined in Expo.

it's an issue because `const colorScheme = useColorScheme();` is returning the expo value so 'light' meaning i can't know where to put a dark background or not.

**To Reproduce**
1. Put your phone in dark mode
2. set the expo `userInterfaceStyle` to `light` in the app.config
3. use the CardForm
4. see the text being white on white

**Expected behavior**
i expect stripe to use the scheme i defined in the expo config.

**Screenshots**
![Screenshot 2022-07-26 at 13 15 31](https://user-images.githubusercontent.com/2178244/180993441-c7df81c7-be8a-4b5d-b3b7-616a8ff0ff16.png)

**Desktop (please complete the following information):**
 - OS: Macbook air M1

**Smartphone (please complete the following information):**
 - Device: emulator iPhone 13 Pro (happens on android or ios)
 - OS: iOS 15

**Comment by charliecruzan-stripe** [comment]
Tested this by changing the `UIUserInterfaceStyle` key in Info.plist to `Light` directly, and CardForm responds correctly (remains in light mode), so I think this might be an issue with that app.config setup. Maybe you need to test it in a built app and not Expo Go?

**Comment by wcastand** [comment]
so i investigated a bit more today and found out it was probably an issue with expo. between expo go and expo-dev

i made an issue on the expo repo

https://github.com/expo/expo-cli/issues/4495

**Comment by charliecruzan-stripe** [comment]
thanks!
