### ISSUE TITLE
Android app crashes after clicking on CardField input

### ISSUE THREAD

**Issue by shubham-snake** [stripe/stripe-react-native#1061]
{
"name": "MusingooApp",
"version": "0.0.1",
"private": true,
"scripts": {
"android": "react-native run-android",
"ios": "react-native run-ios",
"start": "react-native start",
"test": "jest",
"lint": "eslint ."
},
"repository": {
"type": "git",
"url": "git+https://github.com/muhaimenul/musingoo-app.git"
},
"dependencies": {
"@ptomasroos/react-native-multi-slider": "^2.2.2",
"@react-native-community/async-storage": "^1.12.1",
"@react-native-community/clipboard": "^1.5.1",
"@react-native-google-signin/google-signin": "^7.2.2",
"@react-native-picker/picker": "^1.9.4",
"@stripe/stripe-react-native": "^0.15.0",
"@twotalltotems/react-native-otp-input": "^1.3.11",
"axios": "^0.26.0",
"rc-slider": "^9.6.1",
"react": "17.0.1",
"react-dom": "^17.0.1",
"react-native": "0.64.0",
"react-native-calendars": "^1.943.0",
"react-native-camera": "^3.40.0",
"react-native-elements": "^3.0.0-alpha.1",
"react-native-fbsdk-next": "^7.0.0",
"react-native-gesture-handler": "^1.9.0",
"react-native-google-places-autocomplete": "^2.4.1",
"react-native-image-picker": "^3.1.3",
"react-native-linear-gradient": "^2.5.6",
"react-native-loading-spinner-overlay": "^2.0.0",
"react-native-maps": "^0.31.1",
"react-native-modal": "^11.5.6",
"react-native-paper": "^4.11.2",
"react-native-phone-number-input": "^2.0.0",
"react-native-popup-dialog": "^0.18.3",
"react-native-popup-menu": "^0.15.9",
"react-native-progress": "^4.1.2",
"react-native-radio-buttons-group": "^2.2.10",
"react-native-ratings": "^7.3.0",
"react-native-reanimated": "^1.13.1",
"react-native-router-flux": "^4.2.0",
"react-native-screens": "^2.12.0",
"react-native-shadow": "^1.2.2",
"react-native-simple-toast": "^1.1.3",
"react-native-snap-carousel": "^3.9.1",
"react-native-storage": "^1.0.1",
"react-native-timeline-flatlist": "^0.7.3",
"react-native-vector-icons": "^7.1.0",
"react-native-video": "^5.1.0-alpha8",
"react-redux": "^7.2.6",
"redux": "^4.1.2",
"redux-devtools-extension": "^2.13.9",
"redux-thunk": "^2.4.1"
},
"devDependencies": {
"@babel/core": "7.12.3",
"@babel/runtime": "7.12.1",
"@react-native-community/eslint-config": "1.1.0",
"babel-jest": "25.5.1",
"eslint": "6.8.0",
"jest": "25.5.4",
"metro-react-native-babel-preset": "0.59.0",
"react-test-renderer": "16.13.1"
},
"author": "Muhaimenul Islam [i.muhaimen@gmail.com](mailto:i.muhaimen@gmail.com)",
"jest": {
"preset": "react-native"
}
}

buildscript {
ext {
buildToolsVersion = "30.0.3"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 31
kotlin_version = '1.3.50'
}
repositories {
google()
// jcenter()
gradlePluginPortal()
}
dependencies {
classpath('com.android.tools.build:gradle:4.1.1')
classpath 'com.android.tools.build:gradle:4.1.1'
// NOTE: Do not place your application dependencies here; they belong
// in the individual module build.gradle files
}
}

**Comment by charliecruzan-stripe** [comment]
Closing because we require bug reports to follow the issue template we provide. Happy to reopen if you can edit the above to provide all the information we ask for in our issue template!

Otherwise, i would recommend looking through the android logs with `adb logcat` and searching for "fatal"
