### ISSUE TITLE
Card corrupt when saving more than 4 credit/debit cards

### ISSUE THREAD

**Issue by vimukthinuclei** [stripe/stripe-react-native#1063]
**Describe the bug**
When saving more than 4 cards from CardField, saved cards get corrupted. Can't use the cards after saving more than 4 cards. But when delete some cards and get the list back to 4 cards, it'll start to work.

**To Reproduce**
Add more than 4 cards from cardFiled and check the saved cards list (paymentMethods).

**Expected behavior**
This list should load as usual time and could be able to do the payments without any issue.

**Desktop (please complete the following information):**
 - OS: IOS and android
 - Version 0.2.3

**Smartphone (please complete the following information):**
 - Device: All devices
 - OS: All OS

**Comment by charliecruzan-stripe** [comment]
Please provide the code you're using to reproduce this problem

**Comment by vimukthinuclei** [comment]
client_secret is missing from paymentMethods when saved more than 4 cards

```js
const handlePayment = async method => {
    if (!method.client_secret) {
      Alert.alert('400', 'Please re add payment method');
      return;
    }
    const { paymentIntent, error } = await retrievePaymentIntent(
      method.client_secret,
    );

    if (error) {
      Alert.alert(`Error: ${error.code}`, error.message);
    } else if (paymentIntent?.lastPaymentError) {
      // Default to a generic error message
      let failureReason = 'Payment failed, try again.';
      if (paymentIntent?.lastPaymentError?.type === 'Card') {
        failureReason = paymentIntent.lastPaymentError.message;
      }
      Alert.alert(failureReason);
    } else {
      const paymentData = {
        payment_from: user._id,
        amount: job_reward * 100,
      };
      dispatch(addToken(paymentData)).then(resp => {
        if (resp) {
          dispatch(userInfo());
          dispatch(getTransactionHistoryList(1));
          navigation.navigate('AddTokenSuccess', { job_reward });
        }
      });
    }
  };

<PaymentMethods
  paymentMethods={paymentSheet.paymentMethods}
  onPay={method => {
    setActivePaymentMethod(method);
  }}
  filterLoading={load => setFilterFLoading(load)}
/>
<Button
  title={'Pay with Selected Card'}
  color={BUTTON_COLOR_CATEGORY.PINK}
  styleButton={styles.PWSCBtn}
  onPress={() => handlePayment(activePaymentMethod)}
/>

```

**Comment by charliecruzan-stripe** [comment]
I can't really say what's happening here without knowing what's happening in the `PaymentMethods` component. Can you explain why you think this is a bug in the Stripe SDK?

**Comment by vimukthinuclei** [comment]
`PaymentMethods` is only a component for display the saved cards. Simple UI nothing handling in there.

**Comment by charliecruzan-stripe** [comment]
@vimukthinuclei it looks like you're trying to pass a paymentmethod to `retrievePaymentIntent`, which is meant for retrieving payment **intents**, not payment methods. 

Your issue state that "when saving more than 4 cards from CardField, saved cards get corrupted", but the code you shared doesn't contain any logic for saving cards or using CardField
