### ISSUE TITLE
Google Pay Button In PaymentSheet not compliant with Google Brand Guidelines

### ISSUE THREAD

**Issue by P-Russell** [stripe/stripe-react-native#1068]
**Is your feature request related to a problem? Please describe.**
Our integration is not being approved because the google pay button in our app does not meet Google's brand guidelines

Screen shot of payment sheet using the latest version

![GPay-button](https://user-images.githubusercontent.com/16173883/181782456-faf3f0f9-d42a-480c-8610-e495f42bb940.jpg)

New brand guidlines

<img width="221" alt="Screenshot 2022-07-29 at 16 32 57" src="https://user-images.githubusercontent.com/16173883/181782649-abc55ba6-fb2d-4e01-9d5c-450389ce177f.png">

https://developers.google.com/pay/api/android/guides/brand-guidelines#style

**Comment by charliecruzan-stripe** [comment]
thanks! this is in progress now :)

**Comment by P-nReality** [comment]
Thank you

**Comment by remonh87** [comment]
@charliecruzan-stripe  I noticed also the google pay button (not in the payment sheet ) is not compliant. Do you want me to create a separate ticket for that one or will you fix it along with this one?

**Comment by charliecruzan-stripe** [comment]
We just fixed this in payment sheet in `stripe-android`, so pulling in that fix today!

**Comment by charliecruzan-stripe** [comment]
Released in [0.19.0](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0190---2022-09-16)

**Comment by tthongprasert** [comment]
Hi @charliecruzan-stripe 

I'm currently using React Native Expo and the library version

 "expo": "46.0.10",
 "@stripe/stripe-react-native": "0.13.1"

It seems that the Google Pay button hasn't been updated yet.
When I created the Google Pay button from `import { GooglePayButton } from '@stripe/stripe-react-native'.`
I still got the old style which is not compliant with Google Brand Guidelines.

How should I do?


Thank you in advance

**Comment by charliecruzan-stripe** [comment]
You'll need to upgrade to v0.19.0 - https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0190---2022-09-16--expo-sdk-47

**Comment by tthongprasert** [comment]
Thanks @charliecruzan-stripe 

Does this mean I have to upgrade Expo SDK from 46 to 47 as well?

**Comment by srushtiCloudus** [comment]
google pay button is not displaying in my bottom sheet i add.
 await Stripe.instance
          .initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          paymentIntentClientSecret: clientSecret,
          style: ThemeMode.light,
          merchantDisplayName: 'Student Bro',
          googlePay: const PaymentSheetGooglePay(
            merchantCountryCode: 'GB',
            currencyCode: 'GBP',
            testEnv: true
          ),
        ),
      )
      this code
