### ISSUE TITLE
'BankAccount' type is not supported yet

### ISSUE THREAD

**Issue by eesttiwar** [stripe/stripe-react-native#1070]
When I try to use the createToken following the example here https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/CreateTokenScreen.tsx the error returned is the following:  Error code: Failed BankAccount type is not supported yet.

This is my code:
const tokenCreate = async() => {

        const data: any = {
            type: 'BankAccount',
            accountHolderName: 'Jenny Rosen',
            accountHolderType: 'individual',
            accountNumber: '000123456789',
            country: 'US',
            currency: 'usd',
            routingNumber: '110000000',
        }
        
        const { error, token } = await createToken(data);

        if (error) {
          console.log(`Error code: ${error.code}`, error.message);
          console.log(`Error: ${JSON.stringify(error)}`);
        } else if (token) {
          console.log(
            'Success',
            `The token was created successfully! token: ${token.id}`
          );
        }
        
    }

In addition, when I try to do the Token import 
import type {Token} from '@stripe/stripe-react-native';
I get this other error: Module "'@stripe/stripe-react-native'" has no exported member 'Token'.

What could be the error?

Thank you very much in advance

**Comment by charliecruzan-stripe** [comment]
what version of stripe-react-native are you using?

**Comment by eesttiwar** [comment]
> what version of stripe-react-native are you using?

0.1.2 because if I use the current one, it did not raise the application.

**Comment by charliecruzan-stripe** [comment]
Ah yeah, this functionality was added in v0.2.4: https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#024---2022-02-10, so you'll need to upgrade to at least that version to be able to use that feature

**Comment by eesttiwar** [comment]
> Ah yeah, this functionality was added in v0.2.4: https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#024---2022-02-10, so you'll need to upgrade to at least that version to be able to use that feature

You are absolutely right, I updated to the version you told me and it works. Thank you very much.
