### ISSUE TITLE
play-services-tapandpay (private repo) prevents instrumented test builds from compiling

### ISSUE THREAD

**Issue by jfspencerAngel** [stripe/stripe-react-native#1071]
**Describe the bug**

when running the below command, `[com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom](https://repo.maven.apache.org/maven2/com/google/android/gms/play-services-tapandpay/17.1.2/play-services-tapandpay-17.1.2.pom)` is exposed which is not a publicly available repo, preventing e2e test builds from compiling

    ./gradlew assembleDebug assembleAndroidTest

**To Reproduce**
1. perform standard stripe sdk integration for React Native Android
2. run `./gradlew assembleDebug assembleAndroidTest`

**Expected behavior**
The app should compile

**Screenshots**
N/A compile issue 

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5a 
 - OS: Android
 - Version: 8-12 (tested)

**Additional context**

**Comment by charliecruzan-stripe** [comment]
Can you upgrade to either 0.15.0 or 0.16.0 and see if the problem persists? I'm having trouble reproducing on the most recent version

**Comment by jfspencerAngel** [comment]
@charliecruzan-stripe thanks for the quick response. Updating to 0.16.0 gets past the tapandpay dependency error, but I am now not able to build via this command, due to the auth0 manifest, which leverages manifestPlaceholders, is not able to find the placeholders defined in the app build.gradle

    `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`

getting this failure response

```
> Task :react-native-auth0:processDebugAndroidTestManifest FAILED
/Users/angel/Developer/angel-app-react-native/node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest851743200978188818.xml Error:
        Attribute data@host at tempFile1ProcessTestManifest851743200978188818.xml requires a placeholder substitution but no value for <auth0Domain> is provided.
/Users/angel/Developer/angel-app-react-native/node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest851743200978188818.xml Error:
        Attribute data@scheme at tempFile1ProcessTestManifest851743200978188818.xml requires a placeholder substitution but no value for <auth0Scheme> is provided.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```

**Comment by charliecruzan-stripe** [comment]
Glad you got past the Stripe build error! However, I'm not sure this new one is a problem with `stripe-react-native`. If you remove stripe-react-native, that error goes away? 

Looks like [that error has been asked about on auth0's repo](https://github.com/auth0/react-native-auth0/issues/387)

**Comment by jfspencerAngel** [comment]
thanks @charliecruzan-stripe this is what I needed. adding the following to `./android/build.gradle` addresses the issue

```
subprojects {
    afterEvaluate { subproject ->
        if (subproject.name == 'react-native-auth0') {
            def String taskRequests = getGradle().getStartParameter().getTaskRequests().toString()
            if (taskRequests.contains("assembleAndroidTest")) {
                android {
                    defaultConfig {
                        manifestPlaceholders = [auth0Domain: "E2E_TEST", auth0Scheme: "com.E2E.TEST"]
                    }
                }
            }
        }
    }
}
```
