### ISSUE TITLE
Facing error in android build run

### ISSUE THREAD

**Issue by pankajsoftyoi** [stripe/stripe-react-native#1073]
/.gradle/caches/transforms-3/06075525d7c59fa3b2cbf9d0614304ea/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.1.

getting this error while run android build after integrate stripe-react-native in app.

Here is build.gradle file detail:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

```
buildscript {
    ext {
        kotlinVersion = "1.4.20"
        RNNKotlinVersion = kotlinVersion
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath('com.android.tools.build:gradle:4.0.2')
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.10, 0.99.99]'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        maven {
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://maven.google.com' }
        maven { url 'https://maven.zohodl.com' }
        jcenter()
    }
}

```

Please let me know if any solution.

**Comment by charliecruzan-stripe** [comment]
Can you try upgrading your kotlin version? Also, your `compileSdkVersion` is too low, see https://github.com/stripe/stripe-react-native#android

**Comment by charliecruzan-stripe** [comment]
Closing since this looks to be due to a mismatched kotlin version, not an issue with `stripe-react-native` (but to reiterate- after upgrading your kotlin version, the build will still fail since your `compileSdkVersion` is too low (see readme link above)
