### ISSUE TITLE
Google Pay: Wrong documentation

### ISSUE THREAD

**Issue by antoinerousseau** [stripe/stripe-react-native#1076]
After following https://stripe.com/docs/google-pay?platform=react-native#going-live-react-native

## Android setup

Follow up of #866

This line is required in `AndroidManifest.xml`:
```xml
<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
```

(it's present in [the Android tab](https://stripe.com/docs/google-pay?platform=android) but should also be in the React Native tab)

## Going live with Google Pay

Follow up of #730

It says to "reach out to Google support" but that support is hard to find and it seems that the right step is to register at https://pay.google.com/business/console/ instead (my app is now pending review, I'll update this issue once done)

### Merchant ID

The Google Pay & Wallet business console gives a merchant ID, but it seems that there is nowhere in Stripe React Native to set it, is it normal? If so, maybe add a note about this in the doc

**Comment by charliecruzan-stripe** [comment]
thanks!

**Comment by charliecruzan-stripe** [comment]
Will be fixed soon, separate repo so closing this out :)

**Comment by JaLe29** [comment]
Hi,

can some one share clear way how to go live with Google pay?

I am getting an error `OR_BIBED_07` I found X issues about this problem but without any working result.

**Comment by antoinerousseau** [comment]
@JaLe29 is your app validated? at https://pay.google.com/business/console/

**Comment by JaLe29** [comment]
Nope,..

There is a Screenshots of your buyflow section. 

They need image of Payment method screen and Google Pay API payment screen but I cant share it because I can get it in my app because of error.


https://user-images.githubusercontent.com/22296816/197207599-24efb6ee-c57b-4f82-b0d3-94a0ea6cf115.mp4

**Comment by antoinerousseau** [comment]
They don't want a screencast of the full flow, they just want screenshots of the pay button integration (without having to press it)

**Comment by antoinerousseau** [comment]
It's linked by just being the same product bundle ID in that console than in your app (e.g. `com.example.yourapp`) 
For the implementation, just follow Stripe's documentation
https://stripe.com/docs/google-pay?platform=react-native
```ts
import {
  createGooglePayPaymentMethod,
  presentGooglePay,
  useGooglePay,
} from "@stripe/stripe-react-native";
```
