### ISSUE TITLE
App build none code zero exit

### ISSUE THREAD

**Issue by hai-ru** [stripe/stripe-react-native#1080]
**Describe the bug**
I just install react native stripe with yarn and pod install as procedure. after that try to run debug in xcode but always give me error none zero exit code

**To Reproduce**
1.  install stripe with yarn
2.  pod install
3.  open xcode
4.  click run

**Expected behavior**
Can run succesfull.

**Screenshots**

![build stripe](https://user-images.githubusercontent.com/24634668/183564971-039c734b-49ad-4112-9beb-b4c980bdf7bb.PNG)

**Desktop (please complete the following information):**
 - OS: Monterey 12.2.1
 - Xcode Version 13.4.1
 - Macbook air m1 2020 
 - Rosetta is on for xcode and simulator

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone 13
 - OS: iOS 15.5

**Additional context**
I used react native stripe version "@stripe/stripe-react-native": "^0.16.0",
React Native Version  "react-native": "0.68.2",

**Comment by hai-ru** [comment]
for now I fixed the issue with upgrading swift version compiler in xcode
![Capture](https://user-images.githubusercontent.com/24634668/183567969-a3bba2c9-90b5-4e27-bf05-20e1b682b1f5.PNG)

and this is work !

**Comment by charliecruzan-stripe** [comment]
What version of Swift were you using before? 

Closing since this, upgrading to Swift 5 resolves the issue :)
