### ISSUE TITLE
on Android 

### ISSUE THREAD

**Issue by shikhars371** [stripe/stripe-react-native#1081]
Payment confirmation error {"code": "Failed", "declineCode": null, "localizedMessage": "Card details not complete", "message": "Card details not complete", "stripeErrorCode": null, "type": null}

please help me with above error on android only:

here is my code:

const billingDetails: BillingDetails = {
      email: account?.email,
      phone: account?.phoneNumber,
      address: {
        postalCode: postalCode,
      },
    };

    console.log("paymentResp sectre", client_secret.toString());
    //  setLoading(true)

    const { error, paymentIntent } = await confirmPayment(
      client_secret,
      {
        paymentMethodType: 'Card',
        paymentMethodData: {
          billingDetails,
        },
      }
    );

giving error on confirm payment only on android , on IOS its working fine

**Comment by charliecruzan-stripe** [comment]
it's likely that the `CardField` or CardForm` haven't been fully filled out. Check the onCardChanged callback (specifically the `complete` field)

**Comment by jsam6** [comment]
```
              onCardChange={cardDetails => {
                if (cardDetails.complete) {
                    handlePayment()
                }
              }}
```

Despite `cardDetails.complete == true` , `confirmPayment` still returns `{"error": {"code": "Failed", "declineCode": null, "localizedMessage": "Card details not complete", "message": "Card details not complete", "stripeErrorCode": null, "type": null}}`
