### ISSUE TITLE
Appearance does not change when using a setupIntent on my own personal device through expo go?

### ISSUE THREAD

**Issue by McKayMower** [stripe/stripe-react-native#1083]
@stripe/stripe-react-native: "^0.6.1"
react-native: "0.68.2"
expo: "~45.0.0"
iPhone 13 Pro Max (My own Device)

I am trying to get the appearance of initPaymentSheet working with a setupIntent. I get the customerID, ephemeralKey, and setupIntent from my server. However, the appearance does not change at all, and I have tried just about everything before asking this question. Is this because I am using my own device? Am I setting appearance correctly as there is a lot of map nesting? Simply just setting the primary colors of the payment sheet is not working. 

Suggestions/solutions will be much appreciated!

Refer to code below, please ask questions if you have any:

```
const { setupIntent, ephemeralKey, customerID } = res.data;
        await` initPaymentSheet({
          customerId: customerID,
          setupIntentClientSecret: setupIntent,
          customerEphemeralKeySecret: ephemeralKey,
          defaultBillingDetails: billingDetails,
          appearance: {
            colors: {
              light: { primary: "#ffffff" },
              dark: { primary: "#ffffff" },
            },
          },
        }).then(...).catch(...)
```

**Comment by charliecruzan-stripe** [comment]
Hi! Support for the `appearance` param was added in [v0.11.0](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0110---2022-05-24). Other than using too old a version, it looks like you're doing everything else right 👍

**Comment by charliecruzan-stripe** [comment]
FYI- SDK 46 relies on `@stripe/stripe-react-native` v0.13.1, so you can use appearance in SDK 46

**Comment by McKayMower** [comment]
Holy cow, thanks a bunch!
