### ISSUE TITLE
How to buy product by quantity within mobile app(React Native) without redirect to web page.

### ISSUE THREAD

**Issue by dev1ninja** [stripe/stripe-react-native#1089]
I would like to buy product by quantity.
If I use checkout session, it gave me session url.
So I should redirect to web page from my mobile app.
This is not good  way for the mobile app.
I would like to buy product by quantity within my app like presentPaymentSheet.

So my idea is to add qty and product details into presentPaymentSheet.

**Comment by charliecruzan-stripe** [comment]
Hi! You'll need to use a [payment intent](https://stripe.com/docs/payments/payment-intents) in order to use Payment Sheet for your purchase flow
