### ISSUE TITLE
You must provide paymentMethodType - createPaymentMethod Expo issue

### ISSUE THREAD

**Issue by savkevip** [stripe/stripe-react-native#1093]
I have an issue with `createPaymentMethod` 

my implementation:
```
const stripe = useStripe();

const responsePaymentMethod = await stripe.createPaymentMethod({
  paymentMethodType: 'Card',
  paymentMethodData: {
    billingDetails: {
      name: fullName,
      phone,
    },
  },
});
```

and the output is:
`"error": Object {
      "code": "Failed",
      "declineCode": null,
      "localizedMessage": "You must provide paymentMethodType",
      "message": "You must provide paymentMethodType",
      "stripeErrorCode": null,
      "type": null,
  },`
  
version: `"@stripe/stripe-react-native": "^0.16.0",`  
  
am I missing something? :)

**Comment by johnnymichaelnohra** [comment]
I'm having the same issue... :( 
version: "@stripe/stripe-react-native": "^0.18.1"

**Comment by charliecruzan-stripe** [comment]
Hi! Is this on Android or iOS? 

I tested this myself on 0.16.0 and it's working correctly on both, so my guess is maybe you're using Expo and have a version installed that is not compatible with your SDK version. Make sure you're installing the library with `expo install`

**Comment by johnnymichaelnohra** [comment]
Hey, this is on iOS, I just uninstalled @stripe/stripe-react-native and re-installed using expo install, no change. Should I try downgrading to 0.16.0?

Thanks for the fast reply!

**Comment by charliecruzan-stripe** [comment]
Yeah, that's correct. Long story short- you're relying on different versions of `@stripe/stripe-react-native` for Javascript and the native code, so there's a mismatch. Expo's newest SDK supports v0.13.1 - https://github.com/expo/expo/blob/sdk-46/packages/expo/bundledNativeModules.json#L11

**Comment by johnnymichaelnohra** [comment]
Hey, just upgraded my Expo version to the latest one and downgraded `@stripe/stripe-react-native` to v0.13.1, still giving me the same error :/

**Comment by charliecruzan-stripe** [comment]
Okay, please provide a reproducible demo via a GH repo or something like that

**Comment by savkevip** [comment]
Thank you for the hints :) I fixed this with the following steps:

1. remove `yarn.lock` / `package-lock.json`
2. remove `node_modules`
3. then run `yarn` / `npm i` to install packages again
4. and on end run `expo upgrade`

but now I have a new error :D

`{"code": "Failed", "declineCode": null, "localizedMessage": "Your card was declined", "message": "Your card was declined", "stripeErrorCode": null, "type": null}`

for test card `4242 4242 4242 4242` any hint? :)

**Comment by charliecruzan-stripe** [comment]
hm you might be able to take a look at that in the stripe dashboard and see if there are more details there in the attempted payment intent. One thing would be to make sure you're in test mode!

**Comment by savkevip** [comment]
au, you were right! what a rookie mistake 😄  I trigger it with `live` publish key not `test`. It's working now like expected. Thank you a lot. 🙌

**Comment by maxizhukov** [comment]
I have same issue after updating to expo 46.0.0 and updated @stripe/stripe-react-native to 0.18.1

Before everything was working with:
const paymentMethod:any = await createPaymentMethod({ type: "Card" });

Now it show error: "localizedMessage": "You must provide paymentMethodType"

**Comment by maxizhukov** [comment]
Sorry, fixed it by changing createPaymentMethod to:


`const paymentMethod:any = await createPaymentMethod({
			paymentMethodType: 'Card'
		});`

**Comment by shasnk** [comment]
I am still having the 

Payment confirmation error {"code": "Failed", "declineCode": null, "localizedMessage": "You must provide paymentMethodType", "message": "You must provide paymentMethodType", "stripeErrorCode": null, "type": null}

Though I provided exactly what stripe said in docs .Please help me regarding it .

const createStripe_ID = async(Detail_client)=>{
          
        console.log(cardDetails,'cardDetails')
 
        let name = 'test'
             console.log("CardDetailsssssss", Detail_client)
                 const {paymentIntent, error}  =  await   confirmPayment(Detail_client, { 
           
            
                paymentMethodType:'Card',
                paymentMethodData: {
                             cardDetails
                    

                },
          }, 
        
        )
       if (error) { 
        console.log('Payment confirmation error', error);
     } else if (paymentIntent) { 
        console.log('Success from promise', paymentIntent); 
    }
I have checked my methods and console , It come till this methods and give me the error . My versions are "@stripe/stripe-react-native": "^0.2.3",
    "react": "17.0.1",
    "react-native": "0.64.2",

android gradle 
buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30

**Comment by DomVournias** [comment]
This worked for me:

`const { paymentIntent, error } = await confirmPayment(clientSecret, {
          paymentMethodType: "Card", // chaning the card to capitalized Card did the trick
          billingDetails: billingDetails,
        });`

**Comment by cpimentel25** [comment]
Same issues:
`"code": "Failed", "declineCode": null, "localizedMessage": "The provided key 'pk_test_*********************************************************************************************CiaOFS' does not have access to account '' (or that account does not exist). Application access may have been revoked.", "message": "The provided key 'pk_test_*********************************************************************************************CiaOFS' does not have access to account '' (or that account does not exist). Application access may have been revoked.", "stripeErrorCode": null, "type": null}
`

my code component:

```
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import React, { useEffect, useState } from "react";
import checkoutStore from "store/checkout-store";
import { usePayment } from "hooks/usePayment";
import { colors } from "constants/Colors";
import { useGlobalStyles } from "hooks/useGlobalStyles";
import { CardField, useStripe } from "@stripe/stripe-react-native";

export default function Checkout() {
  const { createPaymentMethod } = useStripe();
  const { stateCheckout } = checkoutStore();
  const { initializePaymentSheet, openPaymentSheet, createTransfer } =
    usePayment();

  const { containerStyles } = useGlobalStyles();

  const [amount, seTamount] = useState<number>(0);
  const [cardDetails, setCardDetails] = useState<Object | null>(null);
  const [paymentData, setPaymentData] = useState<Object | any>({
    currency: "usd",
    transferGroup: "TEST00123",
    merchantDisplayName: "NGTEST",
  });

  useEffect(() => {
    const priceFormat: string | any = stateCheckout.price;
    const cleanedString = priceFormat.replace(/[^0-9.,]/g, "");
    const priceNum = parseFloat(cleanedString);
    seTamount(priceNum);
  }, []);

  const handlePayment = async () => {
    if (!cardDetails) {
      console.error("No card details provided");
      return;
    }

    const billingDetails = {
      name: "cpdev",
      email: "cpdev@test.dev",
    };

    const { paymentMethod, error } = await createPaymentMethod({
      paymentMethodType: "Card",
      paymentMethodData: {
        billingDetails: billingDetails,
      },
    });

    if (error) {
      console.error("Error paymenth method create:");
      console.error(error);
    } else if (paymentMethod) {
      const paymentMethodId = paymentMethod.id;
      const initialPayment = await initializePaymentSheet(
        amount,
        paymentData.currency,
        paymentData.transferGroup,
        paymentData.merchantDisplayName,
        paymentMethodId
      );
    }

    // await openPaymentSheet();
    // const transfer = await createTransfer();
  };

  return (
    <View style={[containerStyles, { justifyContent: "space-between" }]}>
      <Text style={{ color: colors.white }}>Checkout</Text>

      <View>
        <CardField
          postalCodeEnabled={false}
          placeholders={{ number: "4242 4242 4242 4242" }}
          cardStyle={{ textColor: colors.black, backgroundColor: colors.white }}
          style={{
            height: 50,
            marginVertical: 30,
          }}
          onCardChange={setCardDetails}
          onFocus={(focusedField) => {
            console.log("focusField", focusedField);
          }}
        />
      </View>

      <View>
        <TouchableOpacity style={styles.btn} onPress={handlePayment}>
          <Text
            style={{ color: colors.black, textAlign: "center", fontSize: 22 }}
          >
            Pay {stateCheckout.price}
          </Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  btn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: colors.yellow,
    marginVertical: 60,
  },
});
```
