### ISSUE TITLE
Apple pay not working 

### ISSUE THREAD

**Issue by december1990** [stripe/stripe-react-native#1094]
hi. I enabled apple pay based on the doc, created merchant, added in xcode, and stripe dashboard, and apple pay button is showing up but when I tap the apple pay button, the payment sheet closes and nothing happens. using version 0.5 of the package.

**Comment by december1990** [comment]
the problem was that, I'd mistakenly written the wrong value for merchantCountryCode.

**Comment by charliecruzan-stripe** [comment]
Thanks for following up @december1990!
