### ISSUE TITLE
CardField: postalCodeEnabled is by default true

### ISSUE THREAD

**Issue by vivekvardhanadepu** [stripe/stripe-react-native#1098]
In [CardField.tsx](https://github.com/stripe/stripe-react-native/blob/master/src/components/CardField.tsx), it says ` Controls if a postal code entry field can be displayed to the user. Defaults to false. If true, the type of code entry shown is controlled by the set countryCode prop. Some country codes may result in no postal code entry being shown if those countries do not commonly use postal codes. If false, no postal code entry will ever be displayed. ` But, it is defaulting to `true`. Need to explicitly give it `false`.

**Comment by charliecruzan-stripe** [comment]
Thanks! this was simply mis-documented, fixed in https://github.com/stripe/stripe-react-native/commit/37e9a50936fb6f1e2279cbb4cc76a81e2ec7ed11
