### ISSUE TITLE
How can I run the example project?

### ISSUE THREAD

**Issue by gran33** [stripe/stripe-react-native#1100]
**Describe the bug**
No instruction for running the example project

**To Reproduce**
1. Try to run the example project :)
**Expected behavior**
Make it run
**Screenshots**
I wish
**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 104.0.5112.79 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Simulator
 - OS: iOS15.5
 - Browser N/A
 - Version N/A
 - 
**Additional context**

**Comment by charliecruzan-stripe** [comment]
we have a guide on this in the contributing.md doc :) https://github.com/stripe/stripe-react-native/blob/master/CONTRIBUTING.md#running-the-example-app
