### ISSUE TITLE
Bank redirect authorization page does not redirect to app

### ISSUE THREAD

**Issue by Ricckkzero** [stripe/stripe-react-native#1101]
Hello there! Thank you for taking the time to read about my issue and hopefully someone can provide some help.

**Describe the issue**
I went through all steps described to setup stripe in my app here: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-fulfillment. 

In short: I am trying to make payments by using bank redirects. However, after the `Authorize test payment` button is clicked it does not automatically redirect back into my app. Instead, it starts loading and finishes loading but stays on the page without changing anything. In my console logs it shows the redirect link through the event listener though.. (with some other information that it returns) When I reload the page, it actually shows that the test payment was completed. When I close the test payment page, it tells me the order was successful.

- Backend is there
- Checkout screen and components are there
- urlScheme is there
- return url is there
- React native deeplinks/universal link is setup for iOS (added the necessary parts to AppDelegate.mm)
- Eventlistener for react native linking is working (it actually received the link when a successful transaction was done)
This is what I received through the event listener:
```
 myapp://home?payment_intent=*removed*&payment_intent_client_secret=*removed*&redirect_status=succeeded
```

My app is using react navigation v5 and I've tested deep links to be sure those are actually working. Also, when I manually close the stripe page it navigated to the correct page. This tells me that linking is working fine..

**Versions**
App:
react-native: 68.2
@stripe/stripe-react-native: 0.18.1

Server:
stripe: 10.4.0

**Code**
Here's the code I am using:

Provider:

`<StripeProvider
      publishableKey="key"
      urlScheme="myapp"
      merchantIdentifier="merchant.com.myapp">`

Initialise:
```const initializePaymentSheet = async () => {
    const {paymentIntent, ephemeralKey, customer} = await fetchPaymentSheetParams();

    const {error} = await initPaymentSheet({
      merchantDisplayName: 'myapp',
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,
      allowsDelayedPaymentMethods: true,
      returnURL: 'myapp://home',
    });

    if (error) {
      // do something
    }
  };
```

Open payment sheet

```
const openPaymentSheet = async () => {
      const {error, paymentOption} = await presentPaymentSheet();
      if (error) {
        Alert.alert(`Error code: ${error.code}`, error.message);
      } else {
        Alert.alert('Success', 'Your order is confirmed!');
      }
  };
```

Used in something similar to app.tsx

``` 
const {handleURLCallback} = useStripe();

  const handleDeepLink = useCallback(
    async (url: string | null) => {
      if (url && url.includes('safepay')) {
        await handleURLCallback(url);
        // Add extra handling here as you see fit
      }
    },
    [handleURLCallback],
  );

  useEffect(() => {
    const getUrlAsync = async () => {
      const initialUrl = await Linking.getInitialURL();
      handleDeepLink(initialUrl);
    };

    getUrlAsync();

    const deepLinkListener: any = Linking.addEventListener('url', (event: {url: string}) => {
      handleDeepLink(event.url);
    });

    return () => deepLinkListener.remove();
  }, [handleDeepLink]);
```

initialUrl is always null btw.. Even when I am running without debugger.

Server:
```
app.post('/checkout', async (req, res) => {
  // Create or retrieve the Stripe Customer object associated with your user.
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', {
    apiVersion: '2022-08-01',
    typescript: true,
  });

  const customer = await stripe.customers.create(); // This example just creates a new Customer every time

  // Create an ephemeral key for the Customer; this allows the app to display saved payment methods and save new ones
  const ephemeralKey = await stripe.ephemeralKeys.create(
    {customer: customer.id},
    {apiVersion: '2022-08-01'},
  );

  // Create a PaymentIntent with the payment amount, currency, and customer
  const paymentIntent = await stripe.paymentIntents.create({
    amount: 973,
    currency: 'eur',
    customer: customer.id,
    automatic_payment_methods: {
      enabled: true,
    },
  });

  res.json({
    paymentIntent: paymentIntent.client_secret,
    ephemeralKey: ephemeralKey.secret,
    customer: customer.id,
  });
});
```

**Expected behavior**
I expect the bank redirect authorization page to redirect to my app.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 15.5

Thanks again and really looking forward to solutions here.

**Comment by charliecruzan-stripe** [comment]
Hi @Ricckkzero ! Thanks for the very thorough bug report, it made this super easy to look into. 

The issue here is that the URL you're getting **is** an actionable Stripe return URL, but because of the `url.includes('safepay')` expression, we're never passing the url to `handleURLCallback`. I understand that that logic is exactly what's in the documentation, so it totally makes sense that that's what you've got in your app. 

The `handleURLCallback` function actually resolves to a boolean value indicating whether or not Stripe was able to handle the URL, so could you try changing your JS code like this:

```diff
const handleDeepLink = useCallback(
    async (url: string | null) => {
-      if (url && url.includes('safepay')) {
-        await handleURLCallback(url);
+      if (url) {
+        const stripeHandled = await handleURLCallback(url);
         // Add extra handling here as you see fit
+        // If stripeHandled is false, this was NOT a Stripe URL and we received a deep link from somewhere else
        }
    },
    [handleURLCallback],
  );
```

**Comment by Ricckkzero** [comment]
@charliecruzan-stripe that was the issue indeed! Now that you shared it, it totally makes sense!

In what case would it have to include 'safepay' (or something similar)? Would it be wise to include this part in the deeplink or check for a certain path so that we are sure it comes from stripe? This last question also relates to the comment you made I think:

```
// If stripeHandled is false, this was NOT a Stripe URL and we received a deep link from somewhere else
```
I take this could result in a potential security threat if not handled correctly? If yes, do you know how to handle this correctly?

Thank you very much for your solution!

**Comment by charliecruzan-stripe** [comment]
`safepay` is added by the Stripe RN SDK, and has so far been used to identify Stripe return URLs. However, this functionality is possible directly from the native SDK (the boolean value that is being resolved from `handleURLCallback`), so we don't really need that check at all, I think. You shouldn't manually append `safepay` to any of your deep links.

> I take this could result in a potential security threat if not handled correctly? 

I don't believe this poses any additional security threat. Stripe either handles the URL if it is recognized as an actionable Stripe redirect URL, or the method does nothing except return `false`. If it returns `false`, then you should handle it however you are handling your deep links (if you don't have any other deep link functionality, then you can just do nothing)
