### ISSUE TITLE
Google pay not showing

### ISSUE THREAD

**Issue by december1990** [stripe/stripe-react-native#1107]
hi. I have used initPaymentSheet and set 
googlePay: true,
testEnv: true, 
merchantCountryCode: 'GB';

I have set test publishable keys as well but can't see the google pay button on the real device, using "@stripe/stripe-react-native": "^0.5.0",;

added <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" /> in  AndroidManifest, 

added 
implementation 'com.google.android.gms:play-services-wallet:18.1.3';
implementation 'com.stripe:stripe-android:19.3.0'
in build.gradle. 

also followed the https://developers.google.com/pay/api/android/guides/setup but nothing happens. 

is it necessary to install google pay app and add a payment method to it in order to show google pay button even in test mode ? 

thnaks

**Comment by charliecruzan-stripe** [comment]
> is it necessary to install google pay app and add a payment method to it in order to show google pay button even in test mode ?



[I believe so](https://developers.google.com/pay/api/android/guides/setup#set-up-your-app-in-your-google-pay-account), yes. Also, you might need to use a physical device and not an emulator

**Comment by Muhammad-Sufian** [comment]
https://stripe.com/docs/google-pay
follow the guides in this page

**Comment by Akshat12042001** [comment]
still having the same issue using initPaymentSheet. I have done all the step including adding text in androidmanifest file . Googlw pay button is not showing

**Comment by nandrew132** [comment]
> still having the same issue using initPaymentSheet. I have done all the step including adding text in androidmanifest file . Google pay button is not showing @charliecruzan-stripe

Hi, Have you solved this problem?
I am running into the same issue.
Thanks

**Comment by shfsakib** [comment]
On my country it is not available that's why googlepaybutton not found I understand. But How can I prevent if not found don't show the button hide it.

**Comment by empiteranga** [comment]
@shfsakib you use something like     
    if (!(await isPlatformPaySupported({googlePay: {testEnv: true}}))) {
      Alert.alert('Google Pay is not supported.');
      return;
    } else {
      console.log('google pay supported');
      Alert.alert('Google Pay is supported.');
    }

**Comment by AppeNik** [comment]
hi please can anyone guide on how to add google pay into app using stripe. I am working as developer but google pay is not supported in Pakistan. And docs say that we need to implement in app subscriptions only through google pay

**Comment by Tieu-Mai-Nhi** [comment]
@december1990 @Akshat12042001 did you fix it? 
I also set params for Google Pay in initPaymentSheet but it still doesn't show Google Pay Button in the form

`   const { error } = await initPaymentSheet({
                        merchantDisplayName: "XXXX",
                        paymentIntentClientSecret: paymentIntent.clientSecret,
                        allowsDelayedPaymentMethods: true,
                        googlePay: {
                            testEnv: true,
                            merchantCountryCode: "UK",
                            currencyCode: "USD",
                            label: "test",
                            amount: "10",
                            buttonType: PlatformPay.ButtonType.Buy
                        }
                        })`
