### ISSUE TITLE
Can not mock useGooglePay with jest

### ISSUE THREAD

**Issue by JperF** [stripe/stripe-react-native#1110]
**Describe the bug**
When attempting to mock `useGooglePay` with `jest` I am getting the following error
```bash
TypeError: Cannot read properties of undefined (reading 'mockImplementation')
```

**To Reproduce**
Attempt to mock `useGooglePay` with the following

```typescript
import { useGooglePay } from '@stripe/stripe-react-native';
...
  const useGooglePayMocked = jest
    .mocked(useGooglePay, true)
    .mockImplementation(() => ({
      isGooglePaySupported: jest.fn(async () => true),
      loading: false,
      initGooglePay: jest.fn(),
      presentGooglePay: jest.fn(),
      createGooglePayPaymentMethod: jest.fn(),
    }));
```

**Expected behavior**
Properly be able to mock `useGooglePay` hook with `jest`.

**Screenshots**
N/A

**Additional context**
I am currently using `"@stripe/stripe-react-native": "0.17.0",`

**Comment by JperF** [comment]
@charliecruzan-stripe thanks for the quick response. I realized this was a misconfiguration with `jest` and nothing to do with the strip lib! 

Closing the issue.

**Comment by KatieBLoop** [comment]
@JperF are you able to share what the configuration fix was for this?? (If you recall). Experiencing the same issue  - Thanks!

**Comment by KatieBLoop** [comment]
UPDATE: We were also missing a config.  From the readme [mentioned above](https://github.com/stripe/stripe-react-native#testing) - adding these two lines to our jestSetupFile.js fixed all issues.

`import mock from '@stripe/stripe-react-native/jest/mock.js';

jest.mock('@stripe/stripe-react-native', () => mock);`
