### ISSUE TITLE
"Remove" button on popup to delete card on PaymentSheet for French app

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-react-native#1115]
The label on the "Remove" button on popup to delete card on PaymentSheet for French app is not translated. The label must to be "Supprimer" like "Annuler" for "Cancel".

![Simulator Screen Shot - iPhone 13 mini - 2022-08-31 at 18 13 03](https://user-images.githubusercontent.com/65358122/187729112-d7069a13-3a4c-4ea0-85fa-fc51cc54824c.png)

**Comment by ramont-stripe** [comment]
Hi @nicolasdevienne,

Thank you for reporting this. Which version of the SDK are you using? I'm not able to reproduce it on the latest version.

<img width="386" src="https://user-images.githubusercontent.com/88752322/187945952-f706c01f-c4c1-4293-81cf-2c09907035c4.png">

**Comment by nicolasdevienne** [comment]
Hi @ramont-stripe! I'm going to upgrade to the last version, sorry :)
My current si version is 0.16.0

**Comment by ramont-stripe** [comment]
Hi @nicolasdevienne, did upgrading solve the localization issue?

**Comment by nicolasdevienne** [comment]
Hi @ramont-stripe, yes perfect! Thx!

**Comment by devbiansor** [comment]
@ramont-stripe Hi, is it possible to change this default alert dialog? We want to customize it
