### ISSUE TITLE
Klarna UI doesn't show "France" in the country list

### ISSUE THREAD

**Issue by minuitagency** [stripe/stripe-react-native#1118]
**Describe the bug**
The country "France" doesn't appear in the available countries list in the Klarna payment method type. 

**To Reproduce**
<img width="436" alt="image" src="https://user-images.githubusercontent.com/38316888/188688005-a10362e1-a7ab-4efa-a144-3226b39b1847.png">

and backend code: 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/38316888/188688122-f4a4ad3c-86f3-4b16-b8bd-b4ef8df9d681.png">

**Smartphone (please complete the following information):**
iPhone 13 Pro Max with the locale set to French and stripe-react-native @0.18.1

Thanks, 

Théo

**Comment by nicolasdevienne** [comment]
Hi @minuitagency ! Maybe you can add this parameter in your initPaymentSheet :
```
        defaultBillingDetails: {
          email: <your_contact_email>,
          address: {
            country: 'FR',
          },
        },
```

**Comment by minuitagency** [comment]
Hi @nicolasdevienne,

Thanks for your help, 

`
          const {error} = await initPaymentSheet({
            customerId: customer,
            customerEphemeralKeySecret: ephemeralKey,
            paymentIntentClientSecret: client_secret,
            returnURL: 'myreturnurl',
            allowsDelayedPaymentMethods: true,
            defaultBillingDetails: {
              email: 'mail@provider.com',
              address: {
                country: 'FR',
              },
            },
          });
`

![image](https://user-images.githubusercontent.com/38316888/189073046-7f16bb2b-75b7-4a73-b816-563730b54ecc.png)

I still don't have access to France... 

Théo

**Comment by charliecruzan-stripe** [comment]
this does look like a bug on iOS, looking into it!

**Comment by charliecruzan-stripe** [comment]
Fixed in the recent releases :)
