### ISSUE TITLE
How the isPending parameter works

### ISSUE THREAD

**Issue by jgalianoz** [stripe/stripe-react-native#1121]
I ask this question as I didn't find documentation on this. I see that adding the **isPending** parameter hides the values ​​from me.

GooglePay supports isPending ?

<img width="303" alt="image" src="https://user-images.githubusercontent.com/12010942/189402141-f446fd1f-cada-443d-b670-9247111638ce.png">

**Comment by charliecruzan-stripe** [comment]
That sets the [PKPaymentSummaryItemType](https://developer.apple.com/documentation/passkit/pkpaymentsummaryitemtype) to pending if true, or final if false. It is not supported in Google Pay.
