### ISSUE TITLE
I need a promptpay feature.

### ISSUE THREAD

**Issue by jinda789** [stripe/stripe-react-native#1122]
promptpay is not supported right now.
Please update this important feature for mobile.

**Comment by charliecruzan-stripe** [comment]
Hi! We don't keep track of payment method feature requests in Github issues, so I'm going to close this. Although we do support Promptpay on [web](https://stripe.com/docs/payments/promptpay/accept-a-payment?platform=web), we don't have a timeline yet for supporting it on mobile
