### ISSUE TITLE
Request to bump podspec to the latest Stripe iOS version

### ISSUE THREAD

**Issue by MarloDelatorre** [stripe/stripe-react-native#1128]
**Describe the bug**
Our app fails to build, see this screen shot:
![image](https://user-images.githubusercontent.com/13562236/190021829-440f94f3-eb41-4604-a164-81e9cf98d3d4.png)

**To Reproduce**
Here's the following setup that causes this error when building:
* `@stripe/stripe-react-native@0.4.0`
* Xcode 14
* Swift version 5.7
* iOS 16

**Expected behavior**
App should build without compiler error

**Additional context**
We've identified the commit that contains the code that fixes the problem: https://github.com/stripe/stripe-ios/commit/a97803ec41ad6bfbc7a5c7d5a657365ff018ba4d#diff-f264211e65891782b617eb55ebd3c6d168c142173337de782ed818c03df23052R86

However, the latest release of this repo (`stripe-react-native`) still points to version `Stripe-iOS 22.77.0` which does not contain the fix we need.

We've identified the following workaround that allows our app to build again:
1. `yarn add @stripe/stripe-react-native@0.18.1`
2. in your `ios/Podfile` bump `platform :ios, '11.0' to platform :ios, '12.0'` (see: https://github.com/stripe/stripe-react-native#ios)
3. in `node_modules/@stripe/stripe-react-native/stripe-react-native.podspec`, bump your Stripe version from `22.7.0` to `22.8.1`
4. `pod update Stripe` in `ios/` (follow any prompts for `pod repo update`)
5. Close Xcode, re-open xcode
6. Clean and build

*Therefore we'd like to request a build/release to NPM with the updated iOS version in the `stripe-react-native.podspec` to fix our issue by your official release.*

Perhaps this is already in your guys' queue, in which case, is there a timeline which we might expect this release?

**Comment by charliecruzan-stripe** [comment]
we're updating the native libraries and pushing a release out this week 👍

**Comment by MarloDelatorre** [comment]
Awesome, thanks for the super quick response! 🙏🏽

Closing...

**Comment by raajnadar** [comment]
Please let us know once it is released with the version number

**Comment by charliecruzan-stripe** [comment]
Released in 0.19.0: https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0190---2022-09-16
