### ISSUE TITLE
Missing function mocks in mocks.js

### ISSUE THREAD

**Issue by beForged** [stripe/stripe-react-native#1129]
**Is your feature request related to a problem? Please describe.**
mocks.js is missing several functions / hasn't been updated recently - for example `isGooglePlaySupported` is missing - causes some difficulty when testing.

**Describe the solution you'd like**
add functions to mock file

**Describe alternatives you've considered**
could manually add them in when testing but it seems unpreferable to do so

**Additional context**
can open a PR as well - not sure if there is a list of functions I can compare with or just manually compare with docs is easiest and if there are any functions that shouldn't be mocked in that file.

**Comment by charliecruzan-stripe** [comment]
Thanks @beForged ! This was fixed in https://github.com/stripe/stripe-react-native/commit/e8745297506e4d20372cc7104691ea53e7dd2cdf
