### ISSUE TITLE
how to add google pay feature in initPaymentSheet useStripe() 

### ISSUE THREAD

**Issue by aashis-bss** [stripe/stripe-react-native#1131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charliecruzan-stripe** [comment]
https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-google-pay
