### ISSUE TITLE
Bug after updating mac

### ISSUE THREAD

**Issue by wcastand** [stripe/stripe-react-native#1132]
**Describe the bug**
can't build my expo app on ios after i updated my mac to the latest version.

**To Reproduce**

**Expected behavior**
being able to build the expo app on ios

**Screenshots**
![Screenshot 2022-09-14 at 13 58 10](https://user-images.githubusercontent.com/2178244/190147884-df1744a6-3e5f-4b96-9128-f44be8c5cd39.png)

**Desktop (please complete the following information):**
 - OS: Mac Air M1 (2020)
 - Version: 12.6 

**Smartphone (please complete the following information):**
 - OS: ios

can't build the expo-dev app using `yarn ios`

**Comment by jkepps** [comment]
I am also running into this issue, but I haven't upgraded my macOS just yet, still running 12.5.1. I have a hunch it is either the new version of xcode (v14) or an incompatibility with iOS 16. I'm downloading iOS 15.5 right now to see if I can get my app to build again on that.

**Comment by ffedelefrsf** [comment]
Hey guys, 

Downgrading iOS won't make a difference since the issue here is compatibility between XCode v.14 compiler and pod Stripe versions lower than 2.7.0.

My recent answer may be useful for you.
[https://github.com/stripe/stripe-ios/issues/2010#issuecomment-1247207314](url)

**Comment by charliecruzan-stripe** [comment]
This is the original issue: https://github.com/stripe/stripe-ios/issues/2001

As @ffedelefrsf stated, this was fixed in stripe-ios 22.7.1, which you can get by re-`pod install`ing on v0.18.1 of this stripe-react-native.

**Comment by wcastand** [comment]
for people coming from expo, it should be fix in future expo version
https://github.com/expo/expo/pull/19055
