### ISSUE TITLE
null cannot be cast to non-null type kotlin.String on Android

### ISSUE THREAD

**Issue by cmejet** [stripe/stripe-react-native#1140]
**Describe the bug**
After migrating from vanilla react native to expo getting error on release builds only.

**To Reproduce**
1. Initialize App with Expo ~46.0.2
2. Initialize Stripe-react-native using `expo install @stripe/stripe-react-native` which installs version 0.13.1
3. Release build (used eas build)
4. App Crashes
5. See error provided in additional context

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Galaxy S22 (all android)
 - OS: Android 13
 - Browser n/a
 - Version 13

**Additional context**
```
09-19 13:42:37.613 26192 26276 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-19 13:42:37.613 26192 26276 E AndroidRuntime: Process: io.[bundleID], PID: 26192
09-19 13:42:37.613 26192 26276 E AndroidRuntime: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:245)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at com.reactnativestripesdk.StripeSdkModule.initialise(StripeSdkModule.kt:91)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
09-19 13:42:37.613 26192 26276 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by charliecruzan-stripe** [comment]
Are you using the `initStripe` function, or the `StripeProvider` component? It looks like maybe the `publishableKey` you're passing in is null or undefined

**Comment by cmejet** [comment]
@charliecruzan-stripe it's utilizing the initStripe funciton in the index.js
That is very helpful to understand that it might be coming form the key. I just recently converted this to NOT have the key hard coded so that it could be switched by environment for dev vs. prod and it might not be picking up the env values. Part of what I was trying to test was if they were be included properly but it was crashing upon start so I never got that far and I obviously went down the rabbit hole without realizing it could be as simple as the publishable key 🤦‍♀️  Super helpful and hopefully exactly what I needed. I'll report back.

**Comment by cmejet** [comment]
Closing issue, was able to resolve when key was supplied

**Comment by charliecruzan-stripe** [comment]
Awesome! thanks for the followup @cmejet, let me know if you run into any other weirdness! We should catch that crash and resolve with a helpful error, so thanks for the report
