### ISSUE TITLE
    TypeError: (0 , _stripeReactNative.initStripe) is not a function

### ISSUE THREAD

**Issue by vishaldhanotiya** [stripe/stripe-react-native#1141]
**Describe the bug**
I am trying to write a test case. but I am trying to mock stripe npm but not getting success.

**To Reproduce**
Write two basic tests and execute them you can see the error in the console

**App.js file**
```
useEffect(() => {
		getStripeToken();
		initializeStripe();
	}, []);

	const initializeStripe = () => {
		initStripe({
			publishableKey:'pk_te9ms7qP6N70007AHphRr',
			merchantIdentifier: 'merchant.identifier',
			urlScheme: 'your-url-scheme'
		});
	};
```
**App.test.tsx**
```
	test('Stripe Payment render correctly', () => {
		render(<StripePayment />);
	});

	test('Stripe Payment snapshot capture correctly', () => {
		const componentTree = render(<StripePayment />).toJSON();
		expect(componentTree).toMatchSnapshot();
	});

```
jest.setup.js
```
import mock from '@stripe/stripe-react-native/jest/mock.js';

jest.mock('@stripe/stripe-react-native', () => mock);
```

Received following error

<img width="755" alt="stripe_test_case_error" src="https://user-images.githubusercontent.com/34983293/191203537-0710f8a4-1f28-487b-b5af-44482fc2a5d2.png">

**Comment by charliecruzan-stripe** [comment]
fixed in https://github.com/stripe/stripe-react-native/commit/e034c824fd72b9e2d3277c1c8dd7dd5ef3bf5b47, thanks for the report! this will go out in our next release
