### ISSUE TITLE
confirmSetupIntent function has bad typing.

### ISSUE THREAD

**Issue by mateuszmolkaofficial** [stripe/stripe-react-native#1142]
**Describe the bug**
Documentation on this [stripe tutorial](https://stripe.com/docs/payments/save-and-reuse-cards-only?platform=react-native#react-native-create-setup-intent) says that the second argument of the confirmSetupIntent function should be 
```
{ paymentMethodType: "Card", ... }
```

but it works with 

```
{ type: "Card", ... }
```
<img width="577" alt="image" src="https://user-images.githubusercontent.com/26611493/191343623-c01f6fde-861d-433e-a779-758b268c1686.png">

**To Reproduce**
1. Invoke confirmSetupIntent("client_secret", { paymentMethodType: "Card"})
2. See error saying "You must provide paymentMethodType"

**Comment by charliecruzan-stripe** [comment]
If you're using Expo, please make sure that you are installing the package with `expo install` to make sure the versions of your JS and native code match

**Comment by mateuszmolkaofficial** [comment]
That helped typescript-wise but the official docs are wrong about the parameter name. It has to be `type` instead `paymentMethodType`

**Comment by charliecruzan-stripe** [comment]
The official docs rely on the most recent version of @stripe/stripe-react-native, whereas with Expo's managed workflow you'll be using an older version and should instead rely on the typings
