### ISSUE TITLE
Integrating Apple Pay

### ISSUE THREAD

**Issue by aurelien-robineau** [stripe/stripe-react-native#1143]
Hi,

I have been trying to implement Apple Pay for days but I can't succeed. I am asking for help here because Stripe support does not seem to know much about this package.

Here is the flow I use :
```js
import { useApplePay, useStripe } from '@stripe/stripe-react-native';

const {
  presentApplePay,
  confirmApplePayPayment
} = useApplePay({
  onShippingMethodSelected: (shippingMethod, handler) => {
    // Handling shipping methods selection here, works fine.
  }
});

const stripe = useStripe();

const MyComponent = () => {
  const handleApplePay = () => {
    const { error, paymentMethod } = await presentApplePay({ // params here work fine, not important });
    
    if (!error) {
      // Call to my custom API. Params are the total amount, the currency code and the address 
      const paymentIntent = createPaymentIntent(params);

      // Always fails, returns {"error": [Error: Payment not completed]}
      const confirmation = await confirmApplePayPayment(paymentIntent.clientSecret);

      // I have never tested this because I never get to this point
      const confirmPayment = await stripe.confirmPayment(clientSecret);
  }

  return (
    <Pressable onPress={handleApplePay}>
      <Text>Apple Pay</Text>
    </Pressable>
  )
}
```

I have several questions :
- Is my flow right?
- Why does the `confirmApplePayPayment` method keeps failing?
- How does Stripe knows what PaymentMethod to use ? I is done automatically with the `confirmApplePayPayment` method or should I do something else?
- How do I get the shipping address the user selected so I can save it to my database (actually using Shopify)?
- Depending on the shipping country, the shipping methods are not the same. Is there a way to update shipping methods ?

If you need more context I will provide it to you, but I don't really know what else to say for now.

Thank you.

**Comment by charliecruzan-stripe** [comment]
The `useApplePay` hook needs to be called from a functional component (i.e. inside `MyComponent`). Your ESLint setup should catch that. Otherwise, this flow looks good to me, but let me know if that doesn't fix things 👍 

I'll answer some of your other questions:

> How does Stripe knows what PaymentMethod to use ? I is done automatically with the confirmApplePayPayment method or should I do something else?

It's done automatically, you'll use the payment method you just created with Apple Pay

> How do I get the shipping address the user selected so I can save it to my database (actually using Shopify)?

Using the callbacks you supply to the `useApplePay` hook: https://stripe.dev/stripe-react-native/api-reference/interfaces/UseApplePayProps.html

> Depending on the shipping country, the shipping methods are not the same. Is there a way to update shipping methods ?

Same answer as above :)

**Comment by aurelien-robineau** [comment]
Thanks a lot for your help. I made a mistake writing this issue, my hooks do get called from the component. So this is not the issue...

As for the shipping method, I can't get it from the hooks because it is incomplete. See [https://github.com/stripe/stripe-react-native/issues/1120](https://github.com/stripe/stripe-react-native/issues/1120). It is a security measure from Apple. Is there any way to get the entire address after Apple Pay confirmed the payment ?

And regarding the shipping methods, I can update cart items with the handler of the callback, but can I update the actual shipping methods ?

**Comment by charliecruzan-stripe** [comment]
We are adding the functionality to edit the actual shipping methods, this will be coming soon

**Comment by EmTeaZy** [comment]
> 

Hi @aurelien-robineau 
I am stuck at the exact same problem, can you please let me know how did you resolve your issue?
Thanks.

**Comment by aurelien-robineau** [comment]
Hi @EmTeaZy, I am sorry I see your comment only now. You have probably found a solution by now but this may help others.

The issue I had was in the `onShippindMethodSelected` method. As you can see it takes a `handler` param, which absolutely needs to be called. If not, Apple Pay will fail.

**Comment by charliecruzan-stripe** [comment]
hi @aurelien-robineau ! you should be able to do this now with the Platform Pay APIs
