### ISSUE TITLE
React Native Stripe is not working after upgrading Xcode to 14

### ISSUE THREAD

**Issue by AhmadMazaal** [stripe/stripe-react-native#1144]
**I have my app developed using a React Native(version **0.66.3**) along with Expo(version **^43.0.3**) that has Stripe(@stripe/stripe-react-native of version ^0.2.3) integrated in it. Everything was working fine, but suddenly after upgrading xCode to version 14 and the iOS on my iPhone to 16, the project is failing to build.**

The error is as follows:

<img width="265" alt="Screen Shot 2022-09-21 at 4 57 48 PM" src="https://user-images.githubusercontent.com/61668890/191554382-11c905c7-fd66-41d2-b892-5e6d480f2911.png">

Any suggestions?

**Comment by charliecruzan-stripe** [comment]
v0.15.0 comes with fixes for Xcode 14, please refer to the changelog. Expo SDK 46 supports v0.13.1, so to use v0.15.0 you can't use Expo's managed workflow

**Comment by umer-viabletree** [comment]
@charliecruzan-stripe  kindly update in V0.19.0 also Thanks

**Comment by dulcemunoz** [comment]
Hi..! I have my app developed using a React Native(version 0.64.0)  that has Stripe("@stripe/stripe-react-native": "^0.1.5") integrated in it. Everything was working fine, but suddenly after upgrading xCode to version 14 and the iOS on my iPhone to 16, the project is failing to build.
The error is as follows:
![Captura de Pantalla 2022-10-28 a la(s) 10 20 09](https://user-images.githubusercontent.com/69825936/198673587-4c62fa2f-1c1d-49e7-bc1f-e25fa74dc4e1.png)


In my PodFile I have set 

platform :ios, '13.0' and 
pod 'stripe-react-native', :path => '../node_modules/@stripe/stripe-react-native'
pod 'Stripe', '~> 21.7.0' 

and even running the pod install command, any suggestions?

**Comment by NgocLe1001** [comment]
Any one has fixed it please?

**Comment by mani53-dev** [comment]
Is there anyone who have fixed this?

**Comment by charliecruzan-stripe** [comment]
You should not need to declare a dependency on Stripe in your podfile, please remove that @dulcemunoz

**Comment by dulcemunoz** [comment]
Hi! @charliecruzan-stripe
I have already removed this line from my podfile, cleared the cache and rebooted my machine and the error persists.
Currently my versions inside the package are
  "react-native": "0.64.0", "@stripe/stripe-react-native": "^0.1.5",

**Comment by charliecruzan-stripe** [comment]
v0.1.5 isn't going to support xcode 14, you'll need to upgrade to at least v0.14.0

**Comment by RituMandloi** [comment]
@charliecruzan-stripe Is there any patch available to address this issue in "@stripe/stripe-react-native" version 0.5.0? We would prefer not to upgrade the React Native version at this time. We need to upload the iOS build and require at least Xcode Version 14.1.
