### ISSUE TITLE
Using a gateway

### ISSUE THREAD

**Issue by raulgordejev** [stripe/stripe-react-native#1145]
Just wondering is it possible to use another payment provider gateway to generate payment tokens as this seems to be the only Google/Apple Pay SDK for React Native which is still maintained?

**Comment by charliecruzan-stripe** [comment]
There isn't, this SDK is specifically for integrating Stripe. We are working on a revamp of the native pay (apple pay and google pay) functionality now where it would be easier to add something like that if we decided to.

Can I ask what other gateways you'd like support for?

**Comment by raulgordejev** [comment]
> Can I ask what other gateways you'd like support for?

We're using checkout.com for example.

**Comment by charliecruzan-stripe** [comment]
Got it, well I'm not sure whether or not adding support for other gateways is something we'd work on, but we'll keep it in mind once that native pay revamp is landed!
