### ISSUE TITLE
GooglePay is not working || throwing error length: 0, index: 0

### ISSUE THREAD

**Issue by gulsher7** [stripe/stripe-react-native#1148]
**Expected behavior**
Open Google Sheet

**Screenshots**
<img width="466" alt="Screenshot 2022-09-25 at 5 19 51 PM" src="https://user-images.githubusercontent.com/56266123/192141912-3d5c6756-77e9-4401-aaf2-84b1d97bd908.png">

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7 Pro
 - OS: Android
 - Browser stock browser
 - Version 12.5.1

**Comment by charliecruzan-stripe** [comment]
Hi! This usually indicates an issue with your server-side stripe code. Check out these two issues that deal with the same problem:

- https://github.com/stripe/stripe-react-native/issues/633
- https://github.com/stripe/stripe-react-native/issues/874
