### ISSUE TITLE
[Andorid] app:checkDebugDuplicateClasses Failed

### ISSUE THREAD

**Issue by meer-habib-dev** [stripe/stripe-react-native#1157]
**Describe the bug**

i was getting this error during build time of android after two weeks of install stripe sdk, it was running perfectly before. it also running and building perfectly in IOS devices. 

**To Reproduce**
Install using this code yarn add @stripe/stripe-react-native
Run yarn android
Terminal get error at 76% , appear this error : Unchecked cast :  >Task: app:checkDebugDuplicateClasses Failed ( picture below)

Desktop (please complete the following information):
![Screenshot 2022-10-01 at 10 09 41 PM](https://user-images.githubusercontent.com/86624941/193418771-d390f33b-8d3b-4ce9-a9ab-194881df34b5.png)
![Screenshot 2022-10-01 at 10 10 36 PM](https://user-images.githubusercontent.com/86624941/193418773-fa9d73fd-6b06-42b2-9688-b923870f801a.png)

I also tried to build and run project using Android Studio :
it was throwing this error : 
![Screenshot 2022-10-01 at 10 56 57 PM](https://user-images.githubusercontent.com/86624941/193420016-f7acb59e-1342-40c4-86ee-2b948f98c846.png)

OS:Macbook M1 Air
Smartphone (please complete the following information):

Debug on real device ( Samsung A71 Android)
Additional context

React versio": "17.0.2",
React native version: "0.68.2",
Stripe version: 0.19.0
buildToolsVersion = "31.0.0"
minSdkVersion = 21
compileSdkVersion = 33
targetSdkVersion = 31

**Comment by YashKalaria-BTC** [comment]
I am also facing the same issue.

**Comment by YashKalaria-BTC** [comment]
I have fixed the issue by adding following lines in `app/build.gradle` dependencies:

````js
implementation (project(':stripe_stripe-react-native')) {
      exclude group: "org.bouncycastle", module: "bcprov-jdk15to18"
}
````

**Comment by meer-habib-dev** [comment]
> I have fixed the issue by adding following lines in `app/build.gradle` dependencies:
> 
> ```js
> implementation (project(':stripe_stripe-react-native')) {
>       exclude group: "org.bouncycastle", module: "bcprov-jdk15to18"
> }
> ```

Solved bro tnx
