### ISSUE TITLE
paymentOption is undefined returning from presentPaymentSheet

### ISSUE THREAD

**Issue by tonyneel** [stripe/stripe-react-native#1159]
**Describe the bug**
After user has successfully filled in information to the payment sheet and no error is returned the payment option is still undefined.

**To Reproduce**
1. Using versions "@stripe/stripe-react-native": "^0.18.1", and "react-native": "0.69.1".
2. Init payment sheet in test mode.
3. Fill in test card to sheet
4. No payment option is returned

**Expected behavior**
Payment option should be defined so I can give a visual confirmation to the customer

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: android 12

**Additional context**
As mentioned before this in test mode with a test card. Is this the reason why? It seems it should still work but not sure.

**Comment by tonyneel** [comment]
I am expected to be able to get the payment details correct?

**Comment by charliecruzan-stripe** [comment]
Hi! This works in our example app code so please provide the code you're using so we can reproduce the issue. See our example code for this here: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICustomScreen.tsx#L61

**Comment by bensnell-stripe** [comment]
@tonyneel we chatted on discord earlier... I forgot that paymentOption is only returned when `customFlow` is set true. Otherwise it is expected to be undefined. As we discussed, fetching the payment mehtod details from your server will be the way to go.

**Comment by charliecruzan-stripe** [comment]
Closing this issue- to get the paymentOption, you'll need to use `customFlow` as @bensnell-stripe mentioned above. Otherwise, `presentPaymentSheet` doesn't return the payment option. If you have a use case for that though, let me know!

**Comment by tonyneel** [comment]
Thanks for the help again @bensnell-stripe ! I am good with this being closed thanks for the clarification. One action item could be to update the typing for paymentOption to be not required then it would have caused less confusion for me.

**Comment by charliecruzan-stripe** [comment]
Great point @tonyneel ! I'll correct that in the types

**Comment by 256hz** [comment]
@charliecruzan-stripe we're using `customFlow: true` with a SetupIntent instead of a PaymentIntent, and after a successful card entry (the 4242 card in the dev environment), I'm getting `undefined` for the PaymentOption.  Is that expected?
