### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "stripe-react-native":   In Podfile:     stripe-react-native (from `../node_modules/@stripe/stripe-react-native`)

### ISSUE THREAD

**Issue by ParmarJigarr** [stripe/stripe-react-native#1166]
[!] CocoaPods could not find compatible versions for pod "stripe-react-native":
  In Podfile:
    stripe-react-native (from `../node_modules/@stripe/stripe-react-native`)
    
    Getting this error and if i update ios version from 10.0 to 12.0 then getting error which is added in attach screenshot 
    Please help me to solve this error.

![Screenshot 2022-10-11 at 10 59 18 AM](https://user-images.githubusercontent.com/96713035/195010746-d831e5a9-a4f0-4eb2-aec5-57f35ea27778.png)

**Comment by charliecruzan-stripe** [comment]
https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios

There a couple other issues with these `pod install` problems that have already been solved. I recommend making sure to follow the linked guide above, then looking at what fixed it for other users [here](https://github.com/stripe/stripe-react-native/issues/1116)
