### ISSUE TITLE
CVC for AMEX

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-react-native#1167]
My AMEX has 4 digits for CVC : xxxx.
If I change one of the 4 digits, the AMEX si accepted when I try to make a payment.
For example, if the 4 digits are 1234, if I use 5234 or 1534 or 1254 or 1235, the payment is successfull.
Is it normal ?

**Comment by charliecruzan-stripe** [comment]
Is this in production, with a real amex card?

**Comment by nicolasdevienne** [comment]
Yes @charliecruzan-stripe in production 😰

**Comment by charliecruzan-stripe** [comment]
Gotchya, well yeah, this can happen (it's dependent on the bank, not Stripe). Check out this article for more info: https://support.stripe.com/questions/charge-succeeded-despite-cvc-or-zip-check-mismatch
