### ISSUE TITLE
Question about ApplePay and Customer attachment

### ISSUE THREAD

**Issue by anija** [stripe/stripe-react-native#1170]
Hello!
This is more a question to understand if there's a problem in our stripe implementation.

We are allowing user to pay with ApplePay, using hooks `presentApplePay` and `confirmApplePayPayment`.

The standard process works just fine: i call the backend, the backend gives me the secret, i confirm the payment on client side.
But if there's something wrong and the payment have to be done again, sometimes I get this error:

```
Error: The provided PaymentMethod was previously used with a PaymentIntent without Customer attachment, shared with a connected account without Customer attachment, or was detached from a Customer. It may not be used again. To use a PaymentMethod multiple times, you must attach it to a Customer first
```

This is because we don't attach the ApplePay PaymentIntent to the Customer, we do this only when user saves a normal credit card.
On the website implementation, the ApplePay PaymentIntent is always different so we don't experience the same problem. I was expecting that the react-native sdk would do the same, but often the PaymentIntent is "recycled".

Should we attach this PaymentIntent also?

**Comment by charliecruzan-stripe** [comment]
> but often the PaymentIntent is "recycled"

You provide the payment intent, so do you mean you are providing the same payment intent the second time? 

> Should we attach this PaymentIntent also?

Can you provide some more details around what you're attaching the payment intent to?

**Comment by anija** [comment]
> You provide the payment intent, so do you mean you are providing the same payment intent the second time?
Exactly. The second time i call the presentApplePay hook, the paymentIntent returned is the same of the one already used for the payment before.

> Can you provide some more details around what you're attaching the payment intent to?
When paying with Apple Pay, we're simply not attaching it to the customer. Since the error says a paymentIntent cannot be reused without attaching it to a customer, I was asking if it's intended this way: that also the ApplePay PaymentIntent should be attached to the customer.

**Comment by charliecruzan-stripe** [comment]
`presentApplePay` returns a paymentMethod, not a paymentIntent. You are generating the payment intent yourself on your server (likely with that payment method), so it's up to you to generate a new one, **or** attach the payment intent to a customer
