### ISSUE TITLE
Remove CardForm margin or padding

### ISSUE THREAD

**Issue by sebastienlabine** [stripe/stripe-react-native#1172]
CardForm seems to have an integrated padding or margin that makes alignment really hard. 

 ![image](https://user-images.githubusercontent.com/8888846/195939740-a550ca44-60c6-46bd-ab08-9b47a8354194.png)

**Comment by charliecruzan-stripe** [comment]
thanks @sebastienlabine ! will be fixed by https://github.com/stripe/stripe-react-native/pull/1234

**Comment by charliecruzan-stripe** [comment]
Fixed in Fixed in v0.22.1 ✅
