### ISSUE TITLE
react native run-ios fails. ios build fails . android works

### ISSUE THREAD

**Issue by manish-shukla01** [stripe/stripe-react-native#1173]
**Describe the bug**
No code changes on my side. Xcode update hapenned and now the build fails. Android works just fine. here is the error i get:

** BUILD FAILED **

The following build commands failed:
        SwiftEmitModule normal x86_64 Emitting\ module\ for\ Stripe (in target 'Stripe' from project 'Pods')
        SwiftCompile normal x86_64 Compiling\ AddPaymentMethodViewController.swift,\ AfterpayPriceBreakdownView.swift,\ Analytic.swift,\ Analytic+Payments.swift,\ APIRequest.swift,\ ApplePayHeaderView.swift,\ Async.swift,\ BackwardsCompatibleColors.swift,\ BillingAddressEditView.swift,\ BottomSheet3DS2ViewController.swift,\ BottomSheetViewController.swift,\ CardDetailsEditView.swift,\ CardScanningView.swift,\ CheckboxButton.swift,\ CheckboxElement.swift,\ ChoosePaymentOptionViewController.swift,\ CircularButton.swift,\ ConfirmButton.swift,\ ContainerView.swift,\ DefaultPaymentMethodStore.swift,\ DimmedView.swift,\ Dropd

package.json:
  "@stripe/stripe-react-native": "^0.1.4",

i saw some other folks got this error and it solved for them to update to ios 14.0. i did the same but does not seem to solve my issue. here is my podfile:

platform :ios, '14.0'

xcode version:
Version 14.0.1 (14A400)

**Comment by mmafrar** [comment]
Me too having the same issue with Xcode 14.0.1 (14A400) and iOS SDK 16.0

**Comment by charliecruzan-stripe** [comment]
That version of stripe-react-native is too old to run with Xcode 14. You should try and use the newest version of stripe-react-native if you're building with Xcode 14

**Comment by manish-shukla01** [comment]
thanks @charliecruzan-stripe . upgrading fixed the ios issue but now android build fails .. i changed following settings as per what is there in example..
buildscript {
    ext {
        googlePlayServicesVersion = "+"
        firebaseMessagingVersion = "21.1.0"
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        
    }
but i get this error now:

> Task :stripe_stripe-react-native:compileReleaseKotlin FAILED
e: /Users/manishshukla/Projects/vMallApp/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonView.kt: (40, 19): Unresolved reference: reactApplicationContext

i am on react-native  "react-native": "0.63.4", if that helps.

**Comment by charliecruzan-stripe** [comment]
I see- getReactApplicationContext was [introduced in RN 0.64](https://github.com/facebook/react-native/blob/0.64-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/ThemedReactContext.java), and is not present in 0.63. The changelog mentions that v0.8.0 requires React Native 0.64 and above.
