### ISSUE TITLE
Error when running eas build for expo managed react native app

### ISSUE THREAD

**Issue by paulsizer** [stripe/stripe-react-native#1177]
Trying to run eas build on an Expo 46 app and getting errors on the fast lane step of the build process:

'''
› Compiling react-native Pods/React-perflogger » BridgeNativeModulePerfLogger.cpp
562
› Packaging @sentry/react-native Pods/Sentry » libSentry.a
563
› Packaging react-native Pods/React-perflogger » libReact-perflogger.a
564

❌  (ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext.swift:240:54)

  238 |         let pk_didSelectShippingMethod = #selector(
  239 |             (PKPaymentAuthorizationControllerDelegate.paymentAuthorizationController(
> 240 |                 _:didSelectShippingMethod:handler:)) as pkDidSelectShippingMethodSignature)
      |                                                      ^ '-> ((PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> Void) -> Void)?' is not convertible to 'pkDidSelectShippingMethodSignature' (aka 'Optional<((any PKPaymentAuthorizationControllerDelegate) -> (PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> ()) -> ())>')
  241 |         let stp_didSelectShippingMethod = #selector(
  242 |             _stpinternal_STPApplePayContextDelegateBase.applePayContext(_:didSelect:handler:))
  243 |         let pk_didSelectShippingContact = #selector(
565
› Compiling react-native Pods/React-logger » react_native_log.cpp
566
› Compiling react-native Pods/React-jsinspector » React-jsinspector-dummy.m
567
› Packaging react-native Pods/React-logger » libReact-logger.a
568
› Compiling react-native Pods/React-jsinspector » InspectorInterfaces.cpp
569
    Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')
570
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
571
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'CoachRx' from project 'CoachRx')
572
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'CoachRx' from project 'CoachRx')
573
    Run script build phase 'Upload Debug Symbols to Sentry' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'CoachRx' from project 'CoachRx')
574
▸ ** ARCHIVE FAILED **
575
▸ The following build commands failed:
576
▸ 	SwiftCompile normal arm64 Compiling\ Address.swift,\ BillingDetails.swift,\ BillingDetails+ApplePay.swift,\ Blocks.swift,\ CardBrand.swift,\ FraudDetectionData.swift,\ PaymentIntent.swift,\ PaymentIntent+API.swift,\ PaymentIntentParams.swift,\ PaymentMethod.swift,\ PaymentMethod+API.swift,\ PaymentMethodParams.swift,\ PKContact+Stripe.swift,\ PKPayment+Stripe.swift,\ SetupIntent.swift,\ SetupIntent+API.swift,\ SetupIntentParams.swift,\ STPAnalyticsClient+Payments.swift,\ STPAnalyticsClient+PaymentsAPI.swift,\ STPAPIClient+ApplePay.swift,\ STPAPIClient+PaymentsCore.swift,\ STPApplePayContext.swift,\ STPApplePayContext+LegacySupport.swift,\ STPTelemetryClient.swift,\ StripeCore+Import.swift,\ Token.swift,\ Token+API.swift,\ UserDefaults+PaymentsCore.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/Address.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/BillingDetails.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/BillingDetails+ApplePay.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Blocks.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/CardBrand.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Telemetry/FraudDetectionData.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentIntent.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/PaymentIntent+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentIntentParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentMethod.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/PaymentMethod+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentMethodParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/PKContact+Stripe.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/PKPayment+Stripe.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/SetupIntent.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/SetupIntent+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/SetupIntentParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Analytics/STPAnalyticsClient+Payments.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Analytics/STPAnalyticsClient+PaymentsAPI.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPAPIClient+ApplePay.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Categories/STPAPIClient+PaymentsCore.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext+LegacySupport.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Telemetry/STPTelemetryClient.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/StripeCore+Import.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/Token.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Token+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Categories/UserDefaults+PaymentsCore.swift (in target 'StripeApplePay' from project 'Pods')
577
▸ 	CompileSwift normal arm64 (in target 'StripeApplePay' from project 'Pods')
578
▸ (2 failures)
579
** ARCHIVE FAILED **
580
581
582
The following build commands failed:
583
	SwiftCompile normal arm64 Compiling\ Address.swift,\ BillingDetails.swift,\ BillingDetails+ApplePay.swift,\ Blocks.swift,\ CardBrand.swift,\ FraudDetectionData.swift,\ PaymentIntent.swift,\ PaymentIntent+API.swift,\ PaymentIntentParams.swift,\ PaymentMethod.swift,\ PaymentMethod+API.swift,\ PaymentMethodParams.swift,\ PKContact+Stripe.swift,\ PKPayment+Stripe.swift,\ SetupIntent.swift,\ SetupIntent+API.swift,\ SetupIntentParams.swift,\ STPAnalyticsClient+Payments.swift,\ STPAnalyticsClient+PaymentsAPI.swift,\ STPAPIClient+ApplePay.swift,\ STPAPIClient+PaymentsCore.swift,\ STPApplePayContext.swift,\ STPApplePayContext+LegacySupport.swift,\ STPTelemetryClient.swift,\ StripeCore+Import.swift,\ Token.swift,\ Token+API.swift,\ UserDefaults+PaymentsCore.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/Address.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/BillingDetails.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/BillingDetails+ApplePay.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Blocks.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/CardBrand.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Telemetry/FraudDetectionData.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentIntent.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/PaymentIntent+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentIntentParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentMethod.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/PaymentMethod+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentMethodParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/PKContact+Stripe.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/PKPayment+Stripe.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/SetupIntent.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/SetupIntent+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/SetupIntentParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Analytics/STPAnalyticsClient+Payments.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Analytics/STPAnalyticsClient+PaymentsAPI.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPAPIClient+ApplePay.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Categories/STPAPIClient+PaymentsCore.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext+LegacySupport.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Telemetry/STPTelemetryClient.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/StripeCore+Import.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/Token.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Token+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Categories/UserDefaults+PaymentsCore.swift (in target 'StripeApplePay' from project 'Pods')
584
	CompileSwift normal arm64 (in target 'StripeApplePay' from project 'Pods')
585
(2 failures)
586
Exit status: 65
587
588

'''

**Comment by charliecruzan-stripe** [comment]
What version of stripe-react-native are you using?
]

**Comment by Pcummings** [comment]
> What version of stripe-react-native are you using?

0.13.1

**Comment by Pcummings** [comment]
I upgraded the version to 0.19.0 and that worked! It would seem that expo needs to update the dependencies.

**Comment by charliecruzan-stripe** [comment]
Could be due to the version of Xcode that EAS is using

**Comment by Joshmatjjen** [comment]
> I upgraded the version to 0.19.0 and that worked! It would seem that expo needs to update the dependencies.

What is your Expo-cli and Eas-cli version
