### ISSUE TITLE
Border width and radius are smaller than that of built in React Native view on Android

### ISSUE THREAD

**Issue by perqin** [stripe/stripe-react-native#1181]
**Describe the bug**
Set the same value of `borderWidth` and `borderRadius` to both `CardField` and `View`. The border of the `CardField` is thinner than that of the `View`, and the `borderRadius` is also smaller. This also happens on `CardForm`.

**To Reproduce**
1. Edit the example in this repo. Change the styles in `WebhookPaymentScreen.tsx` to add border to the switch row:

```typescript
const styles = StyleSheet.create({
  cardField: {
    width: '100%',
    height: 50,
    marginVertical: 30,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 8,
  },
  text: {
    marginLeft: 12,
  },
  input: {
    height: 44,
    borderBottomColor: colors.slate,
    borderBottomWidth: 1.5,
  },
});
```

**Expected behavior**
The switch row has the same border as the `CardField`'s.

**Screenshots**
![Screenshot_20221024_112115](https://user-images.githubusercontent.com/7088631/197442348-3ce6994a-68b9-4b5c-80ef-70664b74a978.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 12

**Additional context**

**Comment by charliecruzan-stripe** [comment]
fixed in https://github.com/stripe/stripe-react-native/pull/1182
