### ISSUE TITLE
 Error build after update Xcode.

### ISSUE THREAD

**Issue by ameerarx** [stripe/stripe-react-native#1183]
**Describe the bug**
 error build: '(any PKPaymentAuthorizationControllerDelegate) -> ((PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> Void) -> Void)?' is not convertible to 'pkDidSelectShippingMethodSignature' (aka 'Optional<((any PKPaymentAuthorizationControllerDelegate) -> (PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> ()) -> ())>')
Did you mean to use 'as!' to force downcast?

**Expected behavior**
A bug appeared after updating Xcode. The project does not start.

**Screenshots**
![telegram-cloud-photo-size-2-5388614232288903119-y](https://user-images.githubusercontent.com/55210011/198012313-4a69ecee-9d07-454d-8991-a42923b8982d.jpg)
<img width="686" alt="image" src="https://user-images.githubusercontent.com/55210011/198014617-a613bdf5-488d-4b53-9939-69a3960b2e49.png">

**Desktop (please complete the following information):**
 - Xcode 14.0.1
 - Iphone 14 Pro Max (Simulator)
 - React Native 0.67.2
 - @stripe/stripe-react-native  "^0.7.0"

**Comment by hasbund** [comment]
Been having same issue for about a week now. Using Expo 46 currently and have tried on 45 and 44 with correct dependencies and same issue persists.

The best I can tell from my research is it seems to be a problem with iOS 16. In my own case I ran my app with iOS 15 and it worked perfectly. Then I updated iphone to iOS 16 which forced xCode update to xCode 14 before it would connect. That's when I started getting the same error that you're getting and have been stuck for a week. Still haven't figured out a fix but thought I'd throw this on the pile of info in case anyone more experienced than I can tell what's going on. It's definitely something between iOS 16 and xCode 14 that's causing the problem, as best as I can tell.

**Comment by cebrakadabra** [comment]
<img width="1137" alt="Screenshot 2022-10-27 at 7 51 13 PM" src="https://user-images.githubusercontent.com/8520633/198481445-751cf5ed-99ce-4a9f-8da8-5c65aa935107.png">

I just ran into the exact same issue. I can confirm it is independent from the stripe version, as I played around with running `0.18.1` all the way down to `0.6.1`. It must have to do something with iOS16 and xCode14 (just upgraded yesterday) - no issues on Android on the same machine (Apple M1) for anything under `0.8.x`

Xcode 14.0.1
Iphone 14 Pro Max (Simulator)
React Native 0.64.1
@stripe/stripe-react-native "^0.6.1"

**Comment by cebrakadabra** [comment]
https://github.com/stripe/stripe-ios/issues/1973

**Comment by adnandothussain** [comment]
Any updates on this issue?

**Comment by cebrakadabra** [comment]
I was able to resolve that issue myself by upgrading to the following in my `package.json`:
```
    ...
    "@stripe/stripe-react-native": "0.19.0"
    ...
    "expo": ">=47.0.0-0 <48.0.0",
    ...
    "react": "18.1.0",
    "react-native": "0.70.4",
    ...
```

**Comment by wassimAJ** [comment]
Upgrading to @stripe/stripe-react-native 0.19.0 then in the ios files running "pod update Stripe" solved my issue.

**Comment by Joshmatjjen** [comment]
Upgrading to version 0.19.0 did not fixed the error

**Comment by Ashishpal438** [comment]
> Upgrading to @stripe/stripe-react-native 0.19.0 then in the ios files running "pod update Stripe" solved my issue.
Thanks Man @wassimAJ This worked for me 

xcode 14.1
react-native 0.64.1

**Comment by wassimAJ** [comment]
> Upgrading to version 0.19.0 did not fixed the error

What react version are you using?
and did you run pod update Stripe after it?

**Comment by ameerarx** [comment]
> <img alt="Screenshot 2022-10-27 at 7 51 13 PM" width="1137" src="https://user-images.githubusercontent.com/8520633/198481445-751cf5ed-99ce-4a9f-8da8-5c65aa935107.png">
> 
> I just ran into the exact same issue. I can confirm it is independent from the stripe version, as I played around with running `0.18.1` all the way down to `0.6.1`. It must have to do something with iOS16 and xCode14 (just upgraded yesterday) - no issues on Android on the same machine (Apple M1) for anything under `0.8.x`
> 
> Xcode 14.0.1 Iphone 14 Pro Max (Simulator) React Native 0.64.1 @stripe/stripe-react-native "^0.6.1"

I updated the stripe to the latest version and solved the problem on iOS

**Comment by ameerarx** [comment]
> Any updates on this issue?

I updated the stripe to the latest version and solved the problem on iOS

**Comment by Joshmatjjen** [comment]
> > Any updates on this issue?
> 
> I updated the stripe to the latest version and solved the problem on iOS

Can you show use your package.json dependency
Let's see your version
And which version of expo-cli are you using

**Comment by ameerarx** [comment]
"@stripe/stripe-react-native": "^0.19.0",
      "react-native": "0.67.2",

**Comment by ameerarx** [comment]
> > > Any updates on this issue?
> > 
> > 
> > I updated the stripe to the latest version and solved the problem on iOS
> 
> @ameerarx Please Can you show use your package.json dependency Let's see your version And which version of expo-cli are you using

"@stripe/stripe-react-native": "^0.19.0",
  "react-native": "0.67.2",

**Comment by antoinerousseau** [comment]
I'm using stripe-react-native 0.23.1 and still getting this error under RN 0.70 or RN 0.71...

> The following build commands failed:
	SwiftEmitModule normal x86_64 Emitting\ module\ for\ StripePayments (in target 'StripePayments' from project 'Pods')
	SwiftCompile normal x86_64 Compiling\ [...] (in target 'StripePayments' from project 'Pods')

Any clue?

Xcode 14.2 on M2 Pro

**Comment by PedroDmian** [comment]
> I'm using stripe-react-native 0.23.1 and still getting this error under RN 0.70 or RN 0.71...
> 
> > The following build commands failed:
> > SwiftEmitModule normal x86_64 Emitting\ module\ for\ StripePayments (in target 'StripePayments' from project 'Pods')
> > SwiftCompile normal x86_64 Compiling\ [...] (in target 'StripePayments' from project 'Pods')
> 
> Any clue?
> 
> Xcode 14.2 on M2 Pro

I solved it as follows 
> 
**My computer is a**
>  M1,  Xcode 14.2 

**package.json** 
...
   "@stripe/stripe-react-native": "^0.2.3"  🆙 👉🏻   "@stripe/stripe-react-native": "0.23.3"
    ...
    "react": "17.0.2", (remained unchanged)
    "react-native": "0.66.0", (remained unchanged)
    ...
    
I update my **PodFile**  https://stackoverflow.com/a/74192042/6080699
...
`platform :ios, '11.0' to platform :ios, '13.0'`

And added these lines 

>     installer.pods_project.targets.each do |target|
>           target.build_configurations.each do |config|
>             if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
>               target.build_configurations.each do |config|
>                   config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>               end
>             end
>           end
>         end
>       end

Delete 

- node_modules
- package-lock.json
- Podfile.lock
- Pods

reinstall 

I hope it will be useful to someone

**Comment by antoinerousseau** [comment]
I don't think turning off code signing has to do with this but anyway I ended up building through Rosetta 2 and it worked.

**Comment by Hopefulee** [comment]
@antoinerousseau - hi how did you get it work?

I am getting errors 


```
LoadError - dlopen(/Users/blackbee/Projects/<project>/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Users/blackbee/Projects/<project>/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/blackbee/Pr<project>/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle
```

    "react": "18.1.0",
    "@stripe/stripe-react-native": "^0.24.0",
    "react-native": "0.70.6",

**Comment by antoinerousseau** [comment]
@Hopefulee make sure you open Xcode through Rosetta 2 (or run `yarn ios` in a Rosetta 2 terminal)

Also check your Ruby version (I use RVM), clean the build folder, pod install etc

**Comment by pkalani1999** [comment]
> @antoinerousseau - hi how did you get it work?
> 
> I am getting errors with M1
> 
> ```
> LoadError - dlopen(/Users/blackbee/Projects/<project>/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Users/blackbee/Projects/<project>/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/blackbee/Pr<project>/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle
> ```
> 
> ```
> "react": "18.1.0",
> "react-native": "0.70.6",
> "@stripe/stripe-react-native": "^0.24.0",
> ```

same issue in IOS xcode 15
