### ISSUE TITLE
pending status when payment is done

### ISSUE THREAD

**Issue by december1990** [stripe/stripe-react-native#1184]
hi, consider the following code :

const openPaymentSheet = async () => {
    const { error } = await presentPaymentSheet();

    if (error) {
      Alert.alert(`Error code: ${error.code}`, error.message);
    } else {
      Alert.alert('Success', 'Your order is confirmed!');
    }
  };

1) When we have no errors we enter the else block, so can we say that payment was 100% successful ? or we have to wait for Webhook to know if it was successful ? 

2) Are there any pending situations here ? which is not mentioned in the docs ? or all we have are error and success status. there seems to be pending state in web but didn't see in React native sdk. if there is pending state, how often does it fail or succeed ? and how to catch that state in code.

thanks in advance

**Comment by charliecruzan-stripe** [comment]
You will need to use Webhooks, refer to [these docs](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-fulfillment). There are pending situations, like with bank debits, but those are mentioned in the docs, and you can also refer to the payment-method specific docs page: https://stripe.com/docs/payments/payment-methods/overview
