### ISSUE TITLE
Android build task "Resolve dependencies of :stripe_stripe-react-native:debugCompileClasspath > Resolve dependencies of :stripe_stripe-react-native:debugRuntimeClasspath" fails

### ISSUE THREAD

**Issue by jsindos** [stripe/stripe-react-native#1186]
**Describe the bug**
I recently upgraded to `@stripe/stripe-react-native@0.19.0`, everything was working fine on Android. I had an issue with npm so re-ran `npm install`, and am now getting the following build error on Android. I've tried removing `node_modules` and re-installing but the issue persists.

It seems that `stripe-react-native` is attempting to load https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml, but it is timing out. I take it this is just an issue with react-native and it should come back online in time?

```
Could not determine the dependencies of task ':stripe_stripe-react-native:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all task dependencies for configuration ':stripe_stripe-react-native:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :stripe_stripe-react-native
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out
```

**Comment by QuangBinhDinh** [comment]
I also have this issue. But it only happened when i run the command `./gradlew bundleRelease` to release an aab file. When I run `react-native run-android --variant=release` to test the release build everything worked fine . My `@stripe/stripe-react-native` version is `0.18.0` and RN version is `0.66.4`

**Comment by QuangBinhDinh** [comment]
**UPDATE** 
I finally fix the problem by replacing `jcenter()` with `mavenCentral()` in `android/build.gradle` inside `node_modules` folder.  Seem like `jcenter()` is deprecated and I found the solution in this issue https://github.com/facebook/react-native/issues/31165.   I also notice many npm package now use `mavenCentral()` instead but your package doesn't use it. Please let me know your answer.

**Comment by jsindos** [comment]
Cool, I commented out the same line and replaced with `mavenCentral()` and it works for me as well now.

**Comment by c-info** [comment]
Temporary solution 

node_modules/@stripe/stripe-react-native/android/build.gradle

Replace jcenter() with mavenCentral()

in repositories { ...} , buildscript { ... }

**Comment by hongkheng** [comment]
Hitting this error:
```bash
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.stripe:financial-connections:20.5.+.
     Required by:
         project :app > project :stripe_stripe-react-native
      > Failed to list versions for com.stripe:financial-connections.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml'.
               > Read timed out
```

**Comment by king-faraz** [comment]
> Hitting this error:
> 
> ```shell
> Execution failed for task ':app:mergeDebugAssets'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve com.stripe:financial-connections:20.5.+.
>      Required by:
>          project :app > project :stripe_stripe-react-native
>       > Failed to list versions for com.stripe:financial-connections.
>          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml.
>             > Could not HEAD 'https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml'.
>                > Read timed out
> ```

did you fixed it?

**Comment by hongkheng** [comment]
Not able to. Need to be able to access finanical connection lib to update build.gradle.

**Comment by hongkheng** [comment]
> > Hitting this error:
> > ```shell
> > Execution failed for task ':app:mergeDebugAssets'.
> > > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> >    > Could not resolve com.stripe:financial-connections:20.5.+.
> >      Required by:
> >          project :app > project :stripe_stripe-react-native
> >       > Failed to list versions for com.stripe:financial-connections.
> >          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml.
> >             > Could not HEAD 'https://jcenter.bintray.com/com/stripe/financial-connections/maven-metadata.xml'.
> >                > Read timed out
> > ```
> 
> did you fixed it?

**Update**: I did a `./gradlew clean` and it able to build again. I'm using version `0.18.1`.
