### ISSUE TITLE
expo deep linking to redirect during onboarding throwing `Not a Valid URL`

### ISSUE THREAD

**Issue by veeramarni** [stripe/stripe-react-native#1188]
**Describe the bug**
We testing onboarding using expo deep linking for onboarding. Right now, it is not accepting expo deep link URL like `exp://127.0.0.1 or myapp://`

**To Reproduce**
1. Call String onboarding with following params
2. API call to `stripe.accountLinks.create` with  below params
```
{
account: 'xxxxxx',
collect: 'eventually_due',
type: 'account_onboarding',
refresh_url: 'exp://1270.0.1:1900/--/redirect?integrationStatus=',
return_url: 'exp://127.0.0.1:1900/--/redirect?integrationStatus=success',
success_url: 'exp://127.0.0.1:1900/--/redirect?integrationStatus=success',
failure_url: 'exp://127.0.0.1:1900/--/redirect?integrationStatus=fail',
}

```
**Expected behavior**

Stripe onboarding should support them.

**Screenshots**

![image](https://user-images.githubusercontent.com/3382355/199201069-fd4623b0-ea68-4f33-8bb4-b10792f6cf37.png)

![image](https://user-images.githubusercontent.com/3382355/199201180-737b9f5d-234e-4bba-a3c4-7faeaef14bd0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qsdamar** [comment]
@veeramarni Did you manage to find a solution for this problem? I have the same situation. Thanks!

**Comment by veeramarni** [comment]
@qsdamar We found some workaround but no direct solution. They say we need to put an intermediate webpage that inter redirect to the app as Stripe API only support web.

**Comment by qsdamar** [comment]
@veeramarni Thanks for answering. I think I'll end up using a WebView.

**Comment by jerry-santana** [comment]
I'm trying to implement something similar (without expo) but I'm facing the same issue.

I think others are having also in the same boat:
https://stackoverflow.com/questions/68695786/stripe-connect-account-return-url-link-back-to-expo-application

The workaround for now is to develop a site and set the ```redirect_url``` and ```return_url``` to your site.
And your sire will then redirect to the deep link in react native app.

Your mobile app > Stripe Onboarding > Your site > Your mobile app.

**Comment by charliecruzan-stripe** [comment]
Closing since this doesn't relate to the `stripe-react-native` library, this is related to the `stripe-node` library

**Comment by charliecruzan-stripe** [comment]
@veeramarni have you considered using a universal link for this instead?

**Comment by waqar-360** [comment]
@charliecruzan-stripe mate is their any proper solution for this issue or still we need to rely on workaround.
