### ISSUE TITLE
requiredShippingAddressFields postal address returns payment not completed

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#1189]
**Describe the bug**
When adding postalAddress as requiredShippingAddressFields in the `presentApplePay` sheet I receive "The payment has been canceled" after 30 seconds. 

**To Reproduce**
1.Add `postalAddress` as requiredShippingAddressFields in presentApplePay
2. Notice the native apple pay screen is shown with the payment sheet.
3. Fill in an address and notice processing is hanging forever.
4. After 30 seconds looks like some timeout is triggered and the payment is cancelled.

**Expected behavior**
I expect the payment to complete.  Tested on latest sync of flutter stripe (which is on par with latest release of this lib).

**Smartphone (please complete the following information):**
 - iOS16
 -  iPhone 14 and iPhonex (both tested on simulator and real phone)

**Comment by charliecruzan-stripe** [comment]
Are you passing the `onShippingMethodSelected` prop to `useApplePay` and calling the `handler` at the end? See this example screen: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ApplePayScreen.tsx#L95-L115

**Comment by remonh87** [comment]
ow wow that is something we totally overlooked in the  Flutter Stripe sdk.  To understand this correctly: 
1. execute presentapple pay
2. User selects shipping address and iOS provides us a callback "shippingmethodselected"
3. we call updateApplePaySummaryItems and the flow continues.
 Is this correct?

**Comment by charliecruzan-stripe** [comment]
Correct! Technically you don't _need_ to call that yourself, as the SDK will automatically call `updateApplePaySummaryItems` if you don't set a value for `onShippingMethodSelected` yourself
