### ISSUE TITLE
Disable card authentication

### ISSUE THREAD

**Issue by keithdarragh** [stripe/stripe-react-native#1197]
**Is your feature request related to a problem? Please describe.**
We would like to disable card authentication for users. it looks as though this can be disabled when confirming a payment through the [api for confirm payment](https://stripe.com/docs/api/payment_intents/confirm#confirm_payment_intent-error_on_requires_action). 

It looks like we can enable `error_on_requires_action` and to disable card auth. This however isn't available in the react native sdk

**Describe the solution you'd like**
Can the `error_on_requires_action` be made available through the sdk

**Describe alternatives you've considered**
Allow params that are not listed in the sdk to be passed to the endpoint

**Comment by charliecruzan-stripe** [comment]
Hi there! You should pass this on the server-side when you create the payment intent. See these docs for an example: https://stripe.com/docs/payments/without-card-authentication
