### ISSUE TITLE
Can I use the payment sheet with custom actions?

### ISSUE THREAD

**Issue by nandorojo** [stripe/stripe-react-native#1202]
**Is your feature request related to a problem? Please describe.**

Hey, this is more of a question.

Can I [Run custom actions before confirming a payment](https://stripe.com/docs/payments/run-custom-actions-before-confirmation?client=react) using this library's PaymentSheet? I only see React web examples on those docs, but figured that might be due to it being in beta. It still uses a payment intent, so I thought it might be possible?

Please let me know, thanks!

**Comment by charliecruzan-stripe** [comment]
Hi! You can pass `customFlow: true` to `initPaymentSheet`. This separates out the payment method selection & confirmation steps, so you can get the `paymentOption` back from `presentPaymentSheet`, then perform some custom logic, _then_ call `confirmPaymentSheetPayment` 👍
