### ISSUE TITLE
EAS build android fails and iOS standalone crashes on launch with @stripe/stripe-react-native@0.19.0

### ISSUE THREAD

**Issue by MoritzWallner** [stripe/stripe-react-native#1207]
**Describe the bug**
I recently upgraded from expo SDK 45 to SDK 47. However, due to some dependencies it wasn't working correctly so I created a new expo project to test all the dependencies piece by piece to find the problem.

I created a new expo SDK 47 project and ran expo install @stripe/stripe-react-native.
I configured the plugin in my app.json file and build my standalone app with eas.

## Android
The build fails for android. After removing @stripe/stripe-react-native@0.19.0 it works. The build also works with @stripe/stripe-react-native@0.2.3.

I get 26 error messages. The first two are:
1. `Dependency 'androidx.appcompat:appcompat:1.5.1' requires libraries and applications that
[stderr]            depend on it to compile against version 32 or later of the
[stderr]            Android APIs.
[stderr]      
[stderr]            :app is currently compiled against android-31.
[stderr]      
[stderr]            Recommended action: Update this project to use a newer compileSdkVersion
[stderr]            of at least 32, for example 32.
[stderr]      
[stderr]            Note that updating a library or application's compileSdkVersion (which
[stderr]            allows newer APIs to be used) can be done separately from updating
[stderr]            targetSdkVersion (which opts the app in to new runtime behavior) and
[stderr]            minSdkVersion (which determines which devices the app can be installed
[stderr]            on).`

2. `Dependency 'androidx.appcompat:appcompat-resources:1.5.1' requires libraries and applications that
[stderr]            depend on it to compile against version 32 or later of the
[stderr]            Android APIs.
[stderr]      
[stderr]            :app is currently compiled against android-31.
[stderr]      
[stderr]            Recommended action: Update this project to use a newer compileSdkVersion
[stderr]            of at least 32, for example 32.
[stderr]      
[stderr]            Note that updating a library or application's compileSdkVersion (which
[stderr]            allows newer APIs to be used) can be done separately from updating
[stderr]            targetSdkVersion (which opts the app in to new runtime behavior) and
[stderr]            minSdkVersion (which determines which devices the app can be installed
[stderr]            on).`

I tried to fix this issue with `expo-build-properties` but the error remains.

`"expo-build-properties", 
        {
          "compileSdkVersion": 32,
          "targetSdkVersion": 32,
          "minSdkVersion": 32
        }`

## iOS
The iOS build succeeds with @stripe/stripe-react-native@0.19.0, however, the app crashes after the splash screen (I think it happens when StripeProvider is being rendered).

I cannot build an iOS app with the previously working @stripe/stripe-react-native@0.2.3, because it uses and outdated version of expo-config-plugins.

See the error of expo doctor from the eas build log on their website:
`[stderr] [00:47:09] Expected package @expo/config-plugins@^5.0.2
[stderr] [00:47:09] Found invalid:
[stderr] [00:47:09]   @expo/config-plugins@3.1.0
[stderr] [00:47:09]   (for more info, run: npm why @expo/config-plugins)`

I am in a managed workflow.

**To Reproduce**
1. create a new expo project `npx create-expo-app my-app --template` and select the bare js template.
2. run `npx expo install @stripe/stripe-react-native`
3. Configure the plugin in app.json
4. Build the iOS app and Android app
5. The iOS app should crash after startup
6. The Android build should fail

**Expected behavior**
Both builds should succeed.

**Screenshots**
I have never worked with Android Studio or Xcode and I am unsure about the error messages.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro (simulator) and Google Pixel 3 (AVD)
 - OS: iOS 16 and Android 11

**Comment by ludwig-pro** [comment]
for Android, you can try 
```
// build.gradle
    implementation ('androidx.appcompat:appcompat:1.3.1') {
        version { 
            strictly '1.3.1' 
        } 
    } 
  ```  
related to https://github.com/stripe/stripe-react-native/blob/master/example/android/app/build.gradle#L203-L207

**Comment by MoritzWallner** [comment]
Thank you! Turns out the problem was expo-build-properties. I ran `expo run:android` and specified the `compileSdkVersion 33` in the app/build.gradle file. 

It works now.
