### ISSUE TITLE
Question: react native "confirmSepaDebitPayment" equivalent

### ISSUE THREAD

**Issue by angelica-snowit** [stripe/stripe-react-native#1208]
Hi,

We are using sepa_debit payments; after paying, the answer from stripe is:
```
requiresConfirmation: true,
paymentIntentStatus: 'requires_payment_method',
...
```

On the website, we call the `confirmSepaDebitPayment` to handle this situation: https://stripe.com/docs/js/payment_intents/confirm_sepa_debit_payment.
I couldn't find the equivalent function for react-native. I've tried the basic `confirmPayment` but I got  a `payment_intent_unexpected_state` error.

**Comment by charliecruzan-stripe** [comment]
Hi! This is working in our example app [here](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/SepaPaymentScreen.tsx). It seems like maybe the payment method is not attached properly. Can you share some sample code to reproduce this?

**Comment by angelica-snowit** [comment]
Hi. The problem was analyzed further on your Slack channel. Basically, it's not possible to confirm the sepa payment on react native without using the PaymentSheet. The `confirmSepaDebitPayment` used on the website was indicated as "deprecated" (not in documentation, but by someone on slack) and not implemented in the react-native library.

**Comment by charliecruzan-stripe** [comment]
Ah i see, well you could [attach the payment](https://stripe.com/docs/api/payment_methods/attach) method to the customer, then use `confirmPayment` with _just_ the client secret, and it will automatically use the customer's default payment method (as of v0.18.0, see changelog- https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0180---2022-08-17)
