### ISSUE TITLE
error: 'const' enums are not supported

### ISSUE THREAD

**Issue by benomatis** [stripe/stripe-react-native#1209]
Trying to run iOS I get the following error:

>error: node_modules/@stripe/stripe-react-native/src/types/Errors.ts: /Users/benomatis/Sites/traininglane.fit/booking-mobile/node_modules/@stripe/stripe-react-native/src/types/Errors.ts: 'const' enums are not supported.

https://github.com/stripe/stripe-react-native/blob/a50a806075e37ab73ab9a76e95782044851d94e1/src/types/Errors.ts#L88

If my understanding is correct, this is because [babel only supports const enums since 7.15](https://github.com/babel/babel/releases/tag/v7.15.0) and you are on 7.13.

**Comment by charliecruzan-stripe** [comment]
We have `^7.13.0`, so it's actually resolved to 7.16.8

What version of stripe-react-native are you using?

**Comment by benomatis** [comment]
@charliecruzan-stripe I recently upgraded to `^0.21.0` hoping it will resolve the issue, I even tried adding 7.15 in resolutions, ended up removing `const` and use `patch-package` to get through this.

**Comment by ianjsikes** [comment]
+1 here. React Native w/ TypeScript does not support `const enum` - [link](https://create-react-app.dev/docs/adding-typescript/#troubleshooting)

stripe-react-native 0.21.0

**Comment by charliecruzan-stripe** [comment]
oh sorry about that- `const enum` snuck in there! pushed a [fix](https://github.com/stripe/stripe-react-native/commit/f882bfa588aa6d23a980b4b43d2cca660ca1dd2a) just now. This will probably be published next week, does that work for you both?

**Comment by benomatis** [comment]
@charliecruzan-stripe I was going to say it must have been a mistake as none of the rest of the variables in that file have it ;) all good here, thank you!

**Comment by charliecruzan-stripe** [comment]
Great! added a lint rule to prevent this from happening again, thanks for the issue!
