### ISSUE TITLE
If the credit card number is not filled in, or is in error, it jumps back to the credit card number

### ISSUE THREAD

**Issue by michelleb-stripe** [stripe/stripe-react-native#121]
**Describe the bug**
Card payment using webhooks: If the credit card number is not filled in, or is in error, any time you type in a later field it jumps back to the credit card number.  This is not the behavior in the CardTokenActivity

**To Reproduce**
1. Go to 'Card payment using webhooks'
2. Click on 'Month'
3. Enter a month
4. See that after each date of the month entered it jumps back to the credit card number.

**Expected behavior**
I would expected that when on the month it would continue to type in the month/year field

**Smartphone:**
 - Device: Android emulator
 - OS: 10

**Additional context**
None

**Comment by arekkubaczkowski** [comment]
@michelleb-stripe after some debugging I found out that it's related to this part of code from stripe-android
```
    override val cardParams: CardParams?
        get() {
           // ...
           // ...
           // ...
            when {
                cardNumber == null -> {
                    cardNumberEditText.requestFocus()
                }
                expirationDate == null -> {
                    expiryDateEditText.requestFocus()
                }
                cvc == null -> {
                    cvcEditText.requestFocus()
                }
                postalCodeEditText.shouldShowError -> {
                    postalCodeEditText.requestFocus()
                }
```
so this issue doesn't happen until you don't use `cardParams` getter in the application, otherwise this piece of the code is triggered and make "jumping" between fields.

could you confirm my guess?

**Comment by michelleb-stripe** [comment]
@arekkubaczkowski cardParams, paymentMethodCreateParams, and paymentMethodCard have the side effect that when called it will shift the focus to an invalid field.   These variables should only be queried when the card is valid as indicated by the `CardValidCallback`.

There is a bug that is currently being addressed where the postalCode field is not included in the `CallValidCallback` if `postalCodeRequired` or `usZipCodeRequired` is set to true.   

Will you be able to make the changes so that these (cardParams, paymentMethodCreateParams, and paymentMethodCard) are only accessed when the card is valid or it is ok to change the focus to the invalid field?
