### ISSUE TITLE
Build Fails Android Could not find react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0)

### ISSUE THREAD

**Issue by russmenum** [stripe/stripe-react-native#1218]
**Describe the bug**
Trying to build an Android app no longer works, the only code changes I made were adding Apple and Google Pay
```
> Could not find react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.71.0-rc.0/react-native-0.71.0-rc.0-release.aar
```
That URL is 404 by the way

**To Reproduce**
1. Open Android Studio
2. Try and run app with Google Pay set up using debug or release build in the simulator
3. Build fails... 

**Expected behavior**
I would expect when you try and run your app in the Android Studio emulator for debug it would build

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.2

**Smartphone (please complete the following information):**
 - Device: Android studio emulators
 - OS: API 30 and 31

**Additional context**
When I look for like past issues I find [#1186](https://github.com/stripe/stripe-react-native/issues/1186) but ```android/build.gradle``` is set to ```mavenCentral()``` 

The error that crashes the build

```
6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':stripe_stripe-react-native:generateDebugRFile'.
> Could not resolve all files for configuration ':stripe_stripe-react-native:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.71.0-rc.0/react-native-0.71.0-rc.0-debug.aar


```

and so on

**Comment by russmenum** [comment]
Not sure if this will work for all but found [this](https://stackoverflow.com/questions/74334162/react-native-android-build-failure-with-different-errors-without-any-changes-in)

```
buildscript {
    // ...
}


allprojects {
    repositories {
       exclusiveContent {
           filter {
               includeGroup "com.facebook.react"
           }
           forRepository {
               maven {
                   url "$rootDir/../node_modules/react-native/android"
               }
           }
       }
        // ...
    }
}

```

Dose seem to have restored this building.

**Comment by charliecruzan-stripe** [comment]
Fixed in patch updates for React Native: https://github.com/facebook/react-native/issues/35210
