### ISSUE TITLE
[Android] Field validation shows 'error' too quickly.

### ISSUE THREAD

**Issue by michelleb-stripe** [stripe/stripe-react-native#122]
**Describe the bug**
Card payment using webhooks: A partially filled in date while still in focus should not be red if it could turn out to be valid.  However a year that starts with 1 could not be valid, but it doesn’t show an error.  The first part is a difference from the card token in the stripe-sdk

**To Reproduce**
Case 1:
1. Go to 'Card payment using webhooks'
2. Click on 'Month'
4. See that entering just '1', turns the field red even when still in focus.
I would expected that the field would not turn red until I had an unrecoverable error (like a month of 19), or I changed focus to another field and the date was incomplete.

Case 2:
1. Go to 'Card payment using webhooks'
2. Click on 'Credit card'
3. Enter 0, or 1, or 321.
4. See that entering just the number above turns the field red even when in focus.
I would expected that the field would not turn red until I had an unrecoverable error (like a card number of '5'), or I changed focus to another field and the number was incomplete.

**Smartphone:**
 - Device: Android emulator
 - OS: 10

**Additional context**
None

**Comment by arekkubaczkowski** [comment]
@michelleb-stripe it seems card numbers which starts from e.g. `0`, `123` are out of ranges defined in `DefaultStaticCardAccountRanges` class and because of that it makes this field invalid, can you confirm this?

**Comment by arekkubaczkowski** [comment]
and this piece of the code is responsible for that:
```
// CardNumberEditText.kt

 } else if (unvalidatedCardNumber.isPartialEntry(panLength) &&
                !unvalidatedCardNumber.isPossibleCardBrand()
            ) {
                // Partial card number entered and brand is not yet determine, but possible.
                isCardNumberValid = isValid // <- false
                shouldShowError = true // <- this makes card number text color red
```

**Comment by charliecruzan-stripe** [comment]
Closing this as the original issue is fixed (although it looks like there's some follow up to be done in `stripe-android`?)
