### ISSUE TITLE
Example Paypal screen not working

### ISSUE THREAD

**Issue by rn-senior** [stripe/stripe-react-native#1228]
Hi, I am testing the PayPal screen on this example app. but I am getting the following issue.

_Payment confirmation error Invalid payment_method_data[type]: must be one of acss_debit, affirm, afterpay_clearpay, alipay, au_becs_debit, bacs_debit, bancontact, blik, boleto, customer_balance, eps, fpx, giropay, grabpay, ideal, klarna, konbini, link, oxxo, p24, paynow, pix, promptpay, sepa_debit, sofort, us_bank_account, or wechat_pay_
 
 it's not working on both live and test mode.
 Please let me know how I can fix this issue.

**Comment by charliecruzan-stripe** [comment]
Hi there! Paypal is currently in private beta for some EU merchants. Let me know if you'd like to be opted in for this by sending me an email (charliecruzan@stripe.com)!

**Comment by filippoLeporati93** [comment]
Hi @charliecruzan-stripe! Is Paypal method still in private beta? There is no documentation about that. Thanks

**Comment by charliecruzan-stripe** [comment]
Hi @filippoLeporati93 ! Yes, it is

**Comment by marchingband** [comment]
@charliecruzan-stripe is the plan to make paypal available in stripe for the US/Canada? If so do you happen to know even a vague timeline? thank you!
