### ISSUE TITLE
Application Crash when reopening payment sheet after cancel button click in Expo [Stripe Mobile Payment Element]

### ISSUE THREAD

**Issue by anzeqar** [stripe/stripe-react-native#1232]
**Bug Description**
After clicking the pay button for the first time, the payment screen appears, when the cancel button is clicked and the pay button is clicked for the second time, the entire application crashes...

**To Reproduce**
1. Click on Pay Button
2. Payment Screen will appear, then click on the cancel button
3. Again click on Pay Button
4. See the Application crash

**Expected behavior**
Even after clicking the cancel button, stripe should show the payment sheet because the user hasn't even initiated payment. If it is a feature then it is recommended to fix it... As many users can click on the cancel button and try to pay again...

**Bug Screen Record**
https://user-images.githubusercontent.com/48426888/206173940-86c40e8d-e606-4408-8dfb-e94b8361a89e.mp4

**Smartphone**
 - Device: Samsung Galaxy
 - OS: Android 13 Stable
 - Expo Go v2.26.4
 - React Native v0.69.6

Note: The code has been taken from the [docs](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet) and integrated into the application...

**Comment by charliecruzan-stripe** [comment]
It's hard to help here without the code that clicking `Pay` is triggering, plus the logs from `adb logcat` would also be helpful in tracking the source of the error. FWIW i'm not able to reproduce this myself.

Please include the version of stripe-react-native as well

**Comment by anzeqar** [comment]
> It's hard to help here without the code that clicking `Pay` is triggering, plus the logs from `adb logcat` would also be helpful in tracking the source of the error. FWIW i'm not able to reproduce this myself.
> 
> Please include the version of stripe-react-native as well

@charliecruzan-stripe 

"@stripe/stripe-react-native": "0.13.1"
"expo": "^46.0.0"

I copy-pasted the code from the docs and did slight modifications...

The `intializePaymentSheet()` and `openPaymentSheet()` functions were copy-pasted from docs...

The `Pay` button is triggered by...

` <ButtonPro
                      onPress={async () => {
                          return openPaymentSheet();
                      }}
                    >
                      <Text>Pay</Text>
                    </ButtonPro>`

ButtonPro is just a pressable component with some styling inside `<StripeProvider>...</StripeProvider>`


Here is last few lines of `adb logcat` while running that bug part...

`12-07 23:21:09.128 28789 28981 I ReactNativeJS:   ephemeralKey: 'ek_test_YWNjdF8xTEQ0VmRGQlpadsfhfgdf4554mg4VDN2ZUFBQTZzRlhYRDFvY0FtSWw_00xpLdcBEo',
12-07 23:21:09.128 28789 28981 I ReactNativeJS:   customer: 'cus_MwDufgrtgfTVw0c',
12-07 23:21:09.128 28789 28981 I ReactNativeJS:   publishableKey: 'pk_test_51LD4VdFBZgYPmmYkGClH5PGK8xnnlgDCII4kiu16ceTvOuJcobm54dfdsf3434KMaALtdUfHgs4PHvZnW00xb92KRL6',
12-07 23:21:09.128 28789 28981 I ReactNativeJS:   token: '25ac5be194fe0f258d7f1ea40acd233423423423424234d9874ae097f8440ec9fe71d3e59f143453a4eadd0f114a58b0fadac460f2ce80afb254cba8aa8805464e597e727c',
12-07 23:21:09.128 28789 28981 I ReactNativeJS:   id: '6390d25324343234dfd8d538300' }
12-07 23:21:09.137 28789 28981 I ReactNativeJS: true
12-07 23:21:09.139 28789 28981 I ReactNativeJS: true
12-07 23:21:09.148 28789 28981 I ReactNativeJS: [ { k: 'K3211', o: '6390d25324343234dfd8d538300', f: 13.00 } ]
12-07 23:21:09.176 28789 28981 I ReactNativeJS: true
12-07 23:21:09.176 28789 28981 I ReactNativeJS: true
12-07 23:21:09.177 28789 28981 I ReactNativeJS: [ { k: 'K3211', o: '6390d25324343234dfd8d538300', f: 13.00 } ]
12-07 23:21:09.193 28789 28981 I ReactNativeJS: 'cus_MwDufgrtgfTVw0c', 'ek_test_YWNjdF8xTEQ0VmRGQlpadsfhfgdf4554mg4VDN2ZUFBQTZzRlhYRDFvY0FtSWw_00xpLdcBEo', 'pi_3MCRl3445FDfdfHgh654fsfs_sdfFGDFGzsSjD5jhy', 'pk_test_51LD4VdFBZgYPmmYkGClH5PGK8xnnlgDCII4kiu16ceTvOuJcobm54dfdsf3434KMaALtdUfHgs4PHvZnW00xb92KRL6'
`
###### Note: The `adb logcat` output had secret information hence I slightly modified values...

## Then after that application suddenly crashes without any error traced in adb logcat...

**Comment by charliecruzan-stripe** [comment]
Please share a link to a reproducible demo in Snack since this is occurring in Expo Go :)

**Comment by charliecruzan-stripe** [comment]
Hi @anzeqar , this is fixed if you upgrade to SDK 47 👍
