### ISSUE TITLE
Padding for Cardfield in android

### ISSUE THREAD

**Issue by gmalija-adopta** [stripe/stripe-react-native#1241]
**Describe the bug**
The issue is that in iOS we have padding Left and Right in CardField element, but in Android not.

**To Reproduce**

Just reproduce it by creating the element like this: 

                <CardField
                    autofocus
                    cardStyle={{
                        fontSize: 16,
                        fontFamily: 'Poppins-Regular',
                        textErrorColor: Color.text.red,
                        borderWidth: 2,
                        borderColor: Color.line.primarySoft,
                        borderRadius: 12
                    }}
                    style={{
                        width: '100%',
                        height: 56
                    }}
                    postalCodeEnabled={false}
                />

**Expected behavior**
Have the same behavior in ios and android (same padding)

**Screenshots**
ios:
![image](https://user-images.githubusercontent.com/97677514/207045919-a31f1a62-cef1-4be6-b13a-01f17b84cd26.png)

android:
![image](https://user-images.githubusercontent.com/97677514/207046115-5be6aa36-4228-42a4-b478-af4c9e5fc909.png)

Thanks!!

**Comment by charliecruzan-stripe** [comment]
Fixed in https://github.com/stripe/stripe-react-native/commit/48debb27de4b02d8309b4e42737be066cdf33835

**Comment by mikevercoelen** [comment]
@charliecruzan-stripe any idea when this will be released?

**Comment by charliecruzan-stripe** [comment]
Fix was released in [v0.23.0](https://github.com/stripe/stripe-react-native/releases/tag/v0.23.0)
