### ISSUE TITLE
[initPaymentSheet] Currency option on applePay > paymentSummaryItems

### ISSUE THREAD

**Issue by luluanacarla** [stripe/stripe-react-native#1246]
**Describe the bug**
Hi! So I'm using the Payment sheet, and I need the currency on apple pay sheet to be GBP, and not USD...can't find a field for that on the initPaymentSheet...I found on the `presentApplePay`, but I need on `initPaymentSheet`. Is this possible?

**To Reproduce**
This is my `initPaymentSheet` code: 
```
const { error, paymentOption } = await initPaymentSheet({
        customerId: data.customer,
        setupIntentClientSecret: data.setupIntent,
        customFlow: true,
        merchantDisplayName: 'Merchant Name',
        applePay: {
          merchantCountryCode: 'GB',
          paymentSummaryItems: [
            {
              paymentType: 'Recurring',
              intervalUnit: 'year',
              intervalCount: 1,
              startDate: 1672247728,
              label: 'Label',
              amount: '69.99',
            },
          ],
        },
        style: 'automatic',
        googlePay: { merchantCountryCode: 'GB', testEnv: true },
        returnURL: 'returnurl://returnurl',
      })

```
And this is what I see:
<img width="403" alt="Screenshot 2022-12-21 at 17 36 08" src="https://user-images.githubusercontent.com/16455407/208968656-2d518007-20ee-4e54-85d8-b68c113a1f78.png">

**Expected behavior**
Being able to change currency on initPaymentSheet > applePay

**Comment by charliecruzan-stripe** [comment]
Hi! Can you try setting the currency with the Payment Intent on the server side? e.g. in node this would look like:

```diff
const myPaymentIntent = await stripe.paymentIntents.create({
      amount: <some amount>,
+    currency: 'gbp',
      <other params>
})
```

**Comment by hrkls** [comment]
I'm having the same issue - the answer does not solve the problem.
In the original question, it uses setupIntentClientSecret, not paymentIntentClientSecret, and for setupIntent, it's impossible to set the currency.

**Comment by charliecruzan-stripe** [comment]
this is being tracked in https://github.com/stripe/stripe-react-native/issues/1333
