### ISSUE TITLE
Android Expo EAS build Fail ':app:lintVitalReportRelease'

### ISSUE THREAD

**Issue by vladis-c** [stripe/stripe-react-native#1247]
Eas build with expo and eas-cli on android fails with the following error

```
[stderr] FAILURE:
[stderr] Build failed with an exception.
[stderr] * What went wrong:
[stderr] Could not determine the dependencies of task ':app:lintVitalReportRelease'.
[stderr] > Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[stderr]    > Could not resolve com.stripe:stripe-android:20.16.+.
[stderr]      Required by:
[stderr]          project :app > project :stripe_stripe-react-native
[stderr]       > Failed to list versions for com.stripe:stripe-android.
[stderr]          >
[stderr] Unable to load Maven meta-data from https://www.jitpack.io/com/stripe/stripe-android/maven-metadata.xml.
[stderr]             > Could not GET 'https://www.jitpack.io/com/stripe/stripe-android/maven-metadata.xml'. Received status code 521 from server: 
```

Environment: 
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.4.0 => 0.4.0 
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: bare
 
```   
   One month ago I build the app successfully with the same environment mentioned above and `@stripe/stripe-react-native": "^0.19.0`. Today build fails. Also I updated the stripe package upto `"@stripe/stripe-react-native": "^0.22.1"` and same result.
   You can say that expo 46 supports lower versions of stripe, yes I know, but it worked in combination of expo 46 and stripe 19 a month ago. 
   
  Any solutions? Thank you!

**Comment by albertbatrshin** [comment]
It looks like Jitpack server is down
https://github.com/jitpack/jitpack.io/issues/5337

**Comment by vladis-c** [comment]
> It looks like Jitpack server is down [jitpack/jitpack.io#5337](https://github.com/jitpack/jitpack.io/issues/5337)

Ok, I see. Let's wait, and if it works and no other solution, then I close the issue later =)

**Comment by NxsHbb** [comment]
Jitpack server is down again.

You can try to build locally

`eas build -p android --profile development --local`

**Comment by ottob** [comment]
@charliecruzan-stripe why was jitpack was added in https://github.com/stripe/stripe-react-native/pull/1200/files#diff-ed8534ece8080a880075e103269eb1b9bdff22e8dfcf8427d7d977603292b889 ? It seems unrelated to the rest of that pr.

**Comment by firas1220** [comment]
> Jitpack server is down again.
> 
> You can try to build locally
> 
> `eas build -p android --profile development --local`

Same issue here! 😢 Do you get a working build locally?

**Comment by charliecruzan-stripe** [comment]
@ottob that's the example app, so it's not distributed ( it was used for testing).

This could depend on the order of your `repositories` set in `build.gradle`, aka:

```
repositories {
    repoA() //tries to fetch all from here.
    repoB() //if something fails on A, tries to fetch from here.
}
```

You can explicitly exclude com.stripe.stripe-android from being tried to fetch via Jitpack to see if that fixes it. something like:
```
maven { url 'https://jitpack.io/' } {
    content {
        excludeGroup("com.stripe:stripe-android")
    }
}
```

**Comment by sofian-io** [comment]
This dependency should really be removed if its possible for them to have such big down time with no response via support/twitter...

**Comment by affansk** [comment]
@sofian-io they are being irresponsible at least on twitter they should put some notice. by when this will get up

**Comment by cmejet** [comment]
Agree @affansk & @sofian-io  I have tried to even mention both jitpack and stripe on twitter and nothing.
I would be super interested to understand why that dependency to jitpack was added as mentioned above.

**Comment by charliecruzan-stripe** [comment]
> I would be super interested to understand why that dependency to jitpack was added as mentioned above.

No dependency on jitpack was added, I explained above that the diff linked is for our example app, it isn't distributed.

**Comment by ottob** [comment]
Thanks for pointing out that the reference was the example app, my bad.
Im using stripe-react-native with expo managed flow so I guess its an expo issue then. I have created an expo issue now: https://github.com/expo/expo/issues/20585

**Comment by charliecruzan-stripe** [comment]
No worries! Going to close this out since this repo doesn't depend on jitpack directly for our distributed package
