### ISSUE TITLE
Add support for returnKeyLabel and returnKeyType for CardField 

### ISSUE THREAD

**Issue by mayankpandav** [stripe/stripe-react-native#1249]
**Is your feature request related to a problem? Please describe.**
I want to dismiss keyboard at half fillup cardelements and I want to select card from the dropdown unless I tap returnkey I cant collapse my keyboard

**Describe the solution you'd like**
add props as a returnKeyLabel and returnKeyType

**Comment by mayankpandav** [comment]
@charliecruzan-stripe nope its not for particular post code its for whole input card field
assume I have two option one is dropdown which contain old added card another one is or section which contain cardfield unfortunately I tap on cardfield it will not let you down your keyboard until fillup all the card fields

**Comment by charliecruzan-stripe** [comment]
The numeric inputs on iOS don't have return key labels, but if you'd like to close the `<CardField />` input, then you should wrap your screen with `<StripeContainer keyboardShouldPersistTaps={false}> ... </StripeContainer>`. This way, whenever you tap outside of the keyboard, it will close the keyboard 👍 

This is the behavior of internal react-native components like TextInput

**Comment by manishnaruka** [comment]
I am facing this with zipcode. In countries like US, this open numeric keyboard but no "Done" button to hide the keyboard

**Comment by manishnaruka** [comment]
> hi @mayankpandav ! So this would specifically be for editing of the postal code, is that correct?


I am facing this with zipcode. In countries like US, this open numeric keyboard but there is no "Done" button to hide the keyboard
