### ISSUE TITLE
The new addressSheet appears to be not customizable on Android

### ISSUE THREAD

**Issue by julestruong** [stripe/stripe-react-native#1251]
**Describe the bug**
The addressSheet that was release 2 months ago seems to be not customizable on Android.
I'm just modifying the appearance and the primaryButtonColor, and look whats happening in the screens.

**To Reproduce**
1. Just followed the steps on this tutorial https://stripe.com/docs/elements/address-element?platform=react-native

**Expected behavior**

**Screenshots**
<img width="853" alt="Capture_decran_2023-01-04_a_16 16 20" src="https://user-images.githubusercontent.com/3956660/210612293-59f43564-69fa-4f73-8547-eb82b8ae09a9.png">

Happens on simulator and emulator Android

**Additional context**
```
  <AddressSheet
                visible={addressSheetVisible}
                onSubmit={async _addressDetails => {
                  // Make sure to set `visible` back to false to dismiss the address element.
                  console.log(_addressDetails)
                  setAddressSheetVisible(false)

                  // Handle result and update your UI
                }}
                onError={error => {
                  console.log(error)
                  if (error.code === AddressSheetError.Failed) {
                    console.log(error?.localizedMessage)
                  }
                  // Make sure to set `visible` back to false to dismiss the address element.
                  setAddressSheetVisible(false)
                }}
                appearance={{
                  primaryButton: {
                    colors: {
                      background: theme.callToAction,
                    },
                  },
                }}
                defaultValues={{
                  address: {
                    country: 'FR',
                    city: 'Paris',
                  },
                }}
                additionalFields={{
                  checkboxLabel: 'Save this',
                }}
                presentationStyle="popover"
                allowedCountries={['FR', 'BE', 'GB', 'US', 'CA', 'DE']}
                primaryButtonTitle={'Use this adqsddress'}
                sheetTitle={'Shipping Address'}
              />
```

**Comment by julestruong** [comment]
@charliecruzan-stripe is the appearance an IOS parameter ?

**Comment by julestruong** [comment]
Also, simple question, but why not add a customerID parameter and the address is automatically saved in Stripe ?

**Comment by charliecruzan-stripe** [comment]
hi @julestruong - interesting, this same code seems to be working for me on both platforms, see this screenshot:

<img width="985" alt="Screen Shot 2023-01-05 at 3 43 18 PM" src="https://user-images.githubusercontent.com/97612659/210876272-7a2f2ae4-f210-4eb1-93d2-ab730531d2aa.png">

What version of the library are you using?

**Comment by julestruong** [comment]
the last one : "@stripe/stripe-react-native": "0.22.1"

**Comment by charliecruzan-stripe** [comment]
Are you using Expo? Can you provide a link to a github repo i can use to reproduce the issue?

**Comment by julestruong** [comment]
I dont use expo, i have no time right now to make a reproductible repo.
Maybe i'll try next week sorry

**Comment by charliecruzan-stripe** [comment]
Any chance you were able to make a repro @julestruong ? I'm not able to get this behavior in a blank project or our test app
