### ISSUE TITLE
Android running Google Pay in test environment even in production build.

### ISSUE THREAD

**Issue by luizfelipefalcao** [stripe/stripe-react-native#1256]
Google Pay runs as expected in staging environment. Once in production environment ( even submitting a signed build to play store ) when trying a payment it returns a message: "App is currently running within a test environment. Transactions will not result in actual charge" 

1. Click on Google Pay button to follow the payment flow;
2. Even with a registered credit card you will see the above message. 

      if (!isGooglePaySupported) {
        Alert.alert(
          strings('quote_payment:p:androidpay_not_support'),
          strings('quote_payment:p:androidpay_not_support_text'),
          [{ text: 'OK', onPress: () => {} }],
        );
      }

      const { error, paymentMethod } = await createGooglePayPaymentMethod({
        amount: total,
        currencyCode: 'USD',
      });

      if (error) {
        dispatch(
          updateToastStatus({
            toastActive: true,
            toastMessage: error?.localizedMessage,
            toastStatus: 'danger',
          }),
        );
        return;
      }

**Comment by luizfelipefalcao** [comment]
Google Pay runs as expected in staging environment. Once in production environment ( even submitting a signed build to play store ) when trying a payment it returns a message: "App is currently running within a test environment. Transactions will not result in actual charge" 

Steps to reproduce the behavior:
1. Click on Google Pay button to follow the payment flow;
2. Even with a registered credit card you will see the above message. 

`
batch(async () => {
      if (!isGooglePaySupported) {
        Alert.alert(
          strings('quote_payment:p:androidpay_not_support'),
          strings('quote_payment:p:androidpay_not_support_text'),
          [{ text: 'OK', onPress: () => {} }],
        );
      }

      const { error, paymentMethod } = await createGooglePayPaymentMethod({
        amount: total,
        currencyCode: 'USD',
      });

      if (error) {
        dispatch(
          updateToastStatus({
            toastActive: true,
            toastMessage: error?.localizedMessage,
            toastStatus: 'danger',
          }),
        );
        return;
      }

      try {
        dispatch(updateIsLoading(true));
        const purchaseIntent = await PaymentService.purchaseIntent(
          quoteId,
          paymentMethod?.id,
        );

        let policy = await api.policy.getPolicy(purchaseIntent.policy.id);
        if (policy) {
          policy.isNewPurchase = true;
          setTimeout(() => {
            dispatch(
              updateToastStatus({
                toastActive: true,
                toastMessage: strings('p:policy_purchase_text'),
                toastStatus: 'success',
              }),
            );
          }, 1000);
          Vibration.vibrate();

          await dispatch(updatePolicyDetails(policy));
          onClose();
          navigation.popToTop();
          navigation.navigate('FinishPurchase');
        } else {
          dispatch(resetNewPolicy());
        }
      } catch (error) {
        console.log('error', error);
      } finally {
        dispatch(updateIsLoading(false));
      }
    });
`

**Comment by andcosta** [comment]
+1

**Comment by luizfelipefalcao** [comment]
Hey @charliecruzan-stripe thank your for your quick reposnse

**Comment by charliecruzan-stripe** [comment]
> `testEnv: true`

change this to `testEnv: false,` when you're going live

**Comment by luizfelipefalcao** [comment]
It worked for me, thank you @charliecruzan-stripe
