### ISSUE TITLE
On Android Device: How to disable the hardware back button when Stripe Payment Sheet is opened?

### ISSUE THREAD

**Issue by ausshadu** [stripe/stripe-react-native#1258]
**Describe the bug**
How to disable the back button on Android while the Payment Sheet is open?

**To Reproduce**
1. Try to make a payment with payment intent
2. `initPaymentSheet()` is called and initialized
3. `presentPaymentSheet()` is called and the payment sheet is presented
4. Now on Android, click on the hardware/on-screen back button - Payment sheet is dismissed. It should be dismissed only by clicking the X button on the sheet

**Expected behavior**
The payment sheet should be dismissed only by clicking the **X** button on the sheet

**Screenshots**
![image](https://user-images.githubusercontent.com/7588667/211992838-79858223-8fd2-4324-b102-ba8eb6529a8c.png)

**Smartphone (please complete the following information):**
 - Device: Samsung SM-A536E
 - OS: Android 13
 - Stripe SDK version: 0.21.0

**Comment by charliecruzan-stripe** [comment]
Hi! You can override this behavior (if you'd like to) using this API: https://reactnative.dev/docs/backhandler
