### ISSUE TITLE
[android] Version 0.23.0 requires The minCompileSdk (32) specified

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [stripe/stripe-react-native#1265]
**Describe the bug**
After downloading the library, the application no longer works, and the following error returns
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (32) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-31).
     Dependency: androidx.appcompat:appcompat-resources:1.5.1.

**Expected behavior**
The application was supposed to work before downloading the stripe, it was working

**Desktop (please complete the following information):**
 - OS: Android
 - Browser react native 65
 - Version 0.23.0

**Smartphone (please complete the following information):**
 - Device: android
 - OS: 31
 - Browser react native
 - Version 0.23.0

 react-native info

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.75 GB / 15.90 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.2 => 0.65.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by charliecruzan-stripe** [comment]
Hi! This is listed in the android prereqs- https://github.com/stripe/stripe-react-native#requirements
