### ISSUE TITLE
presentGooglePay() fails with length=0; index=0

### ISSUE THREAD

**Issue by russmenum** [stripe/stripe-react-native#1267]
**Describe the bug**
Following the documentation
```js
      const { error } = await presentGooglePay({
        clientSecret,
        forSetupIntent: false,
      });
  
      if (error) {
        Alert.alert("presentGooglePay", error.message + "\n" + error.code );

        return;
      }
      Alert.alert('Success', 'The payment was confirmed successfully.');
``` 
fails to launch to paysheet instead return the ```error.message``` of ```length=0; index=0```

**To Reproduce**
1. set up the payment intent
2. on an Android phone try and place google pay
3. fails with the above error

**Expected behavior**
I would expect this to present Google Pay so. user can check out per the documentation

**Desktop (please complete the following information):**
 - OS: [Android 12]

**Smartphone (please complete the following information):**
 - Device: have tried on pixel and Samsung phones

**Additional context**
This error tells me nothing about what ```presentGooglePay()``` thinks it needs, I have logged the ```clientSecret``` to verfiy it is there, and per doc and best practice can not even get here if ```await isGooglePaySupported({ testEnv: true }))``` and ```await initGooglePay()```  has not passed. 

Any help resolving this to show the google paysheet per doc would be of help

**Comment by charliecruzan-stripe** [comment]
Hi! This usually indicates an issue with your server-side stripe code. Check out these two issues that deal with the same problem:

- https://github.com/stripe/stripe-react-native/issues/633
- https://github.com/stripe/stripe-react-native/issues/874

Also- I recommend using the PlatformPay API instead :) https://github.com/stripe/stripe-react-native/blob/master/docs/Platform-Pay-Migration.md

**Comment by russmenum** [comment]
> Hi! This usually indicates an issue with your server-side stripe code. Check out these two issues that deal with the same problem:
> 
> * [Getting `length=0; index=0` as an error from presentGooglePay #633](https://github.com/stripe/stripe-react-native/issues/633)
> * [Getting length=0; index=0 as an error from presentGooglePay #874](https://github.com/stripe/stripe-react-native/issues/874)
> 
> Also- I recommend using the PlatformPay API instead :) https://github.com/stripe/stripe-react-native/blob/master/docs/Platform-Pay-Migration.md

1) If you wish us to use ```isPlatformPaySupported()``` the documentation for [Google Pay](https://stripe.com/docs/google-pay?platform=react-native#react-native-create-enable-google-pay) and [Apple Pay](https://stripe.com/docs/apple-pay) and [tipsi-stripe-migration-guide](https://github.com/stripe/stripe-react-native/blob/master/docs/tipsi-stripe-migration-guide.md) need to be updated to refelct that change

2) if this ```error``` means there is a server-side issue, what could it possibly be? I looked at the issues you linked to but they reference the integration. This is not a new setup, the only new code server side is the ```Create a Payment Intent``` For google we are using the same endpoint we used for Apple Pay, which successfully returns a ```clientSecret```.

When I look at the 2 documentation above the sole difference between the Apple Pay and Google Pay payment intent seems to be that the Google Pay one asks for ```'payment_method_types' => ['card']``` but it also says if that "this is also the default payment method if none are provided" so is it not the default?

This error is very non-discript, and if it is a serve side config issue why is the intent working for the Apple side?

**Comment by russmenum** [comment]
If anyone gets here: this was not server side

```js
const { error } = await presentGooglePay({
      clientSecret,
      forSetupIntent: false,
    });
```
from the documentation will result in this ```ERROR```

```js
const { error } = await presentGooglePay({
      clientSecret: clientSecret,
      forSetupIntent: false,
    });
```
Will launch the pay sheet
