### ISSUE TITLE
AddressSheet onSubmit function is triggering when sheet is closed

### ISSUE THREAD

**Issue by dexsnake** [stripe/stripe-react-native#1268]
**Describe the bug**
When the address sheet is open and you tap the x button to close the modal, it triggers the onSubmit function instead of the intended onError function. 

**To Reproduce**
```typescript
<AddressSheet
   visible={isAddressSheetVisible}
   sheetTitle="New address"
   additionalFields={{ phoneNumber: 'optional' }}
   onSubmit={(addressDetails) => saveAddress(addressDetails)}
   onError={() => setIsAddressSheetVisible(false)}
/>
```

**Expected behavior**
The component should trigger the onError function when the close button is tapped.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: 16.2

**Additional context**
The onError function does not trigger no matter how I interact with the modal

**Comment by charliecruzan-stripe** [comment]
Ah okay, looks like this happens when providing default values. This looks like an issue in stripe-ios, following up there. Thanks for the report!

**Comment by umarmirza20** [comment]
Hi I'm experiencing exactly same issue, has there been any update on this?

**Comment by charliecruzan-stripe** [comment]
Fixed in https://github.com/stripe/stripe-ios/pull/2656! Will be fixed in the next release of stripe-ios which stripe-react-native will automatically pick up
