### ISSUE TITLE
when Use CardForm Error 

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [stripe/stripe-react-native#1269]
**Describe the bug**
The bug when use CardForm Return this 
Binary XML file Line #9 in layout/stripe_card_form_view:
Binary XML File line #9 Error inflating calss com.google.android.material.card.MaterialCardView

**Comment by charliecruzan-stripe** [comment]
Hi! Please provide everything we ask for in the issue template :) then it's much easier to narrow down the cause of the bug

**Comment by xhirazi** [comment]
change AppTheme to MaterialTheme fix my issue
```
<style name="AppTheme" parent="Theme.Material3.Light.NoActionBar">
      <item name="colorPrimaryDark">@color/primary</item>
</style>
```
