### ISSUE TITLE
TypeError: null is not an object (evaluating '_NativeStripeSdk.default.getConstants')

### ISSUE THREAD

**Issue by gaurav27ats** [stripe/stripe-react-native#1270]
**Describe the bug**
I have this error when a build my project on ios simulator: TypeError: null is not an object (evaluating '_NativeStripeSdk.default.getConstants')

I tried to setup stripe-react-native on a new react-native project and it works without problem but not on mine.

**To Reproduce**
1. run the project on android
2. getting errors in metro

**Expected behavior**
To build without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/66780743/214026078-009c9eb5-cb58-4c42-bc3c-520c4a9be1bf.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Smartphone (please complete the following information):**
 - Device: android
 - OS: android
 - Version 12

```
"@stripe/stripe-react-native": "^0.23.0",
 "react": "^16.0.0",
 "react-native": "^0.65.1",

```
Please help me to resolve this issue
Thanks in advance 🙏🙏🙏

**Comment by charliecruzan-stripe** [comment]
Are you using Expo? This looks like the JS you're using doesn't match the native code that is expected. If you're not using Expo, I would try clearing gradle caches and rebuilding the app

**Comment by ejkkan** [comment]
This is happening for me too on iOS.
"@stripe/react-stripe-js": "^1.16.4",
    "@stripe/stripe-js": "^1.46.0",
    "@stripe/stripe-react-native": "^0.23.3",
"expo": "~47.0.12",

**Comment by charliecruzan-stripe** [comment]
If you're using Expo SDK 47 you need to use v0.19.0 of this library: https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0190---2022-09-16--expo-sdk-47. Please follow [Expo's documentation here](https://docs.expo.dev/versions/latest/sdk/stripe/).

Also- `@stripe/react-stripe-js` and `@stripe/stripe-js` are not React Native compatible.

**Comment by mburakkalkan** [comment]
Hi @charliecruzan-stripe, I am trying to setup @stripe/stripe-react-native but getting the same error. I have this configuration:

```
react-native: 0.61.3 (not using expo)
react: 16.11.0
@stripe/stripe-react-native: 0.24.0
-----------------------
minSdkVersion = 22
compileSdkVersion = 33
targetSdkVersion = 33
```

It builds successfully, then installs the apk, but gives this error when launching the app after bundling.

![image](https://user-images.githubusercontent.com/4182925/220700946-067fae90-a39e-4afc-a30a-896debea3633.png)

Any suggesstions?

**Comment by charliecruzan-stripe** [comment]
> `react-native: 0.61.3`

as of v0.8.0, you need to use RN 64: https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#080---2022-04-27

**Comment by Kishore-D18** [comment]
Hey @charliecruzan-stripe i have the same issue in ios simulator. even after RN is 64

dependencies:
"@stripe/stripe-react-native": "^0.19.0",(not using expo)
"react-native": "0.64.0",
"react": "17.0.1"

ios deployment target:
platform :ios, '12.0'

**Comment by khoand04** [comment]
> Hey @charliecruzan-stripe i have the same issue in ios simulator. even after RN is 64
> 
> dependencies: "@stripe/stripe-react-native": "^0.19.0",(not using expo) "react-native": "0.64.0", "react": "17.0.1"
> 
> ios deployment target: platform :ios, '12.0'

I get same issues, anyone can help?

**Comment by kalaanjali19** [comment]
Describe the bug
I have this error when a build my project on ios simulator: TypeError: null is not an object (evaluating '_NativeStripeSdk.default.getConstants')

I tried to setup stripe-react-native on a new react-native project and it works without problem but not on mine.

To Reproduce
Steps to reproduce the behavior:

run the project on android
getting errors in metro
See error

**Comment by viethung0823** [comment]
any updates on this?
