### ISSUE TITLE
Enable Appearance setting for GooglePayButton as well

### ISSUE THREAD

**Issue by alex-vasylchenko** [stripe/stripe-react-native#1276]
**Is your feature request related to a problem? Please describe.**
Currently only the ApplePayButton can be styled.

**Describe the solution you'd like**
Add ability to change styles between DARK and WHITE for GooglePayButton.

**Comment by charliecruzan-stripe** [comment]
Google has strict guidelines around what options the button can have. If you'd like a white themed button, you'd have to use the `PlatformPayButton` with `type={GooglePayMark}`

As for `isLoading`, you should be able to add that in by wrapping the `PlatformPayButton` with another component
