### ISSUE TITLE
"Failed: There was an unexpected error -- try again in a few seconds" while using createPaymentMethod.

### ISSUE THREAD

**Issue by Karniej** [stripe/stripe-react-native#1277]
**Describe the bug**
I'm using a CardField component to pay for services and using createPaymentMethod to add it to stripe and 2-3 months later it doesn't work and I get this strange error: `"Failed There was an unexpected error -- try again in a few seconds"` without any error code. 

**To Reproduce**

This is the method I'm calling, while using CardField: 
`	const { paymentMethod, error } = await createPaymentMethod({
			paymentMethodType: 'Card',
		});`

Carfield component:

```
    <CardField
         postalCodeEnabled={false}
         autofocus
         onCardChange={(cardInfo) => {
            setCardDetails(cardInfo);
         }}
          onFocus={(focusedField) => console.log('focusField', focusedField)}
     />

```

I'm using the newest version of stripe-react-native: 23.01

**Expected behavior**
I  expect to have returned paymentMethod by `createPaymentMethod` function so I can pass it to confirmPayment function. 

**Additional context**
It used to work and also there's no other issue with Stripe, the payment goes through with pre-saved card.

**Comment by charliecruzan-stripe** [comment]
Is this happening on Android or iOS? Is `cardInfo.complete` true?

**Comment by Karniej** [comment]
> Is this happening on Android or iOS? Is `cardInfo.complete` true?

It's happening on iOS, cardInfo.complete true ? Where it says I should add it? 
Also I have an issue with pre-saved card not going through too now, which all of a sudden needs "paymentMethod" to be added to `confirmPayment` function while I pass the paymentMethodID from presaved credit card to it.

**Comment by Alecinvader** [comment]
> > Is this happening on Android or iOS? Is `cardInfo.complete` true?
> 
> It's happening on iOS, cardInfo.complete true ? Where it says I should add it? Also I have an issue with pre-saved card not going through too now, which all of a sudden needs "paymentMethod" to be added to `confirmPayment` function while I pass the paymentMethodID from presaved credit card to it.

Had a similar issue in the [https://github.com/flutter-stripe/flutter_stripe](https://github.com/flutter-stripe/flutter_stripe) library. Not sure how this translates in the react plugin, but a possible fix may be to initialize the Stripe instance without a `stripeAccountId` and only init with parameters like `publishableKey` and `merchantIdentifier` etc..

**Comment by charliecruzan-stripe** [comment]
@Karniej can you let me know if you're passing in a `stripeAccountId` to the `StripeProvider` or `initStripe` call?

**Comment by Karniej** [comment]
I found out that the issue was made by our backend not returning the correct values, preventing stripe from working properly. Closing :)

**Comment by emondd4** [comment]
@Karniej  Still Facing The Problem, working fine on ios emulator but giving exact the same error on real device.

**Comment by MatkoMilic** [comment]
For me fix was to change publishableKey prop to live key because in other places I have set live version but here I had it as test key:

<StripeProvider
      publishableKey="here I have put live key"
      merchantIdentifier="irrelevant"
    >
