### ISSUE TITLE
pod install is giving a minimum deployment target error when my app is set up correctly with iOS 13 as the min deployment target

### ISSUE THREAD

**Issue by MarkoVidalisBreez** [stripe/stripe-react-native#1280]
**Describe the bug**
When running pod install on my iOS project, after installing the stripe react native package with yarn, I am getting an error "Specs satisfying the `stripe-react-native (from `../node_modules/@stripe/stripe-react-native`)` dependency were found, but they required a higher minimum deployment target." but my minimum deployment target is iOS 13 as specified in the documentation.

**To Reproduce**
1. Create a new React Native project (I'm using the latest v0.71.1 of react native) without expo.
2. Run yarn install @stripe/stripe-react-native
3. Run cd ios && pod install
4. This is where I receive the error. 

**Expected behavior**
The package should be installed without issues. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS build running on Mac Mini M1 2020. Tried this with XCode 14 and also upgraded to 14.2 but with the same result. 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11 Pro Max
 - OS: [e.g. iOS8.1] iOS 16.2

**Additional context**
I'm migrating all my code from a RN 0.68.5 project into a new 0.71.1 project. I've started off by setting up the build schemes and installing dependencies in the application. There is quite a list of dependencies and all of them have gone fine except for this one. 
I tried installing the same version as the one that I had installed in my previous RN application, which was @stripe/stripe-react-native@0.21.0, but that actually gave me the same error as the latest version. 
I then tried increasing my deployment target on the iOS app to iOS 14 and 15 and 16 and each of them failed with the same error.

**Comment by charliecruzan-stripe** [comment]
> my minimum deployment target is iOS 13 as specified in the documentation.

Can you share your podfile?

**Comment by MarkoVidalisBreez** [comment]
Sure! Here it is 

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false
$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'Breez' do
  $static_framework = []
  
  config = use_native_modules!
  use_frameworks!
  rn_maps_path = '../node_modules/react-native-maps'
  $static_framework += [
     'react-native-maps',
     'react-native-google-maps',
     'Google-Maps-iOS-Utils',
     'GoogleMaps',
     'RNPermissions',
     'Permission-LocationWhenInUse',
     'Permission-Notifications'
   ]
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"
  # Flags change depending on the env values.
  flags = get_default_flags()

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-') || $static_framework.include?(pod.name)
        def pod.build_type;
          # Uncomment the line corresponding to your CocoaPods version
          Pod::BuildType.static_library # >= 1.9
          # Pod::Target::BuildType.static_library # < 1.9
        end
      end
    end
   
  end
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  target 'BreezTests' do
    inherit! :complete
    use_frameworks!
  end

  post_install do |installer|

    installer.generated_projects.each do |project|
    
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
  end
end
end
```

**Comment by charliecruzan-stripe** [comment]
thanks! and where do you define `min_ios_version_supported`?

**Comment by MarkoVidalisBreez** [comment]
That's actually strange, thanks for pointing that out. I didn't create that variable - must be something new in RN. I changed it to 13.0 and it's installed now!

Thank you for your help :)

**Comment by charliecruzan-stripe** [comment]
Sure thing! Glad we were able to figure this one out, I'll close the issue now

**Comment by MDG-MMeksasi** [comment]
Hello @MarkoVidalisBreez how did you change **min_ios_version_supported** I tried to change it from Xcode but it didn't work

**Comment by MarkoVidalisBreez** [comment]
HI @MDG-MMeksasi,

It was included at the top of my podfile as follows:

![image](https://user-images.githubusercontent.com/108470858/229900843-e1df7325-43f9-4bae-ab2e-da363ac99fac.png)

But there was no definition for the variable.
I replaced the variable with 13.0 as follows and it worked:

![image](https://user-images.githubusercontent.com/108470858/229900937-1ffb5401-fcf1-4473-a229-6eec3e3905e6.png)

**Comment by hussainarthuna** [comment]
After updating the **min_ios_version_supported** to static value it is working fine. But how can we make it dynamic?

**Comment by Pfuster12** [comment]
The variable is defined here:
`node_modules/react-native/scripts/react_native_pods.rb`

Lines 29 to 31 for me:
```rb
# This function returns the min iOS version supported by React Native
# By using this function, you won't have to manualy change your Podfile
# when we change the minimum version supported by the framework.
def min_ios_version_supported
  return '12.4'
end
```

Unfortunately I don't know much ruby if it's possible to override a variable definition in our own Podfile.

**Comment by elibroftw** [comment]
Solution that doesn't require modifying your node_modules.

Add the following (before the existing code comment) to your Podfile

```ruby
MIN_IOS_OVERRIDE = '13.0'
if Gem::Version.new(MIN_IOS_OVERRIDE) > Gem::Version.new(min_ios_version_supported)
    min_ios_version_supported = MIN_IOS_OVERRIDE
end
# existing code
platform :ios, min_ios_version_supported
```

**Comment by olie-chan** [comment]
In case anyone would like the code to read from the IPHONEOS_DEPLOYMENT_TARGET from the proj file

```ruby
#######
# Read min iOS version from Xcode project and set as min iOS version for Podfile
require 'xcodeproj'

project_path = './MyApp.xcodeproj'
project = Xcodeproj::Project.open(project_path)
min_ios_version_supported = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
######

platform :ios, min_ios_version_supported
```

**Comment by alienslab02** [comment]
> In case anyone would like the code to read from the IPHONEOS_DEPLOYMENT_TARGET from the proj file
> 
> ```ruby
> #######
> # Read min iOS version from Xcode project and set as min iOS version for Podfile
> require 'xcodeproj'
> 
> project_path = './MyApp.xcodeproj'
> project = Xcodeproj::Project.open(project_path)
> min_ios_version_supported = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
> ######
> 
> platform :ios, min_ios_version_supported
> ```

Worked like a charm. Thank you

**Comment by acarlstein** [comment]
Regrettably, I need a different solution. When I tried, all the dependencies started screaming different versions of `IPHONEOS_DEPLOYMENT_TARGET`, such as 7.0, 8.0, etc.

I tried to search in files and replace them to `14.0` but when I run `react-native ios` it keep happening.
I also tried running `pod install` in the `ios` folder prior running the `react-native ios` command but not luck.

I also tried via XCode but when I run `pod install` and `react-native ios` all the changes get wasted.

It would be nice to have some simple solution that allow us to setup the minimum target and take care of the rest but I guess that isn't the case. Anyone has a different solution?


```
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'react-native-pager-view' from project 'Pods')
```

**Comment by philelauria** [comment]
> Regrettably, I need a different solution. When I tried, all the dependencies started screaming different versions of `IPHONEOS_DEPLOYMENT_TARGET`, such as 7.0, 8.0, etc.
> 
> I tried to search in files and replace them to `14.0` but when I run `react-native ios` it keep happening. I also tried running `pod install` in the `ios` folder prior running the `react-native ios` command but not luck.
> 
> I also tried via XCode but when I run `pod install` and `react-native ios` all the changes get wasted.
> 
> It would be nice to have some simple solution that allow us to setup the minimum target and take care of the rest but I guess that isn't the case. Anyone has a different solution?
> 
> ```
> The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'react-native-pager-view' from project 'Pods')
> ```
> 
> ```
> > react-native --version
> react-native-cli: 2.0.1
> react-native: 0.72.6
> ```
> 
> ```
> Xcode
> Version 15.0.1 (15A507)
> ```

Have you tried opening your `project.pbxproj` and changing every `IPHONEOS_DEPLOYMENT_TARGET` value?

**Comment by acarlstein** [comment]
> > Regrettably, I need a different solution. When I tried, all the dependencies started screaming different versions of `IPHONEOS_DEPLOYMENT_TARGET`, such as 7.0, 8.0, etc.
> > I tried to search in files and replace them to `14.0` but when I run `react-native ios` it keep happening. I also tried running `pod install` in the `ios` folder prior running the `react-native ios` command but not luck.
> > I also tried via XCode but when I run `pod install` and `react-native ios` all the changes get wasted.
> > It would be nice to have some simple solution that allow us to setup the minimum target and take care of the rest but I guess that isn't the case. Anyone has a different solution?
> > ```
> > The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'react-native-pager-view' from project 'Pods')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > > react-native --version
> > react-native-cli: 2.0.1
> > react-native: 0.72.6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Xcode
> > Version 15.0.1 (15A507)
> > ```
> 
> Have you tried opening your `project.pbxproj` and changing every `IPHONEOS_DEPLOYMENT_TARGET` value?

Yes. I even when to the point where I search for all matches for `IPHONEOS_DEPLOYMENT_TARGET` and ensure they we updated.

Then, I gave up and started a new project by scratch.

**Comment by sleekLancelot** [comment]
> In case anyone would like the code to read from the IPHONEOS_DEPLOYMENT_TARGET from the proj file
> 
> ```ruby
> #######
> # Read min iOS version from Xcode project and set as min iOS version for Podfile
> require 'xcodeproj'
> 
> project_path = './MyApp.xcodeproj'
> project = Xcodeproj::Project.open(project_path)
> min_ios_version_supported = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
> ######
> 
> platform :ios, min_ios_version_supported
> ```

Do i have to delete the podlock file and build folder after doing this?
Just adding this still and doing a pod install gives the same error.

**Comment by GNUGradyn** [comment]
```
In case anyone would like the code to read from the IPHONEOS_DEPLOYMENT_TARGET from the proj file

#######
# Read min iOS version from Xcode project and set as min iOS version for Podfile
require 'xcodeproj'

project_path = './MyApp.xcodeproj'
project = Xcodeproj::Project.open(project_path)
min_ios_version_supported = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
######

platform :ios, min_ios_version_supported
```
I know this thread is old but ive been wrestling with this for days and was wanting to cry from not being able to figure out a good solution. thank you

**Comment by kheitkamp** [comment]
After `npx react-native run-ios` I receive the following warning:
`warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'RNCAsyncStorage' from project 'Pods')
`

I've added the suggested code snippet:
`#######
# Read min iOS version from Xcode project and set as min iOS version for Podfile
require 'xcodeproj'

project_path = './MyApp.xcodeproj'
project = Xcodeproj::Project.open(project_path)
min_ios_version_supported = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
######

platform :ios, min_ios_version_supported`
while changing `MyApp.xcodeproj` to the name of my project

before it was:
`platform: ios, 13.0`

I also checked project.pbxproj, but all occurrences of 'IPHONEOS_DEPLOYMENT_TARGET' are set either to 15.0 or 13.0

Does anyone has another idea where to look else?

**Comment by seba9999** [comment]
If you're still searching for the value of your `min_ios_version_supported` in `react-native@0.80.2`
It has changed location and is now in : `/node_modules/react-native/scripts/cocoapods/helpers.rb` near line 83 :
```rb
def self.min_ios_version_supported
    return '15.1'
end

def self.min_xcode_version_supported
    return '15.1'
end
```

**Comment by Jamal-Ud-Din-hub** [comment]
+1 

it needs to be dynamic

**Comment by Jamal-Ud-Din-hub** [comment]
> If you're still searching for the value of your `min_ios_version_supported` in `react-native@0.80.2` It has changed location and is now in : `/node_modules/react-native/scripts/cocoapods/helpers.rb` near line 83 :
> 
> def self.min_ios_version_supported
>     return '15.1'
> end
> 
> def self.min_xcode_version_supported
>     return '15.1'
> end

but this needs to be dynamic, reading it from the **Build settings**

**Current solution:**

```
#######
# Read min iOS version from Xcode project and set as min iOS version for Podfile
require 'xcodeproj'

project_path = './appname.xcodeproj' #replace appname 
project = Xcodeproj::Project.open(project_path)

target = project.targets.find { |t| t.name == "appname" } || project.targets.first ###replace appname 

config = target.build_configurations.find { |c| c.name == "Release" } ||
         target.build_configurations.find { |c| c.name == "Debug" }

min_ios_version_supported = config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"].to_s
######

platform :ios, min_ios_version_supported
```

This is related to `react-native` itself not `stripe`
