### ISSUE TITLE
Closing PaymentSheet

### ISSUE THREAD

**Issue by ElSeniorMikael** [stripe/stripe-react-native#1283]
**Is your feature request related to a problem? Please describe.**
My probleme is that i have a timer on my cart, so after 15 minutes my cart is getting clear but the Stripe payment sheet stay open

**Describe the solution you'd like**
A way to close stripe payment sheet

Or

Maybe an timeout option on the payment sheet so i can cancel it after a delay

**Comment by charliecruzan-stripe** [comment]
closing this as a duplicate of https://github.com/stripe/stripe-react-native/issues/724
