### ISSUE TITLE
Android - paymentSheets get into background mode

### ISSUE THREAD

**Issue by ElSeniorMikael** [stripe/stripe-react-native#1285]
**Describe the bug**
I'm not sure, if that's new but have the payment sheet always been on background mode on Android device ? It seems like only Android get into background mode whenever stripe open, is it the normal behavior of stripe on Android ?

**To Reproduce**
Init paymentsheet on android => device get in background mode

**Expected behavior**
The same as iOs where that the app doesnt get on background mode

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - React-native 0.71.2
 - @strippe/stripe-react-native 0.23.1

**Additional context**

**Comment by charliecruzan-stripe** [comment]
@ElSeniorMikael what do you mean by "background mode"?

**Comment by ddiazFG** [comment]
@charliecruzan-stripe I think he refers to [app state](https://reactnative.dev/docs/appstate), when stripe presents the bottom sheet, in android, the application goes from active to foreground.
