### ISSUE TITLE
Support for React Native 0.71

### ISSUE THREAD

**Issue by talaikis** [stripe/stripe-react-native#1288]
**Describe the bug**

Unable to build version 0.20+ successfully on RN 0.71.

```
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

**To Reproduce**

1. Start latest RN.
2. Install 0.20+ Stripe
3. `npm run android`

**Expected behavior**

Working builds on RN 0.71

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 0.20+

**Additional context**

Maybe related to Kotlin version (needs 1.7.0 for RN0.71)

**Comment by varemenos** [comment]
Having the same issue on CI, was working just fine on Thursday but suddenly today this error appeared today without any changes done to our codebase.

**Comment by roland-cubicfox** [comment]
Same issue here. 
"react-native": "0.70.6", 
"@stripe/stripe-react-native": "^0.23.1",

**Comment by fviak** [comment]
We're getting a similar error too. last Friday we could build 0.23.1 fine. Now that we upgraded to 0.23.2 we're getting errors like: 
`Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

- Expo 47
- React native 0.70.5
- "@stripe/stripe-react-native": "^0.23.2"

**Comment by ElSeniorMikael** [comment]
I have the issue since this morning, i can't build on Android anymore. See my screen for details about the crash

<img width="961" alt="Screenshot 2023-02-07 at 12 05 30 PM" src="https://user-images.githubusercontent.com/73765089/217313761-7fdb7e1f-c371-4edc-8e02-6ee5c3da2c3c.png">

**Comment by charliecruzan-stripe** [comment]
I think this might have to do with a recent release of stripe-android that we're picking up automatically, will look into this today

**Comment by varemenos** [comment]
Don't wanna dilute the conversation but is there a reason that something like this would happen?

I'm not familiar with Gradle or Android but shouldn't the dependencies be locked to specific versions to avoid situations like this one?

Feel free to ignore my comment or mark it as off-topic, I'm just curious about the process in general.

**Comment by charliecruzan-stripe** [comment]
Hey all, I've got a fix on the way but in order to unblock your development, you can use this workaround:

in your `android/app/build.gradle` file, add this block above your `dependencies {*}` block:

```
// workaround for https://github.com/stripe/stripe-react-native/issues/1288
// Remove once @stripe/stripe-react-native is ugpraded
configurations {
    compileClasspath {
      resolutionStrategy.force "com.stripe:stripe-android:20.19.1"
      resolutionStrategy.force "com.stripe:financial-connections:20.19.1"
    }
}
```

This will lock stripe-android (a dependency of stripe-react-native) to the previous version. Once the fix is out, you can remove this block

**Comment by charliecruzan-stripe** [comment]
@varemenos that's a great question- this should **not** happen. We soft match the version of stripe-android to the minor version, meaning stripe-react-native automatically picks up bug fixes (as in, we pin stripe-android v20.1.X, so it picks up any new version up to **but not including** v20.2.0. Usually this works well for us, but it _looks_ like a new feature was added but only released in a patch release, which caused kotlin to shout about missing `if else` branches.

If you're running into this issue and looking for a workaround, refer to my previous comment. However, we'll publish a fix ASAP to unblock folks. thanks everyone for reporting this so quickly!

**Comment by ElSeniorMikael** [comment]
@charliecruzan-stripe, just to make sure, do i have to upgrade my kotlin to 1.8.0 even with that block you gave us as workaround ?

**Comment by ElSeniorMikael** [comment]
Did i do something bad here ? i can make the workaround working ..

i did set up kotlinVersion = "1.8.0" at line 15

and added classpath at line 23

<img width="668" alt="Screenshot 2023-02-07 at 1 55 12 PM" src="https://user-images.githubusercontent.com/73765089/217339284-152d1e88-f961-4f59-b1f7-35c7a4249e58.png">

and there is a preview of where i did enter the workaround provided. line 197 to 202
<img width="787" alt="Screenshot 2023-02-07 at 1 54 31 PM" src="https://user-images.githubusercontent.com/73765089/217339134-860b064d-fbc8-40fa-a686-023f7bd6c242.png">

and i'm receiving this message whenever i build

```
e: file:///Users/michaellabelle/Documents/apps/rabaischocs/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentLauncherFragment.kt:256:12 'when' expression must be exhaustive, add necessary 'CashAppRedirect' branch or 'else' branch instead
e: file:///Users/michaellabelle/Documents/apps/rabaischocs/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt:453:3 'when' expression must be exhaustive, add necessary 'CashAppRedirect' branch or 'else' branch instead
```

**Comment by ElSeniorMikael** [comment]
UPDATE:: i fixed my problem without the workaround, after i few research inside the stripe source code i realised that the version is fetched while the build from our root build.gradle with the terms stripeVersion. so instead adding the whole block i just added the stripeVersion as follower.

in my android/build.gradle i declared an property inside =>

```
buildscript {
    ext {
        ***
        kotlinVersion = "1.8.0"
        stripeVersion = "20.19.1"
    }
***
}
```

**Comment by charliecruzan-stripe** [comment]
thanks @ElSeniorMikael , that would work as well

**Comment by charliecruzan-stripe** [comment]
Released in v0.23.3

**Comment by mourmukut** [comment]
Still getting issue in react version 0.70.6 getting build filed error. also tried downgrading the version but this didnt worked

**Comment by pskr** [comment]
Also still getting the issue with react-native version 0.71.3 with stripe-react-native 0.23.3.

**Comment by ErickJ3** [comment]
getting error with react-native 0.70.5 with stripe/stripe-react-native 0.26.0

**Comment by pskr** [comment]
I've managed to fix the error by specifying the kotlinVersion in expo-build-properties plugin.
`
      [
        "expo-build-properties",
        {
          "android": {
            "kotlinVersion": "1.8.0"
          }
        }
      ],
`

"react-native": "0.71.6"
"@stripe/stripe-react-native": "0.23.3"

**Comment by hmadJutt** [comment]
Just downgrade your stripe to v0.22.0. works for me

**Comment by AstrOOnauta** [comment]
Into `android/build.gradle`, I just updated my `kotlinVersion` and `kotlin_version` from `1.6.21` to `1.8.0`.
