### ISSUE TITLE
 Duplicate class com.google.android.play.core.common

### ISSUE THREAD

**Issue by DzungNTD** [stripe/stripe-react-native#1292]
![image](https://user-images.githubusercontent.com/94880575/217614181-83da73e6-0d93-4c42-b791-6bccc0551426.png)

**Comment by charliecruzan-stripe** [comment]
I would recommend [searching your gradle dependency tree](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html) for `com.google.android.play`, with just this screenshot I'm not sure this is problem with the stripe-react-native library. If you haven't yet, an easy fix might be to clear android's gradle caches and rebuild (but there also might be two dependencies of yours pulling in those two versions of the libraries, in which case clearing the cache won't fix it)
