### ISSUE TITLE
Expo Application Services Build fails for Android on latest version 0.23.3 

### ISSUE THREAD

**Issue by JHCover** [stripe/stripe-react-native#1293]
"expo": "^47.0.0",
    "@stripe/stripe-react-native": "0.23.3",

This is the log from the "Run Fastlane" portion of EAS build. 
[failedRunFastlaneLog.txt](https://github.com/stripe/stripe-react-native/files/10690472/failedRunFastlaneLog.txt)

**Comment by charliecruzan-stripe** [comment]
Those look like logs for an iOS build
