### ISSUE TITLE
Unable to just add a bank account with stripe in react native

### ISSUE THREAD

**Issue by szercorp** [stripe/stripe-react-native#1296]
In my company we have a delivery app and i want to implement with stripe to add the bank account of a user. The only thing i found in the docs is to only add a card for future charge. I just want to add a bank account.

**Comment by charliecruzan-stripe** [comment]
I think this is what you're looking for- https://stripe.com/docs/financial-connections/other-data-powered-products?platform=react-native

**Comment by Hosam-hsm** [comment]
@charliecruzan-stripe Hi, is this feature available in India?
