### ISSUE TITLE
Apple pay Button not showing in the Real device.

### ISSUE THREAD

**Issue by salmandayal** [stripe/stripe-react-native#1299]
**Describe the bug**
Hi, After successfully following the stripe documentation for Apple pay integration. Apple pay button is not showing up in Real device its only visible in the simulator and it works just fine in simulator

```
 const initialisePaymentSheet = async () => {
    const {paymentIntent, ephemeralKey, customer} =
      await fetchPaymentSheetParams(400);
    // console.log('Fetch check', {paymentIntent, ephemeralKey, customer});
    const {error} = await initPaymentSheet({
      merchantDisplayName: merchantName,
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,
      applePay: {
        merchantCountryCode: 'AE',
      },
      googlePay: {
        merchantCountryCode: 'AE',
        currencyCode: 'aed',
        testEnv: true,
      },
    });
    if (error) {
      console.log('initPaymentSheet Error: ', error);
    }
  };
```

**To Reproduce**

**Expected behavior**
Apple pay button should show in Real device when "presentPaymentSheet" is invoked.

**Screenshots**

**Desktop (please complete the following information):**
 - Version: 0.23.3

**Smartphone (please complete the following information):**
 - Device: Iphone XS Max
 - OS: IOS 13.2

**Additional context**

**Comment by charliecruzan-stripe** [comment]
Do you have a card added to your wallet?

**Comment by salmandayal** [comment]
No, Is that the real cause of it?

**Comment by charliecruzan-stripe** [comment]
It could be- could you try and see if adding a card to your device works?

**Comment by salmandayal** [comment]
Okay, Is it necessary that your country should match the merchant's location?

**Comment by charliecruzan-stripe** [comment]
No

**Comment by salmandayal** [comment]
I am trying to add test card provided by apple in Apple Pay but those just stuck while activation in Apple Wallet. I might add an active card and try things. Closing for now. Thanks
