### ISSUE TITLE
Stripe compatibility issue with React native 0.64.1 version

### ISSUE THREAD

**Issue by Vishujain1** [stripe/stripe-react-native#1303]
My React native project is on 0.64.1 version and i am trying to setup Stripe on different version 0.19.0 ,0.16.0 and 0.8.0  but when i install the package the build failed and get the same  error.
![Screen Shot 2023-02-17 at 2 40 42 PM](https://user-images.githubusercontent.com/125362603/219602187-5fd67cd0-9fc8-4a35-bc07-ea57615c7a42.png)

**Comment by charliecruzan-stripe** [comment]
Hi! Please take a look at [this troubleshooting section](https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios)

**Comment by Vishujain1** [comment]
Hi! I got this error
**Library not found for -lCocoaAsyncSocket**

**Comment by charliecruzan-stripe** [comment]
Sounds like you need to clean your Xcode build folder, maybe clear pods & reinstall them as well. But this doesn't seem to be an issue with the Stripe React Native library
