### ISSUE TITLE
Card field not showing on some Android devices

### ISSUE THREAD

**Issue by h-dung-95** [stripe/stripe-react-native#1309]
Has anyone encountered a similar case?
What is the solution here?
Thanks!

**Comment by h-dung-95** [comment]
I'm using "@stripe/stripe-react-native": "^0.22.1", for my react-native application.
This code:
<CardField
						postalCodeEnabled={false}
						placeholders={{
							number: '4242 4242 4242 4242'
						}}
						cardStyle={{
							textColor: colors.black
						}}
						style={{
							height: 50,
							marginVertical: 16,
							borderWidth: 1,
							borderColor: colors.VDC_normal_grey_2,
							borderRadius: 8
						}}
					/>

**Comment by charliecruzan-stripe** [comment]
Hi! You'll need to add a `width`
