### ISSUE TITLE
can not use confirmAcssDebitPayment method to accept a pre-authorised debit in canada

### ISSUE THREAD

**Issue by abhishekSutariya14** [stripe/stripe-react-native#1310]
**Describe the bug**
can not use confirmAcssDebitPayment method to accept a pre-authorised debit in canada As I used @stripe/stripe-react-native library and as per the docs [https://stripe.com/docs/payments/acss-debit/accept-a-payment?platform=web#web-collect-mandate-and-submit](url) they use stripe.confirmAcssDebitPayment() method to do that. However I can not use this method Please let me know how to do that?

**To Reproduce**
1. import {initStripe, useStripe} from '@stripe/stripe-react-native';
2. const stripe = useStripe();
3. stripe.confirmAcssDebitPayment()
4. See error undefined is not a function (near '...stripe.confirmAcssDebitPayment...')

**Comment by charliecruzan-stripe** [comment]
That documentation is for Stripe.js, the web library. This is the React Native library, and we don't support `acss_debit` yet: https://stripe.com/docs/payments/payment-methods/integration-options#support-bank-debits
