### ISSUE TITLE
How to use 'continue' variant in ApplePayButton

### ISSUE THREAD

**Issue by sn4f** [stripe/stripe-react-native#1312]
**Describe the bug**
Hi guys, I'm using the latest package version `0.24.0` and I'm trying to use 'continue' type for my Apple Pay button. But it doesn't work and shows me a plain version of this button. 

**To Reproduce**
Steps to reproduce the behaviour:
```
  <ApplePayButton
    type="continue"
  />
```

**Screenshots**
![Zrzut ekranu 2023-02-24 o 11 07 27](https://user-images.githubusercontent.com/8761149/221151430-be17be73-8e85-4c7d-b527-312f303958a0.png)
instead
<img width="228" alt="Zrzut ekranu 2023-02-24 o 11 09 21" src="https://user-images.githubusercontent.com/8761149/221151924-68fafae0-2fc7-422f-8e8a-3b353b4fad59.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.2

**Comment by charliecruzan-stripe** [comment]
`ApplePayButton` doesn't support that option, but `PlatformPayButton` does (it's a newer, cross platform version of ApplePayButton and GooglePayButton)

```
 <PlatformPayButton
          type={PlatformPay.ButtonType.Continue}
 />
```

**Comment by sn4f** [comment]
Thank you @charliecruzan-stripe
