### ISSUE TITLE
Cannot read property 'getConstants' of undefined

### ISSUE THREAD

**Issue by SeongwoonHong** [stripe/stripe-react-native#1313]
**Describe the bug**
when I'm running ios. it builds successfully but it got stuck on launching on the ios simulator

![Screen Shot 2023-02-25 at 12 13 28 PM](https://user-images.githubusercontent.com/19713918/221370387-dbaa11f8-3691-4f22-a0eb-339b940517f0.png)

**To Reproduce**
1. download @stripe/stripe-react-native: ^0.24.0
2. react-native: 0.66.5
3. run ios
4. see error on console

**Expected behavior**
being able to run ios with no error

**Screenshots**
![Screen Shot 2023-02-25 at 12 14 59 PM](https://user-images.githubusercontent.com/19713918/221370447-1bd4a7ac-02b7-4e0e-976b-4bf6b0aefa7c.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 14

**Additional context**
my package.json
```
 "@stripe/stripe-react-native": "^0.24.0",
 "react-native": "0.66.5",
 ```
 I even tried downloading@stripe/stripe-react-native to 0.23.0 however i'm getting the same error message.

**Comment by Youssouf-Ouedraogo** [comment]
I am facing similar issue any chance you got passed this?

**Comment by BrayhanV** [comment]
Hello! How did you solve this?

**Comment by pwddle** [comment]
Still having this issue
