### ISSUE TITLE
Can't build on android "Unresolved reference: isWhitespace" /reactnativestripesdk/utils/PostalCodeUtilities.kt:

### ISSUE THREAD

**Issue by mohamedmoawia** [stripe/stripe-react-native#1321]
**Describe the bug**
Can't build on android "Unresolved reference: isWhitespace" /reactnativestripesdk/utils/PostalCodeUtilities.kt:

**To Reproduce**
just install the package on the latest version 

**Expected behavior**
app should run 

**Additional context**
react-native: "0.71.2"
"react": "18.2.0"

   buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "20.1.5948944"
		kotlinVersion = "1.5.30"

**Comment by charliecruzan-stripe** [comment]
isWhitespace should be available on that kotlin version: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-whitespace.html

You might want to try either clearing caches or upgrading that

**Comment by Raymond-Cox** [comment]
I had the exact same issue as @mohamedmoawia with a nearly identical setup (ndkVersion only difference).

The resolution for me was to do as @charliecruzan-stripe suggested and upgrade the kotlin version. I took the latest:
`kotlinVersion = "1.8.10"`

After a clean and rebuild, it works fine 👍

**Comment by charliecruzan-stripe** [comment]
Awesome! thanks for the confirmation, I'll go ahead and close this out, but let me know if that doesn't work for you @mohamedmoawia
