### ISSUE TITLE
Running E2E tests with Detox on Android

### ISSUE THREAD

**Issue by philiplindberg** [stripe/stripe-react-native#1326]
I'm trying to configure some detox e2e tests for my react native app, but I can't figure out how to target the card fields inside the payment sheet on Android using [Detox matchers](https://wix.github.io/Detox/docs/api/matchers). On iOS, I'm able to use the `by.label` and `by.type` matchers to target each card field (see code snippet below), but I'm not sure what the equivalent matchers would be for Android.

I'd like to be able to target payment sheet card fields by some kind of ID or label so I can run e2e detox tests for both iOS and Android.

On iOS, I'm able to write tests like the following:

```ts
await element(by.label('Card number').and(by.type('UITextField'))).typeText('4242424242424242')
await element(by.label('expiration date').and(by.type('UITextField'))).typeText('12/25')
await element(by.label('CVC').and(by.type('UITextField'))).typeText('123')
await element(by.label('ZIP').and(by.type('UITextField'))).typeText('12345')
await element(by.type('_TtCC18StripePaymentSheet13ConfirmButton9BuyButton')).tap()
```

**Comment by charliecruzan-stripe** [comment]
Hi! You should be able to use the `testID` prop for this.

**Comment by charliecruzan-stripe** [comment]
Ah sorry about that! Was mistakenly assuming you were referring to `CardField` | `CardForm`

For Payment Sheet, you are correct in that you should be going by the text- [the native Stripe iOS library does the same in it's UI tests](https://github.com/stripe/stripe-ios/blob/master/Example/PaymentSheet%20Example/PaymentSheetUITest/PaymentSheetUITest.swift). Does detox's `by.label()` function not work for you on Android? FWIW we used to use detox for our e2e tests, and this was how we selected by label: https://github.com/stripe/stripe-react-native/blob/1bc3e06b92bb53d65c8fff559f98897cad8b8de3/e2e/helpers.ts#L14-L18

**Comment by philiplindberg** [comment]
Using detox's `by.label()` matcher doesn't seem to work on android (works fine on ios though). For example, the following matcher does **not** work on android:

```ts
await element(by.label('Card number')).typeText('4242424242424242') // doesn't work
```

Detox's `by.type()` and `by.text()` matchers don't seem to work either:

```ts
await element(by.type('android.widget.EditText[@text="Card number"]')).typeText('4242424242424242') // doesn't work
await element(by.text('Card number')).typeText('4242424242424242') // doesn't work
```

Detox's `by.label()` matcher **does** work on ios though:

```ts
await element(by.label('Card number').and(by.type('UITextField'))).typeText('4242424242424242') // does work
```

@charliecruzan-stripe any thoughts?

**Comment by charliecruzan-stripe** [comment]
Hm, i'm not sure why that wouldn't be working. Although it looks like this has happened in the past to detox: https://github.com/wix/Detox/issues/1539

**Comment by philiplindberg** [comment]
@yannisvetster Nope I never did.

**Comment by cunderw** [comment]
Since this issue was closed I opened another issue: https://github.com/stripe/stripe-react-native/issues/1504

This continue to be an ongoing issue and prevents e2e testing on android.
