### ISSUE TITLE
Cannot find type 'STDSTransaction' in scope

### ISSUE THREAD

**Issue by daylonball** [stripe/stripe-react-native#1327]
**Describe the bug**
Getting these errors in Xcode from stripe payments, no clue where it came from or what to do about it. Been searching the web for hours. 

**Screenshots**
![Screenshot 2023-03-14 at 7 13 34 PM](https://user-images.githubusercontent.com/31872541/225178795-ff56f93e-3a18-4cde-aaaf-729abd3c387f.png)

![Screenshot 2023-03-14 at 7 13 47 PM](https://user-images.githubusercontent.com/31872541/225178818-a96b565a-137f-4b4d-a662-806d7b92660c.png)

**Comment by charliecruzan-stripe** [comment]
Hi! Please provide the version of stripe-react-native you're using, and your Xcode version. If you fill out the issue template, that will give us all the information we need

**Comment by daylonball** [comment]
> 

Apologies, you can close this issue. I think it was a pod version issue on Xcode.

Removing podfile.lock, node_modules, cleaning the build folder, derived data, and reinstalling fixed this issue.
