### ISSUE TITLE
pressing enter in cardFiled number (lessthan or equal to 8 number) geeting crashed in android but working fine in ios

### ISSUE THREAD

**Issue by shashigit107** [stripe/stripe-react-native#1328]
migrating from tipsi-stripe to @Stripe/Stripe-react-native

"dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/checkbox": "^0.5.5",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.9",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-firebase/app": "^8.3.1",
    "@react-native-firebase/messaging": "^7.7.2",
    "@react-native-google-signin/google-signin": "^7.0.4",
    "@react-navigation/bottom-tabs": "^5.10.4",
    "@react-navigation/drawer": "^5.10.4",
    "@react-navigation/material-top-tabs": "^5.3.13",
    "@react-navigation/native": "^5.8.4",
    "@react-navigation/stack": "^5.12.1",
    "@stripe/stripe-react-native": "^0.2.4",
    "axios": "^0.21.1",
    "i": "^0.3.7",
    "moment": "^2.29.1",
    "npm": "^9.4.2",
    "react": "16.13.1",
    "react-instantsearch-native": "^6.12.1",
    "react-native": "0.63.4",
    "react-native-actions-sheet": "^0.5.1",
    "react-native-animated-splash-screen": "^2.0.5",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-aws3": "0.0.9",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-communications": "^2.2.1",
    "react-native-date-picker": "^2.7.10",
    "react-native-deep-linking": "^2.2.0",
    "react-native-draggable": "^3.3.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-geolocation-service": "^5.3.0-beta.1",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-html-to-pdf": "^0.10.0",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localization": "^2.1.6",
    "react-native-location-view": "^0.3.0",
    "react-native-maps": "0.27.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-multiple-select": "^0.5.6",
    "react-native-pager-view": "^5.2.1",
    "react-native-paper": "^4.7.0",
    "react-native-popup-menu": "^0.15.11",
    "react-native-progress-steps": "^1.3.4",
    "react-native-push-notification": "^8.1.0",
    "react-native-ratings": "^7.6.1",
    "react-native-reanimated": "2.2.0",
    "react-native-render-html": "^6.3.4",
    "react-native-root-siblings": "^4.1.0",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.12.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-switch": "^2.0.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-timeline-flatlist": "^0.7.6",
    "react-native-vector-icons": "^8.1.0",
    "react-native-view-pdf": "^0.11.1",
    "react-native-walkthrough-tooltip": "^1.2.0",
    "react-redux": "^7.2.2",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "rn-material-ui-textfield": "^1.0.9",
    "uninstall": "^0.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.2",
    "eslint": "^7.12.1",
    "jest": "^26.6.2",
    "jetifier": "^1.6.6",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "16.13.1"
  },

 const renderCardField = () => {
        return (
            <CardField
                postalCodeEnabled={false}
                placeholder={{ number: ' 4242424242424242' }}
                cardStyle={{
                    backgroundColor: '#FFFFFF',
                    textColor: '#000000',
                    paddingRight: 20
                }}
                style={{
                    width: "100%",
                    height: hp("5%"),
                    paddingRight: 0
                }}
                onCardChange={(valid) => {
                    console.log('valid----', valid)
                    // console.log('----params', params)
                    setCardObj(valid)
                    setCardValid(valid)
                }}
                onFocus={(focusedField) => {
                    console.log('focusField', focusedField);
                }}
            />
        )
    }

**Comment by shashigit107** [comment]
i Have Used this version also
 @stripe/stripe-react-native@0.2.3

**Comment by charliecruzan-stripe** [comment]
Hi! Please try to use a more recent version (0.26.0 is the latest), and this problem should be fixed 👍
