### ISSUE TITLE
Rounded GooglePay button not acceptable

### ISSUE THREAD

**Issue by salman-kryptomind** [stripe/stripe-react-native#1329]
**Describe the bug**
After submitting the app for review for Google Pay Review on Google Pay Console. My submission has been rejected due to rounded button of Google Pay. Example is below

![GooglePayIssue](https://user-images.githubusercontent.com/80668339/225643791-faaadf6c-5eca-4d54-bf2e-8c327edc39e0.jpeg)

This was review response. Google Brand guidelines have been reverted to reflect the rectangular asset and no longer the rounded Google Pay button.

![Screenshot 2023-03-16 at 7 06 31 PM](https://user-images.githubusercontent.com/80668339/225643475-dc2e4bb0-b0d7-432d-b9c6-5300d183c76b.png)

I have tried setting type to "pay" and "standard" as well.
**To Reproduce**

**Expected behavior**
App should be approved from Google

**Screenshots**
Google approval needs below rectangular buttons
![Screenshot 2023-03-16 at 7 15 21 PM](https://user-images.githubusercontent.com/80668339/225644945-3e3c44c1-5eac-4747-a270-13ad24492d6c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Everything is working fine this issue is related to style of the button as Google demands rectangular buttons now.

**Comment by charliecruzan-stripe** [comment]
Hi! It looks like Google just updated these assets a few days ago: https://developers.google.com/pay/api/android/guides/brand-guidelines

We'll update this on our side soon!

**Comment by salman-kryptomind** [comment]
Hey @charliecruzan-stripe, any update?

**Comment by salman-kryptomind** [comment]
![gPay](https://user-images.githubusercontent.com/80668339/230503670-cd314934-273f-447e-b74f-4b6531a10850.jpeg)

@charliecruzan-stripe I'm still seeing rounded button when I invoke the PaymentSheet.

**Comment by charliecruzan-stripe** [comment]
hey @salman-kryptomind , that actually needs to be updated in `stripe-android`. I'll let the team know!
