### ISSUE TITLE
CardForm labels text aren't visible when phone has dark mode

### ISSUE THREAD

**Issue by matthewmturner** [stripe/stripe-react-native#1330]
**Describe the bug**
It's very hard to read the labels and input text when phone is in dark mode. Light mode works okay. 

**To Reproduce**
1. Add CardForm component to app
2. Set phone to dark mode
3. Enter text in CardForm
4. Label and input text will be very light and hard to see

**Expected behavior**

**Screenshots**
Screenshots attached

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![image](https://user-images.githubusercontent.com/22136083/225667983-c606ba5e-09f3-45c0-b5b9-289d0ec8afa2.png)
**Additional context**
![image](https://user-images.githubusercontent.com/22136083/225667943-bad3673d-47c1-4644-b7fc-c09c1fb8dc1c.png)

**Comment by matthewmturner** [comment]
And on android the zip code label text is different color than the labels for the other fields
<img width="877" alt="image" src="https://user-images.githubusercontent.com/22136083/225701637-fcb2e57e-ed49-40c8-bd88-9abda6377f77.png">
<img width="877" alt="image" src="https://user-images.githubusercontent.com/22136083/225702157-7bb1d00b-925e-4391-b5cc-9b76bae9cc3a.png">

**Comment by charliecruzan-stripe** [comment]
Hi! You can use the `cardStyle` prop for this, but overall I would recommend using the `CardField` component instead. It is a much more updated component and has more customizability. 

Also related: https://github.com/stripe/stripe-react-native/issues/771

**Comment by keshavsharma0712** [comment]
@matthewmturner Any workaround you found for iOS devices in dark mode?

**Comment by gabriel11447** [comment]
@keshavsharma0712 I used this workaround:
`cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}`

**Comment by pavan-myana** [comment]
<key>UIUserInterfaceStyle</key>
<string>Light</string>

use this in info.plist file

**Comment by pavan-myana** [comment]
> [@matthewmturner](https://github.com/matthewmturner) Any workaround you found for iOS devices in dark mode?
```

<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

use this in info.plist file
