### ISSUE TITLE
> Task :stripe_stripe-react-native:lintDebug FAILED Lint found 18 errors, 451 warnings. First failure:

### ISSUE THREAD

**Issue by orjiAce** [stripe/stripe-react-native#1334]
**Describe the bug**
i got this error `> Task :stripe_stripe-react-native:lintDebug FAILED
Lint found 18 errors, 451 warnings. First failure:`

when I run `./gradlew build --warning-mode all`

**To Reproduce**
1. I stall stripe react native 0.19.0
2. cd android folder
3. run ./gradlew build --warning-mode all
4. See the error

**Expected behavior**
Build success

**Screenshots**
<img width="777" alt="Screenshot 2023-03-17 at 3 36 25 PM" src="https://user-images.githubusercontent.com/29933392/225935489-41ff8590-58ad-46aa-8898-27bf25f6c943.png">

<img width="777" alt="Screenshot 2023-03-17 at 3 35 55 PM" src="https://user-images.githubusercontent.com/29933392/225935326-cb745ecd-f537-4525-ba70-b07602e920dd.png">

**Additional context**
here is my package json

{
  "name": "bluetanks",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@gorhom/bottom-sheet": "^4",
    "@gorhom/portal": "^1.0.13",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-native-community/netinfo": "9.3.5",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@reduxjs/toolkit": "^1.8.2",
    "@stripe/stripe-react-native": "0.19.0",
    "axios": "^0.27.2",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "expo": "~47.0.12",
    "expo-apple-authentication": "~5.0.1",
    "expo-application": "~5.0.1",
    "expo-asset": "~8.7.0",
    "expo-auth-session": "~3.8.0",
    "expo-checkbox": "~2.2.2",
    "expo-constants": "~14.0.2",
    "expo-crypto": "~12.0.0",
    "expo-device": "~5.0.0",
    "expo-fast-image": "^1.1.3",
    "expo-font": "~11.0.1",
    "expo-haptics": "~12.0.1",
    "expo-image-picker": "~14.0.2",
    "expo-linear-gradient": "~12.0.1",
    "expo-linking": "~3.3.1",
    "expo-location": "~15.0.1",
    "expo-modules-autolinking": "~1.1.0",
    "expo-notifications": "~0.17.0",
    "expo-random": "~13.0.0",
    "expo-secure-store": "~12.0.0",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.4",
    "expo-system-ui": "~2.0.1",
    "expo-updates": "~0.15.6",
    "expo-web-browser": "~12.0.0",
    "formik": "^2.2.9",
    "moti": "^0.18.0",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-config": "^1.5.0",
    "react-native-dotenv": "^3.3.1",
    "react-native-error-boundary": "^1.1.14",
    "react-native-fast-image": "^8.6.3",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.3.2",
    "react-native-maps-directions": "^1.8.0",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-phone-call": "^1.2.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-svg": "13.4.0",
    "react-native-web": "~0.18.11",
    "react-query": "^3.39.1",
    "react-redux": "^8.0.2",
    "redux-persist": "^6.0.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.27",
    "@types/react-native": "~0.70.6",
    "jest": "^29.2.1",
    "jest-expo": "^48.0.0",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.9.4"
  },
  "resolutions": {
    "expo-modules-autolinking": "~0.8.1"
  },
  "private": true
}

**Comment by charliecruzan-stripe** [comment]
To unblock you on linting your own Android code, you could disable linting of your dependencies: https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/LintOptions (linting dependencies leads to quite a bit of extra computation, as stated in that doc)

**Comment by orjiAce** [comment]
yes i already added this

 ` lintOptions {
        disable 'NewApi'
        checkReleaseBuilds false
        abortOnError false
    }`

to my app/build.gradle file but I'm still getting the error
<img width="792" alt="Screenshot 2023-03-18 at 12 12 18 AM" src="https://user-images.githubusercontent.com/29933392/226067616-ca1d2c9b-40e0-4366-9f8d-0db6ade623ab.png">

**Comment by RonanLagan** [comment]
I'm getting the same error, any fix yet?

**Comment by orjiAce** [comment]
I opened the project in android studio, updated my gradle version, and updated my distributionURL in gradle-wrapper.properties 
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip`
everything is fine now
