### ISSUE TITLE
Getting issue in payment Successful alert

### ISSUE THREAD

**Issue by mourmukut** [stripe/stripe-react-native#1341]
I'm getting issue in getting a successful message after i click on pay a webPage opens and it autometicly come back to the app and does not give any alert of error or success and the ui of presentPaymentSheet remain open .

**Comment by charliecruzan-stripe** [comment]
Hi! You're probably not handling the return URL appropriately: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-set-up-return-url
