### ISSUE TITLE
When using customFlow: true in initStripe the error messages are not that helpful on confirmPaymentSheetPayment

### ISSUE THREAD

**Issue by enchorb** [stripe/stripe-react-native#1344]
**Describe the bug**
`Failed: There was an unexpected error -- try again in a few seconds`

Testing a custom payment flow (using a test key) and while Apple pay works, I get the above error when attempting to pay with a saved customer card.

This happens both on an actual device and also the simulator. 

**Expected behavior**
Works with both custom cards (ie. 4242 4242 4242 4242) and Apple Pay

**Comment by charliecruzan-stripe** [comment]
Hi! usually this is a problem with the payment intent itself. Please share everything we ask for in the template like your version & also how to reliably reproduce the error, that way we can help figure out what's going on

**Comment by enchorb** [comment]
If it was a problem with the payment intent why would the Apple Pay flow work, also additional info below

```
 "@stripe/stripe-react-native": "0.26.0"

System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 31.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/ankur/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 10.2.1 => 10.2.1 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by charliecruzan-stripe** [comment]
> If it was a problem with the payment intent why would the Apple Pay flow work

Not sure!

Thanks for the version info, please provide a code sample to reproduce this. I'm not able to reproduce in our test app.

**Comment by enchorb** [comment]
Closing, as the error was found. When using `customFlow: true` in `initStripe` the error messages are not that helpful on `confirmPaymentSheetPayment`. After setting `customFlow: false` the error message was my `returnURL` was not valid which I fixed and then set  `customFlow: true` again and it worked!

**Comment by charliecruzan-stripe** [comment]
> customFlow: true in initStripe the error messages are not that helpful on confirmPaymentSheetPayment

Thanks for letting me know! I'll look into that 🔍
