### ISSUE TITLE
Support auto-fill hints for CardFormView

### ISSUE THREAD

**Issue by hcq0618** [stripe/stripe-react-native#1348]
**Is your feature request related to a problem? Please describe.**
Support auto-fill hints for CardFormField, support it at least on Android

**Describe the solution you'd like**
auto-fill has already been supported on the Android side

as well as I looked into it from stripe-android source codes:
https://github.com/stripe/stripe-android/blob/a7730140b1b457f4f2cb6aad64550b8dfda98afd/payments-core/src/main/java/com/stripe/android/view/CardNumberEditText.kt#L162
https://github.com/stripe/stripe-android/blob/a7730140b1b457f4f2cb6aad64550b8dfda98afd/payments-core/src/main/java/com/stripe/android/view/ExpiryDateEditText.kt#L243
https://github.com/stripe/stripe-android/blob/a7730140b1b457f4f2cb6aad64550b8dfda98afd/payments-core/src/main/java/com/stripe/android/view/CvcEditText.kt#L48
https://github.com/stripe/stripe-android/blob/a7730140b1b457f4f2cb6aad64550b8dfda98afd/payments-core/src/main/java/com/stripe/android/view/PostalCodeEditText.kt#L53

**Describe alternatives you've considered**

**Additional context**
a similar issue which I reported to the android library https://github.com/stripe/stripe-android/issues/6274

**Comment by shiliuus** [comment]
Hi React native team, 

I'm in the same situation with hcq0618. Can someone take a look?

**Comment by charliecruzan-stripe** [comment]
This should be supported on Android already, since `stripe-android` does it. It isn't supported on iOS though.

**Comment by remonh87** [comment]
@charliecruzan-stripe  can you confirm this works for you on react native because it doesn't seem to work for us on flutter.  I need to know this info to either send in a ticket to the flutter team or Stripe android

**Comment by charliecruzan-stripe** [comment]
Confirmed this works for me on React Native. Make sure you've got auto-fill for payment methods enabled in your device's settings
