### ISSUE TITLE
StripeSdk.presentPaymentSheet got 3 arguments, expected 2

### ISSUE THREAD

**Issue by Desttro** [stripe/stripe-react-native#1351]
**Describe the bug**
I am trying to build a Mobile Payment Element with [this guide](https://stripe.com/docs/payments/accept-a-payment?platform=react-native). I am following all steps. I also tried to check [this code](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICompleteScreen.tsx) to be sure that clientSecret and all other needed variables were passed from server to client. Everything is ok. But when I click on a button called openPaymentSheet (this calls presentPaymentSheet), my iOS simulator Expo app crashes without any logs. I have tried on a physical iPhone - the same issue.

So I have tried on Android Emulator, and I am getting the error `StripeSdk.presentPaymentSheet got 3 arguments, expected 2`.
I have also tried adding `({ timeout: 5000 })` params to function and adding more parameters to `initPaymentSheet` but without success.

**Expected behavior**
PaymentSheet should appear.

**Screenshots**
![error-android](https://user-images.githubusercontent.com/170174/230789735-b252648f-19f4-449b-a892-aa23a9d24055.png)

**Smartphone**
 - Device: iOS Simulator
 - OS: 16.4
- Expo 2.28.7.1017523 (SDK 48)

**Smartphone**
 - Device: Android Virtual Device
 - OS: Android 13
 - Expo 2.28.6 (SDK 48)

**Smartphone**
 - Device: iPhone 13
 - OS: iOS 16.4
 - Expo 2.28.7.1017523 (SDK 48)

**Additional context**
```
pn ls --filter expo-app
Legend: production dependency, optional only, dev only

expo-app@1.0.0 /Users/myuser/Developer/myproject/apps/expo (PRIVATE)

dependencies:
@babel/runtime 7.18.9                             expo-dev-client 2.1.6
@clerk/clerk-expo 0.14.2                          expo-font 11.1.1
@my/api link:../../packages/api                   expo-image 1.0.0
@my/ui link:../../packages/ui                     expo-linear-gradient 12.1.2
@react-native-async-storage/async-storage 1.18.1  expo-linking 4.0.1
@react-navigation/bottom-tabs 6.5.7               expo-router 1.0.1
@react-navigation/native 6.0.11                   expo-secure-store 12.1.1
@react-navigation/native-stack 6.7.0              expo-splash-screen 0.18.1
@stripe/stripe-react-native 0.26.0                expo-status-bar 1.4.4
@tanstack/react-query 4.28.0                      expo-updates 0.16.3
@trpc/client 10.18.0                              react 18.2.0
@trpc/react-query 10.18.0                         react-dom 18.2.0
@trpc/server 10.18.0                              react-native 0.71.4
app link:../../packages/app                       react-native-gesture-handler 2.9.0
babel-plugin-module-resolver 4.1.0                react-native-safe-area-context 4.5.0
burnt 0.10.0                                      react-native-screens 3.20.0
expo 48.0.9                                       react-native-svg 13.4.0
expo-auth-session 4.0.3                           react-native-web 0.18.12
expo-constants 14.2.1                             superjson 1.9.1

devDependencies:
@babel/core 7.20.2
@expo/metro-config 0.3.21
@tamagui/babel-plugin 1.9.17
@types/react-native 0.71.3
babel-plugin-transform-inline-environment-variables 0.4.4
metro-minify-terser 0.74.1
typescript 4.9.4
```

**Comment by charliecruzan-stripe** [comment]
Hi! This is because you're not using the proper version according to the version of Expo you're on. Make sure you install your dependencies with `expo install <package>`, and that should install [stripe react native v0.23.3](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0233---2023-02-07--expo-sdk-48)

**Comment by Tushar24042002** [comment]
i;m using latest version but saw same issues, can you help me

**Comment by cttsai-stripe** [comment]
Hi all, in order for us to better assist you with this integration issue, I'd love to point you to our support channel on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you 24/5. Thank you!
