### ISSUE TITLE
iOS: Requiring email in createPlatformPayPaymentMethod doesn't work

### ISSUE THREAD

**Issue by jgillick** [stripe/stripe-react-native#1353]
**Describe the bug**
On iOS, when calling `createPlatformPayPaymentMethod` with email as a required billing contact field, the user I still allowed to select a payment method without email.

```
const { paymentMethod, error: platformPayError } = await createPlatformPayPaymentMethod({
  applePay: {
    cartItems: items,
    merchantCountryCode: 'US',
    currencyCode: 'usd',
    requiredBillingContactFields: [
      PlatformPay.ContactField.PostalAddress,
      PlatformPay.ContactField.EmailAddress,
    ],
  },
  googlePay: {
    testEnv: false,
    merchantCountryCode: 'US',
    currencyCode: 'usd',
    amount: totalCost,
    isEmailRequired: true,
    billingAddressConfig: {
      isRequired: true,
      format: PlatformPay.BillingAddressFormat.Min,
      isPhoneNumberRequired: false,
    },
  },
});
```

**To Reproduce**
1. Use `createPlatformPayPaymentMethod` to open Apple Pay and ensure that `PlatformPay.ContactField.EmailAddress` is defined in the `requiredBillingContactFields` parameter
2. Select a payment option that does not have an email address defined.
3. Tap the CTA (i.e. Pay with passcode)
4. Notice that `paymentMethod.billingDetails.email` is `null`.

**Expected behavior**
The email property should be defined.

**Desktop (please complete the following information):**
 - OS: iOS simulator

**Smartphone (please complete the following information):**
 - Device: iOS simulator, iPhone 12
 - OS: iOS 14.5
 - Version: @stripe/stripe-react-native 0.26.0

**Comment by charliecruzan-stripe** [comment]
Hi! I verified this behavior, but also verified we are correctly setting the `PKPaymentRequest`'s `requiredBillingContactFields` to include the email address. It looks like this might actually be a bug with ios: https://developer.apple.com/forums/thread/61802, so there's not a way for us to solve it in this library, but you could collect the email address as part of the shipping as a workaround?

**Comment by jgillick** [comment]
Thank you for your reply; your suggested workaround works very well.

```tsx
const { paymentMethod, error: platformPayError } = await createPlatformPayPaymentMethod({
  applePay: {
    cartItems: items,
    merchantCountryCode: 'US',
    currencyCode: 'usd',
    requiredBillingContactFields: [ PlatformPay.ContactField.PostalAddress ],
    requiredShippingAddressFields: [PlatformPay.ContactField.EmailAddress], // <-- Required change
  },
  googlePay: {
    testEnv: false,
    merchantCountryCode: 'US',
    currencyCode: 'usd',
    amount: totalCost,
    isEmailRequired: true,
    billingAddressConfig: {
      isRequired: true,
      format: PlatformPay.BillingAddressFormat.Min,
      isPhoneNumberRequired: false,
    },
  },
});

const { email } = paymentMethod.billingDetails;
```
