### ISSUE TITLE
Is there a way to add some marginBottom to the labels in a form created using initPaymentSheet?

### ISSUE THREAD

**Issue by MPuzio15** [stripe/stripe-react-native#1354]
While using initPaymentSheet there is no way to add some margin under the labels. Could you please add some styling props that we could use to change it?

**Describe the solution you'd like**
I would like to be able to add some styling to the inputs' labels  (marginBottom) so that it wasn't 'glued' to the input. 

**Describe alternatives you've considered**
Margin for the inputs would be also ok.

**Additional context**
![image](https://user-images.githubusercontent.com/51422006/231379217-95cf30a8-424a-4b2f-a4b9-590a81d9dd06.png)

**Comment by charliecruzan-stripe** [comment]
Hi! You can't directly add margin to the inputs or labels, but you might be able to accomplish the layout you're looking for by changing the [font](https://stripe.com/docs/elements/appearance-api?platform=react-native)
