### ISSUE TITLE
initPaymentSheet can I move modal close icon to the right?

### ISSUE THREAD

**Issue by MPuzio15** [stripe/stripe-react-native#1355]
**Is your feature request related to a problem? Please describe.**
Hi, I created the payment sheet using initPaymentSheet and i was wondering if there is a way to move the modal close icon to the right? I could not find a way to do that and there is a requirement from the client side to have it on the right like in the rest of their modals. 

**Describe the solution you'd like**
I would like to be able to move the modal close icon to the right side. 

![image](https://user-images.githubusercontent.com/51422006/231388842-2018519a-f808-420c-aac7-2b266aab7eb1.png)

**Comment by charliecruzan-stripe** [comment]
Hi! Unfortunately you can't configure the positioning of that icon.
