### ISSUE TITLE
createPlatformPaymentMethod iOS error 

### ISSUE THREAD

**Issue by acatalina** [stripe/stripe-react-native#1363]
**Describe the bug**
Calling `createPlatformPaymentMethod` produces the following error on iOS:
```
Attempt to present <PKPaymentAuthorizationViewController: 0x7fdfec8d4d60> on <RCTModalHostViewController: 0x7fdfce953b10> (from <RCTModalHostViewController: 0x7fdfce953b10>) whose view is not in the window hierarchy
```

Checked the deprecated `presentApplePay` and it works with no problems.

**To Reproduce**
``` javascript
createPlatformPayPaymentMethod({
  applePay: {
    cartItems: [
      {
        amount: "20",
        paymentType: 'Immediate',
        label: 'Total',
        isPending: false,
      },
    ],
    merchantCountryCode: 'GB',
    currencyCode: 'GBP',
  },
})
```
**Expected behavior**
Apple pay sheet to open

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: 16.4

**Additional context**
- RN 0.71.7
- RN-Stripe 0.26.0
- Pod Stripe 23.5.1

Upgrading from stripe 0.4.0 to latest. Our flow doesn't allow us to use paymentSheet so we were using presentApplePay that has been marked as depecrated.

**Comment by charliecruzan-stripe** [comment]
> RCTModalHostViewController

Looks like you're calling this while a Modal component is presented. I tried this and it's still working for me, so could you provide a reproducible demo?

**Comment by acatalina** [comment]
Hi @charliecruzan-stripe, thanks for looking into it. I'll try to get a reproducible demo.

Out of curiosity, is the behaviour anyway expected?

**Comment by acatalina** [comment]
well, I feel like an idiot. I cannot reproduce it anymore. No idea what it was then, maybe some dodgy depedencies or a bad install... closing

**Comment by michalis-ligopsychakis** [comment]
I have similar issue
```
Attempt to present <PKPaymentAuthorizationViewController: 0x11d225bd0> on <UIViewController: 0x160e324e0> (from <UIViewController: 0x160e324e0>) whose view is not in the window hierarchy.
```

any help?

**Comment by TheoNikos** [comment]
> I have similar issue
> 
> ```
> Attempt to present <PKPaymentAuthorizationViewController: 0x11d225bd0> on <UIViewController: 0x160e324e0> (from <UIViewController: 0x160e324e0>) whose view is not in the window hierarchy.
> ```
> 
> any help?

same issue here!
