### ISSUE TITLE
The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant)

### ISSUE THREAD

**Issue by jonqwerty** [stripe/stripe-react-native#1370]
Adding the CardForm in expo app  gives   :

Binary XML line #9: Error inflating class com.google.android.material.card.MaterialCardView
The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant)

![Screenshot_5](https://user-images.githubusercontent.com/50663567/234783171-fe74d5c9-2c02-4ad5-b98e-efb3f773c46d.jpg)

**Smartphone (please complete the following information):**
 - Device: Android emulator ( Pixel 4XL API 28 )
 - OS: Windows 10
 
    "@stripe/stripe-react-native": "0.23.3",
    "expo": "^48.0.0",
    "react": "18.2.0",
    "react-native": "0.71.6",
  
When I use CardField everything is fine.

**Comment by charliecruzan-stripe** [comment]
hi! this is in our requirements for cardform: https://github.com/stripe/stripe-react-native#requirements

**Comment by bataevvlad** [comment]
@charliecruzan-stripe looks like you mention requirements for CLI project, how can we fix it on expo?

**Comment by noureen-fatima** [comment]
@jonqwerty I am facing the same issue, can you share the solution with me as well? CardField is working fine but it is not what I want for my design.
"@stripe/stripe-react-native": "0.28.0"
"react-native-svg": "13.9.0"
"react-native": "0.72.6"
"react": "18.2.0"
"expo": "~49.0.15"

**Comment by KatsutaHibiki** [comment]
Hello,
I'm experiencing the issue described in this thread in my project that uses Expo.
Additionally, the CardField component cannot be used either, as it causes the app to crash, as mentioned in [this issue.](https://github.com/stripe/stripe-react-native/issues/1732#issue-2530364007)
If there is a solution for this issue in the Expo environment, I would appreciate your guidance.

**Comment by KatsutaHibiki** [comment]
Hello,
I'm experiencing the issue described in this thread in my project that uses Expo.
Additionally, the CardField component cannot be used either, as it causes the app to crash, as mentioned in [this issue.](https://github.com/stripe/stripe-react-native/issues/1732#issue-2530364007)
If there is a solution for this issue in the Expo environment, I would appreciate your guidance.

"@stripe/stripe-react-native": "0.38.6"
"expo": "52"
"react-native": "0.76.3"

**Comment by samer-stripe** [comment]
Hey @KatsutaHibiki! The crash linked was recently fixed in the latest version of the SDK (0.43.0). For expo, you can follow [this example](https://github.com/expo/expo/issues/19563#issuecomment-1576437572) for how to set your `AppTheme` with Expo.

**Comment by KatsutaHibiki** [comment]
@samer-stripe 

Thank you very much!
It seems that the latest SDK is not compatible with Expo52, so the Android build was failing.
That's why I was using an older version.
After trying the settings you suggested, the issue was resolved.
I'm really glad I asked!

**Comment by KatsutaHibiki** [comment]
@samer-stripe

Thank you very much!
It seems that the latest SDK(0.43.0) is not compatible with Expo52, so the Android build was failing.
So, I use the version recommended by expo-doctor.
I tried the settings you suggested with the older SDK(0.38.6), and it worked!
I'm really glad I asked!
