### ISSUE TITLE
Unable to dismiss the webview after 3D Secure authentication - iOS

### ISSUE THREAD

**Issue by marlon-brillantes** [stripe/stripe-react-native#1381]
**Describe the bug**
I'm using test card `4000 0025 0000 3155` as the payment method, after authentication the 3D Secure authentication in the webview, my screen stuck at the webview with the "Return to merchant" button and the button is not working, i have to press the close button of the webview to dismiss the webview in order to direct myself back to the apps. 

I confirmed deep linking works with the schema i am sending for confirmPayment. I tested the deep-link with 
1 - pasting the uri safari
2 - command line - xcrun simctl openurl booted <uri>

I found similar issues and saw that there were fixes. I'm wondering if the fix needs to be implemented for react-native

https://github.com/ezet/stripe-sdk/issues/79
https://github.com/stripe/stripe-ios/issues/1582

**Expected behavior**
Deep link into the app works after confirmation is successful/failed

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro simulator
 - "@stripe/stripe-react-native": "^0.25.0",

**Comment by charliecruzan-stripe** [comment]
hi! are you passing `urlScheme` to your `StripeProvider`?

**Comment by marlon-brillantes** [comment]
hi @charliecruzan-stripe, yes 
```
initStripe({
      publishableKey: this.stripePublicKey,
      stripeAccountId: this.stripeAccountID,
      urlScheme: '<myCompany>stripe',
    });
```
and it is coming back in the deep-link output correctly

**Comment by charliecruzan-stripe** [comment]
Ah i think this is the same as https://github.com/stripe/stripe-react-native/issues/1372, you need to setup return URL handling, see these docs: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-set-up-return-url

We'll need to add those to React Native 3d-secure docs

**Comment by charliecruzan-stripe** [comment]
That's payment sheet specific, what im referring to is the `handleURLCallback` code. sorry for the confusion!

**Comment by marlon-brillantes** [comment]
ah perfect ty!
