### ISSUE TITLE
3d secure confirmation page claim text

### ISSUE THREAD

**Issue by wiulma** [stripe/stripe-react-native#1383]
Hi!
This is my scenario.
I'm going to register a new payment methos for feature payments.
I recently introduced the 3d secure flow without webhook.
It means I use the `createPaymentMethod` to manage the 3ds flow.

I'd need to customize the text (or at least the app name) that is shown when you're redirect to a web view in order to confirm the card with a passcode.
The reason is that I also develop whitelabel, and I'd like to force to show the partner name in that webview, and not the main company one.

![Screenshot](https://github.com/stripe/stripe-react-native/assets/39631533/3566d64a-a125-4222-96ec-3070cd0367ad)

it basically means to customize the text hidden by the red stroke 

Is it possible in some way?

Thanks a lot

**Comment by charliecruzan-stripe** [comment]
hi @wiulma! the value that's displayed is using the statement descriptor that you set in your [profile](https://dashboard.stripe.com/settings/public), and it's also the value that we will use when sending authorization, which later shows in the cardholder's bank statement. for reflecting the statement descriptor based on the actual merchant that the cardholder is paying for, you should consider:
- setting up a dedicated stripe account for your partner
- setting up a Connect account for your partner and use [Connect Direct Charge](https://stripe.com/docs/connect/direct-charges) or [On behalf of](https://stripe.com/docs/connect/charges-transfers#on-behalf-of)
