### ISSUE TITLE
Android build fail after installing stripe-react-native

### ISSUE THREAD

**Issue by Zeeshan404** [stripe/stripe-react-native#1385]
**Describe the bug**
Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult

**To Reproduce**
1. npm install @stripe/stripe-react-native
2. Change compileSdkVersion to 33
3. Clean build android folder

**Expected behavior**
Build without errors

**Screenshots**
![image](https://github.com/stripe/stripe-react-native/assets/54739303/9f42b5a6-6f53-4ca8-bea9-4b82c9b6bbb2)

**Additional context**
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.18 - /opt/homebrew/opt/node@14/bin/npm
    Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/aneesanwar/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-26 | Google APIs ARM 64 v8a, android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-S | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
    Python: 3.10.11 - /opt/homebrew/opt/python@3.10/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.5 => 0.63.5 
    @stripe/stripe-react-native: "^0.27.1",

**Comment by charliecruzan-stripe** [comment]
Can you share the full build error details? The screen shot doesn't point to stripe

**Comment by Zeeshan404** [comment]
It's working in the newly initiated project. Does @stripe/stripe-react-native: "^0.27.1" supports  react native 0.63 ?
