### ISSUE TITLE
CardForm dividers invisible in when device is in dark mode

### ISSUE THREAD

**Issue by jgillick** [stripe/stripe-react-native#1390]
**Describe the bug**
It doesn't seem possible to force light mode in Android or set the divider & icon colors on the CardForm. My app only has a light mode, and I'm trying to use `cardStyle` to set the styles to be consistent, but borderColor does not affect the divider colors and leaves the form looking really bad:

<img width="466" alt="Screenshot 2023-05-12 at 12 07 06 PM" src="https://github.com/stripe/stripe-react-native/assets/35894/b539d466-e973-4faf-b3ef-db7df653f764">

**To Reproduce**
1. On `<CardForm>` set `cardStyle={{borderColor: '#ff0000'}}`
2. Observe that this only changes the outside border color, but not the dividers.

**Expected behavior**
Either we should be able to force the form to be in light (or dark) mode, or an option to set the divider colors.

**Code**

`android/app/src/main/res/values/styles.xml`
```xml
<resources>
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <item name="android:forceDarkAllowed">false</item>

        <item name="android:windowBackground">@color/purple</item>
        <item name="android:navigationBarColor">#FFFFFF</item>
        <item name="android:textColor">#222B45</item>
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>

        <item name="colorPrimary">#222B45</item>
        <item name="colorPrimaryDark">#222B45</item>
        <item name="colorAccent">#222B45</item>
        <item name="colorSurface">#ffffff</item>
        <item name="colorOnSurface">#222B45</item>
    </style>
</resources>
```

`Component`
```jsx
<CardForm
  style={{ height: 300 }}
  cardStyle={{
    placeholderColor: '#222B45',
    cursorColor: '#222B45',
    textColor: '#222B45',
    backgroundColor: '#ffffff',
    borderColor: '#C5CEE0',
    borderWidth: 1,
    borderRadius: 8,
  }}
/>
```

**Smartphone:**
 - Device: Android Pixel 4a
 - OS: Android 12

**Comment by jgillick** [comment]
I've found a partial workaround to the dividers by adding the following styles to my `styles.xml`. However, I still cannot figure out how to get the light-version of the icons and the divider between country and postal code.

```xml
<style name="StripeHorizontalDivider">
    <item name="android:background">#C5CEE0</item>
    <item name="android:layout_width">match_parent</item>
    <item name="android:layout_height">1dp</item>
</style>
<style name="StripeVerticalDivider">
    <item name="android:layout_width">1dp</item>
    <item name="android:layout_height">match_parent</item>
    <item name="android:background">#C5CEE0</item>
</style>
<style name="StripePaymentSheetFormDivider">
    <item name="android:background">#C5CEE0</item>
    <item name="android:layout_width">match_parent</item>
    <item name="android:layout_height">1dp</item>
</style>
```

**Comment by charliecruzan-stripe** [comment]
> It doesn't seem possible to force light mode in Android

You can do this, see [here](https://github.com/stripe/stripe-react-native/issues/692#issuecomment-1072668453) (although it is app-wide, not just for the cardform component).

Otherwise, I think the best course of action is to modify the `cardStyle.backgroundColor` so that the icons/dividers are visible, since programmatically setting those icons & some of the dividers isn't possible
