### ISSUE TITLE
PaymentSheet should not allow users to delete all payment methods

### ISSUE THREAD

**Issue by lewismartin512** [stripe/stripe-react-native#1391]
**Is your feature request related to a problem? Please describe.**

I work often with reservation systems where we need to hold at least one payment method on system until the reservation is complete (e.g. for late cancellation/no-show fees). The PaymentSheet 'Edit' button allows for the deletion of all customer payment methods. This results in the opportunity for customers to book (where a card is required to be on file), and then subsequently use the PaymentSheet UI again to delete the payment method.

**Describe the solution you'd like**

Support for a boolean flag akin to "atLeastOnePaymentMethod" in the SetupParams to indicate whether the user should have the option to remove all payment methods.

**Describe alternatives you've considered**

Other alternative solution is to allow for the 'Edit' button to be enabled/disabled.

**Comment by charliecruzan-stripe** [comment]
thanks for the issue! we're working on a fix for this 👍

**Comment by charliecruzan-stripe** [comment]
hi! 

this wont be fixed directly in the way you are asking, but there are two other options:
- we'll be shipping support for `removeSavedPaymentMethodMessage` soon, which you can set on payment sheet to show a custom message when your customer removes a PM (so they could be warned there)
- we just shipped private beta support for the customer sheet where you can directly control this behavior: https://stripe.com/docs/elements/customer-sheet?platform=react-native

**Comment by charliecruzan-stripe** [comment]
closed in https://github.com/stripe/stripe-react-native/pull/1498

**Comment by byudaniel** [comment]
@charliecruzan-stripe Will this be revisited with the addition of the `allowsRemovalOfLastSavedPaymentMethod` option [added to the Android](https://github.com/stripe/stripe-android/pull/7900) and [iOS](https://github.com/stripe/stripe-ios/pull/3264) libraries?
