### ISSUE TITLE
How to use Link in paymentSheet?

### ISSUE THREAD

**Issue by sn4f** [stripe/stripe-react-native#1393]
**Describe the bug**
Hi, how I can enable [Link](https://stripe.com/docs/payments/link) in paymentSheet? I have enabled all settings related to this in my test account and I still don't see this mode in the app. I'm using Connect + Link

**Expected behavior**
Be able to use Link in react-native app

**Comment by charliecruzan-stripe** [comment]
hi! You need to add `link` as a `payment_method_type` to your payment intent. We go through it in this video: https://www.youtube.com/watch?v=d4xCTtkUfPA

**Comment by sn4f** [comment]
@charliecruzan-stripe Here is a response from our backend team
We're using Stripe Connect. For each buyer who conducts their initial transaction with a specific seller, a customer account is established and assigned to the corresponding Connect account. I have taken the necessary steps to enable Link integration across all Connect accounts; however, it does not seem to be appearing during the checkout process. We generate PaymentIntent with enabled  automatic_payment_methods - then we pass generated client_secret to the frontend.

**Comment by charliecruzan-stripe** [comment]
Could you share an example payment intent with me? feel free to email it to charliecruzan@stripe.com if you'd prefer

**Comment by sn4f** [comment]
Hello @charliecruzan-stripe , any news? We are not getting any responses from you.

**Comment by charliecruzan-stripe** [comment]
I took a look at the payment intent and it definitely has `link` enabled as a payment method. What version of the React Native SDK are you using?

**Comment by sn4f** [comment]
@charliecruzan-stripe hmm weird, we are using [0.27.2](https://github.com/stripe/stripe-react-native/releases/tag/v0.27.2) with latest available sdk for it

**Comment by charliecruzan-stripe** [comment]
Are you using Expo?

**Comment by sn4f** [comment]
@charliecruzan-stripe No, I don't use Expo.

**Comment by charliecruzan-stripe** [comment]
Could you share your `initPaymentSheet()` code?

**Comment by sn4f** [comment]
Sure

```
    const { error } = await initPaymentSheet({
      paymentIntentClientSecret: clientSecret,
      merchantDisplayName: FROM_ENV,
      returnURL: FROM_ENV,
      applePay: {
        cartItems: [
          {
            label: `@${sellerHandle}, via ${FROM_ENV}`,
            amount: priceToPay,
            paymentType: PlatformPay.PaymentType.Immediate,
          },
        ],
        merchantCountryCode: 'GB',
      },
    });

    if (error) {
      return onPaymentError(error);
    }

    const { error: paySheetError } = await presentPaymentSheet();

    if (paySheetError) {
      return onPaymentError(paySheetError);
    }

    onPaymentSuccess(transactionId, priceToPay);
  };
```

**Comment by charliecruzan-stripe** [comment]
Hey @sn4f, sorry about the miscommunication here. We've actually disabled Link in the Mobile Payment Element across iOS, Android, and React Native SDKs for the time being.

We've received feedback on gaps in the experience and we believe to better serve your needs, the experience will require an overhaul. So we are going to rethink the experience including updates to the sign up experience, returning user experience, and saved payment methods experience. We will also be looking to introduce a way to support cross app authentication, which is not possible with today's integration.

We want to make sure we get the experience right, so this will require some iteration and testing. We are happy to contact you once we have more details regarding timelines

**Comment by sn4f** [comment]
Hi @charliecruzan-stripe, any update on this?

**Comment by charliecruzan-stripe** [comment]
Not yet

**Comment by CriusNyx** [comment]
I just wanted to add a note that link does appear to be enabled in the newest version of stripe-react-native.

**Comment by sn4f** [comment]
> I just wanted to add a note that link does appear to be enabled in version 0.33.0 of stripe-react-native.

@charliecruzan-stripe is it true?

**Comment by benomatis** [comment]
@CriusNyx Do you mean the checkbox next to "Save this card for future `<company name>` payments" in the below screenshot just above the blue Pay button? If so, you may be confusing Link with the `setup_future_usage` feature, because that checkmark is not Link. If not, though, please do share with us the code you're using that allows you to use Link on mobile.

By the way, Link not being supported is also confirmed on the [Payment method integration options page for Link](https://stripe.com/docs/payments/payment-methods/integration-options#support-link).

<img width="208" alt="image" src="https://github.com/stripe/stripe-react-native/assets/5822748/c85f9cef-da32-4116-95bf-caa0352a16e7">

**Comment by CriusNyx** [comment]
No, I do mean stripe link. It appears to be working in my companies application. I will reach out to our companies Stripe Rep and see if I can sort out what the official status is for stripe link on the mobile payment element.

**Comment by CriusNyx** [comment]
After reaching out internally it appears that Stripe Link is not enabled on the mobile payment element for all customers, but that it was turned on for our company by our stripe rep.

Sorry to add confusion to this issue. I was not in the loop on these conversations. Good luck to everyone else.

**Comment by lamhong-playon** [comment]
Hello @charliecruzan-stripe,

I've attempted to run the code from this repository (https://github.com/charliecruzan-stripe/react-native-video-series.git) and encountered the same issue where the link does not display with custom payment methods specified as types=[link, card].

Could you please provide an update on the expected timeline for resolving this issue?

Thank you,
Screen Recording 2024-01-09 at 3.19.13 PM
