### ISSUE TITLE
Type error in the object returned from confirmPlatformPaySetupIntent

### ISSUE THREAD

**Issue by Filippo39** [stripe/stripe-react-native#1396]
**Describe the bug**
I don't know if it was a bug or a vulnerability problem.
In **android** the `confirmPlatformPaySetupIntent` function returns a `setupIntent: SetupIntent` object and the interface is as follows:
```
export interface Result {
     id: string;
     clientSecret: string;
     lastSetupError: LastPaymentError | null;
     /** The UNIX timestamp (in milliseconds) of the date this Setup Intent was created. */
     created: string | null;
     livemode: boolean;
     paymentMethodId: string | null;
     status: Status;
     paymentMethodTypes: Type[];
     usage: FutureUsage;
     description: string | null;
     nextAction: NextAction | null;
}
```

When I print this object I get an additional `paymentMethod` field that is not defined in the interface.

In IOS the `paymentMethod` field is null.

**Expected behavior**
The `paymentMethod` field of the `setupIntent` object returned from the `confirmPlatformPaySetupIntent` must be typed correctly

**Smartphone (please complete the following information):**
 - Device: Redmi 10
 - OS: Android 11
 - Stripe: 0.27.2

**Comment by charliecruzan-stripe** [comment]
The [interface](https://github.com/stripe/stripe-react-native/blob/master/src/types/SetupIntent.ts#L9-L24) for SetupIntent.Result is :

```
export interface Result {
  id: string;
  clientSecret: string;
  lastSetupError: LastPaymentError | null;
  /** The UNIX timestamp (in milliseconds) of the date this Setup Intent was created. */
  created: string | null;
  livemode: boolean;
  /** @deprecated Use paymentMethod.id instead. */
  paymentMethodId: string | null;
  paymentMethod: PaymentMethod.Result | null;
  status: Status;
  paymentMethodTypes: Type[];
  usage: FutureUsage;
  description: string | null;
  nextAction: NextAction | null;
}
```

`paymentMethodId` is deprecated in favor of `paymentMethod`, so it's expected that `paymentMethod` be there.

**Comment by galaxxyz** [comment]
Hello @charliecruzan-stripe , my app has some logic that depends on `paymentMethodId` returned from `confirmPlatformPaySetupIntent()`. I would like to use setupIntent.paymentMethod.id instead of deprecated setupIntent.paymentMethodId, but the `setupIntent` has `paymentMethod: null` field , at the same time `paymentMethodId` is presented there and is not null. Does it intended to be like that?

```
{
"clientSecret": "seti_#############",
"created": "#############",
"description": null,
"id": "seti_#############",
"lastSetupError": null,
"livemode": false,
"nextAction": null,
"paymentMethod": null,
"paymentMethodId": "pm_##########",
"paymentMethodTypes": ["Card"],
"status": "Succeeded",
"usage": "OffSession"
}
```

**I test on simulator:**
Device: iPhone 13
OS: iOS 16.2
Stripe: 0.24.0

**Comment by charliecruzan-stripe** [comment]
hey @galaxxyz , that's an issue with the data we're getting from the iOS SDK. Could I ask you to update to the most recent version and check if the same is still occurring?

**Comment by galaxxyz** [comment]
@charliecruzan-stripe I've updated sdk to 0.27.2, `setupIntent.paymentMethod` is still null.
Yes, sure. It's not something critical, I'll keep using paymentMethodId for now.
