### ISSUE TITLE
[Discussion] Naming of methods

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe/stripe-react-native#14]
There is a broader question about naming. e.g. currently
- RN: `useConfirmPayment` & `confirmPayment` vs in Stripe.js we use `confirmCardPayment` (https://stripe.com/docs/js/payment_intents/confirm_card_payment)
- RN: `useConfirmSetupIntent` & `confirmSetupIntent` vs in Stripe.js we use `confirmCardSetup` (https://stripe.com/docs/js/setup_intents/confirm_card_setup)

@auchenberg-stripe I'd appreciate your input on this

**Comment by Seanmclem** [comment]
docs seem to just call it `confirmSetup` in some cases @auchenberg-stripe https://stripe.com/docs/payments/ach-debit/set-up-payment?platform=react-native#react-native-submit-payment

**Comment by Seanmclem** [comment]
docs seem to just call it `confirmSetup` in some cases @auchenberg-stripe https://stripe.com/docs/payments/ach-debit/set-up-payment?platform=react-native#react-native-submit-payment
