### ISSUE TITLE
Card field does not appear on the interface of some android devices

### ISSUE THREAD

**Issue by h-dung-95** [stripe/stripe-react-native#1404]
This error appears my Samsung Z Flip4 seems the Card field has disappeared even though I tried many times
![1685166099975](https://github.com/stripe/stripe-react-native/assets/113409857/39eff974-e8e5-4574-972a-82ce7d70a46b)
<img width="961" alt="Screenshot 2023-05-28 at 09 04 25" src="https://github.com/stripe/stripe-react-native/assets/113409857/80426664-48cc-4abf-8704-d44b98255f73">

**Comment by h-dung-95** [comment]
please help me clarify this, thanks!

**Comment by charliecruzan-stripe** [comment]
hi @h-dung-95 , you need to add a `width` to the `style`
