### ISSUE TITLE
CardForm error inflanting class (Binary XML File)

### ISSUE THREAD

**Issue by Santosl2** [stripe/stripe-react-native#1411]
**Describe the bug**
I'm using expo and i'm getting this error in stripe after run prebuild:

![Screenshot_1685800318](https://github.com/stripe/stripe-react-native/assets/67132916/73589fd8-1fca-4100-9382-4122c4810410)

P.S: in Expo local, without run prebuild, is working correctly (before run prebuild)

![image](https://github.com/stripe/stripe-react-native/assets/67132916/e799267b-f7c7-4b9a-8571-f132c241b8df)

**To Reproduce**
1. First, run prebuild or eas build
2. Run your project
1. Import 'CardForm' from stripe

**Expected behavior**
I need to see CardForm correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device: Pixel 
 - OS: Android 11
 - Browser 
 - Version 

**Additional context**

I added this on app/build.gradle:

![image](https://github.com/stripe/stripe-react-native/assets/67132916/bfa90938-b601-457b-9796-5fcdbb899320)

And this in my styles.xml
![image](https://github.com/stripe/stripe-react-native/assets/67132916/157564fa-af6d-40cb-be04-585d27164b63)

**Comment by Santosl2** [comment]
UPDATE:

I updated my AndroidManifest.xml, and changed android:theme from application:

![image](https://github.com/stripe/stripe-react-native/assets/67132916/c99eeddc-891a-4b94-9f1c-aac677d4fcf7)


And inserted in Styles.xml (src/main/res/values) the below code:

![image](https://github.com/stripe/stripe-react-native/assets/67132916/9165b3b9-d0cf-4191-9e1b-c95dac9dc840)

But doesnt work :(

**Comment by charliecruzan-stripe** [comment]
Plugin should work fine for this with Expo! Glad you found the solution, I'll close this out
