### ISSUE TITLE
Failed pod install with the latest react-native stripe version on Mac13.3

### ISSUE THREAD

**Issue by smiley717** [stripe/stripe-react-native#1412]
**Describe the bug**
The Stripe React Native SDK requires Xcode 14.1 or later and is compatible with apps targeting iOS 13 or above. For iOS 12 support, please use [@stripe/stripe-react-native@0.19.0](https://github.com/stripe/stripe-react-native/releases/tag/v0.19.0).

I am using Ventura 13.3.1 and tried to pod install. but failed with below issues. (@stripe/stripe-react-native@0.27.2)

`
[!] CocoaPods could not find compatible versions for pod "StripeFinancialConnections":
  In snapshot (Podfile.lock):
    StripeFinancialConnections (= 22.8.4, ~> 22.8.1)

  In Podfile:
    stripe-react-native (from `../node_modules/@stripe/stripe-react-native`) was resolved to 0.27.2, which depends on
      StripeFinancialConnections (~> 23.8.0)
`

**Screenshots**
![image](https://github.com/stripe/stripe-react-native/assets/80674675/b6dfb055-c882-4306-9961-b3ec5f3b7a6a)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: Ventura 13.3.1
 - Version 0.27.2

**Comment by smiley717** [comment]
downgrade to 27.0 works for me.

**Comment by stephanrueschenbaum** [comment]
I faced the same issue when updating to latest version 0.34.0. Solved it by just deleting `Podfile.lock` and the `Pods` folder. Then run `pod install` again and worked.
