### ISSUE TITLE
Ios build fail : CompileSwift normal x86_64

### ISSUE THREAD

**Issue by pradoAgustin** [stripe/stripe-react-native#1413]
**Describe the bug**
I am getting this bug every time I try to run the app , xcode version 13.2.1, 

**To Reproduce**
try to build the app 
 CompileSwift normal x86_64 /Users/user/repos/spider-mobile/ios/Pods/StripeFinancialConnections/StripeFinancialConnections/StripeFinancialConnections/Source/Native/Shared/MerchantDataAccessView.swift (in target 'StripeFinancialConnections' from project 'Pods')
and all the errors have the same problem   CompileSwift normal x86_64 / (at least 29 errors like this)

what I have tried:
-reinstall pods
update min_ios_version to 13.0

nothing worked.

I don't know what else I could try. 

Thanks in advance!

**Comment by charliecruzan-stripe** [comment]
Hi! Xcode 13 is [no longer supported by Apple](https://developer.apple.com/news/upcoming-requirements/):

> iOS and iPadOS apps submitted to the App Store must be built with Xcode 14.1

We mention in the changelog that Xcode 14.1 is required as of v0.27.1 of this library.
