### ISSUE TITLE
How can we develop ACH with stripe ?

### ISSUE THREAD

**Issue by Shivani12345** [stripe/stripe-react-native#1416]
Can anyone suggest proper ACH flow setup steps with stipe ?
I have implemented steps from below document but its not working proper. 
[https://stripe.com/docs/terminal/payments/collect-payment?terminal-sdk-platform=react-native#collect_payment](https://stripe.com/docs/terminal/payments/collect-payment?terminal-sdk-platform=react-native#collect_payment)

**Comment by charliecruzan-stripe** [comment]
Can you provide more details about what's not working? We have an example screen here: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ACHPaymentScreen.tsx

**Comment by Shivani12345** [comment]
I need to implement instant verification for payment with ACH without passing any account and routing number.
I show that we can get any URL from stripe for the same but I don't know how we can get this.

**Comment by charliecruzan-stripe** [comment]
Ah i think you're looking for https://stripe.com/docs/financial-connections/other-data-powered-products
