### ISSUE TITLE
is there a way to show the apple pay popup even if the user haven't setup a card?

### ISSUE THREAD

**Issue by olarid** [stripe/stripe-react-native#1420]
it seems isPlatformPaySupported returns false if the user haven't added any card to apple pay, and the confirmPlatformPayPayment api returns "Payment Not Complete". Is there a way to still show the apple pay modal even if card is not setup?

**Comment by ben-wright** [comment]
I am also facing a similar issue. However I have tested this on a device where I know apple pay is setup but still getting following error message:

`{"stripeErrorCode":null,"declineCode":null,"localizedMessage":"Payment not completed","message":"Payment not completed","type":null,"code":"Failed"}`

Also, `isPlatformPaySupported` is returning false even though the device I am testing on already has Apple pay setup

**Comment by charliecruzan-stripe** [comment]
Hi! You can use `openPlatformPaySetup` in this case
