### ISSUE TITLE
StripeSdk.presentPaymentSheet got 3 arguments, expected 2 using react native cli

### ISSUE THREAD

**Issue by Jawad-H** [stripe/stripe-react-native#1427]
{

  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.12",
    "@react-native-community/checkbox": "^0.5.14",
    "@react-native-community/datetimepicker": "^7.0.1",
    "@react-native-firebase/analytics": "^17.4.1",
    "@react-native-firebase/app": "^17.4.1",
    "@react-native-firebase/crashlytics": "^17.4.1",
    "@react-native-firebase/firestore": "^17.5.0",
    "@react-native-firebase/messaging": "^17.5.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-native-picker/picker": "^2.4.10",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "@stripe/stripe-react-native": "^0.2.3",
    "accordion-collapse-react-native": "^1.1.1",
    "apisauce": "^3.0.0",
    "aws-sdk": "^2.1358.0",
    "axios": "^1.3.4",
    "base64-arraybuffer": "^1.0.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "radio-buttons-react-native": "^1.0.4",
    "react": "17.0.2",
    "react-native": "0.68.6",
    "react-native-animatable": "^1.3.3",
    "react-native-blob-util": "^0.17.3",
    "react-native-check-box": "^2.1.7",
    "react-native-cli": "^2.0.1",
    "react-native-collapsible": "^1.6.0",
    "react-native-document-picker": "^8.1.4",
    "react-native-dotenv": "^3.4.8",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-image-picker": "^5.1.0",
    "react-native-marquee": "^0.5.0",
    "react-native-mime-types": "^2.4.0",
    "react-native-modal": "^13.0.1",
    "react-native-paper": "^5.3.1",
    "react-native-picker-select": "^8.0.4",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^3.0.2",
    "react-native-render-html": "^6.3.4",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-root-siblings": "^4.1.1",
    "react-native-root-toast": "^3.4.1",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-select-dropdown": "^3.3.0",
    "react-native-svg": "^13.8.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-toast-message": "^2.1.6",
    "react-native-toast-notifications": "^3.3.1",
    "react-redux": "^8.0.5",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.2.3",
    "reduxsauce": "^1.2.1",
    "socket.io-client": "^4.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by Tushar24042002** [comment]
i saw the same issue even using latest version of stripe in my expo react native

**Comment by cttsai-stripe** [comment]
Hi @Tushar24042002, in order for us to better assist you with this integration issue, I'd love to point you to our support channel on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you 24/5. Thank you!
