### ISSUE TITLE
confirmPlatformPayPayment - Apple Pay not displaying on real device

### ISSUE THREAD

**Issue by ben-wright** [stripe/stripe-react-native#1428]
**Describe the bug**
`confirmPlatformPayPayment` does not display Apple Pay pop up on production builds / builds not connected to debugger. Instead returns following error:
`confirmPlatformPayPayment failed {"stripeErrorCode":null,"declineCode":null,"localizedMessage":"Payment not completed","message":"Payment not completed","type":null,"code":"Failed"}`

**To Reproduce**
1.  "@stripe/stripe-react-native": "^0.28.0"
2.  Add apple pay entitlements
3. Create payment intent (fetch client secret)
4. Use following payload for displaying apple pay:

```
const { paymentIntent, error } = await confirmPlatformPayPayment(intent.data.clientSecret, {
        applePay: {
          cartItems: [
            {
              label: "Test",
              amount: totalPrice.toString(),
              paymentType: PlatformPay.PaymentType.Immediate as any,
            }
          ],
          merchantCountryCode: "GB",
          currencyCode,
          requiredShippingAddressFields: [PlatformPay.ContactField.EmailAddress]
        }
      });
```

**Expected behavior**
Apple pay pop up is displayed where user is given option to double tap to confirm payment.

**Screenshots**
Expected result (works on simulator)
<img src="https://github.com/stripe/stripe-react-native/assets/8125689/91b8d634-79a2-4a1a-a607-f6561f52d3cc" width="200"/>

**Device**
 - Simulator iOS 16.4 iphone 14 pro - Works fine
 - Device iOS 16.5 iphone 14 pro - Does not work

**Additional context**
Was wondeirng if there is some work going on in this area to either fix this or provide better error response?
https://github.com/stripe/stripe-react-native/tree/charliecruzan/paymentsheet/decoupledPaymentIntent

**Comment by seanzhang-stripe** [comment]
Can you call [isPlatformPaySupported()](https://stripe.dev/stripe-react-native/api-reference/index.html#isPlatformPaySupported) and see if your test device supports Apple Pay? If the result is false, run through [this process](https://stripe.com/docs/apple-pay?platform=react-native) again and also make sure you have added a valid card to your Apple Pay.

**Comment by ben-wright** [comment]
Hey @seanzhang-stripe thanks for your reply. I can confirm `isPlatformPaySupported` did return false.

Happy to say this issue is now resolved, this was caused by some automatic signing issues on CI pipeline, the app would build fine and majority of app functionality was working but areas around Apple pay would not work.

CI tool was codemagic and we swapped to use `build-ipa` instead of fastlane. Happy for you to close this issue

**Comment by summer-yyyn** [comment]
I have encountered the same issue, `isPlatformPaySupported` always returns `false`, which is good on the emulator. Please help me

**Comment by charliecruzan-stripe** [comment]
@summer-yyyn this method calls [this iOS function behind the scenes](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationcontroller/1649457-canmakepayments). What emulator are you using and what version?

Closing this since the original issue was resolved

**Comment by summer-yyyn** [comment]
@charliecruzan-stripe 
emulator: iphone 14 pro max ios16.4.0 
device: iphone 11 ios 16.2

**Comment by charliecruzan-stripe** [comment]
@summer-yyyn If there are no configured payment cards, this method always returns false.

**Comment by Akeuuh** [comment]
I have the exact same issue,
I verirfied and have the boolean returned by `isPlatformPaySupported` to `true`. But at the moment I click on the ApplePay button to call this function

```
const pay = async () => {
    if (!clientSecret) {
      return;
    }
    const { error } = await confirmPlatformPayPayment(clientSecret, platformConfig);
    if (error) {
      // handle error
      console.error('[STRIPE] Error displaying PlatformPay form: ', error);
    } else {
      handleSuccess();
    }
  };
```


I have this error
```
{ stripeErrorCode: null,
  declineCode: null,
  localizedMessage: 'Payment not completed',
  message: 'Payment not completed',
  type: null,
  code: 'Failed' }
```

**Comment by SnowingFox** [comment]
if i must use fastlane，how to resolve it? because i'm using expo-dev-client

**Comment by SnowingFox** [comment]
> @summer-yyyn If there are no configured payment cards, this method always returns false.

how to resolve this problem？

**Comment by SnowingFox** [comment]
> @summer-yyyn If there are no configured payment cards, this method always returns false.

In usual case, whether the user configured payment cards, it should the ios payment button to tell user that we can use apple pay

**Comment by Akeuuh** [comment]
> I have the exact same issue, I verirfied and have the boolean returned by `isPlatformPaySupported` to `true`. But at the moment I click on the ApplePay button to call this function
> 
> ```
> const pay = async () => {
>     if (!clientSecret) {
>       return;
>     }
>     const { error } = await confirmPlatformPayPayment(clientSecret, platformConfig);
>     if (error) {
>       // handle error
>       console.error('[STRIPE] Error displaying PlatformPay form: ', error);
>     } else {
>       handleSuccess();
>     }
>   };
> ```
> 
> I have this error
> 
> ```
> { stripeErrorCode: null,
>   declineCode: null,
>   localizedMessage: 'Payment not completed',
>   message: 'Payment not completed',
>   type: null,
>   code: 'Failed' }
> ```
> 
> Everything works on simulator but not on real device

In my case I was having an issue with the amount props, I was passing '85€' and not '85'. 
Don't know why it was working on simulator

**Comment by ashwini-sdlc** [comment]
React native stripe payment apple pay not working in real device working in simulator showing following error

{"code": "Failed", "declineCode": null, "localizedMessage": "Payment not completed", "message": "Payment not completed", "stripeErrorCode": null, "type": null}

1. "@stripe/stripe-react-native": "^0.33.0",
2. "react-native": "0.72.4",

const fetchPaymentIntentClientSecret = async () => {
    console.log("fetchPaymentIntentClientSecret");
    fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        amount: parseInt(price * 100),
      }),
    })
      .then((res) => res.json())
      .then((res) => {
        console.log('intent', res);
        console.log('Customer uid----', res.clientSecret);
        pay(res.clientSecret); // Call the pay function with the clientSecret
      })
      .catch((e) => {
        console.log('error while getting payment intent', e.message);
        setAlerttitle("Error");
        setMsg2(e?.message);
        setAlertVisible2(true);
        setAlertVisible(false);
      });
  };





  const pay = async (clientSecret) => {
   
    console.log("client secret-------",clientSecret)
    const { error,paymentIntent } = await confirmPlatformPayPayment(
      clientSecret,
      {
        applePay: {
          cartItems: [
           
            {
              label: 'Total',
              amount: price.toString(),
              paymentType: PlatformPay.PaymentType.Immediate,
            },
          ],
          merchantCountryCode: 'AE',
          currencyCode: 'AED',
        
        },
      }
    );
    //Alert.alert("after confir,payment")
    console.log("After confirmPlatformPayPayment");
    if (error) {
      // handle error
      
      Alert.alert(error.code, error.message);
     
      console.log("error in apple pay=======",error)
    } else {
      //Alert.alert('Success', 'Check the logs for payment intent details.');
      console.log(JSON.stringify(paymentIntent, null, 2));
      console.log('Success from promise', paymentIntent);
   //   Alert.alert("success payment",paymentIntent.id)
      setTransactionId(paymentIntent.id)
      console.log("paument method....", paymentIntent?.paymentMethod)
      console.log("pay id", paymentIntent.status);
     // Alert.alert("status",paymentIntent.status)
      if (paymentIntent.status == "Succeeded") {
       setMsg("Payment success");
        setAlertVisible(true)
        setAlertVisible2(false)
        if(serviceId&&vendorId&&carId&&slotId&&bookingDate&&countryCode&&phoneNo&&paymentIntent.id){
        navigation.navigate("Success", {
          "car": car,
          "carId": carId,
          "serviceId": serviceId,
          "bookingDate": bookingDate,
          "slotId": slotId,
          "serviceId": serviceId,
          "vendorId": vendorId,
          "serviceName": serviceName,
          "price": price,
          "vendorId": vendorId,
          "serviceName": serviceName,
          "price": price,
          "serviceId": serviceId,
          "vendorId": vendorId,
          transactionId: paymentIntent.id,
          housenum: housenum, street: street,
          countryCode: countryCode.toString()
          , phoneNo: phoneNo,
          addresslabel: addresslabel,
          buildingname: buildingname,
          company: company,
          floor: floor,
          addressType: addressType,
          paymentType: activeTab.toString() == "1".toString() ? "Card" : activeTab.toString() == "2".toString() ? "Apple Pay" : "COD",
          totalPrice: totalPrice ? totalPrice : "",
          quantity: quantity ? quantity : "",
          cartId: cartId ? cartId : ""
        })
      }
    }
  }
  };
