### ISSUE TITLE
Insecure encryption mode CBC with PKCS7 in nimbus-jose-jwt

### ISSUE THREAD

**Issue by Rananjaya** [stripe/stripe-react-native#1432]
We got a security vulnerability from our pentest team, “The application uses insecure encryption mode CBC with PKCS7 padding, an insecure and deprecated algorithm.” And it is related to com.nimbusds:nimbus-jose-jwt maven package which is a dependancy of com.stripe:stripe-3ds2-android package. 

Included files:

com.ourappidentifier/com/nimbusds/jose/crypto/impl/AESCBC.java

com.ourappidentifier/com/nimbusds/jose/jca/JCASupport.java

 

Pentest Team Recommendations:

During the testing we observed that the application uses deprecated encryption mode CBC with PKCS5/PKCS7 padding. This type of configuration is vulnerable to padding oracle attack. Verify that cryptographic algorithms are up to date and in-line with industry standards.  https://owasp.org/www-project-mobile-top-10/2016-risks/m5-insufficientcryptography

This is the dependancy tree:

project :stripe_stripe-react-native

+--- com.stripe:stripe-android:20.9.+ -> 20.9.0

        +--- com.stripe:payments-core:20.9.0

                +--- com.stripe:stripe-core:20.9.0

                        +--- com.stripe:stripe-3ds2-android:6.1.5

                                +--- com.nimbusds:nimbus-jose-jwt:9.21

<img width="855" alt="MicrosoftTeams-image (1)" src="https://github.com/stripe/stripe-react-native/assets/34897947/ff27c7db-6a0c-4237-92ac-db802edbedfb">

**Comment by jameswoo-stripe** [comment]
See this [changelog](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/ff5608a1abf41e10acfedf076d9e87a78f52d07c/SECURITY-CHANGELOG.txt#lines-22) as well.
