### ISSUE TITLE
Keyboard closes and opens on ios while I am filling in the data in payment sheet

### ISSUE THREAD

**Issue by MPuzio15** [stripe/stripe-react-native#1434]
**Describe the bug**
Keyboard closes and opens on ios while I am filling in the data in payment sheet, like below:

https://github.com/stripe/stripe-react-native/assets/51422006/59db769a-1b37-494d-9a6f-e6b72de1d7dd

**To Reproduce**
1. Fill the data in payment sheet in

**Expected behavior**
Keyboard should stay open

 - iOS,
 - Version @stripe/stripe-react-native": "0.17.0",

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone Xs Max, iphone Xs], iphone simulators

**Comment by charliecruzan-stripe** [comment]
Hi! this is fixed in the most recent versions of stripe-react-native

**Comment by faheem-ul** [comment]
I'm facing the same issue but in Next js, web mobile responsiveness.
