### ISSUE TITLE
Google Pay amount displaying 0 in confirmPlatformPaySetupIntent 

### ISSUE THREAD

**Issue by Filippo39** [stripe/stripe-react-native#1436]
In my application, setupIntent is used for payment management, where in some cases the price is known and in others it is not. In Android, the confirmPlatformPaySetupIntent function does not allow setting the displayed amount (it always shows €0.00) nor a label to provide more details to the user.
After doing some research, I noticed that a similar issue has already been resolved for Flutter. 
https://github.com/flutter-stripe/flutter_stripe/issues/1250

I was wondering if it would be possible to get the same modification for React Native.

 - Device: Redmi Note 10
 - OS: Android
 - Version 11
- SDK version 0.27.2

**Comment by charliecruzan-stripe** [comment]
hi @Filippo39 ! Could you provide some more info for me to reproduce Google Pay showing 0 for the price? On my device the price isn't showing (either for payment intents or setup intents) and in Google's docs, it states "This price is not displayed to the user." so they state you should show the price in your own UI.

**Comment by Filippo39** [comment]
I'm using:
```
const { error } = await confirmPlatformPaySetupIntent(
  res.data.clientSecret,
  getStripeConfirmParam(...)
)
```
where `getStripConfirmParam` returns for google:
```
    googlePay: {
    testEnv: testEnv,
    merchantName: 'Test SRL',
    merchantCountryCode: 'IT',
    currencyCode: 'EUR',
    existingPaymentMethodRequired: false,
  },
  ```
  
  and it shows:
  ![2023-08-04_14-13](https://github.com/stripe/stripe-react-native/assets/33987920/c733019a-700c-419f-a2d1-edff20dd0d46)

**Comment by Filippo39** [comment]
> @charliecruzan-stripe I'm using:
> 
> ```
> const { error } = await confirmPlatformPaySetupIntent(
>   res.data.clientSecret,
>   getStripeConfirmParam(...)
> )
> ```
> 
> where `getStripConfirmParam` returns for google:
> 
> ```
>     googlePay: {
>     testEnv: testEnv,
>     merchantName: 'Test SRL',
>     merchantCountryCode: 'IT',
>     currencyCode: 'EUR',
>     existingPaymentMethodRequired: false,
>   },
> ```
> 
> and it shows: ![2023-08-04_14-13](https://user-images.githubusercontent.com/33987920/258416346-c733019a-700c-419f-a2d1-edff20dd0d46.png)

**Comment by charliecruzan-stripe** [comment]
thanks! It was the `merchantCountryCode`- I guess Google shows this for EU countries. I've asked the stripe-android team about this, but in the meantime you can use `createPlatformPayPaymentMethod` which does let you set an amount

**Comment by tillh-stripe** [comment]
Hi @Filippo39 👋 I’m from Stripe’s Android team. We reached out to our contacts at Google to understand whether we can just pass in a `null` amount for setup intents. If that’s possible, it would hide the `Pay merchant` line entirely. I’ll let you know once we hear back.

**Comment by Filippo39** [comment]
Hi @tillh-stripe, it would be nice to have the possibility to show a custom amount for android, in order to keep consistency with ios:
```
applePay: {
    cartItems: [
      ...cartItems.map(
        (item) =>
          ({
            label: item.label,
            amount: X,
            paymentType: PlatformPay.PaymentType.Immediate,
          } as PlatformPay.CartSummaryItem)
      ),
      {
        label: 'Total',
        amount: totalAmount,
        paymentType: PlatformPay.PaymentType.Immediate,
      },
    ],
    merchantCountryCode: 'IT',
    currencyCode: 'EUR',
  },
```

**Comment by tillh-stripe** [comment]
Gotcha, I’ll also ask about that!

**Comment by tillh-stripe** [comment]
Makes sense. I’ll look into making that possible!

**Comment by dmengelt** [comment]
@tillh-stripe passing in a `null` amount is not possible. I believe what @Filippo39 suggested (aligning with Apple Pay) is the best solution going forward. 

Technically, there is a way to "hide" the `Pay merchant` line by setting `totalPriceStatus=NOT_CURRENTLY_KNOWN`. However, this should not be used for EEA countries and therefore isn't a solution in this case.

**Comment by tillh-stripe** [comment]
We just merged the necessary change on Android: https://github.com/stripe/stripe-android/pull/7191

Once @charliecruzan-stripe adds the necessary React Native support, you’ll be able to provide a custom amount (and a custom label!) for setup intents.

**Comment by Filippo39** [comment]
[celebrate]     Filippo Mantovan reacted to your message:
________________________________

**Comment by Filippo39** [comment]
Unfortunately, despite this change, I continue to see €0, perhaps there is a block on the part of Google Pay
```
  googlePay: {
    testEnv: testEnv,
    merchantName: 'Test SRL',
    merchantCountryCode: 'IT',
    currencyCode: 'EUR',
    existingPaymentMethodRequired: false,
    amount: 10,
    label: 'Label'
  },
  ```

**Comment by charliecruzan-stripe** [comment]
hi @Filippo39 , this is working for me on the most recent version, using the same code you shared above-
<img width="325" alt="Screenshot 2023-09-28 at 7 57 19 AM" src="https://github.com/stripe/stripe-react-native/assets/97612659/2de48486-0fb5-48aa-a4e5-0416db8c00d2">

Are you sure you're on the most recent version?

**Comment by Filippo39** [comment]
Yes it works, I had to clear the node modules after updating the library, thanks

**Comment by Filippo39** [comment]
@charliecruzan-stripe 
I still have two questions:
- There is a reason why on Android an amount of `amount: 100` corresponds to 1€ while on iOS an `amount: 100` corresponds to €100
- Also according to `GooglePayBaseParams` the amount and label should be two optional fields, but if I avoid settings them, a crash occurs
![image](https://github.com/stripe/stripe-react-native/assets/33987920/880d1bc0-d402-46b5-b8a4-87ad0e97f729)

**Comment by charliecruzan-stripe** [comment]
> There is a reason why on Android an amount of amount: 100 corresponds to 1€ while on iOS an amount: 100 corresponds to €100

Different behaviors of Apple Pay/Google Pay. I'll reflect that in the docs.

> Also according to GooglePayBaseParams the amount and label should be two optional fields, but if I avoid settings them, a crash occurs

Fixed this, sorry about that!

**Comment by tuanlevi95** [comment]
> > There is a reason why on Android an amount of amount: 100 corresponds to 1€ while on iOS an amount: 100 corresponds to €100
> 
> Different behaviors of Apple Pay/Google Pay. I'll reflect that in the docs.
> 
> > Also according to GooglePayBaseParams the amount and label should be two optional fields, but if I avoid settings them, a crash occurs
> 
> Fixed this, sorry about that!

what is the docs of Different behaviors of Apple Pay/Google Pay.?
