### ISSUE TITLE
Tap-To-Pay 

### ISSUE THREAD

**Issue by Joshandrews43** [stripe/stripe-react-native#1442]
Would love to see tap to pay be an option so that our users can turn their device into a card reader!

**Comment by Pelps12** [comment]
Is there any limitation of the react native SDK that prevents this?

**Comment by Pelps12** [comment]
I think it might be available in the stripe terminal sdk. Different repo

**Comment by charliecruzan-stripe** [comment]
Yep, for tap to pay, please take a look at https://github.com/stripe/stripe-terminal-react-native

**Comment by nfs43** [comment]
I have run its native android code, but in react native I ended up in a smoke.

**Comment by Joshandrews43** [comment]
The examples surrounding react native here are not great, still never figured it out and gave up

**Comment by nfs43** [comment]
luckily, I have run the example successfully.

**Comment by nfs43** [comment]
> The examples surrounding react native here are not great, still never figured it out and gave up

I can help you if you like
