### ISSUE TITLE
iOS App crashes on presentPaymentSheet()

### ISSUE THREAD

**Issue by WinstonNau** [stripe/stripe-react-native#1447]
**Describe the bug**
I implemented the payment sheet implementation like shown in the Stripe docs. Everything works without any problems on my Android Emulator, but once I try to run the application on an iOS Simulator or an iOS physical device, the application crashes as soon as I click on the button to present the payment sheet. Payment Intents are being created, but not fulfilled due to the payment sheet not opening.

**Code Used**

```
  const fetchPaymentSheetParams = async () => {
    const currentUser = auth().currentUser;

    if (!currentUser) {
      return null;
    } else {
      const token = await currentUser.getIdToken();
      const response = await createPaymentSheet(
        token,
        event.event_uid,
        event.price,
        numberOfTickets,
      );

      const {paymentIntent, ephemeralKey, customer} = await response.json();

      return {
        paymentIntent,
        ephemeralKey,
        customer,
      };
    }
  };

  const initializePaymentSheet = async () => {
    const result = await fetchPaymentSheetParams();

    if (result) {
      const {paymentIntent, ephemeralKey, customer} = result;

      const {error} = await initPaymentSheet({
        merchantDisplayName: 'Placeholder',
        customerId: customer,
        customerEphemeralKeySecret: ephemeralKey,
        paymentIntentClientSecret: paymentIntent,
        // Set `allowsDelayedPaymentMethods` to true if your business can handle payment
        //methods that complete payment after a delay, like SEPA Debit and Sofort.
        allowsDelayedPaymentMethods: false,
        defaultBillingDetails: {
          name: 'Jane Doe',
        },
      });

      if (!error) {
        setLoading(true);
      } else {
        console.log(error);
      }
    }
  };

  const openPaymentSheet = async () => {
    actionSheetRef.current?.hide();
    await initializePaymentSheet();

    const {error} = await presentPaymentSheet();
    setLoading(false);

    if (error) {
      actionSheetRef.current?.show();
    } else {
      Alert.alert('Success', 'Your order is confirmed!');
    }
  };
```

`openPaymentSheet()` is the function being called on Button click.

**Expected behavior**
Payment sheet opens without any problem.

**Xcode Error Screenshot**
<img width="1512" alt="Screenshot 2023-07-06 at 14 40 26" src="https://github.com/stripe/stripe-react-native/assets/41019693/4959d46a-7ec2-460d-bb26-2bd7aed88cd7">

**Smartphone (Used Testing Devices):**
 - Device: iPhone Xr (physical) / iPhone 14 Pro (Simulator)
 - OS: iOS 16.1.2 / iOS 16.2

**package.json**
```
{
  "name": "WgwApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.18.2",
    "@react-native-community/geolocation": "^3.0.6",
    "@react-native-firebase/app": "^17.5.0",
    "@react-native-firebase/auth": "^17.5.0",
    "@react-native-firebase/storage": "^18.0.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "@stripe/stripe-react-native": "^0.28.0",
    "react": "18.2.0",
    "react-hook-form": "^7.43.9",
    "react-native": "0.71.8",
    "react-native-actions-sheet": "^0.8.29",
    "react-native-date-picker": "^4.2.13",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-fbsdk-next": "^11.2.1",
    "react-native-image-picker": "^5.3.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-maps": "^1.7.1",
    "react-native-open-maps": "^0.4.2",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-reanimated": "2.17.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0",
    "react-native-snackbar": "^2.6.2",
    "react-native-svg": "^13.9.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-vision-camera": "^2.15.4",
    "vision-camera-code-scanner": "^0.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I appreciate any help! :)

**Comment by WinstonNau** [comment]
> Try adding the returnUrl. I had the same issue and this was the fix for me:
> 
> ```
> const {error} = await initPaymentSheet({
>         merchantDisplayName: 'Placeholder',
>         returnURL: 'your-app://stripe-redirect',
>         customerId: customer,
>         customerEphemeralKeySecret: ephemeralKey,
>         paymentIntentClientSecret: paymentIntent,
>         // Set `allowsDelayedPaymentMethods` to true if your business can handle payment
>         //methods that complete payment after a delay, like SEPA Debit and Sofort.
>         allowsDelayedPaymentMethods: false,
>         defaultBillingDetails: {
>           name: 'Jane Doe',
>         },
>       });
> ```
> 
> Look here for more details: https://stripe.com/docs/payments/save-and-reuse?platform=react-native&ui=payment-sheet#set-up-return-url

I implemented the return url, as well as deep linking in general into my react native app, but I still get the same error.
Any other ideas maybe?

**Comment by robinveraconnect** [comment]
Is the `setLoading` set to true? If not, what does the error say in the log?
Could you also provide the implementation that is behind `createPaymentSheet`?

**Comment by charliecruzan-stripe** [comment]
Hey @WinstonNau ! Could you try re-installing your Pods? This is looking for a file that should be bundled in by the Stripe iOS SDK, so I'm not sure what would prevent that file from being included in your app 🤔 You could also file-search in Xcode (shift + cmd + O) for `form_specs.json` to double-check it was included by the dependency

**Comment by WinstonNau** [comment]
> Hey @WinstonNau ! Could you try re-installing your Pods? This is looking for a file that should be bundled in by the Stripe iOS SDK, so I'm not sure what would prevent that file from being included in your app 🤔 You could also file-search in Xcode (shift + cmd + O) for `form_specs.json` to double-check it was included by the dependency

Thank you so much, it works now! Re-installing my Pods fixed the issue (even though I was so sure I did that already). I did find the file before re-installing the Pods though, so not sure what caused the issue in the first place. I appreciate your help, so have a good rest of your week! :)

**Comment by charliecruzan-stripe** [comment]
awesome! thanks for following up 👍
