### ISSUE TITLE
Apple Pay shows support phone number on bank statement when 'show on receipt and invoices' is turned off

### ISSUE THREAD

**Issue by robinveraconnect** [stripe/stripe-react-native#1450]
**Describe the bug**
Our app accepts apple pay, iDeal and Google Pay. In our Stripe dashboard > Settings > Public details we have a support phone number and the option 'show on receipt and invoices' is turned off. Whenever someone pays via iDeal you don't see the support phone number on their bank statement. You just see the 'Statement descriptor' we configured. When you use Apple Pay it does show the support phone number on their bank statement. Like: "COMPANY NAME +31612345678".

I could not find anything about this, therefore I have the assumption this may be a bug. 

**Expected behavior**
If the option 'show on receipt and invoices' is turned off, don't show the support phone number if you are using Apple Pay (or any of the payment options)

**Other Context**
I could not test if this also happens on Google Pay.

**Comment by charliecruzan-stripe** [comment]
hi @robinveraconnect ! Thanks for the issue, I understand this is confusing :/ 

That setting is _only_ for Stripe Billing. We'll clear this up internally so it's more obvious what that setting will actually affect!

**Comment by robinveraconnect** [comment]
@charliecruzan-stripe Is there another way to remove the support phone number from their bank statement when people use Apple Pay?

**Comment by charliecruzan-stripe** [comment]
Not through Stripe, that's up to the individual bank

**Comment by robinveraconnect** [comment]
@charliecruzan-stripe but if I change the support phone number in that setting via stripe it also changes in the bank statement when using Apple Pay. So somehow the individual bank gets the phone number from stripe, right?
