### ISSUE TITLE
AddressSheet throws error when submitting with keyboard open (v0.29)

### ISSUE THREAD

**Issue by jgrrr** [stripe/stripe-react-native#1457]
**Describe the bug**
If user clicks the submit button with keyboard open, onError callback is called instead of onSubmit

**To Reproduce**
1. set up an address sheet
2. feel address with anything
3. keep the keyboard open
4. scroll down if necessary
5. click submit

**Expected behavior**
onSubmit should be called instead of onError

**Smartphone (please complete the following information):**
Android simulator Pixel 5 API 31

**Additional context**
Downgrading to v0.28 fixes the problem.
my react native version in use:
"react": "18.1.0",
 "react-native": "0.70.6",

**Comment by charliecruzan-stripe** [comment]
hey @jgrrr ! Thanks for the report- a fix has landed in stripe-android and will be released next monday!
