### ISSUE TITLE
Google pay issuing merchant is having trouble ...

### ISSUE THREAD

**Issue by december1990** [stripe/stripe-react-native#1459]
hello hello 

I have configured the stripe payment based on the docs at https://stripe.com/docs/payments/accept-a-payment?platform=react-native using Mobile Payment Element, according to this page to enable google pay we need to change build.gradle, manifest and set googlePay to true, now google pay is not working in production and it prompts that the merchant is having trouble accepting your payment at the moment, OR_BIBED_11 . I searched the issues and faced some posts talking about google instructions to enable google pay live mode, is it necessary for mobile payment element integration as well ?? if yes, do I need to add some code to our app like api key or something and republish our app? It's strange that it used to work 🧐

implementation 'com.google.android.gms:play-services-wallet:19.1.0'
implementation 'com.stripe:stripe-android:20.13.0'
Stripe version : 0.19.0

thanks

**Comment by charliecruzan-stripe** [comment]
Hi! You shouldn't need to add the the 
```implementation 'com.google.android.gms:play-services-wallet:19.1.0'
implementation 'com.stripe:stripe-android:20.13.0'
```
block to your code, this library takes care of that for you. For going live with Google Pay, please follow [this guide](https://stripe.com/docs/google-pay?platform=react-native#going-live-react-native)

**Comment by VTSingle** [comment]
@december1990 Hey, how you solved your problem? 
I faced with this issue too.

**Comment by december1990** [comment]
In order 

> @december1990 Hey, how you solved your problem? I faced with this issue too.

In order for google pay to work on production release you need to follow  https://stripe.com/docs/google-pay?platform=react-native#going-live-react-native , it asks you about your business and asks for some screen shots of your payment flow in your app, then they review your app. If your app is in production and google pay is not working, just follow the link and after review process it's gonna work so you don't need to publish a new release.
