### ISSUE TITLE
font scaling doesn't scale right on Android

### ISSUE THREAD

**Issue by kauamelo** [stripe/stripe-react-native#1468]
**Describe the bug**
Font scaling in `initPaymentSheet` doesn't scale for decimals on Android.
It works fine on iOS.

**To Reproduce**
1. On initPaymentSheet, try the following:
```
appearance: {
    font: { scale: 1.0 },
    ...
```
![image-20230801-132355](https://github.com/stripe/stripe-react-native/assets/100595841/a32d98bd-c388-4b58-a392-eda6b510bdbc)

2. Now, try to use 1.9 and you'll see that they are the same font size
```
appearance: {
    font: { scale: 1.9 },
    ...
```
![image-20230801-132654](https://github.com/stripe/stripe-react-native/assets/100595841/39f0a8de-9d2e-4c4d-9118-18c03f6712e0)

3. Now, try 2.0 and you'll see that the font gets super big.
```
appearance: {
    font: { scale: 2.0 },
    ...
```
![image-20230801-132840](https://github.com/stripe/stripe-react-native/assets/100595841/1bf82bc1-eabf-4916-93ed-bec90d46db0a)

It seems like the package can't scale on a decimal level on Android. It's either 1 or 2, or 3. 
1.1 seems to be the same as 1.9 as show in the example. Meaning we can only scale the font by 100% on Android.

**Expected behavior**
Should be able to scale on a decimal level on Android in the same way that it's possible on iOS.
For example, here'e scale 1.15, 1.9, and 2.0 on iOS:

1.15
![1 15](https://github.com/stripe/stripe-react-native/assets/100595841/90f70dd7-7159-4ed4-8a8a-a9478f96eabb)
:

1.9:
![1 9](https://github.com/stripe/stripe-react-native/assets/100595841/b027a3b9-0f6c-407f-ae1f-05dc77aa66e9)

2.0:
![2 0](https://github.com/stripe/stripe-react-native/assets/100595841/f10c3ec1-2959-4ced-86d9-8572d084cf66)

**Smartphone (please complete the following information):**
 - Device: Android Emulator: Pixel 4
 - OS: Android Tiramisu / API 33

**Comment by charliecruzan-stripe** [comment]
Taking a look at this today!

**Comment by kauamelo** [comment]
Wow, thank you so much @charliecruzan-stripe  :)
That was super fast!

**Comment by charliecruzan-stripe** [comment]
Sure thing! Will merge the PR today and it will be published either this week or the next (we have another change in progress that we're waiting on something upstream for)
