### ISSUE TITLE
Android build failed, Failed to apply plugin 'kotlin-android'.

### ISSUE THREAD

**Issue by echolove38** [stripe/stripe-react-native#1470]
1: Task failed with an exception.
-----------
* Where:
Build file 'node_modules\@stripe\stripe-react-native\android\build.gradle' line: 18

* What went wrong:
A problem occurred evaluating project ':stripe_stripe-react-native'.
> Failed to apply plugin 'kotlin-android'.
   > The current Gradle version 6.8 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.8.3 or newer, or the previous version of the Kotlin plugin.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

how to solve this error?

**Comment by charliecruzan-stripe** [comment]
Hi! Please fill out all of the information we ask for in the issue template, that way we can help you effectively

Some things I would check: 
- Check that the version of Stripe React Native is compatible with your version of React Native (as of v0.8.0, you must use RN 0.64 or above)
- Check to see if you have the correct version of Gradle installed for that version of React Native

**Comment by echolove38** [comment]
> 

where is the template

**Comment by charliecruzan-stripe** [comment]
It's pre-filled in the Github issue content when you create an issue

**Comment by echolove38** [comment]
> Hi! Please fill out all of the information we ask for in the issue template, that way we can help you effectively
> 
> Some things I would check:
> 
> * Check that the version of Stripe React Native is compatible with your version of React Native (as of v0.8.0, you must use RN 0.64 or above)
> * Check to see if you have the correct version of Gradle installed for that version of React Native

which version of stripe react native should I use, my react native version is 0.64.2
