### ISSUE TITLE
Android build failed: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

### ISSUE THREAD

**Issue by echolove38** [stripe/stripe-react-native#1471]
**Describe the bug**
Execution failed for task ':app:mergeDebugResources'.
> C:\Users\008-00001\.gradle\caches\transforms-3\2910f62b59b739dcebb2adff389060bc\transformed\material-1.8.0\res\values\values.xml: Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

**To Reproduce**
1. yarn add @stripe/stripe-react-native
2. change compileSdkVersion to 33
3. yarn android

**Expected behavior**
build success

**Screenshots**
![image](https://github.com/stripe/stripe-react-native/assets/12425497/7a9336ae-b0ba-498b-983f-fa9ed3e89e8a)

**Smartphone (please complete the following information):**
 - Device: [Pixel 4 API 32 emulator]
 - OS: [android]
 - Version [12]

**Additional context**
react native version: 0.64.4
expo version: 41
@stripe/stripe-react-native: 0.30.0
Android Gradle Plugin Version: 4.1.3
Gradle Version: 6.8.3

**Comment by nicolasdevienne** [comment]
https://github.com/stripe/stripe-react-native/issues/1294#issuecomment-1426150258

**Comment by echolove38** [comment]
> Hi @echolove38, same "issue" for me. I must had been upgrade react native version from 0.66.4 to the last 0.72.3 and now it works. You can read this : [#1294 (comment)](https://github.com/stripe/stripe-react-native/issues/1294#issuecomment-1426150258)
I try to upgrade rn, but it is too old, have many issues after upgrade, can not run.

**Comment by nicolasdevienne** [comment]
> > Hi @echolove38, same "issue" for me. I must had been upgrade react native version from 0.66.4 to the last 0.72.3 and now it works. You can read this : [#1294 (comment)](https://github.com/stripe/stripe-react-native/issues/1294#issuecomment-1426150258)
> 
> I try to upgrade rn, but it is too old, have many issues after upgrade, can not run.

Same for me. Upgrade from the original project is impossible... So I start a new project and reborn step by step... 😅

**Comment by charliecruzan-stripe** [comment]
Hi! This is due to stripe-android using Google material 1.8.0. Besides upgrading your project's RN version, the only other option is to use an older version of stripe-react-native, specifically v0.23.0, which uses an older version of stripe-android, which has google material 1.5.0 pinned

**Comment by syaznidin** [comment]
hi. how did you manage to solve this?

**Comment by Pragnesh-Dharajiya** [comment]
@echolove38  i don't use the stripe packages but still i facing same issue also i upgrade sdk 31 to 33

**Comment by Jagdish-958** [comment]
{"kind":"error","text":"Can't determine type for tag '<macro name=\"m3_comp_assist_chip_container_shape\">?attr/shapeAppearanceCornerSmall</macro>'",      Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'
    how i slove this  (and my  gradle 7.0.2
                                              gradle plugin is - 7.0.4
                                        and kotlin_version = "1.6.20"
                                           compileSdkVersion 33
                                                  minSdkVersion 23
                                                       targetSdkVersion 33 )

**Comment by Jagdish-958** [comment]
implementation "com.stripe:stripe-android:20.36.0"
    implementation 'com.github.HITGIF:TextFieldBoxes:1.4.5'

**Comment by Jagdish-958** [comment]
implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.8.0'

**Comment by mendozammatias** [comment]
> it may be related to react-native-screen module. You can fix this issue by this way: go to node_modules/react-native-screens/android/build.gradle file and
> 
> dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }

You saved me hours of pain 🙏🏼

**Comment by avinashpandey-sdn** [comment]
> it may be related to react-native-screen module. You can fix this issue by this way: go to node_modules/react-native-screens/android/build.gradle file and
> 
> dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }



thank bro  it's working

**Comment by rafabulsing** [comment]
> it may be related to react-native-screen module. You can fix this issue by this way: go to node_modules/react-native-screens/android/build.gradle file and
> 
> dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }

Instead of manually changing that file, try also just fixing the `react-native-screen` version to [3.25.0])https://github.com/software-mansion/react-native-screens/releases/tag/3.25.0), which is the latest version where that Material dependency is still the older one.

**Comment by Samamoah** [comment]
> {"kind":"error","text":"Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall'", Error: Can't determine type for tag '?attr/shapeAppearanceCornerSmall' how i slove this (and my gradle 7.0.2 gradle plugin is - 7.0.4 and kotlin_version = "1.6.20" compileSdkVersion 33 minSdkVersion 23 targetSdkVersion 33 )

You saved me with this. Thanks

**Comment by rafaelzao14** [comment]
> > it may be related to react-native-screen module. You can fix this issue by this way: go to node_modules/react-native-screens/android/build.gradle file and
> > dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }
> 
> Instead of manually changing that file, you can also try fixing the `react-native-screen` version to [3.25.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.25.0), which is the latest version where that Material dependency is still the older one.

This worked for me, but i had to update de minSdk and TargetSdk and Compiled Sdk, minSdk 23 and Compile and Targe to 32. Obs: i remove the ^ of react-native-screens in the package.json to install specifically the 3.25.0

**Comment by Akash9923** [comment]
You can force a specific version of the dependency to be used in your project by adding the following code in your build.gradle file
 configurations.all {
    resolutionStrategy {
        force 'com.google.android.material:material:1.1.0'
    }
}

This worked for me

**Comment by Usama-Saud** [comment]
> it may be related to react-native-screen module. You can fix this issue by this way: go to node_modules/react-native-screens/android/build.gradle file and
> 
> dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }


Thank you!
I was facing this error! 

- Change in node_modules > react-native-screens > android > build.gradle file
- dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }

**Comment by aliyanlatif** [comment]
> it may be related to react-native-screen module. You can fix this issue by this way: go to node_modules/react-native-screens/android/build.gradle file and
> 
> dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }

you are a saviour, this solved the issue for me

**Comment by thachbl** [comment]
> it may be related to react-native-screen module. You can fix this issue by this way: go to node_modules/react-native-screens/android/build.gradle file and
> 
> dependencies { ... implementation 'com.google.android.material:material:1.9.0' => 1.6.0 (change version) ... }

Thank you so much
