### ISSUE TITLE
Card details not complete or  last4 returns null

### ISSUE THREAD

**Issue by 520hxw** [stripe/stripe-react-native#1475]
**Describe the bug**

When I use the onCardChange method of the CardField component, I enter the test card number 4242 4242 4242 4242, then "complete: true" is returned, but last4 returns null. Finally, when I called the confirmPayment method, it returned "Card details not complete"

**Screenshots**
![image](https://github.com/stripe/stripe-react-native/assets/92533959/8558930d-775b-41d6-9e13-1c5ac67bb202)
![image](https://github.com/stripe/stripe-react-native/assets/92533959/3a733636-63c6-4b6b-a415-2912ad97ec5d)

**Smartphone (please complete the following information):**
 - Device: [OnePlus 6]
 - OS: [Android 10]
 
"@stripe/stripe-react-native": "0.15.0"

**Comment by micahcharlesbrown** [comment]
Seeing this on all cards android devices. iOs devices strangely don't experience the bug, historically has been working otherwise

**Comment by micahcharlesbrown** [comment]
@520hxw - which version of react native are you using? We started to see this after upgrading to `0.72.4`

**Comment by Pratik-2102** [comment]
hi @micahcharlesbrown  I am on  0.72.3 version of React native. I am also experiencing the same thing. Is there any solution  on it ?

**Comment by charliecruzan-stripe** [comment]
I'm not able to reproduce this on v0.35.0- is anyone running into this on a recent version?
