### ISSUE TITLE
onShippingMethodSelected triggers with the wrong shippingMethod

### ISSUE THREAD

**Issue by aurelien-robineau** [stripe/stripe-react-native#1476]
**Describe the bug**
When updating the shipping methods with `updatePlatformPaySheet`, the `onShippingMethodSelected` method is triggered. However, the `shippingMethod` of the event is the previously selected one, and not the new one (by default, the first one of the new methods).

For example, if I have shipping method A available (and selected), then I update the methods with only method B. By default, Apple Pay selects the method B because it is the only one available. But `onShippingMethodSelected` triggers with shipping method A.

I am not sure if it is a bug or the desired behavior?

**To Reproduce**
1. Initialize the payment sheet with some shipping methods.
2. Update the shipping methods with new methods using `updatePlatformPaySheet`.
3. Log the shipping method attached to the event of `onShippingMethodSelected`.
4. You can see the shipping method is one of the previous ones.

**Expected behavior**
The shipping method attached the the event of `onShippingMethodSelected` should be the new selected shipping method, which by default seems to be the first of the new shipping methods.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro (Xcode Simulator)
 - OS: iOS 16.4 (and macOS 13.4.1)

**Comment by RyanONeill1970** [comment]
I see this on another platform as well (Adyen) when paying via Apple Pay. It seems to be a bug in the core Apple Pay JS API.

**Comment by aurelien-robineau** [comment]
Interesting. Reading a bit through the code of `stripe-react-native` does not reveal anything that could be the source of the issue. This might indeed be a bug in the core API.
