### ISSUE TITLE
unexpected keyword 'export' error on android

### ISSUE THREAD

**Issue by salihgun** [stripe/stripe-react-native#1482]
**Describe the bug**
I am using 0.5.0 version and my react native version is 0.61.3 . So i am getting "Unexpected keyword 'export'" no stack error 

**Screenshots**
![Screenshot 2023-08-24 at 15 30 53](https://github.com/stripe/stripe-react-native/assets/47421572/5a2fff65-8152-4876-a668-3d8103470c22)

**Comment by charliecruzan-stripe** [comment]
Hi, unfortunately there's not much to go off of here with this issue. Could be a bundler issue, not sure though. I would recommend upgrading your version since 0.5.0 is over a year old. If you run into any other issues, please share the full stack trace and I'll be happy to help!

**Comment by salihgun** [comment]
I upgrade the version to 0.19.0 and make compileSdkVersion = 33, now i get below error.
<img width="377" alt="Screenshot 2023-08-31 at 16 18 20" src="https://github.com/stripe/stripe-react-native/assets/47421572/cd08b64d-fe24-4ce1-bca0-685ecae1c975">
