### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by Isra1610** [stripe/stripe-react-native#1483]
When paying with Stripe on iOS, if the card or bank requires 2FA, the Safari browser opens to input the code, but after that, closing the window can be confusing as an error "Safari cannot open the page because the address is invalid" appears.

Perhaps the flow during payment and when adding the card can be confusing.

Instructions to reproduce the bug
Open Customer App
Add producs to cart
Add card with 3D Secure enabled 4000002760003184
Complete order

i'm using "@stripe/stripe-react-native": "0.23.0" but also i used until "0.27.0", RN: "^0.64.2",

However i was able to complete the card register and when i came back to the app data comes with "success"

![image](https://github.com/stripe/stripe-react-native/assets/86847451/8b1a0af9-b8a9-4576-a5bc-331c86e0d6c2)

**Comment by qichuan** [comment]
Looks like Safari is unable to recongize your custom URL.

You should check the Xcode project configuration, and make sure the custom URL scheme that you use is [registered](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app#Register-your-URL-scheme) under the URL Types section.
