### ISSUE TITLE
`onShippingContactSelected` is not available in `usePlatformPay`

### ISSUE THREAD

**Issue by huextrat** [stripe/stripe-react-native#1484]
`useApplePay` has been removed, so the callback `onShippingContactSelected` is no longer available except if you are using `PlatformPayButton`.

Would be super useful to keep both callback `onShippingMethodSelected` and `onShippingContactSelected`  when we are using a custom button to start native payment with `usePlatformPay`.

If there is a way to do this, I can help with the PR.

**Comment by huextrat** [comment]
Our use case is pretty simple, we need to retrieve `shippingContact` in particular the postal address before payment is made.

I would be glad to use the native button, but for now there is missing styling props. This is how it looks when user presses the `PlatformPayButton`, that opacity during the `onPress` is not acceptable for my app.

![Capture d’écran 2023-08-30 à 21 41 27](https://github.com/stripe/stripe-react-native/assets/22995315/14d8bbea-a961-4ea6-91ff-76d68c906f79)

I'll take a look on `ApplePayButtonView.swift` and I'll try to contribute to make it more customizable.

**Comment by huextrat** [comment]
@charliecruzan-stripe Just made a PR https://github.com/stripe/stripe-react-native/pull/1487 to make the opacity during `onPress`

Looks kinda hacky, but it seems that Apple does not provide any API to custom style except the provided one :/

**Comment by charliecruzan-stripe** [comment]
So you'd apply your own custom opacity to the button? That would run the risk of app store rejection since the Apple Pay button needs to match Apple's branding guidelines
