### ISSUE TITLE
StripeSDK iOS 'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'

### ISSUE THREAD

**Issue by adamplenti** [stripe/stripe-react-native#1488]
**Describe the bug**
When XCode builds the application, the error described below is returned. The error occurs only on iOS. My package versions are:
- "@stripe/stripe-react-native": "0.30.0", (but the same problem exist ex. in 0.27.2)
- "react-native": "0.70.8",

**To Reproduce**

1. Build app by XCode
2. See error in @stripe/stripe-react-native/ios/StripeSdk.swift:194:58

**Expected behavior**
The iOS Application builds correctly.

> [!IMPORTANT]  
> The change described below fixed this error

change this fragment:
```
paymentOption.image.pngData()
```
to this fragment:
```
UIImagePNGRepresentation(paymentOption.image)
```

**Screenshots**

![CleanShot 2023-08-31 at 12 39 34@2x](https://github.com/stripe/stripe-react-native/assets/95696811/e205e35e-b514-4381-81a3-b32aab51bfae)

> [!NOTE]  
> The variables below have no meaning

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4 (22F66)
 - Browser Arc
 - Version -

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro/Pro Max [Emulators]
 - OS: iOS 16
 - Browser -
 - Version -

**Comment by adamplenti** [comment]
I fixed build by change Swift Version from `4` to `5` in:

```
Pods > stripe-react-native > Build Settings > Swift Compiler - Language > Swift Language Version > Swift 5
```

**Comment by charliecruzan-stripe** [comment]
You might need to change something on CI as well, but this isn't a bug in the SDK, it's just due to an older swift version so I'm going to close this issue
