### ISSUE TITLE
How to enable Paynow payment method in reactnative

### ISSUE THREAD

**Issue by AliSohail683** [stripe/stripe-react-native#1490]
I want to enable the paynow payment in stripe. I am using stripe payment sheet in react native. Kindly pls help me! Thanks

**Comment by charliecruzan-stripe** [comment]
Hi! This isn't supported now, but it's on our radar: https://github.com/stripe/stripe-ios/issues/1996

**Comment by AliSohail683** [comment]
Is there any way we can enable it from backend(Node.Js)?
