### ISSUE TITLE
Correct subscription flow

### ISSUE THREAD

**Issue by GregoryWullimann** [stripe/stripe-react-native#1493]
I'm trying to setup a subscription for my app. I've been following this example https://github.com/charliecruzan-stripe/react-native-video-series/ with the [PaymentSheetSubscription.tsx](https://github.com/charliecruzan-stripe/react-native-video-series/blob/main/PaymentSheetSubscription.tsx) file.

What's happening now is that the subscription is started as soon as the page is open, since `await stripe.subscriptions.create()` is called.

What I want is to:
1. Collect payment info
2. Start the subscription starting with the free trial

What should be the correct flow to follow? It isn't clear at all from any documentation

**Comment by charliecruzan-stripe** [comment]
I think you might be looking for setup intents- https://stripe.com/docs/payments/setup-intents
