### ISSUE TITLE
Google Pay OR_BIBED_11 (Live mode)

### ISSUE THREAD

**Issue by VTSingle** [stripe/stripe-react-native#1494]
**Describe the bug**
I did integration with Google Pay via the library. Everything works fine in test mode (testEnv: true)
But when I changed the parameter to false (testEnv: false) - I'm getting the next error:

`This merchant is having trouble accepting your payment right now. Try using a different payment method[OR_BIBED_11]`

Also I registered Business Profile, received status Approved and added "Integrate with your website" and received Approved status too. But I'm still getting the same error when I'm trying to init Google Pay method in live mode. 

What I miss ??? 
Mb I need to add "Integrate with your Android app" integration. But I'm not sure. 

Could you share your exp., please?

**To Reproduce**
Follow the instruction - https://stripe.com/docs/google-pay?platform=react-native

**Comment by charliecruzan-stripe** [comment]
This is an issue with Google Pay, not with Stripe- see https://github.com/stripe/stripe-react-native/issues/1459

**Comment by AkshayKrJha** [comment]
@VTSingle was your problem solved ?

**Comment by VTSingle** [comment]
@AkshayKrJha yes. Google Pay started work automatically on PROD env when I got approve from the google team. 
https://pay.google.com/business/console

**Comment by VTSingle** [comment]
For google play you need only publishableKey (live)

On your screen you need to set `testEnv: false`

```
googlePay: {
        testEnv: false,
        merchantName: 'YOUR APP NAME',
        merchantCountryCode: 'US',
        currencyCode: 'USD',
        billingAddressConfig: {
          format: PlatformPay.BillingAddressFormat.Full,
          isPhoneNumberRequired: true,
          isRequired: true,
        },
      },
```

**Comment by AkshayKrJha** [comment]
Did you test PROD payment on app's playstore version, its β release, or its signed release APK ?

**Comment by AkshayKrJha** [comment]
Started working fine, after approval from from Google Pay API Team,
with no requirement for merchant info in code.

**Comment by maroom1** [comment]
seems like this issue still persists, 
Do I need to go to pay.google.com again to get approval. this is non-sense, i came to stripe just to avoid all this kind of non-sense. Kindly help is there any alternate way

**Comment by toluo-stripe** [comment]
@maroom1 Please take a look at [this doc](https://docs.stripe.com/google-pay?platform=react-native#going-live-react-native). I hope it helps

**Comment by crmpicco** [comment]
@AkshayKrJha @toluo-stripe Is there a secondary approval process or is there a delay that i'm not aware about?

When I log in to the Google Pay & Wallet Console I see my Business Profile as "Approved":
<img width="768" height="271" alt="Image" src="https://github.com/user-attachments/assets/4d8d4539-38f3-4f24-8fdf-c46d1ee32b5a" />

Yet, when I click the "Pay with Google Pay" button I get the following error:

> Something went wrong
> This merchant is having trouble accepting your payment right now. Try using a different payment method. [OR_BIBED_11] OR_BIBED_11

**Comment by MuddassarElexoft** [comment]
> [@AkshayKrJha](https://github.com/AkshayKrJha) [@toluo-stripe](https://github.com/toluo-stripe) Is there a secondary approval process or is there a delay that i'm not aware about?
> 
> When I log in to the Google Pay & Wallet Console I see my Business Profile as "Approved": [<img alt="Image" width="768" height="271" src="https://private-user-images.githubusercontent.com/2536923/627547035-4d8d4539-38f3-4f24-8fdf-c46d1ee32b5a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgzMzE5NDQsIm5iZiI6MTc4ODMzMTY0NCwicGF0aCI6Ii8yNTM2OTIzLzYyNzU0NzAzNS00ZDhkNDUzOS0zOGYzLTRmMjQtOGZkZi1jNDZkMWVlMzJiNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA5MDJUMDY0NzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTA0ZmUyM2I4MWJlMDExNWZjMWJkZTk4MWZlNzMxZjY5MzU3NGQzMTUwY2MzMzFhMjMzYTZjOWE4NTRhZmQ0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.PFHooHMpvyoHvvKsq5d5CI_QM7g1AfxQT6mH4hKPdgM">](https://private-user-images.githubusercontent.com/2536923/627547035-4d8d4539-38f3-4f24-8fdf-c46d1ee32b5a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgzMjc4NTEsIm5iZiI6MTc4ODMyNzU1MSwicGF0aCI6Ii8yNTM2OTIzLzYyNzU0NzAzNS00ZDhkNDUzOS0zOGYzLTRmMjQtOGZkZi1jNDZkMWVlMzJiNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA5MDJUMDUzOTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBiOWM5MzJkMjg3ZTBiNTYzM2RiY2VlMDU0YzI0ZmU2N2UyZDA5ZTZlMDdiYWU1NWQyNzhhMjZhOTMzZmM0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.Vk-Zo3YIUkykIiqAlBU3B8zsMDn8PLoMjjCfAOyMUVA)
> 
> Yet, when I click the "Pay with Google Pay" button I get the following error:
> 
> > Something went wrong
> > This merchant is having trouble accepting your payment right now. Try using a different payment method. [OR_BIBED_11] OR_BIBED_11

Yes you need to apply for your app domain approval from GOOGLE PAY API which required additional screen shots of google pay flow.

**Comment by crmpicco** [comment]
Thanks @MuddassarElexoft , I could see there was a second stage to create a "Web Integration" and have that approved
