### ISSUE TITLE
Payment options are not shown in PaymentSheet on iOS

### ISSUE THREAD

**Issue by abanoubamin** [stripe/stripe-react-native#1495]
**Describe the bug**
I'm using `@stripe/stripe-react-native` (v0.28.0)
Payment options are shown in PaymentSheet on Android devices and not shown on the iOS devices

**Screenshots**
| Android  | iOS |
| ------------- | ------------- |
|![267406794-6fffedf6-84f9-4645-b171-6ad3b8b343b7](https://github.com/stripe/stripe-react-native/assets/40027608/f3f6bc5b-c66f-4282-8c32-4af806bc81bb)|![267406583-97f58da2-5a43-49a7-9063-af3099160d95](https://github.com/stripe/stripe-react-native/assets/40027608/bc4976ad-3c48-437f-9d89-75232f12a2e3)|

**Comment by charliecruzan-stripe** [comment]
Hi! Not able to reproduce this myself so please provide more information on how to reproduce

**Comment by abanoubamin** [comment]
Hi :wave: 

Actually I've implemented it exactly like the [doc](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet) 

and these are some snippets from my code, hope that could help

```
const ephemeralKey = await stripe.ephemeralKeys.create(
        { customer: customer.id },
        { apiVersion: '2022-11-15' }
    );
```

```
const paymentIntent = await stripe.paymentIntents.create({
        amount: 15.90,
        currency: 'eur',
        customer: customer.id,
        automatic_payment_methods: {
            enabled: true,
        },
    });
```

```
const { error } = await initPaymentSheet({
          merchantDisplayName: '',
          customerId: customer,
          customerEphemeralKeySecret: ephemeralKey,
          paymentIntentClientSecret: paymentIntent,
          allowsDelayedPaymentMethods: false,
        });
```

As mentioned before it works fine on Android without any problems but on the iOS simulators and real devices the other payment methods that I have (Giropay and PayPal) are not existed in the payment sheet.

**Comment by charliecruzan-stripe** [comment]
I see- could you try this on the most recent version? 0.31.1

**Comment by abanoubamin** [comment]
@charliecruzan-stripe Thanks mate

I got the reason behind this issue

`returnURL` was not set

```
await initPaymentSheet({
  ...
  returnURL: 'your-app://stripe-redirect',
  ...
});
```

![Screenshot 2023-09-13 at 10 44 49 PM](https://github.com/stripe/stripe-react-native/assets/40027608/4f949bab-ca5b-4c8c-8ba7-719a628fe959)
