### ISSUE TITLE
Hide the save card checkbox

### ISSUE THREAD

**Issue by abanoubamin** [stripe/stripe-react-native#1496]
**Describe the bug**
I didn't find any way to hide the save card checkbox and the documentation was not updated regarding this point.

**Screenshots**
![Screenshot 2023-09-12 at 8 10 58 PM](https://github.com/stripe/stripe-react-native/assets/40027608/34519ed3-5a8e-4512-9a78-287f25b8fe73)

**Comment by charliecruzan-stripe** [comment]
You can use the payment intent's `setup_future_usage` for this. This property tells us to save the payment method for future use, and when set, PaymentSheet hides the 'Save this card for future use' checkbox and always saves it

It will also only show when you pass a `customerEphemeralKeySecret`

**Comment by abanoubamin** [comment]
@charliecruzan-stripe 

Is there any way to hide the checkbox from the payment sheet without implementing `setup_future_usage` logic?
