### ISSUE TITLE
PaymentMethod null in paymentIntent from confirmPlatformPayPayment()

### ISSUE THREAD

**Issue by ElliDy** [stripe/stripe-react-native#1499]
**Description of the issue**
When I create a paymentIntent with confirmPlatformPayPayment, the paymentIntent.paymentMethod is null.

**To Reproduce**

``` 
const items: CartSummaryItem[] = [
      {
        label:
          this.props.screenProps.translate('payItemLabel') +
          this.state.chargingPoint.evseId,
        amount: amount,
        paymentType: PlatformPay.PaymentType.Immediate,
      },
    ];
if (isPlatformPaySupported()) {
      const {paymentIntent, error} = await confirmPlatformPayPayment(
        clientSecret,
        {
          applePay: {
            cartItems: items,
            merchantCountryCode: 'DE',
            currencyCode: 'EUR',
          },
        },
      );
}
```

**Expected behavior**
As the paymentMethodId is not null, I would expect, that there is also a paymentMethod.

**Smartphone:**
 - Device: Simulator iPhone 14 Plus
 - OS: iOS 16.4

**Additional context**
"@stripe/stripe-react-native": "0.28.0",
"react-native": "0.69.0",

**Comment by charliecruzan-stripe** [comment]
Hi! Could you use `retrievePaymentIntent` to get the payment intent?

**Comment by ElliDy** [comment]
Same result. I do not get the paymentMethod.

**Comment by charliecruzan-stripe** [comment]
Fix will be released tomorrow!
