### ISSUE TITLE
Adapt react-connect-js for react native

### ISSUE THREAD

**Issue by sebastienlabine** [stripe/stripe-react-native#1533]
I would like to have a connect components be able to configure connected accounts with Stripe React native

**Comment by benomatis** [comment]
@sebastienlabine Would this guide help? https://stripe.com/docs/connect/collect-then-transfer-guide?platform=react-native&ui=payment-sheet

**Comment by sebastienlabine** [comment]
@benomatis Thanks for the guide. The problem isn't with how to do it, but rather the fact that there's no components for react native to handle.


On Web , we can use react-connect-js to embed the connect form directly in our react app. However, on react-native no such option is avalailable. We need to use a webview with a universal link to be able to handle stripe "back button" on the webview.

It would be much easier and appreciated to have a connect form component

**Comment by benomatis** [comment]
@sebastienlabine sorry, can't help you further, I unfortunately don't have it implemented in RN.

**Comment by seanzhang-stripe** [comment]
Hi @sebastienlabine [Connect embedded components](https://stripe.com/docs/connect/connect-embedded-components/quickstart) are only available in web, not mobile.  You can consider embedding a WebView in your mobile app to render a webpage with Connect embedded components.

**Comment by sebastienlabine** [comment]
> Hi @sebastienlabine [Connect embedded components](https://stripe.com/docs/connect/connect-embedded-components/quickstart) are only available in web, not mobile.  You can consider embedding a WebView in your mobile app to render a webpage with Connect embedded components.

I assume there no plan to support it natively? A Webview is kind of bad because of the deeplinks.

**Comment by simonadenic** [comment]
Hello, @seanzhang-stripe, is there any plans on supporting embedded components through react-native, or no?
