### ISSUE TITLE
Release for new Google Pay button UI?

### ISSUE THREAD

**Issue by gregavola** [stripe/stripe-react-native#1539]
I see the following PR was merged (https://github.com/stripe/stripe-react-native/pull/1534) that implemented the new Google Pay Button UI - any idea when it will be released? Google Pay is blocking my submission because it's using the old design, and I can't move forward. Thanks!

**Comment by charliecruzan-stripe** [comment]
Will be released this friday!

**Comment by charliecruzan-stripe** [comment]
@gregavola If you need it right now you can install NPM packages direct from github branches, but your mileage may vary so it might be easier to wait until Friday

**Comment by charliecruzan-stripe** [comment]
sorry @gregavola - we're waiting on a fix in the Stripe iOS library before releasing. Should go out monday or tuesday!

**Comment by gregavola** [comment]
@charliecruzan-stripe Any update on this?

**Comment by charliecruzan-stripe** [comment]
Deployed in v0.34.0!
