### ISSUE TITLE
Stripe API returns "Payment Cancelled" after confirmPlatformPayPayment (Apple Pay)

### ISSUE THREAD

**Issue by gregavola** [stripe/stripe-react-native#1540]
**Describe the bug**
After getting the `clientSecret` from the backend via Payment Intents, the `confirmPlatformPayPayment` returns the following message - this only happens in LIVE mode, and is fine is TEST mode. The Apple Pay sheet doesn't even popup, it just immediately goes to error.

![79449](https://github.com/stripe/stripe-react-native/assets/648949/4ff208bc-d03b-4553-bade-2d3f277a99e4)

**To Reproduce**

1. Add the endpoint to get the intent:

```
    const stripe = new Stripe(
      process.env.STRIPE_SECRET_KEY!,
    {
      typescript: true,
      apiVersion: "2023-08-16",
    }
  );

  const { amount, description } = body;

 const paymentIntent = await stripe.paymentIntents.create({
      amount: Number(amount) * 100,
      description,
      currency: "usd",
    });

return paymentIntent.client_secret;
```

2.  Create the function to initiate the Apple Pay call:

```
const applePay = async () => {
    try {
      setIsSending(true);

      // call HTTP endpoint created above
      const data = await stripePaymentIntent({
        amount: total,
        description: `Entry Fee for ${tournament.name}`,
        eventId: tournamentEvent.id,
      });

      if (!data) {
        showMessage({
          type: 'danger',
          message:
            'Something went wrong. You were not charged. Please try again.',
        });
      } else {
        const secretKey = data.key;

        const {error, paymentIntent} = await confirmPlatformPayPayment(
          secretKey,
          {
            applePay: {
              cartItems: [
                {
                  label: `Entry fee from ${tournamentEvent.name} at ${tournament.name}`,
                  amount: total.toString(),
                  paymentType: PlatformPay.PaymentType.Immediate,
                },
              ],
              merchantCountryCode: 'US',
              currencyCode: 'USD',
            },
          },
        );

        if (error) {
          showMessage({
            type: 'danger',
            message: `Something went wrong. You were not charged. ${
              error.localizedMessage
            } ${JSON.stringify(error)}`,
          });
        } else {
         console.log('payment success');
      }
    } catch (err) {
      showMessage({
        type: 'danger',
        message: handleException(err),
      });
    } finally {
      setIsSending(false);
    }
  };
```

4.  Create the button:

```
<PlatformPayButton
                          onPress={applePay}
                          style={{
                            width: '100%',
                            height: 45,
                          }}
                          appearance={
                            scheme === 'dark'
                              ? PlatformPay.ButtonStyle.White
                              : PlatformPay.ButtonStyle.Black
                          }
                          borderRadius={4}
                          disabled={!isApplePaySupported}
                        />
```

5. See error above

**Expected behavior**
The payment should go through successfully without error.

**Screenshots**
See above for screenshots!

**Additional context**
In TEST mode, this has no issue - this only affects live mode. Tested on iOS 17.0.3 with Apple Pay enabled.

**Comment by seanzhang-stripe** [comment]
Hi @gregavola did you follow [these steps](https://stripe.com/docs/apple-pay?platform=react-native#accept) to register an Apple Merchant ID, create a certificate and set up your Xcode project properly? If you still encounter errors after completing these steps, share with me the PaymentIntent ID and I'd take a further look.

**Comment by gregavola** [comment]
Hey @seanzhang-stripe, I did! My merchant ID is `merchant.getvolleyapp.com`, which matches what is in the Stripe Dashbaord.

Here is the PaymentIntent ID: pi_3O4j9BAuHWG8Y8SB0rsKPanq

I just did this recently, so it should be fresh. In the dashboard is says that no payment type has been attached, but I assume that is normal, as it worked fine in Test Mode.

**Comment by gregavola** [comment]
Update: This turns out that I forgot to "check" the box in Xcode, after importing it. Now it works!

Sorry for the confusion!
 
<img width="450" alt="Screenshot 2023-10-24 at 12 56 25 PM" src="https://github.com/stripe/stripe-react-native/assets/648949/1629553f-80b2-45d8-96c3-8f9aade605d3">
