### ISSUE TITLE
The `onBlur` method on the `<CardField>` element isn't being triggered on iOS

### ISSUE THREAD

**Issue by amer-kocan-sowa** [stripe/stripe-react-native#1541]
**Describe the bug**
The `onBlur` method on the `<CardField>` element isn't being triggered on iOS (at least not in the simulator), even though the element clearly loses focus (as the typing cursor disappears and the keyboard is dismissed upon clicking outside of the element). On Android (emulator) it seems to work fine.

I've tested this on versions `0.27.2` `0.28.0`, and `0.29.0`, however, talking with one of the Stripe support staff on Discord (@karllekko), they confirmed they were able to reproduce this on the latest version `0.33.0` as well.

**To Reproduce**
This seems to be enough for the issue to occur (RN version `0.71.12`):
```js
<CardField
  postalCodeEnabled={false}
  onCardChange={(card: Details) => {
    console.log(card);
  }}
  style={{ height: "100%" }}
  onBlur={() => {
    console.log('blur');
  }}
  onFocus={() => {
    console.log('focus'); 
  }}
/>
```

**Expected behavior**
Upon clicking outside of the `CardField` element, the `onBlur` method should be triggered (it currently isn't). 

**Desktop (please complete the following information):**
M1 Macbook, Mac OS Sonoma

**Smartphone (please complete the following information):**
iPhone SE (3rd Generation) Rosetta simulator, iOS 17

**Additional context**
I haven't tested this on a real device but it should work in the simulator. I don't recall us having these issues before we upgraded our react native version from `0.68.something` to `0.71.12` and our stripe from `0.23.2` to `0.27.2`)

**Comment by charliecruzan-stripe** [comment]
fixed in https://github.com/stripe/stripe-ios/pull/3014, this will be included in the next release

**Comment by amer-kocan-sowa** [comment]
can confirm it works on my end as well 👍 thanks 🥳
