### ISSUE TITLE
attachPaymentMethod for CustomerAdapter / CustomerSheet never fired

### ISSUE THREAD

**Issue by pratikdhody** [stripe/stripe-react-native#1543]
**Describe the bug**
When using CustomerSheet with customer adapter, it doesn't look like the custom attachPaymentMethod is being fired.
detachPaymentMethod fires as expected (minus a secondary issue where I'm unable to reject the detachment on UI as we have logic where we want a minimum of one card on file.

My functions are as below defined inside StripeCustomerAdapter.ts and fetchPaymentMethods and detachPaymentMethod work via the customer adapter but looks like attachPaymentMethod is not.

```
async attachPaymentMethod(paymentMethodId: string) {
    console.log("--> CustomerAdapter: attachPaymentMethod");
    let paymentMethod = null;

    const result = api.postAttachPaymentMethod(
      this.token,
      this.customerId,
      paymentMethodId
    );
    result.then((data) => {
      if (data.kind !== "ok") {
        Alert.alert("Error. Payment method could not be attached.");
      } else {
        paymentMethod = data.result.paymentMethod;
      }
    });
    return paymentMethod;
  }

  async detachPaymentMethod(paymentMethodId: string) {
    console.log("--> CustomerAdapter: detachPaymentMethod");
    let paymentMethod = null;
    const result = api.postDetachPaymentMethod(
      this.token,
      this.customerId,
      paymentMethodId
    );

    result.then((data) => {
      if (data.kind !== "ok") {
        Alert.alert(
          "Error. A minimum of one payment method is required to be attached to your account."
        );
      } else {
        paymentMethod = data.result.paymentMethod;
      }
    });

    return paymentMethod;
  }
```

**To Reproduce**
1. Using CustomerSheet, use CustomerAdapter as per https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ExampleCustomerAdapter.ts
2. Attach card and notice that your custom logic does not get fired and there is no console log of `--> CustomerAdapter: attachPaymentMethod`

**Expected behavior**
attachPaymentMethod is expected to be used.

**Additional context**
```
"@stripe/stripe-react-native": "0.33.0",
"expo": "~47.0.14",
```

**Comment by charliecruzan-stripe** [comment]
Hi! Expo SDK 47 requires you use v0.19.0 - https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0190---2022-09-16--expo-sdk-47

**Comment by pratikdhody** [comment]
ah understood. thanks for the reply @charliecruzan-stripe
