### ISSUE TITLE
cant determine  macro tag android

### ISSUE THREAD

**Issue by bilalkhan-tech** [stripe/stripe-react-native#1549]
**Describe the bug**
Development is in working and i upgrade the react native version from  0.67.2 to 0.72.4 and later on the build is not created .

**To Reproduce**
1- upgrade form 0.67.2 to 0.72.4

**Expected behavior**
its not working only android to make build

**Additional context**
 Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

**Comment by charliecruzan-stripe** [comment]
Hi! There are lots of things that change in your project when upgrading from RN 67 to 72, unfortunately this isn't clearly an issue with Stripe so I would recommend debugging further to see if you can isolate the problem to be in Stripe React Native. If you can do that, I'm happy to look into it
