### ISSUE TITLE
Expo React Native iOS Payment Options not shown (only card shown)

### ISSUE THREAD

**Issue by faisalhotak** [stripe/stripe-react-native#1570]
Hello everyone!

I have implemented the stripe payment inside my mobile app. It works fine but payment cards options are only shown on Android and only "card" option is shown on iOS (they use the same stripe public key so they should show the same card options as the ones activated in my dashboard). The most important payment option being "bancontact" and I do not see it on iOS.

**To Reproduce**
1. Creating the payment intent
2. Showing the payment intent element to the user
3. All the options are available on Android
4. No card options available on iOS (except the "card")

Server side : 

```
const paymentIntent = await stripe.paymentIntents.create({
    amount,
    customer: customer.id,
    currency: "eur",
    automatic_payment_methods: {
        enabled: true,
    },
    metadata: { pendingPaymentId: pendingPayment.id },
  });
```

Client side : 

```
const initializePaymentSheet = async () => {
    const { payload } = await createPaymentIntent();

    console.log("payload", payload);

    const { clientSecret, ephemeralKey, customerId, publishableKey } = payload;

    const { error } = await initPaymentSheet({
      merchantDisplayName: "TEST APP",
      customerId: customerId,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: clientSecret,
      merchantCountryCode: "BE",
    });

    if (error) {
      console.log(error);
    }
  };

  const payTest = async () => {
    await initializePaymentSheet();
    // const response = await confirmPaymentSheetPayment();
    const { error } = await presentPaymentSheet();

    console.log("error", error);

    if (error) {
      Toast.show(error.message, {
        duration: Toast.durations.SHORT,
        position: Toast.positions.CENTER,
        animation: true,
        delay: 0,
      });

      return;
    }

    Toast.show("Paiement effectué", {
      duration: Toast.durations.SHORT,
      position: Toast.positions.CENTER,
      animation: true,
      delay: 0,
    });
  };
```

**Screenshots**

On Android  (showing all the options) : 
<img width="419" alt="Capture d’écran 2023-11-26 à 13 26 11" src="https://github.com/stripe/stripe-react-native/assets/55158944/e22908a2-ac5a-494f-a608-e2d7f82671fd">

On iOS (only showing "card" and not other options such as "bancontact" or others") :
<img width="446" alt="Capture d’écran 2023-11-26 à 13 25 15" src="https://github.com/stripe/stripe-react-native/assets/55158944/aad76fc0-6f0a-4a72-9d5f-f3a68654fd1f">

**Smartphone :**
 - Device: iPhone 15 Pro
 - OS: 17.0.1
- Expo React Native managed application
Using : 
```
"expo": "^49.0.9",
"@stripe/stripe-react-native": "0.28.0"
```

Thanks !

**Comment by oaxio** [comment]
Same issue here

**Comment by oaxio** [comment]
For anyone with this issue,

Add    
`returnURL: 'your-app://stripe-redirect',`
in your initPaymentSheet

**Comment by faisalhotak** [comment]
@oaxio Thank you very much!

Indeed, the return url is needed, make sure to replace 'your-app' by your app name.

Then the payment methods will be shown !

![Capture d’écran 2024-01-29 à 13 48 08](https://github.com/stripe/stripe-react-native/assets/55158944/ea8fcd4c-05bd-4f49-9c3b-02dc87afdea7)
