### ISSUE TITLE
Paymentsheet does not open on iOS when selecting klarna payment.

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#1572]
**Describe the bug**
Paymentsheet does not open on iOS when selecting klarna payment.

**To Reproduce**
1. Create payment intent for klarna
2. In paymentsheet add the paymentintent id that is created in the initpaymentsheet arguments
3. Execute `presentPaymentSheet`
4. Notice paymentsheet is not opening because of  error: `noPaymentMethodTypesAvailable`

The same steps work on android

**Expected behavior**
Paymentsheet opens with klarna

**Comment by seanzhang-stripe** [comment]
Hi @remonh87 Can you share with me the PaymentIntent ID? Also please make sure that you are using SDK version [0.4.0](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#040---2022-03-10) and above.

**Comment by seanzhang-stripe** [comment]
Hi @remonh87 a PaymentIntent ID starts with `pi_`, the ID that you shared belongs to a PaymentMethod. 

Based on [log](https://dashboard.stripe.com/test/logs/req_Y60T1Id0k0q99q), this PaymentMethod was created when you confirm a Klarna payment from your Android application built with Flutter. So I don't think this is the correct ID that we should use to investigate the iOS problem that you described.

**Comment by remonh87** [comment]
@seanzhang-stripe  my apologies I had so many klarna test intents that it was hard to find the right one. This is the correct one: `pi_3OJhk3B3gMa6tyoM1ewK3Bl3 `

**Comment by seanzhang-stripe** [comment]
Hi @remonh87 I couldn't reproduce the problem. Can you share with me a trimmed down version of your react-native project that I run and replicate the issue?

**Comment by remonh87** [comment]
@seanzhang-stripe  I found the issue the returnurl was not set. I could find the cause because the ios sdk was logging a warning somewhere very deep in the sdk (only could get it through xcode).  Would be great if this error was thrown to the cross platform layer so the users could fix it easier.

**Comment by charliecruzan-stripe** [comment]
Interesting, we do warn as of v0.31.1- https://github.com/stripe/stripe-react-native/blob/master/src/functions.ts#L399

**Comment by remonh87** [comment]
yes in the ios logs I see this but for some reason they do not bubble up in flutter not your problem so close it.
