### ISSUE TITLE
Apple pay supported on Android?

### ISSUE THREAD

**Issue by Rc85** [stripe/stripe-react-native#1574]
```
useEffect(() => {
  (async () => {
      const applePaySupported = await isPlatformPaySupported();

      console.log(applePaySupported); // true

      setIsApplePaySupported(applePaySupported);

      const googlePaySupported = await isPlatformPaySupported({ googlePay: { testEnv: __DEV__ } });

      setIsGooglePaySupported(googlePaySupported);
    })();
}, []);
```
Is anyone else experiencing this? This is on a Samsung Galaxy 23 Ultra.

**Comment by pratikdhody** [comment]
> ```
> useEffect(() => {
>   (async () => {
>       const applePaySupported = await isPlatformPaySupported();
> 
>       console.log(applePaySupported); // true
> 
>       setIsApplePaySupported(applePaySupported);
> 
>       const googlePaySupported = await isPlatformPaySupported({ googlePay: { testEnv: __DEV__ } });
> 
>       setIsGooglePaySupported(googlePaySupported);
>     })();
> }, []);
> ```
> 
> Is anyone else experiencing this? This is on a Samsung Galaxy 23 Ultra.

what is your actual questions @Rc85?

**Comment by Rc85** [comment]
> > ```
> > useEffect(() => {
> >   (async () => {
> >       const applePaySupported = await isPlatformPaySupported();
> > 
> >       console.log(applePaySupported); // true
> > 
> >       setIsApplePaySupported(applePaySupported);
> > 
> >       const googlePaySupported = await isPlatformPaySupported({ googlePay: { testEnv: __DEV__ } });
> > 
> >       setIsGooglePaySupported(googlePaySupported);
> >     })();
> > }, []);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is anyone else experiencing this? This is on a Samsung Galaxy 23 Ultra.
> 
> what is your actual questions @Rc85?

Why is Apple Pay supported on an Android device?

**Comment by charliecruzan-stripe** [comment]
^ that is true

`isPlatformPaySupported` is for both apple pay and google pay, depending on what platform it is run on

**Comment by Rc85** [comment]
> ^ that is true
> 
> `isPlatformPaySupported` is for both apple pay and google pay, depending on what platform it is run on

So why is `isPlatformPaySupported()` and `isPlatformPaySupported({ googlePay: { env: __DEV__ } })` returning true on my Android device?
