### ISSUE TITLE
Expo SDK 49 Compatibility

### ISSUE THREAD

**Issue by mattmcardle** [stripe/stripe-react-native#1575]
I have developed an app which uses this library in Expo SDK 49. I note in the documentation under "Expo" it says:

> Each Expo SDK version requires a specific stripe-react-native version. See the [CHANGELOG](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md) for a mapping of versions. To install the correct version for your Expo SDK version run:

> `expo install @stripe/stripe-react-native`

I do not see a changelog entry with a version corresponding to Expo SDK 49. I ran the expo install command above and it installed version 0.28.0. Is the absence of a mention of Expo SDK 49 in the changelog an implication that this library is not yet compatible with version 49?

**Comment by vtech18** [comment]
i am using expo sdk 49 and stripe version of 0.28.0 . I am using test account and entered card n of 4242 4242 4242 4242 (success payment for visa) and it redirected to visa web page and came back. Intially it shows processing and then it is showing amount again .It is not showing the success message or it is not showing any error also.Why  @charliecruzan-stripe
