### ISSUE TITLE
`Task :stripe_stripe-react-native:compileDebugKotlin FAILED `  *** unable to run the app 

### ISSUE THREAD

**Issue by rameesp** [stripe/stripe-react-native#1583]
**Error**

**`Task :stripe_stripe-react-native:compileDebugKotlin FAILED ` **

After installing string : "@stripe/stripe-react-native": "^0.35.0" , i am unable to run the app in android emulator due to the build e error I have mentioned above .

**Versions**

"react": "18.2.0",
"react-native": "0.73.1",
"@stripe/stripe-react-native": "^0.35.0"
 buildToolsVersion = "34.0.0"
 minSdkVersion = 21
 compileSdkVersion = 34
 targetSdkVersion = 34
 ndkVersion = "25.1.8937393"
 kotlinVersion = "1.8.0"

**buidl.gradle**

`buildscript {
    ext {
      buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        kotlinVersion = "1.8.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}
apply plugin: "com.facebook.react.rootproject"`

**Device**

Emulator
Android version 14

**other **

node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/CardFormView.kt:31:70 Unresolved reference: style

> Task :stripe_stripe-react-native:compileDebugKotlin FAILED

**Comment by MrJ0bs** [comment]
Open Android Studio.
Go to  reactnativestripesdk > CardFormView.kt
`
class CardFormView(context: ThemedReactContext) : FrameLayout(context) {
  // Change this line of code
  private var cardForm: CardFormView = CardFormView(context, null, R.style.StripeCardFormView_Borderless) 
  ....
  }`
   // After writing com.stripe.android
  ` private var cardForm: CardFormView = CardFormView(context, null, com.stripe.android.R.style.StripeCardFormView_Borderless)
   `
   Rebuild it again
   This is not a good fix but it is what i did to run the app debug
   
   After Installing new node modules it automatically reverts to its previous error.
   
   I have been facing this since last week.

**Comment by allynsweet** [comment]
Looks like the fix was merged into `master` in #1579, but we're waiting for the team to release it.

**Comment by lernerb** [comment]
Any ETA on when #1579 is going to be released via `master`? Would like to not have to patch this one library temporarily to get our .73.X compat release out the door and instead rely on released versions.

**Comment by ArtanAhmeti** [comment]
I'm using RN 0.73.X and had the same issue, after making changes below it worked: 
in `com/reactnativestripesdk/CardFormView.kt` I replaced 

`private var cardForm: CardFormView = CardFormView(context, null, R.style.StripeCardFormView_Borderless)`
 with 
`private var cardForm: CardFormView = CardFormView(context, null, com.stripe.android.R.style.StripeCardFormView_Borderless)`

**Comment by charliecruzan-stripe** [comment]
Will be releasing the fix for this tomorrow!

**Comment by AnshIcode** [comment]
@ArtanAhmeti where i find this com/reactnativestripesdk/CardFormView.kt i have react native app....

**Comment by AnshIcode** [comment]
@lernerb @allynsweet @rameesp @MrJ0bs @charliecruzan-stripe hi :) I am unable to make the build on android and i am having same issue you can check my issue #1585  please tell me how to correct it and make a build

**Comment by rameesp** [comment]
Have you made changes on that mentioned 

Please note the solution that mentioned is temporary. Installing  or reinstalling or any changes to node modules will undo the changes  u will be making , so after any changes to the node modules you have to redo the solution🙂
@AnshIcode

**Comment by AnshIcode** [comment]
@rameesp Thanks for the information yes its working now!

**Comment by rameesp** [comment]
> @rameesp Thanks for the information yes its working now!
> 
> 

Please update the stripe version they have fixed the issue

**Comment by daniloeder** [comment]
I've solved this problem after removing this line from package.json dependencies:
"expo-application": "~5.9.1".

**Comment by saeedahmed2023** [comment]
Same issue
 "@stripe/stripe-react-native": "0.44.0",
 "react-native": "0.74.0",

**Comment by Rise-admin1** [comment]
Managed to find a fix?

> Same issue "@stripe/stripe-react-native": "0.44.0", "react-native": "0.74.0",
