### ISSUE TITLE
Card Field on android not opening app crashed

### ISSUE THREAD

**Issue by AnshIcode** [stripe/stripe-react-native#1587]
@cpytel @zubko @jlongster @sguha00 hy i am using react native and on android card field is not opening , app is crashed ,
react native is 0.73.0 and stripe is 0.35.0
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by angelo-hub** [comment]
also seeing this

**Comment by AnshIcode** [comment]
@angelo-hub its done , i am using the cardField inside modal so if you are doing the same then remove it.
