### ISSUE TITLE
Apple Pay works in Simulator but can't work in real device

### ISSUE THREAD

**Issue by SnowingFox** [stripe/stripe-react-native#1591]
**Describe the bug**
I'm using expo-dev-client to build my app, apple pay button can be used in simulator but not on real device

**To Reproduce**

**Expected behavior**
Apple pay can be used in real device

**Screenshots**
### Simulator
![image](https://github.com/stripe/stripe-react-native/assets/26035718/96990e6f-4e89-4b70-8215-8d206568aefe)
### Real Device (TestFlight)
![image](https://github.com/stripe/stripe-react-native/assets/26035718/2380aa20-9f48-45eb-bb71-a37fad609329)

**Smartphone (please complete the following information):**
 - Device: iPhone12 pro max
 - OS: >= IOS13

**Additional context**
```ts
import { isPlatformPaySupported } from "@stripe/stripe-react-native";
```
isPlatformPaySupported always return false in real device

**Comment by seanzhang-stripe** [comment]
Hi @SnowingFox Have you completed these [steps](https://stripe.com/docs/apple-pay?platform=react-native#accept) to add Apple Pay support to your application?

**Comment by SnowingFox** [comment]
> Hi @SnowingFox Have you completed these [steps](https://stripe.com/docs/apple-pay?platform=react-native#accept) to add Apple Pay support to your application?

Fixed, because i'm in China so i can't use ApplePay in App
