### ISSUE TITLE
FlowController must be successfully initialized using configureWithPaymentIntent(), configureWithSetupIntent() or configureWithIntentConfiguration() before calling presentPaymentOptions() on Android

### ISSUE THREAD

**Issue by lacroiz01** [stripe/stripe-react-native#1599]
**Describe the bug**
I am getting this error on Android right before the element appears, it works fine on iOS: **FlowController must be successfully initialized using configureWithPaymentIntent(), configureWithSetupIntent() or configureWithIntentConfiguration() before calling presentPaymentOptions()** on Android

React Native: 0.66.5
stripe-react-native: 0.33.0
gradle version: 7.5
gradle plugin version: 7.4.2

The APK file was working fine before and one day it showed this error as well

**Screenshots**
![Screenshot_1706311128](https://github.com/stripe/stripe-react-native/assets/157854411/480430cd-d325-43f7-af79-a4c4777ca21f)

**Comment by osbornZ** [comment]
Is this problem solved?   update version?

**Comment by osbornZ** [comment]
> this was solved. Not sure what caused the issue, just re-install node_modules and sync gradle again.

thx replay，when I  update version to 0.37.3, this was sovled. Maybe because re-install node_modules
