### ISSUE TITLE
Android reflection: Setting tintColorInt no longer works

### ISSUE THREAD

**Issue by jonasbark** [stripe/stripe-react-native#1602]
https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/CardFieldView.kt#L170

This no longer works as tintColorInt is no longer available as field. I think instead one could call the "setTintColorInt" method.

```
java.lang.NoSuchFieldException: No field tintColorInt in class Lcom/stripe/android/view/CardBrandView; (declaration of 'com.stripe.android.view.CardBrandView' appears in /data/app/~~IDz1bgqcI5oqOHV1InrTog==/com.flutter.stripe.example-2hbbaERPHEzQHNeegEKm7Q==/base.apk!classes18.dex)
```

**Comment by charliecruzan-stripe** [comment]
will be fixed by https://github.com/stripe/stripe-react-native/pull/1598 

see https://github.com/stripe/stripe-react-native/pull/1598/commits/eaf49be0077a8a4f38a289d14f07ccb05d4c36b2
