### ISSUE TITLE
Expo SDK 50 changelog

### ISSUE THREAD

**Issue by ArmanPopatKite** [stripe/stripe-react-native#1613]
Hi,
Unsure if this has just not been updated in the change log yet. I wanted to confirm the version that works with expo SDK 50?

Thanks,
Arman

**Comment by charliecruzan-stripe** [comment]
Yes it does! I'll update the changelog now

**Comment by charliecruzan-stripe** [comment]
https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0351---2024-01-16--expo-sdk-50
