### ISSUE TITLE
Undefine symbols error when building in xcode

### ISSUE THREAD

**Issue by RossElder1983** [stripe/stripe-react-native#1615]
**Describe the bug**
Upon adding the stripe-react-native library to my project the build now fails. When i try to run the build from either my xcode workspace project or from terminal in VS code using 'npm run ios'.

If i remove the library my build works and the app will run on my iPhone simulator.

Im not even using the provider or any stripe code in the actual project, its as simple as adding the library and attempting to build.

**package.json**
"version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
  },
  "dependencies": {
    "@babel/preset-react": "^7.23.3",
    "@expo/vector-icons": "^12.0.4",
    "@microsoft/signalr": "^7.0.14",
    "@react-native-async-storage/async-storage": "^1.22.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-community/slider": "^3.0.3",
    "@react-native/metro-config": "^0.73.2",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@stripe/stripe-react-native":"0.37.0",
    "axios": "^0.21.1",
    "buffer": "^6.0.3",
    "faker": "^5.5.2",
    "import": "0.0.6",
    "moment": "^2.29.1",
    "openai": "^4.20.1",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-biometrics": "^3.0.1",
    "react-native-camera": "^3.42.3",
    "react-native-date-picker": "^3.2.10",
    "react-native-elements": "^3.4.1",
    "react-native-email-link": "^1.11.3",
    "react-native-form-validator": "^0.5.1",
    "react-native-gesture-handler": "^2.15.0",
    "react-native-get-location": "^2.2.1",
    "react-native-get-random-values": "^1.10.0",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-image-picker": "^3.2.1",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-location": "^2.5.0",
    "react-native-maps": "^0.27.1",
    "react-native-permissions": "^2.2.2",
    "react-native-qrcode-scanner": "^1.5.3",
    "react-native-qrcode-svg": "^6.3.0",
    "react-native-reanimated": "^3.7.1",
    "react-native-safe-area-context": "^4.8.1",
    "react-native-screens": "^3.29.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^14.1.0",
    "react-native-toast-message": "^2.1.1",
    "react-native-ui-lib": "^7.16.0",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "^8.0.0",
    "react-redux": "^7.2.2",
    "react-signalr": "^0.2.18",
    "react-test-renderer": "^18.2.0",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "socket.io-client": "^4.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.23.9",
    "@babel/runtime": "^7.23.9",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0"
  },
  "jest": {
    "preset": "react-native"
  }

**To Reproduce**
1. Add @stripe/stripe-react-native library to the project
2. Run the build from VS code or from Xcode
3. See error

**Expected behavior**
Id expect the application build successfully so i can carry on with the integration of Stripe into my phone app

**Screenshots**
Output from VS code build
![image](https://github.com/stripe/stripe-react-native/assets/16799124/361408c3-3e4a-4ad9-a703-c5d6249c905e)

Output from Xcode build (sometimes clicking the error takes me to the file in question where it just states 'undefined symbols'
![image](https://github.com/stripe/stripe-react-native/assets/16799124/e408f238-d8f0-4d09-b8b9-3b3511072a1c)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
 - Browser: Chrome
 - Version: 121.0.6167.184 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17
 - Browser: safari
 - Version latest

**Additional context**

**Comment by charliecruzan-stripe** [comment]
Hi! We link to this error in the README: https://github.com/stripe/stripe-react-native?tab=readme-ov-file#undefined-symbols-for-architecture-x86_64-on-ios
