### ISSUE TITLE
React stripe native 0.37.0 build failure for Android (with Expo SDK 49)

### ISSUE THREAD

**Issue by victorosorioparis** [stripe/stripe-react-native#1620]
**Describe the bug**
React Stripe Native 0.37.0 cannot be built anymore for Android with Expo SDK 49 (React native 0.72). This is a very similar issue to one seen and solved in flutter_stripe this week [here](https://github.com/flutter-stripe/flutter_stripe/issues/1676)

**To Reproduce**
1. Install @stripe/stripe-react-native on an expo project ("@stripe/stripe-react-native": "^0.37.0", "expo": "~49.0.10")
2. Try to build it with eas for android (eas build --platform android)
3. Gradle build will fail with following errors

`Execution failed for task ':app:bundleReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
   > Android resource linking failed
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:3: AAPT: error: resource android:color/system_background_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:4: AAPT: error: resource android:color/system_error_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:5: AAPT: error: resource android:color/system_error_container_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:6: AAPT: error: resource android:color/system_on_surface_light not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:7: AAPT: error: resource android:color/system_primary_light not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:8: AAPT: error: resource android:color/system_surface_light not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:9: AAPT: error: resource android:color/system_on_background_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:10: AAPT: error: resource android:color/system_on_error_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:11: AAPT: error: resource android:color/system_on_error_container_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:12: AAPT: error: resource android:color/system_on_primary_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:13: AAPT: error: resource android:color/system_on_primary_container_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:14: AAPT: error: resource android:color/system_on_secondary_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:15: AAPT: error: resource android:color/system_on_secondary_container_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:16: AAPT: error: resource android:color/system_on_surface_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:17: AAPT: error: resource android:color/system_on_surface_variant_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:18: AAPT: error: resource android:color/system_on_tertiary_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:19: AAPT: error: resource android:color/system_on_tertiary_container_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:20: AAPT: error: resource android:color/system_outline_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:21: AAPT: error: resource android:color/system_outline_variant_dark not found.
         
     ERROR:/home/expo/workingdir/build/x/x/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values-v34/values-v34.xml:22: AAPT: error: resource android:color/system_primary_dark not found.`

**Expected behavior**
It should build.

**Screenshots**
I would look on how flutter_stripe solved this [here](https://github.com/flutter-stripe/flutter_stripe/issues/1676)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This issue does not present with 0.36 version... I tried forcing the compileSdkVersion to 34 in my app.json but that was creating other issues

**Comment by victorosorioparis** [comment]
Now I am getting this... Building for Android with stripe react native is becoming really frustrating

```
Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:buildReleasePreBundle'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.stripe:stripe-android:20.36.+.
     Required by:
         project :app > project :stripe_stripe-react-native
      > Failed to list versions for com.stripe:stripe-android.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/stripe/stripe-android/maven-metadata.xml.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/stripe/stripe-android/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Comment by steavenb** [comment]
Facing same issue here. No expo but issue observed.

**Comment by charliecruzan-stripe** [comment]
Expo SDK 49 requires you to use a lower version of stripe-react-native: https://github.com/stripe/stripe-react-native/blob/v0.35.1/CHANGELOG.md#0280---2023-06-16--expo-sdk-49

If you're running into this issue, I would check that you have the correct `compileSdkVersion` (34 for v0.37.0)
