### ISSUE TITLE
will this ever work for expo WEB apps?

### ISSUE THREAD

**Issue by naticio** [stripe/stripe-react-native#1623]
**Is your feature request related to a problem? Please describe.**
stripe react native for EXPO RN WEB APPS

**Describe the solution you'd like**
make it for for EXPO RN WEB APPS

**Describe alternatives you've considered**
payment link->webhook 

**Additional context**
<img width="613" alt="image" src="https://github.com/stripe/stripe-react-native/assets/34293050/875d12e1-f3f2-4cc8-82b6-73141495c225">

**Comment by charliecruzan-stripe** [comment]
Hi! Unfortunately, supporting React Native for web isn't something we're prioritizing right now. For web apps, you should be able to use Stripe.js

**Comment by ericpoulinnz** [comment]
@charliecruzan-stripe why is that? React Native, particularly these days with Expo, is designed to be universal. We deploy to Android, iOS, and web from a single codebase.

Do you have any advice for apps built entirely in React Native to use Stripe.js? Is that done using a WebView?
