### ISSUE TITLE
Android Stripe React Native Init Payment Sheet Error,  React Native Stripe Version 0.37.0

### ISSUE THREAD

**Issue by vidurajith-darshana** [stripe/stripe-react-native#1626]
could not invoke stripe sdk init payment
Didn't find class "com.stripe.android.paymentsheet.PaymentSheet$GooglePayConfiguration$ButtonType

When I used it with IOS, it worked fine. But when worked with Android it gave me the above error. I didn't want to work with Google Pay. but seems it automatically uses Google Pay for payment intent which I created for Cards.

Here is my stripe provider.

`<StripeProvider
      publishableKey={stripe_public_key}
      merchantIdentifier={stripe_merchant_identifier}
    >
....
</StripeProvider>`

and I initiated the payment sheet this way.

`const paymentIntentResponse = await paymentIntentRequest(data);
    if (paymentIntentResponse) {
      const { error } = await initPaymentSheet({
        merchantDisplayName: "example",
        customerId: paymentIntentResponse?.data?.customer,
        customerEphemeralKeySecret: paymentIntentResponse?.data?.ephemeralKey,
        paymentIntentClientSecret: paymentIntentResponse?.data?.paymentIntent,
      });
      if (error) {
        showErrorToast(error?.message);
      }
    }
`

Payment Intent also fine and all the relevant data are coming. But only in Android, it gives above error. I tried to set null to googlePay as well. but no success.

React Native Version: 0.72.8
React Native Stripe: 0.37.0

**Comment by charliecruzan-stripe** [comment]
Are you using Expo? I can't reproduce this error myself

**Comment by vidurajith-darshana** [comment]
No, I'm not using expo.

**Comment by vidurajith-darshana** [comment]
Previously I had several build issues. Those were from R8 issues related to transforming when dexing.
I added below code snippets to my `android -> app -> build.gradle ` and it resolved.

implementation('com.stripe:stripe-android') {
        version {
            strictly '20.28.0' // when coming to 20.34.0 same build issues happens again
        }
    }

    implementation('com.stripe:financial-connections') {
        version {
            strictly '20.28.0'
        }
    }
    
    but the above-mentioned issue still persists.

**Comment by charliecruzan-stripe** [comment]
that would probably cause this bug. If you manually override the installed versions, that can break our dependencies

**Comment by vidurajith-darshana** [comment]
> that would probably cause this bug. If you manually override the installed versions, that can break our dependencies

I had to do that because I had a lot of build issues when I built the app. After overriding, I successfully built the app.

**Comment by vidurajith-darshana** [comment]
I have a solution. It's not proper, but downgrading to` @stripe/stripe-react-native` to `0.28.0` worked successfully for both IOS and Android. after installing, don't forget to pod update.

**Comment by vidurajith-darshana** [comment]
This issue has been fixed using an older version
