### ISSUE TITLE
Preferred networks aren't used with a co-branded card when user does not select a network themselves in CardForm component

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-react-native#1627]
**Describe the bug**
The list of preferred networks that should be used to process payments made with a co-branded card isn't used when user does not select a network themselves in CardForm component. For PaymentSheet it works.

**To Reproduce**
1. Configure CardForm component with preferredNetworks={[CardBrand.Mastercard, CardBrand.Visa]} props
2. Enter co-branded card test number 4000002500001001
3. Add card
4. Properties card.networks.preferred = null and card.display_brand = "cartes_bancaires" while they should be equal to "visa"

**Expected behavior**
Preferred networks should be used.

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro - 2024-03-20 at 18 32 36](https://github.com/stripe/stripe-react-native/assets/65358122/64571beb-0ad2-4de0-a16f-72f4711993c2)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro (simulator)
 - OS: iOS 17.4

**Additional context**
- @stripe/stripe-react-native = 0.37.1

**Comment by tgensol** [comment]
@charliecruzan-stripe
