### ISSUE TITLE
[just a question] when can we actually use this library? (considering that apple only allows apple payment in apps)

### ISSUE THREAD

**Issue by tommy-typos** [stripe/stripe-react-native#1646]
First of all, I am sorry if I sound rude. I just came accross this library while searching how to use Stripe on my next js app.

I would of course love to use this library in future in my mobile apps, but with apple's strict "only apple payment method" policy in mobile apps, how can we even use it in our apps without getting banned from app store?

I would appreciate if you share use cases examples that are not against apple's or google's in-app payment policies. Thank you very much

**Comment by tommy-typos** [comment]
Note: I've read Recommended Usage section on Readme file. I am just curious what those "all the other scenarios" are that we can actually use Stripe..

![Screenshot_2024-04-24-23-43-41-387_com android chrome](https://github.com/stripe/stripe-react-native/assets/137985975/930b9ed2-44dd-4c0b-b020-36562d0a455f)

**Comment by seanzhang-stripe** [comment]
Hi @tommy-typos Google Play and Apple app store updates their rules from time to time, here are [some examples](https://support.stripe.com/questions/changes-to-mobile-app-store-rules) of apps using alternative payment options.

Stripe won't be able to advise whether your app is eligible of alternative payment options, you should work directly with Google Play or Apple app store on this.
