### ISSUE TITLE
Is .cartesBancaires as additionalEnabledApplePayNetworks already supported ?

### ISSUE THREAD

**Issue by huextrat** [stripe/stripe-react-native#1647]
**Is your feature request related to a problem? Please describe.**
Is `additionalEnabledApplePayNetworks` already compatible with `cartesBancaires` network ?

https://github.com/stripe/stripe-react-native/blob/36d9d3f54d815279e3e3a1eab3b85309fcccd883/ios/ApplePayUtils.swift#L21-L24

**Describe the solution you'd like**
Pass `additionalEnabledNetworks: ["cartesBancaires"],` in params of `createPlatformPayPaymentMethod`

**Comment by tgensol** [comment]
Up please

**Comment by charliecruzan-stripe** [comment]
Hi! This is already supported, we accept any string value and then turn it into a PKPaymentNetwork in the swift layer with https://developer.apple.com/documentation/passkit_apple_pay_and_wallet/pkpaymentnetwork/2092174-init

**Comment by charliecruzan-stripe** [comment]
should be `cartesBancaires`, what version are you using?

**Comment by huextrat** [comment]
Hi @charliecruzan-stripe, we have tried both `cartesBancaires` & `.cartesBancaires`. Whatever value we use, we get the same result: the "cartes bancaires" network is not used when using a card compatible with this network.

We are currently using version 0.37.3: https://github.com/stripe/stripe-react-native/releases/tag/v0.37.3
