### ISSUE TITLE
[allowsRemovalOfLastSavedPaymentMethod] for the stripe-react-native

### ISSUE THREAD

**Issue by YuriOlepir** [stripe/stripe-react-native#1656]
Hello!

I see this flag `allowsRemovalOfLastSavedPaymentMethod` is already added to the IOS and Android, are you planning to add this for the stripe-react-native?

It is highly necessary to prevent users from deleting the last payment method.

**Comment by charliecruzan-stripe** [comment]
Hi! Yes, we'll be bringing this in for the next release

**Comment by YuriOlepir** [comment]
@charliecruzan-stripe Thx, for the quick response.
