### ISSUE TITLE
App Crashing when I try to use `stripe/stripe-react-native` | Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes

### ISSUE THREAD

**Issue by petrovicstefanrs** [stripe/stripe-react-native#1658]
**Describe the bug**
I followed the instructions to install `@stripe/stripe-react-native`. Since I'm using Expo, I used `expo install @stripe/stripe-react-native` to install the correct version. I also had to downgrade `@stripe/stripe-identity-react-native` to be compatible with the version of `@stripe/stripe-react-native` that was installed. 

As soon as I import anything from `@stripe/stripe-react-native` the app just crashes with the following error: **```Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes```**

**To Reproduce**
Install `@stripe/stripe-react-native` and try to import `StripeProvider`

As soon as I import anything from the library my app crashes.
```js
import { StripeProvider } from "@stripe/stripe-react-native";
```

**Expected behavior**
App not crashing

**Screenshots**
<img width="416" alt="Screenshot 2024-05-13 at 19 12 16" src="https://github.com/stripe/stripe-react-native/assets/9686040/05cd17b9-b883-482e-b525-0a2083e7b2cd">

**Smartphone (please complete the following information):**
 - Device: iOS Simulator (iPhone 15 Pro Max)
 - OS: iOS17.2

**Additional context**
- "react-native": "0.73.4",
- "@stripe/stripe-identity-react-native": "0.2.2",
- "@stripe/stripe-react-native": "~0.35.1",

**Comment by israelcrux** [comment]
Experiencing this issue as well

**Comment by ccen-stripe** [comment]
cc @charliecruzan-stripe 

hi @petrovicstefanrs could you try the latest release of 
stripe-identity-react-native [0.2.8](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.2.8)
and 
stripe-react-native [0.37.3](https://github.com/stripe/stripe-react-native/releases/tag/v0.37.3) ?

**Comment by petrovicstefanrs** [comment]
Hi @ccen-stripe I'm still facing the same issue.

While I was able to make a build this time using the latest lib versions (this was failing consistently the last time i tried it), I'm still not able to get the `stripe-react-native` lib to not crash. Take a look at what happens as soon as I import `StripeProvider` from the library https://www.loom.com/share/c12483ac7dcf4b7f97eaf35c307cf37b

**Comment by charliecruzan-stripe** [comment]
Hi! This indicates an issue with your local project. In this library, we call `NativeEventEmitter` with `NativeModules.StripeSdk`, so this means you're getting `null` back for that value. I would recommend clearing out your `pods` and re-`pod installing` and trying again. 

Since you're using Expo, make sure you use the proper version of `@stripe/stripe-react-native` (you can see our changelog for which version to use, or use `expo install`).

**Comment by petrovicstefanrs** [comment]
@charliecruzan-stripe 
Thanks for the reply, but unfortunately that didn't help. To make sure nothing was interfering, I started from a clean branch and just added the failing `@stripe/stripe-react-native` that I installed with the `expo install` command. 

It installed "@stripe/stripe-react-native": "~0.35.1" - Which is the version I was trying out initially when I opened this issue. I removed `Pods`, `Podfile.lock`, re-installed all pods, and I'm still getting the same error.

**Comment by charliecruzan-stripe** [comment]
Could you send me the exact steps & commands you're taking? Including things like if you're running this in Expo Go, etc. basically as much detail as possible, OR share a fresh project with me that reproduces the error, and then i can help debug

**Comment by petrovicstefanrs** [comment]
Last night, as I was doing it all again from the start, on a clean branch, so I could document the steps for you, it actually worked.

I would assume that removing `Podfile.lock`, `Pods` folder, and then reinstalling everything did the trick. Not sure why it didn't work the first time around but at least it's working.

Thank you for your time @charliecruzan-stripe!
