### ISSUE TITLE
"Cannot read property 'StripeProvider' of undefined" right after install

### ISSUE THREAD

**Issue by israelcrux** [stripe/stripe-react-native#1660]
**Describe the bug**
Installed `@stripe/stripe-react-native` (0.35.1) on my expo (50.0.14) app by executing:
`expo install @stripe/stripe-react-native`

I followed the instructions on https://github.com/stripe/stripe-react-native/tree/master and https://docs.stripe.com/apple-pay?platform=react-native

I'm experiencing this issue:

```
Cannot read property 'StripeProvider' of undefined
```

**To Reproduce**
1. Install the library
`expo install @stripe/stripe-react-native`

2. Add provider component to root
```
import { StripeProvider } from '@stripe/stripe-react-native';

//...

export const App: React.FC<AppProps> = ({ appName, theme }) => {

  // ...
    return (
      <StripeProvider
      publishableKey="pk_..."
      merchantIdentifier="merchant.com...."
    >
        <SomeAppComponent />
    </StripeProvider>
    );

};

```

3. Launch the app

**Expected behavior**
The app runs.

**Screenshots**
<img width="444" alt="Screenshot 2024-05-14 at 11 39 47 PM" src="https://github.com/stripe/stripe-react-native/assets/4313950/49edecb3-c58b-4dd5-a58d-9f0a6f8bbee8">

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.2.1

**Smartphone (please complete the following information):**
 - Device: iPhone 15 simulator and iPhone 13 pro iOS 17.2
 - OS: iOS 17.2

**Comment by ailtonaires** [comment]
how to solve it?

**Comment by Rooban19** [comment]
Run `react-native run-android` or  `react-native run-ios`
