### ISSUE TITLE
Can't remove Revolut payment method

### ISSUE THREAD

**Issue by alexandr-feschenko** [stripe/stripe-react-native#1666]
Revolut is being rendered by default in my application even though it is turned off in the Stripe control panel. I added paymentMethodTypes: ['card'], but it's still being. 
![Screenshot at May 29 17-00-09](https://github.com/stripe/stripe-react-native/assets/63351437/2b7f045a-8a12-447c-b51d-16b00fe2c23e)

**Comment by martamearin** [comment]
Hello! I'm having the same issue. Were you able to solve it? Thanks!!
