### ISSUE TITLE
[iOS] payment sheet not closing after Swish completion

### ISSUE THREAD

**Issue by ottob** [stripe/stripe-react-native#1675]
**Describe the bug**
After a successful payment using Swish and user is returned to app, the payment sheet is not closed.

It works fine for other providers using redirects (like klarna), it works fine in the iOS simulator. It does not work in TestFlight/App Store version.

**To Reproduce**
1. Click Payment button from payment sheet
2. Open swish app, this opens bankid app (this can not be recorded, that's why there is two videos below).
3. Press Open in app button.
4. Sheet stays open and nothing happens

**Expected behavior**
The payment sheet should disappear.

I also expected the `handleURLCallback` function to return true. It does in simulator (when sheet is closed), but not in the TestFlight/prod version, there it returns `false`.

They return url of the app is:
myapp://stripe-redirect?payment_intent=pi_3POEQ8FVh2i3IPYO0pQbV9zw&payment_intent_client_secret=pi_3POEQ8FVh2i3IPYO0pQbV9zw_secret_MOouimBCcf3rD1raHkasnZUam&redirect_status=succeeded

**Videos**
If applicable, add videos to help explain your problem.

https://github.com/stripe/stripe-react-native/assets/67104/c0b61db1-0387-446a-b361-cd96054b6cc8

https://github.com/stripe/stripe-react-native/assets/67104/eff450f7-a858-4383-97ad-c25aa865cff1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iphone13
 - OS: [e.g. iOS8.1] 17.5.1
 - Browser [e.g. stock browser, safari] safari

**Additional context**
expo, using "@stripe/stripe-react-native": "0.37.2"

**Comment by simonbengtsson** [comment]
We started seeing the same thing recently. Can reproduce every time with live payments using Swish with both version 0.37.3 and now with the latest 0.38.1.

**Comment by simonbengtsson** [comment]
I checked now and already had the latest `23.27.6` iOS SDK. Stripe react native has `'~> 23.27.0'` as version constraint on so `pod update` will get you the latest `23.27.6`

**Comment by ottob** [comment]
Thanks for checking. We are using expo so I cannot fiddle with `pod update`.

I hope they can find another solution then.

**Comment by seanzhang-stripe** [comment]
Hi @ottob we will release a new version that includes the new Stripe iOS SDK very soon. 

Hello @simonbengtsson you mentioned that you still encountered some problems even with iOS SDK `23.27.6`. Can you share with some PaymentIntent IDs so that I can investigate further?

**Comment by simonbengtsson** [comment]
Sure! Here is two that I made just now: 
- pi_3PeaIjC7zQsHkcnd1E9JgnJd
- pi_3PeaGPC7zQsHkcnd0KSA2cfN
