### ISSUE TITLE
useApplePay() and useGooglePay() is not a function undefined

### ISSUE THREAD

**Issue by russmenum** [stripe/stripe-react-native#1681]
**Describe the bug**
Updating an EXPO app required updating Stripe @stripe/stripe-react-native to 0.35.1 for EXPO SDK 50

**To Reproduce**
1. Update to EXPO 50
2. Update @stripe/stripe-react-native to 0.35.1
3. launch all
4. go to view with these hooks

**Expected behavior**
Would expect the working payment hooks to still work,

**Desktop (please complete the following information):**
 - OS: Mac OS 14.3.1

**Smartphone (please complete the following information):**
 - Device: XCODE and Android Studio Emulators
 - OS: iOS 15 and API 34

**Additional context**
Prior to update this code worked fine
```js
import { 
  useApplePay,
  ApplePayButton,
  useGooglePay,
  GooglePayButton,
  useStripe,
} from "@stripe/stripe-react-native";

const { 
    presentApplePay,
    confirmApplePayPayment,
    isApplePaySupported,
  } = useApplePay();

const {
    isGooglePaySupported,
    //initGooglePay, // doc wants here, but see about putting in same pay token place as we did for "tipsi-stripe"
    initGooglePay,
    presentGooglePay,
  } = useGooglePay()


```

Now  ```useGooglePay()``` and ```useApplePay()``` crash the app triggering respective not a function undefined errors

I am not seeing documentation on changes to these hooks? Am I missing it? what changed that these no longer work?

**Comment by charliecruzan-stripe** [comment]
Hi, those APIs were removed in favor of the usePlatformPay API, please take a look at the changelog to see changes when upgrading versions: https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#0290---2023-07-13

**Comment by russmenum** [comment]
> usePlatformPay

What the heck goes in ```TYPE```

```
<PlatformPayButton
        type={PlatformPay.ButtonType.Pay}
        onPress={pay}
        style={{
          width: '100%',
          height: 50,
        }}
      />

```

For Apple side passing the old standard ```type={"plain"}``` works and you can load the paysheet

For android side, even trying to render the button CRASHES the app with either TYPE or cant pass string,, and so on... the doc if obscure on what it wants here

```js
export interface Props extends AccessibilityProps {
  /** Sets the text displayed by the button. */
  type?: ButtonType;

```

It also says this is an "optional" prop, but if you omit it you get ERRORs about setting accessibility state, if you try and pass to it android side you get ERRORs regarding GooglePayButton
