### ISSUE TITLE
400002500003155

### ISSUE THREAD

**Issue by Mauricio-sy** [stripe/stripe-react-native#1697]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by seanzhang-stripe** [comment]
Hi @Mauricio-sy Looks like you accidentally created this ticket. I'm closing it now, feel free to create a new one when you have something to share.
