### ISSUE TITLE
Accessibility issues with buttons from the Express Checkout Element

### ISSUE THREAD

**Issue by fedefunes96** [stripe/stripe-react-native#1706]
**Describe the bug**
When focusing the Google Pay button, the outline is not displayed correctly, it only appears at the top & bottom of the component.

**To Reproduce**
1. Add a Google Pay button from the Express Checkout Element
2. Tab to focus that element
3. See that the outline is not showing as expected

**Expected behavior**
1. The button should have a clear outline of the specified width
2. If using the dark button, the outline should have enough contrast

**Screenshots**
<img width="256" alt="Screenshot 2024-08-02 at 5 28 52 PM" src="https://github.com/user-attachments/assets/92288b0a-85fa-4ac1-95a7-e9d4424d0197">

**Desktop:**
 - Browser: Google Chrome
 - Version: 126.0.6478.127

**Additional context**
This can also be seen in the demo on Stripe site: https://docs.stripe.com/elements/express-checkout-element#try-demo

**Comment by seanzhang-stripe** [comment]
Hi @fedefunes96 Thanks for the feedback! Looks like you want to report an issue for react Stripe.js, and we manage it in a separate github [repo](https://github.com/stripe/react-stripe-js).

I'll close this ticket. Feel free to create a new ticket in [react-stripe-js](https://github.com/stripe/react-stripe-js) github repo
