### ISSUE TITLE
not able to confirm setup intent created for my connected account

### ISSUE THREAD

**Issue by shivam-cosmofeed** [stripe/stripe-react-native#1709]
I’m working with a Stripe account (platformAccount) and using Stripe Connect to set up a connected account. I’m trying to save a card for a customer on the connected account by creating a SetupIntent for that account. I then pass the client secret of this SetupIntent to the frontend, where I use confirmCardSetup(). However, I’m encountering an error with the following details:

Error Documentation: https://stripe.com/docs/error-codes/resource-missing
Message: "No such setupintent: 'seti_1PmBVYRtBFCjzLBfZ*******'"
Param: "intent"
Type: "invalid_request_error"

I’ve verified that the SetupIntent is correctly created for the connected account and that the client secret is correctly passed to the frontend.

Could you suggest whether this is an implementation issue or if it might be related to Stripe? Any advice or potential workarounds would be appreciated.

**Comment by lreardon** [comment]
I'm encountering the same issue. Any additional context other than just "closed"?

**Comment by jrondon** [comment]
Hello, I'm having the same issue, do you found any solution?

**Comment by mrgamedev07** [comment]
same issue here for payment intend for stripe connect account

**Comment by rgommezz** [comment]
If the payment intent is in the context of a connected account, you have to wrap your component with another instance of `StripeProvider`, and there you can set `stripeAccountId`. It's a bit counterintuitive, because it would be more natural to set it as part of the Payment Element flow. For instance, if you are calling both `initPaymentSheet` and `presentPaymentSheet` from the `ScreenContent` component, you can do as follows:

```tsx
<StripeProvider
  publishableKey="yourKey"
  stripeAccountId="connectedAccountId"
>
  <ScreenContent />
</StripeProvider>
```

**Comment by jaynewstrom-stripe** [comment]
Hi all, in order for us to better assist you with this integration issue, I'd love to point you to our support channel on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you 24/5. Thank you!

**Comment by antoinersw** [comment]
hello, StripeProvider exposes a stripeAccountId prop and that prop is the connected account id you need to update !
cheers
