### ISSUE TITLE
Android: Using GPay results in “Something went wrong” message, but payment is successful

### ISSUE THREAD

**Issue by short-dsb** [stripe/stripe-react-native#1714]
**Describe the bug**
Seeing an odd error today when testing which I had not encountered before. Not sure if this is in the React Native layer or the Android layer, but I’m starting here since this is the implementation we use. 🙂 

**To Reproduce**
1. Open payment sheet.
2. Tap GPay button.
3. Select payment method and confirm.
4. A red message reading “Something went wrong” appears underneath the GPay button.
5. However, when checking the Stripe dashboard, the payment was successful.

As a result, the user will encounter an error if they try to pay again (which they likely will since the message indicates the payment failed).

**Expected behavior**
Payment is successful with no error messages.

**Screenshots**
The error message:
![gpay](https://github.com/user-attachments/assets/8d7b75ab-119e-4564-8708-59a1f7288ef1)
The successful GPay transaction:
![stripe](https://github.com/user-attachments/assets/e2eb0a44-c939-4bcd-a8b5-276f9ddf3919)

**Smartphone:**
 - Device: Google Pixel 6 (emulator)
 - OS: API 33

**Additional context**
Not sure if this is happening in production for us as I’d have to make a purchase using real money. However, we haven’t received any user reports as far as I know. It’s possible it’s isolated to the test environment.

Any insight would be appreciated!

**Comment by FerdinandvHagen** [comment]
We are also encountering this issue. Happens mostly on Production and we didn't have any luck recreating the bug in our development environments so far.

Attaching screenshots of Sentry and Stripe. The activity log from Stripe looks normal compared to other transactions.

![Screenshot 2024-08-21 at 11 28 35](https://github.com/user-attachments/assets/11961435-47a1-429a-9b24-411c345bab6e)
![Screenshot 2024-08-21 at 11 25 39](https://github.com/user-attachments/assets/896e3f76-43b5-4ab9-bfeb-0d1d40e71b3c)

**Comment by FerdinandvHagen** [comment]
A new Android SDK update has landed @short-dsb.
Android SDK update https://github.com/stripe/stripe-android/releases/tag/v20.48.5.

The update should be pulled in automatically if you use a CI pipeline.
This seems to have fixed it for us (at least for now).

**Comment by samer-stripe** [comment]
Hey @short-dsb! This was fixed in the Android SDK and should have been pulled into any React Native version after v0.38.2. Please re-open this ticket if you have any more issues regarding this topic!
