### ISSUE TITLE
Getting an error after installing stripe-react-native package in my expo project and building for iOS using npx expo run:ios

### ISSUE THREAD

**Issue by mahithsc** [stripe/stripe-react-native#1715]
**Describe the bug**
After installing the stripe-react-native-package I get an error when trying to build for iOS. I and trying to implement Apple Pay and test on my simulator but it won't let me as I cant build the proejct. I have attached an image of the error that I am getting.

**To Reproduce**
1. create an expo app
2. download stripe-react-native package
3. run `npx expo run:ios`

**Expected behavior**
The package should build as expectedd without any hiccups.

**Screenshots**
![Screenshot 2024-08-17 at 1 26 50 AM](https://github.com/user-attachments/assets/875675bb-96b8-495e-88ec-81f71b0a70a0)

**Desktop (please complete the following information):**
MacBook Pro M1 Pro

**Comment by Tieu-Mai-Nhi** [comment]
Did you fix it? I meet this bug too, I use Xcode 14.3 and macOS 13.0.1

**Comment by mahithsc** [comment]
@Tieu-Mai-Nhi your XCode or MosOS is probably outdated, that’s why it wasn’t working for me. Update to the latest

**Comment by Tieu-Mai-Nhi** [comment]
That's true, I tried building again with Xcode, and macOS newer was successful, thank you for supporting me
