### ISSUE TITLE
Android Payment Sheet: 3d secure browser crashes on close

### ISSUE THREAD

**Issue by shanereid** [stripe/stripe-react-native#1738]
**Describe the bug**
On android devices, the 3d secure browser that stripe pops up seems to crash and stall the entire app when dismissed. Error received in LogCat is ` [ERROR:aw_browser_terminator.cc(166)] Renderer process (31545) crash detected (code -1).`

I've managed to reproduce in a fresh react-native 0.74.5 install with the latest version of stripe-react-native (0.38.6).

**To Reproduce**
1. Download my repro repo: https://github.com/ivo-digital/stripe-react-native-android-issue-example
2. Run it on android
3. Tap "Tap to Pay"
4. Enter an setup-requires-SCA example card, I use `4000 0027 6000 3184`
5. SCA window pops up fine
6. whether you pass, fail or press close on the browser, once it dismisses the app will become unresponsive.
7. Check logcat, you'll see an error similar to `[ERROR:aw_browser_terminator.cc(166)] Renderer process (31545) crash detected (code -1).`

**Expected behavior**
- SCA window completes successfully and returns status to payment sheet

**Screenshots**
<img width="2475" alt="Screenshot 2024-09-26 at 11 36 11" src="https://github.com/user-attachments/assets/55bf8bd4-117d-4928-9505-d874b7800e93">

https://github.com/user-attachments/assets/91e01a5c-e0b4-4a6d-b1e1-7ad443ee5b5c

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro (same issue reported on a Galaxy as well)
 - OS: Android 14
 - React Native 0.74.5

**Additional context**
Exact same setup works perfectly on iOS.

I'm really hoping I'm missing something silly with android setup as I can't seem to see much reported on this elsewhere on the internet. Even with urlSchemes and returnUrls and setup identical to the stripe react native example app I can't seem to get any headway on this. Any help would be massively appreciated!

**Comment by karlr-stripe** [comment]
Hi there,
This is most likely because your code never calls the `intentCreationCallback` in the function you pass to `confirmHandler` : 
https://github.com/ivo-digital/stripe-react-native-android-issue-example/blob/main/StripeButton.tsx#L55-L61 

That's a required step as you need to provide a PaymentIntent client_secret so the SDK can complete the setup process:
https://docs.stripe.com/payments/finalize-payments-on-the-server?platform=react-native&type=setup#confirm-the-payment-details

**Comment by shanereid** [comment]
Hi @karlr-stripe, in the actual usecase we do call that. The problem is the code, on android only, never gets there because it never progresses beyond here due to the issue I'm outlining:
https://github.com/ivo-digital/stripe-react-native-android-issue-example/blob/main/StripeButton.tsx#L34

To get further into the weeds on our exact usecase:
- Using the custom flow is clunky due to the separation of the card form & apple/google pay options, and the fact it seems to be setup more for payment method management than collecting one single payment method. Also some issues with the user dismissing the payment sheet being treated as selecting the Apple Pay option.
- Because of these issues we use the payment sheet standard flow to setup a payment method, allowing for Apple Pay or Google Play to be shown inline with the card form.
- In the confirm handler we confirm the payment method using `handleNextActionForSetup`, call an internal API as part of this process, and if that api fails we can return the api error in the `intentCreationCallback`. If it succeeds we return the secret which will complete & dismiss the payment sheet. This allows us to surface payment method-related errors nicely in the payment sheet.
- On iOS this works perfectly. On Android calling `handleNextActionForSetup` inside a Payment Sheet confirmHandler will simply brick your app and js code after that call will never execute if 3DS is required. Surely this isn't intended functionality?

This flow works perfectly in iOS, are you saying the official stance is that there is an explicit incompatibility with calling `handleNextActionForSetup` inside a payment sheet confirm handler and that this is intended behaviour?

**Comment by karlr-stripe** [comment]
> the official stance is that there is an explicit incompatibility with calling handleNextActionForSetup inside a payment sheet confirm handler and that doing so breaking your app is intended behaviour?

I would say yes — `handleNextActionForSetup` is an old method intended for the old "manual confirmation" flow where you create an Intent with `confirmation_method="manual"` and predates PaymentSheet. That flow has been replaced with newer flows like the one linked above and the PaymentSheet expects to be handling all the authentication and next actions itself, your code just needs to give it the client_secret, so your code calling other SDK functions at the same time is probably causing undefined behaviour. 

The flow you're describing seems non-standard and not supported really. You might open a support ticket at https://support.stripe.com/?contact=true instead for integration advice.

**Comment by shanereid** [comment]
OK, fair enough. Thanks @karlr-stripe
