### ISSUE TITLE
Google play new photo and video permissions policy

### ISSUE THREAD

**Issue by aliosman21** [stripe/stripe-react-native#1740]
**Is your feature request related to a problem? Please describe.**

According to this link [here](https://support.google.com/googleplay/android-developer/answer/14115180) Google play is requiring apps to remove the permission of ```android.permission.READ_MEDIA_IMAGES & android.permission.READ_MEDIA_VIDEO```, These permissions are used in this library to scan the the cards and populate the data.

**Describe the solution you'd like**

Since this is not considered a core functionality for most apps since not all apps are gallery or editing apps in our case we only save the cards for the customer for future purchases there should be an option to disable this permission fully or use the permissions that Google play allows which is photo picker permission.

It would be great either to use the permission allowed by Google play or make the scan an optional feature in a sense where it allows the developer to put its permission by hand in the manifest file

**Describe alternatives you've considered**

We will try to submit the appeal but most probably it will be refused since the app's core functionality isn't gallery or photo editing or capturing

**Comment by seanzhang-stripe** [comment]
Hi @aliosman21 I [searched](https://github.com/search?q=repo%3Astripe%2Fstripe-android+READ_MEDIA&type=code) the Stripe Android SDK source code, and I don't see any usage of `android.permission.READ_MEDIA_IMAGES` or `android.permission.READ_MEDIA_VIDEO`, can you check your project again and see if these two permissions are added by other dependencies?

**Comment by aliosman21** [comment]
You are right it's added by another dependency.

Thank you for clarifying 🙏🏼
