### ISSUE TITLE
Unable to integrate and test the payment sheet

### ISSUE THREAD

**Issue by travisobregon** [stripe/stripe-react-native#175]
**Describe the bug**
I am trying to [integrate and test the payment sheet](https://stripe.com/docs/mobile/payments-ui-beta?platform=react-native#integrate-payment-sheet) using the `payment-sheet` branch. Is it okay to start doing that? I am getting compilation errors for iOS.

**To Reproduce**
1. Download and extract a ZIP file of the `payment-sheet` branch
2. Inside the extracted folder run: `yarn bootstrap && yalc publish`
3. Run `yalc add @stripe/stripe-react-native` in your dependent project
4. Run `yarn && npx pod-install`
5. Run `yarn ios` or run the app through XCode

**Expected behavior**
The app to compile.

**Screenshots**
These are the errors in XCode:
<img width="260" alt="Screenshot 2021-04-29 at 13 51 23" src="https://user-images.githubusercontent.com/12074713/116553405-ff600680-a8f1-11eb-8212-b4d3ea693b4c.png">
<img width="853" alt="Screenshot 2021-04-29 at 13 51 51" src="https://user-images.githubusercontent.com/12074713/116553471-10107c80-a8f2-11eb-8edd-533a762ac10c.png">

**Desktop (please complete the following information):**
 - macOS 11.2.1
 - XCode 12.5

**Additional context**
I think I have mentioned everything, but if there is something else I should do, please let me know.

**Comment by thorsten-stripe** [comment]
Closing this out as I believe via updating pod dependencies this will be resolved. 

Alternatively you might want to start from scratch and install via `yarn` and follow the new docs: https://stripe.com/docs/payments/accept-a-payment?platform=react-native
