### ISSUE TITLE
[iOS] Can't see card input fields after `presentPaymentSheet` is initiated

### ISSUE THREAD

**Issue by SRI-SRINIVASAN-S** [stripe/stripe-react-native#1751]
**Description**:  
When initiating the Stripe `presentPaymentSheet` on iOS, the card input fields are not visible, and the app crashes immediately. This issue occurs on iOS (tested on iPhone simulators with versions 15 and 16) but works perfectly fine on Android.

**Expected Behavior**:  
We should be able to see the card input fields on the payment sheet to proceed with the payment.

**Steps to Reproduce**:
1. Navigate to the subscription payment screen on the iOS app.
2. Click the "Subscribe" button to trigger `initializePaymentSheet` and `presentPaymentSheet`.
3. Notice that the card input fields are not visible, and the app crashes.

**Code Example**:  
Here’s a code snippet that initializes the payment sheet:

```javascript
const initializePaymentSheet = async (billingAddress) => {
  const {customer, ephemeralKey, paymentIntent} = await fetchPaymentSheetParams();
  
  const {error} = await initPaymentSheet({
    merchantDisplayName: 'XYZ Pvt Ltd.',
    customerId: customer,
    customerEphemeralKeySecret: ephemeralKey,
    paymentIntentClientSecret: paymentIntent,
    returnURL: 'https://docs.stripe.com',
    allowsDelayedPaymentMethods: true,
    defaultShippingDetails: billingAddress,
  });

  if (!error) {
    setLoading(true);
    openPaymentSheet();
  } else {
    Alert.alert('Error initializing payment sheet', error.message);
  }
};

const openPaymentSheet = async () => {
  const {error} = await presentPaymentSheet();
  if (error) {
    Alert.alert(`UnSuccess: ${error.code}`, error.message);
    navigation.navigate(SUBSCRIPTION_PLANS);
  } else {
    Alert.alert('Success', `Subscribed to ${selectedSubscriptionPlan} plan`);
    navigation.navigate(SUBSCRIPTION_PLANS);
  }
};
```

**Screenshots/Video**:

- **iOS (Crash)**: [iOS App Crash Video](https://github.com/user-attachments/assets/9d3cd11c-850f-49c2-b69f-b4ce746c94db)
- **Android (Working)**: [Android Working Video](https://github.com/user-attachments/assets/ea7d74e7-6ba9-40e6-a7b5-e9f9c6fa7e3d)

**Smartphone Details**:
- **Device**: iPhone simulator 15,16
- **macOS Version**: 15.0.1
- **Xcode Version**: 16

**Additional Context**:  
This issue only occurs on iOS, and there is no issue with Android. The payment sheet is initialized properly but crashes on iOS without showing the card input fields. Additionally, the payment status appears incomplete in the Stripe dashboard, indicating that the payment could not be processed.

**Comment by parkerbo** [comment]
I am also experiencing this issue

**Comment by Parth8733** [comment]
**Update**: I previously used version 0.35.1, and all other settings remained as described above. After updating to version 0.37.2, the issue has been resolved. @parkerbo @SRI-SRINIVASAN-S

**Comment by SRI-SRINIVASAN-S** [comment]
@parkerbo @Parth8733 I also updated the Stripe version from 0.35.1 to the latest version, 0.39.0, which resolved the issue.
