### ISSUE TITLE
Payment Sheet showing Indonesian Rupiah incorrectly

### ISSUE THREAD

**Issue by krisbaum74** [stripe/stripe-react-native#1759]
**Describe the bug**

If I create a payment intent of 5500000 (which is 55,000.00 IDR), the payment sheet will show this as 5,500,000 - the IDR cents are excluded even though the payment intent must include them.

**To Reproduce**
1. create a payment intent with indonesian rupiah - use above value as an example
2. open the payment sheet

**Expected behavior**
value displayed should be 550,000.00IDR.

**Screenshots**
 
<img width="284" alt="Screenshot 2024-10-18 at 7 31 29 AM" src="https://github.com/user-attachments/assets/1e398a18-d6ce-4245-bb6d-d6ec18972144">

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro 
 - OS: ios 17.4
 - Expo version 50

**Comment by yuki-stripe** [comment]
Hello @krisbaum74, what iOS SDK version are you using? This should have been fixed in https://github.com/stripe/stripe-ios/releases/tag/23.28.0

**Comment by krisbaum74** [comment]
hi @yuki-stripe  thankyou yes it seems to work now that ive upgraded my stripe react native package.
