### ISSUE TITLE
Payment Sheet input validation incorrectly marks account numbers as invalid

### ISSUE THREAD

**Issue by timleyden** [stripe/stripe-react-native#1770]
**Describe the bug**
After moving from elements hosted on a web page to the react native sdk with payment sheet we got several reports that stripe was not allowing users to enter bank account numbers. After investigation we found that several banks in Australia have 6 digit account numbers. When a customer enters this valid number they cannot proceed and receive a validation error stating the number in incomplete

**To Reproduce**
1. Go to payment sheet with payment method type becs enabled
2. Click on 'AU BECS Direct Debit'
3. Scroll down to 'Account Number' and enter only 6 digits

**Expected behavior**
except 6 digit account numbers
alternatively automatically padding with 0s but this may lead to confusion

**Screenshots**
![image](https://github.com/user-attachments/assets/e4044b1e-6c58-48f6-b233-282a74a57933)

**Smartphone (please complete the following information):**
 - Device: Samsung s22
 - OS: Android 14
 - Version: stripe/stripe-react-native": "^0.39.0",

**Additional context**

**Comment by seanzhang-stripe** [comment]
Hi @timleyden Thanks for flagging this problem.

The account number validation logic is from the underlying Stripe Android SDK. I've already informed the Stripe mobile SDK team about this problem. Once this problem is fixed in the new Android and iOS SDK, you can just remove `yarn.lock` file and run `yarn install` again to download the latest mobile SDK.

**Comment by samer-stripe** [comment]
Hey @timleyden! This was fixed in this [PR](https://github.com/stripe/stripe-android/pull/9576) and released in [v21.0.1](https://github.com/stripe/stripe-android/releases/tag/v21.0.1). Please re-open if you continue having issues.

**Comment by karl007253** [comment]
Hello @samer-stripe! I believe we should still open this issue until new version for `stripe-react-native` is released.

Cause I've tried updating android sdk (21.0.1) and it seems that `stripe-react-native` doesn't support this atm.
![image](https://github.com/user-attachments/assets/c648c479-f697-4671-ab7f-352e7cdcf35f)

PS: I think this is resolved in this [PR](https://github.com/stripe/stripe-react-native/pull/1765), just waiting for release.

**Comment by karl007253** [comment]
> Hello @samer-stripe! I believe we should still open this issue until new version for `stripe-react-native` is released.
> 
> Cause I've tried updating android sdk (21.0.1) and it seems that `stripe-react-native` doesn't support this atm. ![image](https://private-user-images.githubusercontent.com/34635589/386510070-c648c479-f697-4671-ab7f-352e7cdcf35f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Njg2MzMsIm5iZiI6MTczMTY2ODMzMywicGF0aCI6Ii8zNDYzNTU4OS8zODY1MTAwNzAtYzY0OGM0NzktZjY5Ny00NjcxLWFiN2YtMzUyZTdjZGNmMzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEwNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjM5NzBlMWFlNzc1Nzg4ZmZjYTA0ZDYwNGVkMDcxZWZlN2U1NGQzYzE4NGFkY2JmNGU5YThlOTkyMzUxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HGDn_oq9AlSeQ7-EG6sUe45zqiFLIHdosBfERMMt-nE)
> 
> PS: I think this is resolved in this [PR](https://github.com/stripe/stripe-react-native/pull/1765), just waiting for release.

For the meantime, here's a patch-package I did to resolve this.
[@stripe+stripe-react-native+0.39.0.patch](https://github.com/user-attachments/files/17774437/%40stripe%2Bstripe-react-native%2B0.39.0.patch)

**Comment by timleyden** [comment]
@samer-stripe  i don't seem to be able to reopen
