### ISSUE TITLE
Creating a Card without CardField or CardFieldPayment

### ISSUE THREAD

**Issue by adkenyon** [stripe/stripe-react-native#178]
**Describe the bug**
I am unable to create a `card` payment type without using a `<CardField/>` or `<CardFieldPayment/>`

**To Reproduce**
```
const paymentMethod = await createPaymentMethod({
  type: 'card',
  card: {
    number: 4242424242424242,
    expMonth: 5,
    expYear: 2022,
    cvc: 314 
  },
});
```

**Expected behavior**
I can create a `card` payment method without stripe form fields. 

**Additional context**
I believe the code [here](https://github.com/stripe/stripe-react-native/blob/251b8f9a6de8853277993a6ce3c8bc25c132687e/ios/PaymentMethodFactory.swift#L115) is preventing passing the card details

**Comment by thorsten-stripe** [comment]
Closing this out, but @adkenyon feel free to reopen if the above mentioned resolution doesn't work for you.

**Comment by agentscamp5** [comment]
@thorsten-stripe our team has been using a beta version of the package that did allow us to submit card information directly using our own form. We weren't sending it to our servers though, it was directly between the client application and Stripe's servers.

What about using the CardField allows special PCI compliance rules versus our own form that does not send information to our servers?

The design team is considering using the CardField now in light of the released version of this package not supporting using our own form, but we also are interested in potentially dealing with PCI compliance ourselves and having the form layout we want, and if that were the case is it even possible to use this package currently?
