### ISSUE TITLE
Colors set in `threeDSecureParams` are mostly ignored

### ISSUE THREAD

**Issue by benomatis** [stripe/stripe-react-native#182]
I tried setting the main color (themeColors.brandBlue) everywhere I could, but the only thing that changed is the text in the middle - that's the colour everything that is now violet should have. How can I achieve that?

```js
<StripeProvider
  publishableKey={key}
  threeDSecureParams={{
    backgroundColor: '#FFFFFF', // iOS only
    timeout: 5,
    label: {
      headingTextColor: themeColors.brandBlue,
      headingFontSize: 13
    },
    navigationBar: {
      headerText: 'Complete card authentication',
      statusBarColor: themeColors.brandBlue // Android only
    },
    footer: {
      // iOS only
      backgroundColor: themeColors.brandBlue,
      headingTextColor: '#FFFFFF',
      textColor: '#FFFFFF'
    },
    submitButton: {
      backgroundColor: themeColors.brandBlue,
      borderRadius: 0,
      textColor: '#FFFFFF',
      textFontSize: 14
    }
  }}>
  <Component />
</StripeProvider>
```

<img width=300 src=https://user-images.githubusercontent.com/5822748/117082025-6db52680-ad41-11eb-9ae4-8cf44f260dee.png />

**Comment by benomatis** [comment]
@davidme-stripe adding `barTintColor` solves the issue with the header colour, it looks pretty neat now except for the 'Cancel' and the 'Complete Authentication' buttons, they still appear to ignore any styling changes I attempt to do to them.

@michelleb-stripe Is this going to be taken care of in this issue (and thus re-opened?) or shall I open a new one?

**Comment by benomatis** [comment]
@michelleb-stripe yes, and for iOS, we really only have the issue with the colors of those 2 buttons remaining.

**Comment by davidme-stripe** [comment]
I filed a new issue for the iOS changes: https://github.com/stripe/stripe-react-native/issues/201

**Comment by benomatis** [comment]
thank you @davidme-stripe
