### ISSUE TITLE
Android: 3D secure popup styling changes

### ISSUE THREAD

**Issue by benomatis** [stripe/stripe-react-native#185]
- [ ] 1. Android: 3DS progress spinner color
- [ ] 2. Android: The section titles under the 3DS2 complete authentication take the color of the main `backgroundColor` (which is supposed to be iOS only?) when opened

**Comment by arekkubaczkowski** [comment]
there was also one thing on my side to fix: https://github.com/stripe/stripe-react-native/pull/234/files#diff-4c983f2aa3f1856047fffa58ecd9f6447b449cfa4f480e8eb159ac858758aa57R424

- the first thing is that `accentColor` now changes the section titles color, @michelleb-stripe is it intentional?
- `accentColor` probably should change the spinner color (I haven't found any different way to set it tho)

So I guess the rest of issues should be fixed on android side, @michelleb-stripe let me know if I am wrong

**Comment by thorsten-stripe** [comment]
@michelleb-stripe can you help out with this?

**Comment by michelleb-stripe** [comment]
@thorsten-stripe and @arekkubaczkowski Let me get back to you on this.

**Comment by michelleb-stripe** [comment]
We have this on our list to look at, but I am not sure I will get to it this week.

**Comment by michelleb-stripe** [comment]
> the first thing is that accentColor now changes the section titles color, @michelleb-stripe is it intentional?
This does intentionally change the section title colors

> accentColor probably should change the spinner color (I haven't found any different way to set it tho)
From the code it looks like setting the accentColor should set the spinner color.  

Let me know if you are seeing anything different @arekkubaczkowski, and if there are any other parts to this issue that I am missing.

**Comment by arekkubaczkowski** [comment]
I've checked this again and it works properly within the latest library version

**Comment by benomatis** [comment]
@arekkubaczkowski sorry, what is working properly exactly? The initial points were:

1. Android: 3DS progress spinner color
  **Question**: have we exposed a separate setting that would control the color of the spinner?

 2. Android: The section titles under the 3DS2 complete authentication take the color of the main backgroundColor (which is supposed to be iOS only?) when opened
  **2 Questions**: a) are the section titles supposed to take the color of the main backgroundColor at all? b) Has there been a documentation change added that corrected this value being iOS only?

**Comment by arekkubaczkowski** [comment]
>Android: 3DS progress spinner color
Question: have we exposed a separate setting that would control the color of the spinner?

According to recent @michelleb-stripe answer it's intentional. @michelleb-stripe any chance to split it to two separate params?

>The section titles under the 3DS2 complete authentication take the color of the main backgroundColor (which is supposed to be iOS only?) 

I haven't noticed such behavior, can you check it again if it still occurs within the latest version?

>are the section titles supposed to take the color of the main backgroundColor at all

section titles colors are set based on `accentColor` at the moment

**Comment by benomatis** [comment]
@arekkubaczkowski Sorry, which option defines the spinner color? I understand nothing is exposed to do that, it just has the default purple.

I'm testing now the rest...

**Comment by arekkubaczkowski** [comment]
> Sorry, which option defines the spinner color? I understand nothing is exposed to do that, it just has the default purple.

`accentColor` is responsible for that

**Comment by benomatis** [comment]
@arekkubaczkowski I cannot test this, it's opening in a webview instead of the customized screen - why is that? Has anything changed that requires a certain setting to be set in order to avoid opening the webview?

**Comment by benomatis** [comment]
@arekkubaczkowski further to my previous comment about no custom screen, but instead the webview appearing, I only found one sentence in the doc related to it and it says "To automatically dismiss the webview when authentication is finished, configure a custom URL scheme or universal link and set your scheme in the urlScheme parameter."

- but the problem is that I don't see the webview not closing, that part is working fine, I simply don't want the webview to appear at all, otherwise all my settings I applied above will be ignored entirely.

**Comment by arekkubaczkowski** [comment]
@benomatis there are cards which supports 3ds or 3ds2, where only 3ds2 allows to display custom view, you can use these cards from this link https://stripe.com/docs/testing#three-ds-cards  to test it.

**Comment by benomatis** [comment]
@arekkubaczkowski That helped indeed, and I can confirm `accentColor` fix both issues. Thank you.
