### ISSUE TITLE
Question: 3D Secure flow auto dismiss browser

### ISSUE THREAD

**Issue by vigzmv** [stripe/stripe-react-native#190]
**Describe the bug**
After 3DS Authenticating in webview, the page stays at "Authentication Complete".
In the docs [here](https://stripe.com/docs/payments/3d-secure), at the bottom, it mentions something about a return_url.
> 3D Secure authentication must be completed for the payment to be successful. Triggers the challenge flow using a webview. You can check that your return_url dismisses the modal.

I suppose there is a way to pass an App scheme URL to automatically close the browser and go back to app. But I couldn't  find any reference to `return_url` in this codebase, so I don't know how to use it

Please help if auto close is possible now and if not, can a feature request be added? 
Thanks

**Comment by trag-stripe** [comment]
Adding @laurenoh-stripe to this issue ✅

**Comment by laurenoh-stripe** [comment]
This is all set! https://stripe.com/docs/payments/3d-secure#when-to-use-3d-secure
