### ISSUE TITLE
Features missing from tipsi-stripe

### ISSUE THREAD

**Issue by tgensol** [stripe/stripe-react-native#196]
Hi there,

I am trying to move from tipsi-stripe and I am "missing" some features : 

### CardField focusing

- An AutoFocus/focus function on the CardField component could be really cool. It will save some clicks to my user and by abtesting we saw that the conversion rate was better in the past
- Separated card number, cvc and expiration. We saw by doing abtesting, that your "credit card" component is not always understood, and we really liked to be able to have every inputs separated. Is it something possible ? ([like this](https://camo.githubusercontent.com/b12ec43c53f7081d820f522cd0e0ae55325abebd38d4ab0f9941d650faaa7892/68747470733a2f2f73332e67696679752e636f6d2f696d616765732f556e7469746c6564363265616538653032333466613132392e676966))

### ApplePay hiding

- It was possible to "**hide**" the apple Pay modal if an error was happening. We can only **presentApplePay**
- **isApplePaySupported** means that Apple Pay is enabled and a credit card is ready ? I used to have **deviceSupportsNativePay** and **canMakeNativePayPayments**

### Google Pay
- I used to have **deviceSupportsNativePay** and **canMakeNativePayPayments**, but now I cannot know if the user can pay with Google Pay now
- Android Pay native, without having to use your UI sheet

Really thanks a lot for this first version ! It works very well on my side for my first tests (but it is not yet on production where we have 100k transactions per month)

Thanks a lot for your time

**Comment by aakanksha-02** [comment]
Hey, is your Apple Pay implementation woking with this?

**Comment by aakanksha-02** [comment]
> Hey, yes ! I followed the example and not the doc

https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ApplePayScreen.tsx  You mean this example ?

**Comment by thorsten-stripe** [comment]
> An AutoFocus/focus function on the CardField component could be really cool. It will save some clicks to my user and by abtesting we saw that the conversion rate was better in the past

Would you mind opening a feature request for that?

> Separated card number, cvc and expiration. We saw by doing abtesting, that your "credit card" component is not always understood, and we really liked to be able to have every inputs separated. Is it something possible ? (like this)

We're tracking this feature here: https://github.com/stripe/stripe-react-native/issues/83

> It was possible to "hide" the apple Pay modal if an error was happening. We can only presentApplePay

This is being tracked here: https://github.com/stripe/stripe-react-native/issues/148#issuecomment-815697077

> isApplePaySupported means that Apple Pay is enabled and a credit card is ready ? I used to have deviceSupportsNativePay and canMakeNativePayPayments

Correct: "YES if the device is currently able to make Apple Pay payments via one of the supported networks. NO if the user does not have a saved card of a supported type, or other restrictions prevent payment (such as parental controls)." - https://stripe.dev/stripe-ios/docs/Classes/StripeAPI.html#/c:@M@Stripe@objc(cs)StripeAPI(cm)deviceSupportsApplePay 

> I used to have deviceSupportsNativePay and canMakeNativePayPayments, but now I cannot know if the user can pay with Google Pay now

Standalone Google Pay is not yet supported (tracked here: https://github.com/stripe/stripe-react-native/issues/9). Google Pay is currently only supported via the payment sheet integration: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#google-pay

> Android Pay native, without having to use your UI sheet

Would you mind outlining why you can't (or don't want to) use the payment sheet? It would give you the split fields that you desire as well as Google Pay support. Would love for you to evaluate this option and provide feedback! 

For all the folks that added a 👍 , could you outline which ask(s) your 👍 relates to? That would help us a lot, thanks 🙏

**Comment by thorsten-stripe** [comment]
@tgensol did you have a chance to evaluate if the new payment sheet could fit your needs? And if not, can you outline why/what you're missing? Thanks.

**Comment by tgensol** [comment]
Hi @thorsten-stripe ,

Not yet, I plan to do it today :) ! But the perfect flow for me is to have a separated button like Apple Pay, that open the Google Pay modal sheet

**Comment by thorsten-stripe** [comment]
@Yonom thank you for the feedback! As mentioned, standalone Google Pay support is being tracked here: https://github.com/stripe/stripe-react-native/issues/9

I'm going to close this issue out as I believe all mentioned asks are being traced in their own issues: https://github.com/stripe/stripe-react-native/issues/196#issuecomment-838734268

Please let me know if that isn't the case, thanks.

**Comment by DanGDroid** [comment]
> CardField focusing
An AutoFocus/focus function on the CardField component could be really cool. It will save some clicks to my user and by abtesting we saw that the conversion rate was better in the past

we actually preffer not to force Auto focuse (it can be good to set as an optional param),
because we have another InputText - Card Holder - before the Card Input
![Screenshot 2021-05-24 at 13 43 49](https://user-images.githubusercontent.com/10976856/119336243-18ac6680-bc96-11eb-9d91-087687e35710.png)

**Comment by thorsten-stripe** [comment]
@DanGDroid `autofocus` is `false` by default, so it only focuses if you set `autofocus` to `true`.

**Comment by anija** [comment]
tipsi-stripe allowed to get the Apple Payment token using paymentRequestWithNativePay (https://tipsi.github.io/tipsi-stripe/docs/paymentRequestWithNativePay.html).
Any chance to get the same feature?

**Comment by thorsten-stripe** [comment]
@anija this is being tracked here: https://github.com/stripe/stripe-react-native/issues/271

**Comment by anija** [comment]
> @anija this is being tracked here: #271

thank you!

**Comment by khenriksson** [comment]
Is there any way to check whether cards have been added for Google Pay? I suppose `initGooglePay` only checks whether it's possible to use Google Pay on the device, not whether it's configured? What I'm basically looking for is something resembling `canMakeNativePayPayments`.
