### ISSUE TITLE
Need to update the items property of presentApplePay()'s param from Stripe doc

### ISSUE THREAD

**Issue by aakanksha-02** [stripe/stripe-react-native#198]
I was trying to implement Apple Pay on react-native platform using [https://stripe.com/docs/apple-pay?platform=react-native](https://stripe.com/docs/apple-pay?platform=react-native).

For **presentApplePay()** method, the param should have **cartItems** property, not **items** as per [https://stripe.dev/stripe-react-native/api-reference/interfaces/applepay.presentparams.html](https://stripe.dev/stripe-react-native/api-reference/interfaces/applepay.presentparams.html)

I think it should be updated in the doc in Step 6 and 7 from the first link.

**Comment by trag-stripe** [comment]
Thanks for filing this issue @aakanksha-02 - adding a few minor notes for a new team member:

On the page: https://stripe.com/docs/apple-pay?platform=react-native

Update the following code snippets from `items` to `cartItems` as shown:

_Step 6 code snippet:_ 

<img width="428" alt="Apple_Pay" src="https://user-images.githubusercontent.com/47867685/118756019-04044480-b838-11eb-85b0-52e3dfb13dd5.png">

_Step 7 code snippet:_
<img width="435" alt="cart_items" src="https://user-images.githubusercontent.com/47867685/118756110-34e47980-b838-11eb-8146-3a4468d17e24.png">

**Comment by trag-stripe** [comment]
Adding @laurenoh-stripe to this issue ✅

**Comment by laurenoh-stripe** [comment]
This is all set! https://stripe.com/docs/apple-pay?platform=react-native
