### ISSUE TITLE
AutoFocus/focus function on CardField

### ISSUE THREAD

**Issue by tgensol** [stripe/stripe-react-native#199]
An AutoFocus/focus function on the CardField component could be really cool.

It will save some clicks to my user and by abtesting we saw that the conversion rate was better in the past

**Comment by tgensol** [comment]
**autoFocusOnLoad** would be great !

But being able to control the focus, would be  better for me

**Comment by anija** [comment]
Is the _autofocus_ field the prop intended for this? Because it seems it's not working.

**Comment by arekkubaczkowski** [comment]
@anija yes it should work, if you having any problems please create a separate issue and provide all needed information following bug report template
