### ISSUE TITLE
Android build is failing.

### ISSUE THREAD

**Issue by sahildeliwala** [stripe/stripe-react-native#203]
**Describe the bug**
Android build is failing with `yarn android`. getting error: `Could not find method buildFeatures() for arguments [build_pxtvtursd53qqug9358kg7m3$_run_closure1$_closure8@7f4be65d] on extension 'android' of type com.android.build.gradle.LibraryExtension.`

**To Reproduce**
1. install the plugin
2. run app on android: `yarn android`

**Expected behavior**
It should run the app.

**Screenshots**
![Screenshot from 2021-05-12 15-21-19](https://user-images.githubusercontent.com/10909011/117955887-211bad80-b336-11eb-8b8a-7121cda87687.png)

**Comment by arekkubaczkowski** [comment]
@sahildeliwala  which android studio version are you using?

**Comment by sahildeliwala** [comment]
@arekkubaczkowski this what my `android/build.graddle` has:
`ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlinVersion = '1.4.21'
    }`

**Comment by arekkubaczkowski** [comment]
can you also provide android gradle plugin version?

**Comment by sahildeliwala** [comment]
@arekkubaczkowski 
![Screenshot from 2021-05-12 17-21-27](https://user-images.githubusercontent.com/10909011/117970694-92fbf300-b346-11eb-95dd-233b0fa215fe.png)

**Comment by arekkubaczkowski** [comment]
yup, this is why this error occurs. `buildFeatures` is available from gradle plugin  >= 4.x, are you able to upgrade it?

**Comment by sahildeliwala** [comment]
@arekkubaczkowski It worked! Thank you very much!!!

**Comment by thorsten-stripe** [comment]
> yup, this is why this error occurs. `buildFeatures` which is used in our sdk is available from gradle plugin >= 4.x, are you able to upgrade it?

@arekkubaczkowski can you add this to https://github.com/stripe/stripe-react-native#android please?

**Comment by carlosq-ordering** [comment]
@arekkubaczkowski Si, how can I get the Android Gradle plugin version? and how can I upgrade it? thanks
