### ISSUE TITLE
Remove example from published package

### ISSUE THREAD

**Issue by michaelbayday** [stripe/stripe-react-native#204]
**Describe the bug**
I don't think the example should be included within the node_module. Perhaps this should be excluded when publishing? 

**Expected behavior**
Examples should be tested when cloning the repo not via the package installed within node_modules.

**Screenshots**
![image](https://user-images.githubusercontent.com/35093298/118012037-8014fe80-b305-11eb-94a0-4aa7c699b8d7.png)

**Additional context**

Context is I am trying to patch the package with patch-package this folder is giving me issues.

**Comment by michaelbayday** [comment]
For more context, the pods within the example folder use a symlink for the various React Native pods. Since i think it's a relative path and patch-package downloads the package in a `tmp` folder. this breaks it.
``ts
Error: ENOENT: no such file or directory, stat '/var/folders/hd/5w15dl7n0fvfvk0s78typbjc1mqh4n/T/tmp-66903Q0xaQMNPTFcv/node_modules/@stripe/stripe-react-native/example/ios/Pods/Headers/Private/DoubleConversion/double-conversion/bignum-dtoa.h'
```

**Comment by michaelbayday** [comment]
@thorsten-stripe  do you have a rough timeline on when this would be published? just so i can plan my next sprint on when to incorporate the public package

**Comment by arekkubaczkowski** [comment]
@michaelbayday I am working on it already

**Comment by thorsten-stripe** [comment]
@michaelbayday hoping to publish later today (Fri May 14th AM PT time)
