### ISSUE TITLE
`createPaymentMethod` not resolved with test card on live mode on android

### ISSUE THREAD

**Issue by aganov** [stripe/stripe-react-native#209]
**Describe the bug**
`createPaymentMethod` is not resolved when using stripe's test cards on `live` mode on `android`. 

**To Reproduce**

1. Create `CardField` input
2. Enter stripe's testing card eg: `4242 4242 4242 4242`
3. Submit card data with `const { paymentMethod, error } = await createPaymentMethod({ type: "Card", billingDetails })` method
4. Promise not resolved neither with error or exception.

**Expected behavior**
Promise to be resolved with `error` `{"code": "Failed", "message": "Your card was declined"}`

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 10
 - Version 0.1.0

**Comment by thorsten-stripe** [comment]
@aganov thanks for flagging this! Indeed a bug.
