### ISSUE TITLE
Payment sheet customisation

### ISSUE THREAD

**Issue by travisobregon** [stripe/stripe-react-native#211]
**Is your feature request related to a problem? Please describe.**
Is there a way to hide the Country and ZIP fields in the payment sheet or at least default to a specific country?

**Describe the solution you'd like**
An option within `initPaymentSheet` to disable Country/ZIP fields. I think this is similar to how `CardField` has `postalCodeEnabled`?

**Comment by thorsten-stripe** [comment]
This isn't possible, the payment sheet controls what data to collect, e.g. for high risk transactions it might collect additional billing details etc.

If this is important for you to control, you'd have to open feature requests on the [Android](https://github.com/stripe/stripe-android/issues/new/choose) and [iOS](https://github.com/stripe/stripe-ios/issues/new) SDKs
