### ISSUE TITLE
I get `Value for url cannot be cast from readablenativemap to string` when I try to init the implementation

### ISSUE THREAD

**Issue by carlosq-ordering** [stripe/stripe-react-native#214]
**Describe the bug**
After implement StripeProvider and try show the CardField component, the app crash with `value for url cannot be cast from readablenativemap to string`  message

**To Reproduce**
Here my code:

I add the provider:
![image](https://user-images.githubusercontent.com/77166972/118210675-cae36300-b438-11eb-8180-3f1876f48687.png)

And here the content of my `StripeCardForm`
![image](https://user-images.githubusercontent.com/77166972/118210734-e0f12380-b438-11eb-9a0a-a1af52b18fb0.png)

**Expected behavior**
Show the CardField component and put the credit card to init stripe workflow

**Screenshots**
![image](https://user-images.githubusercontent.com/77166972/118210189-1c3f2280-b438-11eb-958e-7d8415609796.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 API 29
 - OS: Android 10.0 x86
 - Version: 29

**Comment by thorsten-stripe** [comment]
This is related to https://github.com/stripe/stripe-react-native/issues/200#issuecomment-838852320 can you try the workaround mentioned there, please?
