### ISSUE TITLE
Unable to dismiss the keyboard using `CardField`

### ISSUE THREAD

**Issue by travisobregon** [stripe/stripe-react-native#222]
**Describe the bug**
There is no way to dismiss the keyboard (by pressing "Done", or taping away) using the `CardField` component from what I can tell. This is the same behavior in the example project as well.

**To Reproduce**
1. Use the `CardField` component on a screen
2. Tap into the field to open the keyboard

**Expected behavior**
A user can easily dismiss the keyboard.

**Comment by arekkubaczkowski** [comment]
Hi, thanks for flagging. 
Yeah it is because internal react-native behaviors work only with build-in TextInput component https://github.com/facebook/react-native/blob/174753600778675c8b0e7d341b6044192af68d00/Libraries/Components/ScrollView/ScrollView.js#L1380

In this case we have to handle it manually, so we need to track screen interactions and dismiss the keyboard if needed. To achieve this I propose to that stripe sdk will expose extra UI component which will take care of it. To use it you will have to wrap your entire screen where is the CardInput with our component.
cc @thorsten-stripe

**Comment by smeetagrawal** [comment]
Can anyone provide more information as how we dismiss the keyboard, because I am searching for it, is there any property or method we need to call in order to dismiss keyboard.

**Comment by arekkubaczkowski** [comment]
you have to wrap your screen with `<StripeContainer />` component

**Comment by smeetagrawal** [comment]
If I understand properly, you mean to say
- First I have to import StripeContainer component like this *import { StripeContainer } from "@stripe/stripe-react-native"*
- Then wrap screen with <StripeContainer /> like below

```
<StripeContainer>
	<SafeAreaView>
		<ScrollView>
			<View>
				<CardField
					postalCodeEnabled={false}
					placeholder={{
						number: "4242 4242 4242 4242",
					}}
					cardStyle={{
						backgroundColor: "#FFFFFF",
						textColor: "#000000",
					}}
					style={{
						width: "100%",
						height: 50,
						marginVertical: 30,
						borderWidth: 1,
						borderColor: "#000",
					}}
					onCardChange={(cardDetails) => {
						setCard(cardDetails);
					}}
					onFocus={(focusedField) => {
						console.info("focusField", focusedField);
					}}
				/>
			</View>
		</ScrollView>
	</SafeAreaView>
</StripeContainer>
```

**Comment by smeetagrawal** [comment]
But above code is not working and I am also not able to get StripeContainer from @stripe/stripe-react-native like below.
*import { StripeContainer } from "@stripe/stripe-react-native"*

Version "@stripe/stripe-react-native": "^0.1.2"

**Comment by thorsten-stripe** [comment]
@smeetagrawal `StripeContainer` has been added here (https://github.com/stripe/stripe-react-native/pull/260) and will be available starting v0.1.3. If you need it earlier, you can clone down the master branch and build and install the library locally: https://github.com/stripe/stripe-react-native/blob/master/CONTRIBUTING.md#install-library-as-local-repository

**Comment by aganov** [comment]
Is there any way to call `endEditing` on ios manually? Our use case involves custom bottom sheet (where `CardField` is rendered and we want to close the keyboard when bottom sheet is dismissed.

**Comment by cinnabarcaracal** [comment]
Does anyone have any ideas on how to dismiss the keyboard without the press triggering something else?

We have the CardField in a scrollview containing other payment methods (things like loyalty points), and if you click off to dismiss the keyboard it is very easy to accidentally swap the payment method for something else.

The best I can come up with so far is to track when the field is in use and disable the all of the other elements on screen

**Comment by thorsten-stripe** [comment]
@cinnabarcaracal thanks for outlining your workaround. I've copied this to the `onBlur` issue.

**Comment by johanjq** [comment]
Hi everyone! I'm still not able to resolve this, I've a modal with a TextInput from react-native and a <CardField /> coming from @stripe/stripe-react-native v0.1.4. When you focus the  <TextInput /> and then press somewhere else, the keyboard dismisses correctly. but this doesn't happen with the <CardField />. Is there any way to resolve this? I tried wrapping the view with a < StripeContainer /> but that didn't work.

Thanks so much everyone!

https://user-images.githubusercontent.com/35921850/133979529-75ea9742-a096-4293-9dc8-fa8b1ddfb6ee.mov

**Comment by edi** [comment]
Having the same issue. I'm unable to hide the keyboard. Not with `Keyboard.dismiss()`, not with `StripeContainer` .. not with anything.

**Comment by edi** [comment]
@johanjq You need to add `keyboardShouldPersistTaps="never"` to `<StripeContainer />` in order for the keyboard to get dismissed.

It defaults to `always`, which is wrong in my opinion.

**Comment by akandaurov** [comment]
> am also not able to get StripeContainer from @stripe/stripe-react-native like below. _import { StripeContainer } from "@stripe/stripe-react-native"_
> 
> Version "@stripe/stripe-react-native": "^0.1.2"
> 
> It will be good, If you can send any reference for dismissing keyboard when click outside of CardField, Because I am not able to get any working example yet.

It's just boolean
`<StripeContainer keyboardShouldPersistTaps={false}>`

**Comment by johnsonfash** [comment]
For bottomsheetmodal

Use the CardForm ref to control keyboard dismiss.

`
const cardRef = useRef<CardFormView.Methods>(null)
 const [cardFocus, setCardFocus] = useState(false);

 <Pressable
     onPress={() => {
        if (cardFocus) {
          cardRef.current?.blur()
          setCardFocus(false);
        }
      }}
 >
....other view components
    <Pressable onPress={() => {
          if (!cardFocus) {
            cardRef.current?.focus()
            setCardFocus(true)
          }
        }}>
          <CardForm ref={cardRef} style={styles.CardForm} />
        </Pressable>
</Pressable>

`
