### ISSUE TITLE
Android: CardField component has limited width for card number on first focus

### ISSUE THREAD

**Issue by michaelbayday** [stripe/stripe-react-native#230]
**Describe the bug**
On first focus, card number has a fixed width which is very small. If the user advances to zip/cvc and returns they have access to the "correct width"

**To Reproduce**
1. Render CardField on Android
2. Start typing card number
3. On first focus, card number has a fixed width. If the user advances to zip/cvc and returns they have access to the "correct width"

**Screenshots**
On first focus
![image](https://user-images.githubusercontent.com/35093298/118513807-e8d6ef00-b6e8-11eb-8353-5c39a49348ea.png)

After advancing and returning back to card number input
![image](https://user-images.githubusercontent.com/35093298/118515704-78c96880-b6ea-11eb-9f82-f9d70e8f913a.png)

**Smartphone (please complete the following information):**
- Android Simulator pixel 4

**Additional context**
```ts
          <CardField
            onCardChange={handleCardChange}
            style={{
              height: 56,
              width: '100%',
              alignItems: 'center',
            }}
            cardStyle={{
              backgroundColor: theme.BACKGROUND,
              textColor: theme.FOREGROUND,
              placeholderColor: theme.GREY3,
              borderColor: theme.GREY2,
              borderWidth: 1,
              borderRadius: 4,
              fontSize: 16,
            }}
            placeholder="Card"
            postalCodeEnabled={false}
          />
```

**Comment by thorsten-stripe** [comment]
@michaelbayday are you on the latest version of master? And can you provide a screenrecording of this? It's looking fine on my end:

https://user-images.githubusercontent.com/23213994/118615336-32abfc00-b7f3-11eb-8f63-9600f849d090.mp4

**Comment by michaelbayday** [comment]
i am using version 0.1.1

https://user-images.githubusercontent.com/35093298/118902936-825df680-b8cb-11eb-892c-035f6c7ee013.mov

**Comment by michaelbayday** [comment]
https://user-images.githubusercontent.com/35093298/118903001-9e619800-b8cb-11eb-8ef2-a0c3ad6204f1.mov

**Comment by thorsten-stripe** [comment]
@michelleb-stripe might this be related to the short custom placeholder? @michaelbayday maybe try to add some whitespace to your placeholder, e.g.

```js
placeholder={{
          number: 'Card               ',
        }}
```

**Comment by michaelbayday** [comment]
looks like that was the issue. On an unrelated note, for some reason the card icon only shows in dark mode and not in light mode any ideas on this one?

**Comment by michaelbayday** [comment]
still feels like that is a bug since the UI width shouldnt be dependent on the length of the placeholder (since it is a placeholder)

**Comment by thorsten-stripe** [comment]
Yes, definitely a bug, but not reproducible on a native android app and therefore must be related to some RN quirk and that will take time to debug I'm afraid. Can you live with the placeholder whitespace workaround for the time being?

**Comment by michaelbayday** [comment]
Yep that’s fine. Thank you for the help. Should I submit another but for the asset?

**Comment by thorsten-stripe** [comment]
> Should I submit another but for the asset?

Yes, please, ideally with some screenshots. Thanks.

**Comment by agustinfece** [comment]
The same happens to me, the card field is not fitting the screen width.

**Comment by arekkubaczkowski** [comment]
it seems like it's not reproducible within the latest version. Please reopen if anyone having this issue and provide steps to reproduce
