### ISSUE TITLE
Alternative for `confirmCardSetup` method?

### ISSUE THREAD

**Issue by carlosq-ordering** [stripe/stripe-react-native#231]
What alternative can I use for this method ?

E.G:

```JS
const result = await stripe.confirmCardSetup(
  requirements,
  {
    payment_method: {
     card,
     billing_details: {
      name: `${user.name} ${user.lastname}`,
      email: user.email,
      address: user.address
     }
    }
   }
 )
```

**Comment by paulasjes-stripe** [comment]
Hi there, you'd use `confirmSetupIntent` which is available as part of the `useConfirmSetupIntent` or `useStripe` hook. More info here: https://stripe.com/docs/payments/save-and-reuse#react-native-collect-card-details
