### ISSUE TITLE
3D Secure not initiating iOS

### ISSUE THREAD

**Issue by MattHorriganSunrise** [stripe/stripe-react-native#233]
3D secure is not initiating maybe I am doing something not correct but these are my steps.

I have setup 3D secure params through the `initStripe` method:
```js
threeDSecureParams: {
  backgroundColor: '#FFFFFF', // iOS only
  timeout: 5,
  label: {
    headingTextColor: '#0000',
    headingFontSize: 13,
  },
  navigationBar: {
    headerText: '3d secure',
  },
  footer: {
    // iOS only
    backgroundColor: '#FFFFFF',
  },
  submitButton: {
    backgroundColor: '#000000',
    cornerRadius: 12,
    textColor: '#FFFFFF',
    textFontSize: 14,
  },
},
```
When I try to complete my payment and it requires additional authorization I then go through the process of `confirmPayment` passing the client secret and type `Card`:

```js
const paymentIntent = await confirmPayment(clientSecret, {
  type: 'Card',
});
```
I receive `You must provide card details` error, I tried passing in a cardDetails object that looks like the same object from the `onChangeCard` cardDetails object, but I still get the same error. I don't know what I am missing, the docs are very limited for this feature and looking at #177 passing cardDetails is deprecated.

iOS 13.0

**Comment by arekkubaczkowski** [comment]
for handling card payments we provide dedicated CardField component, you don't need to care about passing card data to the payment because we do it under the hood.
Please follow our docs for more details https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom

**Comment by MattHorriganSunrise** [comment]
@arekkubaczkowski Yes I am using the CardField Component, but sometimes it's not used for already saved CC info.

**Comment by arekkubaczkowski** [comment]
so you are saying that you see this error only when the payment requires additional 3ds authorization or I misunderstood smth? Can you provide gist of your code so I can check what can be wrong with your implementation?

**Comment by MattHorriganSunrise** [comment]
Thanks for the fast response @arekkubaczkowski ,

Yes I want to initiate 3D secure when required, this happens when I get an error from our BE that looks something like this:
```
{
  "type": "payment_intent",
  "message": "The card was declined as the transaction requires authentication.",
  "requires_action": true,
  "failures": [
    {
      "line_item_id": 7834,
      "client_secret": "secret_redacted"
    }
  ],
}
```
once I receive this error I want to trigger the 3D secure, so then I go through the process of `confirmPayment` to try and trigger this, whenever I do with this:
```js
const paymentIntent = await confirmPayment(clientSecret, {
  type: 'Card',
});
```
I receive this error:
```
"error": {"code": "Failed", "message": "You must provide card details"}}
```
The cardField component is only used when adding new cards to our system, so I am currently using a card I added that was a test for the 3D secure process but this is the Component we use to add cards:
```js
<CardField
  postalCodeEnabled
  placeholder={{
    number: 'Card Number',
  }}
  cardStyle={styles.cardStyles(theme)}
  style={styles.containerStyles}
  onCardChange={(cardDetails) => {
    paymentFormStore.card = {
      ...cardDetails,
    };
  }}
/>
```
Maybe I don't have to use the `confirmPayment` method to trigger the 3D secure? Or is there another way?

**Comment by arekkubaczkowski** [comment]
I think you made couple of mistakes 
two things:
1. if you want to finalize the payment on the server side you should follow this doc: https://stripe.com/docs/payments/accept-a-payment-synchronously

2. if you want to process the payment using card, CardField component should be on the same screen as the payment is processing, when it's not, we cannot reference to the card details

**Comment by MattHorriganSunrise** [comment]
Yes finalizing the payments is handled via server side the method I wanted to use was actually:
```js
await handleCardAction(clientSecret);
```
but this also displays the same error as I was having before:
```
"error": {"code": "Failed", "message": "You must provide card details"}}
```
is this because the CardField component is not on the same screen?

**Comment by MattHorriganSunrise** [comment]
Thank you, yes we are doing the payments server side. The method I was looking for was `handleCardAction`
