### ISSUE TITLE
Initial installation issues

### ISSUE THREAD

**Issue by cinnabarcaracal** [stripe/stripe-react-native#235]
We are switching over from tipsi-stripe.

Our app is currently using RN version 0.61.4 (this is probably the source of our issues).

### iOS:

- had to add the Fix.swift file (and bridging header) to solve an error regarding SWIFT_VERSION.
- had to bump minimum ios target
- had to switch to the latest xcode
- had to add some post-install logic in the Podfile to workaround issue with our RN version and the latest xcode

### Android:

- had to upgrade gradle
- had to bump com.android.tools.build:gradle dependency
- had to bump minSdkVersion
- had to bump kotlinVersion

## Current Issue

The above was enough to get the app to build with @stripe/stripe-react-native as a dependency.

Once I start importing components (e.g. StripeProvider), metro fails with the following error:

```
error: bundling failed: SyntaxError: /Users/m/Workspace/polygon-mobile/staged/node_modules/@stripe/stripe-react-native/src/hooks/useStripe.tsx: Unexpected token (1:12)

> 1 | import type {
    |             ^
  2 |   PaymentMethodCreateParams,
  3 |   ApplePay,
  4 |   PaymentSheet,
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓░░░░░ 70.8% (1501/1784), failed.
```

I think that some combination of the RN version we are using or some missing babel/ts config is causing metro to choke on the ts files exported by this dependency. We haven't had any dependencies that try to get us to run ts before, they have always contained the transpiled js.

I tried patching the entrypoint in your package.json to advertise the transpiled code (and adjusting the import statement in our app's js code) but that just gives me a different error:

```
error: bundling failed: Error: Unable to resolve module `../../package.json` from `node_modules/@stripe/stripe-react-native/lib/module/components/StripeProvider.js`:

None of these files exist:
  * package.json
  * node_modules/@stripe/stripe-react-native/lib/package.json/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/m/Workspace/polygon-mobile/staged/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.2% (1781/1796), failed.
```

I'm afraid I know what the answer is going to be, but can you think of any way we might be able to get this to work without updating RN?

**Comment by arekkubaczkowski** [comment]
Hi, you're right
babel started supporting this feature since `7.9.0v`  https://github.com/babel/babel/pull/11171
so probably you should upgrade your babel version or install plugin which allows to transpilation of this syntax.
https://babeljs.io/docs/en/babel-plugin-transform-typescript

**Comment by arekkubaczkowski** [comment]
and thanks for flagging, it's worth to add this information to the README

**Comment by cinnabarcaracal** [comment]
thanks @arekkubaczkowski 

I have tried installing that plugin (or the superset of typescript presets) to no success. I have also tried various combinations and degrees of babel dependency upgrades, but there was always some issue (loss of jsx support, metro locking up and so on). I'm now halfway through upgrading the app to the latest RN (and oh boy is that pbxproj file a monster when the automated upgrade tool fails). I'm not sure whether to close this issue now or wait until the upgrade is done to check that the issue is definitely resolved (but pretty sure it will be). Very happy to go with whatever you and/or the other maintainers prefer

**Comment by thorsten-stripe** [comment]
Thanks for the update, @cinnabarcaracal. I'll close this out for now as we've added the additional requirements to the README, but please reopen or file a new issues should it not get resolved. Thanks.

**Comment by simawn** [comment]
I managed to fix this issue by upgrading @babel/core and @babel/runtime to 7.9.0 (Upgrading to the latest version 7.14.5 didn't work. Using babel-plugin-transform also didn't work)

I'm using React Native 0.61.5, the previous version of both core and runtime were 7.6.2

**Comment by Sofianio** [comment]
@cinnabarcaracal can you please share how you fixed the SWIFT_VERSION issue?
