### ISSUE TITLE
Unable to back to the App after 3D Payment Auth ( Bancontact )

### ISSUE THREAD

**Issue by ThomasPnt** [stripe/stripe-react-native#238]
Once the payment has been accepted by the bank whether on IOS or Android the return to merchant button does not work.
I tested the return_url from my phone when I put myapp://safepay it redirects me to my application. Except that since when I do the confirmPayment the confirmation screen appears, since it is still in the app and does not open a new app the return to merchant is maybe just supposed to close the screen?

**Comment by thorsten-stripe** [comment]
Please use the bug report template to report sufficient information for us to investigate: https://github.com/stripe/stripe-react-native/issues/new?assignees=&labels=&template=bug_report.md&title=
