### ISSUE TITLE
Return to merchant button doesn't work

### ISSUE THREAD

**Issue by ThomasPnt** [stripe/stripe-react-native#240]
**Describe the bug**
Once I do the confirmPayment we go through the bank which validates our payment, but once we get to the redirection page with the return to merchant button nothing happens when we click on it.

On android we get "cannot open this type of links".

**To Reproduce**
my wrapper 

<StripeProvider publishableKey={config.stripe} urlScheme='myapp' setUrlSchemeOnAndroid={true}>...

my function on CardField complete : 

const res = await confirmPayment(client_secret, {
    type: 'Bancontact',
    billingDetails,
});

**Expected behavior**
When you click on the return to merchant it closes the screen and returns to the application or it redirects to the application.

**Comment by thorsten-stripe** [comment]
What does your `StripeProvider` look like? Are you setting the `urlScheme` prop?

**Comment by ThomasPnt** [comment]
My `StripeProvider` looks like this:
`<StripeProvider publishableKey={config.stripe} urlScheme='myapp' setUrlSchemeOnAndroid={true}>`

In IOS I added the scheme
```
<key>CFBundleURLSchemes</key>
<array>
<string>myapp</string>
</array>
```

**Comment by thorsten-stripe** [comment]
Have you implemented deep linking? https://stripe.com/docs/payments/bancontact/accept-a-payment?platform=react-native#react-native-handle-deep-linking

**Comment by ThomasPnt** [comment]
@thorsten-stripe Thanks for your help, I obviously made a mistake in the IOS setup and I was testing the Linking with the open debugger which seems to cause some problems.

Now I can make the return on the application as I wished, as well on android as on IOS, my friend who tested on Android had maybe a too old phone
