### ISSUE TITLE
iOS: Fails when I try install the dependency

### ISSUE THREAD

**Issue by carlosq-ordering** [stripe/stripe-react-native#241]
I try to install `@stripe/stripe-react-native` in ios, already run `pod install` in ios folder, but I'm getting this error

Any idea?

![image](https://user-images.githubusercontent.com/77166972/118894514-6447c480-b8d2-11eb-9dfe-aa29d9b49c82.png)

Thanks.

**Comment by Santix11** [comment]
If your target is IOS 11 or above in your Podfile and it still does not work then perhaps check this out. 

https://github.com/stripe/stripe-react-native/issues/45#issuecomment-762927330

**Comment by carlosq-ordering** [comment]
> If your target is iOS 11 or above in your Podfile and it still does not work then perhaps check this out.
> 
> [#45 (comment)](https://github.com/stripe/stripe-react-native/issues/45#issuecomment-762927330)

Still failing

**Comment by thorsten-stripe** [comment]
@arekkubaczkowski is this potentially related to appium https://github.com/appium/appium/issues/12511 ?

**Comment by arekkubaczkowski** [comment]
> @arekkubaczkowski is this potentially related to appium [appium/appium#12511](https://github.com/appium/appium/issues/12511) ?

@carlosq-ordering can you check whether you have two build directories in ios folder (Debug and Release)? If so, you need to remove one of them (probably Release if you want develop the app)

**Comment by carlosq-ordering** [comment]
> @carlosq-ordering can you check whether you have two build directories in ios folder (Debug and Release)? If so, you need to remove one of them (probably Release if you want develop the app)

I only try to run `yarn react-native run-ios`, I'm not try to generate a IPA file

**Comment by arekkubaczkowski** [comment]
yup but I thought that you could run e2e tests which generates release build, so you didn't?

**Comment by carlosq-ordering** [comment]
> yup but I thought that you could run e2e tests which generates release build, so you didn't?

No, I only install the dependency, I do my code and when I try to run-ios, this fails, I already try with this https://github.com/stripe/stripe-react-native/issues/45#issuecomment-762927330, but still failing.

FYI, in android all works fine

**Comment by arekkubaczkowski** [comment]
@carlosq-ordering are you sure that when you uninstall stripe sdk it works again?

**Comment by carlosq-ordering** [comment]
> @carlosq-ordering are you sure that when you uninstall stripe sdk it works again?

I am only using this dependency
![image](https://user-images.githubusercontent.com/77166972/118996925-41f78a80-b956-11eb-881a-c100df01a281.png)

**Comment by arekkubaczkowski** [comment]
this is what I am asking for, could you make sure it's works without this dependency?
you can also try to run your project via xcode instead of cli, but make sure you open .xcworkspace file

**Comment by carlosq-ordering** [comment]
> this is what I am asking for, could you make sure if it works without this dependency?
> you can also try to run your project via xcode instead of cli, but make sure you open .xcworkspace file

Oh, my project works without this dependency `@stripe/stripe-react-native`, But when I install it to implement my stripe requirements, I can run the app with run-ios command, is the same if I try to run with xcode.

Exist some alternative to install or make it work on Ios?

**Comment by thorsten-stripe** [comment]
Have you followed all the https://github.com/stripe/stripe-react-native#troubleshooting steps? Especially 

Open Xcode and create a new Swift file to the project (File > New > File > Swift), give it any name (e.g. Fix.swift) and create a bridging header when prompted by Xcode.

**Comment by jimji1005** [comment]
I tried to implement on a fresh project with `rn init`. this is 64.1, with Xcode 12.5, deployment target 11

plain implementation with out bridging header build generates 9 errors

after implementing the bridging header there are 5 errors
```
Undefined symbols for architecture x86_64:
  "type metadata accessor for (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType", referenced from:
      closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in (extension in Stripe):__C.NSURLSession.stp_performDataTask(with: Foundation.URLRequest, completionHandler: (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> (), retryCount: Swift.Int) -> () in libStripe.a(URLSession+Retry.o)
  "protocol conformance descriptor for __C.NSOperationQueue : Combine.Scheduler in Foundation", referenced from:
      lazy protocol witness table accessor for type __C.NSOperationQueue and conformance __C.NSOperationQueue : Combine.Scheduler in Foundation in libStripe.a(URLSession+Retry.o)
  "(extension in Foundation):__C.NSScanner.scanUpToString(Swift.String) -> Swift.String?", referenced from:
      static Stripe.STPPhoneNumberValidator.formattedRedactedPhoneNumber(for: Swift.String, forCountryCode: Swift.String?) -> Swift.String in libStripe.a(STPPhoneNumberValidator.o)
  "(extension in Foundation):__C.NSOperationQueue.SchedulerTimeType.init(Foundation.Date) -> (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType", referenced from:
      closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in (extension in Stripe):__C.NSURLSession.stp_performDataTask(with: Foundation.URLRequest, completionHandler: (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> (), retryCount: Swift.Int) -> () in libStripe.a(URLSession+Retry.o)
  "_swift_getOpaqueTypeConformance", referenced from:
      associated type witness table accessor for Body : SwiftUI.View in Stripe.PaymentSheet.PaymentButton<A> : SwiftUI.View in Stripe in libStripe.a(PaymentSheet+SwiftUI.o)
      associated type witness table accessor for Body : SwiftUI.View in Stripe.PaymentSheet.FlowController.PaymentOptionsButton<A> : SwiftUI.View in Stripe in libStripe.a(PaymentSheet+SwiftUI.o)
      associated type witness table accessor for Body : SwiftUI.View in Stripe.PaymentSheet.FlowController.ConfirmButton<A> : SwiftUI.View in Stripe in libStripe.a(PaymentSheet+SwiftUI.o)
      associated type witness table accessor for SwiftUI.ViewModifier.Body : SwiftUI.View in Stripe.PaymentSheet.PaymentSheetPresentationModifier : SwiftUI.ViewModifier in Stripe in libStripe.a(PaymentSheet+SwiftUI.o)
      associated type witness table accessor for SwiftUI.ViewModifier.Body : SwiftUI.View in Stripe.PaymentSheet.PaymentSheetFlowControllerPresentationModifier : SwiftUI.ViewModifier in Stripe in libStripe.a(PaymentSheet+SwiftUI.o)
      associated type witness table accessor for Body : SwiftUI.View in Stripe.ConfirmPaymentPresentationModifier<A, B> : SwiftUI.ViewModifier in Stripe in libStripe.a(STPPaymentConfirmation+SwiftUI.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here are my specs
```System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 3.12 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```


This is the library search path listed
<img width="678" alt="Screen Shot 2021-05-21 at 5 02 41 PM" src="https://user-images.githubusercontent.com/5834998/119208292-5d49bf00-ba56-11eb-9d51-8d8006f6cf3c.png">

**Comment by jimji1005** [comment]
I found the issue on my build.

I was a bit puzzled by the troubleshoot step of removing entry from LIBRARY_SEARCH_PATHS, because when I looked at my Xcode project no such path existed. 

But I do see the paths there.... however just not in the entry.
<img width="1114" alt="Screen Shot 2021-05-21 at 10 52 06 PM" src="https://user-images.githubusercontent.com/5834998/119216275-acf4ae80-ba87-11eb-91c5-a750241b6803.png">


What I did is to open the xcode project file with an editor and just search for LIBRARY_SEARCH_PATHS, and remove the entire thing from it. This is what I saw.
```
LIBRARY_SEARCH_PATHS = (
  "\"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)\"",
  "\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"",
  "\"$(inherited)\"",
);
```

remove
```
   "\"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)\"",
  "\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"",
```

Once thats removed the build started to work

**Comment by arekkubaczkowski** [comment]
it's already described here https://github.com/stripe/stripe-react-native#troubleshooting

**Comment by jimji1005** [comment]
> it's already described here https://github.com/stripe/stripe-react-native#troubleshooting

Correct, it just wasn't clear it had to be done via an editor instead of using Xcode, since via Xcode the entry did not show up.

**Comment by tareq0065** [comment]
> it's already described here https://github.com/stripe/stripe-react-native#troubleshooting

library search paths doesn't work. You need to change it manually by editing the Xcode project file. can you update the README please? I did not get the paths in the library search paths list in the Xcode.

**Comment by kfiggins** [comment]
> it's already described here https://github.com/stripe/stripe-react-native#troubleshooting

This answer is what helped me solve it. https://github.com/stripe/stripe-react-native/issues/45#issuecomment-762927330. The troubleshooting piece was a great hint but I had to dive through issues till I found this and was able to get my build to work. Thanks!
