### ISSUE TITLE
[Android] error: cannot find symbol new StripeSdkPackage()

### ISSUE THREAD

**Issue by rahu431** [stripe/stripe-react-native#242]
projectrootpath.../android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:35: error: package com.reactnativestripesdk does not exist
import com.reactnativestripesdk.StripeSdkPackage;
                               ^
projectrootpath.../android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:133: error: cannot find symbol
      new StripeSdkPackage(),
          ^
  symbol:   class StripeSdkPackage
  location: class PackageList

After install package getting this above error when I try to run the project using this "npx react-native run-android"

RN Version: 0.63.1
Node Version: v15.11.0
NPM Version:  7.6.3

**Comment by arekkubaczkowski** [comment]
@rahu431  can you share a bit more context of this error? It seems to be compilation error but it's hard to figure out what is the cause based on this information

**Comment by scaralfred** [comment]
Having the same issu. Did you find a solution?

**Comment by rahu431** [comment]
@scaralfred No am not able to find the solution, used alternative option with tipsi-stripe.
@arekkubaczkowski what kind of information specifically and how should I can get that, pls let me know so that I can share it.

**Comment by arekkubaczkowski** [comment]
just copy paste a bit more around of this error, or you can try to run it via android studio and take the logs from logcat

**Comment by thorsten-stripe** [comment]
Closing out as stale. Feel free to reopen with more information.
