### ISSUE TITLE
No signature of method Error

### ISSUE THREAD

**Issue by franciscofernandez0** [stripe/stripe-react-native#244]
Hello!
The library throws the attached error when runing on Android emulator
Just install last version and run "npm run android"

![Sin título](https://user-images.githubusercontent.com/20439136/118979383-b17e7180-b978-11eb-9188-6e4286c1d1d2.png)

This is happening on Android Emulator with SDK 29 and react-native 0.63.4
Any idea?

**Comment by arekkubaczkowski** [comment]
can you check the version of android gradle plugin and upgrade to  >= 4.x if it's lower already?

**Comment by franciscofernandez0** [comment]
Yes, that was the problem.
added:
        classpath("com.android.tools.build:gradle:4.0.0")
to build.gradle and now is working. Thanks!

**Comment by arekkubaczkowski** [comment]
cool, I have just added this information to the README https://github.com/stripe/stripe-react-native/pull/246
