### ISSUE TITLE
[Expo] NativeStripeSdk in StripeProvider.tsx is undefined using initStripe

### ISSUE THREAD

**Issue by carl-passnfly** [stripe/stripe-react-native#249]
**Describe the bug**
```js
initStripe({
  publishableKey: 'pk_test_xxx',
}).then(r => console.log(r)).catch(e => console.error(e));
```
Using the preceding code to initialize stripe in a componentDidMount in an expo project causes a:

 `TypeError: Cannot read property 'initialise' of undefined (StripeProvider.tsx:42)` error.

**To Reproduce**
```js
import { initStripe } from '@stripe/stripe-react-native';

class App extends Component {
  state = {};

  componentDidMount = () => {
  
    initStripe({
      publishableKey: 'pk_test_xxx',
    }).then(r => console.log(r)).catch(e => console.error(e));
  };

  // render() {...}
}

```
**Expected behavior**
NativeStripeSdk to be compiled and working in the package import.

**Desktop (please complete the following information):**
 - OS: Ubuntu desktop 
 - Version: 20.04

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - OS: Android Pixel 4 API level 30

**stripe-react-native version:**
0.1.1

**Comment by thorsten-stripe** [comment]
How are you running your expo project? Expo support is still quite limited, see https://github.com/stripe/stripe-react-native#expo

We're working with the Expo team to make this smoother, you can follow along here: https://github.com/stripe/stripe-react-native/issues/3

**Comment by carl-passnfly** [comment]
> How are you running your expo project? Expo support is still quite limited, see https://github.com/stripe/stripe-react-native#expo
> 
> We're working with the Expo team to make this smoother, you can follow along here: #3

Hi @thorsten-stripe! I'm running the project as a "managed workflow". Like you said the expo support does still seem quite limited. I'll maybe try my chances to eject the project to a bare workflow instead. Generally I'd like to avoid it since there would be no other reason than getting compatibility with this project. I have already been playing around with options to see if it's caused by babel or anything similar configurable.

**Comment by cruzach** [comment]
hi @carl-passnfly ! Good news for you- Expo managed workflow support for `@stripe/stripe-react-native` has landed 😄 

If you download the newest versions of Expo Go from the stores, you should be good to go
