### ISSUE TITLE
Document How To Use Confirm Payment More Clearly

### ISSUE THREAD

**Issue by DZuz14** [stripe/stripe-react-native#250]
From looking at the documentation, I still have no idea how to include things like expiration and card number in the confirmPayment method. I've looked through all of the types in [PaymentMethods](https://github.com/stripe/stripe-react-native/blob/4396df7/src/types/PaymentMethods.ts#L66), and see no mention of a card number or expiration field.

What I'd like to see, is more documentation on how to handle this, perhaps a full real world example. It's not clear to me how the card number and expiration are sent in any of the example snippets, or [here ](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&lang=node&ui=custom#react-native-submit-payment)as well.

**Comment by thorsten-stripe** [comment]
For PCI compliance reasons the SDK retrieves the card details from the `CardField` component: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom#react-native-create-checkout-page

Example can be found in the example folder: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/WebhookPaymentScreen.tsx

**Comment by Jpoliachik** [comment]
This definitely confused me as well, especially because the documentation says specifically to 
> save the details in the component’s state

https://stripe.com/docs/payments/save-during-payment

**Comment by NamNP06** [comment]
Hello @thorsten-stripe . I feacd problem : **CARD DETAIL NOT COMPLETE **  when 1 screen has two component Strip . please how to fix ? thank you !

**Comment by arekkubaczkowski** [comment]
@NamNP06 you cannot use two Stripe components on one screen at the same time. What is the purpose of this approach?

SDK hand over data from the component to the specific payment methods under the hood and it's not possible to handle multiple components.

For the next time, please create a separate issue.
