### ISSUE TITLE
ld: library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by jonasgroendahl** [stripe/stripe-react-native#251]
**Describe the bug**
I'm following the Troubleshooting guide since I'm experiencing the case described there but whenever I remove everything in the Search paths, it can't find libraries, first one it complains about is the DoubleConversion lib. I get the error:

```
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I however keep everything in the library search path (default), I get the error as described in the troubleshooting section:

```
Undefined symbol: type metadata accessor for (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType

Undefined symbol: protocol conformance descriptor for __C.NSOperationQueue : Combine.Scheduler in Foundation

Undefined symbol: (extension in Foundation):__C.NSScanner.scanUpToString(Swift.String) -> Swift.String?

Undefined symbol: (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType.init(Foundation.Date) -> (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType

Undefined symbol: _swift_getOpaqueTypeConformance
```

I have removed node_modules, pods, podfile.lock, cleaned build folder but always the same error :(

System:

"react-native": "0.64.1",
Xcode 12.5
MacOS big sur
"@stripe/stripe-react-native": "^0.1.1",

**Comment by arekkubaczkowski** [comment]
Did you follow all steps from https://github.com/stripe/stripe-react-native#troubleshooting?

**Comment by jonasgroendahl** [comment]
I was confused by the documentation, I ended up deleting all things instead of just ${inherited}. this video helped me adding stuff back: https://www.youtube.com/watch?v=XvaqW0lQL18
