### ISSUE TITLE
<unknown>:0: error: module map file Stripe/Stripe.modulemap' not found

### ISSUE THREAD

**Issue by AliShirzad** [stripe/stripe-react-native#253]
I am trying to archive my project. I build with emulator and it is working fine. 

my device is macbook pro M1

Error:
<img width="798" alt="Screenshot 2021-05-21 at 14 42 48" src="https://user-images.githubusercontent.com/9092949/119161400-89713a00-ba6e-11eb-832a-ef8181618222.png">

**Comment by arekkubaczkowski** [comment]
@AliShirzad can you make sure that you have set `deployment target >= 11` in your project configuration?
<img width="394" alt="Zrzut ekranu 2021-05-24 o 15 08 16" src="https://user-images.githubusercontent.com/18654447/119352470-046e6680-bca2-11eb-82f5-a06774066fa8.png">

**Comment by arekkubaczkowski** [comment]
and actually it should be the same as in your Podfile

**Comment by wesvance** [comment]
I'm getting this same error - I have confirmed my deployment target is >= 11, specifically 12.

**Comment by wesvance** [comment]
Switching to yarn, deleting node_modules and package-lock.json and relying on yarn.lock, cleaning the build, closing XCode and reopening fixed the issue for me. 😊

**Comment by flora8984461** [comment]
Hi, I am still having this issue, and I confirmed my deployment target is >= 11, and did all the steps to clean cache. 
And I can run it with yarn run ios, but not with Xcode.

My react-native is 0.64.1, "@stripe/stripe-react-native" is "0.2.0".
Xcode is v12.5 

Any help is really appreciated.

**Comment by the-habu** [comment]
I have the same problem, please give advice or maybe reopen the ticket.

**Comment by joartola** [comment]
Having the same issue, did not work using yarn and de prerequisite of delete node_modules etc

**Comment by joartola** [comment]
> Hi, I am still having this issue, and I confirmed my deployment target is >= 11, and did all the steps to clean cache. I have done https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios, then I can run it with yarn run ios, but not with Xcode.
> 
> My react-native is 0.64.1, "@stripe/stripe-react-native" is "0.2.0".
> Xcode is v12.5. My device is also M1.
> 
> Any help is really appreciated.

Could you resolve the issue?

**Comment by joartola** [comment]
Could solve the issue with the following config:

![image](https://user-images.githubusercontent.com/31057068/129596869-0a995c58-dc23-41e1-932c-b572b77c1b44.png)

` post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" //ADD THIS LINE
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
     end
  end`

**Comment by flora8984461** [comment]
@joartola Thanks for checking and offering me advice. I did not try last week, I think before I tried this:
```
post_install do |installer| react_native_post_install(installer) installer.pods_project.targets.each do |target| target.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" //ADD THIS LINE config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0' end end end
```
and it claimed another error, I'll try again this week to see. 

I have another working project which is ejected from expo, the react-native version is "~0.63.4", and react version is  "react": "16.13.1", stripe version is"@stripe/stripe-react-native": "^0.1.4". And this working one does not need EXCLUDED_ARCHS and IPHONEOS_DEPLOYMENT_TARGET in Podfile.

Anyone who has errors can check the versions too.

The current project I am doing is brand new without expo. I suspect it's the version issue. I plan to downgrade react-native from 0.64.1 to 0.63.4, and downgrade"@stripe/stripe-react-native" from "0.2.0" to 0.1.4. to see if it works.

I will post updates here later.

**Comment by markl-vesper** [comment]
also seeing this xcopde build error after adding swift file and created bridging header

My react-native is 0.65.1,
"@stripe/stripe-react-native" is "0.2.0".
Xcode is v12.5. My device is Intel

Im going to try @flora8984461 and dowengrade to see if I can spot the exact clash

**Comment by markl-vesper** [comment]
what I managed to get working was RN62.3 & stripe RN 0.1.1

it at least build helloWord app after adding stripe and fixing the various ios issues as described in readme.md

only thing I would add is that its best to search for lines to remove by removing ""$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"", line from LIBRARY_SEARCH_PATHS in project.pbxproj file

dont bother trying to find the lines inside xcode

and do not forget to create swift file for bridging header

unfortunatly trying the same fixes in RN65.1 doesn't help ios build yet. still severe issues

**Comment by Steven-lunchCo** [comment]
I was having a similar problem and running xcode in rosetta fixed it. found the idea here https://stackoverflow.com/a/68852414/16640688

**Comment by aakanksha-bb** [comment]
It was all working on my machine earlier with Xcode 12.1
I recently updated to Xcode 13.1, and I'm getting this issue again. 

Any help is really appreciated.

**Comment by mygit1313** [comment]
> also seeing this xcopde build error after adding swift file and created bridging header
> 
> My react-native is 0.65.1, "@stripe/stripe-react-native" is "0.2.0". Xcode is v12.5. My device is Intel
> 
> Im going to try @flora8984461 and dowengrade to see if I can spot the exact clash

Abbe saale
