### ISSUE TITLE
ApplePayButton cornerRadius

### ISSUE THREAD

**Issue by robert-nash** [stripe/stripe-react-native#258]
ApplePayButton doesn't appear to expose any way of setting cornerRadius, it would be useful if it did. https://developer.apple.com/documentation/passkit/pkpaymentbutton/2999416-cornerradius

**Comment by thorsten-stripe** [comment]
This will be part of the v0.1.3 release later this week

**Comment by robert-nash** [comment]
Brilliant, thank you
