### ISSUE TITLE
Apple Pay Docs - Server side confirmation code snippet is native

### ISSUE THREAD

**Issue by ImPDP** [stripe/stripe-react-native#264]
React Native Apple Pay's documentation has Swift/Objective-C code snippet in the payment intent section. Can anyone please check and update with js codes?

**Comment by thorsten-stripe** [comment]
Thanks for flagging @ImPDP. The server-side confirmation flow is not available in React Native. We will remove the tab from the docs, thanks. Please use the "Payment Intents API" path instead.

**Comment by laurenoh-stripe** [comment]
This has now been updated! https://stripe.com/docs/apple-pay?platform=react-native
