### ISSUE TITLE
Card Details Not Resetting Properly. Able To Submit With Empty CardField.

### ISSUE THREAD

**Issue by DZuz14** [stripe/stripe-react-native#265]
## Issue
While I was doing some error validation for my applications checkout screen, I noticed that after entering information into a CardField component, I could then erase all of that information, and still submit and get a successful payment. If this isn't clear, the steps to reproduce listed below should clarify things.

## Steps To Reproduce
I know most of the Stripe test information can be chosen at random, but ill make it easy on you, and leave what I entered into the component. Since you guys are on the ones that built this library, I would assume you would have the following setup before trying to reproduce:

- `useConfirmPayment and CardField imported`
- `A button to trigger the payment`
- `A method that fetches a clientSecret, which will then be used in confirmPayment`

1. Fill out a single CardView component with the following details:
  ```
  #: 4242424242424242
  mm/dd: 09/29
  cvc: 359
  ```
2. Erase all of the information you have just entered.
3. Submit the payment.
4. It should process successfully.

## Code
Here is a snippet of what I am using to process a payment. I have a button that when pressed, triggers the submitPayment function. From speaking to someone previously on here, it is my understanding that somehow behind the scenes the card details are extracted from the CardField component.

Don't be confused by our API route `/payment/token`, behind the scenes its calling `stripe.paymentIntents.create`, and passing back the client secret.

```
/**
 * @function getClientSecret
 */
const getClientSecret = async () => {
  try {
    const res = await axiosClient.post('/payment/token', {
      productId: route.params.productId,
      saveCard: false,
    });

    return res.data.result.clientSecret;
  } catch (e) {
    console.log('Stripe getClientSecret Error', e);
  }
};

/**
 * @function submitPayment
 */
const submitPayment = async () => {
  try {
    const clientSecret = await getClientSecret();

    setApiError('');

    const { paymentIntent, error } = await confirmPayment(clientSecret, {
      type: 'Card',
    });

    if (error) {
      handleStripeError(error);
    } else if (paymentIntent) {
      handleSuccess(paymentIntent);
    }
  } catch (e) {
    console.log('Stripe submitPayment Error', e);
  }
};

...other code

<CardField
  postalCodeEnabled={true}
  cardStyle={cardFieldStyles}
  style={{ height: 45, marginTop: 10, marginBottom: 10 }}
/>

...other code
```

## Other Notes
By logging the cardDetails via the CardField's prop, `onCardChange`, I see that after filling the CardField, and then erasing the information, some of the properties are not reset. Here is a console.log of what `onCardChange` shows after everything has been erased.

```
{
  last4: '4242',
  expiryMonth: '',
  expiryYear: '',
  postalCode: '',
  brand: 'Visa',
  complete: true
}
```

The expiration month and year do in fact reset, but last4, brand, and complete do not.

**Comment by thorsten-stripe** [comment]
This has been fixed in https://github.com/stripe/stripe-react-native/releases/tag/v0.1.2 please update to that version
