### ISSUE TITLE
[Android] : presentPaymentSheet() is not opening stripe payment sheet in android

### ISSUE THREAD

**Issue by hpvnarola** [stripe/stripe-react-native#267]
**Describe the bug**
presentPaymentSheet() is not opening the stripe payment sheet in android when passing direct charge payment intent client secret. it's working fine in iOS.

**server-side**
```
// Direct charge
const payment_intent = await payment.getPaymentIntent(
    {
        payment_method_types: ['card'],
        amount: parseFloat(amount) * 100,
        currency: 'usd',
        application_fee_amount: tools.calculateApplicationFee(amount),
    }, 
    {
        stripeAccount: user.stripe_connect_id,
    }
);
console.log(payment_intent.client_secret, '------');
return res.status(200).send({
    status: 200,
    message: 'Checkout data fetched successfully.',
    data: {
        paymentIntent: payment_intent.client_secret,
        customer: customer_id,
    }
});
```
**client-side(react-native -> android)**
```
console.log(data);
const { error, paymentOption } = await initPaymentSheet({
    customerId: data.customer,
    paymentIntentClientSecret: data.paymentIntent,
});

const { error, paymentOption } = await presentPaymentSheet({
    clientSecret: data.paymentIntent,
});
```

**Expected behavior**
The payment sheet should open in android as well like in IOS.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.7 Catalina]
 - Browser [chrome, safari]
 - Version [node: v15.2.1, react-native: 0.63.4, "@stripe/stripe-react-native": "^0.1.2"]

**Smartphone (please complete the following information):**
 - Device: [Moto G5S]
 - OS: [Android 8.1.0 API 27]
 - Browser [stock browser, safari]

**Comment by thorsten-stripe** [comment]
Are you setting `stripeAccountId` to be the same value as `user.stripe_connect_id` in your `StripeProvider` component? https://stripe.dev/stripe-react-native/api-reference/interfaces/stripeproviderprops.html#stripeaccountid

**Comment by hpvnarola** [comment]
Yes, I'm doing the same, I wrapped the children components inside StripeProvider, below you can see the code for the `StripeProvider` setup.
Below also have attached the video for what happens when invoking stripe payment in android. 
It's a live project and we are facing a problem with android please help us with this.

Video link: https://drive.google.com/file/d/1NCW12oiso_InVKEEZ3VU3h3uGJpxK1il/view?usp=sharing

```
<StripeProvider
    publishableKey={Tools.getStripeKeys().PUBLISHABLE_KEY}
    stripeAccountId={params?.churchDetail?.stripe_connect_id}>
    <View style={styles.container}>
        <KeyboardAwareScrollView
            style={styles.wrapper}
            bounces={false}
            keyboardShouldPersistTaps={'handled'}
            keyboardOpeningTime={Number.MAX_SAFE_INTEGER}
            showsVerticalScrollIndicator={false}>
            <View style={styles.card}>
                <Input
                    placeholder={t('add_donation_plan.amount')}
                    style={[styles.subjectInput, { marginBottom: 0 }]}
                    placeholderColor={Colors.GRAY}
                    value={amount}
                    onChangeText={(text) => {
                        setAmount(text);
                        setAmountError('');
                    }}
                    keyboardType={'numeric'}
                    errorMsg={amountError}
                />
            </View>
            <Button
                label={t(
                    'church_details_profile.donate',
                ).toUpperCase()}
                style={styles.button}
                onPress={onPressDonate}
                isLoading={isLoadingSetupCheckout}
            />
        </KeyboardAwareScrollView>
    </View>
</StripeProvider>
```

**Comment by thorsten-stripe** [comment]
@hpvnarola thank you for reporting this, and sorry for the inconvenience! I've just merged the fix into master and am hoping to release it within v0.1.3 by end of week. If you need it earlier, you can clone down master branch and build the library locally: https://github.com/stripe/stripe-react-native/blob/master/CONTRIBUTING.md#install-library-as-local-repository

**Comment by RajeshRRathod** [comment]
I used master branch "@stripe/stripe-react-native": "https://github.com/RajeshRRathod/stripe-react-native#master", in package.json 
but still payment sheet dialog open just one second & its close automatic in android
pls give me any suggestion for this issue, its urgent

**Comment by hpvnarola** [comment]
Hi @thorsten-stripe  
Thanks for resolving the issue and provide quick support

We are waiting for the latest release with fixes

**Comment by NuHunter** [comment]
I ran into the same problem when I used flutter  ->  presentPaymentSheet() is not opening stripe payment sheet in android

**Comment by RONAKDHOLARIYA** [comment]
<StripeProvider ### merchantIdentifier="merchant.identifier" publishableKey="publishableKey"></StripeProvider>

Adding merchantIdentifier my app work fine in adnroid

**Comment by Mihai-github** [comment]
Hi, I've ran into the same problem after the paymentSheet appearing for the first time if we close it and try to make it appear for the second time we have no error but it won't appear and we have no idea how to debug this issue at least...

Maybe someone has any idea?

**Comment by arslanafzal077** [comment]
payment sheet dialog open with loading for just one second & its close automatic in ios simulator

**Comment by mannu2saini** [comment]
I have same issue presentPaymentSheet is not appearing on android device.So update to
stripe-react-native version 0.23.1 and pass  **merchantDisplayName**  with **initPaymentSheet** then it works for me.

```
  const {error}  = initPaymentSheet({
      merchantDisplayName:appConstant.userName,
      customerId: this.state.customerId,
      customerEphemeralKeySecret: this.state.ephemeralKey,
      paymentIntentClientSecret: this.state.clientSecretkey,
    })
```

**Comment by mannu2saini** [comment]
I have same issue presentPaymentSheet is not appearing on android device.So update to stripe-react-native version 0.23.1 and pass merchantDisplayName with initPaymentSheet after that it works for me.
  const {error}  = initPaymentSheet({
      merchantDisplayName:appConstant.userName,
      customerId: this.state.customerId,
      customerEphemeralKeySecret: this.state.ephemeralKey,
      paymentIntentClientSecret: this.state.clientSecretkey,
    })

**Comment by saad9624-tribalScale** [comment]
Just add merchantDisplayName under initPaymentSheet , it will open the modal in android.

**Comment by ankitk-nimblechapps** [comment]
![Screenshot_2023-02-06-13-29-59-94_a40c374f801420dce36ea483382aa15e](https://user-images.githubusercontent.com/77725221/216917175-6d5bd924-135a-447e-9b74-f0b79dbc4da5.jpg)
while calling  initpaymentSheet method app crashed with these error in android, please help me with these issue.
