### ISSUE TITLE
Make Displaying Error Messages Easier

### ISSUE THREAD

**Issue by DZuz14** [stripe/stripe-react-native#269]
Is it possible to make displaying API errors to the user easier? The Stripe API does provide error messages that are descriptive enough to what the actual problem is, but it takes some string manipulation in order to get the pretty printed version of them.

For example, here is my code that will set an error message above the submit button of my payment screen.

```
if (Platform.OS === 'android') {
  const msg = error.message
    .slice(error.message.lastIndexOf(':') + 1)
    .trim();

  setApiError(msg);
} else if (Platform.OS === 'ios') {
  //
}
```

The error that is returned from confirmPayment looks like this:
```
{"code": "Failed", "message": "Request-id: req_csD9cEwwzXR4FQ com.stripe.android.exception.CardException: Your card was declined."}
```

I also can't be certain what the error object looks like for iOS devices (_I don't have one available at the moment to test it_), so I am not handling the error at this moment.

Is there anyway we could get a cleaner version, that's cross platform, and simply gives us what the error was? Something like this:

```
{"code": "Failed", "message": "Your card was declined."}
```

**Comment by arekkubaczkowski** [comment]
it will be handled here https://github.com/stripe/stripe-react-native/issues/206
