### ISSUE TITLE
How to scale the CardField fontSize ?

### ISSUE THREAD

**Issue by AlixH** [stripe/stripe-react-native#275]
I'd like to scale the CardField fontSize to have a proper size on all devices (iPhone, iPad, etc)
I am using the https://github.com/nirsky/react-native-size-matters library to scale my UI. When using it inside the cardStyle object, it does not work on the fontSize property.

**Comment by thorsten-stripe** [comment]
Please provide code snippets and screenshots

**Comment by AlixH** [comment]
iPhone UI
<img width="503" alt="Screenshot 2021-05-26 at 16 55 08" src="https://user-images.githubusercontent.com/32574035/119682434-2c490000-be43-11eb-8e96-21fbe3cac4ae.png">
iPad UI
<img width="756" alt="Screenshot 2021-05-26 at 16 55 03" src="https://user-images.githubusercontent.com/32574035/119682439-2d7a2d00-be43-11eb-9913-0f0c3b35233f.png">


```
<CardField
        cardStyle={{
          backgroundColor: commonColor.buttonBg,
          textColor: commonColor.textColor,
          placeholderColor: commonColor.brandDisabledDark,
          cursorColor: commonColor.textColor,
          fontSize: scale(15) // The scale function is imported from 'react-native-size-matters'
        }}

        onCardChange={(details: CardFieldInput.Details) => setCardDetails(details)}
        postalCodeEnabled={false}
        style={style.cardFieldContainer}
      />
```

Note: I dont manage to use percentage either to scale the fontSize

**Comment by arekkubaczkowski** [comment]
@AlixH  what is the output of `scale()` function?

**Comment by AlixH** [comment]
It's a number

**Comment by AlixH** [comment]
Ok I solved it, the scale function returned lots of decimals. Using Math.round did the job !

**Comment by AlixH** [comment]
Would you know how to change the size of the icon on the left of the input ?

**Comment by thorsten-stripe** [comment]
@AlixH I don't think that's possible atm. Will need to look into that. Tracking here https://github.com/stripe/stripe-react-native/issues/299
