### ISSUE TITLE
Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk15on-1.54

### ISSUE THREAD

**Issue by jigartankhupp** [stripe/stripe-react-native#278]
**Describe the bug**
After installing stripe-react-native i got this error while running for android.

`@stripe/stripe-react-native` version is **0.1.2**

**To Reproduce**
1. `npm install @stripe/stripe-react-native`
2. `npm run android`

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
 - Memory: 392.79 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh

**SDKs:**
 - iOS SDK: Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
 - Android SDK: API Levels: 29, 30, Build Tools: 29.0.2, 30.0.3, System Images: android-30 | Google APIs Intel x86 Atom

**IDEs:**
 - Android Studio: 4.2 AI-202.7660.26.42.7322048
 - Xcode: 12.3/12C33 - /usr/bin/xcodebuild
 
**npmPackages:**
    react: 16.13.1 => 16.13.1 
    react-native: ^0.61.4 => 0.61.4
    @stripe/stripe-react-native: "^0.1.2"
    
**Additional context**
```
> Task :app:checkDebugDuplicateClasses FAILED
> Task :app:mergeDebugJavaResource FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
461 actionable tasks: 4 executed, 457 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk15on-1.54 (org.bouncycastle:bcprov-jdk15on:1.54) and jetified-bcprov-jdk15to18-1.68 (org.bouncycastle:bcprov-jdk15to18:1.68)
     Duplicate class org.bouncycastle.asn1.ASN1ApplicationSpecific found in modules jetified-bcprov-jdk15on-1.54 (org.bouncycastle:bcprov-jdk15on:1.54) and jetified-bcprov-jdk15to18-1.68 (org.bouncycastle:bcprov-jdk15to18:1.68)
     Duplicate class org.bouncycastle.asn1.ASN1ApplicationSpecificParser found in modules jetified-bcprov-jdk15on-1.54 (org.bouncycastle:bcprov-jdk15on:1.54) and jetified-bcprov-jdk15to18-1.68 (org.bouncycastle:bcprov-jdk15to18:1.68)
```

**Comment by jigartankhupp** [comment]
Found fix at native stripe-android github page.
[https://github.com/stripe/stripe-android/issues/3173#issuecomment-785116680](https://github.com/stripe/stripe-android/issues/3173#issuecomment-785116680)

Adding those configuration inside **android/app/build.gradle** solved issue.

**Comment by SudoPlz** [comment]
In case anyone is using both stripe sdk and reader sdk, take a look [here](https://github.com/square/reader-sdk-flutter-plugin/issues/103#issuecomment-1686906006)
