### ISSUE TITLE
[Android] Payment sheet have infinite loading when call `presentPaymentSheet` function

### ISSUE THREAD

**Issue by KalumDog** [stripe/stripe-react-native#281]
**Describe the bug**
Android bottom sheet have infinite loading when call `presentPaymentSheet` function

**To Reproduce**
1. Fetch payment params from server
2. Init payment sheet with `initPaymentSheet` function
3. call `presentPaymentSheet` function

**Expected behavior**
Payment sheet should have finite loading and present the card form

**Screenshots**
![Screen Shot 2564-05-28 at 10 44 30](https://user-images.githubusercontent.com/5292440/119926470-b0b19500-bfa1-11eb-8b94-70d86db9317b.png)

**Desktop (please complete the following information):**
 - OS: MacOs Catalina 
 - Version 10.15.7

**Smartphone (please complete the following information):**
 - Device: Simulator (Pixel 3 XL)
 - OS: Android
 - Version API 27

**Additional context**
-

**Comment by thorsten-stripe** [comment]
@KalumDog can you please provide your code? And does your cord work on iOS?

**Comment by KalumDog** [comment]
@thorsten-stripe 

I follow instruction from this https://stripe.com/docs/payments/accept-a-payment?platform=react-native&lang=node&ui=payment-sheet

Btw, It works on iOS

**Comment by thorsten-stripe** [comment]
@KalumDog we'll need some more information to dig into this. Are you using Stripe Connect? If so, maybe it's the same as https://github.com/stripe/stripe-react-native/issues/267 ?

If not, please provide your server-side and client-side code.

**Comment by KalumDog** [comment]
**Server Side**

`
let customer = await this.customerRepository.findOne({
      userId: user.id,
    })

if (!customer.stripeCustomerId) {
      const { id } = await this.stripeClient.customers.create()
      customer.setStripeCustomerId(id)
      customer = await this.customerRepository.save(customer)
    }

    const ephemeralKey = await this.stripeClient.ephemeralKeys.create(
      { customer: customer.stripeCustomerId },
      { apiVersion: '2020-08-27' },
    )

    const paymentIntent = await this.stripeClient.paymentIntents.create(
      {
        amount: totalAmount * 100,
        currency: 'eur',
        customer: customer.stripeCustomerId,
        metadata: {
          bookingId: booking.id,
        },
      },
    )

    return {
      paymentIntent: paymentIntent.client_secret,
      ephemeralKey: ephemeralKey.secret,
      customer: customer.stripeCustomerId,
      bookingId: booking.id,
    }`

**Client Side**

`
const initPayment = async (
   params,
    merchantDisplayName?: string
  ) => {
    try {
      setIsLoading(true)
      const resp = await checkoutApi(params)

      if (resp) {
        setpaymentParams(resp)
        const { error } = await initPaymentSheet({
          customerId: resp.customer,
          customerEphemeralKeySecret: resp.ephemeralKey,
          paymentIntentClientSecret: resp.paymentIntent,
          merchantDisplayName,
          customFlow: false,
        })

      }
    } catch (error) {
      console.log(`_fetchMyOrder error`, error.response)
    } finally {
      setIsLoading(false)
    }
  }

  const fillCardAndPay = async (onSuccess: () => void, onError: () => void) => {
    try {
      const { error } = await presentPaymentSheet({
        clientSecret: Config.STRIPE_SECRET_API_KEY,
      })

      if (error) {
        onError()
      } else {
        onSuccess()
      }
    } catch (error) {}
  }`

PS. try to add stipe account id on both server-side and client-side not working as well

**Comment by thorsten-stripe** [comment]
I think the issue is with 

```js
const { error } = await presentPaymentSheet({
clientSecret: Config.STRIPE_SECRET_API_KEY,
})
```

Here `clientSecret` needs to be the PaymentIntent's client secret, in your case `resp.paymentIntent`.

But I now realise that our parameter naming is not consistent across these methods, and the docs also don't help in making this clear. Thank you for flagging and providing your code!

**Comment by KalumDog** [comment]
@thorsten-stripe 

Thanks for your help.
