### ISSUE TITLE
apple pay: don't support this device(both simulator and real device)

### ISSUE THREAD

**Issue by jackyang1984** [stripe/stripe-react-native#282]
**Describe the bug**
after setting in apple developer and stripe dashboard, apple pay: the device don't support this device

**Expected behavior**
should be support apple pay

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 0.1.2

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS10

**Comment by thorsten-stripe** [comment]
Please provide screenshots and detailed reproduction steps.

**Comment by thorsten-stripe** [comment]
Closing out as stale. Feel free to reopen with the above mentioned info.
