### ISSUE TITLE
[expo go] CardField component shows wrong card details on submit.

### ISSUE THREAD

**Issue by Vivekanand16** [stripe/stripe-react-native#283]
Iam using CardField component to get card details.

I entered all the details (card, expiry and cvc), then submitted the form and logged the card details, the card details are shown correctly.
Then I cleared all the fields and submitted the form again, this time in the log I can still see the last4 property holding previsouly enterd value.

```
const [card, setCard] = useState(null);

  const handlePayPress = async () => {
    Alert.alert(JSON.stringify(card));
  };

  return (
    <View>
      <CardField
        postalCodeEnabled={false}
        style={{
          width: "100%",
          height: 50,
          marginVertical: 30,
        }}
        onCardChange={(cardDetails) => setCard(cardDetails)}
      />
      <Button title="Pay" onPress={handlePayPress} />
    </View>
  );
```

**Expected behavior**
Correct card details needs to be shown.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/19799245/119963921-452dee80-bfc6-11eb-9221-728a16f5d8d0.jpg)

**Comment by thorsten-stripe** [comment]
This has been fixed in https://github.com/stripe/stripe-react-native/releases/tag/v0.1.2 but I guess it will take a while for this to propagate to the Expo Go client. However, I think when you build the app, it will use the latest version. Is that correct @cruzach ?

**Comment by cruzach** [comment]
That's correct, as long as you are building with [EAS Build](https://docs.expo.io/build/introduction/), the version of stripe-react-native specified in your package.json is what will be used in your final build
