### ISSUE TITLE
[Android] : When the first call to presentPaymentSheet() does not open the stripe payment sheet in android, but the second call is fine

### ISSUE THREAD

**Issue by Sirzs** [stripe/stripe-react-native#286]
When the first call to presentPaymentSheet() does not open the stripe payment sheet in android, but the second call is fine.
BTW,IOS is ok

SDK Version 0.1.2

**Comment by thorsten-stripe** [comment]
You need to wait for `initPaymentSheet` to resolve before calling `presentPaymentSheet`: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICompleteScreen.tsx#L55

**Comment by chengsam** [comment]
@Sirzs In my case, I need to wait for 1-2 seconds before presenting the payment sheet.
