### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by itsBhuviRana** [stripe/stripe-react-native#287]
This issue occur when i install the @stripe/stripe-react-native
=======================================================================================
* Where:
Build file '/home/kvch/admedic-mobile-app/node_modules/@stripe/stripe-react-native/android/build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':stripe_stripe-react-native'.
> Could not find method buildFeatures() for arguments [build_4f5811yusol8ahwjh2bw9vmo0$_run_closure1$_closure8@5ae828c7] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

====================================================================================
and my build.gradle file code
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by thorsten-stripe** [comment]
https://github.com/stripe/stripe-react-native/issues/203#issuecomment-839710098
