### ISSUE TITLE
[Android] presentPaymentSheet Dialog not open in android 

### ISSUE THREAD

**Issue by RajeshRRathod** [stripe/stripe-react-native#289]
**Describe the bug**
[Android] presentPaymentSheet Dialog just open one second & close it automatic in android 
You can see video : https://drive.google.com/file/d/1aL8GhOSA1J0TZoZiDGyLJe6DAOc_yAxe/view?usp=sharing

**To Reproduce**
1. Go to 'initPaymentSheet success without any error '
2. Click on 'click  pay button for presentPaymentSheet dialog'
4. See error : return this error  {"code":"Failed","message":""} by presentPaymentSheet

**Expected behavior**
I need to payment using google pay using this library  

**Desktop (please complete the following information):**
 - OS: Mac os catalina
 - Version [master and 1.0.2]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 7S]
 - OS: [9]
 
**Additional context**
=> My code integration below step 
step 1: **First initPaymentSheet success without any error** 
             const fetchPaymentSheetParams = async (cartDetails:any) => {

    const reqNew = {
      venueId,
      totalFeeCost: cartDetails?.totalCost,
      totalCost: cartDetails?.totalCost
    }
    // backend api call for get payment intent for stripe dialog    
    const { data } = await cartIntentPayment(reqNew);       

    setPaymentIntents(data.paymentIntent);
    setCustomers(data.customer);

    const { error } = await initPaymentSheet({
      customerId: data?.customer?.id,
      paymentIntentClientSecret: data?.paymentIntent?.client_secret,        
    });
    if (!error) {      
      console.log("initPaymentSheet success ");
      setLoading(true);
    }
  }
step 2: **visible google payment button & click on it** 

    const openPaymentSheet = async () => {
        try {           
          var secretKey = paymentIntents.client_secret;
          const { error } = await presentPaymentSheet({ clientSecret: secretKey });
    
          if (error) {       
            console.log('Error in openPaymentSheet ' + JSON.stringify(error));
          } else {
            console.log(`Success: `, 'Your order is confirmed!');
          }
    
        } catch (error) {
          console.log("error in stripe in google pay " + error);
        }
      }

step 3 : Payment sheet dialog open just 2-3 second  & its close automatic with below error

           {loading && Platform.OS === 'android' && <PaymentGoolePayButton
                  onPress={ openPaymentSheet }
                  customStyles={{ marginBottom: 20 }}
                />}
======== error after press PaymentGoolePayButton button =========== 
            {"code":"Failed","message":""}

**Comment by thorsten-stripe** [comment]
What's the value of `var secretKey = paymentIntents.client_secret;`? That needs to be the same as the value for `data?.paymentIntent?.client_secret`

**Comment by thorsten-stripe** [comment]
Closing out as stale. Feel free to reopen with the above details.
