### ISSUE TITLE
Android Crash - onActivityResult

### ISSUE THREAD

**Issue by JesperLekland** [stripe/stripe-react-native#297]
**Describe the bug**
Whenever we launch a separate activity for a result (e.g the camera) the app crashes upon resuming. 
I've managed to narrow it down to get a stack trace to 

>com.reactnativestripesdk.StripeSdkModule$mActivityEventListener$1

 but for some reason can't find the exact line it refers to. The detail error message states 

>Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data

**To Reproduce**
Start any Android activity for a result and finish it.

**Expected behavior**
App should not crash and Stripe not should not interfere with Intents not meant for Stripe.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
 - Device: Any physical device
 - OS: Android

**Additional context**
We've managed to reproduce in both a debug and a release build on numerous devices, albeit not in the emulator.
Error message `Failure delivering result ResultInfo{who=null, request=61110, result=0, data=null} to activity`

**Comment by michaelbayday** [comment]
kind of hacky but we solved this but patching the package and adding this to event listener
```
      if (!::stripe.isInitialized) return
```

am curious as to what stripe's devs would recommend though

**Comment by thorsten-stripe** [comment]
This has been fixed here (https://github.com/stripe/stripe-react-native/pull/255) and will be released in v0.1.3 later this week. If you need it earlier you can clone down the master branch and install the library locally: https://github.com/stripe/stripe-react-native/blob/master/CONTRIBUTING.md#install-library-as-local-repository

**Comment by JesperLekland** [comment]
Thank you @thorsten-stripe, great job! 

Is this partly a user error? Meaning that we have failed to correctly initialise Stripe and that Stripe related functionality might not work after the fix due to it not being initialised?
