### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe/stripe-react-native#3]
**Is your feature request related to a problem? Please describe.**
Expo is one of the most popular frameworks for developing React native applications. I'd expect we'll get a lot of requests about this.

**Describe the solution you'd like**
Is it possible to suppor expo without needing to eject? If so, how much work would that be?

**Describe alternatives you've considered**
If this isn't easily possible, can we add a "usage with Expo" guide?

**Additional context**
Currently, when I try to use `CardField` within an expo project I get “Invariant Violation: requireNativeComponent: "CardField" was not found in the UIManager.” which is related to the webview usage I beleive.

**Comment by aganov** [comment]
Is it possible to remove `@expo/config-plugins` as a hard dependency? It installs a lot of unnecessary packages in non-expo apps...

**Comment by cruzach** [comment]
hey @aganov, without the `config-plugins` dependency, it'd be difficult to give first class support `@stripe/stripe-react-native` for both the managed and bare workflows. The package itself is pretty minimal (about 0.6% of the size of the `stripe-react-native` package), and [this is the breakdown of that bundle](https://bundlephobia.com/result?p=@expo/config-plugins@1.0.30). Are there particular dependencies of config-plugins that concern you and you don't want to have in your project? 

If this is an absolute blocker for you right now, you could get rid of the transitive dependency in a post-install script


As for why it's included, you can read about what exactly config plugins **do** [here](https://docs.expo.io/guides/config-plugins/)

**Comment by westbrookj** [comment]
@thorsten-stripe I noticed on the calendar it showed a public beta for May 11th and a potential Expo Go patch release May 17th. I'm not seeing those on there anymore. Is there still a timeline laid out for when this project would be available for use in managed workflows either in a beta or official release?

**Comment by cruzach** [comment]
Expo managed workflow support has landed as of this morning 😄 

You will need to use the most recent versions of Expo Go from the stores (or locally on simulators installed with `expo install:client:[ios|android]`). 

You can refer to [these docs](https://docs.expo.io/versions/v41.0.0/sdk/stripe/) to get more specifics on what's supported in Expo Go, and what you'll need to build with EAS Build for. 

Closing this issue since Expo support has officially landed 🎉
