### ISSUE TITLE
CardField was not found in the UIManager

### ISSUE THREAD

**Issue by alvaroAsap** [stripe/stripe-react-native#300]
**Describe the bug**
When trying to render the CardField component, an error shows up: CardField was not found in the UIManager. 
_Note: This happens only for Android, it works fine for iOS._

**To Reproduce**
1. Initialize your app using `initStripe` inside App.js providing just the `publishableKey`, just like [here](https://github.com/stripe/stripe-react-native#stripe-initialization)
2. Follow the [Usage example](https://github.com/stripe/stripe-react-native#usage-example), to render your CardField component
3. Start your app in an Android emulator
4. Navigate to the screen of your App where CardField will render
5. See the error

**Expected behavior**
Show the card input field.

**Screenshots**
![image](https://user-images.githubusercontent.com/26637928/120332405-17e28880-c2c5-11eb-80af-b9b588234eed.png)

**Smartphone:**
 - Device: Nexus 6P API 30 (Android Virtual Device)
 - OS: Android 11

**Additional context**
node 12.22.1
react native 0.62.2

**Comment by thorsten-stripe** [comment]
Your repro steps work fine for me. This is the code I end up with based on your steps:

```js
import React, { useEffect } from 'react';
const publishableKey = 'pk_test_xxx';

import { initStripe } from '@stripe/stripe-react-native';

export default function App() {
  useEffect(() => {
    initStripe({
      publishableKey: publishableKey,
    });
  }, []);
  return <PaymentScreen />;
}

// PaymentScreen.ts
import { CardField, useStripe } from '@stripe/stripe-react-native';

function PaymentScreen() {
  const { confirmPayment } = useStripe();

  return (
    <CardField
      postalCodeEnabled={true}
      placeholder={{
        number: '4242 4242 4242 4242',
      }}
      cardStyle={{
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
      }}
      style={{
        width: '100%',
        height: 50,
        marginVertical: 30,
      }}
      onCardChange={(cardDetails) => {
        console.log('cardDetails', cardDetails);
      }}
      onFocus={(focusedField) => {
        console.log('focusField', focusedField);
      }}
    />
  );
}
```

What's your code?

**Comment by alvaroAsap** [comment]
Thanks for answering!

Unfortunately, that didn't solve my problem. I used your code but I'm having the same error message. I guess there may be something with the dependencies, since I was using [tipsi-stripe](https://github.com/tipsi/tipsi-stripe) before.

By the way, is there any guide about the flow of this library? Or at least something with the step-by-step API calls? I would appreciate that. 

I realized that in the example `useStripe` is being called, but never used. Is that right?

**Comment by thorsten-stripe** [comment]
Full docs here: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom and example: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/WebhookPaymentScreen.tsx

**Comment by iuliabarzan15** [comment]
@alvaroAsap Hi! I was having the same issue and I was able to fix it by adding the `<StripeProvider />` above `<CardField />`.

**Comment by alvaroAsap** [comment]
@iuliabarzan15 Hi, I tried what you suggested. Unfortunately, I wasn't lucky.

I am using initStripe because when I try to use <StripeProvider />, this [error](https://github.com/stripe/stripe-react-native#typeerror-null-is-not-an-object-evaluating-_nativestripesdkdefaultinitialise-on-android) shows up, despite I'm not using Expo.

**Comment by thorsten-stripe** [comment]
@alvaroAsap can you provide the content of your package.json please?

**Comment by alvaroAsap** [comment]
@thorsten-stripe sure!

[package.txt](https://github.com/stripe/stripe-react-native/files/6609127/package.txt)

**Comment by alvaroAsap** [comment]
Solved. Linking was the problem. I came up with a workaround because I was getting an error while running `react-native link @stripe/stripe-react-native`.

**Comment by thorsten-stripe** [comment]
@alvaroAsap any chance you could briefly outline how you resolved this issue. Someone else is running into this also https://github.com/stripe/stripe-react-native/issues/359
