### ISSUE TITLE
[confirmSetupIntent] Illegal Callback Invocation from native module when error is returned

### ISSUE THREAD

**Issue by aaronrondina5** [stripe/stripe-react-native#302]
**Describe the bug**
- When you enter a bad card in a CardField and attempt to confirm the setup intent, the iOS simulator raises the following error: 
illegal callback invocation from native module.  This callback type only permits a single invocation from native code

**To Reproduce**
1. Render a CardField
2. Enter a bad card
3. Save the card in state
3. Create a setup intent
4. Pass the client secret to `confirmSetupIntent`
5. Error occurs

**Expected behavior**
Error should simply display on my custom component. 

**Screenshots**
![Screen Shot 2021-06-01 at 5 10 14 PM](https://user-images.githubusercontent.com/21230847/120404996-67907680-c2fc-11eb-82ff-e176e3bb4da9.png)

![Screen Shot 2021-06-01 at 5 09 26 PM](https://user-images.githubusercontent.com/21230847/120404942-534c7980-c2fc-11eb-8f2d-8a39505a5745.png)

![Screen Shot 2021-06-01 at 5 10 22 PM](https://user-images.githubusercontent.com/21230847/120405005-6cedc100-c2fc-11eb-86bd-0665dac96561.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] emulator, iPhone 11
 - OS: [e.g. iOS8.1] iOS 14.3

**Additional context**
We previously used our own native modules to communicate with Stripe. We did not use tipsi or anything. This native module has been deleted

**Comment by thorsten-stripe** [comment]
I'm not able to reproduce this
![image](https://user-images.githubusercontent.com/23213994/120437369-92d59d00-c3b2-11eb-84ab-65a68f2dd040.png)

Can you maybe provide a link to your code?

**Comment by aaronrondina5** [comment]
`import {Stack} from '@mobily/stacks'
import {useNavigation, useRoute} from '@react-navigation/native'
import {CardField, CardFieldInput, confirmSetupIntent} from '@stripe/stripe-react-native'
import React, {useState} from 'react'
import {SafeAreaView, StyleSheet, View} from 'react-native'
import {CappuccinoButton} from 'src/components/widgets/button/CappuccinoButton'
import {useCreateSetupIntentMutation, useMyPaymentMethodsQuery} from 'src/graphql/types.generated'
import {RouteName} from 'src/navigation/Routes'
import {writePaymentMethodToCache} from 'src/service/Payment'
import {spacing} from 'src/theme/spacing'
import {ColorHex} from 'src/theme/ThemeConstants'

import {CappuccinoErrorText} from '../../widgets/text/CappuccinoErrorText'
import {ProfileFlow} from '../LoginScreen/LoginScreen'

interface AddCardScreenParams {
    flow: ProfileFlow
}

export const AddCardScreen = () => {
    const [card, setCard] = useState<CardFieldInput.Details | undefined>()
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | undefined>()

    const [createSetupIntent] = useCreateSetupIntentMutation()
    const {data: paymentMethodsData} = useMyPaymentMethodsQuery({
        fetchPolicy: 'cache-first'
    })

    const {goBack} = useNavigation()
    const route = useRoute()
    const {flow} = route.params as AddCardScreenParams
    async function saveMethod() {
        setLoading(true)
        try {
            const resCreateSetupIntent = await createSetupIntent()
            const clientSecret = resCreateSetupIntent.data!.createSetupIntent
            const {setupIntent, error: confirmSetupIntentError} = await confirmSetupIntent(clientSecret, {type: 'Card'})

            if (confirmSetupIntentError || !setupIntent?.paymentMethodId) {
                throw new Error(confirmSetupIntentError?.message || 'Card not created')
            }

            writePaymentMethodToCache(setupIntent.paymentMethodId, card!)
            goBack()
        } catch (e) {
            console.error(`Error adding card ${e}`)
            setLoading(false)
            setError(`${e}`)
        }
    }

    return (
        <SafeAreaView style={styles.container}>
            <Stack space={spacing.medium} align='center' style={styles.inner}>
                <CardField
                    postalCodeEnabled={true}
                    placeholder={{
                        number: '4242 4242 4242 4242'
                    }}
                    cardStyle={{
                        backgroundColor: '#FFFFFF',
                        textColor: '#000000'
                    }}
                    style={styles.cardFieldContainer}
                    onCardChange={(cardDetails: CardFieldInput.Details) => {
                        setCard(cardDetails)
                    }}
                />
                <View>
                    <CappuccinoErrorText>{error}</CappuccinoErrorText>
                </View>
                <View>
                    <CappuccinoButton size='large' mainText={loading ? 'Loading...' : 'Save'} onClick={() => saveMethod()} />
                </View>
            </Stack>
        </SafeAreaView>
    )
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: ColorHex.WHITE
    },
    inner: {
        paddingTop: 24
    },
    cardFieldContainer: {
        width: '100%',
        height: 50,
        marginVertical: 30
    }
})
`

**Comment by aaronrondina5** [comment]
seems to be a simulator only issue

**Comment by Seanmclem** [comment]
@thorsten-stripe if you handle the error with an Alert, as you've shown in the screenshot, then it will not throw the error. Otherwise it does. Experiencing it when canceling a `collectBankAccountForPayment` early
