### ISSUE TITLE
Class based component support

### ISSUE THREAD

**Issue by n3rd253** [stripe/stripe-react-native#304]
**Is your feature request related to a problem? Please describe.**

Im trying to port from using tipsi stripe and have a working class based implementation throughout.  Im only seeing function based component support?

**Describe the solution you'd like**
Class based component support

**Describe alternatives you've considered**
Not migrating to this SDK until required, instead of now.

**Comment by thorsten-stripe** [comment]
All needed functions are also directly exported `e.g. import { confirmPaymentMethod } from '@stripe/stripe-react-native';` usage of hooks is therefore optional.

**Comment by n3rd253** [comment]
@thorsten-stripe great thanks for the prompt reply.  Pardon my ignorance

**Comment by saeedtkh** [comment]
@thorsten-stripe: Thanks for your nice library. Ca you please put an example with class base here?
