### ISSUE TITLE
Android: A problem occurred evaluating project ':stripe_stripe-react-native'.

### ISSUE THREAD

**Issue by sheldoncoates** [stripe/stripe-react-native#307]
While attempting to run my react native Android app using the cli on Mac with:
`npx react-native run-android`

I get the following error in terminal:

`Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Sheldon/Desktop/smartgolfdealsapp/node_modules/@stripe/stripe-react-native/android/build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':stripe_stripe-react-native'.
> Could not find method buildFeatures() for arguments [build_eup7vw58a3viottlnadxg0hod$_run_closure1$_closure8@6c9c831e] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Sheldon/Desktop/smartgolfdealsapp/node_modules/@stripe/stripe-react-native/android/build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':stripe_stripe-react-native'.
> Could not find method buildFeatures() for arguments [build_eup7vw58a3viottlnadxg0hod$_run_closure1$_closure8@6c9c831e] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at makeError (/Users/Sheldon/Desktop/smartgolfdealsapp/node_modules/execa/index.js:174:9)
    at /Users/Sheldon/Desktop/smartgolfdealsapp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/Users/Sheldon/Desktop/smartgolfdealsapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/Sheldon/Desktop/smartgolfdealsapp/node_modules/@react-native-community/cli/build/index.js:186:9)`

Is this a bug or is there something I need to add to build.gradle? 

I've tried adding all of the follow to android>app>build.gradle but none of them resolved the issue:

`buildFeatures.dataBinding = true`
`   buildFeatures {
           dataBinding {
            enabled true
        }
    }`
` dataBinding {
        enabled = true
    }`
` buildFeatures {
        dataBinding = true
    }`

Gradle version: 6.2 
React-Native version: 0.64.1
OS: Big Sur 11.4
Android studio version: 4.2.1

**Comment by sheldoncoates** [comment]
When I build in Android studios it brings me to the file: `@stripe/stripe-react-native/android/build.gradle`

It bring me to:
` buildFeatures {
    viewBinding true
  }`

Maybe this needs to be changed?

**Comment by thorsten-stripe** [comment]
Duplicate, see https://github.com/stripe/stripe-react-native/issues/203#issuecomment-839710098
