### ISSUE TITLE
presentApplePay [Error: Payment not completed] @0.1.4

### ISSUE THREAD

**Issue by mohalhashem** [stripe/stripe-react-native#312]
I'm trying to use presentApplePay, but I keep getting this error. Here is exactly what I'm doing.

```

import { initStripe, useApplePay } from '@stripe/stripe-react-native';

await initStripe({
    publishableKey: stripePublishableKey,
    merchantIdentifier: applePayMerchantId,
    setUrlSchemeOnAndroid: true,
});

const data = {
    cartItems: [{
        label: 'Test',
        amount: 500,
        type: 'final',
    }],
    country: 'US',
    currency: 'USD',
};

const { presentApplePay } = useApplePay();

const { error, paymentMethod } = await presentApplePay(data);

console.log('apple pay error:', error);
console.log('apple pay method:', paymentMethod);
```

Here is the output:

```
LOG  apple pay error: [Error: Payment not completed]
LOG  apple pay method: undefined
```

 - Device: iPhone XS
 - OS: iOS14.6
 - @stripe/stripe-react-native version 0.1.4

Apple pay sheet wasn't presented at all, only got this error.

**Comment by thorsten-stripe** [comment]
For Apple Pay the amount needs to be a string: https://stripe.dev/stripe-react-native/api-reference/interfaces/applepay.cartsummaryitem.html#amount

**Comment by prodev-alt** [comment]
@thorsten-stripe I am still getting the same error.

const { error } = await presentApplePay({
      cartItems: [{ 
        label: 'Tip for Waitress',
        amount: parseFloat(totalAmount).toFixed(2) + ''
      }],
      country: 'US',
      currency: 'USD',
      requiredShippingAddressFields: ['emailAddress', 'phoneNumber'],
      requiredBillingContactFields: ['phoneNumber', 'name'],
    });

**Comment by thorsten-stripe** [comment]
Your above code is working fine for me:
![image](https://user-images.githubusercontent.com/23213994/121146826-e3497080-c872-11eb-9e8f-1d87b47d374e.png)
Have you tried refreshing/rebuilding your app?

**Comment by mohalhashem** [comment]
Thanks @thorsten-stripe I changed amount to string and it's working just fine now.

**Comment by jaaywags** [comment]
For me, I was passing in a display price ($1.99 USD) and didn't even realize. This helped me figure that out. Thanks!
