### ISSUE TITLE
TypeError: null is not an object (evaluating '_NativeStripeSdk.default.initialise') with React Native CLI

### ISSUE THREAD

**Issue by aliboyraz** [stripe/stripe-react-native#314]
**Describe the bug**
I'm having an issue while trying to initialize SDK on Android. SDK is not able to initialized so I am not able to start any transaction.

_TypeError: null is not an object (evaluating '_NativeStripeSdk.default.initialise'_

**PS: Same question had been asked multiple times and answer was related with upgrading Expo version however my app is not using Expo. Its React Native CLI**

    "@stripe/stripe-react-native": "^0.1.4",
    "react-native": "0.64.1",

**Screenshots**
<img width="356" alt="Screen Shot 2021-06-07 at 2 29 18 PM" src="https://user-images.githubusercontent.com/5192560/121001930-d78b7a80-c79c-11eb-8605-8060e4bde49c.png">

I tried to use **StripeProvider** but it also gives same error. 

**Smartphone (please complete the following information):**
 - Device: Huawei
 - OS: Android

**Additional context**
It works well with IOS simulator. Problem is on Android side.

**Comment by thorsten-stripe** [comment]
@aliboyraz mind quickly posting how you've resolved it? Might be helpful for others. Thanks.

**Comment by yayjkCC** [comment]
Can you please re open this? I am facing the same issue
