### ISSUE TITLE
Build android Fail :cannot find symbol  new StripeSdkPackage(),

### ISSUE THREAD

**Issue by ththugues44** [stripe/stripe-react-native#316]
Hello

When I try to compile my project just with stripe installation I got this error : 

[http://image.noelshack.com/fichiers/2021/23/2/1623104072-capture-d-ecran-du-2021-06-07-23-14-01.png](url)

`Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
1261 actionable tasks: 10 executed, 1251 up-to-date
/media/myDataOnlinux/project/fokogroup/YamoDating/YamoMobile/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:49: error: package com.reactnativestripesdk does not exist
import com.reactnativestripesdk.StripeSdkPackage;
                               ^
/media/myDataOnlinux/project/fokogroup/YamoDating/YamoMobile/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:208: error: cannot find symbol
      new StripeSdkPackage(),
          ^
  symbol:   class StripeSdkPackage
  location: class PackageList
Note: /media/myDataOnlinux/project/fokogroup/YamoDating/YamoMobile/android/app/src/debug/java/com/yamo/dating/cameroon3/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /media/myDataOnlinux/project/fokogroup/YamoDating/YamoMobile/android/app/src/main/java/com/yamo/dating/cameroon3/MainMessagingService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
`

Thanks for response sugestion

**Comment by arekkubaczkowski** [comment]
@ththugues44 this errors says that library is not installed or is installed incorrectly, can you provide more information about your env? versions of react-native, gradle plugin, android studio.
Also, can you provide steps how exactly did you install stripe library?

**Comment by thorsten-stripe** [comment]
Closing out as stale. Please reopen with additional information if needed.

**Comment by MuhammadShaheer97** [comment]
I get the same issue, it cannot find the library I'm guessing. I tried manually linking but this does not work. I have attempted to clean and rebuild with no success. I can see it's missing from my list of libs in the root folder in android. I can see webview, picker_picker and so on but no stripe. This info is just be trying to help/. 

first 

/Users/shaheer/VSCode/guest-app/guestApp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:29: error: package com.reactnativestripesdk does not exist
import com.reactnativestripesdk.StripeSdkPackage;
                               ^

second 

/Users/shaheer/VSCode/guest-app/guestApp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:116: error: cannot find symbol
      new StripeSdkPackage(),
          ^
  symbol:   class StripeSdkPackage
  location: class PackageList
