### ISSUE TITLE
How to accept on-session payments with saved payment method.

### ISSUE THREAD

**Issue by benipuri** [stripe/stripe-react-native#318]
Hi, I am migrating my App from Charges API to PaymentIntents and I think I am missing something very basic here but Is there any documentation about how to accept on-session payments with saved cards/payment methods. I checked Stripe's documentation about saving and reusing a payment method but it only explains about off-session payments and steps one should follow to start a recovery flow in case the off-session payment gets declined.

In my use case, and I think this is a very common use case, customer adds a card and pay for their order. I am saving this card for future use with **setup_future_usage : on-session**. Everything working perfectly fine when I try to add a new card and pay. The payment is processed perfectly, the authentication screen pops up wherever required, the payment method gets saved to the customer and so on.. But I can't understand how should I use this saved payment method later.

Any help will be highly appreciated.

**Comment by thorsten-stripe** [comment]
You can simply call `confirmPayment` with the saved payment method's id:

```js
const { error, paymentIntent } = await confirmPayment(clientSecret, {
    type: 'Card',      
    paymentMethodId,    
});
```

You can see an example of this here: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/CVCReCollectionScreen.tsx#L74-L80

Note that if you're not recollecting the cvc, you can just leave out the cvc param as shown above.

**Comment by benipuri** [comment]
Thank you so much for the prompt reply. 

Actually I already tried using `confirmPayment` in the exact same way as mentioned by you but I think I am not importing `confirmPayment` correctly.

My import statement. 

`import { initPaymentSheet, presentPaymentSheet, confirmPayment } from '@stripe/stripe-react-native';`

`initPaymentSheet` and `presentPaymentSheet` are working perfectly but `confirmPayment` is giving the error **Undefined is not a function..**

**Comment by benipuri** [comment]
Thank you for the quick clarification. `confirmPaymentMethod` did the work.
