### ISSUE TITLE
Android Gradle Build Failure?

### ISSUE THREAD

**Issue by n3rd253** [stripe/stripe-react-native#319]
**Describe the bug**
Receiving the following when trying to run react native on device
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/michaelsampsell/src/gruther/SnackDispatcherRN/node_modules/@stripe/stripe-react-native/android/build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':stripe_stripe-react-native'.
> Could not find method buildFeatures() for arguments [build_6svqzkt1jhqpls20ts85az2r6$_run_closure1$_closure8@605d9a76] on extension 'android' of type com.android.build.gradle.LibraryExtension.
```
**To Reproduce**
Install npm package
Run react-native run-android --deviceId=<mydeviceid>

**Expected behavior**
Build succeeds

**Smartphone (please complete the following information):**
 - Device: Galaxy S10

**Additional context**
implementation 'com.stripe:stripe-android:16.10.0'
"@stripe/stripe-react-native": "^0.1.2",

**Comment by thorsten-stripe** [comment]
Duplicate https://github.com/stripe/stripe-react-native/issues/203#issuecomment-839710098
