### ISSUE TITLE
[India account] payment not working all the way

### ISSUE THREAD

**Issue by manish-shukla01** [stripe/stripe-react-native#321]
**Describe the bug**
hi, i am trying out https://stripe.com/docs/payments/accept-a-payment?platform=react-native and i am able to integrate it mostly but i am not able to do a successful payment all the way.

it is opening the payment form. i am entering the test card number but then it gives an error saying there was an unexpected error. try again in few seconds. i have just followed the instructions in the documentation. Below screenshot shows my super simple code and the error i am seeing on iphone simulator.

![image](https://user-images.githubusercontent.com/24440615/121175829-6e1a7300-c853-11eb-90cb-a1b203b2b01a.png)

**Comment by manish-shukla01** [comment]
so i know more about the issue. i used us test card  on india account. when i used internation account it worked. two remaining questions on it: 1. how can i use us card on india account. looks like i need to set item description or osmething while creating payment intent. any links on how to do it?
2. how can i set the publishable key on client programatically. the example has it set up declarative but in my case even the publish key will be stored in backend and i want to drive it by configuration rather than hardcoding it in the apk files. any idea how i can accomplish that?

**Comment by tayzlor** [comment]
@manish-shukla01 

on 2. For retrieving publishable key on the client there's an example here retrieving it from an express REST API:

https://github.com/stripe/stripe-react-native/blob/master/example/server/index.ts#L71-L75

In the frontend component you can simply fetch() it. See https://github.com/stripe/stripe-react-native/blob/master/example/src/components/PaymentScreen.tsx#L16
