### ISSUE TITLE
retrievePaymentIntent with stripe Custom Connect 

### ISSUE THREAD

**Issue by rchoffar** [stripe/stripe-react-native#322]
**Describe the bug**
Hello, i am trying to implement this flow: https://stripe.com/docs/payments/save-and-reuse
I am using stripe custom connect so i can't do exactly the same as in the doc

```
const {retrievePaymentIntent, confirmPayment} = useStripe();
const handleConfirm = async () => {
const {paymentIntent, error} = await retrievePaymentIntent(
        route?.params?.clientSecret,
      );
      console.log(paymentIntent);
      console.log(error);
}
```
When i do this ( with a valid clientSecret ) for exemple: pi_1J0S3h4CbU68Y2vvxOzxQEbw_secret_qUR8unO6vVPFx64f407eD1gOj

I have an error:
```
 {"code": "Unknown", "declineCode": null, "localizedMessage": "There was an unexpected error -- try again in a few seconds", "message": "There was an unexpected error -- try again in a few seconds", "stripeErrorCode": null, "type": null}
```

This does not help me at all to solve the issue, i suspect that it is because i created this intent to an other stripeAccountId but i can't specified this stripeAccountId in the react-native API

This is the backend intent creation
```
const intent = await this.stripe.paymentIntents.create(
        {
          payment_method: paymentMethod.id,
          amount: amountEur,
          application_fee_amount: collectedFeesAmount,
          currency: 'eur',
          confirmation_method: 'manual',
          confirm: true,
          off_session: true,
          metadata: {
            paymentId: String(payment._id),
          },
        },
        {
          stripeAccount: seller.stripeAccountId,
        },
      );
      return intent;
```

**To Reproduce**
1 create a payment intent with a stripeAccount header
2 get the clientSecret of the intent
3 try to retrieve the paymentIntent

**Expected behavior**
I would expect to retreive the paymentIntent

**Smartphone (please complete the following information):**
 - Device: [e.g. iphone11 simulator]
 - OS: [e.g. iOS14.4]

**Additional context**
I am stuck with similar errors for weeks, i realy think this is because the stripeAccount header is not send when trying to retreive the payment intent, maybe i missed something in the doc

**Comment by thorsten-stripe** [comment]
@rchoffar the connected account ID needs to be set in the `StripeProvider` or `initStripe` method: https://stripe.dev/stripe-react-native/api-reference/interfaces/stripeproviderprops.html#stripeaccountid

**Comment by rchoffar** [comment]
So if the connected account change every time, i need to call initStripe multiple times in my app ?

**Comment by Shivani12345** [comment]
Getting same error while implementing retrive payments for ACH

```
 try {
      const paymentIntent = await retrievePaymentIntent(
        'pi_**************_secret_******************',     //secrettoken
      )
        .then(response => {
          console.log(response, 'response');
        })
        .catch(e => {
          console.log(e, 'ERROR');
        });
      console.log('paymentIntent', paymentIntent);
    
    } catch (error) {
      console.log('Error:', error);
    }
```
