### ISSUE TITLE
payment sheet not opening with unknown error in test mode

### ISSUE THREAD

**Issue by manish-shukla01** [stripe/stripe-react-native#323]
hi, i am able to call initPaymentSheet like below:

```
const { error } = await initPaymentSheet({
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,
    });
    if (!error) {
      console.log('no error so far');
      Alert.alert('All good','Try the next step');
    }
```
i see no error so far. then when i do the following:
```
const { error } = await presentPaymentSheet({ clientSecret: pi });
  console.log(JSON.stringify(error));
  if (error) {
    Alert.alert(`Error code: ${error.code}`, error.message);
  } else {
    Alert.alert('Success', 'Your order is confirmed!');
  }
```

i get error below(this is the result of logging error:
```
{"stripeErrorCode":null,"declineCode":null,"localizedMessage":"There was an unexpected error -- try again in a few seconds","message":"There was an unexpected error -- try again in a few seconds","type":null,"code":"Failed"}
```
i have not changed anything in my code and i believe it was working yesterday. what could be the reason? obviously i am seeing incomplete payments in stripe dashboard as its not even giving me chance to enter the credit card information. if it opens, i can enter cc information and go to next step. result of this issue is that on iphone, payment sheet comes and goes away immediately and nothing happens on android.

**Comment by trex-quo** [comment]
What happens if you sleep for 1-2 seconds between those two function calls? I have experienced a similar issue
https://github.com/stripe/stripe-react-native/issues/315

**Comment by manish-shukla01** [comment]
@trex-quo i saw that issue so i deliberately designed it in such a way that there will be enough gap between both the calls. there is something else going on. i wish there was better error message indicating what to do. any other ideas anyone?

**Comment by thorsten-stripe** [comment]
@manish-shukla01 can you double check your parameters https://github.com/stripe/stripe-react-native/issues/290#issuecomment-852774950 ?

**Comment by manish-shukla01** [comment]
@thorsten-stripe  i dont think this is my issue. here is my initpaymentsheet:
```
                console.log(JSON.stringify(response.data));
                const { error } = await initPaymentSheet({
                customerId: response.data.customerId,
                customerEphemeralKeySecret: response.data.ephemeralKeySecret,
                paymentIntentClientSecret: response.data.paymentIntentClientSecret,
                });
                console.log('input payment sheet done');
```
and log for this is:
```
Thu Jun 10 2021 09:55:19.865]  LOG      {"customerId":"cus_Je1ivStklNm29M","paymentIntentClientSecret":"pi_1J0jfXSB3Ekrrc8v86DIWiSp_secret_soFSjOBesFrKDWxLxeE7zzMnb","ephemeralKeySecret":"ek_test_YWNjdF8xSVhtNGtTQjNFa3JyYzh2LFhmbUN5OXV3ZUxpUURJOEVQZTQzcHRCS29GYWYwQks_00AN5sL7io"}
[Thu Jun 10 2021 09:55:19.885]  LOG      input payment sheet done
```
this happens when page loads. then i have a pay button and pay button code is like this:
```
            let finalerror;
            try{
            console.log(`paymentIntentClientSecret is ${paymentIntentClientSecret}`);
            finalerror  = await presentPaymentSheet({ clientSecret: paymentIntentClientSecret });
            }catch(error){
                console.log(`came in error: ${error}`);
            }
            console.log(`final error is ${JSON.stringify(finalerror)}`)
            if (finalerror) {
                console.log(`finalerror is ${finalerror}`);
                Alert.alert(`Error code: ${finalerror.code}`, finalerror.message);
                return {'status':'Payment was not processed'}
              } else {
                  console.log('everythign worked');
                Alert.alert('Success', 'Your order is confirmed!');
                 return {'status':'All Done with payment'}
              }
```
and log is (basically logging disappears after presentpaymentsheet call.this is android emulator. in iphone emualtor it goes in everything worked path. You can see the client secret is being unpassed unlike the other example. one thing different i am doing from teh example provided in stripe documentation is i am setting stripeprovider.publishablekey = 'key from backend' instead of putting it declaratively in the UI itself. (could this be issue?) :
```
[Thu Jun 10 2021 09:58:38.781]  LOG      about to get something done on server side
[Thu Jun 10 2021 09:58:38.781]  LOG      paymentIntentClientSecret is pi_1J0jfXSB3Ekrrc8v86DIWiSp_secret_soFSjOBesFrKDWxLxeE7zzMnb

```

**Comment by manish-shukla01** [comment]
@thorsten-stripe my suspicion was true in that issue was  stripeprovider publishablekey not being set if i set it through code or at least i am not setting it correctly. it all started working correctly if i just wrapped the whole screen in stripeprovider element and set the publishable key hardcoded. now only thing i need to figure out is how to make it dynamic. any pointers on that?

**Comment by thorsten-stripe** [comment]
You can set the publishable key on the StripeProvider via a state variable. The Stripe provider automatically reinitializes the library when the props change. The important thing though is that that needs to happen before you call `initPaymentSheet`. Here an example that uses `initStripe` instead of `StripeProvider`: https://github.com/stripe/stripe-react-native/blob/master/example/src/components/PaymentScreen.tsx#L14-L29

**Comment by Krow-Works** [comment]
I'm suffering and I don't know what to do anymore , everything works ok when I create a paymentIntent or setupIntent , but when I want to make a payment using subscriptions it opens and closes the modal very quickly , everything looks fine in initPaymentSheet , but in presentPaymentSheet it returns a error , an error that tells me nothing , I searched the internet and nothing . I just don't understand why it's the error only in the subscription


--> FRONT END

`
await api.post("/stripe-webhook/create-subscription-first", {
            customerId:user.stripe_customer_id,
            priceId:price.id
         }).then( async res => {
          
              const { status , client_secret  } = res.data.subscription.latest_invoice.payment_intent
              const { ephemeralKey , customerId } = res.data 
              
               if(status === 'requires_action') {
                const response = await initPaymentSheet({
                    customerId,
                    paymentIntentClientSecret:client_secret,
                    customerEphemeralKeySecret:ephemeralKey,
                })

                await new Promise( (resolv , reject) => setTimeout(() => resolv(''), 2000)  );

                if(response.error) { 
                    console.log(response.error);
                    return
                }
                console.log(response);
                
                const response2 = await presentPaymentSheet({
                     clientSecret: client_secret,
                })
                
                if(response2.error) {
                    console.log("Deu erro na segunda etapa");
                    console.log(response2.error);
                    return
                }
                console.log("SUCCESS");

               }
  
         }).catch( error => {
             console.log("Error ");
             console.log(error);  
         })
`

`
Object {
    "code": "Failed",
    "declineCode": null,
    "localizedMessage": "The operation couldn’t be completed. (Stripe.PaymentSheetError error 0.)",
    "message": "The operation couldn’t be completed. (Stripe.PaymentSheetError error 0.)",
    "stripeErrorCode": null,
    "type": null,
}

-->> BACKEND

`
router.post('/create-subscription-first', async (request , response) => {
    const {customerId,priceId} = request.body
    try {
      // await setPaymentMethodDefault(customerId)
      const ephemeralKey = await stripe.ephemeralKeys.create(
        {
          customer:customerId
        },
        {
          apiVersion:'2020-08-27'
        }
      )
    
      const subscription = await stripe.subscriptions.create({
        customer:customerId,
        items:[
          {
            price:priceId
          }
        ],
        payment_behavior: 'allow_incomplete',
        expand: ['latest_invoice.payment_intent','pending_setup_intent'], 
      })
      console.log(subscription);
      return response.json({ subscription, ephemeralKey:ephemeralKey.secret , customerId })

    } catch (error) {
        console.log("Error Create Subs");
        console.log(error);
        return response.status(404).json({error:'Error'})
    }

})
`

**Comment by matmac** [comment]
@Krow-Works did you found a solution to this? I'm facing the same issue.

In the logs I can see the payment is **incomplete - The customer has not entered their payment method.** with a charge of 0.20€ and in the mobile app I receive an error with **Stripe.PaymentSheetError error 1**.

I guess since the sheet appears for a second I can't add any payment method.

**Comment by qasimgit** [comment]
Facing the same exact issue, when calling the **presentPaymentSheet** function after the initialisation.

getting this error:
`Error code: Failed The operation couldn’t be completed. (StripePaymentSheet.PaymentSheetError error 1.)`

can you please reopen this issue @thorsten-stripe

**Comment by qasimgit** [comment]
Solved this issue by increasing the amount in the creation of paymentIntent, what I was adding in the amount was 12, which was according of stripe was 0.12, so I increased the amount to 120 which is 12 according the stripe.

here is the different minimum amount you can set for different currencies
https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts

**Comment by ARBAB1** [comment]
Can any one tell why this error returning from paymentPresentSheet() in ios, I am using stripe react native sdk in testmode.
I have 
setupIntentClientSecret,
customerEphemeralKeySecret,
customerId,
merchantDisplayName


 **{"code": "Failed", "declineCode": null, "localizedMessage": "The operation couldn’t be completed. (Stripe.PaymentSheetError error 1.)", "message": "The operation couldn’t be completed. (Stripe.PaymentSheetError error 1.)", "stripeErrorCode": null, "type": null}** 
 
 @thorsten-stripe
