### ISSUE TITLE
Android app crashes when attempting to create a payment method with a "bad" test card 

### ISSUE THREAD

**Issue by germanp173** [stripe/stripe-react-native#324]
**Describe the bug**
I'm currently using the `CardField` component to allow users to enter their credit card information.
When I try to enter a "bad" card to test an `insufficient_funds` failure, the app crashes with a `Value for message cannot be cast from ReadableNativeMap to String` low-level error.

The test card number I'm using is `4000 0000 0000 9995` as specified in the documentation [here](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet-custom#test).

**Note:** All other valid test cards listed the documentation link above work as expected

**To Reproduce**
1. In an app that uses the `CardField` component, enter the card number `4000 0000 0000 9995` and fill out the rest of the arbitrary details.
2. Attempt to `createPaymentMethod` with the card's details
3. Error comes up

**Expected behavior**
This action should not cause the app to crash. If there's a problem with the card, then it should be returned in the `error` property of `createPaymentMethod`.

**Screenshots**
![Screenshot_1623309677](https://user-images.githubusercontent.com/38846104/121482242-ccde0a80-c981-11eb-841f-cc9b75279672.png)

**Smartphone (please complete the following information):**
 - Device: Android
 - Version: 9

**Additional context**

* React Native version: 0.64.0
* @stripe/stripe-react-native version: 0.1.2

**Comment by thorsten-stripe** [comment]
I'm not able to reproduce this. Can you please update to the latest version and see if that resolves it?
![image](https://user-images.githubusercontent.com/23213994/121627436-eed2ac80-caa9-11eb-8eae-12b99ea8be06.png)

**Comment by germanp173** [comment]
My apologies, this was an error on my end. I really appreciate your time @thorsten-stripe.
