### ISSUE TITLE
ConfirmPaymentMethod returns "Canceled" error after doing 3DS confirmation

### ISSUE THREAD

**Issue by konstantinmv** [stripe/stripe-react-native#326]
Hi all, thanks for you work on this lib again. 
I've discovered a bug which happens just sometimes, making it even worse. 

When trying to create a payment method, which is a card, and charge 1 euro to the customer to check if the card is working, the response of the function `confirmPaymentMethod` returns `Canceled`. The full error is as follows:

`code: "Canceled"
declineCode: null
localizedMessage: "The payment has been canceled"
message: "The payment has been canceled"
stripeErrorCode: null
type: null`

Sometimes it does work though, but mostly it sends back this error. 
This has been tested in development on an iOs simulator. 
The `CardField` is located on the same screen and works fine. This issue does not occur with `confirmSetupIntent` when no payment is involved.

**To Reproduce**
1. Create a payment intent which charges 1 euro to the customer. 
2. The card being used is one of the cards that you provide for testing, concretely 4000002500003155 (https://stripe.com/docs/testing)
3. Use this payment intent client's secret and call `confirmPaymentMethod` with `type: 'Card', billingDetails: { name: "Blabla" }`. 
4. The confirmation screen is brought up, asking you to confirm or fail the transaction. After the transaction is confirmed, the next screen appears, the user is then asked to close it (as the authentication is completed).
5. After closing it, the app receives `Canceled` error from Stripe. 
6. After refetching the payment method, the card is actually saved in Stripe, so the error is completely wrong. 

**Expected behavior**
When the payment has been authenticated, the expected behavior would be to receive the payment method info in order to continue with the process.

**Desktop (please complete the following information):**
 - OS: MacOs Big Sur 11.2.3
 - Browser: Chrome
 - Version: 91.0.4472.77 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: iPhone 6s (Simulator!)
 - OS: 13.5
 - Browser: stock browser

**Comment by konstantinmv** [comment]
Here's a video of the problem. 
Thanks in advance!

https://user-images.githubusercontent.com/54809274/121507233-bd43dd80-c9e4-11eb-92f2-733815f084b8.mov

**Comment by thorsten-stripe** [comment]
Hm, I'm not able to reproduce this. Are you using the latest version? And do you have a link to your code maybe? Do you see any logs in your Stripe Dashboard? https://dashboard.stripe.com/test/logs

**Comment by konstantinmv** [comment]
Hi!
Seeing that you can't reproduce it, we just checked with our backend team and saw that it's actually our fault. It's caused by a difference between webhook handling between Stripe and tipsi-stripe. We were cancelling the payment (reverting the 1 euro charge) too fast, so we were getting this error. 

Setting a timeout for cancelling this solved the issue. 

Thanks anyway!
