### ISSUE TITLE
Android equivalement of Apple pay methods such as presentApplePay, useApplePay

### ISSUE THREAD

**Issue by carl-passnfly** [stripe/stripe-react-native#327]
From reading the documentation and looking at examples I don't see any examples to directly open Google Pay, without presenting a `paymentSheet` on android. 

Methods seems to exist for iOS but I don't see any way to accomplish the same on android.

My feature request would be to have something similar on android as for example: `presentGooglePay`.

Thanks!

**Comment by konstantinmv** [comment]
The issue is already open, it also has an updated response from the Stripe team:

https://github.com/stripe/stripe-react-native/issues/9
