### ISSUE TITLE
Undefined symbols for architecture arm64:    "_swift_getOpaqueTypeConformance", referenced from:

### ISSUE THREAD

**Issue by enormousrodent** [stripe/stripe-react-native#328]
**Describe the bug**
When building locally it is successful.  When automated build via AppCenter get the following error:

    ld: warning: -sdk_version and -platform_version are not compatible, ignoring -sdk_version
    Undefined symbols for architecture arm64:
      "_swift_getOpaqueTypeConformance", referenced from:
          __hidden#62050_Tm in 1177.o
          __hidden#62129_ in 1177.o
          __hidden#62142_ in 1177.o
          __hidden#79276_ in 1306.o
    ld: symbol(s) not found for architecture arm64
    Exited with 1

**Expected behavior**
IOS Build to be successful.  Only started to fail after adding in Stripe SDK

**Additional context**
I have tried removing all Search Paths, added in fix.swift and created bridging header as per documentation.  Still fails to build.  Additionally have set build target to ios12 as per other guidance. 

Can someone please try to point me in another direction on what could be the cause?

**Comment by robsco** [comment]
This sounds familiar, I had a perfectly working RN app earlier, after installing this library, and up'ing my build target in both the podfile and Build Settings, I now get a failing build, with these errors:

Undefined symbol: type metadata accessor for (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType
Undefined symbol: protocol conformance descriptor for __C.NSOperationQueue : Combine.Scheduler in Foundation
Undefined symbol: (extension in Foundation):__C.NSScanner.scanUpToString(Swift.String) -> Swift.String?
Undefined symbol: (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType.init(Foundation.Date) -> (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType
Undefined symbol: _swift_getOpaqueTypeConformance

"@invertase/react-native-apple-authentication": "^1.1.2",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "^3.4.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-picker/picker": "^1.14.0",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "@stripe/stripe-react-native": "^0.1.4",
    "react": "^17.0.2",
    "react-native": "^0.64.1",
    "react-native-elements": "^2.3.2",
    "react-native-fbsdk": "^3.0.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-picker": "^2.3.4",
    "react-native-numeric-input": "^1.8.3",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "^1.13.3",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-vector-icons": "^7.1.0",
    "typescript": "^4.2.3"

**Comment by enormousrodent** [comment]
As per my additional context...I have tried removing all Search Paths already...When I view the search paths in the UX it shows nothing and when viewing via code its only inherited..

**Comment by enormousrodent** [comment]
To rule out any other issues i have removed the Stripe SDK from my project for RN and it successfully built (this was to rule out any possible 3rd party problems and isolates the issue to just this library.  Any guidance would be great.

**Comment by thorsten-stripe** [comment]
Have you created the swift file with the bridging header as outlined here https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios ?

**Comment by enormousrodent** [comment]
Yes...created a swift file..and we already have a bridging header created for other dependencies in our project.

**Comment by enormousrodent** [comment]
Out of interest...what should the bridging header do?  I only ask this as we have a file in our solution already called App-Bridging-Header.h which has no contents apart from:

//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

Should this contain any specific Stripe stuff?

**Comment by arekkubaczkowski** [comment]
@enormousrodent can you open project.pbxproj file in editor and check whether `LIBRARY_SEARCH_PATHS` does contain only `inherited` value?
like this:
```
LIBRARY_SEARCH_PATHS = (
	"\"$(inherited)\"",
);
```

**Comment by arekkubaczkowski** [comment]
> Out of interest...what should the bridging header do? I only ask this as we have a file in our solution already called App-Bridging-Header.h which has no contents apart from:
> 
> //
> // Use this file to import your target's public headers that you would like to expose to Swift.
> //
> 
> Should this contain any specific Stripe stuff?

```
To import a set of Objective-C files in the same app target as your Swift code, you rely on an Objective-C bridging header to expose those files to Swift. Xcode offers to create this header file when you add a Swift file to an existing Objective-C app, or an Objective-C file to an existing Swift app.
```

**Comment by enormousrodent** [comment]
Inherited is the only value i see against any search paths..

**Comment by enormousrodent** [comment]
Any other suggestions?

**Comment by arekkubaczkowski** [comment]
@enormousrodent 
I wasn't able to reproduce it in AppCenter
- I created new RN project
- added stripe library
- Created new swift file with bridging header
- Removed items from release LIBRARY_SEARCH_PATHS
- Changed ios deployment target to be consistent with this from Podfile
<img width="328" alt="Zrzut ekranu 2021-06-18 o 09 12 54" src="https://user-images.githubusercontent.com/18654447/122522535-5e025080-d016-11eb-8692-dd5c57bfc85e.png">
- Used default configuration in AppCenter
<img width="524" alt="Zrzut ekranu 2021-06-18 o 09 10 41" src="https://user-images.githubusercontent.com/18654447/122522553-622e6e00-d016-11eb-9c5b-7762099bba14.png">

And it builds successfully 
<img width="762" alt="Zrzut ekranu 2021-06-18 o 09 20 55" src="https://user-images.githubusercontent.com/18654447/122522663-812d0000-d016-11eb-96bc-5301ad029125.png">

**Comment by enormousrodent** [comment]
We discovered that the issue was caused by Bitcode.  When we disable BITCODE on build then we get successful.

**Comment by imsuresh97** [comment]
Hi Facing same issue even after disabling the BITCODE and with other alternatives tried all the available solutions ... tried in fresh react native project ... only difference ,xcode Version 12.5 (12E262) ... kindly advice

**Comment by aliboyraz** [comment]
Make sure; all swift releated items are removed from Library_Search_Path. **Even though they are removed via XCODE Editor and its not being showed in editor any more, open project file via Text Editor and search whether they are there or not.**

**Comment by imsuresh97** [comment]
Hi Aliboyraz , i have checked it .. and make sure the only thing present now is ''$(inherited)" in Library_Search_Path ... still facing the same issue ... and OS version 11.4 , m1 processor , xcode Version 12.5 (12E262) ... this is happening only if i add stripe dependencies ...

**Comment by minh-dai** [comment]
same, I delete all in Library_Search_Path, the file has only ''$(inherited)", and create file Swift and a bridging header.

**Comment by arekkubaczkowski** [comment]
@minh-dai can you try this? https://github.com/stripe/stripe-react-native/issues/387#issuecomment-879006851

**Comment by minh-dai** [comment]
@arekkubaczkowski i did, but it's not wroking
