### ISSUE TITLE
[Apple Pay]: createToken-esque support for Apple Pay

### ISSUE THREAD

**Issue by rkyle35242** [stripe/stripe-react-native#329]
**Is your feature request related to a problem? Please describe.**

We are looking to move off `tipsi-stripe` in favor of `stripe-react-native`. The recent support for `createToken` could allow us to do that while our backend updates to support PaymentIntents/PaymentMethods, but `presentApplePay` returns a PaymentMethod. 

**Describe the solution you'd like**

Could support be added for getting a card token (`tok_*****`) for Apple Pay?

Something like a legacy function similar to `tipsi-stripe`'s `paymentRequestWithNativePay` from previous versions (we are on 7.5.3) or an optional param for `presentApplePay` to return a legacy token.

**Describe alternatives you've considered**

The Stripe dependency for the version of `tipsi-stripe` that supports creating a token from their payment form is incompatible with `stripe-react-native`, so utilizing both libraries is right out.

Our backend has prioritized the work to move to Payment Intents, but that work will be significant.

I couldn't find anything in the docs or from parsing the library's code that led me to believe this functionality existed, but I could've easily missed something.

**Additional context**

Example `tipsi-stripe` ver 7.5.3 result from `paymentRequestWithNativePay`
```{
  "livemode": false,
  "extra": {
    "billingContact": {
      "supplementarySubLocality": "",
      "name": "Payment McCardface",
      "street": "123 Champing at Debit",
      "city": "Nowhere",
      "country": "United States",
      "ISOCountryCode": "US",
      "postalCode": "99999",
      "state": "Hawaii"
    },
    "shippingMethod": null,
    "shippingContact": null
  },
  "created": 1623327212,
  "card": {
    "addressLine1": "123 Champing at Debit",
    "country": "US",
    "cardId": "card_1J0mlMGeIPwANAtnIykrbI9J",
    "dynamicLast4": "4242",
    "addressCity": "Nowhere",
    "brand": "Visa",
    "last4": "4242",
    "isApplePayCard": true,
    "addressZip": "99999",
    "name": "Payment McCardface",
    "addressCountry": "US",
    "funding": "credit",
    "expYear": 2022,
    "addressState": "Hawaii",
    "expMonth": 12
  },
  "tokenId": "tok_1J0mlMGeIPwANAtnTufMCmw2"
}
```

Example `stripe-react-native` result from `presentApplePay`
```
{
  "paymentMethod": {
    "Card": {
      "funding": "credit",
      "country": "US",
      "last4": "4242",
      "fingerprint": null,
      "expYear": 2022,
      "expMonth": 12,
      "brand": "Visa"
    },
    "Ideal": { ... },
    "Fpx": { ... },
    "Upi": { ... },
    "type": "Card",
    "BacsDebit": { ... },
    "customerId": null,
    "AuBecsDebit": { ... },
    "SepaDebit": { ... },
    "id": "pm_1J0nYRGeIPwANAtnsRQjkUNZ",
    "Sofort": { ... },
    "billingDetails": { ... }
    },
    "livemode": false
  }
}
```

**Comment by thorsten-stripe** [comment]
Tokens are legacy and we're not planning on supporting them in this library. Please use PaymentIntents going forward: https://stripe.com/docs/apple-pay?platform=react-native

**Comment by rkyle35242** [comment]
@thorsten-stripe No worries, I thought it would be a long shot. Thanks for the reply!
