### ISSUE TITLE
createToken - Card Details not complete when passing specified props

### ISSUE THREAD

**Issue by patrickcoca** [stripe/stripe-react-native#331]
I am trying to implement the dependency's `createToken` function in my React Native app. In the `params` argument I have passed a `name`, `type`, and `address` as specified in the [API reference](https://stripe.dev/stripe-react-native/api-reference/interfaces/card.createtokenparams.html). I have called `initStripe()` in my root component to initialize the dependency. (I have also implemented the `CardField` component but the `cardDetails` did not fit the params of the `createToken` or `createPaymentMethod` function calls, and I had tried passing them in anyway to no avail).

When I call the `createToken` function like so: 
`await createToken({
                        name: 'Dave',
                        type: 'Card',
                        address: {
                            city: 'Baltimore',
                            country: 'U.S.A.',
                            state: 'Maryland',
                            postalCode: '11111',
                            line1: '1234 Root Beer Lane',
                            line2: 'Apt. #56',
                        },
});`

I get the returned error: 
` { 
token: {
 error: { 
code: "Failed",
localizedMessage: "Card details not complete",
message: "Card details not complete",
declineCode: null,
type: null,
stripeErrorCode: null,
}
} 
}`

Once again, I also tried the above function call, spreading in the `cardDetails` in various forms but got the same error message. 

**Expected behavior**
A token, with an id such as `tok_1234`, returned as consistent with the Stripe API

**Smartphone**
 -  iPhone X
 - iOS 14.4
 - @stripe/stripe-react-native version: 0.1.4
 - react-native version 0.63.3

My main question is what the full parameters for createToken should be, and how to get it working correctly. 
Thank you!

**Comment by patrickcoca** [comment]
@thorsten-stripe I have also experienced similar issues trying to use `createPaymentMethod`, but I am hoping it's a simple solution and I am just using the dependency wrong. In either case, any help would be appreciate very much!

**Comment by thorsten-stripe** [comment]
`createToken` is a legacy method that should only be used in exceptional cases, please use `createPaymentMethod` instead. In any case, these methods have to be used in combination with the `CardField` component. Please see the docs: https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native
