### ISSUE TITLE
createPaymentMethod- Throws error on IOS "This payment type is not supported yet"

### ISSUE THREAD

**Issue by NicholasPeck** [stripe/stripe-react-native#332]
**Describe the bug**
createPaymentMethod throws the following error on IOS but works as intended on Android when passed the same card information. 

{code: "Failed", declineCode: null, localizedMessage: "This payment type is not supported yet", message: "This payment type is not supported yet", stripeErrorCode: null, type: null}

**To Reproduce**
1. Enter Card information to the CardField
2. Click the Button to call createPayment

```
export default function PaymentScreen({ onPress, price, disabled }) {
  const { createPaymentMethod } = useStripe()
  const [loading, setLoading] = useState(false)

const createPayment= async () => {
    setLoading(true)
    const { error, paymentMethod } = await createPaymentMethod({
      type: 'card',
    })
    console.log(error)
    console.log(paymentMethod)
  }

  return (
    <>
      <CardField
        postalCodeEnabled={true}
        placeholder={{
          number: '4242 4242 4242 4242',
        }}
        cardStyle={{
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
        }}
        style={{
          width: '100%',
          height: 50,
          marginVertical: 30,
        }}
      />
      <Button title="Pay Now" disabled={loading} onPress={createPayment} />
    </>
  )
}

```
**Expected behavior**
createPaymentMethod should return a PaymentMethod.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS14.4

**Additional context**
Is the PaymentMethod type card not accepted at this time for IOS?

**Comment by simawn** [comment]
`type: 'card'` should be `type: 'Card'` (Notice the capitalization)
