### ISSUE TITLE
CardField not hiding keyboard when complete, or clicking away

### ISSUE THREAD

**Issue by robsco** [stripe/stripe-react-native#334]
My app is component based, and/therefore I'm using initStripe, createPaymentMethod, handleCardAction, and the CardField.

This mirrors my web-based way of working, so helps keep things simple, to me, and able to re-use a lot of my existing code.

Everything is working fine, in taking payments, but when I've finished entering the card details, the keyboard doesn't hide, and even when clicking away, the keyboard remains.

I have to click into another TextInput, then click away to hide the keyboard.

This is with postalCodeEnabled set to false.

With postalCodeEnabled set to true there is the "return" key on the keyboard, but this isn't available when entering card numbers/dates since it's the numeric keypad.

Currently testing on iOS, not sure about Android behaviour yet.

**Comment by thorsten-stripe** [comment]
You'll need to wrap the `CardField` component with the `StripeContainer` component to achieve this: https://github.com/stripe/stripe-react-native/blob/master/example/src/components/PaymentScreen.tsx#L34
