### ISSUE TITLE
Ability to hide the close CTA in presentPaymentSheet, when Pay is press and payment is processing state

### ISSUE THREAD

**Issue by harbolaez** [stripe/stripe-react-native#335]
**Is your feature request related to a problem? Please describe.**
When presentPaymentSheet is call the bottom sheet will open with the close, which great. But when the user press Pay, and they payment in underway, they user can close the X and it closes the sheet, but they payment still got process. Will be great if the X to close the sheet, is hidden when the user press Pay. 

Maybe there is a way now? I can’t find it in the doc or code.

thanks!

**Comment by thorsten-stripe** [comment]
Thanks @harbolaez this is a bug in the respective native payment sheet implementations. I have forwarded it to the team and they are looking into fixing it.

**Comment by harbolaez** [comment]
Hi @thorsten-stripe any update on above? Thanks!
