### ISSUE TITLE
[Expo Go] The result of  the confirmPayment API is undefined.

### ISSUE THREAD

**Issue by ruida-shen** [stripe/stripe-react-native#336]
**Describe the bug**
The result of the confirmPayment API is undefined. I am following this setup [guide](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&lang=node&ui=custom).

**To Reproduce**

**Here's the client code:**
```JS
import React, { useState, useEffect } from "react";
import { View, StyleSheet } from "react-native";
import {
  CardField,
  initStripe,
  useConfirmPayment,
} from "@stripe/stripe-react-native";
import { Button } from "react-native-elements";
import { ActivityIndicator } from "react-native";
import axios from "axios";

const fetchClientSecret = async () => {
  const { data } = await axios.post(
    "http://192.168.1.66:5000/create-payment-intent"
  );
  return data; // client secret
};

const StripePaymentForm = () => {
  const [loading, setLoading] = useState(true);
  const { confirmPayment } = useConfirmPayment();
  const handlePayPress = async () => {
    const clientSecret = await fetchClientSecret();
    const confirmPaymentResult = await confirmPayment(clientSecret, {
      type: "Card",
      billingDetails: {
        email: "email@stripe.com",
        phone: "+48888000888",
        addressCity: "Houston",
        addressCountry: "US",
        addressLine1: "1459  Circle Drive",
        addressLine2: "Texas",
        addressPostalCode: "77063",
      },
    });
    console.log("confirmPaymentResult:", confirmPaymentResult); // getting { paymentIntent: undefined }
  };

  useEffect(() => {
    async function init() {
      await initStripe({
        publishableKey: process.env.publishable_key,
      });
      setLoading(false);
    }
    init();
  }, []);

  if (loading) {
    return <ActivityIndicator color="black"></ActivityIndicator>;
  }

  return (
    <View>
      <CardField
        postalCodeEnabled={true}
        placeholder={{
          number: "4242 4242 4242 4242",
        }}
        cardStyle={{
          backgroundColor: "#FFFFFF",
          textColor: "#000000",
          ...styles.border,
        }}
        style={{
          height: 50,
          width: "100%",
        }}
      ></CardField>
      <Button
        title="Pay"
        containerStyle={{ marginTop: 20 }}
        onPress={handlePayPress}
      ></Button>
    </View>
  );
};

const styles = StyleSheet.create({
  textInput: {
    height: 50,
    width: "100%",
  },
  border: {
    borderWidth: 1,
    borderRadius: 6,
    borderColor: "black",
  },
});

export default StripePaymentForm;

```

**Here is the server code:**
```JS
const app = require("express")();
const stripe = require("stripe")(process.env.secret_key);

app.post("/create-payment-intent", async (req, res) => {
  const paymentIntent = await stripe.paymentIntents.create({
    amount: 1099,
    currency: "usd",
  });
  res.send(paymentIntent.client_secret);
});


app.listen("5000", () => {
  console.log("App listening at http://localhost:5000");
});

```

**Expected behavior**
Getting a correct response from the confirmPayment API such as 
```JS 
{ paymentIntent:{currency:'USD'} }
 ```

**Smartphone (please complete the following information):**
 - Device: [Iphone 12]
 - OS: [14.6]

**Additional context**
I am using Expo Go

**Comment by thorsten-stripe** [comment]
What's the full log of `confirmPaymentResult`? Does the error object tell you anything?

**Comment by ruida-shen** [comment]
> What's the full log of `confirmPaymentResult`? Does the error object tell you anything?

The full log of confirmPaymentResult is:
![Capture](https://user-images.githubusercontent.com/75506336/121933740-4f0c5d00-ccfb-11eb-856a-97412f35f505.PNG)

There is no error object

**Comment by thorsten-stripe** [comment]
Your code works fine for me on `Expo/2.19.6.1011482`. Can you check if you see any errors in your Stripe logs: https://dashboard.stripe.com/test/logs

**Comment by Kavf** [comment]
@thorsten-stripe Hello, I used the command "expo install @strip/strip react native" to install the strip of Expo version. When I run Expo in the browser, the following error occurred. Could you help me check the problem?
`Failed to compile.
C:/project/project-name/node_modules/@stripe/stripe-react-native/lib/module/components/StripeProvider.js
Module not found: Can't resolve '../../package.json' in 'C:\project\project-name\node_modules\@stripe\stripe-react-native\lib\module\components'`

**Comment by ruida-shen** [comment]
> @thorsten-stripe Hello, I used the command "expo install @strip/strip-react-native" to install the stripe of Expo version. When I run Expo in the browser, the following error occurred:
> 
> 
> 
> `Failed to compile.
> 
> C:/project/project-name/node_modules/@stripe/stripe-react-native/lib/module/components/StripeProvider.js
> 
> Module not found: Can't resolve '../../package.json' in 'C:\project\project-name\node_modules\@stripe\stripe-react-native\lib\module\components'`
> 
> 
> 
> Could you help me check the problem?

I think react native stripe is not supported in Web 

https://docs.expo.io/versions/latest/sdk/stripe/

**Comment by ruida-shen** [comment]
> Your code works fine for me on `Expo/2.19.6.1011482`. Can you check if you see any errors in your Stripe logs: https://dashboard.stripe.com/test/logs

```
Some dependencies are incompatible with the installed expo package version:
 - @stripe/stripe-react-native - expected version: 0.1.1 - actual version installed: 0.1.4
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run:
```

Thanks for replying, somehow I missed this message on the console, I have fixed the issue.
