### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by Jackyaung** [stripe/stripe-react-native#338]
when I press the button "pay with passcode", the process for one or two second then app crash. I even couldn't track what the problem is, it just crash when I press the button. is anyone having this problem?

**Comment by thorsten-stripe** [comment]
Please fill out the bug report template with the necessary information to help us help you: https://github.com/stripe/stripe-react-native/issues/new?assignees=&labels=&template=bug_report.md&title= Thanks.
