### ISSUE TITLE
Stripe SDK not worked for ios work fine in android.

### ISSUE THREAD

**Issue by vaibhavcis2912** [stripe/stripe-react-native#339]
**Describe the bug**

* BUILD FAILED *

The following build commands failed:
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/AddPaymentMethodViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/AlipayDetailsEditView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/BillingAddressEditView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/BottomSheet3DS2ViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/BottomSheetViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/CardDetailsEditView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/CardScanningView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/CheckboxButton.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/ChoosePaymentOptionViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/CircularButton.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/ConfirmButton.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/IdealDetailsEditView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/LoadingViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/NSDictionary+Stripe.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/NSError+Stripe.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/NSMutableURLRequest+Stripe.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/NSString+Stripe.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/NSURLComponents+Stripe.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/View/PanContainerView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Animator/PanModalAnimator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Presentable/PanModalHeight.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Presentable/PanModalPresentable+Defaults.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Presentable/PanModalPresentable+LayoutHelpers.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Presentable/PanModalPresentable+UIViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Presentable/PanModalPresentable.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Animator/PanModalPresentationAnimator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Controller/PanModalPresentationController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Delegate/PanModalPresentationDelegate.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PanModal/Presenter/PanModalPresenter.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentMethodTypeCollectionView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentOption+Images.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheet+Helpers.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheet+SwiftUI.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheet.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheetConfiguration.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheetError.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheetFlowController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheetViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PaymentSheetViewControllerViews.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PKAddPaymentPassRequest+Stripe_Error.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/PKPaymentAuthorizationViewController+Stripe_Blocks.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/SavedPaymentMethodCollectionView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/SavedPaymentOptionsViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/SheetNavigationBar.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPAddress.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPAddressFieldTableViewCell.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPAddressViewModel.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPAPIClient+ApplePay.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPApplePayContext+PaymentSheet.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPApplePayContext.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPAUBECSDebitFormView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPAUBECSFormViewModel.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPAuthenticationContext.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBackendAPIAdapter.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBankAccount.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBankAccountParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBankSelectionTableViewCell.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBankSelectionViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBECSDebitAccountNumberValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBINRange.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBlocks.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBSBNumberValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPBundleLocator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCameraView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCard.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardBINMetadata.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardBrand.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardCVCInputTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardCVCInputTextFieldFormatter.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardCVCInputTextFieldValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardExpiryInputTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardExpiryInputTextFieldFormatter.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardExpiryInputTextFieldValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardFormView+SwiftUI.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardFormView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardLoadingIndicator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardNumberInputTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardNumberInputTextFieldFormatter.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardNumberInputTextFieldValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardScanner.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardScannerTableViewCell.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardValidationState.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCardValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPColorUtils.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConfirmAlipayOptions.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConfirmBLIKOptions.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConfirmCardOptions.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConfirmPaymentMethodOptions.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConnectAccountAddress.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConnectAccountCompanyParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConnectAccountIndividualParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPConnectAccountParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPContactField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCoreScrollViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCoreTableViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCoreViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCountryPickerInputField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCustomer.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPCustomerContext.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPDispatchFunctions.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPEmailAddressValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPEmptyStripeResponse.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPEphemeralKey.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPEphemeralKeyManager.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPEphemeralKeyProvider.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPError.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFakeAddPaymentPassViewController.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFile.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFloatingPlaceholderTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFormEncodable.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFormEncoder.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFormTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFormTextFieldContainer.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFormView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFPXBankBrand.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPFPXBankStatusResponse.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPGenericInputPickerField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPGenericInputTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPiDEALBank.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPiDEALBankPickerInputField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPiDEALFormView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPImageLibrary.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPInputFormColors.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPInputTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPInputTextFieldFormatter.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPInputTextFieldValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPIntentAction.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPIntentActionAlipayHandleRedirect.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPIntentActionOXXODisplayDetails.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPIntentActionRedirectToURL.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPIntentActionUseStripeSDK.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPInternalAPIResponseDecodable.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPIssuingCardPin.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPKlarnaLineItem.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPLabeledFormTextFieldView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPLabeledMultiFormTextFieldView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPLocalizationUtils.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPLocalizedString.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPMandateCustomerAcceptanceParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPMandateDataParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPMandateOnlineParams.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPMultiFormTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPMultipartFormDataEncoder.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPMultipartFormDataPart.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPNumericDigitInputTextFormatter.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPNumericStringValidator.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPPaymentActivityIndicatorView.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPPaymentCardTextField+SwiftUI.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPPaymentCardTextField.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPPaymentCardTextFieldCell.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPPaymentCardTextFieldViewModel.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPPaymentConfiguration.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobile/ios/Pods/Stripe/Stripe/STPPaymentConfirmation+SwiftUI.swift
        CompileSwift normal x86_64 /Users/cis/Desktop/untitled_folder/VaibhavDevelopment/new/RymindrMobil

**Expected behavior**

**Comment by vaibhavcis2912** [comment]
Application worked without stripe package but once I install this package. It starts throwing above error.

**Comment by thorsten-stripe** [comment]
Did you run `pod install` in your `ios` folder after installing the library?

**Comment by vaibhavcis2912** [comment]
yes i have install the pods

**Comment by arekkubaczkowski** [comment]
@vaibhavcis2912 are you still facing above issue?

**Comment by vaibhavcis2912** [comment]
Yes I am still facing the same issue

**Comment by arekkubaczkowski** [comment]
@vaibhavcis2912 have you followed all of troubleshooting steps from README? https://github.com/stripe/stripe-react-native#troubleshooting

**Comment by dcx86** [comment]
Hi,

I'm having the same exact issue.
The build works if i uninstall stripe and it breaks when stripe is installed.
`pod install` manages to install stripe no problem

I have tried the same fix and the one mentioned by @arekkubaczkowski but it didn't fix the issue.
- For me `Build Settings > Library Search Paths' is empty there is nothing there to remove
- Adding a new swift file and creating bridging header when prompted by Xcode was simple enough to follow

I'm running the app on Apple M1 chip. Are there any known issues with the stripe library regarding that?

**Comment by dcx86** [comment]
The build also fails on AppCenter with the following error:

```
The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

Works perfectly fine the moment I uninstall `stripe`.
Any idea what is happening here?

**Comment by vaibhavcis2912** [comment]
@arekkubaczkowski yes I have followed readme , but no solution there for the issue i have

**Comment by vaibhavcis2912** [comment]
My app worked fine when uninstall the stripe

**Comment by arekkubaczkowski** [comment]
@vaibhavcis2912 can you provide more details about your issue and say what you have exactly tried so far?

**Comment by dcx86** [comment]
I tried a clean install:

`rm -rf node_modules && rm package-lock.json && cd ios && rm -rf Pods && rm Podfile.lock && npm i && pod install && npm run ios`

I had tipsi-stripe installed before but I removed it to replace it with stripe. Could that have caused any issues/conflicts?
Maybe I should try to start a new react-native project to see if I still get the same error when building the app for ios after installing stripe.

**Comment by dcx86** [comment]
I can confirm that starting a new project and installation stripe does successfully build. Thus this seems to be a problem with my current project. Not sure how to identify the issue. Could there be any conflicting npm packages?

**Comment by arekkubaczkowski** [comment]
@dcx86 can you check this out https://github.com/stripe/stripe-react-native/issues/387#issuecomment-879006851 ?
If it's s not help can you provide more details about the issue and error message?

**Comment by dcx86** [comment]
@arekkubaczkowski your solution worked for me! Thank you!
More precisely I had to make sure that **ios version is consistent** across all instances:
1. ios version in Xcode>Target>Deployment Info
2. `platform :ios, '12.1` in Podfile
3. `['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1` in Podfile

**Comment by AftabUfaq** [comment]
same issue. `Xcode version 13.0` and` @stripe/react-native-stripe versions 0.2.3`
