### ISSUE TITLE
Problem when yarn bootstrap   node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by EinarHm** [stripe/stripe-react-native#340]
**Describe the bug**
Problem when trying to install dependencies

/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@15.14.0 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-darwin-unknown-arm64.tar.gz
node-pre-gyp http 404 https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-darwin-unknown-arm64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.7.0 and node@15.14.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.14.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.14.0 | darwin | arm64
gyp info find Python using Python version 3.9.4 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/opt/homebrew/Cellar/node/15.14.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/homebrew/Cellar/node/15.14.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/einarhohenstein/Library/Caches/node-gyp/15.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/einarhohenstein/Library/Caches/node-gyp/15.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/Cellar/node/15.14.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/einarhohenstein/Library/Caches/node-gyp/15.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/Cellar/node/15.14.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/opt/homebrew/Cellar/node/15.14.0/bin/node" "/opt/homebrew/Cellar/node/15.14.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
gyp ERR! cwd /Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas
gyp ERR! node -v v15.14.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --fallback-to-build --module=/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 20.5.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/15.14.0/bin/node" "/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas
node-pre-gyp ERR! node -v v15.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp configure --fallback-to-build --module=/Users/einarhohenstein/Desktop/stripe-react-native/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/einarhohenstein/Desktop/stripe-rea

error Command failed with exit code 1.
**To Reproduce**
1. Clone Proyect
2. cd stripe-react-native
3. yarn bootstrap

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Chip: M1
 - Version 11.4

**Comment by mrkp** [comment]
Experiencing the same problem, M1 chip mac. Any fix yet?

**Comment by arekkubaczkowski** [comment]
@EinarHm @mrkp have you managed to solve above issue or you still need help with this?

**Comment by mrkp** [comment]
Can't remember what I changed exactly but it was because the external environment of the examples folder wasn't installed correctly. If you need help I can walk you through

**Comment by arekkubaczkowski** [comment]
@mrkp  actually I just wanted to help but would appreciate if you could share the solution with other folks facing this issue

**Comment by bujoralexandru** [comment]
I am encountering the same issue on a M1 chip. Anyone available to make the solution public, please?

**Comment by antoniskak** [comment]
Had the same issue on M1. Solved when I did `yarn upgrade` first
