### ISSUE TITLE
[iOS] Error: Assertion failed: Failed to find an image named icon_x 

### ISSUE THREAD

**Issue by paschalidi** [stripe/stripe-react-native#341]
When I am calling the `await presentPaymentSheet({clientSecret})` on my client side I am getting an error 
```
Assertion failed: Failed to find an image named icon_x
```
I am trying to make the `presentPaymentSheet` visible on the screen and the app crashes. 

Probably related to the https://github.com/stripe/stripe-ios/issues/1722 & https://github.com/stripe/stripe-react-native/issues/290

**Desktop (please complete the following information):**
 - OS: iOS
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - Versions: 
     Stripe (21.6.0)
     stripe-react-native (0.1.4)

**Comment by thorsten-stripe** [comment]
@yuki-stripe @davidme-stripe any ideas on this?

**Comment by salehshah** [comment]
any update to this? facing the same issue.

**Comment by melomontoya** [comment]
I'm facing this same issue, added Stripe tru package manager and it gives the same error :C  
![Captura de Pantalla 2021-08-11 a la(s) 12 56 50](https://user-images.githubusercontent.com/6599630/129079653-36760d34-dc7b-4df8-82f9-407c6a2d8c12.png)
![Captura de Pantalla 2021-08-11 a la(s) 12 57 00](https://user-images.githubusercontent.com/6599630/129079654-459cab9b-e330-42d1-b761-7f311ef52325.png)
![Captura de Pantalla 2021-08-11 a la(s) 12 57 32](https://user-images.githubusercontent.com/6599630/129079657-50e098ca-4350-4a09-af27-0053a2795ceb.png)

**Comment by arekkubaczkowski** [comment]
Fix will be available within the next release
