### ISSUE TITLE
[Android] lateinit property stripe has not been initialized

### ISSUE THREAD

**Issue by i-suraj007** [stripe/stripe-react-native#343]
Steps to produce this error:

Step 1: Make Sofort Payment
Step 2: You will get this error Screen **`lateinit property stripe has not been initialized`**
Step 3. Reload the App and try again. It works!

I am getting this error **sometimes**.

**Screenshots**
![photo_2021-06-15_13-06-16](https://user-images.githubusercontent.com/24787428/122012180-843bac80-cdda-11eb-879b-96745f1baca1.jpg)

**Smartphone:**
 - Device: Realme x
 - OS: Android 10

**Comment by thorsten-stripe** [comment]
How are you initializing Stripe? Are you using `StripeProvider` or `initStripe`? Can you please share your code?

**Comment by i-suraj007** [comment]
oops! I forgot to initialize Stripe. Thanks for your quick response.
Your question solved my issue :p
