### ISSUE TITLE
Getting Error Card Details not complete on use of Custom Card Input Component

### ISSUE THREAD

**Issue by aayushm9595** [stripe/stripe-react-native#345]
**I am using using version "@stripe/stripe-react-native": "0.1.4" and on confirmSetupIntent I get the error **_Card details not complete_** in all scenarios when I use my own custom card input and pass all the required arguments in same format**

**To Reproduce**
We have our own custom UI for getting user payment details and on submission of the same with fields populated in paymentDetails object 

```
const { setupIntent, error } = await confirmSetupIntent(res, {
        type: 'Card',
        
        billingDetails,
        
        paymentDetails,
        
      });
```
- I can confirm that the object is of exact format as the one with Card Field Component provided by Stripe Library 
as I added logs to /node_modules/@stripe/stripe-react-native/src/functions.ts below function
```
export const confirmSetupIntent = async (
  paymentIntentClientSecret: string,
  data: ConfirmSetupIntent.Params,
  options: ConfirmSetupIntent.Options = {}
): Promise<ConfirmSetupIntentResult> => {
  try {
    console.log('paymentIntentClientSecret', paymentIntentClientSecret)
    console.log('data', data)
    console.log('options', options)
    const { setupIntent, error } = await NativeStripeSdk.confirmSetupIntent(
      paymentIntentClientSecret,
      data,
      options
    );
    if (error) {
      return {
        error,
      };
    }
    return {
      setupIntent: setupIntent!,
    };
  } catch (error) {
    return {
      error: createError(error),
    };
  }
};
```

```
<CardField
        postalCodeEnabled={false}
        placeholder={{
          number: 'Card Number',
        }} 
          cardStyle={{
            backgroundColor: "#DCDAF6",
            textColor: !isCardValid ? '#ff0000' : "#000000",
            fontSize: 15,
            borderRadius: 10
          }}
        style={{  
          width: '90%',
          height: 50,
          alignSelf: 'center',
          marginVertical: 9,
          marginBottom: 20
        }}
        onCardChange={(cardDetails) => {
          console.log('cardDetails', cardDetails)
          setPayment(cardDetails)
          cardValidator(true)
        }}
        onFocus={(focusedField) => {
          console.log('focusField', focusedField);
        }}
      /> 
```

- Make use of your own custom card 

- Getting incomplete card details error

**Expected behavior**
To get the custom card input work exactly as CardField Component provided by Stripe

**Screenshots**
One with our own custom card input
![image](https://user-images.githubusercontent.com/50030865/122099192-5c2a6880-ce2f-11eb-9e10-8ddfb72b107c.png)

**Desktop (please complete the following information):**
 - OS: iOS and android Both
 - Version RN Version 0.63.4 and  "@stripe/stripe-react-native": "0.1.4"

**Additional context**
Trying to get custom ui on card input field

**Comment by thorsten-stripe** [comment]
Custom UI is not supported due to PCI compliance requirements: https://stripe.com/docs/security/guide#validating-pci-compliance
![image](https://user-images.githubusercontent.com/23213994/122151917-fd96d600-ce92-11eb-8cb1-5902a08f2546.png)
Please use either the payment sheet or the `CardField` component to handle card data as outlined in the docs: https://stripe.com/docs/payments/accept-a-payment?platform=react-native

**Comment by smeetagrawal** [comment]
Hi, I want to create custom input for card number, expiry date and cvc number. Is it possible to create it using stripe-react-native package.

Right now I am using cardfield for getting information from users in our app.
