### ISSUE TITLE
Create card from scratch without using Stripe UI

### ISSUE THREAD

**Issue by kyle-ssg** [stripe/stripe-react-native#346]
We were previously using a card scanning library as a way of creating a stripe card with tipsi-stripe SDK. As far as I can see, there's no way to create a payment method by specifying card fields (expiry,number,cvv).

I'm wondering if I'm missing something here or whether this will be allowed in the future?

**Comment by thorsten-stripe** [comment]
There are currently no plans to support this due to the PCI compliance considerations this has (e.g. see https://github.com/stripe/stripe-react-native/issues/178#issuecomment-831651413) We recommend to migrate to use the payment sheet or the `CardField` component.

**Comment by agentscamp5** [comment]
@thorsten-stripe I don't understand why PCI compliance is a blocker for there to be a way to use this package without the UI components (which my team was doing when we had a pre-v1.0.0 beta version of this package a couple month ago).

There was already just recently added a new field called `dangerouslyGetFullCardDetails` that has a comment warning that if you use it, you are responsible for making sure you are PCI compliant so there is already a way to accidentally break PCI compliance in this package.

My company is already working on proving/maintaining PCI compliance for other reasons and our design/UX is very important to our brand, we very extremely want to use our own forms and not the pre-built ones (we never send any card info to the server).
