### ISSUE TITLE
Hi,how should I use the  promotion code

### ISSUE THREAD

**Issue by Sirzs** [stripe/stripe-react-native#347]
https://stripe.com/docs/api/promotion_codes

**Comment by trex-quo** [comment]
Make an API request to create a promotion code or create it in the Stripe dashboard. When creating a subscription for the user, you can pass it in as an optional parameter

https://stripe.com/docs/api/subscriptions/create

**Comment by thorsten-stripe** [comment]
Please only use the issues for bug reports and feature requests. For general integration questions please use our support form (https://support.stripe.com/) or technical chat on IRC https://webchat.freenode.net/#stripe
