### ISSUE TITLE
Element CardField crashes on Android (RN v 0.64.0) 

### ISSUE THREAD

**Issue by aayushm9595** [stripe/stripe-react-native#348]
**Describe the bug**
The CardField provided by the library crashes on React Native version .64 on android platform on tap on the input fields (works fine on lowering the react native version to 0.63)

**To Reproduce**

```
<CardField
        postalCodeEnabled={false}
        placeholder={{
          number: 'Card Number',
        }} 
          cardStyle={{
            backgroundColor: "#DCDAF6",
            textColor: !isCardValid ? '#ff0000' : "#000000",
            fontSize: 15,
            borderRadius: 10
          }}
        style={{  
          width: '90%',
          height: 50,
          alignSelf: 'center',
          marginVertical: 9,
          marginBottom: 20
        }}
        onCardChange={(cardDetails) => {
          console.log('cardDetails', cardDetails)
          setPayment(cardDetails)
          cardValidator(true)
        }}
        onFocus={(focusedField) => {
          console.log('focusField', focusedField);
        }}
      />
```
      
      
import this element from library on latest react native element and tap to enter card number details and observe crash

**Expected behavior**
The element should take input of custom card details for submission of payment method

**Desktop (please complete the following information):**
 - Development OS: MacOS 11.4 
 - MObile OS: Android 11

**Comment by AlexGrump** [comment]
A similar problem. The application closes silently without errors by tapping on CardField while autofocus works normally

**Comment by IbrarButt** [comment]
Facing, similar problem on android by tapping on the CardField android app crashes.

**Comment by DaveyvdBogaard** [comment]
Similar problem here. CardField works for iOS but crashes when used on Android (using RN v0.64.1)

**Comment by Frankisgek** [comment]
We are experiencing the same problem using RN 0.64.x. Android crashes occasionally when CardField is openend or clicked a few times in a row. No errors.

**Comment by EinarHm** [comment]
Similar issue: "CardField" was not found in UIManager work fine in IOS
