### ISSUE TITLE
createPaymentMethod should also work with card from token

### ISSUE THREAD

**Issue by jonasbark** [stripe/stripe-react-native#349]
A related issue for Flutter: https://github.com/flutter-stripe/flutter_stripe/issues/153
Possibly related: https://github.com/stripe/stripe-react-native/issues/239

Essentially it should be possible to create a payment method based on the token that was received with Google / Apple Pay. Right now it's not possible because createPaymentMethod relies only on the information provided from the card field.

**Comment by thorsten-stripe** [comment]
`confirmPayment` allows to pass in a token, that's the only client-side use case I see. Otherwise you can send the token to your server and attach it to a customer there etc.

Why would you need to create a payment method from a token client-side?

**Comment by markphillips100** [comment]
Well in my specific use case my backend only deals with a payment method (no tokens), whether that was created from a credit card or via native pay.  Hence the reason I expected to use the token to obtain a payment method.

**Comment by thorsten-stripe** [comment]
@markphillips100 can you describe your flow a bit more please. Your backend can turn the token into a payment method if needed: https://stripe.com/docs/api/payment_methods/create#create_payment_method-card

**Comment by markphillips100** [comment]
I use an event driven architecture at the backend so "place order" from a client perspective doesn't give me the opportunity to confirm payment.  The payment flow works this way:

1. On user selecting place order, payment method Id for the order is sent to the backend resulting in a message being placed on a queue.  Client is now waiting for a message from server (via websocket) to determine what to do next.  It could receive a message to confirm payment or something else may need resolution, e.g. different payment method, etc.
2. Backend event handler takes care of creating the required payment intent from the supplied payment method.
3. Backend webhook receives stripe response from creation of payment intent and decides what to do next, e.g. send a message for client to confirm payment, etc.

I agree I can extend my backend api to support both a payment method Id or a token for step 1.  That's my plan B.  Plan A was to see if I can get away with no change to my code :-) .

If createPaymentMethod isn't meant to be used in this way then maybe Plan B is the only option and perhaps @jonasbark maybe indicate in migration doc the use case is not supported and what the alternative is?

**Comment by thorsten-stripe** [comment]
@markphillips100 thanks for the details. Yes, you will need some backend changes, but they should be minimal as you can pass a token to payment intent creation directly via `payment_method_data`: 

```
curl https://api.stripe.com/v1/payment_intents \
  -u sk_test_xxx: \
  -d amount=2000 \
  -d currency=usd \
  -d "payment_method_types[]"=card \
  -d confirm=true \
  -d "payment_method_data[type]"="card" \
  -d "payment_method_data[card][token]"="tok_visa"
```
