### ISSUE TITLE
useApplePay, ApplePayButton, presentApplePay does not work at all

### ISSUE THREAD

**Issue by atalon-kn** [stripe/stripe-react-native#351]
From the doc here: https://stripe.com/docs/apple-pay?platform=react-native
- isApplePaySupported function from useApplePay hook always returns Apple Pay not available even it is indeed available
- ApplePayButton component does not show up
- presentApplePay always return error saying Apple Pay is not available

**To Reproduce**
follow the steps of the official doc: https://stripe.com/docs/apple-pay?platform=react-native

**Expected behavior**
an apple pay button which can handle payment properly: https://stripe.com/docs/apple-pay?platform=react-native

**Screenshots**
https://stripe.com/docs/apple-pay?platform=react-native

tested on ipad and iphone devices

**Comment by thorsten-stripe** [comment]
Did you follow all the necessary setup steps: https://stripe.com/docs/apple-pay?platform=react-native#accept ?

Also do note that Apple Pay is only considered available when you have an active payment method set up in Apple Pay.
![image](https://user-images.githubusercontent.com/23213994/122418697-f9ff6e00-cfbc-11eb-8021-1cda280f59f0.png)

Closing this out as we know that with proper setup and configuration Apple Pay does work.

**Comment by atalon-kn** [comment]
@thorsten-stripe I have set up apple pay properly as I can use it with initPaymentSheet with applePay set to 'true'.
I have also set up apple pay using [useApplePay, ApplePayButton, presentApplePay] according to https://stripe.com/docs/apple-pay?platform=react-native and my app has been launched to App Store.
However, only the payment sheet works but the Apple Pay module does not work at all.

**Comment by atalon-kn** [comment]
@thorsten-stripe the style prop of ApplePayButton is not optional, need to specify the height and width for the button to show, please update the doc or set default value to the button.

**Comment by thorsten-stripe** [comment]
You're right, that's not clear in the docs, thanks for flagging!
