### ISSUE TITLE
[Question] Replacement for `confirmPaymentIntent` and hooks vs class components

### ISSUE THREAD

**Issue by lucasfronza** [stripe/stripe-react-native#356]
Hey 👋 

Sorry if this isn't the best place to ask questions, but I didn't find a better place for it...

1 - I'm coming from `tipsi-stripe`, and we still use `confirmPaymentIntent`. I do understand, from Stripe docs, that this method is deprecated. But I wonder if there's a replacement for this method, and if so, which one would it be.
If not, are there any tutorials on Stripe about how to migrate from it?

2- I've noticed that pretty much everything in this library is under `useStripe()` and thus being used as hooks. Are there any plans to allow functions like `confirmSetupIntent` to be used in class components? (unless I'm missing something, and that is already the case 😅 )

It's really nice to finally have an official React Native SDK for Stripe. Looking forward to finishing the integration and start testing it. :)

Thanks in advance!

**Comment by thorsten-stripe** [comment]
> 1 - I'm coming from tipsi-stripe, and we still use confirmPaymentIntent. I do understand, from Stripe docs, that this method is deprecated. But I wonder if there's a replacement for this method, and if so, which one would it be.
If not, are there any tutorials on Stripe about how to migrate from it?

In this library you use `confirmPaymentMethod` instead: https://stripe.dev/stripe-react-native/api-reference/modules.html#confirmpaymentmethod. The docs are here: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom Note that in the docs the hook is being used which exports the method `confirmPayment`. The top level export however is called `confirmPaymentMethod`. 

2- I've noticed that pretty much everything in this library is under useStripe() and thus being used as hooks. Are there any plans to allow functions like confirmSetupIntent to be used in class components? (unless I'm missing something, and that is already the case 😅 )

All functions are also provided as top-level imports, so usage of hooks is not required.
