### ISSUE TITLE
confirmPayment returns nothing after success payment 

### ISSUE THREAD

**Issue by shanutthankachan** [stripe/stripe-react-native#363]
**Describe the bug**
When calling confirmPayment with the card 4242 4242 4242 4242 ( which is expected to success ), then succesfull payment retuns nothing,but error works 

**To Reproduce**

```
      const {paymentIntent, error} = await confirmPayment(clientSecret, {
        type: 'Card',
        BillingDetails:{ .... },
      });

    if (error) {
      console.log('Payment confirmation error', error); // works 
    } else if (paymentIntent) {
      console.log('Success from promise', paymentIntent); // no paymentIntent shows 
    }
```

**Expected behavior**
paymentIntent

**Desktop :**
 - OS: Ubuntu 
 - Browser : Brave 

**Smartphone :**
 - Device:MI
 - OS: Android 

**Additional context**
Following Docs  :[ accept paymnet ](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom)
Expo 41

**Comment by thorsten-stripe** [comment]
You need to install the exact version of the library which is supported in Expo, which for Expo SDK 41 is `@stripe/stripe-react-native` v 0.1.1 (`@stripe/stripe-react-native@0.1.1`)

You should see this in the expo logs when starting the metro server:
![image](https://user-images.githubusercontent.com/23213994/122964580-fe12fd80-d3b9-11eb-958f-93c47fc30a56.png)

You can fix this by running `expo install @stripe/stripe-react-native`
