### ISSUE TITLE
error: module map file .../Charts.modulemap' not found [IOS only] 

### ISSUE THREAD

**Issue by AlixH** [stripe/stripe-react-native#365]
**Describe the bug**
I have installed stripe-react-native on my project which also includes the lib react-native-charts-wrapper.
After stripe-react-native installation, I faced the issue 'Undefined symbols for architecture x86_64' which I solved thanks the the troublshooting doc. Since then, I am facing the following error on my release build:
<img width="1374" alt="Screenshot 2021-06-22 at 17 29 17" src="https://user-images.githubusercontent.com/32574035/122954031-62649b80-d37f-11eb-876c-b087e6ed9c26.png">

**To Reproduce**
1. Install react-native-stripe
2. Install react-native-charts-wrapper
3. Remove the swift related entries in library search paths as said in the troubleshooting doc of stripe-react-native
4. Try to build 

**Expected behavior**
IOS build works 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS

  - Version: 
  "react-native-charts-wrapper": "^0.5.7",    
   "react": "17.0.1",
   "react-native": "0.64.2",
    "@stripe/stripe-react-native": "^0.1.2",
  - Platform: MacOS with  IntelliJ and GitHub build pipeline to build the release
  - XCode 12.5

**Issue has been opened also in the react-native-charts-wrapper repository :**
 https://github.com/wuxudong/react-native-charts-wrapper/issues/813

**Comment by thorsten-stripe** [comment]
Hey @AlixH, can you try the steps outlined here? https://stackoverflow.com/questions/55675694/how-to-fix-cocoapod-modulemap-file-not-found

**Comment by AlixH** [comment]
Thanks a lot, I found the solution in the link provided.
Stipe made me do a IOS version bump to 11.0 in the PodFile but I had to do the same version bump inside the project.pbxproj (or directly from XCode in the Build Settings -> IOS deployment target)
