### ISSUE TITLE
Discrepancy between Date handling on iOS and Android

### ISSUE THREAD

**Issue by jonasbark** [stripe/stripe-react-native#368]
We noticed a discrepancy between iOS / Android regarding "created" attribute on PaymentIntent on the native side:

https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/Mappers.kt#L328 -> created is a string
https://github.com/stripe/stripe-react-native/blob/master/ios/Mappers.swift#L360 -> created is an int
https://github.com/stripe/stripe-react-native/blob/master/src/types/PaymentIntents.ts#L7 -> created is a string

I'm not sure if it has an effect on React Native itself but it does on Android. Adjusting convertToUnitTimestamp on Mappers.kt on Android to return a String would fix this issue.

**Comment by arekkubaczkowski** [comment]
Which version of library do you use? 
https://github.com/stripe/stripe-react-native/blob/master/ios/Mappers.swift#L824 
`convertDateToUnixTimestamp` returns string so it should be consistent with the rest of cases

**Comment by arekkubaczkowski** [comment]
@jonasbark ok I guess you meant that on ios 'created` is a string but on android is `int` right?
