### ISSUE TITLE
Error appear after some days, without having change the integrated code: "null is not an object (evaluating '_await$NativeStripeSd9.paymentOption')"

### ISSUE THREAD

**Issue by actaruss** [stripe/stripe-react-native#369]
**Describe the bug**
Hello,
I'm using expo on an IOS simulator. I had a perfectly integrated payment system on my plateform, using stripe-react-native on the app. But now I'm getting this error object when I call the "initPaymentSheet" function:
```
 {
  "error": Object {
    "code": undefined,
    "declineCode": undefined,
    "localizedMessage": undefined,
    "message": "null is not an object (evaluating '_await$NativeStripeSd9.paymentOption')",
    "stripeErrorCode": undefined,
    "type": undefined,
  },
}
```
**To Reproduce**
1. Install and init the StripeProvider at the top of my application
2. Create a component that return null but which is handling the init from stripe
3. Try to call the "initPaymentSheet" of "useStripe()" hook in the component, with those params:
         customerId, 
         customerEphemeralKeySecret, 
         paymentIntentClientSecret
4. See error (as result of the promise): 
```
{
  "error": Object {
    "code": undefined,
    "declineCode": undefined,
    "localizedMessage": undefined,
    "message": "null is not an object (evaluating '_await$NativeStripeSd9.paymentOption')",
    "stripeErrorCode": undefined,
    "type": undefined,
  }

```
**Expected behavior**
Not supposed to have an error

**Screenshots**

![Screenshot 2021-06-24 at 13 26 51](https://user-images.githubusercontent.com/15266924/123306911-261d7080-d522-11eb-962b-a6078bae7dce.jpg)
![Screenshot 2021-06-24 at 13 15 38](https://user-images.githubusercontent.com/15266924/123306523-b1e2cd00-d521-11eb-839d-0ff941eb44a6.jpg)

**Desktop (please complete the following information):**
 - OS: [MacOs Catalina 10.15.6]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS12.2]

**Additional context**
This code worked perfectly at the begining but did appeat recently without any changes on the code.

The backend correctly return the expected data:
```
 {
  "customerEphemeralKeySecret": "ek_test_YWNj*****",
  "customerId": "cus_JjP*****",
  "paymentIntentClientSecret": "pi_1J*****",
}

```
Here is the code of the function:
```
	const { initPaymentSheet, presentPaymentSheet } = useStripe()

	const initializePaymentSheet = useCallback(async () => {
		try {
			const paymentIntent = await fetchPaymentSheetParams()

			const { client_secret, ephemeral_key, customer_id } = paymentIntent

			const initData = {
				customerId: customer_id,
				customerEphemeralKeySecret: ephemeral_key,
				paymentIntentClientSecret: client_secret,
			}

			const result = await initPaymentSheet(initData)

			if (result.error) {
				console.log(result.error)
				throw result.error
			}
			if (_isMounted()) {
				setClientPaymentIntent(paymentIntent)
				onLoad?.()
			}
		} catch (error) {
			_onError()
		}
	}, [
		initPaymentSheet,
		onLoad,
		_isMounted,
		_onError,
	])
```

**Comment by thorsten-stripe** [comment]
What's your Expo Go client version, your Expo SDK version, and your `stripe-react-native` version? Are they potentially out of sync?

Can you try running `expo install @stripe/stripe-react-native` and see if that resolves it?

**Comment by actaruss** [comment]
The command `expo install @stripe/stripe-react-native` did work !!!
Big thanks @thorsten-stripe we didn't think about that.
We did an upgrade to "@stripe/stripe-react-native": "^0.1.4" recently.
But when we run `expo install @stripe/stripe-react-native` it passed to :
"@stripe/stripe-react-native": "0.1.1",
Obviously we had some missing dependancy for the last version. Big thanks !!!

**Comment by teamalfy-technical** [comment]
TypeError: undefined is not an object (evaluating 'setupIntent.paymentMethodId')]
i have issues here code was working perfectly until today
