### ISSUE TITLE
[EXPO GO] 3D secure not return to Expo

### ISSUE THREAD

**Issue by shanutthankachan** [stripe/stripe-react-native#370]
**Describe the bug**
Cards like Authentication required: 4000 0027 6000 3184, lead to hooks.stripe.com as a webview and  return to **Expo App Home** aftere succefull or failure payment .

also, click on complete authentication or fail clicks then,  If close the webview trigger back to **App screen** .

**To Reproduce**
`            <StripeProvider
            publishableKey="***************************"
            urlScheme="exp://192.168.1.102:19000"
                threeDSecureParams={{
                 // backgroundColor: '#FFFFFF', // iOS only
                  timeout: 5,
                  label: {
                   // headingTextColor: '#0000',
                    headingFontSize: 13,
                  },
                  navigationBar: {
                    headerText: '3d secure',
                  },
                  footer: { // iOS only
                    backgroundColor: '#FFFFFF',
                  },
                  submitButton: {
                   // backgroundColor: '#000000',
                    cornerRadius: 12,
                    textColor: '#FFFFFF',
                    textFontSize: 14,
                  },
                }}            
            > `

**Screenshots**
![Hooks Stripe webview](https://i.ibb.co/RgkM8BK/1.png)
![App Screen](https://i.ibb.co/TrnQ64d/2.png)
![Expo App Home](https://i.ibb.co/72kC924/3.png)

**Additional context**
Expo Go , Expo 41, stripe-react-native :0.1.1

**Comment by thorsten-stripe** [comment]
@shanutthankachan can you try `urlScheme="exp://192.168.1.102:19000/--/"` and see if that works?

But yah, I think it's not ideal atm. @cruzach do you have any recommendations how we can make this better for usage with Expo Go?

**Comment by shanutthankachan** [comment]
> /--/

clicks on "Complete Authentication"  returns to the same "3d secure test payment Page"

**Comment by thorsten-stripe** [comment]
@shanutthankachan to automatically dismiss the webview you have to implement deep link handling: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/HomeScreen.tsx#L17-L25

**Comment by shanutthankachan** [comment]
above solution is not working 
https://snack.expo.io/@charliecruzan/stripe-react-native-example,

**Comment by cruzach** [comment]
The snack example above works for the Prebuilt UI screens, but for the webhook payment after clicking "confirm authentication" I see "Safari cannot open the page because the address is invalid" (not sure what the difference is between those two in regards to where the redirect is pointing @thorsten-stripe)

But as for urlScheme redirects- you should use [`Linking.createUrl()`](https://docs.expo.io/versions/latest/sdk/linking/#linkingcreateurlpath-options) to get the scheme of your app. However, in Snack, you cannot set the app scheme, so you'll have to run a project locally

**Comment by shanutthankachan** [comment]
@thorsten-stripe  @cruzach  Google Sign In ( [Expo](https://docs.expo.io/versions/latest/sdk/app-auth/) ) using the same method they return back with successfully, then why don't you

**Comment by shanutthankachan** [comment]
could you please give me a working example, If it fails or not wanna redirect to the App screen and goes to the next step, I think Stripe should help me with this?

**Comment by cruzach** [comment]
I can confirm that the example works when you run it locally (not via a Snack), and pass `urlScheme: Linking.createURL('') + '/--/'` into `initStripe`

**Comment by shanutthankachan** [comment]
> I can confirm that the example works when you run it locally (not via a Snack), and pass `urlScheme: Linking.createURL('') + '/--/'` into `initStripe`

what will do in production @cruzach

**Comment by cruzach** [comment]
https://docs.expo.io/versions/latest/sdk/linking/#linkingcreateurlpath-options

**Comment by KryptKode** [comment]
> I can confirm that the example works when you run it locally (not via a Snack), and pass `urlScheme: Linking.createURL('') + '/--/'` into `initStripe`

This doesn't work for me. I am running locally, it doesn't close the WebView and return to the app on Expo. Can you share a snippet? Was there something else you added?

**Comment by cruzach** [comment]
@KryptKode I'm using the example from Stripe (also found in the Expo docs), with this change applied:
```
--- a/example/src/components/PaymentScreen.tsx
+++ b/example/src/components/PaymentScreen.tsx
@@ -3,6 +3,7 @@ import React, { useEffect, useState } from 'react';
 import { ActivityIndicator, ScrollView, StyleSheet, Text } from 'react-native';
 import { colors } from '../colors';
 import { fetchPublishableKey } from '../helpers';
+import * as Linking from 'expo-linking';
 interface Props {
   paymentMethod?: string;
@@ -18,7 +19,7 @@ const PaymentScreen: React.FC<Props> = ({ paymentMethod, children }) => {
         await initStripe({
           publishableKey,
           merchantIdentifier: 'merchant.com.stripe.react.native',
-          urlScheme: 'stripe-example',
+          urlScheme: Linking.createURL('') + '/--/',
           setUrlSchemeOnAndroid: true,
         });
         setLoading(false);
(END)
```

- run the example and server
- accept a payment -> card element only screen
- use `4000 0027 6000 3184`
- webview opens, click succeed, then im redirected back to the app and payment is successful

**Comment by thorsten-stripe** [comment]
@KryptKode you might be missing the `handleURLCallback` call. You can find an example here: https://github.com/stripe-samples/accept-a-payment/pull/193/files#diff-14f2faf1e4844e7e9e5bcbb71bea64e1dd27d9c09f0a05aa6d02fec208f9173aR16

**Comment by shanutthankachan** [comment]
> @KryptKode I'm using the example from Stripe (also found in the Expo docs), with this change applied:
> 
> ```
> --- a/example/src/components/PaymentScreen.tsx
> +++ b/example/src/components/PaymentScreen.tsx
> @@ -3,6 +3,7 @@ import React, { useEffect, useState } from 'react';
>  import { ActivityIndicator, ScrollView, StyleSheet, Text } from 'react-native';
>  import { colors } from '../colors';
>  import { fetchPublishableKey } from '../helpers';
> +import * as Linking from 'expo-linking';
>  interface Props {
>    paymentMethod?: string;
> @@ -18,7 +19,7 @@ const PaymentScreen: React.FC<Props> = ({ paymentMethod, children }) => {
>          await initStripe({
>            publishableKey,
>            merchantIdentifier: 'merchant.com.stripe.react.native',
> -          urlScheme: 'stripe-example',
> +          urlScheme: Linking.createURL('') + '/--/',
>            setUrlSchemeOnAndroid: true,
>          });
>          setLoading(false);
> (END)
> ```
> 
> * run the example and server
> * accept a payment -> card element only screen
> * use `4000 0027 6000 3184`
> * webview opens, click succeed, then im redirected back to the app and payment is successful

standalone app gives an error, 
```
400 Error
POST /v1/payment_intents/pi_3JSeHwSJwGztdZyL1BuqSJQq/confirm
"return_url": "app:///--/://safepay",
url_invalid - return_url Not a valid URL
```

**Comment by shanutthankachan** [comment]
> @KryptKode I'm using the example from Stripe (also found in the Expo docs), with this change applied:
> 
> ```
> --- a/example/src/components/PaymentScreen.tsx
> +++ b/example/src/components/PaymentScreen.tsx
> @@ -3,6 +3,7 @@ import React, { useEffect, useState } from 'react';
>  import { ActivityIndicator, ScrollView, StyleSheet, Text } from 'react-native';
>  import { colors } from '../colors';
>  import { fetchPublishableKey } from '../helpers';
> +import * as Linking from 'expo-linking';
>  interface Props {
>    paymentMethod?: string;
> @@ -18,7 +19,7 @@ const PaymentScreen: React.FC<Props> = ({ paymentMethod, children }) => {
>          await initStripe({
>            publishableKey,
>            merchantIdentifier: 'merchant.com.stripe.react.native',
> -          urlScheme: 'stripe-example',
> +          urlScheme: Linking.createURL('') + '/--/',
>            setUrlSchemeOnAndroid: true,
>          });
>          setLoading(false);
> (END)
> ```
> 
> * run the example and server
> * accept a payment -> card element only screen
> * use `4000 0027 6000 3184`
> * webview opens, click succeed, then im redirected back to the app and payment is successful

standalone app gives an error,

400 Error
POST /v1/payment_intents/pi_3JSeHwSJwGztdZyL1BuqSJQq/confirm
"return_url": "app:///--/://safepay",
url_invalid - return_url Not a valid URL

**Comment by shanutthankachan** [comment]
> > I can confirm that the example works when you run it locally (not via a Snack), and pass `urlScheme: Linking.createURL('') + '/--/'` into `initStripe`
> 
> This doesn't work for me. I am running locally, on android, it doesn't close the WebView and return to the app on Expo. Can you share a snippet? Was there something else you added?

its not work in standalone app, do you have any suggestion?

**Comment by arekkubaczkowski** [comment]
> @KryptKode you might be missing the handleURLCallback call. You can find an example here: https://github.com/stripe-samples/accept-a-payment/pull/193/files#diff-14f2faf1e4844e7e9e5bcbb71bea64e1dd27d9c09f0a05aa6d02fec208f9173aR16

@shanutthankachan have you tried that?

**Comment by shanutthankachan** [comment]
> > @KryptKode you might be missing the handleURLCallback call. You can find an example here: https://github.com/stripe-samples/accept-a-payment/pull/193/files#diff-14f2faf1e4844e7e9e5bcbb71bea64e1dd27d9c09f0a05aa6d02fec208f9173aR16
> 
> @shanutthankachan have you tried that?

yes, https://github.com/stripe/stripe-react-native/issues/539

but something wrong :(

**Comment by DariusPirvulescu** [comment]
> @shanutthankachan to automatically dismiss the webview you have to implement deep link handling: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/HomeScreen.tsx#L17-L25

For future reference.

```
return () => deepLinkListener.remove();
```
This [line](https://github.com/stripe/stripe-react-native/blob/ed01df67b9a9eecbaace12325bed9fbf52aa7ba0/example/src/screens/HomeScreen.tsx#L45) was throwing an error in TS:
> Property 'remove' does not exist on type 'void'

I replaced everything with:
```
[...]
    // ListenerCallback
    const listenerCallback = (event: {url: string}) => {
      handleDeepLink(event.url);
    };

    // Create URL listener event
    Linking.addEventListener("url", listenerCallback);

    // Remove Listener
    return () => { return Linking.removeEventListener("url", listenerCallback); };
```

I tested and it was still redirecting the app back to Main menu screen on Expo (the last photo from [shanutthankachan](https://github.com/shanutthankachan)'s report). Only after I opened the app it displayed the right page.

Will look more into it.
