### ISSUE TITLE
Migrate from Tipsi Stripe & Payment Using Custom Card Field

### ISSUE THREAD

**Issue by hbole** [stripe/stripe-react-native#372]
Hi,

I have been using `tipsi-stripe` in my app to make payments. But with new google play policies, I am unable to upload apks to the play store.
So here is my flow which I use to pay using stripe via `tipsi-stripe` 

I have my own custom card field which collects name, card number, expiry month, expiry year, and cvv.
With these details I create a token. (https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html)
Using the generated token, I create a payment method for the card.(https://tipsi.github.io/tipsi-stripe/docs/paymentIntents.html)

Once payment method is generated, I use the payment method id to and send it to backend along with the currency and cvv to pay the desired amount.
The backend creates payment intents and proceeds further. If any authorization is required for the payment, the backend returns with appropriate message and payment intent is confirmed on client side using ```tipsi-stripe``` ```using await stripe.authenticatePaymentIntent({ clientSecret: "..." })```, passing in the client_secret that I receive. (https://tipsi.github.io/tipsi-stripe/docs/paymentIntents.html)

With the new official sdk in place, I am totally lost on how to replicate the same with this official SDK. And also enable to save cards for future.
Please help

**Comment by thorsten-stripe** [comment]
> I have my own custom card field which collects name, card number, expiry month, expiry year, and cvv.

This is not supported as it has PCI compliance implications. Please use the `CardField` component to collect card details: https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native#react-native-create-checkout-page

> With these details I create a token. (https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html)
Using the generated token, I create a payment method for the card.(https://tipsi.github.io/tipsi-stripe/docs/paymentIntents.html)

Tokens are legacy, please create a payment method directly: https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native#react-native-collect-card-details

> The backend creates payment intents and proceeds further. If any authorization is required for the payment, the backend returns with appropriate message and payment intent is confirmed on client side using tipsi-stripe using await stripe.authenticatePaymentIntent({ clientSecret: "..." }), passing in the client_secret that I receive. (https://tipsi.github.io/tipsi-stripe/docs/paymentIntents.html)

Use `handleCardAction`: https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native#react-native-handle-next-actions

Hope this helps, thanks for taking the effort to migrate, we appreciate it! :)

**Comment by hbole** [comment]
@thorsten-stripe It would be more helpful, If you help me with saving cards for future use

**Comment by thorsten-stripe** [comment]
https://stripe.com/docs/payments/save-and-reuse?platform=react-native

**Comment by hbole** [comment]
Thanks @thorsten-stripe :)
