### ISSUE TITLE
presentPaymentSheet is not opneing the payment sheet. 

### ISSUE THREAD

**Issue by techTutorialsYTube** [stripe/stripe-react-native#373]
**Describe the bug**
presentPaymentSheet Does not open the payment sheet.  For the first time when we call presentPaymentSheet nothing happens.
But if we call it again it open the page with old paymentintent values ( price) 

**To Reproduce**
This is my code. When I call openPaymentPage on app load. Nothing seems to happen. There is no error. 
But if i call openPaymentPage  again. The payment page will open but it's for the old paymentIntent and the payment will succeed if i continue. 
```
// ---- 
const { user } = useContext(LoginContext);
  const { initPaymentSheet, presentPaymentSheet } = useStripe();

  const getPaymentIntent = async () => {

    let response = await BackendUtil.post(user, CHECKOUT_GET_PAYMENT_INTENT);
    const { paymentIntent, ephemeralKey, customer } = await response.json();
    const { error } = await initPaymentSheet({
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,
    });

    if (error) {
      Alert.alert('OK, SOMETHING IS WRONG... NO IDEA WHAT');
    }
    return paymentIntent;
  };

  const openPaymentPage = async () => {
    const paymentIntent = await getPaymentIntent();
    const { error } = await presentPaymentSheet({
      clientSecret: paymentIntent,
    });
    if (error) {
      Alert.alert(`Error code: ${error.code}`, error.message);
    } else {
      Alert.alert('Success', 'Your order is confirmed!');
      setList([]);
    }
  };

  return openPaymentPage;
```
**Expected behavior**
Should be consistent. Its should show correct payment intent information. 

**Desktop (please complete the following information):**
 - Windows

**Smartphone (please complete the following information):**
 - android emulator. 
 
**Additional context**
 "@stripe/stripe-react-native": "^0.1.4",
I have created the app with the expo bare workflow.

**Comment by trex-quo** [comment]
I believe this one is being tracked already
https://github.com/stripe/stripe-react-native/issues/315
