### ISSUE TITLE
Payment Option undefined when calling initPaymentSheet , presentPaymentSheet not working?

### ISSUE THREAD

**Issue by NikolaP93** [stripe/stripe-react-native#375]
**Describe the bug**

I would like to display the prebuilt payment sheet

**To Reproduce**
I wrapped my whole app with the Stripe provider, and gave it my publishableKey like so:

`  <StripeProvider publishableKey="mypublishabletestkey">
        <App/>
      </StripeProvider>`

And in the App I have 

`
const result = await initPaymentSheet({
        customerId: customer.id,
        customerEphemeralKeySecret: ephemeralKey.secret,
        setupIntentClientSecret: paymentIntent.client_secret,
      })
console.log(result)

{"paymentOption": undefined}

As you can see, I keep getting payment option as undefined here, here are my keys

ephemeralKey: ephkey_1J7KbPKN3W88XVfoQ7khNUSu 
customerId: cus_JkocvtKKkryYU0 
paymentIntentId: pi_1J7KbQKN3W88XVfoB4s0vmoj

When I try to hardcode my client secret into the presentPaymentSheet and log the response, nothing happens, any log that falls under the method does not get called
`

**Expected behavior**
Either I should get a response when initializing , which I get as paymentOption: undefinde OR a modal should pop up when I try to call presentPaymentSheet

**Screenshots**
<img width="457" alt="Screen Shot 2021-06-28 at 15 39 02" src="https://user-images.githubusercontent.com/39632973/123645838-f8d50900-d826-11eb-82ba-0a8de15c922b.png">

Both have been tested in Android & IOS simulator and nothing seems to work

**Comment by thorsten-stripe** [comment]
Please provide your library and RN versions and which devices you're testing on.

But it's very likely this https://github.com/stripe/stripe-react-native/issues/290#issuecomment-852774950

Do reopen the issue if that doesn't resolve it. Thanks.

**Comment by seema2406** [comment]
I am facing the same issue. I have added publishable key like this
`<StripeProvider publishableKey='publishable_key'>
        <Provider store={store.store}>
          <PersistGate loading={null} persistor={store.persistor}>
            <AppContainer />
          </PersistGate>
        </Provider>
      </StripeProvider>`

after that i have used that initPaymentSheet but getting **{"paymentOption": undefined}**. here is the code 
` const {error, paymentOption} = await initPaymentSheet({
        customerId: 'cus_JroC8UIBU5Os5z',
        customerEphemeralKeySecret: 'ek_test_YWNjdF8xRmlpY2dHWjVSU0psQXpvLElLNGJZSmt4dTNFZ1BIRE9WN2p3S0dGdlhOMGZOWEs_00RcwRBn6m',
        paymentIntentClientSecret: 'pi_1JE4aaGZ5RSJlAzooKs7Cpej_secret_9FslhNiomCVchtdXUVIMkmfSb',
        googlePay: true,
        merchantCountryCode: 'US',
        testEnv: true,
      });`

**Comment by daveadapptor** [comment]
I'm seeing the same issue, paymentOption comes back as undefined on both Android and iOS.  
Using :  "@stripe/stripe-react-native": "^0.2.3",     "react-native": "0.63.4".
I can see the payment_method coming back in the response from the api call and if I re-open the payment sheet with the same customer id I can see the card has been added so its working its simply that the data isn't being exposed correctly.  I'm looking into the actual code to see if I can identify why that is.

**Comment by NikolaP93** [comment]
@daveadapptor I managed to solve this a while ago, you need to pass in your client secret like so

presentPaymentSheet({
            clientSecret: client_secret
        })
        
But you need to obtain that from your backend

**Comment by daveadapptor** [comment]
@NikolaP93 presentPaymentSheet doesn't have any parameters so that's not an option.  Are you possibly using an older version of the SDK?

From useStripe.d.ts...

`  presentPaymentSheet: () => Promise<PresentPaymentSheetResult>;
`

**Comment by aliMurtaja** [comment]
I have also got undefined, I dont know why I followed the same step defined in docs in react-native

**Comment by justinmichael-stripe** [comment]
The `paymentOption` being `undefined` when the Payment Sheet is first initialized seems expected, as the Customer has not selected a Payment Method to use yet.  Also note that `paymentOption` coming from `initPaymentSheet` will only be present when `customFlow` is set to `true`.

It looks like `paymentOption` will be populated if the Customer has a default set, but otherwise it won't be.  You should use `paymentOption` if it's defined, but ignore it if it's not.

The `paymentOption` coming back from `presentPaymentSheet` is more likely to be present, as you get it back after the Customer selects a method of payment.

**Comment by aliMurtaja** [comment]
I am using @stripe/stripe-react-native in my react-native app, I have used the initPaymentSheet and card is being stored in strip console working fine.
but I need the token after payment sheet close, so that I can use this token in my database.

**Comment by daveadapptor** [comment]
@justinmichael-stripe  I eventually realised that we should be using the customFlow and yes indeed it does return in that instance.  However if you aren't using the custom flow the customer HAS selected a payment method and in fact the dashboard backs this up.  To be clear this is after the payment sheet has been presented, the user selects a payment option and the payment sheet returns, it returns undefined.  I can see the payment id being returned in the api call so its there, also if you call retrieveSetupIntent it comes back with a paymentMethodId so this is clearly a bug.  Either way its no longer a problem for us but I'd suggest its still going to be a problem for others.

**Comment by swatantragoswami09** [comment]
I am Also getting the same issues
![image](https://user-images.githubusercontent.com/54662673/203114919-051223e0-8097-49bf-875f-b944a54ec8cd.png)

**Comment by ankitk-nimblechapps** [comment]
facing the same issue, checked the function on library too and valid keys are passed to the 
![Screenshot 2023-02-02 at 1 46 15 PM](https://user-images.githubusercontent.com/77725221/216268810-168ef0cf-f80d-4807-a4f6-70fe75f648bb.png)

getting the paymentoption undefined..
any Solution..

**Comment by ruchat-nimblechapps** [comment]
Hi, I am  currently using react native 0.68.5 and "@stripe/stripe-react-native": "^0.19.0",
android crash with these error, Please help with solution
![Screenshot_2023-02-06-13-29-59-94_a40c374f801420dce36ea483382aa15e](https://user-images.githubusercontent.com/55687931/216924545-d028a62a-77b7-43a7-b78f-2a84ccf18a85.jpg)

**Comment by Vikasatneaxus** [comment]
do we have any solution for this. [thorsten-stripe](https://github.com/thorsten-stripe) pls don't just close the issue without any proper solution.

**Comment by BennetLeff** [comment]
Hi I'm using the latest version of stripe-react-native and getting the same problem? I'm not really sure how this issue could be related to #290 because the type defs show that `presentPaymentSheet` does not even take a parameter.

**Comment by gbirch-stripe** [comment]
`paymentOption` returned from `presentPaymentSheet` is expected to be `undefined` unless you are using `customFlow: true` in `initPaymentSheet`. If you are seeing this in other scenarios, please open a new issue.
