### ISSUE TITLE
Card number overlaps with the mm/yy on android - CardField component

### ISSUE THREAD

**Issue by loisestint** [stripe/stripe-react-native#377]
**Describe the bug**

This styling bug relates to the the `CardField` component on android.

On small devices or inside small containers, the `card number` part of the input overlaps with the `mm/yy` part of the input. See images below.

**To Reproduce**
1. Use the `CardField` component:

```
const styles = StyleSheet.create({
  cardInput: {
    height: 45,
    marginTop: 8,
    width: '100%',
  },
});

<CardField
      postalCodeEnabled={false}
      placeholder={{
        number: '4242 4242 4242 4242',
    }}
    style={styles.cardInput}
/>
```
2. Put it inside a `300` width container.
3. Notice how the card number overlaps with the month/year input

**Expected behavior**
The month input should stay to the right of the card number input.

**Screenshots**
![Screenshot from 2021-06-29 16-13-44](https://user-images.githubusercontent.com/59910329/123813913-90a12880-d8f5-11eb-82bd-f9a3b81975fb.png)

![Screenshot from 2021-06-29 16-14-11](https://user-images.githubusercontent.com/59910329/123813928-93038280-d8f5-11eb-838e-2fadbda6f2ee.png)

**Smartphone (please complete the following information):**
 - Device: [Pixel 4 API 30, Samsung Galaxy S21]
 - OS: [Android 11]
 - Version [@stripe/stripe-react-native": "0.1.4",]

**Comment by loisestint** [comment]
Thanks @thorsten-stripe. I think we will wait for the multi line component then. 

Increasing the width of the container won't make a difference on smaller devices. They styling issue was picked up on smaller devices during our QA process. 

I just changed the container size to easily reproduce the problem.

It's strange though, because iOS behaves so nicely with the small container. The card input takes on full width and you don't see the month/year section. I was looking for this behaviour on the android component

**Comment by thorsten-stripe** [comment]
FYI @michelleb-stripe as this seems to be an Android quirk?

**Comment by Borduhh** [comment]
We have the same issue on Android only. The iOS version hides the expiration date as expected.

Android:
![Screenshot_20220418-133012](https://user-images.githubusercontent.com/4759596/163855196-74d8a02f-a5e8-43a5-9d64-b81975edd283.png)

iOS:
![IMG_B745A06A92B2-1](https://user-images.githubusercontent.com/4759596/163855234-ab236621-5f66-49bb-85d9-d8c670855b68.jpeg)

**Comment by kh-abir** [comment]
I'm facing the same issue, not in the development but after building the apk. any suggestions for thsi?
