### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by carlosq-ordering** [stripe/stripe-react-native#380]
**Describe the bug**
The app shows this message after create a card

`JSON value '<null>' of type NSNull cannot be converted to NSString`

any idea?

**Comment by thorsten-stripe** [comment]
Please use the bug report template and provide the necessary information prompted there to help us debug this: https://github.com/stripe/stripe-react-native/issues/new?assignees=&labels=&template=bug_report.md&title=
