### ISSUE TITLE
is this library having createTokenWithCard method for token generation?

### ISSUE THREAD

**Issue by naishadh-hyperspace** [stripe/stripe-react-native#381]
is this library having `createTokenWithCard` method for token generation like tipsi-stripe having this feature?

**Comment by paulasjes-stripe** [comment]
Tokens are a legacy integration path and aren't supported with this library. Please upgrade to use PaymentMethods instead: https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native#react-native-collect-card-details
