### ISSUE TITLE
Customisations for fields

### ISSUE THREAD

**Issue by Sunhat** [stripe/stripe-react-native#382]
**Is your feature request related to a problem? Please describe.**
Hi - The current CardField is not very user friendly, hides the long card number and throws the post code off screen. Is there are chance of getting a more traditional layout?

**Describe the solution you'd like**
Long card number, cvv and expiry as separate fields,
ideally able to place other fields like country in between the fields

**Describe alternatives you've considered**
Using a different payment provider

**Comment by thorsten-stripe** [comment]
Component with separate fields is being tracked here: https://github.com/stripe/stripe-react-native/issues/83
