### ISSUE TITLE
expo: "CardField" was not found in the UIManager.

### ISSUE THREAD

**Issue by HQDung** [stripe/stripe-react-native#393]
**Describe the bug**
Im trying to integrate stripe with Expo, and I got this issue.

**To Reproduce**
expo version : 40.0.1
stripe-react-native: 0.1.4

Here is my code (just copy the example):
```
<StripeProvider publishableKey={publishableKey}>
      <CardField
        postalCodeEnabled={true}
        placeholder={{
          number: '4242 4242 4242 4242',
        }}
        cardStyle={{
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
        }}
        style={{
          width: '100%',
          height: 50,
          marginVertical: 30,
        }}
        onCardChange={(cardDetails) => {
          console.log('cardDetails', cardDetails);
        }}
        onFocus={(focusedField) => {
          console.log('focusField', focusedField);
        }}
      />
  </StripeProvider> 

```
**Expected behavior**
CardField showed up

**Screenshots**
<img width="517" alt="Screen Shot 2021-07-02 at 16 24 23" src="https://user-images.githubusercontent.com/9845485/124253187-f853af80-db51-11eb-82af-e372b58423af.png">

**Desktop (please complete the following information):**
 - OS: Android Simulator

**Additional context**

**Comment by arekkubaczkowski** [comment]
https://github.com/stripe/stripe-react-native/issues/363#issuecomment-866142212
