### ISSUE TITLE
Can't programatically close the keyboard

### ISSUE THREAD

**Issue by kperdomo1** [stripe/stripe-react-native#396]
**Describe the bug**
Unable to close the keyboard using ReactNative's [Keyboard.dismiss()](https://reactnative.dev/docs/keyboard#dismiss) when `CardField` has focus.

In my use case, I want to close the keyboard programatically once user finished providing all card details.
```
  const onCardChange = (details: CardFieldInput.Details) => {
    if (details.complete) {
      Keyboard.dismiss();
    }
  };
```

**To Reproduce**
1. Use `CardField` component.
2. Provide all card details
3. Programatically dismiss the keyboard
4. Keyboard remains opened.

**Expected behavior**
Keyboard should close after executing Keyboard.dismiss()

**Smartphone (please complete the following information):**
 - Device: Simulator - iPhone 8
 - OS: iOS 14.4

**Additional context**
I am using StripeContainer with keyboardShouldPersistTaps={false} which closes the keyboard once tapping anywhere else, but does not fit our use case.

**Comment by arekkubaczkowski** [comment]
https://github.com/stripe/stripe-react-native/pull/337 it will be available from the next release

**Comment by kperdomo1** [comment]
great news, thanks @arekkubaczkowski :) are you able to share any ETA for next release?

**Comment by thorsten-stripe** [comment]
Next release will be later this week. If you need it earlier you can build and install the master branch locally: https://github.com/stripe/stripe-react-native/blob/master/CONTRIBUTING.md#install-library-as-local-repository
