### ISSUE TITLE
Stripe equivalent for `openNativePaySetup` from `tipsi-stripe`

### ISSUE THREAD

**Issue by bill-pairaktaridis** [stripe/stripe-react-native#400]
`tipsi-stripe`, from which we are migrating, had a method called `openNativePaySetup` which allowed us to open Apple Wallet from within our app, in case the user hadn't set it up (seen here: https://github.com/tipsi/tipsi-stripe/blob/2e777c704bd00833fa1642035b03886049563846/src/Stripe.js#L232).

**Describe the solution you'd like**
We would like to have a method or way to do the same, as well as to be able to check if Apple Pay is support but **not** set up. Right now, if I'm not mistaken, `isApplePaySupported` checks for both, so there's no in-between.

**Comment by jaaywags** [comment]
This may be a duplicate of issue #9
