### ISSUE TITLE
Ability to add payment methods and native Apple Pay outside of a component

### ISSUE THREAD

**Issue by bill-pairaktaridis** [stripe/stripe-react-native#401]
**Is your feature request related to a problem? Please describe.**
If I'm understanding the documentation and examples correctly, right now the payment method flow (get/create setup intent, create payment method, submit payment method to API) all needs to happen within the same component as the calling component. Meaning, it all needs to happen within the same component as `<CardField />` or `<ApplePayButton />`. However, this is currently breaking our coding norms as we were able to abstract most of it to methods living outside components and GraphQL mutations.

**Describe the solution you'd like**
We would like a way to do what I described or, if there's no way or plan, an answer here so that we know we've exhausted our options.

**Describe alternatives you've considered**
It's not the end of the world to keep all payment related actions in methods within components but, as I said, it does break our coding patterns.

**Additional context**
We are coming from `tipsi-stripe`, which allowed us to do this, albeit at the cost of possible lack of PCI compliance.

**Comment by thorsten-stripe** [comment]
It does not need to be called within the same component, the requirement is rather that the `CardField` component needs to be mounted at the time of calling `confirmPayment` or `createPaymentMethod` etc. 

We traverse the view stack and find the CardField, so as long as it is visible and filled in we are able to extract the card details.

**Comment by bill-pairaktaridis** [comment]
@thorsten-stripe thanks! Would be great if a note about this could be added to the docs because right now it's not clear how it all works.
