### ISSUE TITLE
Allow passing metadata to confirmSetupIntent

### ISSUE THREAD

**Issue by tantommy** [stripe/stripe-react-native#402]
**Is your feature request related to a problem? Please describe.**
Currently, `confirmSetupIntent` does not allow us to pass `metadata` per https://github.com/stripe/stripe-react-native/blob/3378e6f24d92accfff4b6b8d66ae764561ba470b/src/types/SetupIntent.ts#L23.  `metadata` is part of the `SetupIntent` object and the Stripe api allows us to set it as well, for example, https://stripe.com/docs/api/setup_intents/update.  Maybe we can even add a `updateSetupIntent` method?

**Describe the solution you'd like**
Would be great if we can have a parameter to set the `metadata` for `confirmSetupIntent`

**Describe alternatives you've considered**
1.) Do this through server side
2.) possibly run a webview with only the Javascript Stripe SDK loaded and call, for example, `confirmCardSetup` through there
3.) eject from managed workflow and integrate Stripe with Android/iOS

**Comment by thorsten-stripe** [comment]
Confirming a SetupIntent with a publishable key does not allow passing of metadata. Please pass metadata on the server-side when creating or updating the SetupIntent.
