### ISSUE TITLE
Missing methods to handle errors on apple pay.

### ISSUE THREAD

**Issue by thevishnupradeep** [stripe/stripe-react-native#404]
**Is your feature request related to a problem? Please describe.**
I am unable to find any methods to cancel apple pay in case of an error. If we pass anything other than proper clientSecret to `confirmApplePayPayment` the whole app crashes. Am I missing 

**Describe the solution you'd like**
A new method like `cancelApplePayPrompt` should be enough.

**Comment by thorsten-stripe** [comment]
To show an error in the apple pay sheet you need to use the callback handler, e.g. https://stripe.dev/stripe-react-native/api-reference/interfaces/useapplepayprops.html#onshippingcontactselected

There is no way to close the Apple Pay sheet programmatically.

**Comment by thevishnupradeep** [comment]
`tipsi-stripe` managed to do it on their [library](https://tipsi.github.io/tipsi-stripe/docs/cancelNativePayRequest.html). May be we could apply the same logic here?

**Comment by thevishnupradeep** [comment]
This seems to be how they are doing it.
```
RCT_EXPORT_METHOD(cancelApplePayRequest:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject) {
    if (applePayCompletion) {
        promiseResolver = resolve;
        [self resolveApplePayCompletion:PKPaymentAuthorizationStatusFailure];
    } else {
        resolve(nil);
    }
}
```
