### ISSUE TITLE
Ability to setParams to the CardInput component

### ISSUE THREAD

**Issue by carl0shd** [stripe/stripe-react-native#406]
**Is your feature request related to a problem? Please describe.**
I want to pass certain values to the CardInput to create a functionality (Scan the card and pass the data to the cardInput).

**Describe the solution you'd like**
Expose a method `setParams` through a reference like tipsi-stripe does.
https://tipsi.github.io/tipsi-stripe/docs/paymentcardtextfield.html#instance-methods-available-via-ref

**Comment by thorsten-stripe** [comment]
https://github.com/stripe/stripe-react-native/issues/263

**Comment by bill-pairaktaridis** [comment]
@thorsten-stripe I don't think @carl0shd is requesting to not use `<CardField />` just the ability to pre-fill values. I'd like to do the same but for test coverage.

**Comment by carl0shd** [comment]
@bill-pairaktaridis @thorsten-stripe Thats correct.

**Comment by jgalianoz** [comment]
Any update with this ?

**Comment by thorsten-stripe** [comment]
We should avoid sending card details over the JS bridge. For testing you can specify test mode payment method IDs, e.g. `pm_card_visa` etc: https://stripe.com/docs/testing#cards
