### ISSUE TITLE
No possibility to set metadata for "createPaymentMethod" method

### ISSUE THREAD

**Issue by Noolie** [stripe/stripe-react-native#407]
**Describe the bug**
No possibility to set metadata for "createPaymentMethod" method.
For my case it was a try to set default payment method on new payment method creation.

**To Reproduce**
```
<CardField
      postalCodeEnabled={false}
      placeholder={{ number: '0000 0000 0000 0000' }}
      cardStyle={{ backgroundColor: "FFFFFF", textColor: "#000000" }}
      style={{ width: '100%', height: 48 }}
   />
<Button onPress={async () => {
  const creation = await createPaymentMethod({
      type: 'Card',
      billingDetails: {
          name: `${user?.firstName} ${user?.lastName}`,
          email: user?.email,
          phone: user?.phoneNumber,
      },
      metadata: {
         setDefault: true, // none of these are working
         isDefault: true, // none of these are working
         default: true // none of these are working
      }
  });
}}>
  create
</Button>
```

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Stripe version: ^0.1.4

**Comment by thorsten-stripe** [comment]
Metadata is not meant to be set on the client-side. Can you outline your use case more and we can make a recommendation how to best handle this.

**Comment by Noolie** [comment]
Then is there any possibility to set default card from client during new payment method creation ?
