### ISSUE TITLE
`handleCardAction` thows on fail instead of returning error

### ISSUE THREAD

**Issue by JJK801** [stripe/stripe-react-native#409]
**Describe the bug**

**To Reproduce**
```javascript
if (paymentStatus === PaymentIntents.Status.RequiresAction) {
  try {
    const {
     error
    } = await this._stripe.handleCardAction(clientSecret)
   console.log(error)
  } catch (e) {
    console.error(e)
  }
}
```
1/ trigger a 3D Secure using test card
2/ Fail the authorization
3/ returned error is undefined and the error is thrown

**Expected behavior**
Return the error as the other functions

**Comment by JJK801** [comment]
weird, it seems that it's sometimes returned and sometimes thrown...

i had to wrap it all in a try / catch and throw error in it when it's returned to cover any cases

**Comment by thorsten-stripe** [comment]
How are you importing the library? How are you setting `this._stripe`?

I think you might be importing `NativeStripeSDK` rather than the top level functions.

**Comment by JJK801** [comment]
there is some legacy code in our app, so i actually inject `useStripe` return in the class constructor while waiting for a rework on this code.

We just migrated from tipsi so we had to make some withdrawals to do it fast.

**Comment by thorsten-stripe** [comment]
Okay, sounds like this is an issue with your specific integration, not the library per se. As you can see, the function does never throw but always return: https://github.com/stripe/stripe-react-native/blob/master/src/functions.ts#L228-L248
