### ISSUE TITLE
An event for Apple Pay cancel

### ISSUE THREAD

**Issue by jimhill** [stripe/stripe-react-native#410]
**Is your feature request related to a problem? Please describe.**
When using `presentApplePay` to open the Apple Pay sheet, when a user cancels there is no event.

**Describe the solution you'd like**
It would be incredibly helpful to have an event that can be listened to for when a user dismisses the Apple Pay sheet.

**Describe alternatives you've considered**
None

**Comment by thorsten-stripe** [comment]
`presentApplePay` resolves with an `error` object for this case:

```
{
  "code": "Canceled",
  "message": "The payment has been canceled",
  "domain": "RCTErrorDomain",
  "userInfo": null,
  "nativeStackIOS": [...]
}
```

**Comment by jimhill** [comment]
Sorry @thorsten-stripe. That makes sense. Thank you.
