### ISSUE TITLE
OpenPaymentSheet crashes

### ISSUE THREAD

**Issue by qrosakee** [stripe/stripe-react-native#411]
**Describe the bug**
Crashes when I trying to open the example payscreen from a modal.

**To Reproduce**
1. Copy the code on https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet
2. Instead of attaching `openPaymentSheet()` to the button, replace it with a state change `openModal(true)`
3. Add a modal like below with a button that both closes the current modal and opens the paysheet.
```

<Modal
        animationType="slide"
        transparent={false}
        visible={openModal}
        onRequestClose={() => {
          setOpenModal(!openModal);
        }}
      >
        <View style={{justifyContent: 'center', flex: 1, height: '100%'}}>
          <View style={{justifyContent: 'center'}}>
            <TouchableOpacity
              onPress={() => {
                  setOpenModal(!openModal);
                  setOpenPaysheet(true);
                }}
            >
              <Text>Hide Modal</Text>
            </TouchableOpacity>
          </View>
        </View>
</Modal>
```
4. Add a listener useEffect:
```
    useEffect(()=>{
        openPaymentSheet();
    })();
    }, [openPaysheeet])
```
3. Run. Open the modal then close it by clicking the "Hide Modal" button.
3. The app crashes with no error

**Expected behavior**
should open payscreen like in the example

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: ios14.4
 - simulator

Other information:
Sometimes it seems to work inconsistently, but it will crash most of the time.

**Comment by thorsten-stripe** [comment]
This has been fixed here https://github.com/stripe/stripe-react-native/pull/366 and will be available in the next release. If you need it earlier you can build and install the master branch locally: https://github.com/stripe/stripe-react-native/blob/master/CONTRIBUTING.md#install-library-as-local-repository
