### ISSUE TITLE
Show save card for future payment in Payment Sheet

### ISSUE THREAD

**Issue by saxenanihal95** [stripe/stripe-react-native#412]
**Describe the bug**
In Payment Sheet documentation: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet, in screenshot which shows checkbox **save card for future payments**, but when i open the payment sheet there is no checkbox for **save card for future payments**,

**To Reproduce**
1. Initialise payment sheet:

  ```
  useEffect(() => {
      initialisePaymentSheet();
  }, []);
  
const initialisePaymentSheet = async () => {
    setLoading(true);

    try {
      const {clientSecret, customerId} = await fetchPaymentSheetParams();

      const {error, paymentOption} = await initPaymentSheet({
        customerId,
        paymentIntentClientSecret: clientSecret,
        customFlow: true,
        merchantDisplayName: 'Example Inc.',
        applePay: true,
        merchantCountryCode: 'US',
        style: 'alwaysDark',
        googlePay: true,
        testEnv: true,
      });

      if (!error) {
        setPaymentSheetEnabled(true);
      }
      console.log({paymentOption});
      if (paymentOption) {
        setPaymentMethod(paymentOption);
      }
    } catch (error) {
      console.log('error', error);
    } finally {
      setLoading(false);
    }
  };
```
2. Choose Payment Option:

```
  const choosePaymentOption = async () => {
    const {error, paymentOption} = await presentPaymentSheet({
      confirmPayment: false,
    });

    if (error) {
      console.log('error', error);
    } else if (paymentOption) {
      setPaymentMethod({
        label: paymentOption.label,
        image: paymentOption.image,
      });
    } else {
      setPaymentMethod(null);
    }
  };
```

**Expected behavior**
It should show **save card for future payments**

![Screenshot 2021-07-12 at 11 20 06 AM](https://user-images.githubusercontent.com/17348595/125237322-05e90200-e2d5-11eb-8b6c-e000a2457963.png)

**Screenshots**
![Screenshot 2021-07-12 at 11 02 43 AM](https://user-images.githubusercontent.com/17348595/125235829-97a34000-e2d2-11eb-9dc3-a3fe3fc814b4.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS14.1]
 - simulator

**Additional context**
I am not sure if there is option to pass to show it

**Comment by thorsten-stripe** [comment]
In order for the save card option to show up the `customerEphemeralKeySecret` secret needs to be provided: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICompleteScreen.tsx#L55-L66
