### ISSUE TITLE
Separate the fields to be used in a customized UI.

### ISSUE THREAD

**Issue by cerezagroup** [stripe/stripe-react-native#414]
From what I've seen now you can only use the <Card Field /> component to enter the card information.
Is there a way to separate the fields of the card? by way of using them a personalized interface of the card input.

I have not found the solution in the current version,

you could put the fields manually at the end when the payment is to be confirmed,

something like:

confirmPayment: (paymentIntentClientSecret, {
  card_number,
  card_expiry,
  card_cvc,
}, options ?: Options) 

like the following video whose solution is for React and not for React Native apparently ;
https://www.youtube.com/watch?v=gW8b0Y6Ae8o&ab_channel=StripeDevelopers

I would appreciate if someone can give me information if this functionality is already implemented,

Thank you so much.

**Comment by cerezagroup** [comment]
Apparently, that for security reasons is not recommended, due to the issue of data sensitivity,

Someone to get me out of doubt?

**Comment by trex-quo** [comment]
I believe that the team added this feature in the last release, although you are correct about it not being recommended.

https://github.com/stripe/stripe-react-native/pull/306

**Comment by cerezagroup** [comment]
> I believe that the team added this feature in the last release, although you are correct about it not being recommended.

Thanks, I'll take a look at it.

**Comment by cerezagroup** [comment]
@tex-quo clarify something for me please. I do not know if your comment is on track with the following:

I need set the fields, separately , i have an inteface like bellow,

![Captura de pantalla 2021-07-12 192409](https://user-images.githubusercontent.com/73009730/125371646-cd820c00-e346-11eb-8876-af8d2bc43937.png)

and the only option that I think stripe provides for me to enter the card data is the one they have by default:

![Captura de pantalla 2021-07-12 192727](https://user-images.githubusercontent.com/73009730/125371852-4da87180-e347-11eb-82fe-4f33ce622615.png)

NOTE: I am currently using a library  called [react-native-stripe-payments](https://github.com/Fitpassu/react-native-stripe-payments#readme), and it uses an old version of the android sdk (14.2.1), which Google Play rejects for reasons of privacy policies and data sensitivity ( as I mentioned before) and suggests updating to a version higher or equal to (16.9.0), which has controlled that sensitivity of the data. The problem is described in this [issue](https://github.com/Fitpassu/react-native-stripe-payments/issues/40#issue-941816430).

I wouldn't be telling you all of this, if I weren't considering using @stripe /stripe-react-native library, which is obvious, it will feature much more support.

But if you realize the problem, on the one hand and on the other, lies in that sensitivity in the data, and I am stuck on both sides.

Then,

1. Will I have to worry about not being able to use a custom interface and use the default interface that @stripe /stripe-react-native brings?
2. Or is it better to wait for the @stripe /stripe-react-native library to stabilize a bit more?

Thank you.

**Comment by thorsten-stripe** [comment]
Custom card input fields are not supported due to PCI compliance requirements: https://stripe.com/docs/security/guide#validating-pci-compliance

Work on split fields is tracked here: https://github.com/stripe/stripe-react-native/issues/83
