### ISSUE TITLE
[iOS] Undefined symbol: type metadata accessor for (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType

### ISSUE THREAD

**Issue by sohamb91** [stripe/stripe-react-native#417]
Ran the npm install command and then ran pod install in ios folder. The project has unity integrations and I am trying to run the project in a real device (iPhone 7). I keep getting the following errors:
**Undefined symbol: type metadata accessor for (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType**

Library search path has two entries :
    ${inherited} and $(SDKROOT)/usr/lib/swift . tried removing all combinations of files. And then, created Fix.swift at the root level as suggested in the docs. No luck whatsoever. 
Project Structure:
<img width="485" alt="Screenshot 2021-07-14 at 11 54 46 AM" src="https://user-images.githubusercontent.com/75128071/125573522-68f39128-60c5-4092-82b5-f312515ce4ff.png">

iPhone os 14.6 and xcode version 12.5.

**Comment by arekkubaczkowski** [comment]
@sohamb91 https://github.com/stripe/stripe-react-native/issues/387#issuecomment-879006851

**Comment by sohamb91** [comment]
@arekkubaczkowski 
Podfile:
<img width="274" alt="Screenshot 2021-07-14 at 12 03 37 PM" src="https://user-images.githubusercontent.com/75128071/125574437-0398c439-7033-4849-b6d2-afbbb1e7e368.png">

Deployment info on xcode:
<img width="594" alt="Screenshot 2021-07-14 at 12 04 18 PM" src="https://user-images.githubusercontent.com/75128071/125574516-3a480e39-9b7a-434c-96a1-13b1e3cf83d5.png">

**Comment by arekkubaczkowski** [comment]
@sohamb91 can you paste your `Library search path` entries from Target -> build settings -> Library search path?

**Comment by sohamb91** [comment]
Project -> Build Settings -> Library Search Paths
<img width="811" alt="Screenshot 2021-07-14 at 12 07 41 PM" src="https://user-images.githubusercontent.com/75128071/125574875-3048f4bc-e716-4964-a5cc-ec7e43112c2e.png">

**Comment by sohamb91** [comment]
@arekkubaczkowski  updated the pbxproj file as well. But no luck
<img width="223" alt="Screenshot 2021-07-14 at 12 13 15 PM" src="https://user-images.githubusercontent.com/75128071/125575606-100a30ea-f9a3-4baa-a43c-539dcd982565.png">

**Comment by arekkubaczkowski** [comment]
Can you try clean build folder? `Product -> clean build folder`
Please also make sure that bridging header has been created and added properly to the settings.
Let's navigate to: `**Target** -> build settings -> Objective-C bridging header` and make sure that path indicates to your previously created bridging header file

**Comment by sohamb91** [comment]
@arekkubaczkowski editing the LIBRARY_SEARCH_PATHS manually and restarting XCode works. Thank you!

**Comment by arekkubaczkowski** [comment]
@sohamb91 actually editing any configurations from xCode should automatically make changes in pbxproj file since it basically the same

**Comment by sohamb91** [comment]
@arekkubaczkowski Thank you! Let's hope it does not break any of the other integrations/functionalities in the app
