### ISSUE TITLE
PostalCode is not sent with cardDetails

### ISSUE THREAD

**Issue by Brotakuu** [stripe/stripe-react-native#420]
I'm following the example in [SetupFuturePaymentScreen](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/SetupFuturePaymentScreen.tsx), but I have enabled `postalCodeEnabled={true}` for better compliance.

```
<CardField
	postalCodeEnabled={true}
	onCardChange={(cardDetails) => {
	  console.log('card details', cardDetails);
	}}
	style={styles.cardField}
/>
```

In the example, `postalCodeEnabled` is false so the `postalCode` is set manually. But I have enabled user input for postalCode, yet the postalCode does not get sent along with the card details.

```

// 2. Gather customer billing information (ex. email)
const billingDetails: PaymentMethodCreateParams.BillingDetails = {
    phone: '+48888000888',
    addressCity: 'Houston',
    addressCountry: 'US',
    addressLine1: '1459  Circle Drive',
    addressLine2: 'Texas',
    // addressPostalCode: '77063', // REMOVED POSTAL CODE
}; // mocked data for tests

// 3. Confirm setup intent
const { error, setupIntent: setupIntentResult } = await confirmSetupIntent(
    clientSecret,
    {
        type: 'Card',
        billingDetails,
    }
);
```

The postalCode that the user inputted did not get sent to stripe. Do I need to do this manually by setting the state of the zipcode during input?
```

<CardField
	postalCodeEnabled={true}
	onCardChange={(cardDetails) => {
	  console.log('card details', cardDetails);
	  setPostalCode(cardDetails.postalCode)
	}}
	style={styles.cardField}
/>
```

**Comment by tantommy** [comment]
I believe you'll need to structure your data differently.  the "data" arg you're passing to `confirmSetupIntent` should conform to the `ConfirmSetupIntent.Params` interface below.  In the Params interface, your `address` will also need to conform to the `Address` interface below.
```
  export interface Params {
    country: string;
    brand: Card.Brand;
    currency?: string;
    expMonth: number;
    expYear: number;
    last4: string;
    funding: 'Credit' | 'Debit' | 'Prepaid' | 'Unknown';
    address: Address;
    name?: string;
  }

  export interface Address {
    city?: string;
    country?: string;
    line1?: string;
    line2?: string;
    postalCode?: string;
    state?: string;
  }
  
  export const confirmSetupIntent = async (
  paymentIntentClientSecret: string,
  data: ConfirmSetupIntent.Params,
  options: ConfirmSetupIntent.Options = {}
): Promise<ConfirmSetupIntentResult> 
```

**Comment by Brotakuu** [comment]
@tantommy There no issue with the structure. But how can I retrieve the postalCode that the user entered when confirming the setupIntent?
