### ISSUE TITLE
CardField, design customization, multiline input.

### ISSUE THREAD

**Issue by taimoorsultani-10p** [stripe/stripe-react-native#424]
**Is your feature request related to a problem? Please describe.**
I'm using `CardField` and `createToken` method in my application. Everything is working perfectly fine.
But I want to do customizations with `CardField` design, and I'm unable to do that. 
I want to display `CardNumberInput` in a single line. Below `CardNumberInput`, `expiryDate` and `CVC` side by side.

Exactly like this. (The screenshot is from payment sheet.)
<img width="489" alt="Screenshot 2021-07-15 at 2 47 58 PM" src="https://user-images.githubusercontent.com/86574738/125767975-80f17e22-7d5b-470f-83a6-1a3d5b9272df.png">

I can see there is PR for this, #83, but I'm unable to see anything related to `CardField`.

**Describe the solution you'd like**
`CardField` should receive a new `prop`, which can be `multiline` a bool prop, to decide how three fields will be displayed. (Just a suggestion) **OR** a new component `CardFieldMultiLine`. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by arekkubaczkowski** [comment]
https://github.com/stripe/stripe-react-native/pull/415 this is exactly what you expect, but the name of component is `CardForm`

**Comment by taimoorsultani-10p** [comment]
@arekkubaczkowski when it will be available? I can't see anything related to it in `0.1.5`.

**Comment by arekkubaczkowski** [comment]
because work is in progress, it will be probably available around 15 August

**Comment by taimoorsultani-10p** [comment]
Okay. Sounds good.

**Comment by shikhars371** [comment]
any help with this how can we customise card filed ?

**Comment by ZawadiSumba66** [comment]
Asking the same too. Any updates?

**Comment by LaGregance** [comment]
Hi, I got the same need, any news ?
