### ISSUE TITLE
[Android] confirmSetupIntent - Exception in native call from JS

### ISSUE THREAD

**Issue by nicolegros** [stripe/stripe-react-native#426]
**Description**
When calling `confirmSetupIntent`, the app crashes with the error displayed in the screenshot below.

**To Reproduce**
1. Fill the `<CardField/>` (4242 4242 4242 4242 - 02/25 - 345)
2. Save
3. See error

**Screenshots**
![Screenshot_20210715-085038](https://user-images.githubusercontent.com/23622435/125803683-099229a4-73cd-45cd-a6da-e69810af0f36.png)

**Smartphone:**
 - Expo: SDK 41
 - Device: Pixel 3
 - OS: Android
 - Version 11

**Code:**
```
  const { confirmSetupIntent } = useConfirmSetupIntent();
  const [loading, setLoading] = useState<boolean>(false);
  const [providerError, setProviderError] = useState<string>();
  const [card, setCard] = useState<CardFieldInput.Details>();

  const handlePayPress = async () => {
    try {
      setProviderError(undefined);
      setLoading(true);
      const clientSecret = await PaymentServices.requestSetupIntent();
      const { error } = await confirmSetupIntent(clientSecret, { type: "Card" });
      if (error) throw error;
      const fetchedPaymentMethods = await AccountServices.fetchPaymentMethods();
      dispatch(AccountActions.storePaymentMethods(fetchedPaymentMethods));
      setLoading(false);
    } catch (error) {
      setProviderError(error);
      setLoading(false);
    }
  };

  return (
    <View style={styles.container}>
      <Error error={providerError} />

      <CardField
        autofocus={true}
        postalCodeEnabled={false}
        onCardChange={(cardDetails) => setCard(cardDetails)}
        cardStyle={{ backgroundColor: "#FFFFFF", textColor: "#000000" }}
        style={styles.card}
      />

      <Button
        color="primary"
        disabled={loading || !card || !card.complete}
        loading={loading}
        onPress={handlePayPress}
        label={texts.get("submit")}
      />
    </View>
  );
};
```

**Comment by tantommy** [comment]
I noticed you're on SDK41 but i was under the impression that this was released for SDK42

**Comment by arekkubaczkowski** [comment]
@nicolegros which version of stripe-react-native you got declared in package.json? it was also mentioned here: https://github.com/stripe/stripe-react-native/issues/363#issuecomment-866142212

**Comment by nicolegros** [comment]
Here's the version in package.json: `"@stripe/stripe-react-native": "0.1.1"`
It's the version installed when running `expo install @stripe/stripe-react-native`

**Comment by nicolegros** [comment]
Upgrading to SDK42 seems to have fixed the issue.
