### ISSUE TITLE
createToken - Account type is not supported yet

### ISSUE THREAD

**Issue by nihedjaz** [stripe/stripe-react-native#427]
**Describe the bug**
I am trying to implement the dependency's createToken function. In the params argument I have passed a type.

When I call the createToken function like so:
await createToken({ type: 'Account' });

I get the returned error:
Account type is not supported yet

**Additional context**
stripe-react-native version: "@stripe/stripe-react-native": "^0.1.4",

Please let me know what kind of extra information you need from me in order to debug, thanks!

**Comment by thorsten-stripe** [comment]
Account tokens are not supported yet. For the time being please create accounts on the server side.

**Comment by clusterson** [comment]
Hi! is the same for "BankAccount" ?

Thanks!

**Comment by charliecruzan-stripe** [comment]
Creating a token with a `BankAccount` was added in https://github.com/stripe/stripe-react-native/pull/591, but I believe this issue is referring to Connect Accounts- https://stripe.dev/stripe-ios/docs/Classes/STPAPIClient.html#/Connect%20Accounts

**Comment by charliecruzan-stripe** [comment]
I'm going to close this in favor of https://github.com/stripe/stripe-react-native/issues/842, they're asking for the same thing but that other issue is more specific.
