### ISSUE TITLE
Fetch customer info from stripe 

### ISSUE THREAD

**Issue by nica0012** [stripe/stripe-react-native#431]
Hi all,

Right now I am able to allow my customers to make payments.

My case now is my customer subscribes to a product. 

When they do this, I want to be able to show them their subscription details. The stripe API has information on this, but it seems it an only be done server side?

How can I achieve this using this library - is it even possible? I cannot seem to figure this out client side.

Cheers!

**Comment by paulasjes-stripe** [comment]
This issues page is for problems and bugs with the React Native SDK. For integration questions like this you're better off reaching out to support directly (https://support.stripe.com/contact) or joining the official Discord server: https://stripe.com/go/developer-chat

To unblock you, retrieving subscription information would have to happen from your backend using a secret API key: https://stripe.com/docs/api/subscriptions/retrieve

**Comment by Sirzs** [comment]
> Hi all,
> 
> Right now I am able to allow my customers to make payments.
> 
> My case now is my customer subscribes to a product.
> 
> When they do this, I want to be able to show them their subscription details. The stripe API has information on this, but it seems it an only be done server side?
> 
> How can I achieve this using this library - is it even possible? I cannot seem to figure this out client side.
> 
> Cheers!

Hi, have you found a solution
