### ISSUE TITLE
3d secure payment not working 

### ISSUE THREAD

**Issue by heritvithalani1997** [stripe/stripe-react-native#433]
Describe the bug
3ds payment not working. it shows the status success on the stripe dashboard but in-app it shows as the error (iOS) and processing on android

server-side

// Direct charge
const payment_intent = await payment.getPaymentIntent(
    {
        payment_method_types: ['card'],
        amount: parseFloat(amount) * 100,
        currency: 'usd',
        application_fee_amount: tools.calculateApplicationFee(amount),
    }, 
    {
        stripeAccount: user.stripe_connect_id,
    }
);
console.log(payment_intent.client_secret, '------');
return res.status(200).send({
    status: 200,
    message: 'Checkout data fetched successfully.',
    data: {
        paymentIntent: payment_intent.client_secret,
        customer: customer_id,
    }
});
client-side(react-native)

console.log(data);
const { error, paymentOption } = await initPaymentSheet({
    customerId: data.customer,
    paymentIntentClientSecret: data.paymentIntent,
});

const { error, paymentOption } = await presentPaymentSheet({
    clientSecret: data.paymentIntent,
});

Expected behavior
Payment should successfully completed.

Screenshots
iOS : - 
![3ds_ios_issue](https://user-images.githubusercontent.com/85918817/126145314-5072ac59-5691-4b83-a94f-ee09b10e213d.jpg)

Android : - 
![3ds_android_issue](https://user-images.githubusercontent.com/85918817/126145354-4632db8c-c69d-4ecc-96e8-d86422c56ec5.png)

Desktop (please complete the following information):

OS: [macOS 10.15.7 Catalina]
Browser [chrome, safari]
Version [node: v15.2.1, react-native: 0.63.4, "@stripe/stripe-react-native": "^0.1.5", (node js)"stripe": "^8.148.0"]
Smartphone (please complete the following information):

Device: [Moto G5S & iPhone 11]
OS: [Android 8.1.0 API 27 & iOS 14.3]
Browser [stock browser, safari]

**Comment by dilipsuthar97** [comment]
Hey bro,
I also faced same issue 2 days ago, but didn't get any solution yet.
Hope stripe will solve this issue ASAP.

**Comment by aliriaz-stripe** [comment]
@dilipsuthar97 @heritvithalani1997 hello, can you both share the PaymentIntent ID (not the client_secret) for those payments?

**Comment by heritvithalani1997** [comment]
> @dilipsuthar97 @heritvithalani1997 hello, can you both share the PaymentIntent ID (not the client_secret) for those payments?

Yes sure
Thanks for the quick response

PaymentIntent ID  :  pi_1JEsxGRKY0n0w2BJd8NzIAhI,

**Comment by heritvithalani1997** [comment]
@aliriaz-stripe 
is there any updates?

**Comment by thorsten-stripe** [comment]
In your Stripe Dashboard logs I'm seeing: "You cannot create a charge on a connected account without the `card_payments` capability enabled." Please make sure to enable the relevant capabilities on the connected account: https://stripe.com/docs/connect/account-capabilities#creating

**Comment by heritvithalani1997** [comment]
@thorsten-stripe 
We have checked and test the payment which connects account card_payments capability enabled below is payment intent ID 

pi_1JCfE8SFege9kljXuAv0QTTw

Looking for your positive response
Thanks

**Comment by dilipsuthar97** [comment]
Hello @thorsten-stripe 
Have missed the context

I'm also getting the same issue with the live environment, below I have added the intent ID for live transaction.

ID: pi_1JCLAiSFege9kljXfJQBxswB

Thanks

**Comment by heritvithalani1997** [comment]
@thorsten-stripe @aliriaz-stripe 
is there anything that we have missed? Can you please help us for 3ds issue

**Comment by thorsten-stripe** [comment]
@heritvithalani1997 this is not related to the SDK, please check the error message on your PaymentIntent: "As per Indian regulations, only registered Indian businesses (i.e. sole proprietorships, limited liability partnerships and companies, but not individuals) can accept international payments. More info here: https://stripe.com/docs/india-exports".

For support with this please use https://support.stripe.com/

**Comment by heritvithalani1997** [comment]
@thorsten-stripe 
Thanks for your quick response.

**Comment by heritvithalani1997** [comment]
@thorsten-stripe 
We are still facing the issue of the 3ds payment. Can you please help us with the same. We are using live stripe environment 
Below is the payment intent id. 

1. pi_1JHPncSFege9kljXUSjj2PVd 

Request body : - 
![request](https://user-images.githubusercontent.com/85918817/126973685-48172574-1704-41eb-aab5-20312f2a0f4d.png)

Response
![response](https://user-images.githubusercontent.com/85918817/126973853-f83031a4-1af4-47e9-88c1-c8672071d9a3.png)
![response_continue](https://user-images.githubusercontent.com/85918817/126973861-e3504e8c-7cec-413c-be51-48643407f63c.png)
: -

**Comment by thorsten-stripe** [comment]
Same error message related to https://stripe.com/docs/india-exports as before. Please check your logs: https://dashboard.stripe.com/events/evt_1JHPoISFege9kljXQNWZVHLG

In the future please use our support channels (e.g. https://support.stripe.com/) as this is not related to the library. Thanks.
