### ISSUE TITLE
Pre-file data in CardField component

### ISSUE THREAD

**Issue by BrianCortes** [stripe/stripe-react-native#437]
**Is your feature request related to a problem? Please describe.**
 I am using an scan system to get the info of the card, so now I need pass this data through of CardField component to pre-load the card info

**Describe the solution you'd like**
I really like pass data (card number and expiration date) via props.

**Describe alternatives you've considered**
I know that we can create a custom field but I feel that is too much effort, because CardField works perfectly. so if you have any advice what I should do, I am open to get feedback.

**Comment by thorsten-stripe** [comment]
https://github.com/stripe/stripe-react-native/issues/346#issuecomment-861997822
