### ISSUE TITLE
presentPaymentSheet doesn't open in release apk

### ISSUE THREAD

**Issue by pro030** [stripe/stripe-react-native#438]
Hi , 
I am using [this](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet ) code sample. Payment sheet opens fine when i run the app locally in debug mode but if i create a release apk then payment sheet doesn't open and no error is thrown . 
I am using testenv in release apk too . 
I am calling initPaymentSheet and presentPaymentSheet sequentially after clicking buy button . 
I tried to add a delay of 5 seconds after calling initPaymentSheet but that also doesn't solve any issue .
 i have tried upgrading the library to 0.1.5 too as it fixes one similar bug #315 but that also didn't work . 

Any help is appreciated .

**Comment by soulzidda** [comment]
@pro030  did you manage to resolve this?

**Comment by pro030** [comment]
Yes ,
basically i moved my StripeProvider from App.js to my PaymentScreen .
Somehow, StripeProvider context wasn't carrying on to the PaymentScreen.js and was being lost.

**Comment by soulzidda** [comment]
Perfect will give this a try thank you :) was knocking my head against a brick wall
