### ISSUE TITLE
 Not working in expo 

### ISSUE THREAD

**Issue by ankurC-AI** [stripe/stripe-react-native#439]
I am using webhook payment card only and
Getting error when calling method confirmPayment

 _NativeStripeSdk.default.confirmPayment is not a function

**Screenshots**

![Screenshot 2021-07-20 at 6 13 03 PM](https://user-images.githubusercontent.com/86366168/126326087-2883e7e1-6095-4458-9d5b-ffbbe9a38627.png)

 - Device: [iPhone12]
 - OS: [ iOS 14.5]

**Comment by aliriaz-stripe** [comment]
@ankurC-AI hello, what version of stripe-react-native are you on? I think 0.1.5, right?

**Comment by jlayhue** [comment]
We are using Expo 0.42 and react-native-stripe 0.1.5 and seeing the same error.

**Comment by brentvatne** [comment]
can you provide a minimal reproducible example?

**Comment by aliriaz-stripe** [comment]
@jlayhue ah I think Expo 42 only supports 0.1.4 of stripe-react-native right now, so you should move to 0.1.4 in your app and it should work.

**Comment by thorsten-stripe** [comment]
Each Expo SDK version requires a specific `stripe-react-native` version. To install the correct version for your Expo SDK version run:

```sh
expo install @stripe/stripe-react-native
```
