### ISSUE TITLE
[ios] Close Apple Pay sheet programmatically

### ISSUE THREAD

**Issue by jaaywags** [stripe/stripe-react-native#447]
**Is your feature request related to a problem? Please describe.**
I don't think so. 

**Describe the solution you'd like**
I would like to be able to call the` useApplePay() `method, and it return a method which can be used to close the Apply Pay window.

Currently, [it returns 3 methods, and one property](https://github.com/stripe/stripe-react-native/blob/14709da7e11907660650f2ecbade8c43cd6306c7/src/hooks/useApplePay.tsx#L155). Can we add a 4th method? Maybe called `closeApplePayWindow()`

**Additional context**
I have an application where the user can toggle between n subscription tiers. They can pay by entering their card info into the app, or choose to pay with Apple Pay. 

If they choose to pay with Apple Pay, the window pops up asking which card they would like to use. Once they decide and select their card, the application sends a request to our Payment Service, with the payment id they selected. Our Payment Service will subscribe the customer to that subscription plan using the payment method. The Payment Service will return success if everything goes well. 

The application is then done processing the payment. It updates the state as needed, but there is no way to close the Apple Pay window. This is normally done with the `confirmApplePayPayment()` function, but in our case, we did not use a PaymentIntent, and so we have no ClientSecret to pass it.

**Describe alternatives you've considered**
The existing implementation outlined in the example project utilizes the PaymentIntent workflow. That is not ideal for the subscription model. If I try to create a PaymentIntent, there is no way I can specify what Subscription it corresponds to. This is a problem because once the PaymentIntent succeeds, there is no way our Payment Service can determine this and provision the correct features.

A work around would be to modify our Payment Service to store the PaymentIntent Id, and what Subscription it corresponds to. We could then setup a webhook that looks this up after the PaymentIntent succeeds, but this is (to me at least) not the cleanest way. I think it would be better to implement a method returned from `useApplePay()`. I can call this method and it will close the Apple Pay window.

**Comment by jaaywags** [comment]
I would be willing to make the code change, I just get a bit lost on how to go from stripe-react-native to the StripeSdk. I followed the call [all the way down to here](https://github.com/stripe/stripe-react-native/blob/14709da7e11907660650f2ecbade8c43cd6306c7/src/NativeStripeSdk.tsx#L29), but I am not sure where to go from there.

**Comment by thorsten-stripe** [comment]
You will need to extract the PaymentIntent from your subscription object, return that PaymentIntent's client_secret to your app and then call `confirmApplePayPayment` with that client_secret. The SDK will read out the state from the PaymentIntent (e.g. succeeded) and close the sheet accordingly.

**Comment by jaaywags** [comment]
@thorsten-stripe Hi, thank you for getting back to me. 

Creating a subscription does not always create a PaymentIntent. For example, if a customer has credit, that credit is applied to the new cost and if it covers the full amount, no additional payment is required, thus no PaymentIntent is created.

I have an example of this scenario. I attached a screenshot from my debugger. It is a very straight forward approach to create subscription and it is not creating any PaymentIntent. I confirmed this is a valid scenario with the Stripe support team today.

What do you advise we do?

![Screenshot](https://user-images.githubusercontent.com/38050123/126701521-9d0e1f6b-ef53-4a29-aabe-dbf1f5446c52.jpg)

**Comment by acatalina** [comment]
I've got another use case for this feature... I am confirming all my payments server side so I need to be able to call the completion block myself when I get confirmation from the server

**Comment by simonmitchell** [comment]
This is definitely a requirement of this SDK. What happens if our call to get a client secret from the server fails? Currently, we have to wait for the Apple Pay UI to timeout itself and disappear, we really need a way to programmatically dismiss it!

**Comment by jamiembrown** [comment]
+1 on this. Another use case is Stripe Connect. You can't currently use Direct Charges in the stripe-react-native API - but if you could cleanly close the Apple Pay Window without a Client Secret, then you could attach the payment method to your platform and charge the card server side.

Without this little feature it's actually impossible to use with Direct Charges on Stripe Connect, but with this feature it would be trivial.

**Comment by shqear93** [comment]
We have the same issue, we're not able to create subscriptions on stripe!

**Comment by shqear93** [comment]
Our case was:

1. we have trial period in the first subscription
2. we want to use apple pay
3. we can't create $0 payment intent
4. we can't collect the payment method from apple pay

I was able to fix the issue using setup intents, so basically we create a subscription with trial free period in `incomplete` status (`payment_behaviour = default_incomplete` and `default_payment_method = nil`), the newly created subscription will automatically create setup intent in (subscription->pending_setup_intent)
for the app side we followed [this](https://stripe.com/docs/payments/save-and-reuse?platform=react-native&ui=payment-sheet#react-native-apple-pay) article to confirm the setup intent

**Comment by JacobJaffe** [comment]
> This is definitely a requirement of this SDK. What happens if our call to get a client secret from the server fails? Currently, we have to wait for the Apple Pay UI to timeout itself and disappear, we really need a way to programmatically dismiss it!

Is there a workaround for this? Even forcing an error state would be good (I've tried via calling `confirmApplePayPayment` with a dummy `clientSecret`, but that just... crashes the app)

**Comment by innergap** [comment]
Also having this issue. Creating a subscription using the payment method id retrieved from Apple Pay button and there's no way to close the sheet after this happens without calling confirmApplePayPayment which makes another payment so that the user is charged twice.

**Comment by KeithM23** [comment]
We're also having this issue but using a hack to get around it.

On the stripe dashboard we create a Payment on Live/Test and record the client secrets generated. We then pass these known good client secrets to confirmApplePayPayment, this works / closes the popup with a done/success message. 

The client secrets don't seem to expire / can be confirmed indefinitely from our experience but this could change/may not be the case so its best to use this hack with the client secrets being passed from your server so you can hot swap them if needed.

This appears to work for Stripe Connect as well, we created a payment on the Platform account and used its client secret to close the popup. We are using this for Stripe Connect when creating Shared/Cloned Customers so it may not work in other scenarios

Ideally though an actual fix for this is added as the above could break at any time

**Comment by innergap** [comment]
Thanks, @KeithM23 for the work around. Worked for me on iPhone, but didn't on mac Safari. 

To successfully close the sheet and create a subscription with stripe, I pass in the client secret from the backend:
1. subscription = stripe.subscriptions.create
2. latest_invoice = stripe_subscription.latest_invoice
3. invoice = await stripe.invoices.retrieve(latest_invoice);
4. payment_intent = invoice.payment_intent
5. paymentIntent = stripe.paymentIntents.retrieve(payment_intent);
6. client_secret = paymentIntent.client_secret;
7. front-end confirmApplePayPayment(client_secret)

However, when you create a subscription with a coupon or trial days, it doesn't create latest_invoice and alas, we cannot use it to retrieve any payment intent client secret - and so we cannot use this method to close the sheet.

**Comment by ronak-safara** [comment]
@charliecruzan-stripe how does #1164 close this?

**Comment by charliecruzan-stripe** [comment]
With the `dismissPlatformPay` function

**Comment by ronak-safara** [comment]
@charliecruzan-stripe got it thank you. Any chance there's an equivalent in the iOS native library (sorry I thought this was that initially)?

**Comment by charliecruzan-stripe** [comment]
This is the native call that that JS function results in -> https://github.com/stripe/stripe-react-native/blob/master/ios/ApplePayViewController.swift#L59 (hopefully that answers your question)

**Comment by RZR666** [comment]
is there any solution to this?  Currently the last step on a Cordova solution I'm working on
