### ISSUE TITLE
CreateToken typescript interface missing some fields

### ISSUE THREAD

**Issue by migue1s** [stripe/stripe-react-native#448]
Hello,

I was browsing the code to check compatibility with some react-native code I currently manage. I noticed that there is some missing information in the create token interface:

https://github.com/stripe/stripe-react-native/blob/ec34e553a631f684efa2199b6ef5efeb6873d8dd/src/types/Card.ts#L61-L65

Whereas in the native swift implementation the parameters are as follows:
https://github.com/stripe/stripe-react-native/blob/ec34e553a631f684efa2199b6ef5efeb6873d8dd/ios/StripeSdk.swift#L482-L507

Should the number, cvc, and other information expected in the native code be added to the interface here or is there a reason why they were omitted?

For clarity, my use case is having a custom UI get the billing information, then pass it along to the Stripe SDK through `const {createToken} = useStripe()` in order to create a token. Stripe interface here: https://github.com/stripe/stripe-react-native/blob/ec34e553a631f684efa2199b6ef5efeb6873d8dd/src/hooks/useStripe.tsx#L202

**Comment by thorsten-stripe** [comment]
For PCI compliance reasons only the native code is allowed to handle card details, they are not exposed via the JS bridge. Also tokens are considered legacy, please upgrade to use PaymentIntents with the CardField component: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom or utilize the payment sheet: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet

**Comment by hanselabreu** [comment]
> For PCI compliance reasons only the native code is allowed to handle card details, they are not exposed via the JS bridge. Also tokens are considered legacy, please upgrade to use PaymentIntents with the CardField component: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom or utilize the payment sheet: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet

I'm confused then. What is the use case of the `createToken` function?

**Comment by migue1s** [comment]
In case anyone else stumbles on this. using the `CardInput` is writing the card data into the singleton. The `createToken` function will read from the singleton and create a token from there, that's the reason it doesn't accept params other than `{ type: 'card' }`
