### ISSUE TITLE
`undefined` as a response when we do a createPaymentMethod

### ISSUE THREAD

**Issue by jordipc** [stripe/stripe-react-native#455]
**Describe the bug**
We are getting paymentMethod = `undefined` as a response when we do a createPaymentMethod

**To Reproduce**
We are using the same call that we have seen in the example, `handlePayPress` function from `NoWebhookPaymentScreen.tsx `file. Our code:

```
 const response = await createPaymentMethod({
      type: 'Card',
      billingDetails,
    });
```

Obtained response:
```
Object {
  "paymentMethod": undefined,
}
```

Thank you! :)

**Comment by thorsten-stripe** [comment]
Please provide which library (and if, Expo) versions you are using. 

This might be: https://github.com/stripe/stripe-react-native/issues/369#issuecomment-868166681

**Comment by jordipc** [comment]
Hi @thorsten-stripe, 
Sorry, I forgot. We are using expo version 41 (we can't upgrade to 42 due to our app requirements).
Versions we have tested of `stripe-react-native`
- 0.1.5: In addition to the response 
```
Object {
  "paymentMethod: undefined,
} 
```
we get the following error on iOS.
![Simulator Screen Shot - iPhone 11](https://user-images.githubusercontent.com/3213913/126770388-82cbfb4a-180a-4b98-9a20-b80d5227cd92.png)

- 0.1.4 | 0.1.3: We don't get the iOS error but we still get the response
```
Object {
  "paymentMethod": undefined,
}
```

**Comment by thorsten-stripe** [comment]
Please use `expo install @stripe/stripe-react-native` to install the correct version for your Expo SDK version: https://github.com/stripe/stripe-react-native#expo
