### ISSUE TITLE
Support for External Accounts 

### ISSUE THREAD

**Issue by hanselabreu** [stripe/stripe-react-native#457]
Will this library provide support for [external accounts](https://stripe.com/docs/api/external_accounts) to be used with the Connect feature?

I am in the development stages of a mobile application and have created my own bridge with Stripe similar to [tipsi-stripe](https://tipsi.github.io/tipsi-stripe/).

As per @thorsten-stripe on https://github.com/stripe/stripe-react-native/issues/448#issuecomment-884654008 using something similar to [createTokenWithCard](https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html) or [createTokenWithBankAccount](https://tipsi.github.io/tipsi-stripe/docs/createtokenwithbankaccount.html) does not meet PCI compliance as only native code is allowed to handle card data. 

Does that mean that any application currently using those functions or similar ones is not complying with PCI?

If so, is there a _recommended_ way to achieve this or will there be support for this in this library?

**Comment by thorsten-stripe** [comment]
> Will this library provide support for external accounts to be used with the Connect feature?

It does: https://stripe.com/docs/connect/authentication#adding-the-connected-account-id-to-a-client-side-application

> Does that mean that any application currently using those functions or similar ones is not complying with PCI?

Potentially, yes, please refer to the "Mobile SDK" tab at: https://stripe.com/docs/security/guide#validating-pci-compliance

```
Should you do otherwise, such as writing your own code to handle card information, you may be responsible for additional PCI DSS requirements (6.3 - 6.5) and not be eligible for an SAQ A. In this case, we’d suggest you reach out to a PCI Qualified Security Assessor (QSA) to determine how best to validate your compliance according to the current guidance from the PCI Council.
```

**Comment by hanselabreu** [comment]
> > Will this library provide support for external accounts to be used with the Connect feature?
> 
> It does: https://stripe.com/docs/connect/authentication#adding-the-connected-account-id-to-a-client-side-application
> 

Right, but how exactly do I create the external accounts (Debit Card or Bank Account)? I've gone through the your docs and can't seem to find anything.

> > Does that mean that any application currently using those functions or similar ones is not complying with PCI?
> 
> Potentially, yes, please refer to the "Mobile SDK" tab at: https://stripe.com/docs/security/guide#validating-pci-compliance
> 
> ```
> Should you do otherwise, such as writing your own code to handle card information, you may be responsible for additional PCI DSS requirements (6.3 - 6.5) and not be eligible for an SAQ A. In this case, we’d suggest you reach out to a PCI Qualified Security Assessor (QSA) to determine how best to validate your compliance according to the current guidance from the PCI Council.
> ```

Good to know, thanks!

**Comment by thorsten-stripe** [comment]
> Right, but how exactly do I create the external accounts (Debit Card or Bank Account)? I've gone through the your docs and can't seem to find anything.

@hanselabreu sorry, I was thinking of connected accounts 🙈 

> Debit Card 

For debit cards you can use the `createToken` method with the `CardField` component and then provide the token to https://stripe.com/docs/api/external_account_cards/create

> Bank Account

Bank account token creation is currently not supported, her you would need to build your own form to collect the bank account details and then send them to your server and supply them to https://stripe.com/docs/api/external_account_bank_accounts/create#account_create_bank_account-external_account

**Comment by hanselabreu** [comment]
> @hanselabreu sorry, I was thinking of connected accounts 🙈

Haha, it happens 🙂 

> Bank account token creation is currently not supported, her you would need to build your own form to collect the bank account details and then send them to your server and supply them to https://stripe.com/docs/api/external_account_bank_accounts/create#account_create_bank_account-external_account

Very interesting! Please excuse my ignorance, but does this mean that bank account details are not subject to the same PCI rules as cards, meaning that the details can be sent to your API?

**Comment by thorsten-stripe** [comment]
> Very interesting! Please excuse my ignorance, but does this mean that bank account details are not subject to the same PCI rules as cards, meaning that the details can be sent to your API?

That's correct, only card data falls under the PCI (payment card industry) compliance standard.

**Comment by hanselabreu** [comment]
> That's correct, only card data falls under the PCI (payment card industry) compliance standard.

This is excellent news. Thanks for the enlightenment, I appreciate you 🙂
