### ISSUE TITLE
Build fails when installing @stripe/stripe-react-native

### ISSUE THREAD

**Issue by theprogra** [stripe/stripe-react-native#458]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ryanrebbas/Documents/imathtutor/node_modules/@stripe/stripe-react-native/android/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':stripe_stripe-react-native'.
> No signature of method: build_bbl9an5zk2qyahldiorpiosx2.android() is applicable for argument types: (build_bbl9an5zk2qyahldiorpiosx2$_run_closure1) values: [build_bbl9an5zk2qyahldiorpiosx2$_run_closure1@6e0828ef]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

**Comment by theprogra** [comment]
I'm using it firebase. Fails with both android and IOS

**Comment by arekkubaczkowski** [comment]
does your project meet sdk requirements? https://github.com/stripe/stripe-react-native#requirements 
also please try to follow troubleshooting section https://github.com/stripe/stripe-react-native#troubleshooting

**Comment by theprogra** [comment]
@arekkubaczkowski thanks that worked for android! i changed the gradle version to 4.0.0 in android/build.gradle and i worked

**Comment by arekkubaczkowski** [comment]
@theprogra your iOS issue doesn't look like smth related to the stripe sdk, you can make sure by uninstalling stripe library and then try to build an app

**Comment by theprogra** [comment]
For IOS i'm getting the error:
Apple Mach-O Linker (ld) Error Group
Apple Mach-O Linker (ld) Error Group
I tryid changinr arm64 to armv7 and armv6

i'm getting this error when building
ld: warning: directory not found for option '-L/Users/ryanrebbas/Documents/imathtutor/ios/Pods/Stripe/InternalFrameworks'
ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by arekkubaczkowski** [comment]
@theprogra have you followed all of the troubleshooting steps? Please also check this out https://github.com/stripe/stripe-react-native/issues/387#issuecomment-879006851

**Comment by SeongwoonHong** [comment]
> Author

is there other thing you tried to make android running? I've tried changing the gradle version to 4.0.0 and other versions but none of them worked on my end :( 
but iOS build is fine
