### ISSUE TITLE
For Amex Cards, card details show as done before the entire cvv code is entered.

### ISSUE THREAD

**Issue by stupidtools** [stripe/stripe-react-native#460]
**Describe the bug**
In the CardField component, the onCardChange attribute takes a callback that is passed cardDetails as a parameter.  cardDetails has a boolean field "done"  that should return true when the card details are entered completely, and false otherwise.  In the case of amex cards though, it returns true after only 3 digits of the four digit cvv are entered. 

**To Reproduce**

On a screen with the CardField, enter an amex card.
Log the done parameter of the cardDetails argument passed to the onCardChange callback.
After 3 digits are entered, the value changes to true.

**Expected behavior**

The cardDetails argument should have done set to false until all 4 cvv digits are entered

**Comment by michelleb-stripe** [comment]
@stupidtools American Express cards have a 4 digit CVV on the back, but also provide a 3 digit CVV on the front of the card that also works.

The behavior is as we would expect:
- It is valid after 3 digits
- After 4 digits another callback is called that also has isValid = true
