### ISSUE TITLE
Hooks and Classes

### ISSUE THREAD

**Issue by theprogra** [stripe/stripe-react-native#462]
i'm trying to use the new stripe-react-native library but it seems that the hooks folder contains what i need (use confirm payment) The problem is i'm using classes and not hooks so whats the solution to implement a the check

**Comment by thorsten-stripe** [comment]
All methods are also available as top-level exports, usage of hooks is optional.

Do note that before v0.1.5, the top level export for `confirmPayment` is called `confirmPaymentMethod`: https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#015---2021-07-14
