### ISSUE TITLE
Error: library not found for -lStripeCore  (version 0.1.5)

### ISSUE THREAD

**Issue by semenetsvladislav** [stripe/stripe-react-native#463]
**Describe the bug**
Have an error library not found for -lStripeCore when trying to build the app on iOS

**Expected behavior**
Be able to build the app normally. It worked on previous version.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOS Big Sur 
 - react-native: 0.63.4

**Comment by arekkubaczkowski** [comment]
@semenetsvladislav have you followed troubleshooting section? https://github.com/stripe/stripe-react-native#troubleshooting

**Comment by semenetsvladislav** [comment]
@arekkubaczkowski yes. It worked normally on v. 0.1.4.. But it seems like new pod StripeCore was added in 0.1.5 and I've this error during a build.

**Comment by arekkubaczkowski** [comment]
did you try to remove Pods directory and Podfile.lock and install again? After that I would also clean build folder

**Comment by semenetsvladislav** [comment]
@arekkubaczkowski yes, but have the same issue... Is it possible to link this StripeCore manually somehow?

**Comment by arekkubaczkowski** [comment]
it's not recommended, however this error seems like is not related to the library itself

**Comment by semenetsvladislav** [comment]
@arekkubaczkowski Fixed! It seems like I've missed path to this StripeCore in Build Settings -> Library Search Path. I've just added this "${PODS_CONFIGURATION_BUILD_DIR}/StripeCore" manually there and now it's working :D
