### ISSUE TITLE
Bank Account support for `createToken`

### ISSUE THREAD

**Issue by hanselabreu** [stripe/stripe-react-native#464]
Couldn't find an issue for this, but it'd be ideal to allow the creation of Bank Account tokens using the `createToken` function.

**Comment by thorsten-stripe** [comment]
There is currently no timeline for adding this. For now please build your own form to collect the bank account details and then send them to your server and supply them to https://stripe.com/docs/api/external_account_bank_accounts/create#account_create_bank_account-external_account

**Comment by charliecruzan-stripe** [comment]
Completed in https://github.com/stripe/stripe-react-native/pull/591, which will be available in the next release
