### ISSUE TITLE
App not building after adding stripe

### ISSUE THREAD

**Issue by ivantacca** [stripe/stripe-react-native#465]
**Describe the bug**
`stripe-react-native` has been added to a working project through `npm`. After the installation, the xcode build fails with these errors:

```
Undefined symbol: protocol conformance descriptor for __C.NSOperationQueue : Combine.Scheduler in Foundation
Undefined symbol: type metadata accessor for (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType
Undefined symbol: (extension in Foundation):__C.NSScanner.scanUpToString(Swift.String) -> Swift.String?
Undefined symbol: (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType.init(Foundation.Date) -> (extension in Foundation):__C.NSOperationQueue.SchedulerTimeType
Undefined symbol: _swift_getOpaqueTypeConformance
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreMIDI
Undefined symbol: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreML
Undefined symbol: __swift_FORCE_LOAD_$_swiftWebKit
```

Since I am not using `Expo`, I skipped the 'Expo' section after installation

**Steps to reproduce**
- `react-native init newProj`
- `cd newProj`
- `npm install @stripe/stripe-react-native`
- Change the podfile version to 11.0
- `cd ios`
- `pod install`
- `cd ..`
- `react-native run-ios`

**Test device (Simulator)**
- Device: Iphone 12
- OS: IOS 14.4

**Dev**
- MacOS BigSur 11.5
- XCode: 12.5.1
- RN: 0.64.2

**Comment by Georgiyukr** [comment]
Is your RN app in TypeScript or JavaScript?

**Comment by ivantacca** [comment]
My App is written in JavaScript

**Comment by arekkubaczkowski** [comment]
> Is your RN app in TypeScript or JavaScript?

it doesn't matter

@ivantacca please follow troubleshooting section https://github.com/stripe/stripe-react-native#troubleshooting

**Comment by Georgiyukr** [comment]
> > Is your RN app in TypeScript or JavaScript?
> 
> it doesn't matter
> 
> @ivantacca please follow troubleshooting section https://github.com/stripe/stripe-react-native#troubleshooting

Thank you

**Comment by ivantacca** [comment]
@arekkubaczkowski I have just tried to:
- check out my `library search paths`(which doesn't include any /swift entry):

![Libraries](https://user-images.githubusercontent.com/29736939/127535600-333e700c-4f96-4c56-adaf-516043226efe.jpg)

- Create a new Swift file to the project with a bridging header.

But I am still getting these 5 errors:
<img width="605" alt="Errors" src="https://user-images.githubusercontent.com/29736939/127535594-c9198aa5-2fb6-4489-8721-21d68944d66d.png">

**Comment by arekkubaczkowski** [comment]
@ivantacca because you need to change `project` build settings rather than `target` ones

**Comment by ivantacca** [comment]
My bad, thank you @arekkubaczkowski, It works now!
