### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by jetonk** [stripe/stripe-react-native#467]
**Describe the bug**
After installing `@stripe/stripe-react-native` and importing `StripeProvider` from the official guides
`import { StripeProvider } from '@stripe/stripe-react-native';`

the app crashes and it shows: **Native module cannot be null**

**To Reproduce**
1. Install `@stripe/stripe-react-native` 
2. `import { StripeProvider } from '@stripe/stripe-react-native';`
3. See error

**Expected behavior**

**Screenshots**
<img width="551" alt="Screenshot 2021-07-28 at 18 11 54" src="https://user-images.githubusercontent.com/10130015/127358148-80948b30-5b63-4ded-9ad8-0fe22ff2bb06.png">

**Desktop
 - macOS BigSur v.11.4
 - Xcode version: 12.5.1
 - React Native Expo SDK 40.0.1
 
**Smartphone
 - Device: iPhone 8 Simulator / Xcode version: 12.5.1
 - OS: iOS 14.5

**Comment by Georgiyukr** [comment]
I have the same problem. App also fails to build.

**Comment by arekkubaczkowski** [comment]
@jetonk  if you are using expo please follow this: https://github.com/stripe/stripe-react-native#expo

**Comment by jetonk** [comment]
@arekkubaczkowski Exactly I have followed the steps from https://github.com/stripe/stripe-react-native#expo, https://docs.expo.io/versions/latest/sdk/stripe/

**Comment by arekkubaczkowski** [comment]
Not sure why you get this error but are you able to upgrade expo sdk to the latest version?

**Comment by jetonk** [comment]
@arekkubaczkowski Yes, upgrading Expo from 40 to 42 fixed this error. Thank you!

**Comment by Symyon** [comment]
I am on Expo 42.0.0 and I have the same issue. Any import from @stripe/stripe-react-native will crash the app on opening with no message or anything else. That is when running the standalone app. For Expo Go works no problem.

e.g. import { StripeProvider } from "@stripe/stripe-react-native"; - crash
import { useStripe } from "@stripe/stripe-react-native"; - crash

You don't have to use any of those imports, just import itself will kill it.
