### ISSUE TITLE
Undefined symbol: __swift_FORCE_LOAD_$_swiftWebKit;  Showing Recent Messages Undefined symbol: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers

### ISSUE THREAD

**Issue by Ihor-Kulpekin** [stripe/stripe-react-native#470]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arekkubaczkowski** [comment]
@Ihor-Kulpekin please describe your issue
