### ISSUE TITLE
Create a payment method from card information

### ISSUE THREAD

**Issue by nicopir** [stripe/stripe-react-native#473]
Hello everyone,

I'm glad to see that there is now an official library from Stripe for React Native!
I'm using tipsi-stripe for a while to be compliant with the SCA rules but I'm now considering migrate to this new library especially to fix the Google Play warning about "the non-compliant version of Stripe SDK" from tipsi-stripe.

However, while checking the documentation I do not find a method to create a payment method from the app side. Tipsi-stripe is proving the following method where you can create a payment method based on the card information.

```
const paymentMethod = await stripe.createPaymentMethod({
    card : {
      number : '4000002500003155',
      cvc : '123',
      expMonth : 11,
      expYear : 2020
    }
  })
 ```
 
I noticed that the Stripe API can create a payment method with such arguments but needs the secret key, which I don't want to integrate in my app of course. Does this method is now only available on the server side? Do I need to create a new endpoint in my backend to handle this operation?

Thank you for your help and good job for this new library!

**Comment by ahmaddehnavi** [comment]
Same here,
we have custom design so we can not use the "CardFiled" component and because of Google play warning we have to migrate from "tipsi-stripe".

we were using "confirmPaymentIntent" method of "tipsi-stripe" like this
```
confirmPaymentIntent({
        clientSecret,
        paymentMethod: {
            card: {
                number: newCard.number,
                cvc: newCard.code,
                expMonth: newCard.expireMonth,
                expYear: newCard.expireYear,
            },
        }
    })
```

how can we use card info to start a payment using this SDK?

**Comment by thorsten-stripe** [comment]
There are currently no plans to support this due to the PCI compliance considerations this has (e.g. see https://github.com/stripe/stripe-react-native/issues/178#issuecomment-831651413) We recommend to migrate to use the payment sheet or the `CardField` component.

**Comment by marquina-abreu** [comment]
Same problem!
