### ISSUE TITLE
Unable to upgrade to v v0.1.5 from 0.1.4

### ISSUE THREAD

**Issue by togonow** [stripe/stripe-react-native#476]
Describe the bug
was using v0.1.4 trying to upgrade to v0.1.5, 

after updating the npm, and doing pod install, i'm getting the error below

`[!] CocoaPods could not find compatible versions for pod "Stripe":
  In snapshot (Podfile.lock):
    Stripe (= 21.6.0, >= 21.3.1, ~> 21.6.0)

  In Podfile:
    stripe-react-native (from `../node_modules/@stripe/stripe-react-native`) was resolved to 0.1.5, which depends on
      Stripe (~> 21.7.0)

Specs satisfying the `Stripe (= 21.6.0, >= 21.3.1, ~> 21.6.0), Stripe (~> 21.7.0)` dependency were found, but they required a higher minimum deployment target.`

Cocoapod deployment target is already set to v11, and the project target too

**Comment by togonow** [comment]
Found it, turned out had to run

 pod install --repo-update

instead of only "pod install" seems the pod stripe was locked into 21.6.x instead the needed 21.7.0

may be this should be added to the "troubleshooting section" or migration

**Comment by arekkubaczkowski** [comment]
@togonow  that's great you've managed you solve your issue, however this is a very common thing while upgrading cococapods dependencies and it's not related to this library at all.
