### ISSUE TITLE
App will be removed from the Google Play store because of a non-compliant version of Stripe SDK

### ISSUE THREAD

**Issue by trta2352** [stripe/stripe-react-native#477]
**Used stripe-react-native version: v0.1.4.** 

After I uploaded an update to my app that is on both the App Store and Google Play store I received an email that contained: 

<img width="722" alt="Screenshot 2021-08-01 at 08 40 09" src="https://user-images.githubusercontent.com/20231467/127761852-06740784-cc54-41f7-bfc1-9c6b556b0ca5.png">

Will this issue be resolved when I update to version 0.1.5, or is there something specific I have to change to get this to work?

**Comment by ahmaddehnavi** [comment]
https://github.com/stripe/stripe-react-native/issues/473

**Comment by arekkubaczkowski** [comment]
@trta2352 can you check if `0.2.0v` resolves your issue?

**Comment by trta2352** [comment]
I will upload the new version  to Google Play store today. Probably wont get no if it fixed the problem by the end of the week.

**Comment by arekkubaczkowski** [comment]
@trta2352 please reopen if you still having this problem
