### ISSUE TITLE
Customize Add a card modal sheet

### ISSUE THREAD

**Issue by togonow** [stripe/stripe-react-native#478]
**Describe the bug**
add a card modal "Country or region" section defaults to Afghanistan

**To Reproduce**
const { error, paymentOption } = await initPaymentSheet({
                paymentIntentClientSecret: _paymentIntent?.client_secret,
                customFlow: true,
                applePay: true,
                merchantCountryCode: 'US',
                googlePay: true,
                testEnv: true,
            });

 const { error, paymentOption } = await presentPaymentSheet({
                confirmPayment: false,
            });

**Expected behavior**

1. hide country or region or default it to USA, currently defaults to Afganistan
2. customize  the color of add card button 

**Screenshots**

![image](https://user-images.githubusercontent.com/4708158/127761705-984c0204-678a-4393-895a-11d90a4bb0d7.png)

![image](https://user-images.githubusercontent.com/4708158/127761720-8a102b14-103b-4bed-8152-9f5c175097ca.png)

**Comment by arekkubaczkowski** [comment]
@togonow are you checking it on ios simulator right? It seems to be an issue with some simulator behavior itself, when you change country in system settings it starting to work as expected. It works on real device as expected.
