### ISSUE TITLE
Set up future payments process billingDetails not saving

### ISSUE THREAD

**Issue by m-salamon** [stripe/stripe-react-native#482]
**Describe the bug**
**Set up future payments** process doesn't save billingDetails on `confirmSetupIntent` method (Using Expo SDK 42)
https://stripe.com/docs/payments/save-and-reuse?platform=react-native#react-native-collect-card-details

  ```
const { confirmSetupIntent } = useStripe();
const { setupIntent, error } = await confirmSetupIntent(clientSecret, {
      type: 'Card',
      billingDetails: {
        address: {
          city: "San Francisco",
          country: "US",
          line1: "1234 Fake Street",
          line2: "2B",
          postalCode: "94102",
          state: "CA"
        },
        phone: '5167889999',
        name: 'test name',
        email: 'test@example.com'
    },
  });
```

**Expected behavior**
The Billing address should get saved with the card.

**Screenshots**
When checking the stripe portal and checking the card that was saved the billingDetails are empty.
<img width="1123" alt="Screen Shot 2021-08-02 at 10 49 29 PM" src="https://user-images.githubusercontent.com/15313259/127950187-0e8cc4a5-d96b-4b26-a351-ccebd6a72fa5.png">

**Smartphone**
 - Device: iPhone 11 Pro
 - OS: IOS 11
 - Browser Expo go
 - Version Expo CLI 4.8.1

**Additional context**

**Comment by arekkubaczkowski** [comment]
you provided wrong structure of billing details, please refer to the documentation  https://stripe.dev/stripe-react-native/api-reference/modules/PaymentMethodCreateParams.html#BillingDetails

**Comment by m-salamon** [comment]
@arekkubaczkowski Yes it works! you should add more detail and clarity to the website documentation for `confirmSetupIntent`.
https://stripe.com/docs/payments/save-and-reuse?platform=react-native#react-native-collect-card-details
