### ISSUE TITLE
[Bug] Incorrect typing import on useGooglePay hook, type information lost 

### ISSUE THREAD

**Issue by trex-quo** [stripe/stripe-react-native#492]
**Describe the bug**
Type information is being lost on the `useGooglePay` hook, as it is incorrectly being importing `GooglePay` types.

The file `stripe-react-native/lib/typescript/src/hooks/useGooglePay.d.ts` imports  the `GooglePay` types as follows:
`import type { GooglePay } from './src/types';`
which is incorrect. The file should be imported as follows instead:
`import type { GooglePay } from '../types';`

**To Reproduce**
Go to file linked above in the node_modules folder to confirm

**Comment by thorsten-stripe** [comment]
Thanks for catching this @trex-quo
