### ISSUE TITLE
Clear data in CardField 

### ISSUE THREAD

**Issue by aec2f** [stripe/stripe-react-native#495]
I'm looking to clear the data in the Stripe element Card Field.  But don't see a way to do this via the element.  

![image](https://user-images.githubusercontent.com/61921037/128365231-b0977c2c-682a-43b9-8671-621702e97b87.png)

                    <CardField
                        onCardChange={(cardDetails) => {
                            setCardDetails(cardDetails);
                        }}
                        style={styles.cardField}
                        postalCodeEnabled={true}
                        
                    />

**Comment by arekkubaczkowski** [comment]
you need to use `ref` and call `clear` method on this. Please check this pr description https://github.com/stripe/stripe-react-native/pull/337

**Comment by aec2f** [comment]
> 
> 
> you need to use `ref` and call `clear` method on this. Please check this pr description #337

Thanks! Although I'm using expo so it appears I have to wait for the release of expo 43 to get this?  I tried just updating the package to 0.2.0 but that I get the error "No command found with name "clear"".  Although the ref.current seems to have it:
Object {
  "blur": [Function blur],
  "clear": [Function clear],
  "focus": [Function focus],
}
