### ISSUE TITLE
stripe/stripe-react-native: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Pavel-Ananich** [stripe/stripe-react-native#498]
At first, the project was at the expo. It used expo-payments-stripe. Then we switched to react-native. I installed stripe/stripe-react-native, removed expo-payments-stripe, but after pod install I encountered such errors:

![Снимок экрана 2021-08-06 в 16 15 50](https://user-images.githubusercontent.com/86955927/128515867-26bc2bd6-615b-420b-a419-5e1c8c1eac34.png)

I found this solution in docs:

![Снимок экрана 2021-08-06 в 16 16 43](https://user-images.githubusercontent.com/86955927/128515995-02f014e4-5093-4f25-8364-b6ffaefe6283.png)

But when I created Swift file, Xcode didn't prompt me to create a bridging header. I suppose that I added Swift file in an incorrect way. I don't know which Group and Targets I have to choose and where to put the file:

![Снимок экрана 2021-08-06 в 16 19 37](https://user-images.githubusercontent.com/86955927/128516425-da31650e-1ab9-4063-b3ae-c5c9f0d7619f.png)

May be the correct way of adding Swift file will solve this errors

Simulator: iphone 11 pro, ios 11.0
Package.json:
"dependencies": {
    "@eva-design/eva": "^2.0.0",
    "@expo/vector-icons": "^10.2.1",
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/auth": "^11.4.1",
    "@react-native-firebase/crashlytics": "^11.4.1",
    "@react-native-picker/picker": "^1.8.3",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
    "@react-navigation/material-top-tabs": "^5.3.11",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "@stripe/stripe-js": "^1.16.0",
    "@stripe/stripe-react-native": "^0.2.0",
    "@ui-kitten/components": "^5.0.0",
    "@ui-kitten/eva-icons": "^5.0.0",
    "expo-constants": "^9.3.5",
    "expo-file-system": "^11.0.2",
    "expo-font": "^8.3.0",
    "expo-in-app-purchases": "^10.1.0",
    "expo-keep-awake": "^8.4.0",
    "expo-linking": "^1.0.4",
    "expo-location": "^12.0.4",
    "expo-notifications": "^0.7.2",
    "expo-screen-orientation": "^2.1.0",
    "i": "^0.3.6",
    "moment": "^2.29.1",
    "npm": "^7.12.1",
    "opentok-react-native": "^0.15.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-android-location-enabler": "^1.2.2",
    "react-native-appsflyer": "^6.2.60",
    "react-native-camera": "^3.43.1",
    "react-native-collapsible": "^1.5.3",
    "react-native-device-info": "^8.0.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-maps": "0.27.1",
    "react-native-open-maps": "^0.3.6",
    "react-native-paper": "^4.8.1",
    "react-native-password-strength-meter": "^0.0.5",
    "react-native-permissions": "^2.2.2",
    "react-native-picker-select": "^8.0.4",
    "react-native-qrcode-scanner": "^1.5.3",
    "react-native-reanimated": "^1.13.2",
    "react-native-rename": "^2.7.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.12.0",
    "react-native-slider": "^0.11.0",
    "react-native-snackbar": "^2.4.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^9.13.6",
    "react-native-swift": "^1.2.3",
    "react-native-tab-view": "^2.15.2",
    "react-native-tracking-transparency": "^0.1.1",
    "react-native-unimodules": "^0.11.0",
    "react-native-vector-icons": "^7.1.0",
    "react-native-video": "^5.1.1",
    "react-native-webview": "^11.6.4"
  },
  "devDependencies": {
    "@babel/core": "7.12.3",
    "@babel/runtime": "7.12.1",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },

**Comment by cebrakadabra** [comment]
@Pavel-Ananich I ran into the same issue. For me the fix was `disabling` and/or `removing` your AppTestTarget from xcode and also in case you have it linked in your Podfile. 

Since then everything works. I am about to comment that also on other issues.

**Comment by Pavel-Ananich** [comment]
@cebrakadabra A search in xcode AppTestTarget yielded no results. Can you tell me where to find the AppTestTarget?

**Comment by KhawajaAsim** [comment]
@Pavel-Ananich follow this link, see if this works for you 
https://github.com/stripe/stripe-react-native#troubleshooting

**Comment by Pavel-Ananich** [comment]
Managed to solve this by this guide: [https://www.youtube.com/watch?v=XnjA8PlwFIc&t=1697s&ab_channel=VadimSavin](url)

But get the same issue: [https://githubmemory.com/repo/stripe/stripe-react-native/issues/467](url)
The only difference - I don't use Expo. And can't solve this issue by updating Expo

**Comment by arekkubaczkowski** [comment]
@Pavel-Ananich thats great you've managed to solve your issue, however this is also described here https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios
regarding your current error, what version of RN are you using?

**Comment by Pavel-Ananich** [comment]
@arekkubaczkowski I know where it's described, I even attached screenshot with this solution, you can see it higher. But I couldn't follow this steps in a correct way, and in video I saw how to do it. But now I got this error: Invariant Violation: Native module cannot be null. My version of RN also specified higher. It's 0.63.3

**Comment by Pavel-Ananich** [comment]
App is working when this line is commented:
![Снимок экрана 2021-08-10 в 14 11 19](https://user-images.githubusercontent.com/86955927/128856965-557a8bec-a0d3-4238-bbb1-551ed111ee76.png)

But when I try to import Stripe Provider, got this error:
![Снимок экрана 2021-08-10 в 14 12 23](https://user-images.githubusercontent.com/86955927/128857091-ee5b7a54-4d23-4eb5-a5d2-87738776445a.png)

package.json:
![Снимок экрана 2021-08-10 в 14 13 13](https://user-images.githubusercontent.com/86955927/128857208-d351c64d-2aab-440e-a4a4-63397408193e.png)

**Comment by thorsten-stripe** [comment]
@Pavel-Ananich does `pod install` run successfully for you?

**Comment by Pavel-Ananich** [comment]
@thorsten-stripe Yes

**Comment by arekkubaczkowski** [comment]
@Pavel-Ananich can you check your `ios/Pods` directory if it contains `stripe-react-native` folder there?

**Comment by arekkubaczkowski** [comment]
if so, please also try to clean build folder and build your app again. (`Product -> clean build folder`)

**Comment by Pavel-Ananich** [comment]
> @Pavel-Ananich can you check your `ios/Pods` directory if it contains `stripe-react-native` folder there?

![Снимок экрана 2021-08-11 в 11 56 16](https://user-images.githubusercontent.com/86955927/129000401-18623f45-8e0e-4cd6-82d2-4dd6d7caf9da.png)

No, it should be?

**Comment by arekkubaczkowski** [comment]
yes it should, but can you can check subfolders as well?

**Comment by Pavel-Ananich** [comment]
![Снимок экрана 2021-08-11 в 12 52 49](https://user-images.githubusercontent.com/86955927/129008957-c402429a-4da9-414f-b686-37d5cebeb953.png)
 
It works! I simply forgot to delete expo-payments-stripe after following the steps from here: https://github.com/stripe/stripe-react-native#troubleshooting

**Comment by carlosq-ordering** [comment]
> Managed to solve this by this guide: https://www.youtube.com/watch?v=XnjA8PlwFIc&t=1697s&ab_channel=VadimSavin
> 
> But get the same issue: https://githubmemory.com/repo/stripe/stripe-react-native/issues/467
> The only difference - I don't use Expo. And can't solve this issue by updating Expo

Youtube video works for me!
