### ISSUE TITLE
[ERROR] Cannot call a class as a function

### ISSUE THREAD

**Issue by Legym** [stripe/stripe-react-native#502]
Hey everyone. 

In my Expo App, I am fetching the clientSecret from my `paymentIntents` endpoint. I get my clientSecret but when i pass it into a function i receive the error `Cannot call a class as a function`. I am trying to call confirmPayment from the useConfirmPayment hook.

package.json
```
"expo": "~42.0.1",
"@stripe/stripe-react-native": "0.1.4",
```

React Component
```
import { CardField, useConfirmPayment } from '@stripe/stripe-react-native';

const FeedHome = () => {
  const { confirmPayment, loading: buttonLoading } = useConfirmPayment();
  
    // ...API returns clientSecret
    onCompleted: ({ createPaymentIntent }) => {
      const { clientSecret, error } = createPaymentIntent;

      async function payment() {
        if (error) {
          console.log('Unable to process payment');
        } else {
        
        // Calling confirmPayment causes my issue
          const { paymentIntent } = await confirmPayment(clientSecret, {
            type: 'Card',
          });
        }
      }
      
      payment();
}
```

I've been following [examples ](https://github.com/stripe/stripe-react-native/blob/4b0bcc461ec3a3bdce90b71332d241da03ed943b/example/src/screens/AlipayPaymentScreen.tsx#L40) on how to send payments but i always get the error. I can see my clientSecret and i can see the logging in my stripedashboard, but whenever `confirmPayment` is called it fails.

Does anyone know have any suggestions on how I could resolve this? Thank you

**Comment by Legym** [comment]
I stepped into the `useConfirmPayment` hook and noticed this error. I'm not sure what details i need to pass in. This may explain my original issue.

![image](https://user-images.githubusercontent.com/4462368/128794586-664706e5-c490-4ad3-a1c8-3bc785809f75.png)

**Comment by Legym** [comment]
Im digging further into the issue and found the thread with the same exact issue as me

https://github.com/stripe/stripe-react-native/issues/371

I've upgraded `@stripe/stripe-react-native` to `"@stripe/stripe-react-native": "^0.2.0",`. 

However i am still receiving the error. on my android simulator my app crashes whenever it tries to `confirmPaymentMethod` hook.

**Comment by arekkubaczkowski** [comment]
@Legym Expo requires specific version of `stripe-react-native` library as described here https://github.com/stripe/stripe-react-native#expo.
Regarding the error about the card details that are not completed, do you use CardField or CardForm component on the same screen as you proceed the payment?

**Comment by Legym** [comment]
Thanks @arekkubaczkowski. Expo 42 only installs `"@stripe/stripe-react-native": "^0.1.4" by default. 

I am using Apollo for my request. When the user submits their request, my backend creates the `stripe.paymentsIntents`. I do receive my `clientSecret` which is sent back to my App. 

`CardField` is in the same component as my request. The part of code that crashes my app is this


```
          const { error, setupIntent: setupIntentResult } = await confirmSetupIntent(clientSecret, {
            type: 'Card',
          });

```

Whenever i call `confirmSetupIntent` either my app crashes or i get the error `Cannot call a class as a function`

![image](https://user-images.githubusercontent.com/4462368/128881200-c9feeabe-e081-46a8-ad76-698a0e44ff9d.png)

**Comment by Legym** [comment]
I read another comment by you and it looks like Expo needs to update stripe-react-native to v0.2.0 for Expo 43. (Currently using SDK 42)

**Comment by thorsten-stripe** [comment]
@Legym it looks like you're trying to call `confirmSetupIntent` on a PaymentIntent `client_secret`. For PaymentIntents you will need to use `confirmPayment` instead.

**Comment by Legym** [comment]
Thanks @thorsten-stripe. 

In my original post I was using the `useConfirmPayment` hook and calling `confirmPayment(clientSecret)`. 
I was following this [example ](https://github.com/stripe/stripe-react-native/blob/4b0bcc461ec3a3bdce90b71332d241da03ed943b/example/src/screens/AlipayPaymentScreen.tsx#L40)

I thought i was perhaps using the wrong function and copied code from this [example](https://github.com/stripe/stripe-react-native/blob/4b0bcc461ec3a3bdce90b71332d241da03ed943b/example/src/screens/SetupFuturePaymentScreen.tsx) This is what my screenshot up above is following.

Since ive already created the intent and just now need to confirm the payment, that makes sense to use `confirmPayment`. However that was what i had originally and the error i got was `Cannot call a class as a function`

**Comment by thorsten-stripe** [comment]
@Legym can you try out this example and see if it works for you? https://github.com/stripe-samples/accept-a-payment/blob/main/custom-payment-flow/client/react-native-expo/Card.tsx

**Comment by hierror** [comment]
I believe that this error could be related to my [issue](https://github.com/stripe/stripe-react-native/issues/508#issue-966937141), since the `Card details not complete` is also showing up right here.

**Comment by arekkubaczkowski** [comment]
@hierror not really, @Legym uses Expo so there is no refactor yet which fixes `Card details not complete` issue

**Comment by arekkubaczkowski** [comment]
@Legym your issue should be fixed within the next Expo release, they need to upgrade stripe-react-native to 0.2.0
