### ISSUE TITLE
Include stripe-react-native 0.2.0 in Expo 43

### ISSUE THREAD

**Issue by Brotakuu** [stripe/stripe-react-native#503]
There are many breaking issues in the current version of stripe 0.1.4 that is supported by Expo. We are using this in production and users are reporting frequent crashes (ie: cardField always crashes iOS 12). 

I've tried reaching out to expo support, discord and creating a request  https://github.com/expo/expo/issues/13979 but haven't had a response.

Is there someone on stripe that can reach out to expo to make sure 0.2.0 is included in Expo 43?

**Comment by thorsten-stripe** [comment]
This is already planned, see more details here: https://github.com/stripe/stripe-react-native/issues/449#issuecomment-896068092

**Comment by charliecruzan-stripe** [comment]
This was done 👍
