### ISSUE TITLE
Support for automated end to end client testing with id matching elements

### ISSUE THREAD

**Issue by ayhoung** [stripe/stripe-react-native#504]
**Is your feature request related to a problem? Please describe.**
I'm trying to insert data into the Stripe CardField element for automated e2e testing via testID

**Describe the solution you'd like**
CardField inputs should provide a testID element to help e2e tests identify relevant fields i.e.
`await element(by.id('ccInput')).typeText('42424242424242')`

**Describe alternatives you've considered**
There doesn't seem to be any alternatives.

**Comment by arekkubaczkowski** [comment]
ID's of particular text inputs are hardcoded already and there is no way to override them, you can check them in our e2e tests: https://github.com/stripe/stripe-react-native/blob/master/e2e/screenObject/components/CardField.ts#L2

**Comment by ayhoung** [comment]
@areitz-stripe  thank you, but I'm having trouble understanding which id to use in this scenario. I've tried using `card_number_edit_text` and `card number` and `cardNumberEditText` but all have returned with:

Test Failed: No elements found for “MATCHER(identifier == “<testID>”)”

**Comment by arekkubaczkowski** [comment]
please check this out: https://github.com/stripe/stripe-react-native/pull/108/files#diff-82e000665a6972a7215983a325695d7874c31230014415818c837faa5bfa8343R14

**Comment by ayhoung** [comment]
amazing thank you so much!!

**Comment by ayhoung** [comment]
@areitz-stripe i don't seem to see an equivalent for postal code?
```
await element(by.label('card number')).typeText('4242424242424242');
await element(by.label('expiration date')).typeText('12/22');
await element(by.label('CVC')).atIndex(0).typeText('123');
```
this is what is in the file,

but no postal code test.

I've tried 
```
await element(by.label('postal code')).typeText('123');
```

but it doesn't seem to work

**Comment by arekkubaczkowski** [comment]
@ayhoung I think it's missing in stripe-ios sdk https://github.com/stripe/stripe-ios/blob/fabd7ebe14052d505466ffe824b49eeab3778501/Stripe/STPPaymentCardTextField.swift#L697
you need to try to workaround this somehow, e.g. by looking for all of the fields and getting the last one
