### ISSUE TITLE
Looking for a method to clear card fields.

### ISSUE THREAD

**Issue by misbahkhalilaz** [stripe/stripe-react-native#507]
**Scenario:**
If the user has filled card fields and navigates to another screen without submitting the card, all card fields remain filled when the user comes back to add card screen. I just need to clear them in cases like when the user is logged out.

_**Is there any method or workaround to clear input fields?**_

using version: 0.1.4

**Comment by arekkubaczkowski** [comment]
You can use this https://github.com/stripe/stripe-react-native/issues/495#issuecomment-896711037
