### ISSUE TITLE
CardForm occur crash on react native android

### ISSUE THREAD

**Issue by panda919** [stripe/stripe-react-native#509]
**Describe the bug**
I tried to use CardForm, But app is crashed
**To Reproduce**
<View>
<CardForm
            onFormComplete={cardDetails => {
              console.log('card details', cardDetails);
            }}
            style={{ height: 200 }}
          />
</View>

**Screenshots**
![image](https://user-images.githubusercontent.com/25161426/129131407-924d2836-af6c-4d81-a7d8-f6fd4993b5d3.png)

**Desktop (please complete the following information):**
 - OS: [Android]
 - Version [10]
- react-native:0.64.0
- @stripe/stripe-react-native:0.2.0

**Comment by arekkubaczkowski** [comment]
as a workaround you can change in your styles.xml `parent` to `Theme.MaterialComponents.Light.NoActionBar` like:
```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
```
@michelleb-stripe is it real requirement for CardFormView or can be omitted somehow?

**Comment by panda919** [comment]
Thanks. It is working now

**Comment by arekkubaczkowski** [comment]
@thorsten-stripe we should add this information to the docs as a requirement
