### ISSUE TITLE
Errors in doc's code

### ISSUE THREAD

**Issue by Pavel-Ananich** [stripe/stripe-react-native#515]
**Describe the bug**
Errors in doc's code

You will have errors, if you copy this code: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet-custom#:~:text=before%20displaying%20the%20payment%20sheet%2C%20your%20checkout%20page%20should
1. If you don't use TypeScript, you have to rewrite this:
![Снимок экрана 2021-08-12 в 18 22 30](https://user-images.githubusercontent.com/86955927/129223489-c00da7b2-2d18-4f05-9c3a-5643d6132e38.png)
into this:
const [paymentMethod, setPaymentMethod] = useState({
    image: '',
    label: '',
  });
2. Also here you have Button and code written into title(!):
![Снимок экрана 2021-08-12 в 18 24 09](https://user-images.githubusercontent.com/86955927/129223743-731878e8-349b-4b00-a04b-89c913b32e5a.png)
change it to this:
![Снимок экрана 2021-08-12 в 18 25 55](https://user-images.githubusercontent.com/86955927/129224014-6f25b35b-7aef-4042-b4db-3d6d805a9cc7.png)
3. Also 'paymentSheetEnabled' isn't declared in previous point. I simply removed it. May be it will be needed further
4. And styles are used but not specified. I found them in different files in docs, here they are:
const styles = StyleSheet.create({
  section: {
    marginTop: 40,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  text: {
    marginLeft: 12,
  },
  image: {
    width: 26,
    height: 20,
  },
});

**To Reproduce**
Install stripe-react-native and try to use it, following this docs:
https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet-custom#:~:text=before%20displaying%20the%20payment%20sheet%2C%20your%20checkout%20page%20should%3A

**Expected behavior**
I expect that code should work in RN, if it is written for RN.

**Comment by charliecruzan-stripe** [comment]
Thanks for this! Updating the docs now. BTW- the code written for the `title` prop on a `Button` _does_ work, so it may be that you're on an older version of React Native?
