### ISSUE TITLE
Card field isn't closing

### ISSUE THREAD

**Issue by Pavel-Ananich** [stripe/stripe-react-native#516]
**Describe the bug**
Can't close cardfield. It doesn't respond to pressing the x button. Also it  doesn't respond to pressing "Add card" button. And even after reloading app it's still visible
Screenshot after reloading:
![Снимок экрана 2021-08-12 в 18 46 04](https://user-images.githubusercontent.com/86955927/129227149-56f5929c-2747-4b83-931f-98f16b030937.png)

**To Reproduce**
1. Follow this docs: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet-custom#integrate-payment-sheet

**Expected behavior**
I want to be able to close this modal. But I don't have access to its functionality

**Comment by thorsten-stripe** [comment]
Please provide details about your RN, Expo (if applicable), and stripe versions. E.g. providing the content of your `package.json` file is helpful. Thanks.

**Comment by arekkubaczkowski** [comment]
@Pavel-Ananich snippet of your code also would be helpful

**Comment by Pavel-Ananich** [comment]
> Please provide details about your RN, Expo (if applicable), and stripe versions. E.g. providing the content of your `package.json` file is helpful. Thanks.

"react": "16.13.1",
"react-native": "0.63.3",
"@stripe/stripe-react-native": "^0.2.0",

the whole file:
{
  "name": "HebePilates",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@eva-design/eva": "^2.0.0",
    "@expo/vector-icons": "^10.2.1",
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/auth": "^11.4.1",
    "@react-native-firebase/crashlytics": "^11.4.1",
    "@react-native-picker/picker": "^1.8.3",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
    "@react-navigation/material-top-tabs": "^5.3.11",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "@stripe/stripe-react-native": "^0.2.0",
    "@ui-kitten/components": "^5.0.0",
    "@ui-kitten/eva-icons": "^5.0.0",
    "expo-constants": "^9.3.5",
    "expo-file-system": "^11.0.2",
    "expo-font": "^8.3.0",
    "expo-in-app-purchases": "^10.1.0",
    "expo-keep-awake": "^8.4.0",
    "expo-linking": "^1.0.4",
    "expo-location": "^12.0.4",
    "expo-notifications": "^0.7.2",
    "expo-screen-orientation": "^2.1.0",
    "i": "^0.3.6",
    "moment": "^2.29.1",
    "npm": "^7.12.1",
    "opentok-react-native": "^0.15.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-android-location-enabler": "^1.2.2",
    "react-native-appsflyer": "^6.2.60",
    "react-native-camera": "^3.43.1",
    "react-native-collapsible": "^1.5.3",
    "react-native-device-info": "^8.0.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-maps": "0.27.1",
    "react-native-open-maps": "^0.3.6",
    "react-native-paper": "^4.8.1",
    "react-native-password-strength-meter": "^0.0.5",
    "react-native-permissions": "^2.2.2",
    "react-native-picker-select": "^8.0.4",
    "react-native-qrcode-scanner": "^1.5.3",
    "react-native-reanimated": "^1.13.2",
    "react-native-rename": "^2.7.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.12.0",
    "react-native-slider": "^0.11.0",
    "react-native-snackbar": "^2.4.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^9.13.6",
    "react-native-swift": "^1.2.3",
    "react-native-tab-view": "^2.15.2",
    "react-native-tracking-transparency": "^0.1.1",
    "react-native-unimodules": "^0.11.0",
    "react-native-vector-icons": "^7.1.0",
    "react-native-video": "^5.1.1",
    "react-native-webview": "^11.6.4"
  },
  "devDependencies": {
    "@babel/core": "7.12.3",
    "@babel/runtime": "7.12.1",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by Pavel-Ananich** [comment]
> @Pavel-Ananich snippet of your code also would be helpful

![Снимок экрана 2021-08-13 в 11 32 52](https://user-images.githubusercontent.com/86955927/129328851-4844a34b-cfb7-43fb-aeda-5424783278b1.png)

![Снимок экрана 2021-08-13 в 11 33 11](https://user-images.githubusercontent.com/86955927/129328895-e8913aca-482e-4469-a328-ab5bc3168f0e.png)
![Снимок экрана 2021-08-13 в 11 33 50](https://user-images.githubusercontent.com/86955927/129328983-b1f51a06-c787-4f95-921b-c601f5f568e0.png)
![Снимок экрана 2021-08-13 в 11 34 06](https://user-images.githubusercontent.com/86955927/129329026-5409ba46-d9ac-47ba-8f92-e260ab0bd21e.png)

**Comment by arekkubaczkowski** [comment]
> As I understood, it was ejected from expo

what you mean? this library is available using expo and without, if your project uses Expo please follow instruction how to install it properly https://github.com/stripe/stripe-react-native#expo

**Comment by Pavel-Ananich** [comment]
I fixed problem, you can remove this issue
