### ISSUE TITLE
CardForm onFormComplete occure undefined for all case

### ISSUE THREAD

**Issue by panda919** [stripe/stripe-react-native#517]
**Describe the bug**
I tried to use card form on react native android
**To Reproduce**
 <CardForm
            onFormComplete={cardDetails => {
              console.log('card form', cardDetails);
            }}
            style={{ height: 200 }}
          />

**Expected behavior**
I have to fetch correct input value on onFormComplete
![image](https://user-images.githubusercontent.com/25161426/129256114-bac472c0-b74d-4c04-819b-5d8155c37359.png)
But I get correct value on CardFiemd for same card input data 
But I got an undefined value
**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Smartphone (please complete the following information):**
 - Device: [Android 10]
-React-Native:0.64
-Stripe-react-native:0.2.0

**Comment by arekkubaczkowski** [comment]
@panda919  you can have one Card component on the same screen

**Comment by panda919** [comment]
Yeah, I tried one component mode. But I got the same error

**Comment by arekkubaczkowski** [comment]
@panda919 you should set higher height of CardForm because there is one more hidden field, `height: 350` should be enough

**Comment by Shaheryar123** [comment]
@AlexSirenko actually this required all fields to be filled the issue here is you  are not adding postal code field set height to 350 or more, you can see the postal code field try to put data in all fields then it'll give you complete data.
