### ISSUE TITLE
confirmPayment() show hooks.stripe modal and need closed manually

### ISSUE THREAD

**Issue by hjwlpjr** [stripe/stripe-react-native#519]
Hi, I have a question.

Currently I integrate the card field element and make a payment, but after call the confirmPayment function it actually open some modal like shown in attachment.

how to auto close or disable this? is this only happening for development environment? I need to manually press close button before Stripe can return the success/error object.

Note: I also implement the webhook on my backend

RN : 0.64.2
@stripe/stripe-react-native : 0.2.0

<img width="373" alt="Screenshot 2021-08-13 at 8 39 38 AM" src="https://user-images.githubusercontent.com/54148306/129293368-55f5116e-0b80-4a25-b896-cf5e201002c3.png">

**Comment by thorsten-stripe** [comment]
To automatically dismiss the webview when authentication is finished, configure a custom URL scheme or universal link and set your scheme in the urlScheme parameter: https://stripe.com/docs/payments/3d-secure#when-to-use-3d-secure

**Comment by te-online** [comment]
@thorsten-stripe How does this work? We configured a custom scheme and the return URL is `our-scheme://safepay`, but the webview does not close. Presumably, because the app is already focused. Isn't it the SDK that needs to implement a listener to close the sheet/webview when "returning" to the app?

**Comment by arekkubaczkowski** [comment]
@te-online you need to follow this one https://stripe.com/docs/payments/bancontact/set-up-payment#react-native-handle-deep-linking

**Comment by te-online** [comment]
@arekkubaczkowski Thanks for your response. I did that and it works great! 🎉 

Unfortunately it's not working when using `handleCardAction`. Any ideas why?  

[In this method](https://github.com/stripe/stripe-react-native/blob/cd323b44a1d02ce3059006465f7b06826350fb5c/ios/StripeSdk.swift#L602), it looks to me like no `return_url` is set on the paymentIntent, but I'm not 100% sure I understand the method in context.

Is this just a configuration issue or should I open a new issue around this?
