### ISSUE TITLE
WeChat Pay: Accept a payment (app to app flow)

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe/stripe-react-native#52]
WeChatPay is currently on private beta. Should be available for implementation by early March. Will update here with docs once ready.

**Comment by thorsten-stripe** [comment]
* iOS: https://stripe.com/docs/payments/wechat-pay/accept-a-payment?platform=ios
  * `pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'wechatpay-pm-beta'`
* Android: https://stripe.com/docs/payments/wechat-pay/accept-a-payment?platform=android
  * https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md#1671---2021-04-29

**Comment by thorsten-stripe** [comment]
We're are currently blocked on WeChat Pay requiring additional external SDKs. I'm afraid we don't yet have a timeline when we will be able to proceed.

**Comment by buiquangduc** [comment]
I notice this issue is closed with a Pull Request, is the WeChat Pay integrated into the next React Native Stripe version? 
Thank you guys for your awesome works!
