### ISSUE TITLE
I can not use china union pay 

### ISSUE THREAD

**Issue by panda919** [stripe/stripe-react-native#522]
**Describe the bug**
I tried to call ConfirmPayment by using Card 
**To Reproduce**
"your card is not supported. please use a visa,MasterCard or American express card"
 const { error, paymentIntent } = await confirmPayment(paymentClientSecret, {
        type: 'Card',
      });

It is test card for china union pay
8171999927660000 | 10/2030 | 737
![image](https://user-images.githubusercontent.com/25161426/129592782-c3087304-a60d-41a0-a9e6-092262f99819.png)If 
But, I got success by using visa. 

**Additional context**
"react-native": "0.64.0",
 "@stripe/stripe-react-native": "^0.2.0",

**Comment by souhe** [comment]
Hi @panda919. I was able to reproduce the issue but I need to investigate it more now. I'll let you know about the status of it.

**Comment by arekkubaczkowski** [comment]
@panda919 
This is an error being returned from the Stripe server.  A couple of things I would request:
- PaymentIntent being used.
- Stripe Account Country and Customer Country used (See supported list here: https://stripe.com/docs/payments/cards/supported-card-brands)

**Comment by thorsten-stripe** [comment]
@panda919 you're using the test card for a different payment provider. Please use the correct Stripe test card: `6200000000000005` - https://stripe.com/docs/testing#cards
