### ISSUE TITLE
useConfirmPayment/confirmPayment hook returning undefined

### ISSUE THREAD

**Issue by samdetrent** [stripe/stripe-react-native#526]
![image](https://user-images.githubusercontent.com/5244952/129934995-78352acf-4fd3-47f0-b451-ca3dad1cc589.png)

I'm attempting to use the Stripe RN package's useConfirmPayment hook.

import { CardField, useConfirmPayment } from '@stripe/stripe-react-native';
...
const {confirmPayment, loading} = useConfirmPayment();

when I call confirmPayment, the above error is returned, saying confirmPayment is undefined. 

Any ideas why? 

v0.2.0 @stripe/stripe-react-native
v42.0.1 @expo 
v0.63.4 react-native

Thanks :)

**Comment by arekkubaczkowski** [comment]
please follow expo installation steps https://github.com/stripe/stripe-react-native#expo

**Comment by samdetrent** [comment]
haha... the very first line... get the correct stripe-react-native version for expo. Amazing what happens when instructions are read. 

Thanks @arekkubaczkowski  :)
