### ISSUE TITLE
Google Pay ON_INIT_GOOGLE_PAY initGooglePayPromise called twice

### ISSUE THREAD

**Issue by jonasbark** [stripe/stripe-react-native#528]
Hi!

When integrating the new Google Pay functionality we noticed that this line is called twice:

https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt#L177

caused by using the same callback twice:
https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt#L55
https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/GooglePayFragment.kt#L70
and thus causing the broadcast intent to be fired twice.

Does react-native handle this issue gracefully? On Flutter the app will typically crash as the promise cannot be resolved a second time.

**Comment by souhe** [comment]
Hi @jonasbark. Even if the app is not crashing I believe we should improve handling the `ON_INIT_GOOGLE_PAY`. There are two solutions to this:
1. We can assume that `resultCallback` from one of the methods (for example `GooglePayLauncher`) is enough to notify RN and resolve `initGooglePayPromise`
2. We can try to aggregate `resultCallback` from both `GooglePayLauncher` and `GooglePayPaymentMethodLauncher `
