### ISSUE TITLE
Can't use rgba colors within `cardStyle` props

### ISSUE THREAD

**Issue by yungkittty** [stripe/stripe-react-native#529]
**Describe the bug**
The title is already pretty clear. I would also add that `transparent` as color doesn't work.

**To Reproduce**
```javascript
<CardField
  {...props}
  cardStyle={{
    backgroundColor: "rgba(255, 255, 255, 0.5)",
  }}
/>
```

**Expected behavior**
It should work but it doesn't (see the screenshot down below)

**Screenshots**
![Screenshot 2021-08-23 at 15 52 44](https://user-images.githubusercontent.com/20394860/130459241-feb6e90c-a761-4ea1-8b79-42cb048aaee0.png)

**Comment by thorsten-stripe** [comment]
Currently only hex strings are supported, please use those.

**Comment by yungkittty** [comment]
@thorsten-stripe alright, thanks for you quick reply

**Comment by beandotio** [comment]
I want to add something if someone else is having this issue, doesn't accepts verbosed hex strings, if we used #FFF, at least for android, it won't work, at least for 1.5 version

**Comment by gbmsimoes** [comment]
Kinda late to the party but I guess you can control transparency (or opacity) via Hex...
https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
