### ISSUE TITLE
Failed to transform material-icons-extended-1.0.0-rc02.aar

### ISSUE THREAD

**Issue by Gabotron-ES** [stripe/stripe-react-native#530]
Hi, I'm getting this error right after installing stripe sdk, if I uninstall and build my app I don't get this error so it must be related to Stripe.

Error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform material-icons-extended-1.0.0-rc02.aar (androidx.compose.material:material-icons-extended:1.0.0-rc02) to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-incremental-desugaring-v2=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\GABRIEL\.gradle\caches\transforms-2\files-2.1\c22b07d4460b2cefc6bc4786380dff41\jetified-material-icons-extended-1.0.0-rc02-runtime.jar.
         > Error while dexing.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
* ```

**Comment by thorsten-stripe** [comment]
Are you using the `CardForm` component? It requires some material dependencies: https://github.com/stripe/stripe-react-native#android

**Comment by Gabotron-ES** [comment]
I haven't really used since I haven't been able to build my app at all, is it CardForm or CardField though? the one I have seen used in the docs is called CardField I think

**Comment by Gabotron-ES** [comment]
> Are you using the `CardForm` component? It requires some material dependencies: https://github.com/stripe/stripe-react-native#android
I haven't really used since I haven't been able to build my app at all, is it CardForm or CardField though? the one I have seen used in the docs is called CardField I think

Anyway, what version should I specify?

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES please provide your project and environment details, also please make sure that your project meet all requirements https://github.com/stripe/stripe-react-native#android
especially `Android gradle plugin 4.x and above`

**Comment by Gabotron-ES** [comment]
Hi, I created project with react native cli, haven't touched anything related to Android Studio yet afaik.

I build my project like this:
```
cd C:\xampp\htdocs\SoFood && cd android  && gradlew clean && cd .. && npx react-native run-android -- --reset-cache
```
And my android/build.gradle looks like this:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21 //was 16
        compileSdkVersion =29 //was 29
        targetSdkVersion = 29  //was 29
        googlePlayServicesAuthVersion = "18.0.0" // <--- use this version or newer
        /*androidXAnnotation = "1.2.0"
        androidXBrowser = "1.3.0"*/
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        //classpath("com.android.tools.build:gradle:3.5.3")
        classpath("com.android.tools.build:gradle:4.2.0")
        //Added this line
        classpath('com.google.gms:google-services:4.3.4')
        
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        //Added this line
        maven { url "https://jitpack.io" }
    }
}

```

What other fails should I provide for you guys to help me?

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES  please open in android studio File->Project Structure and check given versions

**Comment by Gabotron-ES** [comment]
I can't seem to find where the versions are in Android Studio, if you mean gradle versions I have these ones in my build.gradle and graddle-wrapper.properties files:

classpath("com.android.tools.build:gradle:4.2.0")
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip

Which I think are the correct ones.

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES can you try clear caches? in android studio: `File -> Invalidate caches / restart`

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES have you managed to fix that?

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES  @zuhairnaqi please verify all the things from this comment: https://github.com/stripe/stripe-react-native/issues/558#issuecomment-914474719

**Comment by ggerminiani** [comment]
Same issue

**Comment by ggerminiani** [comment]
I found solution here... many tries!

First >>> Following the stripe example, I checked each gradle file (https://github.com/stripe/stripe-react-native/tree/master/example/android), and I've tested one by one...

What was needed:

### **android/build.gradle:**

I've tested with buildToolsVersion 29.0.2 and 30.0.3, both has worked.

I'm using gradle 6.7 which is compatible (see [Android notes](https://developer.android.com/studio/releases/gradle-plugin?hl=pt&gclid=Cj0KCQjws4aKBhDPARIsAIWH0JXzDIF_8D29Ea8VOcUz-okkvaWJKNuM75N7k3zUhXWiu1BM5Wply84aAr-WEALw_wcB&gclsrc=aw.ds)) with the gradle plugin 4.0.0 (the minimun required by stripe - [see here](https://github.com/stripe/stripe-react-native#requirements)).

```
buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        playServicesVersion = "17.0.0"
        androidMapsUtilsVersion = "2.2.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.0")
        classpath("com.google.gms:google-services:4.3.5")
    }
}
```


### **android/app/build.gradle:**

That was essential to works: insert the material implementation, even you haven't used the CardForm Component.

```
dependencies {
    //::stripe requeriment::
    implementation("com.google.android.material:material:1.4.0")
}
```


### **Android Studio:**

**IMPORTANT**: to material components works, and, consequently, the stripe-react-native, that's necessary download the Andoird 11 (you can [see here](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#2-compile-your-app-with-android-11))

As important as Android 11, is necessary to check if you have downloaded the version SDK tools corresponding to your buildToolsVersion (from gradle file), eg, I've downloaded Android SDK Build 30.0.3, 30.0.0 and 29.0.2 (essential for react naitve) on my Android Studio.


Well, after a lot of testing, this worked for me. I hope this helps you.

Cheers

**Comment by Gabotron-ES** [comment]
> @Gabotron-ES Build still stuck at 79% with the above error

Still stuck at 77%, tried with a new black app and still getting the same error, quite ridiculous...

**Comment by Gabotron-ES** [comment]
I haven't used Android Studio yet, I test with my android phone plugged in, how can I download Android Studio 11?

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES what did you build an app without android studio?

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES please make sure that your `build.gradle` file conforms to this provided by @ggerminiani. The most important thing is build tools version I guess: `buildToolsVersion = "30.0.3"`

**Comment by charliecruzan-stripe** [comment]
@Gabotron-ES are you still running into this issue?

**Comment by charliecruzan-stripe** [comment]
Closing this for now since it seems to be inactive, hopefully the build.gradle changes fixed things. If you're running into this same error and have tried the fix above, please open a new issue with a reproducible demo
