### ISSUE TITLE
Apple Pay 'street' field with two lines not being split

### ISSUE THREAD

**Issue by YoQuieroDistraerlo** [stripe/stripe-react-native#531]
When Apple Pay provides the street field along with city, state, etc., both in billing address and in shipping address and, the address has two lines (e.g., number and street and, suite number, etc.), street is given by Apple Pay as 'line1'\n'line2'. It must be split manually by the developer.
This is not being done in stripe-react-native, instead, all the content of 'street' is loaded in 'line1' field.

1. Call presentApplePay requiring 'postalAddress' for billing or shipping address.
2. In Apple Pay sheet select an address (billing or shipping) with two street lines in it.
3. Check out billingDetails/address/line1 in the payment method returned and both lines will be in line1.
4. Check out billingDetails/address/line2 in the payment method returned and it will be empty.
5. Continue to complete the payment and the same will happen with the shipping address node in the payment intent.

Expected behavior
When a contact's address has two lines, the 'street' field provided by Apple Pay must be split (using '\n' as the separator) and the resulting components must be loaded in the corresponding fields (line1 and line2).

**Smartphone (please complete the following information):**
 - Device: iPhone 11 simulator
 - OS: iOS. 14.5
 - Version:  0.2.0

NOTE: Street is not provided by Apple Pay until the purchase is completed, only the rest of the address fields are provided through useApplePay (onShippingContactSelected).

Workaround
Once the payment method is attached to a customer, split the street and update it to save the changes. Once the payment intent is processed successfully, update its address as well.

**Comment by arekkubaczkowski** [comment]
@YoQuieroDistraerlo thanks for flagging, it's already fixed here https://github.com/stripe/stripe-react-native/pull/548
