### ISSUE TITLE
Device does not have Google Pay but initGooglePay success

### ISSUE THREAD

**Issue by preflower** [stripe/stripe-react-native#533]
**Describe the bug**
Device does not have Google Pay but initGooglePay success, and when i continue to call presentGooglePay function, it return presentForSetupIntent() may only be called when Google Pay is available on this device. error

**Smartphone (please complete the following information):**
 - Device: [OnePlus 5]
 - OS: [Android 10]

**Comment by arekkubaczkowski** [comment]
@preflower thanks for flagging, there was a bug in `initGooglePay` method, now it's gonna be resolved with an error if google pay is not available on the device. https://github.com/stripe/stripe-react-native/pull/546/files
