### ISSUE TITLE
Configure Google Pay Button - Support buttonType and buttonColor

### ISSUE THREAD

**Issue by dali-98** [stripe/stripe-react-native#535]
Greatly benefited by the work! Thanks for writing this amazing package

It would be amazing if we could configure the google button mostly if we could change the text like in native code by just setting `buttonType = "subscribe"` and if we could change the button color to dark i.e black by providing `buttonColor="black"` !

**Comment by arekkubaczkowski** [comment]
@dali-98 we do support only 4 types of google pay buttons atm https://github.com/stripe/stripe-react-native/blob/master/src/components/GooglePayButton.tsx#L18
> and if we could change the button color to dark i.e black by providing buttonColor="black"

button color is set based on system dark mode settings and there is no way to override it atm.

**Comment by dali-98** [comment]
Okay ! Thanks 
Will be looking forward to configure google button !
