### ISSUE TITLE
Don't work out-of-the-box with Jest

### ISSUE THREAD

**Issue by yungkittty** [stripe/stripe-react-native#536]
**Describe the bug**
When running Jest tests on my app I have the following error :

![Screenshot 2021-08-25 at 15 08 53](https://user-images.githubusercontent.com/20394860/130796231-2c0cb43f-234a-4019-9923-728c0130c2f6.png)

When running `cat node_modules/@stripe/stripe-react-native/lib/commonjs/components/StripeProvider.js | grep -i --color package.json` from the root directory of my app :

![Screenshot 2021-08-25 at 15 10 13](https://user-images.githubusercontent.com/20394860/130796512-97c31214-2cc4-410f-8363-ba6bbe6b91d7.png)

I've seen you seem to have a workaround for that here (not sure) :

https://github.com/stripe/stripe-react-native/blob/4b0bcc461ec3a3bdce90b71332d241da03ed943b/src/plugin/__tests__/withStripe-test.ts#L6

But it doesn't work (same error).

What it's weird is that `../../package.json` from `node_modules/@stripe/stripe-react-native/lib/commonjs/components/StripeProvider.js` should be `node_modules/@stripe/stripe-react-native/lib/package.json`.

But even if I do something like :

```javascript
jest.mock(
  '@stripe/stripe-react-native/lib/package.json',
  () => ({
    name: 'stripe-react-native',
    version: '0.1.1',
  }),
  { virtual: true }
);
```

It doesn't work. (Tried with couples of paths but still).

Do you guys have any workaround or insights ?

In the meantime something like that works :

```javascript
const mockStripe = require("@stripe/stripe-react-native");
jest.mock("@stripe/stripe-react-native", () => {
  return mockStripe;
});
```

But it feels akward.

**Comment by arekkubaczkowski** [comment]
@yungkittty @joeyschoblaska you need to mock particular components from the module like this: 
```
jest.mock('@stripe/stripe-react-native', () => ({
  StripeProvider: jest.fn(({children}) => children),
  CardField: jest.fn(({children}) => null),
  presentPaymentSheet: jest.fn(),
  initPaymentSheet: jest.fn(),
}));
```

**Comment by arekkubaczkowski** [comment]
we are going to create complex mock for jest tests so you will be able to use it in the near future.

**Comment by yungkittty** [comment]
@arekkubaczkowski thanks 🙏.
