### ISSUE TITLE
CocoaPods could not find compatible versions for pod "stripe-react-native"

### ISSUE THREAD

**Issue by arunabhverma** [stripe/stripe-react-native#538]
**### When pod install inside the ios directory then getting error**
```
[!] CocoaPods could not find compatible versions for pod "stripe-react-native":
  In Podfile:
    stripe-react-native (from `../node_modules/@stripe/stripe-react-native`)

Specs satisfying the `stripe-react-native (from `../node_modules/@stripe/stripe-react-native`)` dependency were found, but they required a higher minimum deployment target.
```

**To Reproduce**
1. yarn add @stripe/stripe-react-native
2. cd ios && pod install 

**Expected behavior**
pod installed without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/59590144/130948714-363f8296-f8df-42ee-b22e-bf741d8ab4e1.png)

**Comment by arunabhverma** [comment]
> Please see requirements for iOS: https://github.com/stripe/stripe-react-native#ios
> 
> You will need to specify platform 11 as minimum in your podfile, e.g. https://github.com/stripe/stripe-react-native/blob/master/example/ios/Podfile#L1

Thanks it help me lot

**Comment by robschwitzer** [comment]
**For anyone migrating from `tipsi-stripe` and facing this issue even after making sure the iOS platform is set to 11:**

i had to remove tipsi-stripe before running `pod install`, was fine after that

**Comment by Eli-Nathan** [comment]
Worth noting that if you hit this issue in 2022 then you may need to specify `12` as the [minimum](https://github.com/stripe/stripe-react-native/blob/master/example/ios/Podfile#L1) rather than 11 mentioned above 😄

**Comment by Seanmclem** [comment]
I got this on a fresh install, with minimum version set to 12
