### ISSUE TITLE
[EXPO standalone app] url_invalid - return_url Not a valid URL

### ISSUE THREAD

**Issue by shanutthankachan** [stripe/stripe-react-native#539]
confirmPayment return 400 error, Worked fine in Expo Go and Publish, after the build of standalone app returns the error

 **"return_url": "appname:///--/://safepay",**

```
 const handleDeepLink = useCallback(
      async (url: string | null) => {
        if (url && url.includes('safepay')) {
          await handleURLCallback(url);
          console.log('url',url)
          navigation.navigate('Checkout', { url });
        }
      },
      [navigation, handleURLCallback]
    );




  useEffect(() => {
    const getUrlAsync = async () => {
      const initialUrl = await Linking.getInitialURL();
      handleDeepLink(initialUrl);
      console.log('initialUrl',initialUrl)
    };

    const urlCallback = (event: { url: string }) => {
      handleDeepLink(event.url);
    };

    getUrlAsync();

    Linking.addEventListener('url', urlCallback);

    return () => Linking.removeEventListener('url', urlCallback);
  }, [handleDeepLink]);
  /*------------------------------------------*/
```

```
       <StripeProvider
            publishableKey="xyz"
            urlScheme={Linking.createURL('') + '/--/'}
            setUrlSchemeOnAndroid = {true}
            .............................../>
```

Additional context
Standalone app, Expo 42, stripe-react-native :0.1.4

**Additional context**
400 Error
POST /v1/payment_intents/pi_3JSeHwSJwGztdZyL1BuqSJQq/confirm
"return_url": "app:///--/://safepay",
url_invalid - return_url Not a valid URL

https://github.com/stripe/stripe-react-native/issues/370#issuecomment-869912001

**Comment by shanutthankachan** [comment]
@cruzach

**Comment by arekkubaczkowski** [comment]
@cruzach are you able to help with this?

**Comment by cruzach** [comment]
`"return_url": "app:///--/://safepay",` definitely looks wrong to me 😅 

somewhere, `://safepay` is being appended to the url you're setting with `urlScheme={Linking.createURL('') + '/--/'}`, but I'm not sure where.

**Comment by arekkubaczkowski** [comment]
@cruzach it's being set on native side right here: https://github.com/stripe/stripe-react-native/blob/master/ios/Mappers.swift#L645
don't remember the exact purpose of this but I think it should be omitted only within Expo

**Comment by arekkubaczkowski** [comment]
or maybe this `app:///--/` is not a proper url within a standalone app?

**Comment by cruzach** [comment]
Ah yeah, you only need the `/--/` in Expo Go, not in standalone apps. We state this in the docs: https://docs.expo.dev/versions/latest/sdk/stripe/#common-issues

```
urlScheme:
  Constants.appOwnership === 'expo'
    ? Linking.createURL('/--/')
    : Linking.createURL(''),
 ```

**Comment by arekkubaczkowski** [comment]
@cruzach yeah that totally make sense, thanks!
@shanutthankachan that should fix your issue
