### ISSUE TITLE
Payment Sheets & Manually Confirmed Intents

### ISSUE THREAD

**Issue by jack828** [stripe/stripe-react-native#543]
Hello! Thanks for the library! Apologies for opening an issue for a question - I would be happy to open a discussion instead but they are not enabled for the repo.

I am finally performing a migration to this lib from tipsi and I am taking advantage of the beautiful payment sheet integration.

I am however hitting a couple roadblocks with what I used to have and what I now have to have.

My previous flow was:
1. User views checkout page
2. User selects payment method (card/native)
3. A payment method or payment method token is created
4. User's order is sent to server where a manual intent is created with appropriate fees etc
5. Server attempts to confirm/charge the intent, and tells the app if further (SCA) auth is required
6. If approved/not required then another request to the server is made to confirm the intent again
7. The user's order is considered "paid" at this point and out-of-scope things happen

Now with the payment sheets setup I am unable to replicate this behaviour and appear to have to rely on webhooks - but I'd like to keep the old behaviour if at all possible (if it ain't broke, don't fix it) as this means I can guarantee payment will be taken at the time of purchase and not have to handle sending events from the server back to the app to sync states.

After many hours of combing through code/documentation (some props do not match e.g. [presentPaymentSheet](https://stripe.dev/stripe-react-native/api-reference/modules.html#presentPaymentSheet) does not say that it needs `clientSecret` [second code block L5](https://stripe.com/docs/payments/accept-a-payment?platform=react-native#integrate-payment-sheet)) I found this PR https://github.com/stripe/stripe-react-native/pull/514 (which, to confuse matters more, removes `clientSecret` from `presentPaymentSheet` in the examples).

514 suggests that `customFlow` must be used if one needs to manually confirm intents - however I cannot figure for the life of me how this can be done whilst retaining the UI journey from a `customFlow: false` option. The `confirmPayment` option would appear to do what I need!

I hope this makes sense and please ask if you need some code examples.

**Comment by jack828** [comment]
So apologies for immediately commenting after posting an issue...I had spent a while writing that out before trying some other stuff out:

Amending server side intent creation code like so:

```diff
    const paymentIntent = await stripeService.paymentIntents.create({
      amount: 1099,
      currency: 'gbp',
      customer: customer.id,
+     confirmation_method: 'manual',
+     confirm: false
    })
```

And continuing with the paymentsheet stuff like in the example, I get this in my app logs after attempting `presentPaymentSheet`:

```
 LOG  {"result": {"error": {"code": "Failed", "declineCode": null, "localizedMessage": "PaymentIntent with confirmation_method='automatic' is required.
The current PaymentIntent has confirmation_method Manual.
See https://stripe.com/docs/api/payment_intents/object#payment_intent_object-confirmation_method.", "message": "PaymentIntent with confirmation_method='automatic' is required.```

😢

**Comment by jack828** [comment]
Gunna triple comment on my own issue now - I wanted to clarify the payment methods that I'll be using will only ever be card or native pay (Apple/Google Pay). I am unsure and cannot get from the docs whether or not these payments will always be relatively instant. 

If this is the case, I should think this flow may be acceptable:
1. On checkout screen load, send request to server to obtain correctly structured payment intent (with appropriate fees etc)
2. Show "Pay" button to trigger payment flow
3. On complete (resolution from `presentPaymentSheet()` promise), trigger another server request to update state server side, which will check payment intent status with stripe API
4. Update order server side and return updated state

With an additional edge case handling via webhooks to ensure payments that _do_ happen to take longer than that round trip time are correctly updated. Luckily, I had planned integration with firebase to synchronise order state within my app so this should be suitable.

I would still like to ask the question (with the additional one of if the above ☝🏻 is suitable/correct) if manually confirmed payment intents are possible.

**Comment by jack828** [comment]
Any ideas with this one?

**Comment by arekkubaczkowski** [comment]
> 514 suggests that customFlow must be used if one needs to manually confirm intents - however I cannot figure for the life of me how this can be done whilst retaining the UI journey from a customFlow: false option. The confirmPayment option would appear to do what I need!

this change was about only simplifying payment flow from technical POV, which means that if you provided `customFlow` flag in `initPaymentSheet` then you don't need to again specify if it should confirm payment intent or not, because we know it based on this flag.

@paulasjes-stripe would you mind to help answer to the rest of questions?

**Comment by paulasjes-stripe** [comment]
It sounds like what you're trying to do is manual server-side confirmation so you can immediately verify that a payment completed without relying on webhooks. This manual server-side confirmation is possible, but not with the payment sheet unfortunately: https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native

We don't really recommend this flow as it can result in dropped payments. If your user closes the browser or quits the app after doing the 3DS step but before they can be redirected back to your app, you'd never know that the payment is ready to be confirmed again on your server. Hence why we recommend using webhooks, so there's no chance that you miss any important information.

If you don't want to set up a webhook process however, you could immediately check the status of the PaymentIntent after the payment has completed by calling [`retrievePaymentIntent`](https://stripe.dev/stripe-react-native/api-reference/modules.html#retrievePaymentIntent) and checking the resulting PaymentIntent's [status](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-status). This still leaves you vulnerable to the edge case of users quitting before being redirected, but it saves you a roundtrip to your server to check on the PaymentIntent status.

**Comment by trag-stripe** [comment]
@jack828 let us know if you're still having issues - thanks

**Comment by jack828** [comment]
Sorry about that. Been a little busy and my project fell off my radar. I'll look to have a check at this and what has been said and will get back to you hopefully before this weekend.

Have a great week and thanks again for your patience! (and the library)

**Comment by Zurdge** [comment]
@jack828  I'm trying to solve this too this weekend.
I'm trying to reserve a timeslot for my students & take their card details...I only want to charge them once a teacher has confirmed their availability.
If you make any progress do share. Likewise I will :)

**Comment by charliecruzan-stripe** [comment]
hey @jack828 - just checking in to see if you were able to get things working either with the non-Payment Sheet && no-webhooks flow, or with the Payment Sheet && webhooks flow?

**Comment by jack828** [comment]
Hey @charliecruzan-stripe unfortunately the project ended up dying, and it was so long ago I find it hard to remember exactly what I did. I'm pretty sure it never went anywhere since my previous comment.

The ability to do this would be greatly beneficial still though. I appreciate you checking in on this!

**Comment by charliecruzan-stripe** [comment]
Got it, I think if you (or someone else) is trying to do this in the future, they should follow [this comment here](https://github.com/stripe/stripe-react-native/issues/543#issuecomment-915126988), but lmk if you have issues or questions!
