### ISSUE TITLE
Can we use google pay inside ios with pre-built React native ui

### ISSUE THREAD

**Issue by arunabhverma** [stripe/stripe-react-native#547]
Hi, @thorsten-stripe I need to know can we use google pay in ios using react native stripe pre-built Ui

I have using this pre-built ui (multi-step)
[](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet-custom)

please help me.

**Comment by arekkubaczkowski** [comment]
Google pay is not available on iOS the same as Apple Pay is not available on android
