### ISSUE TITLE
Cardfield personalized (" separate inputs with customization by styles with flexbox")

### ISSUE THREAD

**Issue by bert27** [stripe/stripe-react-native#549]
Hello good ,

I recently successfully established cardfield and can add cards, get them and make payments.

Is there a possibility to create a form with custom inputs for this library?

I understand that I should put cardform.
I have not seen photos of his appearance.

I followed the steps to install Material UI, but when you hit the refactor button in Android studio, the app crashes.

Can it be used at the same time with another library as tipsi?

**Comment by arekkubaczkowski** [comment]
@bert27 please use dedicated template for bug report

**Comment by rrsalian16** [comment]
> Hello good ,
> 
> I recently successfully established cardfield and can add cards, get them and make payments.
> 
> Is there a possibility to create a form with custom inputs for this library?
> 
> I understand that I should put cardform. I have not seen photos of his appearance.
> 
> I followed the steps to install Material UI, but when you hit the refactor button in Android studio, the app crashes.
> 
> Can it be used at the same time with another library as tipsi?

@bert27  Did you found any solution ?

**Comment by bert27** [comment]
In the end he redirected to the stripe website with connected accounts.
This allows to transfer money in a simpler way
