### ISSUE TITLE
Apple Pay 'street' field with two lines not being split in payment method billing address

### ISSUE THREAD

**Issue by YoQuieroDistraerlo** [stripe/stripe-react-native#553]
Please see #531, partially resolved by #548.
Summary: the payment method is still being created with the problem reported in #531, which could make address verification service fail. The payment intent passed to 'confirmApplePayPayment' (by means of a client secret) is also being updated with a shipping address with the same problem, which could make the delivery process fail.

After #548 'paymentMethod' returned from 'presentApplePay' has the street correctly split in line1, line2.

``` javascript
const { error, paymentMethod } = await presentApplePay({
  cartItems: items,
  country: 'US',
  currency: 'USD',
  shippingMethods,
  requiredShippingAddressFields: ['name', 'emailAddress', 'postalAddress'],
  requiredBillingContactFields: ['name', 'emailAddress', 'postalAddress'],
  jcbEnabled: true,
});
if (error) throw error;
console.log('paymentMethod', JSON.stringify(paymentMethod, null, 2));
```

This logs both street fields (line1 and line2) correctly:

```javascript
paymentMethod {
  "id": "pm_1JU...g4xi73D",
  "AuBecsDebit": {
    "fingerprint": null,
    "last4": null,
    "bsbNumber": null
  },
  "billingDetails": {
    "email": "customer@mailserver.com",
    "phone": null,
    "name": "Paying Customer",
    "address": {
      "line2": "STE 1234",
      "country": "US",
      "state": "FL",
      "line1": "1111 APPLE ST",
      "city": "MIAMI",
      "postalCode": "33166"
    }
  },
  "livemode": false,
  ...
```

The issue remaining being that the payment method created in this same call to 'presentApplePay', i.e., "id": "pm_1JU...g4xi73D" still has the original problem. The street field is not split in line1, line2.

From stripe dashboard logs:

```json

200 OK | POST | /v1/payment_methods

Request POST body
{
  "billing_details": {
    "address": {
      "city": "MIAMI",
      "country": "US",
      "line1": "1111 APPLE ST\nSTE 1234",  // <== this should be split in line1 and line2
      "postal_code": "33166",
      "state": "FL"
    },
    "email": "customer@mailserver.com",
    "name": "Paying Customer"
  },
  "card": {
    "token": "tok_1JUu...FVP0uEX"
  },
  "type": "card"
}
```

The same happens when the payment intent is confirmed and updated with Apple Pay's selected shipping address:

```json

200 OK | POST | /v1/payment_intents/pi_3JUu1...4IEPED/confirm

Response body
{
  "id": "pi_3JUu1...4IEPED",
  "object": "payment_intent",
  ...
  "shipping": {
    "address": {
      "city": "MIAMI",
      "country": "US",
      "line1": "1111 APPLE ST\nSTE 1234",  // <== this should be split in line1 and line2
      "line2": null,
      "postal_code": "33166",
      "state": "FL"
    },
    "carrier": null,
    "name": "Paying Customer",
    "phone": null,
    "tracking_number": null
  },
  ...
```

 - Device: iPhone11 simulator
 - OS: iOS14.5
 - Version 0.2.0

Workaround

The workaround mentioned in #531 will not fix the address prior to AVS is performed.

**Comment by arekkubaczkowski** [comment]
@YoQuieroDistraerlo iOS team is going to fix it in the near future, I will keep you posted

**Comment by charliecruzan-stripe** [comment]
This has been fixed in the most recent versions of `stripe-react-native` :)
