### ISSUE TITLE
Return Shipping Address in presentApplePay result

### ISSUE THREAD

**Issue by jamiembrown** [stripe/stripe-react-native#556]
**Is your feature request related to a problem? Please describe.**
Currently the `presentApplePay` function returns customer payment information and billing address, but not shipping address. So it's hard to check if the shipping address is one you support before confirming the charge.

**Describe the solution you'd like**
I'd like the user's chosen shipping details to be included in the variable returned by:

`const applePayResult = await presentApplePay()`

**Describe alternatives you've considered**
It may be possible to catch the shipping address by monitoring `onShippingContactSelected` and then storing it somewhere, but it seems a complicated workaround.

**Comment by arekkubaczkowski** [comment]
@jamiembrown sorry but this is the only way to get this atm, and I wouldn't say it's a workaround but rather desired approach.
Please refer to the example for more details https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ApplePayScreen.tsx#L57 and if you still having troubles with implementation I am willing to help you with this.
