### ISSUE TITLE
Issue : TypeError: null is not an object (evaluating '_NativeStripeSdk.default.initialise')

### ISSUE THREAD

**Issue by abxlayedev** [stripe/stripe-react-native#562]
Hi,

I am beginner and I want to use the stripe CardField component. I tried to add the example below "card element only" (https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom) 

But I have this error from the <StripeProvider> component : TypeError: null is not an object (evaluating '_NativeStripeSdk.default.initialise')

I think my issue is because I don't use Expo for my project.

Can you help me to use CardField without expo please ?

Thank you for your help.

**Comment by arekkubaczkowski** [comment]
Please use bug report template

**Comment by martinnogueira** [comment]
hi, how this error was solved? where I can see it. thanks
