### ISSUE TITLE
createToken not working with CardForm 

### ISSUE THREAD

**Issue by taimoorsultani-10p** [stripe/stripe-react-native#566]
**Describe the bug**
My application is already using the `createToken` method to generate a user token, and use it for further processing. I'm really glad that now `Stripe` provided `CardForm`, the UI looks really great, but I'm unable to use the `createToken` with `CardForm`. It was perfectly working fine with `CardField`. Not sure if it's a bug, or I'm missing something. 

**To Reproduce**

Render Method:
`<CardForm onFormComplete={cardDetails => { setCard(cardDetails); }}/>`

Callback:
`

    const onSaveButton = async () => {
        setLoading(true);
        createToken({ type: 'Card'})
           .then(async result => {
             console.log('CardForm, Result is: ', result);
             let tokenId = null;
            if (result?.error?.message) {
              showError(result?.error?.message);
              return;
            }
            tokenId = result?.token?.id;
          })
          .catch(err => {
             console.log('CardForm, Error is: ', err);
          })
          .finally(() => setLoading(false));
      };

`
**Expected behavior**

My understanding is that `CardForm` should work like `CardField` and provide a `token`.  But `createToken` returns an error **Card details not completed**.

**Screenshots**
![stripe-card-form](https://user-images.githubusercontent.com/86574738/132218978-87dc544a-2728-4d64-afe1-02cb50cac30b.jpg)

**Desktop (please complete the following information):**
 - OS: macOS-BigSur

**Smartphone (please complete the following information):**
 - Device: iPhone-X
 - OS: iOS-14.7.1

**Comment by arekkubaczkowski** [comment]
@taimoorsultani-10p it is already fixed here https://github.com/stripe/stripe-react-native/pull/521
you can install library with specified master branch or wait for the next release.
