### ISSUE TITLE
CardForm component input field issue

### ISSUE THREAD

**Issue by smeetagrawal** [stripe/stripe-react-native#567]
*Card Form component is not working as expected*
When Card Form is rendered and user starts entering form details for each fields, getting an error like TextInputState.focusInput is not a function.

**To Reproduce**
1. After Card Form rendered successfully.
2. User starts filling the form details and when user enters a single value for that field, getting an error for it.

**Expected behavior**
No such error comes when user fills the form details as it was expected.

**Screenshots**
![CardForm input error](https://user-images.githubusercontent.com/21281748/132246779-3937a6a7-c424-402d-a0c3-764f12bc453f.png)

**Smartphone**
 - Device: Motorola G5 plus
 - OS: Android 8.1.0 (Oreo)
 
 **Packages Details**
Packages used
"react": "16.13.1"
"react-native": "^0.61.4"
"@stripe/stripe-react-native": "^0.2.0"

*Code Implemented in order to get form*
```
<SafeAreaView style={styles.safeView}>
	<ScrollView>
		<View style={styles.safeView}>
			<View style={styles.cardContainer}>
				<CardForm
					autofocus
					onFormComplete={(cardDetails) => {
						console.log(cardDetails);
					}}
				/>
			</View>
		</View>
	</ScrollView>
</SafeAreaView>
```

One more thing I want to inform you that If I update my react-native version to 0.63.4 then this issue does not occur, but I cannot update my application to react-native 0.63.4 version.

**Comment by arekkubaczkowski** [comment]
@smeetagrawal actually this specific issue shouldn't occurs from 0.62.x or higher, however I am going to fix it to be working also within lower versions

**Comment by smeetagrawal** [comment]
Can you please provide me information when above issue fix will get released and in which specific version, so I can implement CardForm in my application.

**Comment by arekkubaczkowski** [comment]
you will need to wait couple of weeks for the next release probably but you are able to install library with specified branch name like: 
```
yarn add stripe/stripe-react-native#fix/card-form-methods
```

**Comment by arekkubaczkowski** [comment]
I will keep this branch alive until the next release so you can use it at the moment.

**Comment by smeetagrawal** [comment]
Thank you for your feedback and support, will install library with this *yarn add stripe/stripe-react-native#fix/card-form-methods*.
