### ISSUE TITLE
CardField is not working properly while using ScrollView as parent component on android

### ISSUE THREAD

**Issue by SaeedGujjar** [stripe/stripe-react-native#570]
**Describe the bug**
when use CardField under the scrollView whole screeen get stucked and get console cardField is selected 
**To Reproduce**
1-in return function use scrollView as parent and use CardField as child 
2-click on the card
3-click outside the card 
4-check your console while click outside the card

code is here.
import React, {useEffect, useRef, useState} from 'react';
import {CardField, useStripe} from '@stripe/stripe-react-native';
import {
  TouchableOpacity,
  Text,
  View,
  Image,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  SafeAreaView,
} from 'react-native';
function App() {
  return (
    <StripeProvider
      publishableKey={publishableKey}
      merchantIdentifier="merchant.identifier">
      <PaymentScreen />
    </StripeProvider>
  );
}
// PaymentScreen.ts
export default function PaymentScreen() {
  const {confirmPayment} = useStripe();
  return (
    <ScrollView 
    scrollEnabled={false}>
      <CardField
      
        postalCodeEnabled={false}
        placeholder={{
          number: '4242 4242 4242 4242',
        }}
        cardStyle={{
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
        }}
        style={{
          paddingVertical: 50,
          // width: '100%',
          // height: 50,
          // marginVertical: 30,
        }}
        onCardChange={cardDetails => {
          console.log('cardDetails', cardDetails);
        }}
        onFocus={focusedField => {
          console.log('focusField', focusedField);
        }}
      />
    </ScrollView>
  );
}
Stripe version:    "@stripe/stripe-react-native": "^0.1.2",

**Comment by arekkubaczkowski** [comment]
@SaeedGujjar please use bug report template

**Comment by arekkubaczkowski** [comment]
also I would suggest to upgrade library to the latest version
