### ISSUE TITLE
Impossible to correct a wrong entered information in CardField - iOS only bug

### ISSUE THREAD

**Issue by magicmove** [stripe/stripe-react-native#572]
**Describe the bug**
Using CardField component, if user enters a wrong information, for example a wrong card number, then tries to go back to the card number from expiration date to correct the card number, the keyboard disappears and no matter how many times he touches the card number the keyboard does not come back. At this moment, touching the CardField produces a placeholders glitch. 

The only was to unlock it is to submit the wrong or uncompleted CardField and then touching the card number makes the keyboard appear again.

**To Reproduce**
1. Go to the screen where CardField appears
2. Enter a card number
3. Enter the expiration date
4. Try to come back to the card number to change it

**Expected behavior**
The keyboard should appear and the card number field should act like a normal text field.

**Screenshots**
![Simulator Screen Shot - iPhone 12 - 2021-09-08 at 10 42 42](https://user-images.githubusercontent.com/79968676/132488758-598b465b-1b6c-4bd7-83d1-cb7780acb3e8.png)
![Simulator Screen Shot - iPhone 12 - 2021-09-08 at 10 43 00](https://user-images.githubusercontent.com/79968676/132488787-207dfcef-e661-401a-800b-99a299f88792.png)

**Smartphone**
 - Device: iPhone12 simulator and iPhone 11 pro max real device
 - OS: 14.4

**Additional context**
@stripe/stripe-react-native: "^0.1.4",

**Comment by arekkubaczkowski** [comment]
@magicmove can you record a video what exactly happens on your end? I haven't noticed anything unexpected

https://user-images.githubusercontent.com/18654447/132491883-8dff8768-ad1b-4ee1-b47f-e7876110199f.mov

**Comment by arekkubaczkowski** [comment]
the same with enabled postal code:

https://user-images.githubusercontent.com/18654447/132492216-c00a0a6e-004d-4864-a6e0-c31ee9bb2d00.mov

**Comment by magicmove** [comment]
Thank you for the fast replay. There is the video.

https://user-images.githubusercontent.com/79968676/132510239-b2634f39-5d32-4d13-9c3a-205a76ce7caf.mov

And this is how I added it. 

```
    <View>
      <CardField
        postalCodeEnabled={true}
        placeholder={{
          expiration: 'Expire le',
          postalCode: 'Code postal',
        }}
        cardStyle={{
          backgroundColor: Colors.whiteLighter,
          textColor: Colors.black,
        }}
        style={{
          width: '100%',
          height: 50,
          marginVertical: 30,
        }}
        onCardChange={(card: any) => card.complete && setCardComplete(card.complete)}
      />

      <ButtonFit
        disabled={!cardComplete}
        title="Ajouter une carte"
        style={Colors.black}
        onPress={() => {
          saveCard().catch((err: any) => {
            cardError(err);
          });
        }}
      />
    </View>
```

**Comment by arekkubaczkowski** [comment]
that's super weird and cannot reproduce it, are you able to update library to the latest version?

**Comment by arekkubaczkowski** [comment]
just to make sure, can you try to remove all of your code from this specific screen and leave only CardField then check how it behave?

**Comment by magicmove** [comment]
I just updated the package, but it didn't help. Removing everything from the component makes it work so the problem is coming from our code.

Sorry for the wasted time and thank you for the reactivity! That's all for me :)
