### ISSUE TITLE
Context Registered Broadcast Receivers

### ISSUE THREAD

**Issue by nvarsh** [stripe/stripe-react-native#573]
Hey all,

Our team is using the Stripe-React-Native SDK and we are concerned with how the broadcast receivers can be used.

We are hoping the devs can shed some light and answer the following question:
Q. Can these broadcast receivers be used maliciously by other applications on the Android OS?

Our primary goal is to ensure 3rd party libraries do not become security concerns.

**Comment by michelleb-stripe** [comment]
@nvarsh Thanks for asking this. After reviewing this SDK's use of broadcast receivers, we agree that there is a risk of unintended communication between the SDK and other applications on the device. We've switched to using LocalBroadcastManager as an immediate fix, and will remove all use of broadcast receivers in a future update.

This change has been released as 0.2.2, and is live now. 

We hope this helps with your continued usage of the SDK, please let us know if you have any other questions.
