### ISSUE TITLE
initPaymentSheet error

### ISSUE THREAD

**Issue by katiachumakova** [stripe/stripe-react-native#574]
**Describe the bug**
When using initPaymentSheet it always returns an error:

`{code: "Failed", localizedMessage: "There was an unexpected error -- try again in a few seconds", message: "There was an unexpected error -- try again in a few seconds", declineCode: null, type: null, …}`

Also getting the same error on presentPaymentSheet (if I use `confirmPayment: false` the Payment Sheet doesn't open at all, if I don't use it then it opens and closes automatically with the same error).

Using iOS, I haven't tested this on Android.

My code:

Server

```
exports.paymentSheet = functions.https.onRequest(
  async (req, res) => {
  const customer = await stripe.customers.create();
  const ephemeralKey = await stripe.ephemeralKeys.create(
    {customer: customer.id},
    {apiVersion: '2020-08-27'}
  );
  const paymentIntent = await stripe.paymentIntents.create({
    amount: 1099,
    currency: 'usd',
    customer: customer.id,
  });
  res.json({
    paymentIntent: paymentIntent.client_secret,
    ephemeralKey: ephemeralKey.secret,
    customer: customer.id
  });
});
```

Client

```
  const fetchPaymentSheetParams = async () => {
    const response = await fetch(`${API_URL}/paymentSheet`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const {paymentIntent, ephemeralKey, customer} = await response.json();

    return {
      paymentIntent,
      ephemeralKey,
      customer,
    };
  };

  const initializePaymentSheet = async () => {
    const {paymentIntent, ephemeralKey, customer} =
      await fetchPaymentSheetParams();

    const {error, paymentOption} = await initPaymentSheet({
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,
      customFlow: true,
      merchantDisplayName: 'Example Inc.',
      style: 'alwaysDark',
    });

    setLoading(false);
    if (error) {
      Alert.alert(`Error code: ${error.code}`, error.message);
    }
    // updateButtons(paymentOption);
  };


  useEffect(() => {
    initializePaymentSheet();
  }, []);
```

Btw, this is a duplicate of #461 sorry couldn't reopen the issue.

**Versions**
 - "react-native": "0.64.2"
 - "@stripe/stripe-react-native": "0.1.5"

**Comment by arekkubaczkowski** [comment]
Have you checked whether you provide correct params to initPaymentSheet? i.e. customerId, customerEphemeralKeySecret and paymentIntentClientSecret

**Comment by katiachumakova** [comment]
@arekkubaczkowski yes, these are the params and they all return values:

```
res.json({
    paymentIntent: paymentIntent.client_secret,
    ephemeralKey: ephemeralKey.secret,
    customer: customer.id
  });
```

**Comment by bbenson09** [comment]
Have you checked your API keys? I have gotten this error before on initPaymentSheet, and it was because I wasn't using the correct publishable key. presentPaymentSheet definitely won't work if initPaymentSheet doesn't.

**Comment by katiachumakova** [comment]
@bbenson09 Checked API keys, they are correct and I can see the customers being created in the stripe panel

**Comment by katiachumakova** [comment]
any update?

**Comment by RyanMan56** [comment]
Getting this error too

**Comment by arekkubaczkowski** [comment]
can you please upgrade library to the latest version? There are improved error messages

**Comment by katiachumakova** [comment]
Thank you! I was using expired keys. I'm going to close this issue.

**Comment by arekkubaczkowski** [comment]
@RyanMan56 please make sure that you also provide correct API keys, otherwise please create a separate issue with all needed details

**Comment by dragma** [comment]
I have the same error. This occurred on iOS only. The same code runs on Android like a charm. Same code, same server, same configuration, same keys, same everything.

**Comment by Brainilio** [comment]
Keep getting the same error... Any ideas??? https://github.com/stripe/stripe-react-native/issues/750

**Comment by jordzawada** [comment]
This is happening on iOS and Android, but no on my android emulator.

**Comment by Brainilio** [comment]
i resolved my issue by upgrading stripe & expo by the way.

**Comment by jordzawada** [comment]
> i resolved my issue by upgrading stripe & expo by the way.

which versions?

**Comment by jordzawada** [comment]
> > 
> 
> i'm currently running these versions: "react": "17.0.1", "react-dom": "17.0.1", "react-native": "0.64.3", "expo": "^44.0.0", "@stripe/stripe-react-native": "0.2.3",

upgrading to expo 42/43 from 41 solved it for me too.

**Comment by Brainilio** [comment]
> > > 
> > 
> > 
> > i'm currently running these versions: "react": "17.0.1", "react-dom": "17.0.1", "react-native": "0.64.3", "expo": "^44.0.0", "@stripe/stripe-react-native": "0.2.3",
> 
> upgrading to expo 42/43 from 41 solved it for me too.

Happy to hear that!
