### ISSUE TITLE
Be able to add parameters to confirmPaymentSheetPayment

### ISSUE THREAD

**Issue by FelipeVa** [stripe/stripe-react-native#576]
**Is your feature request related to a problem? Please describe.**
I've been working with the paymentSheet and I noticed something, there's no way to enter parameters to the confirmPaymentSheetPayment. For example, with confirmPayment you can do it. Right Now I want to set the billingDetails, but I don't see a way to do it.

**Describe alternatives you've considered**
Right now, I don't feel I have any alternatives to handle this.

**Comment by charliecruzan-stripe** [comment]
Hi! sorry for the late response- you can set the `defaultBillingDetails` for your payment sheet in your `initPaymentSheet` call 👍  Let me know if there's something else you're looking for or something about your use case that makes that impossible
