### ISSUE TITLE
[Expo][iOS] App crashes on presentPaymentSheet with React Navigation

### ISSUE THREAD

**Issue by bbenson09** [stripe/stripe-react-native#579]
Hi, calling `presentPaymentSheet` causes my app to crash with no useful error messages. I'm getting the error, `Service exited due to SIGABRT`. 

I am able to get the paymentOption from `initPaymentSheet` and am not receiving any errors with that function, so I believe I have set up the StripeProvider correctly.

I have also confirmed that I have successfully set `paymentIntent`, `ephemeralKey`, and `customerId`.

Here is the relevant code:

**Initializing Payment**
```
useEffect(() => {
    const initializePaymentSheet = async () => {
      console.log('initializing payment sheet');
      setState({ ...state, paymentSheetLoading: true });
      const variables = { phone, email, customerId, products, promo };
      const { paymentIntent, ephemeralKey, customer } = await fetchPaymentSheetParams(variables);

      const paymentVariables = {
        customerId: customer,
        customerEphemeralKeySecret: ephemeralKey,
        paymentIntentClientSecret: paymentIntent,
        customFlow: true,
        merchantDisplayName: 'Flyby',
        applePay: true,
        merchantCountryCode: 'US',
        googlePay: true,
        testEnv: true,
      };

      console.log(paymentVariables);

      const { paymentOption, error } = await initPaymentSheet(paymentVariables);

      if (!error) {
        console.log('no error');
        setState({
          ...state,
          paymentMethod: paymentOption,
          paymentSheetEnabled: true,
          clientSecret: paymentIntent,
          paymentSheetLoading: false,
        });
      } else {
        setState({ ...state, paymentSheetLoading: false });
        console.error(error);
      }
    };
    initializePaymentSheet();
  }, []);
```

**Choosing payment object**
```
const choosePaymentOption = async () => {
    if (!clientSecret) {
      return;
    }
    console.log('choosing payment option');
    console.log(clientSecret);

    let results;
    try {
      results = await presentPaymentSheet({
        confirmPayment: false,
        clientSecret: clientSecret,
      });
    } catch (e) {
      console.log(e);
    }
    const { error, paymentOption } = results;

    console.log(paymentOption);

    if (error) {
      console.log('error', error);
    } else if (paymentOption) {
      setState({
        ...state,
        paymentMethod: {
          label: paymentOption.label,
          image: paymentOption.image,
        },
      });
    } else {
      setState({ ...state, paymentMethod: null });
    }
  };
```

**Component**
```
<TouchableOpacity onPress={choosePaymentOption} disabled={!paymentSheetEnabled}>
     <View>
          <SectionTitle>Add Payment Method</SectionTitle>
          <FontAwesomeIcon icon={faPlus} />
     </View>
</TouchableOpacity>
```

I am using React Navigation. I have read that presentPaymentSheet doesn't work in modals, and my screen is _not_ a modal.

Any ideas or suggestions on how to debug this would be very much appreciated!!

**Comment by arekkubaczkowski** [comment]
@bbenson09 which version of library do you use?

**Comment by brdlysmth** [comment]
I'm experiencing the same issue with Expo Go and Stripe payment sheet in React Native. The payment sheet will crash when I try to input the test card details with no useful error messages 

```
"code": "Canceled",
"declineCode": null,
"localizedMessage": "The payment has been canceled",
"message": "The payment has been canceled",
"stripeErrorCode": null,
"type": null,
```

- "@stripe/stripe-react-native": "^0.2.0"
- "expo": "~42.0.0"
- "react-native": "^0.64.2"

**Comment by bbenson09** [comment]
Thanks, Arek. I'm using:

- "@stripe/stripe-react-native": "^0.2.1"
- "expo": "^42.0.0"
- "react-native": "~0.63.4"

**Comment by arekkubaczkowski** [comment]
If you are using Expo please follow installation steps https://github.com/stripe/stripe-react-native#expo

**Comment by bbenson09** [comment]
Yes, thank you. I followed the installation steps three times.

**Comment by arekkubaczkowski** [comment]
So the docs says that you can't use latest version of library within Expo. https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md#014---2021-06-04---expo-sdk-4200

**Comment by bbenson09** [comment]
This was the issue! Thanks for your help!
