### ISSUE TITLE
Does not work: The style on this component requires your app theme to be Theme.MaterialComponents

### ISSUE THREAD

**Issue by talaikis** [stripe/stripe-react-native#581]
**Describe the bug**

Adding the CardForm gives

```
The style on this component requires your app theme to be Theme.MaterialComponents
```

**Smartphone (please complete the following information):**
 - Device: Android 11 emulator
 - OS: Windows 10

**Comment by wcastand** [comment]
what did you do to fix this?
i still the error making the android crash (works fine in emulator for me but users have crashes on the cardForm)

using expo managed here

**Comment by talaikis** [comment]
> what did you do to fix this? i still the error making the android crash (works fine in emulator for me but users have crashes on the cardForm)

Don't know about managed, but for bare RN just replace with`<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">` inside `res/values/styles.xml`

Maybe this will work for you (not tried though): https://chafikgharbi.com/expo-android-manifest/

**Comment by sebastienlabine** [comment]
@wcastand did you manage to make it work with the managed flow? Expo Prebuild always creates a new AppTheme...

I'm not so much of an android developer myself, but how can we tweak the android manifest to set our theme @talaikis?

**Comment by wcastand** [comment]
added this into app.config.js: 
```
{
  plugins: ['./android-material.plugins.js'],
  [...],
}
```

```
// android-material.plugins.js
const { withAndroidStyles } = require('@expo/config-plugins');

module.exports = function androidStyles(config) {
	return withAndroidStyles(config, async config => {
		config.modResults.resources.style = config.modResults.resources.style.map(s => {
			if (s['$'] && s['$'].name === 'AppTheme') {
				return {
					...s,
					['$']: {
						name: 'AppTheme',
						parent: 'Theme.MaterialComponents.DayNight.NoActionBar',
					},
				};
			}
			return s;
		});

		return config;
	});
};
```
