### ISSUE TITLE
CardForm on Android response is empty

### ISSUE THREAD

**Issue by QQizi** [stripe/stripe-react-native#585]
**Describe the bug**
On Android, the CardForm component display correctly but the datas in onFormComplete callback is always empty. Everything is ok on IOS

**To Reproduce**
`
<CardForm
  onFormComplete={cardDetails => {
  console.log('card details', cardDetails);
  if (cardDetails.complete) {
    setCardDetails(cardDetails);
    setComplete(true);
  }
}}
cardStyle={inputStyles}
/>`

**Expected behavior**
I'm expecting the cardDetails to look something like : 
`{ last4: "4242", expiryMonth: 4, expiryYear: 24, complete: true, brand: "Visa", country: "AF", postalCode: "9" }`

Instead i'm getting : 

`{ last4: undefined, expiryMonth: undefined, expiryYear: undefined, complete: undefined, brand: undefined, country: undefined, postalCode: undefined }`

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s20
 - OS: Android 11
 - Version 0.2.0

**Comment by arekkubaczkowski** [comment]
@QQizi can you please check if below thread is related to your issue?
https://github.com/stripe/stripe-react-native/issues/517#issuecomment-898234293

**Comment by charliecruzan-stripe** [comment]
This means the CardForm doesn't have all fields completed yet. As stated in the other issue, make sure you have enough of a `height` set on the component to see all input fields.
