### ISSUE TITLE
No static field stripe_default_reader_id 

### ISSUE THREAD

**Issue by bitkidd** [stripe/stripe-react-native#592]
**Describe the bug**
Trying to replace `tipsi-stripe`. The project builds just fine, but when I try to use `<CardField />` component, app crashes with an error:

```
java.lang.NoSuchFieldError: No static field stripe_default_reader_id of type I in class Lcom/stripe/android/R$id; or its superclasses (declaration of 'com.stripe.android.R$id' appears in /data/app/***-lw2TFOoXxyiRP4Z0n_BdfQ==/base.apk!classes24.dex)
        at com.stripe.android.view.CardInputWidget.<clinit>(CardInputWidget.kt:1206)
```

**To Reproduce**

**Expected behavior**
Expected to see `<CardField />` component.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia
 - OS: Android 9

**Additional context**
RN 0.65.1

**Comment by arekkubaczkowski** [comment]
@bitkidd did you uninstall tipsi-stripe from your project? There might by mismatch versions of stripe-android which both libraries include
