### ISSUE TITLE
alwaysDark style for PaymentSheet not functional in Android apps - system theme always applied 

### ISSUE THREAD

**Issue by brendanm-stripe** [stripe/stripe-react-native#593]
**Describe the bug**
When trying to force dark theme using `style='alwaysDark'` in `initPaymentSheet`, Payment Sheet in Android apps do not actually always use dark theme. Instead, they end up getting the system light vs dark theme applied, you can toggle it via system settings to see it switch.

**To Reproduce**
1. Run the example app included in this repository. Note that [PaymentsUICompleteScreen](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICompleteScreen.tsx#L58) and [PaymentsUICustomScreen](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICustomScreen.tsx#L50) both include `style='alwaysDark'`.
2. In the example app, go to Accept a Payment > Prebuilt UI (either version). Press the button (top on custom/multi-step).
3. Notice on Android that the PaymentSheet theme matches the system theme, `alwaysDark` is not honoured. iOS PaymentSheet adheres to provided theme.

**Expected behavior**
Android PaymentSheet should always be dark when `style='alwaysDark'` is set.

**Screenshots**
In all examples, `style='alwaysDark'` is set.

Android with light system theme
![alwaysDark-system-override](https://user-images.githubusercontent.com/57721954/133710792-9ae27930-146e-4092-b91c-260e50d913f6.jpg)

Android with dark system theme
![alwaysdark-system-override-dark](https://user-images.githubusercontent.com/57721954/133710770-91cfe2eb-82af-4792-86a2-4f45bb58bb11.jpg)

iOS 
![iphone-alwaysdark-correct](https://user-images.githubusercontent.com/57721954/133710745-747fb528-c5d9-468a-9e06-c17594e1d9c5.jpg)

**Smartphone (please complete the following information):**
 - Device: Pixel 4 AVD
 - OS: Android 10
 - Browser N/A
 - Version SDK 29 on virtual device per RN instructions

**Additional context**

**Comment by michelleb-stripe** [comment]
@brendanm-stripe This is not something that the android currently supports, but we do have it in our backlog.  I will post an update when we have it complete.

**Comment by brendanm-stripe** [comment]
Ah, excellent, thanks! Looking forward to that :)

**Comment by JigarAdesara1** [comment]
Hello @skyler-stripe,

We are creating an application that has a dark theme only throughout the app and it's not changeable so to match the payment sheet with our app's theme we require this force dark mode feature, It's working fine with iOS but with Android, it's not working

**Comment by skyler-stripe** [comment]
Thanks for the responses! 

We're looking into customization changes and will keep dark mode toggling in mind. In the mean time, it does seem possible that forcing dark mode at an application level is a solution for those that want to match. [According to this](https://stackoverflow.com/questions/57175226/how-to-disable-night-mode-in-my-application-even-if-night-mode-is-enable-in-andr) you can put this line in your launcher activity's `onCreate` and force darkmode.

```
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
```

I'm hoping that is a good solution/bandaid while we work on more sophisticated customization.

**Comment by gauravag23** [comment]
You can check color scheme and set cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}as per light or dark theme.
