### ISSUE TITLE
Please keep supporting react-native@0.63.4 because expo/expo uses it

### ISSUE THREAD

**Issue by umrashrf** [stripe/stripe-react-native#596]
**Describe the bug**
I am getting this exception with latest version of stripe-react-native with fresh/new `expo init` project when I use `<CardField />` on the Web. **It works fine on iOS simulator and my iPhone device.**
```
Failed to compile.
./node_modules/react-native/Libraries/Components/TextInput/TextInputState.js
Module not found: Can't resolve '../../Utilities/Platform' in '/Users/.../Desktop/expo_test_app/node_modules/react-native/Libraries/Components/TextInput'
```

**To Reproduce**
1. expo init
2. cd expo_test_app
3. yarn install @stripe/stripe-react-native
4. Use `<CardField />`

**Expected behavior**
It should work on the Web using `yarn web`.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5 M1 arm64
 - Browser: Safari
 - Version: v0.2.2

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 14.8
 - Browser Expo Client
 - Version: N/A

**Additional context**

**Comment by arekkubaczkowski** [comment]
This library supports RN 0.63.x, in order to install library within Expo Please follow the steps from the docs https://github.com/stripe/stripe-react-native#expo

**Comment by arekkubaczkowski** [comment]
But it doesn't support react native Web, you need to use this lib  https://github.com/stripe/react-stripe-js for such purpouses

**Comment by moza88** [comment]
Thank you @arekkubaczkowski for sharing the library.

**Comment by moza88** [comment]
Thank you @arekkubaczkowski for sharing the library. But I am still having issues compiling my web app even after I use it. Is there example code somewhere that show us how to use stripe for our expo app that can run on all 3 types of platforms, ios, android, and web. Even if I have platform conditions it's giving me the error.

**Comment by ollyde** [comment]
I'm trying to use both libs but I can't seem to ignore the import for @stripe/stripe-react-native even when using different files.
