### ISSUE TITLE
undefined-symbols-for-architecture-x86_64-on-ios after adding Stripe React Native

### ISSUE THREAD

**Issue by gbmahili** [stripe/stripe-react-native#599]
**Describe the bug**
I am getting the following error when I run the app in **Release** mode.
`undefined-symbols-for-architecture-x86_64-on-ios`

That error is documented [here](https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios) but it only fixes the issue in the **Debug scheme**, not in the **Release scheme.**

That same fix is also documented [here](https://github.com/react-native-community/upgrade-support/issues/62#issuecomment-622985723) but also fix the issue in the Debug scheme, not the Release scheme.

**To Reproduce**
1. Install a new React Native app
2. Add Stripe as instructed in the Getting started documentation
3. Open your project via Xcode, go to project -> build settings, find library search paths and remove all swift related entries such as: `$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)` and `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)`.
4. Create a new Swift file to the project (File > New > File > Swift), give it any name (e.g. Fix.swift), and create a bridging header when prompted by Xcode.
5. Run the app in Debug scheme (From your XCode,  go to Product > Scheme > Edit Scheme) and choose Run on the left and select Debug in the right pane, do the same for Test
6. Run the app
7. The app will build successfully
8. Repeat step 5 but change Debug to Release then run the app, Build will fail with error `undefined-symbols-for-architecture-x86_64-on-ios`

**Expected behavior**
The app should build successfully in the Release scheme just like how it is building successfully in the Debug Scheme.

**Screenshots**
<img width="1680" alt="Screen Shot 2021-09-20 at 8 00 28 AM" src="https://user-images.githubusercontent.com/12724186/133999572-ef5554a9-5007-4237-a575-5ea3edf65d55.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max Simulator
 - OS: 14.5

**Comment by arekkubaczkowski** [comment]
@gbmahili have you removed those library search paths entries both for debug and release mode
<img width="845" alt="Zrzut ekranu 2021-10-4 o 11 58 06" src="https://user-images.githubusercontent.com/18654447/135831687-ea16b745-17d1-4f45-b10e-857fb1bda6e2.png">
?

**Comment by michaelbayday** [comment]
also getting this issue and these entries are not within my repo

**Comment by michaelbayday** [comment]
```
❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_RCTEventEmitter
> Referenced from: type metadata for stripe_react_native.StripeSdk in StripeSdk-a3ebf5d1e464abf21f2a5d95fac11bff897a445930bcdef1f62aed67246f0d19.o
```

**Comment by arekkubaczkowski** [comment]
@michaelbayday what version of react-native and library are you using? 
Assuming that you went trough all of the points form troubleshooting section list, there are couple more things to check:
- make sure that  the `platform :ios` version in your Podfile is `11` at least 
- above mentioned version is consistent with this specified in your XCode settings:
<img width="520" alt="Zrzut ekranu 2021-10-5 o 15 00 52" src="https://user-images.githubusercontent.com/18654447/136150488-806c5c32-fd47-4ae8-a018-8d4c7b87925d.png">

Are you having this issue within debug or release schema?

**Comment by FilatovHerman** [comment]
> @gbmahili have you removed those library search paths entries both for debug and release mode?
> <img alt="Zrzut ekranu 2021-10-4 o 11 58 06" width="845" src="https://user-images.githubusercontent.com/18654447/135831687-ea16b745-17d1-4f45-b10e-857fb1bda6e2.png">

Hi) I have the same problem with stripe-react-native         
I did everything as on the screen, but another problem appeared -
ld: library not found for -lCocoaAsyncSocket

I did pod install - everything was ok

Also my Build Settings -> Library Search paths 
![image](https://user-images.githubusercontent.com/47091417/137640395-2645a54c-6f13-481b-a5fb-80cc2713e2de.png)

**Comment by insteptech** [comment]
same issue: 

need help

<img width="1054" alt="Screenshot 2021-12-29 at 1 01 18 PM" src="https://user-images.githubusercontent.com/9575126/147637806-909ecf67-5d36-4a0c-8f97-1c8a8de8c216.png">
e

**Comment by iranaahsanali** [comment]
I have the same issue.

**Comment by DanielDanaee** [comment]
Any updates on this?

I have the same issue

> same issue:
> 
> need help
> 
> <img alt="Screenshot 2021-12-29 at 1 01 18 PM" width="1054" src="https://user-images.githubusercontent.com/9575126/147637806-909ecf67-5d36-4a0c-8f97-1c8a8de8c216.png">

**Comment by Eli-Nathan** [comment]
Same issue, tried all the options with clearing Library Search paths to just have the `inherited` value and creating the empty swift file for create the bridging header but i'm still getting this problem.
Xcode 13
RN 0.64.1
@stripe/stripe-react-native 0.8.0

**Comment by metinjakupi** [comment]
Any update on this issue? 
I have the same issue

**Comment by Eli-Nathan** [comment]
I may have found a solution. The [README's troubleshooting guide](https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios) wasn't exactly right in my case.

It said to remove the swift entries from the library search paths.

But I had to remove everything and just leave the `inherited` value. See screenshot below.

You could also head to your `[Project name].pbxproj` file and find references to `LIBRARY_SEARCH_PATHS` and make sure they only have the inherited value in them there.

I have 4 references to `LIBRARY_SEARCH_PATHS` in the file and I made them all look like this:
```txt
LIBRARY_SEARCH_PATHS = "$(inherited)";
```

and now it works!

![Screenshot 2022-07-19 at 10 43 57](https://user-images.githubusercontent.com/32842898/179720848-598105e2-4b23-482b-827e-3c0bdcdffbf7.png)

**Comment by metinjakupi** [comment]
@Eli-Nathan Do you have MPB M1 or Intel?

**Comment by Eli-Nathan** [comment]
I had an Intel up until last week so I was able to test on that and it worked 😄 

I now have an M1 and as long as i'm running Xcode in rosetta mode then it works there too

**Comment by metinjakupi** [comment]
This solution fixed my issue 
https://github.com/facebook/react-native/issues/31941#issue-959300156

**Comment by charliecruzan-stripe** [comment]
If you're using an M1, the above comment from @metinjakupi should resolve things for you!

Otherwise, [this comment contains the correct solution](https://github.com/stripe/stripe-react-native/issues/599#issuecomment-1188847671) (which is also mentioned in our readme :) )
