### ISSUE TITLE
Subsequent calls to `handleCardAction` on a PaymentIntent with status `RequiresAction` fail

### ISSUE THREAD

**Issue by lucasroca** [stripe/stripe-react-native#602]
**Describe the bug**
After killing the app while the first 3D Secure 2 authentication is in progress, calling `handleCardAction` subsequent times on a PaymentIntent with status RequiresActions returns an error.
Could it be related to 3D Secure 2 authentication? Because I'm only having this problem when testing with the card 4000000000003220.

**To Reproduce**
@stripe/stripe-react-native v0.2.2

1. Create a Customer and add 4000000000003220 as an off-session card
2. Create a PaymentIntent server-side
3. Retrieve it with`retrievePaymentIntent`
4. Its status is RequiresAction, so call `handleCardAction`
5. When the authentication modal opens don't press any CTAs, just kill the app
6. Reopen the app, repeat steps 3 and 4, now `handleCardAction` returns an error

The error is different depending on the platform.

**PaymentIntent**:
```json
{
    "shipping": null,
    "lastPaymentError": null,
    "paymentMethodId": "pm_1Jc3K3IawKXSD15nUlW5EKjw",
    "currency": "dkk",
    "captureMethod": "Automatic",
    "status": "RequiresAction",
    "description": "MANUAL_TOP_UP",
    "amount": 60000,
    "confirmationMethod": "Automatic",
    "livemode": false,
    "clientSecret": "pi_3Jc3d4IawKXSD15n12C2xIXl_secret_61odyJ7tqol9hwBZruwXk5k7A",
    "created": "1632210182000",
    "receiptEmail": null,
    "canceledAt": "0",
    "id": "pi_3Jc3d4IawKXSD15n12C2xIXl"
}
```
Error on **iOS**:
```json
{
    "code": "Failed",
    "localizedMessage": "There was an unexpected error -- try again in a few seconds",
    "message": "The SDK doesn't recognize the PaymentIntent action type.",
    "declineCode": null,
    "type": null,
    "stripeErrorCode": null
}
```
Error on **Android**:
```json
{
    "stripeErrorCode": null,
    "declineCode": null,
    "localizedMessage": "The payment has been canceled",
    "message": "The payment has been canceled",
    "type": null,
    "code": "Canceled"
}
```

**Expected behavior**
Be able to perform 3D Secure authentication on a PaymentIntent with status RequiresAction

**Smartphone (please complete the following information):**
 - Devices: iPhone X, Samsung Galaxy S9+

**Additional context**

**Comment by lucasroca** [comment]
Hi @charliecruzan-stripe , I'm no longer working on that project so I can't tell whether it works or not

**Comment by charliecruzan-stripe** [comment]
Okay, going to close this for now then. If someone runs into this on a recent version, let me know what version and how to repro and ill reopen 😃
