### ISSUE TITLE
Crash android when initPaymentSheet is initialized

### ISSUE THREAD

**Issue by joaochiquitin** [stripe/stripe-react-native#603]
**Describe the bug**
every time I start a payment intent for the first time, the app crashes, but the second time it doesn't crash, I don't know what it is, I've tried using timeout and stuff.

**Expected behavior**
when the app starts for the first time does not crash, and need to start the app again.

Code:

async function initialisePaymentSheet() {
    setLoading(true);

    try {
      console.log(paymentIntent, ephemeralKey, customer)

      await initPaymentSheet({
        customerId: customer,
        customerEphemeralKeySecret: ephemeralKey,
        paymentIntentClientSecret: paymentIntent,
        merchantDisplayName: "Word EIRELI.",
        merchantCountryCode: "brl",
        customFlow: true,
      }).then(({ error, paymentOption }) => {
        console.log(error, paymentOption);

        if (!error) {
          setPaymentSheetEnabled(true);
        } else {
          console.log(error.message);
        }

        if (paymentOption) {
          setPaymentMethod(paymentOption);
        }

      }).catch((error) => console.log(error));

    } catch (error) {
      console.log("error", error);
    } finally {
      setLoading(false);
    }
  };

useEffect(() => {
      initialisePaymentSheet();
}, []);

**Comment by g-hamilton** [comment]
Same here. I'm getting the same behaviour, and in addition, on the second try when `initPaymentSheet()` completes and I subsequently call `presentPaymentSheet()`, I get an infinite loading state on the sheet. It just shows a loading spinner with no error while the promise never resolves. This is only on Android for me - it works fine on iOS.

I'm in an` "expo": "~41.0.1"` project using `"@stripe/stripe-react-native": "0.1.1"`

**Comment by joaochiquitin** [comment]
i'm using expo too, but it is SDK 42. Yeah, here onlycrash in Android, but IOS works fine.

**Comment by SrBrahma** [comment]
Any updates?

**Comment by ReisMari** [comment]
> > in my case i just removed StripeProvider in App.tsx / js and it worked again, it was starting StripeProvider and initStripe together so it crashed.
> 
> How do you give the publishableKey to Stripe, though? Even if I use initStripe instead of the provider, the app still crashes.

Hi! Did you find the answer?

**Comment by joaochiquitin** [comment]
> 

`
import React, { useEffect, useState } from 'react';

import { ActivityIndicator, ScrollView, StyleSheet, Text } from 'react-native';

import { initStripe } from '@stripe/stripe-react-native';

interface Props {
  paymentMethod?: string;
  onInit?(): void;
}

const PaymentScreen: React.FC<Props> = ({
  paymentMethod,
  children,
  onInit,
}) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function initialize() {
      const publishableKey = 'pk_test_KEY.....';

      await initStripe({
        publishableKey,
        merchantIdentifier: 'merchant.com.stripe.react.native',
        urlScheme:
          paymentMethod === 'wechat_pay' ? undefined : 'stripe-example',
        setUrlSchemeOnAndroid: true,
      });
      setLoading(false);
      onInit?.();
    }

    initialize();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return loading ? (
    <ActivityIndicator size="large" style={StyleSheet.absoluteFill} />
  ) : (
    <ScrollView
      accessibilityLabel="payment-screen"
      style={styles.container}
      keyboardShouldPersistTaps="always"
    >
      {children}
      {/* eslint-disable-next-line react-native/no-inline-styles */}
      <Text style={{ opacity: 0 }}>appium fix</Text>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,

    paddingTop: 20,
    paddingHorizontal: 16,
  },
});

export default PaymentScreen;
`

later i wrap in

`
<PaymentScreen paymentMethod="Cart" onInit={initialisePaymentSheet}>
             <ButtonPay
                  variant="primary"
                  loading={loading}
                  title={
                    paymentMethod ? (
                      <View style={{ flexDirection: "row", alignItems: "center" }}>
                        <Image
                          source={{
                            uri: `data:image/png;base64,${paymentMethod.image}`,
                          }}
                          style={{ width: 26, height: 20 }}
                        />
                        <Text
                          style={{
                            color: "#000",
                            fontSize: 16,
                            fontWeight: "600",
                            marginLeft: 12,
                          }}
                        >
                          {paymentMethod.label}
                        </Text>
                      </View>
                    ) : (
                      "Choose a card"
                    )
                  }
                  disabled={!paymentSheetEnabled}
                  onPress={choosePaymentOption}
                />
              </PaymentScreen>
`

**Comment by jordzawada** [comment]
I tried moving the stripe provider to a higher level component, but my initPaymentSheet is still crashing on the first call. After re-opening the app it seems to work fine. What's interesting is I cannot console log any information before initPaymentSheet . Ex;

const initializePaymentSheet = async () => {
   **console.log('going to initPaymentSheet');**
   const { error } = await initPaymentSheet({
keys
ids
blah blah blah
})
}

the console log is never hit unless I block out initPaymentSheet

**Comment by jordzawada** [comment]
I tried moving the stripe provider to a higher level component, but my initPaymentSheet is still crashing on the first call. After re-opening the app it seems to work fine. What's interesting is I cannot console log any information before initPaymentSheet . Ex;

const initializePaymentSheet = async () => {
console.log('going to initPaymentSheet');
const { error } = await initPaymentSheet({
keys
ids
blah blah blah
})
}

the console log is never hit unless I block out initPaymentSheet

"@stripe/stripe-react-native": "0.2.2",
"expo": "^43.0.0",

**Comment by SrBrahma** [comment]
It's still happening to me. I fear this will happen on Prod.

**Comment by jordzawada** [comment]
> It's still happening to me. I fear this will happen on Prod.

It has happened on a prod app built with eas-build for me.

**Comment by SamuelNavarro** [comment]
Same behaviour that @jordzawada Any updates?

**Comment by DariusPirvulescu** [comment]
I actually can see the console.logs added before `initPaymentSheet`, but it will still crash the app.
stripe-react-native was installed using expo install and I'm using `initStripe` function to initialize he app.
```
"@stripe/stripe-react-native": "0.1.4"
```
We'll have to go live with our app soon, are there any solutions for this?

**Comment by charliecruzan-stripe** [comment]
This was fixed in https://github.com/stripe/stripe-react-native/pull/788, sorry for the late notice! Fix is available in `0.2.4` and above

**Comment by charliecruzan-stripe** [comment]
If one doesn't already exist, you can write an EAS Config Plugin to update the `targetSdkVersion`- https://docs.expo.dev/guides/config-plugins/#default-mods

**Comment by SrBrahma** [comment]
> If one doesn't already exist, you can write an EAS Config Plugin to update the `targetSdkVersion`- https://docs.expo.dev/guides/config-plugins/#default-mods

Unfortunately I still have no experience with EAS plugins and I can't find a way to get this done :/ Looks like it's said in https://docs.expo.dev/guides/config-plugins/#android-gradle-files, but can't progress further.

**Comment by jordzawada** [comment]
I have tried 0.2.4, 0.3.0, and 0.4.0, and I am still getting NullPointerException crash on first try. 

I DID upgrade expo to SDK 44 tho. I couldn't EAS build android in SDK 43 because it required api level 31. I don't know if stripe had this requirement in 0.3.0 or if it was another package.

**Comment by charliecruzan-stripe** [comment]
How have you tried 0.2.4 and above if you can't build due to the required API level?

**Comment by jordzawada** [comment]
> How have you tried 0.2.4 and above if you can't build due to the required API level?

"expo start" builds fine. I cannot EAS build to make apk stuff.

**Comment by charliecruzan-stripe** [comment]
`expo start` is going to use Expo's bundled-in version of `@stripe/stripe-react-native`- https://github.com/expo/expo/blob/sdk-44/packages/expo/bundledNativeModules.json - which is 0.2.3, which would explain why you're still getting the crash there

**Comment by jordzawada** [comment]
I do get an error saying:

"Opening developer tools in the browser...
Some dependencies are incompatible with the installed expo package version:
 - @stripe/stripe-react-native - expected version: 0.2.3 - actual version installed: 0.4.0
Your project may not work correctly until you install the correct versions of the packages."

When I run expo start.

**Comment by SrBrahma** [comment]
@jordzawada This is because Expo checks the installed package versions with the linked .json and warns if they differ.

Anyway you won't get it working. The Stripe native code will only get installed after a new EAS build, and you won't be able to do it due to Android SDK incompatibility.

**Comment by jordzawada** [comment]
@SrBrahma Does that mean there is no way to upgrade react native/expo/eas build in a way that builds onto API 31?

**Comment by SrBrahma** [comment]
Good to know! Just being able to use the latest stripe is already good enough for me. Maybe you should also change `targetSdkVersion`, as mentioned [here](https://github.com/stripe/stripe-react-native/issues/812#issuecomment-1041538608)?

**Comment by DariusPirvulescu** [comment]
> The only case where you're limited is if you have an Expo managed workflow project where you do not have access to your native projects (you only have access to the Javascript), otherwise you can edit your Android SDK version.
> 
> If you _do_ have an Expo managed workflow project, then to change your Android SDK version (or anything else in your native projects) you need to use a Config Plugin, which Expo provides documentation for here: https://docs.expo.dev/guides/config-plugins/

Thanks for pointing it out. I tried version 0.2.4, but still crashes the app as you said [here](https://github.com/stripe/stripe-react-native/issues/603#issuecomment-1072393143). 
I still don't understand how to change the Android SDK version. The project is Expo managed workflows and I never worked with config plugins in Expo or bare workflow. 
Is it from the [android gradle files](https://docs.expo.dev/guides/config-plugins/#android-gradle-files)? Do you have any code which I can use to do this?

**Comment by SrBrahma** [comment]
@DariusPirvulescu, if  you use basic Expo (no EAS), you can't make this Android SDK version change. Config plugins are only for EAS. Maybe you can try to use Payment Form to avoid this error, or use EAS, or await some good months until Expo changes its Android SDK from 30 to 31 😬

**Comment by SrBrahma** [comment]
Here is the EAS plugin to get it working:

https://forums.expo.dev/t/change-targetsdkversion-for-stripe-react-native-0-2-4/62534/4
