### ISSUE TITLE
google pay is not available on this device (stripe react native).

### ISSUE THREAD

**Issue by Mukthaharshaik** [stripe/stripe-react-native#607]
**Describe the bug**
Whenever i call initGooglePay, It is saying - google play is not available on this device. I have installed googlepay in my mobile. I enabled gpay in manifestfile.xml. 

**To Reproduce**

import {useStripe,  initGooglePay,
  presentGooglePay,
  createGooglePayPaymentMethod, } from '@stripe/stripe-react-native';

===========================
const error = await initGooglePay({
      testEnv: true,
      merchantName: 'com.stripe_app',
      countryCode: 'IN',
      billingAddressConfig: {
        format: 'FULL',
        isPhoneNumberRequired: true,
        isRequired: false,
      },
      existingPaymentMethodRequired: false,
      isEmailRequired: true,
    });

**Smartphone (please complete the following information):**
 - Device: samung m30s
 - OS: [android 11

**Comment by anija** [comment]
Using latest version of the library, initGooglePay works fine for me on phisical device: Huaweii p30, Android 10. Are you passing `testEnv: true` as option?

**Comment by charliecruzan-stripe** [comment]
@Mukthaharshaik are you still seeing this issue?

**Comment by sailes-coding** [comment]
any idea on how can i resolve this problem on Expo sdk 44??. i already create the EAS dev-client too

**Comment by charliecruzan-stripe** [comment]
If you're using the dev client, then you can pull in `@stripe/stripe-react-native` v0.3.0 and check the `isGooglePaySupported` method

**Comment by sailes-shakya** [comment]
After i pull latest version . min sdk and complilesdk 31 doesnt match with expo sdk 44 .any idea to solve this problem. Thank you in advance

**Comment by charliecruzan-stripe** [comment]
Please refer to this issue- https://github.com/stripe/stripe-react-native/issues/812

You'll either have to override those values in `build.gradle`, or wait until Expo updates

**Comment by sailes-shakya** [comment]
Oo ok thank you for your reply

**Comment by zoalna** [comment]
i have faced same issues but not getting any proper solution

**Comment by nadeem36212** [comment]
I was also facing this issue, after spending couple of hours, I am able to find the solution
https://developers.google.com/pay/api/android/guides/setup
