### ISSUE TITLE
Support payment_method_options in confirmPayment

### ISSUE THREAD

**Issue by ssharkey-stripe** [stripe/stripe-react-native#609]
**Is your feature request related to a problem? Please describe.**
[confirmPayment](https://stripe.dev/stripe-react-native/api-reference/modules.html#confirmPayment) has an `options` parameter but there is currently nothing in it. Would it be possible to support the same `payment_method_options` as in [PaymentIntent Confirm](https://stripe.com/docs/api/payment_intents/confirm) so we can pass this data?

**Comment by arekkubaczkowski** [comment]
@ssharkey-stripe what is your use case for this?  We fulfill paymentMethodOptions under the hood based on chosen payment method. What kind of data would you like to handover? If it needs to be a custom parameters then we can apply it into the `additionalAPIParameters` but it requires changes in the library code.

**Comment by ssharkey-stripe** [comment]
@arekkubaczkowski sorry I missed your response here! the use case is card brand choice, i.e. passing `network` into card payment method options https://stripe.com/docs/api/payment_intents/confirm#confirm_payment_intent-payment_method_options-card-network. So if I understand correctly, it's still possible for users to pass `network` to payment intents on the React SDK by using `stripe.paymentIntents.confirm` directly? I'm a little unfamiliar with how this library works so i'm trying to understand the limitations

**Comment by charliecruzan-stripe** [comment]
Closing for now since this isn't going to be prioritized and the workaround (setting these on the server with the Node SDK linked above) is straightforward. However, if that doesn't fit your use case please let me know and we can reopen!
