### ISSUE TITLE
STPPaymentHandler does not support concurrent calls to its API.

### ISSUE THREAD

**Issue by kekami** [stripe/stripe-react-native#610]
**Describe the bug**
We have a user that is unable to complete a payment. After completing the 3d secure flow the user receives the following error message:
`The current action is not yet completed. STPPaymentHandler does not support concurrent calls to its API.`

Could not find any relevant pointers on what causes this error. Would appreciate some suggestions.

Thanks in advance.

**Smartphone:**
 - Device: iPhone 12 Prop
 - OS: iOS14.8
 
 Lib version: "@stripe/stripe-react-native": "^0.1.5"

**Comment by Roundups** [comment]
We are receiving this error on an expo project with stripe-ract-native 0.6.1, expo SDK 45.

The above comment unfortunately did not resolve our issue.

**Comment by charliecruzan-stripe** [comment]
We have docs for the URL callback handling that @Sascha1251 mentions above: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-set-up-return-url :)
