### ISSUE TITLE
Edit Payment Method using CardField

### ISSUE THREAD

**Issue by aikhan** [stripe/stripe-react-native#615]
I am able to create a new payment method using CardField and setup intent. Is there a way where I can edit card info (expiry date) attached to the payment method using the CardField. Currently all info is being captured by CardField including the number and CVC, is a way to limit it show just expiry date or CVC?

**Comment by arekkubaczkowski** [comment]
@aikhan unfortunately there is no way to achieve this. CardField is a complex component to being used within all SDK payment methods which meets all PCI compliance requirements and cannot be customized in such way.

**Comment by arekkubaczkowski** [comment]
but if it's help you, there is an option to confirm the payment using paymentMethodId and cvc number:

example:
```
const { error, paymentIntent } = await confirmPayment(clientSecret, {
      type: 'Card',
      cvc: '123',
      paymentMethodId: 'pm_***'
    });
```
