### ISSUE TITLE
`presentPaymentSheet` crashes the app in android

### ISSUE THREAD

**Issue by obayit** [stripe/stripe-react-native#620]
**Describe the bug**
The app crashes after calling `presentPaymentSheet`.

**To Reproduce**
I followed the example in the integration guide here.
My checkout page:
```
import React, { useState, useEffect } from "react";
import { useStripe } from '@stripe/stripe-react-native';
import useAPIError from '../../common/hooks/useAPIError';
import stripeSheet from '../../common/api/stripe';
import { Button, VStack, Text } from 'native-base';

export default function CheckoutScreen() {
  const { initPaymentSheet, presentPaymentSheet } = useStripe();
  const [loading, setLoading] = useState(false);
  const [apiIntent, setApiIntent] = useState('');
  const [apiCustomer, setApiCustomer] = useState('');
  const [apiEphemeralKey, setApiEphemeralKey] = useState('');
  // const [clientSecret, setClientSecret] = useState();
  const { addError } = useAPIError();

  const fetchPaymentSheetParams = async () => {
      try{
        const response = await stripeSheet(addError);
        const { paymentIntent, ephemeralKey, customer }  = response.result;
        console.log(paymentIntent);
        console.log(ephemeralKey);
        console.log(customer);
        setApiIntent(paymentIntent);
        setApiEphemeralKey(ephemeralKey);
        setApiCustomer(customer);
        return {
          paymentIntent,
          ephemeralKey,
          customer,
        };

      }catch(e){
          // TODO: handle error
          return {
            paymentIntent: null,
            ephemeralKey: null,
            customer: null,
          }
      }
  };

  const initializePaymentSheet = async () => {
    const {
      paymentIntent,
      ephemeralKey,
      customer,
    } = await fetchPaymentSheetParams();

    const { error } = await initPaymentSheet({
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,

    });
    if (!error) {
      setLoading(true);
    }else{
    }
  };

  const openPaymentSheet = async () => {
    const { error } = await presentPaymentSheet(); // app crashes here
    if (error) {
      addError(`Error code: ${error.code}`, error.message);
    } else {
      addError('Success', 'Your order is confirmed!');
    }
  };

  useEffect(() => {
    initializePaymentSheet();
  }, []);

  return (
    <VStack>

      <Button colorScheme="primary" onPress={initializePaymentSheet}>Retry</Button>
      <Text>Disabled is {(!loading) + ''}</Text>
      <Text>intent is {apiIntent}</Text>
      <Text>customer is {apiCustomer}</Text>
      <Text>ephemeralKey is {apiEphemeralKey}</Text>
      <Button
        colorScheme="primary"
        disabled={!loading}
        onPress={openPaymentSheet}
      >Checkout</Button>

    </VStack>
  );
}

```

**Screenshots**

![Screenshot_20211004-105834](https://user-images.githubusercontent.com/20386024/135823643-7d9e52cd-0007-4348-84f4-35163243f30e.jpg)

**Smartphone (please complete the following information):**
 - Device: Android Huawei GR3 2017
 - OS: Android 8.0

**Additional context**
Developing app with `expo` and using `nativebase` for UI (I tried pure react native UI but the issue is still there).

**Comment by arekkubaczkowski** [comment]
Expo does support the older version of this library (0.1.4), this means that there are differences in initializing the PaymentSheet. Please follow our example which points to this specific version: https://github.com/stripe/stripe-react-native/blob/v0.1.4/example/src/screens/PaymentsUICompleteScreen.tsx

**Comment by obayit** [comment]
Thanks, I solved the issue by downgrading the package to `0.1.4` with:
```
yarn upgrade @stripe/stripe-react-native@0.1.4
```
Then adding these missing args to `initPaymentSheet`:
```
      customFlow: false,
      merchantDisplayName: 'Example Inc.',
      style: 'alwaysDark',
```

**Comment by arekkubaczkowski** [comment]
@obayit you don't need to manually specify stripe-react-native version in your project, as docs says you just need to run 
`expo install @stripe/stripe-react-native`

https://github.com/stripe/stripe-react-native#expo

**Comment by arekkubaczkowski** [comment]
@obayit there is one more difference https://github.com/stripe/stripe-react-native/blob/v0.1.4/example/src/screens/PaymentsUICompleteScreen.tsx#L36
you need to pass clientSecret also to the `presentPaymentSheet` method

**Comment by obayit** [comment]
@arekkubaczkowski thanks again

**Comment by discodane** [comment]
@obayit Downgrading was the only thing that worked for me. I know @arekkubaczkowski said you don't need to manually specify, but unless I downgraded to specifically that version, it would crash with no logs.

**Comment by DariusPirvulescu** [comment]
I also had to downgrade*, otherwise, it will throw an error something along the line "presentPaymentSheet expects 3 arguments but got only 2".
Also, I replaced the `StripeProvider` with`initStripe` and the app doesn't crash anymore (Android)

*as it says in this tutorial: 
https://youtu.be/qiEwO_UrOro?t=576

**Comment by JaLe29** [comment]
> customFlow: false,
>       merchantDisplayName: 'Example Inc.',
>       style: 'alwaysDark',

Same! Fixed.
