### ISSUE TITLE
confirmPayment doesn't work when subscribing with 3D Secure cards

### ISSUE THREAD

**Issue by JoeKlimcak** [stripe/stripe-react-native#623]
Similar issue seems to be #508, although a more specific subscription workflow:
1. My app already has `paymentMethodId`s cached
2. User then selects payment method, and subscribes to a product
3. Following [this flow](https://www.reddit.com/r/stripe/comments/oaedzb/are_there_any_resources_on_handling_subscriptions/), I pull the `PaymentIntent` of the `latest_invoice` from the received subscription object, and I pass the `client_secret` back to client
4. Finally, I pass that `client_secret` to `confirmPayment`

This was the flow I was using before migrating to stripe-react-native (using Tipsi). With stripe-react-native, this seems to work fine for cards with no authentication required (e.g. 4242 4242 4242 4242). However, if we try with a card that requires authentication (e.g. 4000 0027 6000 3184), it breaks at `confirmPayment` with the error:
```
{"error": {"code": "Failed", "declineCode": null, "localizedMessage": "Card details not complete", "message": "Card details not complete", "stripeErrorCode": null, "type": null}}
```
The library and documentation seems to be great and updated for one-off-payments, but I feel like the subscription flow is not yet robust. Can you confirm whether the above is still the recommended approach? If so, can you advise on the error? If not, can you please clarify what's the best approach here, especially for subscribing with cards that require further authentication?

Many thanks,

**Comment by arekkubaczkowski** [comment]
@JoeKlimcak can you please provide  the code snippet of your payment screen so I can have a look a bit closer

**Comment by JoeKlimcak** [comment]
Sure.

First let me clarify that I'm not using stripe-react-native's `PaymentScreen` for subscriptions, only for one-off payments. It's exactly what I couldn't find on your website or in the examples folder on GitHub. If you do have an example/doc on how to use it for subscriptions - that would be fantastic.

For now, I'm doing it as described above. So let's say we receive a response object from the server (which calls `stripe.subscriptions.create()`), then I do:

```
...
          const paymentIntent = subscription.latest_invoice.payment_intent;
          if (paymentIntent.status === 'requires_action') {
            const clientSecret = paymentIntent.client_secret;
            initStripe({
              PUBLISHABLE_KEY,
            })
              .then(() => {
                confirmPayment(clientSecret, {
                  paymentMethodId: paymentIntent.paymentMethod,
                  type: 'Card',
                })
                ...
              })
...
```

Thanks @arekkubaczkowski for looking into this -

**Comment by arekkubaczkowski** [comment]
@JoeKlimcak  Thanks for providing  more details, can you also clarify if it's occur on both platforms (iOS & Android)?

**Comment by JoeKlimcak** [comment]
Only testing on iOS atm

**Comment by arekkubaczkowski** [comment]
I wasn't able to reproduce it on my end (example app).
The thing is that it doesn't matter if it's subscription or not, you just should be able to confirm the payment using paymentMethodId.
In order to investigate this can you please tell me which version of library you are using (and Expo if applicable)?

**Comment by JoeKlimcak** [comment]
So the above code should work? That's the recommended flow for subscriptions that need further authentication?

Not using expo. Versions:
```
    "@stripe/stripe-react-native": "^0.2.2",
    "react": "17.0.1",
    "react-native": "0.64.2",
```

**Comment by arekkubaczkowski** [comment]
Can you make sure that you have correct paymentMethodId provided into the method?
```
.then(() => {
                confirmPayment(clientSecret, {
                  paymentMethodId: paymentIntent.paymentMethod, <--- what is the value?
                  type: 'Card',
                })
                ...
              })
        ```

**Comment by arekkubaczkowski** [comment]
I believe that you provide the whole paymentMethod object instead of ID

**Comment by JoeKlimcak** [comment]
Partially right - it should be `paymentIntent.payment_method`, not `.paymentMethod`. Thanks @arekkubaczkowski, sorry for the bother!
