### ISSUE TITLE
confirmApplePayPayment crash

### ISSUE THREAD

**Issue by developer-at-openbar** [stripe/stripe-react-native#628]
**Describe the bug**
I'm trying with test stripe key to test apple pay and the way I implemented was
1. presentApplePay and get paymentMethod id
2. use PaymentMethod id to get clientSecret
3. When the intent is made, call confirmApplePayPayment with clientSecret I got
4. Crashes without any errors

**To Reproduce**
1. presentApplePay and get paymentMethod id
2. use PaymentMethod id to get clientSecret
3. When the intent is made, call confirmApplePayPayment with clientSecret I got
4. Crashes without any errors - even tried with random string and crashes

**Expected behavior**
Close Apple pay

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arekkubaczkowski** [comment]
@developer-at-openbar which version of library are you using? Can you also share a code snippet of your apple pay payment process?

**Comment by developer-at-openbar** [comment]
This is screen recording of its behaviour. Crashes right after confirmApplePayPayment is call

https://user-images.githubusercontent.com/82211803/136413835-9c8c76e1-f0a9-4f09-aee6-08076a4059f5.mov

ed

**Comment by developer-at-openbar** [comment]
@arekkubaczkowski Yes the client secret is the `pi_3JhyjHBVN56aHDIQ1DZig5bd_secret_59qiWuVptdL5jGSmSexcYpzfX`
But I'm getting a crash. I've migrated from expo-payments-stripe by uninstalling expo-payments-stripe and used this library by installing with react native. Is there any extra steps that I have to do to make it work? Apple pay shows up fine with `presentApplePay` but confirmApplePayPayment crashes all the time and there is not other function to close the apple pay.

**Comment by arekkubaczkowski** [comment]
if you are using Expo please follow expo installation guide: https://github.com/stripe/stripe-react-native#expo

**Comment by arekkubaczkowski** [comment]
ok so you are using bare workflow right? so it's shouldn't be the case
