### ISSUE TITLE
com.android.tools.lint.client.api.Vendor

### ISSUE THREAD

**Issue by Tanzeel-ur-rehman-git** [stripe/stripe-react-native#636]
**Describe the bug**
in Android, I am facing that error when I try to build an APk release version . but it does not have any impact on the functionality and build also successfully 

Error Is: 
Caused by: java.lang.ClassNotFoundException: com.android.tools.lint.client.api.Vendor

**To Reproduce**
just install and try to make build

**Expected behavior**

**Screenshots**
<img width="1311" alt="Screenshot 2021-10-08 at 3 58 31 PM" src="https://user-images.githubusercontent.com/81971499/136545227-2f16b5ea-525b-425c-8663-9224d112e6a4.png">
<img width="1359" alt="Screenshot 2021-10-08 at 3 58 58 PM" src="https://user-images.githubusercontent.com/81971499/136545278-758e1697-709d-4b68-a7f0-2212a4c79820.png">

<img width="927" alt="Screenshot 2021-10-08 at 4 01 21 PM" src="https://user-images.githubusercontent.com/81971499/136545548-e0b1827f-3a83-4445-858a-aa909058843a.png">
<img width="692" alt="Screenshot 2021-10-08 at 4 00 31 PM" src="https://user-images.githubusercontent.com/81971499/136545452-9de77852-dee2-4e04-be3c-7bf2c94055b6.png">

**Comment by MontreaI** [comment]
Sorry to bother, but any resolutions on this?

**Comment by FadiAboMsalam** [comment]
Am facing same issue any solution for this

**Comment by FadiAboMsalam** [comment]
@arekkubaczkowski  my build version is 30.0.2 and am still facing same issue downgrading to 0.2.0 same issue as well 
I have kotlin 1.5.20

any suggestion

**Comment by angelorobo** [comment]
Please check this solution

https://stackoverflow.com/a/69281505/772481

```
lintOptions { 

    checkReleaseBuilds false

}
```

**Comment by charliecruzan-stripe** [comment]
This doesn't look like it's an issue with `stripe-react-native`, so I'm going to close this for now. If this error only occurs in your project after installing `@stripe/stripe-react-native`, please let me know

**Comment by goubar** [comment]
hi @charliecruzan-stripe , yes , I can confirm this, I'm getting this issue also after installing `@stripe/stripe-react-native`. any help please

**Comment by Arthurlss** [comment]
any solution to this?

**Comment by charliecruzan-stripe** [comment]
Please share a github repo that reproduces the issue and I'll be happy to look into it!

**Comment by Gmlogy** [comment]
> Please check this solution
> 
> https://stackoverflow.com/a/69281505/772481
> 
> ```
> lintOptions { 
> 
>     checkReleaseBuilds false
> 
> }
> ```

i think this is the solution for release build, thanks
