### ISSUE TITLE
Card `4000 0000 0000 3063` does not trigger 3D Secure/SCA modal

### ISSUE THREAD

**Issue by r1jsheth** [stripe/stripe-react-native#640]
**Describe the bug**
Card `4000 0000 0000 3063` does not trigger 3D Secure/SCA modal
I am using Subscriptions with free trial. On client side I am using `SetupIntent` after successful creation of subscription.
Similar to: https://github.com/stripe-archive/react-stripe-elements/issues/402

**To Reproduce**
1. Use card `4000 0000 0000 3063`
2. Create subscription with `trial period`.
3. Use `client_secret` retrieved from previous step and use it to create a SetupIntent.

**Expected behavior**
This should create a webview, but it is not creating right now.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - iOS: 15

**Smartphone (please complete the following information):**
 - iPhone 11
 - OS: 15

**Additional context**
Similar to: https://github.com/stripe-archive/react-stripe-elements/issues/402. Not sure why is that closed.

**Comment by charliecruzan-stripe** [comment]
Hi @r1jsheth, sorry for the late response here. I'm not able to reproduce this on the most recent version of `@stripe/stripe-react-native`. Are you still running into this problem?

**Comment by r1jsheth** [comment]
@charliecruzan-stripe yes, not reproducible in the latest version.
Please feel free to close this.
Thanks!
