### ISSUE TITLE
Question about Apple Pay ShippingAddressFields type

### ISSUE THREAD

**Issue by fbredius** [stripe/stripe-react-native#641]
Shouldn't the type of `requiredShippingAddressFields?` be `AddressFields` (defined on line 11)? Since currently the type is `ContactFieldsType`, which to me doesn't really makes sense.  

https://github.com/stripe/stripe-react-native/blob/04abc26fcbd43da0c0132d5fbde17567e0bd0117/src/types/ApplePay.ts#L65

**Comment by charliecruzan-stripe** [comment]
The `ContactFieldsType` is correct- see Apple's docs: https://developer.apple.com/documentation/passkit/pkcontactfield

**Comment by huwmartin** [comment]
Is there any way to specify that only postal code should be required similar to `billingAddressConfig.format: 'MIN'` for Google Pay?
