### ISSUE TITLE
[RN 0.66] NativeEventEmitter is called with a non-null argument warning Android

### ISSUE THREAD

**Issue by carl0shd** [stripe/stripe-react-native#644]
**Describe the bug**
React Native 0.66 is issuing a warning in the useApplePay.tsx file when the apps start.

**To Reproduce**
1. Update to React Native 0.66.
2. Open the App on Android.
3. Expect to see the warning.

**Expected behavior**

**Screenshots**
<img width="428" alt="Screen Shot 2021-10-12 at 6 57 17 PM" src="https://user-images.githubusercontent.com/8359234/137044448-be540c7f-5ffa-4a73-b69b-440ad3d59460.png">

**Smartphone (please complete the following information):**
 - Device: Pixel 5 Simulator
 - OS: Android
 - Version 12

**Additional context**

**Comment by developerhowdy** [comment]
Been getting this for a while now, getting annoying

**Comment by charliecruzan-stripe** [comment]
Updated for RN 66 [here](https://github.com/stripe/stripe-react-native/commit/7cfcdc00bdaac7deb5836baba6ce8542bce509d7) so this should be fixed in the next release
