### ISSUE TITLE
payout with stripe in react native

### ISSUE THREAD

**Issue by arunabhverma** [stripe/stripe-react-native#647]
Hi, I am using stripe for react native, and I used react native stripe for accept payment but now I need stripe for payout, So how can I implement stripe for payout, there is any prebuilt ui for this, like accept payment,

**Comment by arunabhverma** [comment]
Hi, anyone available for the query

**Comment by arunabhverma** [comment]
Hi, any one available for help? for payout using stripe react native

**Comment by charliecruzan-stripe** [comment]
Hi! Sorry about the late response- any charge that you create for a connected account accumulates in the connected account’s [Stripe balance](https://stripe.com/docs/connect/account-balances) and is paid out on a daily rolling basis. Let me know if there's something else specifically that you're looking for
