### ISSUE TITLE
Confirm payment server-side with Payment Sheet (NoWebhookPaymentScreen example)

### ISSUE THREAD

**Issue by rsanchez** [stripe/stripe-react-native#649]
**Is your feature request related to a problem? Please describe.**
My app cannot confirm payment client side because we need to confirm & reserve inventory in our back-end immediately prior to taking payment. The typical asynchronous, webhook-based flow does not work for this scenario, since a user can complete a purchase without us having an opportunity to confirm inventory.

**Describe the solution you'd like**
I would like to be able to confirm payment server-side while using Payment Sheet. According to documentation, I can only confirm payment client side when using the payment sheet. Essentially, I'd like the [NoWebhookPaymentScreen.tsx](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/NoWebhookPaymentScreen.tsx) example, but using Payment Sheet instead of Card Element.

**Describe alternatives you've considered**
Just using Card Element and the NoWebhookPaymentScreen example, but then we'd lose out on some of the great features of the sheet (save card for later, Apple pay integration, etc.).

**Additional context**
Perhaps this is already possible but not documented?

**Comment by kutaisan** [comment]
I need this document too. We can't just use our front-end to handle this payment sheet. Is there any update on it?

**Comment by charliecruzan-stripe** [comment]
Added in https://github.com/stripe/stripe-react-native/pull/1424
