### ISSUE TITLE
React Native Android App - Could not create task ':stripe_stripe-react-native:compileDebugAndroidTestKotlin'.

### ISSUE THREAD

**Issue by MedFount** [stripe/stripe-react-native#654]
**Describe the bug**
After installing "npm install @stripe/stripe-react-native" on my React Native Project, I cannot build. It give following error

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > A problem occurred configuring project ':stripe_stripe-react-native'.
      > Failed to notify project evaluation listener.
         > Could not create task ':stripe_stripe-react-native:compileDebugAndroidTestKotlin'.
            > KOTLIN_1_4
         > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.

Here is my gradle file details

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
        kotlinVersion = "1.3.72"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.lint:lint:26.3.2'
        classpath("com.android.tools.build:gradle:4.0.1")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath 'com.google.gms:google-services:4.3.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

And my Gradle Version details. 
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Windows 10 10.0 amd64

I will really appreciate, if some one can point me in a direction to resolve this build issue. 

Thanks

**Comment by tarouboy** [comment]
same: https://github.com/stripe/stripe-react-native/issues/385
Update Kotlin version to 1.5.20+

**Comment by MedFount** [comment]
Thanks for helping me out. I updated Kotlin version to 1.5.21. Now I'm getting following error during build. Really appreciate the help.

**Gradle -v**
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Windows 10 10.0 amd64

**build.gradle**

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
        kotlinVersion = "1.5.21"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.lint:lint:26.3.2'
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath 'com.google.gms:google-services:4.3.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**BUILD ERROR -**

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':stripe_stripe-react-native:bundleLibCompileToJarRelease'.
> Could not create task ':stripe_stripe-react-native:compileReleaseKotlin'.
   > Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultLanguageSettingsBuilderKt

**Comment by charliecruzan-stripe** [comment]
What version of `@stripe/stripe-react-native` are you using @MedFount ?

**Comment by charliecruzan-stripe** [comment]
Closing this as the fix for the original issue is to upgrade your kotlin version
