### ISSUE TITLE
Apple Pay Error code undefined

### ISSUE THREAD

**Issue by NoisyBoyII** [stripe/stripe-react-native#659]
when i am sending client secret in confirmApplePayPayment method i am getting this error
{ code: 'Failed',
  message: 'Payment not completed',
  localizedMessage: undefined,
  declineCode: undefined,
  stripeErrorCode: undefined,
  type: undefined }

when i try to call this method retrievePaymentIntent i am getting this 
{ stripeErrorCode: null,
  declineCode: null,
  localizedMessage: 'There was an unexpected error -- try again in a few seconds',
  message: 'There was an unexpected error -- try again in a few seconds',
  type: null,
  code: 'Unknown' }

Stripe version 0.2.2
react version 16.13.1
mac os version 11.6 big sur
xcode version 12.5.1

**Comment by khenriksson** [comment]
Did you find any fix for this?

**Comment by bll-prataps** [comment]
@khenriksson  Are you using stripe connect ?
You will face this error when your backend is setup for stripe connect and you are sending normal stripe payment.
