### ISSUE TITLE
[Types] TypeScript error rendering StripeProvider

### ISSUE THREAD

**Issue by hagmic** [stripe/stripe-react-native#666]
**Describe the bug**
Rendering the `StripeProvider` in my application results in the following TypeScript error:

```
TS2786: 'StripeProvider' cannot be used as a JSX component.   Its return type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactElement<any, string | JSXElementConstructor<any>>[]' is not a valid JSX element.     Type 'ReactElement<any, string | JSXElementConstructor<any>>[]' is missing the following properties from type 'ReactElement<any, any>': type, props, key
```

**To Reproduce**
1. Create new application.
2. Render the `StripeProvider` at the top of your app:
```
  import { StripeProvider } from '@stripe/stripe-react-native';

  function App() {
    return (
      <StripeProvider publishableKey='123'>
        {...}
      </StripeProvider>
   )
  }
```
3. See error.

**Expected behavior**
Ability to render `StripeProvider` without error in a TypeScript project.

**Additional context**
This error seems to have been introduced in version `0.2.3`. If I roll back to `0.2.2` the error disappears.

**Comment by acomley-stripe** [comment]
The fix has been merged and will be in the next release.

https://github.com/stripe/stripe-react-native/pull/658
