### ISSUE TITLE
createToken function results did't have the card id info

### ISSUE THREAD

**Issue by echolove38** [stripe/stripe-react-native#671]
I use cardfield to createToken, and the result is the following:
`{
    "token": {
        "bankAccount": null,
        "card": {
            "address": [
                null
            ],
            "brand": "Visa",
            "country": "US",
            "currency": null,
            "expMonth": 11,
            "expYear": 2022,
            "funding": "Credit",
            "last4": "4242",
            "name": null
        },
        "created": "1634898062000",
        "id": "tok_1JnKryGcYvQPn7TLRZJtk77X",
        "livemode": false,
        "type": "Card"
    }
}`

the card Object have no id info , so how can I get the card Id?

**Comment by echolove38** [comment]
Is there anybody have time to check this

**Comment by acomley-stripe** [comment]
Can you provide more detailed reproduction steps? Providing some screenshots and code snippets would help add context to the issue.

**Comment by echolove38** [comment]
> Can you provide more detailed reproduction steps? Providing some screenshots and code snippets would help add context to the issue.
![git1](https://user-images.githubusercontent.com/12425497/139979865-dd94ddfe-343b-466f-a5b2-b585c5527db7.png)

![git2](https://user-images.githubusercontent.com/12425497/139980267-3ed44aad-a80b-43a0-902b-752f6991eb07.png)
look at this. just a simple cardField and use createToken method

**Comment by echolove38** [comment]
Is there anybody have time to check this

**Comment by charliecruzan-stripe** [comment]
@echolove38 the best thing to do if you're looking for help is to provide a link to a Github repo that reproduces the same bug with _as little code as possible_

**Comment by echolove38** [comment]
> @echolove38 the best thing to do if you're looking for help is to provide a link to a Github repo that reproduces the same bug with _as little code as possible_

It's already so clear
