### ISSUE TITLE
TS error:  'StripeProvider' cannot be used as a JSX componen

### ISSUE THREAD

**Issue by anija** [stripe/stripe-react-native#678]
**Describe the bug**
Typescript error when using `<StripeProvider>` component
```
TS2786: 'StripeProvider' cannot be used as a JSX component.   Its return type 'ReactElement<any, string | ((props: any) => ReactElement<any, any> | null) | (new (props: any) => Component<any, any, any>)> | ReactElement<any, string | ... 1 more ... | (new (props: any) => Component<...>)>[]' is not a valid JSX element.     Type 'ReactElement<any, string | ((props: any) => ReactElement<any, any> | null) | (new (props: any) => Component<any, any, any>)>[]' is missing the following properties from type 'Element': type, props, key
```
**To Reproduce**
Add a basic `<StripeProvider  publishableKey={...} merchantIdentifier={...}>` component to App.

**Expected behavior**
No typescript errors.

**Additional context**
Library version: 0.2.3
This bug was not present on previous version 0.2.2

**Comment by Johnhollack** [comment]
> Hi! they said it has been fixed with this PR #658 you can change it yourself by following the PR then use patch-package. but you will also need to change the type of the StripeProvider too inside the `yourStripeLib/typescript/src/components/StripeProvider.d.ts`

Please what type should this be changed to?

**Comment by te-online** [comment]
Changing the return type to `React.ReactElement` seems to work for me

**Comment by dahlbyk** [comment]
Is there an ETA on a new release?

In the meantime, this is what I came up with to avoid patching `node_modules`:

```ts
import { StripeProvider as _StripeProvider } from '@stripe/stripe-react-native';
import type { Props as StripeProviderProps } from '@stripe/stripe-react-native/lib/typescript/src/components/StripeProvider';
const StripeProvider = _StripeProvider as React.FC<StripeProviderProps>;
```

**Comment by Great-hijack** [comment]
Looking forward to the new release.
