### ISSUE TITLE
Postal Code field is differently visible for the same countries on Android and iOS

### ISSUE THREAD

**Issue by AlexSirenko** [stripe/stripe-react-native#679]
**Describe the bug**
Postal Code field is differently visible for the same countries on Android and iOS

**To Reproduce**
Open CardForm on IOS and Android

**Expected behavior**
Postal Code should have the same behavior on Android and iOS

**Comment by charliecruzan-stripe** [comment]
duplicate of https://github.com/stripe/stripe-react-native/issues/752
