### ISSUE TITLE
Custom font family

### ISSUE THREAD

**Issue by dqii** [stripe/stripe-react-native#681]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support custom font families (e.g., those imported with [useFonts](https://docs.expo.dev/guides/using-custom-fonts/))

**Comment by dqii** [comment]
Adding context here for anyone else ---
https://github.com/stripe/stripe-react-native/pull/247
It seems like custom fonts are only supported as long as they're system fonts.

**Comment by edi** [comment]
I'm interested in this as well.

**Comment by binitgurzu** [comment]
Still looking for  solutions

**Comment by charliecruzan-stripe** [comment]
Reopening- is there desire for this in the components like CardField and CardForm? Or does the Payment Sheet integration suit everyone's needs here?

**Comment by dqii** [comment]
Would absolutely love for it to be in CardField and CardForm.

**Comment by charliecruzan-stripe** [comment]
@dqii can I ask why Payment Sheet doesn't work for your use case? It would help us in making improvements to Payment Sheet :)

**Comment by dqii** [comment]
I think purely cosmetic reasons. We wanted more flexibility with the design... we wanted payment method to be provided "inline" for example
@charliecruzan-stripe

**Comment by charliecruzan-stripe** [comment]
👍 fair enough, that makes sense

**Comment by charliecruzan-stripe** [comment]
closed in https://github.com/stripe/stripe-react-native/pull/1150

**Comment by dqii** [comment]
@charliecruzan-stripe sorry could this be reopened? I think @perqin's diff only added support for Android

**Comment by perqin** [comment]
It seems that custom font is already supported on iOS.

**Comment by dqii** [comment]
Is it supported? Last I had heard, this was a blocker to supporting custom fonts on iOS: https://github.com/stripe/stripe-ios/issues/1932

**Comment by dqii** [comment]
@charliecruzan-stripe Is it supported? Last I had heard, this was a blocker to supporting custom fonts on iOS: https://github.com/stripe/stripe-ios/issues/1932

**Comment by charliecruzan-stripe** [comment]
If you're looking for custom font control on iOS, I'd recommend either `CardField`, or the Payment Sheet :) I'm not sure about the timeline for adding this to CardForm so it could take a while

**Comment by dqii** [comment]
Oh I use CardField. I didn't realize it was supported there! Thank you. :)
