### ISSUE TITLE
isGooglePaySupported without initGooglePay

### ISSUE THREAD

**Issue by SamKomesarook** [stripe/stripe-react-native#683]
**Is your feature request related to a problem? Please describe.**
In order to simply check if Google Pay is supported on the device, it must be initialised with `initGooglePay`, then checked if an err occurred.

**Describe the solution you'd like**
Is it possible to create an `isGooglePaySupported` bool similar to `isApplePaySupported` returned from the `useGooglePay` hook?

**Describe alternatives you've considered**
Currently, just initialising Google Pay, then awkwardly passing the var from parent to children, as initialising multiple times in different components to check is leading to strange behaviour...

As for initialising once in a root component and saving the state to datastore, this could lead to issues where the store doesn't update after a user uninstalls Google Pay, which would throw an err. It would be best to check in real time when each component requires it.

**Additional context**
Different screens and components require the knowledge of if Google Pay is available, and initialising the pay each time is a little frustrating, so would be great if there was a cleaner way like the Apple Pay hook has.

**Comment by charliecruzan-stripe** [comment]
Thanks for this request! It's in progress now

**Comment by SamKomesarook** [comment]
Thanks for this yall!
