### ISSUE TITLE
Updating Shipping Options After Presenting Apple Pay screen on the basis of Address

### ISSUE THREAD

**Issue by NoisyBoyII** [stripe/stripe-react-native#685]
We want to call our api when ever user select the address on **Apple Pay** on the basis of that we want to update our shipping options. This is the code 

 const { presentApplePay, confirmApplePayPayment, isApplePaySupported } =
    useApplePay({
      onShippingContactSelected: (shippingContact, handler) => {
        console.log('shippingContact', shippingContact);
        // We call our api and get the shipping options from shippingContact but we don't have anything to update the options here on handler
        handler(cart);
      },
    });
When ever we update the shipping address the handler is returning out null or empty.
I have traced this function back to stripe sdk but i think it is not implemented, please see these screenshots.

Stripe Version : 0.2.2
<img width="1127" alt="Screenshot 2021-10-28 at 10 06 37 PM" src="https://user-images.githubusercontent.com/23364502/139298739-9e89e406-8656-40dc-bf16-df77c0bbe48b.png">

<img width="1103" alt="Screenshot 2021-10-28 at 10 06 54 PM" src="https://user-images.githubusercontent.com/23364502/139298780-9b3fa967-9b53-4ee3-bf04-4a03602c175b.png">

**Comment by p-sebastian** [comment]
@charliecruzan-stripe I think what @NoisyBoyII was asking, and the issue I am also having is that:

When the `ApplePay` sheet is opened, and the user selects a new `ShippingAddress`, we would like a way to update the `ShippingMethods`, for instance when shipping to a different country the shipping methods change.

Right now `onShippingContactSelected`  handler just updates the summary items, and it's the same with `onShippingMethodSelected`, there is no way to update the ApplePay sheet, once it has been opened.

**Comment by charliecruzan-stripe** [comment]
I see, thanks for the clarification! We can add that I believe
