### ISSUE TITLE
Custom font-family and font-weight not working in CardField Component

### ISSUE THREAD

**Issue by binitgurzu** [stripe/stripe-react-native#686]
**Describe the bug**

I am trying to change the CardInputField font-family with **Montserrat** font-family and also trying to apply font-weight but **font-family** and **font-weight** both not working in **android emulator** but on **iOS simulator** font-weight is working but font-family not working.

`
import {
  CardField,
  CardFieldInput,
  useStripe,
} from '@stripe/stripe-react-native';

<CardField
                postalCodeEnabled={true}
                placeholder={{
                  number: '4242 4242 4242 4242',
                  postalCode: 'ZIP',
                }}
                cardStyle={StyleSheet.flatten([
                  // STYLES.paymentCardInputFieldStyle,
                  {
                    fontFamily: 'Montserrat-Bold',
                    fontWeight: '700',
                    placeholderColor: Colors.lightGrey3,
                    textColor: Colors.black,
                    textErrorColor: Colors.error,
                  },
                ])}
                style={STYLES.cardFieldStyle}
                onCardChange={(cardDetails) => {
                  setCard(cardDetails);
                }}
              />
`
**Above code output:-**

**Screenshots**

**In Android Emulator**

![Screenshot_1635497350](https://user-images.githubusercontent.com/68578227/139405798-fb85dac7-1210-4142-81f5-a5239270179e.png)

**In iOS emulator:-**

![Simulator Screen Shot - iPhone 12 - 2021-10-29 at 14 25 41](https://user-images.githubusercontent.com/68578227/139406669-0d43a1e3-6f4e-4408-a68c-4949f6e34129.png)

**Working Environments**
```

"react-native": "0.64.1",

"@stripe/stripe-react-native": "^0.2.2",

Platform: android/iOS
```

**Expected behavior**
 I want to change the CardInputField default font-family and font-weight with my custom font-family and custom font-weight on both platforms.

**Comment by dqii** [comment]
From my understanding, custom fonts aren't supported, only system fonts (https://developer.apple.com/fonts/system-fonts/).

It's discussed here: https://github.com/stripe/stripe-react-native/pull/247

I made a request for custom fonts here: https://github.com/stripe/stripe-react-native/issues/681

**Comment by acomley-stripe** [comment]
Closing. Follow https://github.com/stripe/stripe-react-native/issues/681 for updates to support for custom fonts.
