### ISSUE TITLE
Apple Pay Payment Sheet Merchant Name Review Rejected

### ISSUE THREAD

**Issue by robert-nash** [stripe/stripe-react-native#691]
I'm not sure this is a bug per se but I'm having some trouble with the App Store reviewers and Apple Pay.

I have received the following response from review:

(Specifically, your app does not include the following: ... - Merchant's name on the payment sheet)

![image](https://user-images.githubusercontent.com/1884158/139653937-63333153-f083-4774-8d6f-8f215075e097.png)

It seems that I need to be displaying the merchant name on the Apple Pay sheet but I can't see how I can do this using stripe-react-native. I can't see any properties related to the merchant name in https://github.com/stripe/stripe-react-native/blob/master/src/types/ApplePay.ts

Any help or advice would be appreciated.

**Comment by robert-nash** [comment]
The merchant name should be specified as the label in the last element in cartItems passed to presentApplePay. I hadn't read the Apple documentation carefully enough.

**Comment by Mihai-github** [comment]
@robert-nash I have also got from Apple the same message about Merchant's name but I have provided the name... Idk why they thought is not there but they also told me to add the **Product description and specifications** and I have no idea how I can do that...

**Apple Response:**

Specifically, the following information is not specified on the payment sheet.

- Product description and specifications
- Merchant's name

**Comment by robert-nash** [comment]
Have you set cartItems with your product descriptions and the merchant name as seperate items?

**Comment by Mihai-github** [comment]
@robert-nash **initPaymentSheet** does not have this prop, I think you are talking about **presentApplePay** method to pay using directly Apply Pay not using initPaymentSheet.

Am I right?

**Comment by robert-nash** [comment]
Ah I see, yes. Sorry I've never used initPaymentSheet so probably can't be much help.

**Comment by Mihai-github** [comment]
Ok, I see. What do you use to collect payments with or without Google Pay / Apple Pay??

**Comment by robert-nash** [comment]
I've built my own UI to select from existing cards, add new cards or pay by Apple/Google Pay

**Comment by mrhillman** [comment]
Just got this for the first time despite having apps with same implementation for years, but if it helps others, here's what the docs say (https://docs.stripe.com/apple-pay?platform=react-native#present-payment-sheet):
`The final item must represent your company and the total; it appears in the sheet with the word “Pay” prepended (for example, “Pay iHats, Inc. 50 USD”)`

<img width="440" height="326" alt="Image" src="https://github.com/user-attachments/assets/b915bc1a-57e8-415e-a10e-a98c61b5250d" />

Still playing around with it, the example doesn't have the "Pay" prepended as it implies, but yeah
