### ISSUE TITLE
Apple Pay creates duplicate credit card payment methods

### ISSUE THREAD

**Issue by cooperwalter** [stripe/stripe-react-native#693]
**Describe the bug**
I'm using the `useStripe`, `initPaymentSheet`, and `presentPaymentSheet` flow with `applePay: true`. Every time I complete a transaction using Apple Pay, a new credit card payment method is added to the stripe customer. If I use the same credit card through Apple Pay each time, then duplicate credit card payment methods are created. I confirmed the presence of duplicate credit card payment methods in the Stripe dashboard record for the customer.

**To Reproduce**
1. Open the payment sheet
2. Press the Apple Pay button to pay with Apple Pay
3. Complete Apple Pay payment
4. Open a second payment sheet
5. Press the Apple Pay button
6. Complete Apple Pay payment with the same credit card as used in step 3.
7. Open a third payment sheet
8. See two credit card payment methods for the same card, the card used in Apple Pay

**Expected behavior**
Either no credit card payment methods are added, or only one is created. None are duplicated.

**Screenshots**
![IMG_0051](https://user-images.githubusercontent.com/40807488/139759006-4946d490-5f21-47c1-a61d-002d7c9af18f.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS15.0.1

**Additional context**
"react-native": "0.63.2",
"@stripe/stripe-react-native": "^0.2.1"

Here is what I'm passing to `initPaymentSheet`:
```
initPaymentSheet({
            customerId: 'the customer id',
            customerEphemeralKeySecret: 'the ephemeral key secret',
            paymentIntentClientSecret: 'the payment intent client secret',
            customFlow: false,
            merchantDisplayName: 'The Merchant Name',
            applePay: true,
            googlePay: true,
            merchantCountryCode: 'US',
            testEnv: Config.APP_ENV !== 'release',
})
```

Any help would be much appreciated!

**Comment by daveadapptor** [comment]
Agreed, I'm seeing exactly the same behaviour.  Every time I select Apple pay it duplicates an existing credit card although in my case the Apple pay card is a different one. (simulated card on simulator so its a fake Amex, other card is a test Visa).

"react-native": "0.63.4"
"@stripe/stripe-react-native": "^0.2.3"

**Comment by brhoomjs** [comment]
same here with ionic capacitor, any update?

**Comment by gazjones00** [comment]
We're also having this issue, with both Google pay and Apple pay. It seems to duplicate the payment method is there any update on this issue @acomley-stripe, please?

**Comment by tsalama** [comment]
@charliecruzan-stripe Still happening for me with both setup and payment intents. Would you prefer a new GH issue?

FWIW, I'm not using `customFlow: true` @jamzi

**Comment by skoolaidl** [comment]
Bump, I am also seeing this behavior.

**Comment by aviattri** [comment]
still hapenning

**Comment by joyceqin-stripe** [comment]
Hello, I'm sorry you're having issues. Are you on the latest SDK version? Cards saved through wallets like ApplePay are no longer displayed in the saved payment method list— they should be filtered out.
