### ISSUE TITLE
[CRASH] java.lang.NullPointerException: null cannot be cast to non-null type com.reactnativestripesdk.PaymentSheetFragment

### ISSUE THREAD

**Issue by deng-yc** [stripe/stripe-react-native#694]
**Describe the bug**

firebase crashlytics

![image](https://user-images.githubusercontent.com/12589538/139808344-14a8d168-2f2e-4566-943e-6835376549c7.png)

**To Reproduce**
my code:
![image](https://user-images.githubusercontent.com/12589538/139806955-bf14fcd1-81bd-4647-8aee-1ad48019192c.png)

**Smartphone (please complete the following information):**
 - Device: OPPO K3，Redmi k40
 - OS: android
 - Version 10

**Additional context**
 It's not happening all the time.

**Comment by remonh87** [comment]
@acomley-stripe  FYI: we also get reports from users that this crash is happening from users of our Flutter lib.  So it is not only this specific case. For reference: https://github.com/flutter-stripe/flutter_stripe/issues/416

**Comment by carl0shd** [comment]
+1, we having +100 crashes everyday in production because this error :(

![image](https://user-images.githubusercontent.com/8359234/153633043-f6cb7cc7-bbdd-4638-98ea-1110e839745d.png)

**Comment by remonh87** [comment]
@charliecruzan-stripe I think this is fixed with #788

**Comment by charliecruzan-stripe** [comment]
right you are @remonh87 👍
