### ISSUE TITLE
CardForm - Default country

### ISSUE THREAD

**Issue by Sunhat** [stripe/stripe-react-native#695]
**Is your feature request related to a problem? Please describe.**
Default Country is USA.

**Describe the solution you'd like**
Set a default country

**Describe alternatives you've considered**
Advising Stripe to hire a UX expert

**Additional context**

**Comment by SamKomesarook** [comment]
Lol

**Comment by Sunhat** [comment]
Trust Americans to think they're the only ones

**Comment by thenationofalex** [comment]
Australia should be the default 🤪

**Comment by ak55mm** [comment]
Is there any way we can choose a default country? The country-list is too long and not providing a way to set the default country is super annoying!

**Comment by hugoh59** [comment]
I would like this feature as well. Thank you.

**Comment by nuhman6281** [comment]
Zip Code selection field doesn't load first time. When I selected another country and come back to US. Then only the Zip Code field displays

**Comment by charliecruzan-stripe** [comment]
On iOS, the `CardForm` country defaults to the device's region. However, we can add the option to configure the default country on Android
