### ISSUE TITLE
error and paymentIntent undefined after handleCardAction

### ISSUE THREAD

**Issue by anija** [stripe/stripe-react-native#696]
**Describe the bug**
handleCardAction called with clientSecret when Stripe backend answer is: requiresNextAction and type is "stripe_3ds2_fingerprint" don't returns an error but also don't returns the paymentIntent.

**To Reproduce**
I can't reproduce this bug since it's happening in production, with a real customer card. Every test we made on test environment, with test cards, works fine.
The only difference we noticed between the test cards and the real one is that the test card is Visa, while the real one is Mastercard.

**Expected behavior**
Or error or paymentIntent should be returned by handleCardAction.

**Comment by anija** [comment]
Is this library still mantained? A bug opened 3 months ago still waiting to be seen by someone...

**Comment by charliecruzan-stripe** [comment]
Hi, can you provide code we can try to reproduce this bug with? Also, there's a lot of different test cards you can use to test here- https://stripe.com/docs/testing#cards (including visa and mastercard)

**Comment by anija** [comment]
As said:
I can't reproduce this bug since it's happening in production, with a real customer card. Every test we made on test environment, with test cards, works fine.

And yes, we tried every test card we found in the link you pasted.

**Comment by charliecruzan-stripe** [comment]
Maybe you can send me the paymentIntent ID of the relevant payment? If you have that, send it to charliecruzan@stripe.com please. Otherwise, without more information it's really difficult to try and guess at what might be happening here without seeing your code

**Comment by anija** [comment]
It's impossibile for me to get back to this particular case and its paymentIntent since it happened 5 months ago. But as soon as we'll get this problem again, i will send everything.

**Comment by charliecruzan-stripe** [comment]
Closing this issue for now, but if you can share details on how to reproduce it or a paymentIntent that this happened with, I will be happy to reopen 👍
