### ISSUE TITLE
Compatibility with Expo SDK 43

### ISSUE THREAD

**Issue by quentinmodena** [stripe/stripe-react-native#698]
**Is your feature request related to a problem? Please describe.**
We need to use some 0.2.0 new features in an Expo App

**Describe the solution you'd like**
Is a Expo SDK 43 compatible version of this library planned ? 
Or is there another way to use 0.2.0 with an Expo SDK 42 app ?

**Describe alternatives you've considered**
Rewriting the app in bare react native

**Comment by adnan909** [comment]
any updates on this? is there a workaround to use any of stripe's version with expo sdk 44?

**Comment by charliecruzan-stripe** [comment]
v0.2.2 was included in Expo SDK 43: https://github.com/expo/expo/blob/sdk-43/packages/expo/bundledNativeModules.json#L11

**Comment by Atanda1** [comment]
It's still not compatible. At least on expo snack.
