### ISSUE TITLE
CardField CVC placeholder not displayed on android device

### ISSUE THREAD

**Issue by quentinmodena** [stripe/stripe-react-native#699]
**Describe the bug**
CardField component : The placeholder "CVC" is not displayed before focus on android devices despite having the necessary space.

**To Reproduce**
1. Add a CardField component with postalCodeEnabled={false}

**Expected behavior**
As long as the input is not focused the "CVC" placeholder doesn't show.

**Screenshots**

Android :
![Capture d’écran du 2021-11-04 16-03-49](https://user-images.githubusercontent.com/16798995/140338766-b6a58536-3273-4ec1-9ca4-addd547946db.png)

IOS :
![IMG_5191](https://user-images.githubusercontent.com/16798995/140338934-a397339a-415c-47b1-bd52-424279709cd6.jpg)

**IOS device :**
 - Device: iPhone 8
 - OS: iOS14

**Android device :**
 - Device: Pixel 4 XL API 30 (Emulator), Samsung A51
 - OS: Android 11

**Additional context**
Expo SDK 42
@stripe/stripe-react-native 0.1.4

**Comment by Mo1otow** [comment]
Same question
