### ISSUE TITLE
Getting started & Installation fails

### ISSUE THREAD

**Issue by trag-stripe** [stripe/stripe-react-native#7]
**Describe the bug**
Filing this feedback on behalf of @richardg-stripe - feel free to add additional context.

Difficulty installing the project and not having a working build process. Richard (extensive RN experience) was asked to use the library without reading the steps. The feedback is shared below 👇 

## Notes from Richard's dogfooding session:

I created a new react native project following the instructions here: https://reactnative.dev/docs/environment-setup

### Project won't install and doesn't have a build.

- Project has both .circleci and Github actions couldn't find Circle build, github actions is failing.

- added: `"react-native-stripe-sdk": "stripe/stripe-react-native"` to package.json. Ran: `yarn install` this generated errors relating to example directory.

- `git clone https://github.com/stripe/stripe-react-native && cd stripe-react-native && yarn install` fails with the same error. `cd examples && yarn install` fixes it.

- Examples obviously should be built when building the package.

### `(cd ios && pod install)` fails

```pod install
Auto-linking React Native module for target `StripeReactNativeTesting`: react-native-stripe-sdk
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "react-native-stripe-sdk":
  In Podfile:
    react-native-stripe-sdk (from `../node_modules/react-native-stripe-sdk`)

Specs satisfying the `react-native-stripe-sdk (from `../node_modules/react-native-stripe-sdk`)` dependency were found, but they required a higher minimum deployment target.
```

I had modify `./ios/Podfile` `platform :ios, '1{0,1}.0'` to make this work.

### iOS Project still won't build

Error:

```
/Build/Products/Debug-iphonesimulator/StripeReactNativeTesting.app/StripeReactNativeTesting
ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
ld: warning: Could not find or use auto-linked library 'swiftCoreML'
Undefined symbols for architecture x86_64:
  "(extension in Foundation):__C.NSScanner.scanUpToString(Swift.String) -> Swift.String?", referenced from:
      static Stripe.STPPhoneNumberValidator.formattedRedactedPhoneNumber(for: Swift.String, forCountryCode: Swift.String?) -> Swift.String in libStripe.a(STPPhoneNumberValidator.o)
  "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_Stripe in libStripe.a(PKPaymentAuthorizationViewController+Stripe_Blocks.o)
```

I got stuck here

### Usage example

- To cater for the greatest number of developers it should be a javascript example not a typescript one. typescript developers understand javascript, but the reverse isn't true.

- The usage example is pseudo code - it doesn't actually work.

### Don't fetch publishable key from server?

I'm not super-familar with ios / android SDK - but is fetching publishable key from your server a best-practice we recommend? 

https://github.com/stripe/stripe-react-native/blob/master/example/src/App.tsx#L21-L29

It complicates their examples considerably and makes integration more difficult.

### Android builds but adding `import {StripeProvider} from 'react-native-stripe-sdk';` breaks the project 

RN isn't giving me an error anymore, I just get a white screen as soon as I add that line.

But at one point it said: 

```
 Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

This error is located at:
    in StripeProvider (at example.js:36)
    in _default (at App.js:36)
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView) (at App.js:31)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

But this might be a red herring. 

### Android minSDKVersion

Had to update: `android/build.gradle`

```
minSdkVersion = {16,21}
```

**Comment by ImPDP** [comment]
The bug is still there. Is there any fix for this issue
?

**Comment by arekkubaczkowski** [comment]
yes, it's still there but you can find workaround for this in the README under `troubleshooting` section
