### ISSUE TITLE
In Production only, Native 3D secure fails to authenticate, webview works. iOS and Android

### ISSUE THREAD

**Issue by bradsb** [stripe/stripe-react-native#703]
**Describe the bug**
Our customers cannot pass 3D secure authentication when it triggers the native flow despite receiving verification from their bank. This is not reproducible in development. One customer sent us a video, and we confirmed with others that it is multiple banks. The problem occurs with the flows triggered with these [test cards](https://stripe.com/docs/payments/3d-secure#three-ds-cards), except the Webview one, which successfully authenticates based on our customer feedback and witnessing the flow at promotional events.

**To Reproduce**
Not reproducible in development as far as we can tell. The test cards work fine.

**Expected behavior**
Customers to be able to authenticate in all 3D secure flows.

**Screenshots**
Censored video from customer to our support, the notification that appears is the bank for verification. Multiple users have told us that they complete the verification and return to the app and it has failed. This video shows that it fails immediately after selecting the verification method:

https://user-images.githubusercontent.com/18087818/140757439-faf58dde-068d-43ff-b514-2cc6e6039098.mp4

Customers this occurs to typically have a timeline on their payments in our dashboard that look like this:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/18087818/140758484-648ad86c-b41b-4e11-b8c4-692388e8dd6d.png">

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: any Android/iOS
 - OS: Android 11 / iOS 15
 - Browser N/A
 - Version N/A

**Additional context**
We are actually using [Flutter Stripe](https://github.com/flutter-stripe/flutter_stripe), and I have posted [an issue](https://github.com/flutter-stripe/flutter_stripe/issues/431) to their repository as well. However, that plugin seems to be a wrapper around this one to port it to dart, and the issue seems like something that may need to be dealt with by the Stripe team.

**Comment by bradsb** [comment]
This is marked as blocked on the Flutter stripe repo, so I hope someone will take a look at it. With this broken, the packages aren't really usable in production in the EU where SCA is required.

**Comment by nerder** [comment]
Any update on this?

**Comment by charliecruzan-stripe** [comment]
hi everyone, I believe this is the same as this issue- https://github.com/stripe/stripe-react-native/issues/733

> We're working on a solution for this. If you're experiencing this issue and would like to opt into our testing program, please email [3ds2-mobile-fallback@stripe.com](mailto:3ds2-mobile-fallback@stripe.com) with your [account ID](https://stripe.com/docs/dashboard#find-account-id). Thanks!
