### ISSUE TITLE
Ideal is not visible on Paymentsheet 

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#705]
**Describe the bug**
When creating a payment intent for ideal, the method is not being displayed on the payment sheet. According to the official docs this should be the case: https://stripe.com/docs/payments/accept-a-payment?platform=react-native. 

**To Reproduce**
1. Create an payment intent on the example server
2. init the paymentsheet using the paymentintentsecret of the response
3. confirm the paymentsheet and notice it is displayed without the option for iDeal (but I can set the card).

**Expected behavior**
Option Ideal to be displayed on the paymentsheet.

**Desktop (please complete the following information):**
 - iOS 15
 - Stripe library v.0.23

**Smartphone (please complete the following information):**
 - iPhone 13 simulator

**Comment by aliriaz-stripe** [comment]
@remonh87 hello, can you share: 

1/ Share the PaymentIntent ID where IDEAL is not showing up

2/ your client-side and server-side code of creating and confirming the PaymentIntent

This is most likely an integration bug and not an issue with the SDK (as the SDK does support IDEAL), so closing but I can unblock you if you give me more info

**Comment by remonh87** [comment]
@aliriaz-stripe  I checked my payment intent and there was sth wrong with the server-side (the example node-js server had an issue). Not sth for this library

**Comment by Sascha1251** [comment]
Hey @remonh87,
I have currently the same issue with the example node-js server, could you please share what you had to change on the server-side?
Thanks!

**Comment by Sascha1251** [comment]
@remonh87, ok, this wasn't the issue in my case.
Thank you very much for your answer :)

**Comment by ayushin** [comment]
having the same issue, how was this resolved and is there any good way to debug it?
