### ISSUE TITLE
Build failed on iOS with Error

### ISSUE THREAD

**Issue by AftabUfaq** [stripe/stripe-react-native#707]
the library worked fine on another project and also on another system where `Xcode version is 12.5` but it failed with error on Xcode 13 with the following Error

```
CompileSwift normal x86_64 /Users/Aftab/repos/winchit/customer/ios/Pods/Stripe/Stripe/STPAPIClient+Payments.swift (in target 'Stripe' from project 'Pods')
	CompileSwift normal x86_64 /Users/Aftab/repos/winchit/customer/ios/Pods/Stripe/Stripe/STPAPIClient+PushProvisioning.swift (in target 'Stripe' from project 'Pods')
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Stripe' from project 'Pods')
```

no issue on another project on Xcode 13.0. tried all solutions that are given in the double shooting but nothing improved. its day two now.

**Comment by Mahdisaghroun** [comment]
same issue

**Comment by jcmlumacad** [comment]
same issue

Xcode Version: 13.2

**Comment by handlez36** [comment]
Has anyone had any luck with this issue? I am facing the same on Xcode v13.2.1 (downloaded from apple dev site). Can't go back to 12 since I'm on Monterey.

**Comment by dhavalMindinventory** [comment]
facing same issue @handlez36 , have you find any solution ?

**Comment by dhavalMindinventory** [comment]
https://github.com/react-native-community/upgrade-support/issues/138#issuecomment-1018830449

**Comment by charliecruzan-stripe** [comment]
What version of React Native are your projects on? I'm on Xcode 13.2.1 and RN 0.66.4 and not seeing this error. 

If you're on RN 0.67, please follow the link that @dhavalMindinventory shared and lmk if that resolves it for you as well
