### ISSUE TITLE
Payment option icon disappears on iOS dark appearance

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#710]
**Describe the bug**
When setting the appearance to dark on iPhone the payment sheet option disappears:

https://user-images.githubusercontent.com/20230599/140979211-77d4ac8e-cd5e-4347-8893-6b66cb31f1e3.MP4

**To Reproduce**
Make sure to set iPhone appearance to dark in settings
1. Init payment sheet and set theme to light
2. Present the payment sheet
3. Click on the other payment method and notice the icon disappears (see video above).

**Expected behavior**
The icon should be visible.

**Additional info**
- iPhone X (iOS15)
- lib version 0.2.3

**Comment by charliecruzan-stripe** [comment]
this has been fixed in stripe-ios :)
