### ISSUE TITLE
presentPaymentSheet does not return when Apple Pay selected as payment type

### ISSUE THREAD

**Issue by daveadapptor** [stripe/stripe-react-native#715]
**Describe the bug**
When we call this...

`const { paymentOption, error } = await presentPaymentSheet();`

If a card is selected we get a callback.  However if Apple Pay is selected then no callback occurs, the payment sheet and Apple Pay sheets simply dismiss.

**To Reproduce**

Using : 
   "react-native": "0.63.4",
    "@stripe/stripe-react-native": "^0.2.3",

Setup phone with Apple Pay

Init payment sheet with

` const { error } = await initPaymentSheet({
      customerId: customer_id,
      customerEphemeralKeySecret: ephemeral_key,
      setupIntentClientSecret: client_secret,
      defaultBillingDetails: {
        address: {
          country: Config.COUNTRY_CODE,
        },
      },
      applePay: true,
      merchantCountryCode: Config.COUNTRY_CODE,
      merchantDisplayName: "REMOVED",
      testEnv: true,
      allowsDelayedPaymentMethods: true,
    });`

Present payment sheet with 

`const { paymentOption, error } = await presentPaymentSheet();
`

Forms dismiss and no callback is made.  However viewing the customer in the dashboard reveals that the payment method of Apple Pay has been successfully attached to the user.

**Expected behavior**
Callback occurs when Apple Pay setup complete and a paymentOption or error is returned.

**Smartphone (please complete the following information):**
Running on either an iOS simulator with iOS 12.2 (iPhone 6)
or
Physical device iPhone 6 with 12.5.5

**Comment by daveadapptor** [comment]
Turns out it doesn't work on iOS 12 but does on later versions....

**Comment by deng-yc** [comment]
Same problem
device：iphone 13 
os: ios15.1.1

**Comment by alecsvancsa66** [comment]
Having the same issue. Tested on multiple IOS devices and the bottom sheet just dismisses without any feedback.

**Comment by omtrx** [comment]
Solved my issue.

On the initPaymentSheet() constructor I had merchantCountryCode passed in as "UK" instead of the correct code "GB".

The Stripe paymentsheet closes to allow the Apple Pay sheet to open in its place. With an incorrect merchantCountryCode the Apple Pay sheet will not open and the Stripe paymentsheet will never return.
