### ISSUE TITLE
Remove country or region in Payment Sheet

### ISSUE THREAD

**Issue by dhananjayanravi** [stripe/stripe-react-native#717]
Hi,Guide me to remove "Country or region" from payment sheet 

Code am using:
const {error, paymentOption} = await initPaymentSheet({
        customerId: '',
        customerEphemeralKeySecret: '',
        paymentIntentClientSecret: '',
        merchantDisplayName: 'example Ltd.',
        merchantCountryCode: 'AU',
        testEnv: false,
        primaryButtonColor: '#635BFF', // Blurple
        returnURL: 'stripe-example://stripe-redirect',
        postalCodeField:false,
        defaultBillingDetails:{
        address :{
          country: 'AU'
        }}
        });  
Following screen shot which am getting now, 
![Screenshot 2021-11-12 at 8 05 41 PM](https://user-images.githubusercontent.com/80961313/141483995-2ea86caa-9039-4aaf-b9d4-5f1e717f794b.png)

**Comment by charliecruzan-stripe** [comment]
I'm not sure this is currently possible from the native libraries. Would you like this removed just to simplify the UI?

**Comment by adrien-may** [comment]
Same issue here. We don't need to store or retrieve country information. It would be a great addition if we can simplify the UI and remove that field.

**Comment by BerkeAras** [comment]
**_Still relevant_**
Same issue here. We are a plattform and only sell to german customers. We do not need that too.

**Comment by ktiniatros** [comment]
To at least prelect a country, you can set it in the billing details:

```
await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        billingDetails: const BillingDetails(
          address: Address(
            country: 'GR',
            city: '',
            line1: '',
            line2: '',
            state: '',
            postalCode: '',
          ),
        ),
        style: ThemeMode.light,
      ),
    );
```

**Comment by charliecruzan-stripe** [comment]
Hi! This can be removed by setting the `billingDetailsCollectionConfiguration`. You can avoid collecting the address with:

```
const { error } = await initPaymentSheet({
      ...
      billingDetailsCollectionConfiguration: {
        address: PaymentSheet.AddressCollectionMode.NEVER,
      },
    });
```

**Comment by ethanb1996** [comment]
Is this compatible with expo sdk 0.48

**Comment by rashedoz** [comment]
> Hi! This can be removed by setting the `billingDetailsCollectionConfiguration`. You can avoid collecting the address with:
> 
> ```
> const { error } = await initPaymentSheet({
>       ...
>       billingDetailsCollectionConfiguration: {
>         address: PaymentSheet.AddressCollectionMode.NEVER,
>       },
>     });
> ```

This worked for me

`  await Stripe.instance
          .initPaymentSheet(
              paymentSheetParameters: SetupPaymentSheetParameters(
                  billingDetailsCollectionConfiguration: const BillingDetailsCollectionConfiguration(address: AddressCollectionMode.never),
....
...`
