### ISSUE TITLE
React Native Android App - Could not create task ':stripe_stripe-react-native:compileDebugAndroidTestKotlin'.

### ISSUE THREAD

**Issue by MedFount** [stripe/stripe-react-native#718]
I would really appreciate, if some one can help me. I'm adding the payment option on my android app and after installing "npm install @stripe/stripe-react-native" on my React Native Project, I cannot build. It give following error

Gradle -v
Gradle 7.2
Build time: 2021-08-17 09:59:03 UTC
Revision: a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin: 1.5.21
Groovy: 3.0.8
Ant: Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM: 15.0.2 (Oracle Corporation 15.0.2+7-27)
OS: Windows 10 10.0 amd64

build.gradle

buildscript {
ext {
buildToolsVersion = "29.0.3"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29
ndkVersion = "20.1.5948944"
kotlinVersion = "1.5.21"
}
repositories {
google()
jcenter()
}
dependencies {
classpath 'com.android.tools.lint:lint:26.3.2'
classpath 'com.android.tools.build:gradle:4.0.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
classpath 'com.google.gms:google-services:4.3.8'
// NOTE: Do not place your application dependencies here; they belong
// in the individual module build.gradle files
}
}

BUILD ERROR -

FAILURE: Build failed with an exception.

What went wrong:
Could not determine the dependencies of task ':stripe_stripe-react-native:bundleLibCompileToJarRelease'.
Could not create task ':stripe_stripe-react-native:compileReleaseKotlin'.
Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultLanguageSettingsBuilderKt

**Comment by penghouho** [comment]
in my code, the error starts happening after I added 
classpath com.android.tools.lint:lint

**Comment by Kashikamoka7124** [comment]
> in my code, the error starts happening after I added classpath com.android.tools.lint:lint

Sir Do you finds its solution ??

**Comment by Kashikamoka7124** [comment]
> I would really appreciate, if some one can help me. I'm adding the payment option on my android app and after installing "npm install @stripe/stripe-react-native" on my React Native Project, I cannot build. It give following error
> 
> Gradle -v Gradle 7.2 Build time: 2021-08-17 09:59:03 UTC Revision: a773786b58bb28710e3dc96c4d1a7063628952ad
> 
> Kotlin: 1.5.21 Groovy: 3.0.8 Ant: Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM: 15.0.2 (Oracle Corporation 15.0.2+7-27) OS: Windows 10 10.0 amd64
> 
> build.gradle
> 
> buildscript { ext { buildToolsVersion = "29.0.3" minSdkVersion = 21 compileSdkVersion = 29 targetSdkVersion = 29 ndkVersion = "20.1.5948944" kotlinVersion = "1.5.21" } repositories { google() jcenter() } dependencies { classpath 'com.android.tools.lint:lint:26.3.2' classpath 'com.android.tools.build:gradle:4.0.1' classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" classpath 'com.google.gms:google-services:4.3.8' // NOTE: Do not place your application dependencies here; they belong // in the individual module build.gradle files } }
> 
> BUILD ERROR -
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong: Could not determine the dependencies of task ':stripe_stripe-react-native:bundleLibCompileToJarRelease'. Could not create task ':stripe_stripe-react-native:compileReleaseKotlin'. Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultLanguageSettingsBuilderKt

Sir Do you finds its solution ??

**Comment by penghouho** [comment]
can you try remove 
classpath 'com.android.tools.lint:lint:26.3.2'

for me I have non-blocking warning before I added it,
after added it, I could not even build
hence I removed it again...

**Comment by charliecruzan-stripe** [comment]
Going to close this as it seems @penghouho had the same error and fixed it with the above. In the future, if you get build errors in your app after installing `@stripe/stripe-react-native`, please share the full error message and preferably a project we can use to reproduce the issue :)
