### ISSUE TITLE
getting a error while running app in debug mode Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)

### ISSUE THREAD

**Issue by Nsingh0007** [stripe/stripe-react-native#720]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.JWEObject$State found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.JWSObject found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.JWSObject$State found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.Payload found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.Payload$Origin found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.Requirement found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter$AlgFamily found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH$AlgorithmMode found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  Duplicate class com.nimbusds.jose.jwk.KeyOperation found in modules jetified-nimbus-jose-jwt-9.12.1.jar (com.nimbusds:nimbus-jose-jwt:9.12.1) and jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 15s

**Comment by Nsingh0007** [comment]
I am also facing this Error.
can you please help me to resolve this out?

 gradle-6.8.1-all.zip

**Comment by Nsingh0007** [comment]
this is happening if You are using Square payment gateway in your app and trying to implement Stripe.

I Just commented on the square code and tried. It workes for me.

**Comment by Nsingh0007** [comment]
this is happening if You are using Square payment gateway in your app and trying to implement Stripe.

I Just commented on the square code and tried. It workes for me.

**Comment by charliecruzan-stripe** [comment]
Thanks for sharing the fix @Nsingh0007 ! Is there a use case for using both, or was it just some leftover unused code? You can configure gradle to install only one version of the threedssdk if you do need both libraries installed in your project
