### ISSUE TITLE
Clicking the cross to close the payment sheet doesn't send a Canceled error in custom flow

### ISSUE THREAD

**Issue by Liodene** [stripe/stripe-react-native#723]
**Describe the bug**
If you create a payment sheet with a custom flow and, present it using presentPaymentSheet then close it, you don't get an error. If you do the same thing without the custom flow, you get a PaymentSheetError.Canceled error.

It means you can't know if the user added a payment or just decided to close the payment form.

Moreover, there is a different response to presentPaymentSheet between Android and iOS if the user filled the form correctly then close it with the cross:
- On Android, you get a paymentOption undefined, so you know the user didn't validate the form and you can stop the payment flow
- On iOS, you get the paymentOption entered, so you can't know whether the user want to continue or not

**To Reproduce**
1. Create a payment sheet with custom flow and call presentPaymentSheet
2. Fill the form
3. Close with the cross

**Expected behavior**
- When clicking the cross, we should get a Canceled error
- When clicking the cross, we shouldn't get a value in paymentOption

**Smartphone (please complete the following information):**
 - Android: OnePlus 5T / Android 10
 - iOS: iPhone 13 (Simulator) / iOs 15

**Additional context**
Using it with Expo 42 so it's a quite old version of Stripe (0.1.4).

**Comment by jonasbark** [comment]
There's also the following log output:
> D/Error: com.stripe.android.paymentsheet.PaymentOptionResult$Canceled cannot be cast to com.stripe.android.view.AddPaymentMethodActivityStarter$Result

**Comment by abdullahIsa** [comment]
Hello i am still having this issue on android

"react-native": "0.70.6"
"@stripe/stripe-react-native": "^0.23.1"

**Comment by charliecruzan-stripe** [comment]
Can you provide a reproducible demo via a Github repo? I'm not able to reproduce that myself

**Comment by abdullahIsa** [comment]
> Can you provide a reproducible demo via a Github repo? I'm not able to reproduce that myself

Just an update seems to be working ok now after downgrading and updating to the new latest version, thanks.
