### ISSUE TITLE
Google Pay OR_BIBED_07

### ISSUE THREAD

**Issue by SamKomesarook** [stripe/stripe-react-native#730]
**Describe the bug**
When completing a purchase through Google Pay, a small modal with the following error pops up:

`Request Failed. An unexpected error has occurred.. Please try again later. [OR_BIBED_07]`

It might be parallel to [this issue](https://github.com/google-pay/flutter-plugin/issues/102) which shows the same err, and references a "payment configuration JSON". Is this something the lib creates?

Viewing the logs from `adb logcat` shows the following logs being executed with each click of the GooglePayButton and the throwing of the err:

```
11-22 14:24:56.392 10666 10666 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3293 
11-22 14:24:56.392 10487 31503 I GCM.HTTP: Last HTTP status code for blocked entry: 500
11-22 14:24:56.392 10487 31503 W GCM.HTTP: HTTP request blocked due to automatic backoff: https://payments-pa.googleapis.com/payments/apis-secure/ui2/buyflowservice/initialize
11-22 14:24:56.392  4006  7313 W GoogleURLConnFactory: Blocked by temporary_blocked2: https://payments-pa.googleapis.com/payments/apis-secure/ui2/buyflowservice/initialize
11-22 14:24:56.392 10666 10666 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1981 
11-22 14:24:56.393 10666 10666 I DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():79 Notify device unlocked.
11-22 14:24:56.394  4006 20227 E O2NetworkAction: Network Error: java.util.concurrent.ExecutionException: com.android.volley.NoConnectionError: xzl: Blocked by rule: temporary_blocked2
11-22 14:24:56.807 16973 17007 D OpenGLRenderer: endAllActiveAnimators on 0xb400007c7489fcf0 (RippleDrawable) with handle 0xb400007b848a45f0
11-22 14:24:56.808  1792  4606 W InputManager-JNI: Input channel object 'de73e91 com.google.android.gms/com.google.android.gms.wallet.activity.GenericDelegatorInternalActivity (client)' was disposed without first being removed with the input manager!
1
```

**To Reproduce**
Reproducing the err is difficult, as different devices we have tested with reported different errs, all using the same builds and similar versions of android.

We have implemented a google play button exactly as outlined in the docs: initialising stripe appropriately, creating a GooglePayButton, and presenting google pay when the button is clicked. We deployed our app to the app store for beta testing.

**Expected behavior**
Google Play Button initiates and completes the payment.

**Screenshots**
![Screenshot_20211122-135539(1)](https://user-images.githubusercontent.com/47465976/142943073-117fe15b-14b2-4845-9dca-cbb4d81974d8.png)

**Smartphone:**
 - Device: Google Pixel 5
 - OS: Android 12

**Additional context**
The payment flow works fine when running the app on the Android Emulator (API Version 30), however once deployed to the app store, throws the err.

**Comment by JlUgia** [comment]
Hi @SamKomesarook, do you get any [`WalletMerchantError` entries](https://developers.google.com/pay/api/android/support/troubleshooting#request-failed) in the logs? These contain more details about the issue.

**Comment by SamKomesarook** [comment]
Hey @JlUgia, I've run the log command listed in the link you sent, reproduced the error, and no logging appears in my console :(

**Comment by SamKomesarook** [comment]
Turned out this issue was related to not initialising the Google Pay API for this app. Strange that the message was not clearer to reflect that, as some other tests showed a different err with more specific wording.

**Comment by weeks6** [comment]
> Turned out this issue was related to not initialising the Google Pay API for this app. Strange that the message was not clearer to reflect that, as some other tests showed a different err with more specific wording.

Hi, I'm having very simillar issue, what exactly do you mean by "not initialising the Google Pay Api for this app"? I went thorugh the official guide, added all the dependencies and edited the manifest file. Are there any extra steps?

**Comment by SamKomesarook** [comment]
@weeks6 Yeah I used this [guide](https://developers.google.com/pay/api/android/overview), specifically initialising it in the [console](https://pay.google.com/business/console). I kinda think this stuff should be added to the docs, as it isn't mentioned anywhere I could find either in this lib or in generic stripe docs...

**Comment by Flucadetena** [comment]
Hey guys!, Im having the same issue and I don't know if the documentation changed or I'm doing something wrong. But could you explain here what are the steps to take please.

I've tried adding my stripe public key to the "Encryption Keys" y the direct "integration section" in business console and I get and error that it is not coded the right way.

I must be doing something wrong but can't find how to set up this. Thanks a lot for time and effort

**Comment by SamKomesarook** [comment]
@Flucadetena can you post the err you get in the business console? You mean the encryption keys you created were not valid?

**Comment by Flucadetena** [comment]
Hi @SamKomesarook of course!

This is the error (I have erase the name sensitive data):
<img width="1670" alt="Captura de pantalla 2022-01-21 a las 9 41 25" src="https://user-images.githubusercontent.com/38214790/150494909-da48b974-02da-4dd2-a8b4-6968eb355a27.png">
 

The key I pasted was the pubishable key from stripe. I've you need me to explain anything else let me know.

**Comment by SamKomesarook** [comment]
@Flucadetena have you encoded the API key in base64 and tried saving that? Try `openssl base64 -in <infile> -out <outfile>` from the command line, and copy the contents of the outfile as your public key.

**Comment by alexzaitsev** [comment]
Guys, just want to confirm - even if my company already uses Stripe to Apple Pay and now we are adding Google Pay, do we still need to do Google Business Console set up?

**Comment by JlUgia** [comment]
Hi!
If you are operating in `PRODUCTION` you need to add a `merchantId` that is valid and has been approved in [Google Pay's Business Console](https://pay.google.com/business/console) in your configuration.

**Comment by oriedofelo** [comment]
> Hi! If you are operating in `PRODUCTION` you need to add a `merchantId` that is valid and has been approved in [Google Pay's Business Console](https://pay.google.com/business/console) in your configuration.

Hi, I have added a valid merchantId in my app, where do I put the merchant id for approval in the Google Pay Business Console? Kindly assist

**Comment by arthurfacredyn** [comment]
@samcampisi Where did you upload your AAB/APK, did you upload it to the Closed Testing Track? Or do you have to do it to the Releases?

**Comment by nipunru** [comment]
If anyone still having this issue. I got resolved by creating a singned APK instedad of using ADB.

`After your app has been approved, test your integration in production by setting the environment to GooglePayEnvironment.Production, and launching Google Pay from a signed, release build of your app. Remember to use your live mode [API keys](https://stripe.com/docs/keys).`

**Comment by glennweb** [comment]
My app is not yet approved in Google Pay Console.  Am I able to test using ENVIRONMENT_TEST = 3?

Or also need to wait for approval to test this?

**Comment by nipunru** [comment]
For TEST environmnt, you don't need an approval.
Please read this documentation. https://stripe.com/docs/google-pay
