### ISSUE TITLE
Android fails to build after updating to 0.2.3

### ISSUE THREAD

**Issue by droplessjake** [stripe/stripe-react-native#732]
**Describe the bug**

Could not compile build file '/Users/jakegilesphillips/Documents/Dropless/mobile/node_modules/@stripe/stripe-react-native/android/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61

**To Reproduce**
Update to latest 0.2.3, try to run android build.

**Expected behavior**
Android should build

**Screenshots**
<img width="897" alt="Screenshot 2021-11-24 at 10 42 58" src="https://user-images.githubusercontent.com/83917938/143223706-1014f5a5-51ad-47b4-8b2d-46d6ab914563.png">

**Smartphone (please complete the following information):**
 - Device: Android

**Additional context**
I recently updated to the latest 0.2.3 version, and am now met with this error when trying to run the build. 
Seems like the issue is within ```/@stripe/stripe-react-native/android/build.gradle```

**Comment by sandrok1609** [comment]
Same issue here, works fine on iOS but take ages to build on Android

**Comment by droplessjake** [comment]
> Same issue here, works fine on iOS but takes ages to build on Android. What version were you on previously?

Was on 0.2.2 previously, tempted to rollback, the changes aren't crucial to me

**Comment by charliecruzan-stripe** [comment]
What versions of React Native and Gradle are you using?

**Comment by charliecruzan-stripe** [comment]
The originally posted error here ("Unsupported class file major version 61") seems to indicate that your project may be trying to use a newer JDK version.. [Make sure you've installed the correct version of JDK according to your React Native version](https://reactnative.dev/docs/environment-setup)
