### ISSUE TITLE
Pod Install Build Error

### ISSUE THREAD

**Issue by drinikol** [stripe/stripe-react-native#738]
We have successfully published our app previously but upon creating a fresh install. This occurs. Tried the suggested solutions but It create more errors in XCODE.

XCODE 12.5.1

```[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `stripe-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

**Comment by NamNP06** [comment]
You can try 👍  add modular_headers==>fasle in Podfile
pod '...', :path => '../node_modules/react-native-', :inhibit_warnings => true, :modular_headers => false

**Comment by lordival** [comment]
any luck with this issue?

**Comment by prog-24** [comment]
> You can try 👍 add modular_headers==>fasle in Podfile pod '...', :path => '../node_modules/react-native-', :inhibit_warnings => true, :modular_headers => false

This solves it. but it should be `:modular_headers => true` instead of false

**Comment by drinikol** [comment]
`  pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true`
Figured it out by trial and error. This made it work.
