### ISSUE TITLE
PostalCode not sent with CardField

### ISSUE THREAD

**Issue by bernardorubin** [stripe/stripe-react-native#739]
**Describe the bug**
When using the CardField component the PostalCode isn't being sent. i can see the new Payment Method being correctly sent on the Stripe dashboard but the PostalCode is missing.

**To Reproduce**
1. Use the `CardField` component and set postalCodeEnabled to true.
2. Then send the data to stripe using 
```
const { error, paymentMethod } = await createPaymentMethod({
          type: "Card",
        });
```
3. Log into the stripe admin, filter the customer with the same email, notice how there is no Postal Code under the customer Payment methods details.

**Expected behavior**
Postal Code should be sent using CardField and should appear under the payment method details.

**Screenshots**
Screenshot of a payment method that was sent using `tipsi-stripe` with correct Postal Code Data (below) and the payment method being sent by `stripe-react-native` (above)
<img width="530" alt="Screen Shot 2021-12-01 at 20 14 33" src="https://user-images.githubusercontent.com/25016886/144509541-ec151229-fe1c-4820-92db-3b341f99ce9e.png">
<img width="378" alt="Screen Shot 2021-12-02 at 16 02 53" src="https://user-images.githubusercontent.com/25016886/144510406-43635124-4014-49dc-a5d0-3f4999ba4421.png">

**Smartphone (please complete the following information):**
 - OS: macOS
 - React Natie on both iOS and android

**Additional context**
I'm not getting any errors back from the response.

**Code:**
```
        const [card, setCard] = useState(null);

        const { error, paymentMethod } = await createPaymentMethod({
          type: "Card",
        });
        
       <CardField
        postalCodeEnabled={true}
        placeholder={{
          number: "1234 5678 1234 5678",
        }}
        cardStyle={{
          backgroundColor: theme.colors.basic200,
        }}
        style={{
          width: "100%",
          height: 50,
          marginVertical: theme.space.lg,
        }}
        onCardChange={(cardDetails) => {
          setCard(cardDetails);
        }}
      />
```

**Comment by seanzhang-stripe** [comment]
Hi @bernardorubin thanks a lot for reporting this problem and I'm sorry for the inconvenience.

I'm able to reproduce the issue in Android, and I can see that the `post_code` is missing in the request and that is why you don't find it in the Dashboard. 

While waiting for the fix, here is a simple workaround that you can try.

All you need to do is create an empty `billingDetails` object and pass it to the `createPaymentMethod()`

```js
const billingDetails: PaymentMethodCreateParams.BillingDetails = {}; 

const { paymentMethod, error } = await createPaymentMethod({
      type: 'Card',
      billingDetails,
});
```
Please let us if the workaround works for you, and feel free to reach out to us if you have any questions.

**Comment by bernardorubin** [comment]
I can confirm this is a valid workaround. Thanks for the reply @seanzhang-stripe 👍
