### ISSUE TITLE
[bug] createCardPaymentMethodParams does not support Cards with paymentMethodId param

### ISSUE THREAD

**Issue by jamesblasco** [stripe/stripe-react-native#744]
**Describe the bug**
Right now when you build a PaymentMethodParam you can use the prebuilt components, the deprecated token and the paymentMethodId.

On the native layer the `PaymentMethodFactory` does not build correctly the params for the one with the `paymentMethodId`, in fact without any warning uses the card params from the prebuilt card ui elements if they have been used!

https://github.com/stripe/stripe-react-native/blob/189fd3233b9347e712f8f3b7ea549a6a344aff96/ios/PaymentMethodFactory.swift#L129-L136

https://github.com/stripe/stripe-react-native/blob/b49a8a758af3fe7722abd5798a1100fd508eb2c0/src/types/PaymentMethods.ts#L73-L76

**Expected behavior**
Implement correctly the PaymentMethodParam.Card with paymentMethodId on the native layer

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charliecruzan-stripe** [comment]
hi! we actually don't rely on the PaymentMethodFactory if the paymentMethodId is passed: https://github.com/stripe/stripe-react-native/blob/master/ios/StripeSdk.swift#L822-L826

Going to close this since it seems to be implemented correctly, but let me know if this isn't working for you!
