### ISSUE TITLE
Can't determine if user has checked save payment checkbox

### ISSUE THREAD

**Issue by DZuz14** [stripe/stripe-react-native#745]
I am using the [prebuilt UI](https://stripe.com/docs/payments/accept-a-payment#react-native-collect-payment-details) and want to know if the user has checked the  save payment checkbox so I can do some additional processing with our own database. Is this currently possible? If not, it would be cool if somehow that was available.

Not sure how difficult that is, but thanks in advance.

**Comment by charliecruzan-stripe** [comment]
Unfortunately that's not exposed right now (it's an internal save on Stripe's end). Out of curiosity- what's the use case for this?
