### ISSUE TITLE
EventEmitter.removeListener is deprecated

### ISSUE THREAD

**Issue by alwyntan** [stripe/stripe-react-native#746]
**Describe the bug**

Console throwing the following warning because removeListener has been deprecated:

EventEmitter.removeListener('onDidSetShippingMethod', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.

The following lines of code in [useApplePay.tsx](https://github.com/stripe/stripe-react-native/blob/a54cbe9e4a3211f208996134cb19cc668425dcc3/src/hooks/useApplePay.tsx#L117-L127) is causing the issue.

```
    return () => {
      eventEmitter.removeListener(
        SET_SHIPPING_METHOD_CALLBACK_NAME,
        onDidSetShippingMethod
      );
      eventEmitter.removeListener(
        SET_SHIPPING_CONTACT_CALLBACK_NAME,
        onDidSetShippingContact
      );
    };
  }, [onDidSetShippingContact, onDidSetShippingMethod]);
```

**To Reproduce**
1. Anywhere in your React Native app, import and use the "useApplePay" hook.

**Expected behavior**
No warnings to be shown because removeListener is deprecated.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

versions:
    "react-native": "0.66.1",
    "@stripe/stripe-react-native": "^0.2.3",
    "react": "17.0.2",

**Comment by charliecruzan-stripe** [comment]
fixed in https://github.com/stripe/stripe-react-native/commit/7cfcdc00bdaac7deb5836baba6ce8542bce509d7, thanks for filing this issue!
