### ISSUE TITLE
Google Pay Button - Request failed This merchant is not enabled for Google Pay. 

### ISSUE THREAD

**Issue by MaelTlb** [stripe/stripe-react-native#753]
**Describe the bug**
My app is developed on expo react native, eas-build compilation process. My application accepts payments through ApplePay (works correctly simulator and compiled), GooglePay gives me the following error when trying to pay from an Android device with the wallet configured.  A popup message appears with the following text -> Request failed This merchant is not enabled for Google Pay. 

My code is roughly the same as the example in this library. 

**Screenshots**
"Can't take screenshot due to security policy"

**Smartphone (please complete the following information):**
Device: Samsung Galaxy A50
OS: Android
Version: 11.0

**Additional context**

These are the version numbers of the libraries I’m using, relevant to this topic/issue:
    "@stripe/stripe-react-native": "0.2.3",
    "expo": "^43.0.3",
    "react-native": "0.64.3",

I completed payments https://play.google.com/console

**Comment by charliecruzan-stripe** [comment]
Hi, this is an error from Google, not Stripe: https://developers.google.com/pay/api/web/support/troubleshooting

> The Google Pay API requires a Google merchantId for sites that configure PaymentsClient for a PRODUCTION environment. A Google merchantId is associated with one or more fully qualified domains through the [Business Console](https://pay.google.com/business/console). Check the returned error details for more information.

You linked the regular google play console, have you gone through the business console?

(Closing since I don't believe this is a bug in `stripe-react-native`, but will reopen if we find out otherwise)
