### ISSUE TITLE
PaymentSheet: Collect shipping information 

### ISSUE THREAD

**Issue by akhan118** [stripe/stripe-react-native#754]
**Is your feature request related to a problem? Please describe.**
Hi there,

Would it be possible to have the new PaymentSheet collect the shipping address?

**Describe the solution you'd like**

`  shipping_address_required: true,
`
**Describe alternatives you've considered**
Building my own form

**Additional context**
<img width="249" alt="Screen Shot 2021-12-22 at 1 00 04 PM" src="https://user-images.githubusercontent.com/4065374/147142073-97b8282f-db71-43bd-ae64-d600bcb87987.png">

**Comment by charliecruzan-stripe** [comment]
Waiting on https://github.com/stripe/stripe-ios/issues/1813 for this

**Comment by charliecruzan-stripe** [comment]
available with AddressSheet :) 

See: https://stripe.com/docs/elements/address-element?platform=react-native
