### ISSUE TITLE
Ability to remove cancel button from initPaymentSheet

### ISSUE THREAD

**Issue by Mihai-github** [stripe/stripe-react-native#757]
**Is your feature request related to a problem? Please describe.**

-> Not able to remove the close button that exists on the bottom payment sheet (initPaymentSheet).

**Describe the solution you'd like**

-> Adding a param that can remove the close button that appears on the bottom payment sheet.

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/56633911/147643741-998767c1-815a-4f3c-8baa-adb45f67c4b0.png)

**Comment by charliecruzan-stripe** [comment]
hi! Can you provide details on why you want the option to remove the close button?

**Comment by Mihai-github** [comment]
@charliecruzan-stripe I wanted to be able to not let the user close the payment sheet and then manually make it appear again by letting the user press a button so the user can pay because I have a separate screen where the payment sheet appears and the payment is processed and there's not anything then the payment sheet on that page so he/she can see anything then a white background on that page.

I know is just a let's say an "edge case" or not necessarily a must to exist, but would help in the future if someone else will need this "feature" to exist.

**Comment by Mihai-github** [comment]
Yes, I know but it's already going to production and for this version, we will keep this functionality. Probably we are gonna change to use individual elements in the next release of the app.

**Comment by charliecruzan-stripe** [comment]
sounds good!
