### ISSUE TITLE
customize payment sheet  --> stripe / stripe-react-native

### ISSUE THREAD

**Issue by aliMurtaja** [stripe/stripe-react-native#761]
Hello,

  I am use stripe/stripe-react-native  in my app,
  actually my requirement is that when I show the payment sheet using -->presentPaymentSheet()  method provided by same 
  package, it will show the card that is not expired(enable), and will show the card that is expired(disabled).
  and default card checked automatically when first time load the page.
  
Thanks in advance....

**Comment by charliecruzan-stripe** [comment]
Hi! Could you provide some more details around what you're asking for? What's the current behavior, and what behavior are you looking to have?
