### ISSUE TITLE
Apple Pay on paymentsheet does not complete on iOS12

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#765]
**Describe the bug**
Some of our users of the FlutterStripe lib mentioned that the paymentsheet Apple Pay is hanging on iOS12. I was able to reproduce this issue.

**To Reproduce**
1. Create payment intent
2. Open the paymentsheet on a iOS12 device
3. Tap apple pay
4. Notice the Apple Pay sheet is displayed
5. Confirm the form and press pay
6. Notice the sheet is hanging

I expect the payment to go through like on iOS13/14/15.

**Screenshots**
See movie
https://user-images.githubusercontent.com/20230599/148358818-b176d7c1-c3c9-400c-b7df-efb5e26871e0.mp4

**Comment by charliecruzan-stripe** [comment]
@remonh87 unfortunately your video skips right from the 2nd second all the way to the end for me 🙁 I tested this on an iOS 12 simulator and did not notice any hang (using the code from the `example/` app). Could you try that? Or you may also be able to debug this further by looking through the Xcode logs at the point when the app hangs
