### ISSUE TITLE
Be able to change cursor color on Android

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#766]
**Is your feature request related to a problem? Please describe.**
Cursor color cannot be changed on the Cardield when running on  Android. On iOS this is possible.

**Describe the solution you'd like**
I would like to change the cursor color on Android.

**Additional context**
Looks like cursor color is not set here: https://github.com/stripe/stripe-react-native/blob/b49a8a758af3fe7722abd5798a1100fd508eb2c0/android/src/main/java/com/reactnativestripesdk/StripeSdkCardView.kt#L81

**Comment by michelleb-stripe** [comment]
@charliecruzan-stripe Take a look and see if you can use ViewBinding to bind to the fields and set the cursor color.
