### ISSUE TITLE
No AppDelegate.swift file

### ISSUE THREAD

**Issue by Bamorem** [stripe/stripe-react-native#767]
https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-set-up-return-url

On the documentation to how setup payment, at the step 5 you give only the code for the AppDelegate.swift, but the issue is hat by default the react native project are set up with AppDelegate.h and AppDelegate.m 

how can i place the code for AppDelegate.swift in my AppDelegate.m ?

**Comment by MagnusSinger** [comment]
I'm having the same problem

**Comment by MagnusSinger** [comment]
Okay so I figured it out and I'll post my solution here in case anyone has the same problem in the future.

1: At the top of the file, before `@implementation AppDelegate` place this to import the framework:

`@import Stripe;`

2: In the openURL block, add the following before `return NO;`:

`  if ([StripeAPI handleStripeURLCallbackWithURL:url]) {
    return YES;
  }`

3: Change the continueUserActivity method to the following:

`if ( [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler]) {
    return YES;
  }
  if (userActivity.activityType == NSUserActivityTypeBrowsingWeb) {
    if (userActivity.webpageURL != NULL) {
      if ([StripeAPI handleStripeURLCallbackWithURL:userActivity.webpageURL]) {
        return YES;
      }
    }
  }
  return NO;`

Sorry for the bad formatting, this is the first time I do something like this. Hope this helps anyway.

Reference: https://stripe.com/docs/mobile/ios/sdk-21-migration?language=objc

**Comment by MagnusSinger** [comment]
From the Apple Docs it says: "The app calls this method when it receives data associated with a user activity, for example, when the user transfers an activity from a different device using Handoff. Implement this method to update your iOS app so that the user can continue the activity from where they left off." (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623072-application?language=objc)

If you don't have this method inside your AppDelegate yet, just add this at the end of the file **before** the `@end` statement:
```
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{  
  if (userActivity.activityType == NSUserActivityTypeBrowsingWeb) {
    if (userActivity.webpageURL != NULL) {
      if ([StripeAPI handleStripeURLCallbackWithURL:userActivity.webpageURL]) {
        return YES;
      }
    }
  }
  
  return NO;
}
```

**Comment by charliecruzan-stripe** [comment]
Hi! You actually shouldn't need to edit your AppDelegate file anymore, you can instead use the `handleURLCallback` exported from the SDK. Here's an example of how to use it:

```jsx
export default function MyApp() {
  const { handleURLCallback } = useStripe();

  const handleDeepLink = useCallback(
    async (url: string | null) => {
      if (url && url.includes('safepay')) {
        await handleURLCallback(url);
        // Add extra handling here as you see fit
      }
    },
    [handleURLCallback]
  );

  useEffect(() => {
    const getUrlAsync = async () => {
      const initialUrl = await Linking.getInitialURL();
      handleDeepLink(initialUrl);
    };

    getUrlAsync();

    const deepLinkListener = Linking.addEventListener(
      'url',
      (event: { url: string }) => {
        handleDeepLink(event.url);
      }
    );

    return () => deepLinkListener.remove();
  }, [handleDeepLink]);

  return (
    <View>
      <AwesomeAppComponent />
    </View>
  );
}
```

I'll be updating the docs shortly!

**Comment by flurryventures** [comment]
@charliecruzan-stripe as of which @stripe/stripe-react-native version is the above valid? Also, where in the docs can I find the update that shows these changes? Thanks!
