### ISSUE TITLE
Pressing "Set Up" in PaymentSheet changes StatusBar color to purple in Android

### ISSUE THREAD

**Issue by SrBrahma** [stripe/stripe-react-native#768]
**Describe the bug**
Pressing "Set Up" in PaymentSheet changes StatusBar color to purple in Android

**To Reproduce**

1) Run `await presentPaymentSheet();` after `initPaymentSheet()`
2) Enter new card info or select existing card and press `Set Up` button

**Expected behavior**
My status bar color shouldn't change its color.

**Screenshots**
Before pressing

![image](https://user-images.githubusercontent.com/28177550/148664302-3a48716b-d439-43e9-961e-99529abdc7d4.png)

After pressing

![image](https://user-images.githubusercontent.com/28177550/148664304-2826c405-fd10-47bc-ac19-b85d4150b154.png)

The color returns to its previous after the Processing ends.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8 Pro
 - OS: Android

**Additional context**

**Comment by charliecruzan-stripe** [comment]
Fix is merged, and will be released in the next version of `stripe-android` (we soft-match versions, so if it's released as a patch version, then you can pull it in automatically, otherwise we'll need to do another release of stripe-react-native as well)
