### ISSUE TITLE
CardField Style Customizability is limited

### ISSUE THREAD

**Issue by michaelbayday** [stripe/stripe-react-native#77]
**Describe the bug**
CardField component does not respond to color in the style prop to set text color. Perhaps have an api to handle the components styling in different states would be great i.e. focusedStyle errorStyle and unfocusedStyle 

```ts
    <CardField
        onCardChange={(cardDetails) => {
          setCardData(cardDetails);
        }}
        style={{
          height: 50,
          width: '100%',
          backgroundColor: theme.BACKGROUND,
          borderColor: theme.GREY3,
          borderRadius: 4,
        }}
        postalCodeEnabled={false}
      />
```

**To Reproduce**
1. Use CodeBlock above

**Expected behavior**
1. Color should be allowed to be set by the consuming application

**Screenshots**
![image](https://user-images.githubusercontent.com/35093298/108916139-b3879d00-75e2-11eb-87ee-aba428560803.png)

![image](https://user-images.githubusercontent.com/35093298/108915952-715e5b80-75e2-11eb-90d5-7790749975c7.png)

**Smartphone (please complete the following information):**
- iOS simulator

**Additional context**
1. We have a dark mode here at Rivian and the inability to customize font color makes the component unusable in dark mode.

**Comment by marcshilling** [comment]
> @arekkubaczkowski these properties doesn't work on the CardForm component. is that intentional?

Agreed. We need all these options on CardForm as well. CardForm barely has any styling options.

**Comment by gauravag23** [comment]
for Card form:

You can check color scheme and set cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}as per light or dark theme.

             <CardForm
                    cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}
                 
                />
