### ISSUE TITLE
Unable to resolve module ../../package.json

### ISSUE THREAD

**Issue by yanzdog** [stripe/stripe-react-native#770]
**Describe the bug**

Hello! I am quite new to React Native and trying to integrate Stripe using @stripe/stripe-react-native. After initializing the library following the installment guide on Stripe (https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=custom), I get the error below and not sure how to solve this (I don't know if this is a bug or not). 

```
Unable to resolve module ../../package.json from /Users/.../node_modules/@stripe/stripe-react-native/lib/commonjs/components/StripeProvider.js: None of these files exist: *node_modules/@stripe/stripe-react-native/lib/package.json
```

**Versions**
```
react: 17.0.2
react-native: 0.66.4
stripe-react-native: 0.2.3
babel: 7.12.9
running device: iOS 15 simulator
```

Also I am developing in React cli (not expo)

Is there anything else I need to integrate the library other than `yarn add and pod install` ? Any help would be much appreciated! Thanks a lot in advance!

**Comment by fdelacruzsoto** [comment]
I started to get the same issue a few minutes ago, it happened after I deleted (for reasons) the yarn lock file and installed everything again.

**Comment by yanzdog** [comment]
@fdelacruzsoto 

found any solutions ... ?

**Comment by yanzdog** [comment]
this was my bad. I had wrong settings in `metro.config.js`. Closing!

**Comment by alekhinen** [comment]
@yanzdog what was the setting you had in metro that was causing the issue? I'm running into the same problem in my app.

**Comment by yanzdog** [comment]
@alekhinen @jukaha 

I am using https://github.com/apollographql/apollo-client for api client and added some changes to metro config referring to this change log. (https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-354-2021-11-19). 

However, `require("metro-config")` was looking at wrong path and causing this stripe error. So I corrected it to the right path which is `require('metro-config/src/defaults/defaults')`.

Hope this helps!

**Comment by Kinzito17** [comment]
@jukaha @alekhinen I was able to find a workaround to this issue [here]( https://github.com/stripe/stripe-react-native/issues/841 ) hope it helps!
