### ISSUE TITLE
Android - CardForm wouldn't accept style on light themed app

### ISSUE THREAD

**Issue by rakefetWorkiz** [stripe/stripe-react-native#771]
**Describe the bug**
Using CardForm element on android, when having the app on light theme (`Theme.MaterialComponents.Light.NoActionBar`), when using the app on a device using dark mode the input text will stay white, making it invisible. 

adding a black background only for this form is of course not an option, since it will not go with the rest of the app. 

we cannot look into the source code of the elements used, so changing them to fit the app design is also not an option. 

how can we tap into the style of those components?

**To Reproduce**
1. Add the library to your app like advised in the library readme file.
2. Add material components to the app main style `<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">`
3. Add card form element to your component : 
`
<CardForm
    onFormComplete={card => {  }}
    style={{
        height: Platform.OS === "ios" ? 200 : 300,
    }}
    cardStyle={{}}
/>
`
4. run the app on android device being set to dark mode.

**Expected behavior**
The component will catch the main theme to be "light" and accordingly, use light theme color, with no regards to the device dark/light mode.

**Screenshots**
This is how it looks in iOS : (expected behaviour) 
![Screen Shot 2022-01-10 at 18 35 10](https://user-images.githubusercontent.com/42907218/148802660-84e6deb3-e73f-4955-b244-e432e1548a83.png)

this is how it looks in android: 
![Screen Shot 2022-01-10 at 18 35 46](https://user-images.githubusercontent.com/42907218/148802772-4b9f200a-8db1-4575-a867-c32701fd2a0b.png)

**Smartphone (please complete the following information):**
 - Device: Galaxy S20
 - OS: android 11
 - Browser NA
 - Version NA

PS: I couldn't find any documentation on how to tackle design on this component. 
if you can reference me please to a documentation on the matter, so I can make the android styling more matching to our app style, that would be greatly helpful

Thanks

**Comment by remonh87** [comment]
we observe the same on the flutter_stripe library. There is no way to configure the text color at the moment.

**Comment by james-chege** [comment]
Similar issue on iOS but vice versa. When the phone is set to a dark theme, the text and placeholders are not visible.

**Comment by cark1** [comment]
To make it works for iOS, set a text color for the **cardStyle** prop.

` <CardField
          cardStyle={{
            textColor: '#000000',
    }} />`
    
For android I changed the app theme:

` <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">`
in
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`

In this way, I can see the texts in light and dark mode (Android and iOS)

**Comment by JacobHicks** [comment]
Has anyone found a solution for this? `textColor` doesn't seem to work for CardForm

**Comment by charliecruzan-stripe** [comment]
Keeping track of `CardForm` customization in this issue- https://github.com/stripe/stripe-react-native/issues/563. I have a PR open for the Android side, but on iOS we are blocked (see the issue)

For your specific case @rakefetWorkiz , I would either change your theme to use `DayNight` as recommended by Material in their documentation, or if you want to completely block Dark theme UI you could add 

```
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
```

to your `MainApplication.java` inside of `onCreate`

**Comment by charliecruzan-stripe** [comment]
Landed https://github.com/stripe/stripe-react-native/pull/849 which helps with this as well :)

**Comment by gauravag23** [comment]
You can check color scheme and set cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}as per light or dark theme.

                 <CardForm
                        cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}
                     
                    />

**Comment by muhammadvsashfaq** [comment]
textColor doesn't seem to work for CardForm.

**Comment by uragirii** [comment]
For anyone who stumbled upon this issue and is using Expo CNG i used the following custom plugin 

```js
const { withMainApplication } = require('expo/config-plugins');

function withDisableNightMode(config) {
  return withMainApplication(config, config => {
    const mainApplication = config.modResults.contents;

    // Check if the line already exists to avoid duplicates
    if (
      !mainApplication.includes(
        'AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)',
      )
    ) {
      const onCreateIndex = mainApplication.indexOf(
        'override fun onCreate() {',
      );
      if (onCreateIndex !== -1) {
        const insertIndex = mainApplication.indexOf('{', onCreateIndex) + 1;
        const updatedMainApplication = [
          mainApplication.slice(0, insertIndex),
          '\n    androidx.appcompat.app.AppCompatDelegate.setDefaultNightMode(androidx.appcompat.app.AppCompatDelegate.MODE_NIGHT_NO)',
          mainApplication.slice(insertIndex),
        ].join('');
        config.modResults.contents = updatedMainApplication;
      }
    }

    return config;
  });
}

module.exports = { withDisableNightMode };

```

and then you can import this in your `app.config.ts` file and wrap your config in `withDisableNightMode`
