### ISSUE TITLE
handleCardAction not calling returnURL / authentication WebView not closing

### ISSUE THREAD

**Issue by te-online** [stripe/stripe-react-native#772]
**Describe the bug**
When calling `handleCardAction`, if an authentication modal opens for 3D-secure, it is never closed, since no return URL is called.

**To Reproduce**
1. Create a payment intent with a test card that always requires authentication
2. Call `handleCardAction(paymentIntentClientSecret)`
3. Go through 3D-secure or cancel it
4. WebView / Sheet does not close

**Expected behavior**
The authentication WebView closes, because `scheme://safepay` is being called and the app in question has implemented a handler for these links and calls `handleURLCallback` subsequently.

**Screenshots**
![Simulator Screen Shot - iPhone 12 Pro - 2022-01-12 at 12 21 18](https://user-images.githubusercontent.com/4127167/149131025-5e21c7d9-91bd-4f18-820f-5e173940099c.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.2
 - Browser: Safari
 - Version [e.g. 22] n/a

**Additional context**
I already mentioned this problem in [this related issue](https://github.com/stripe/stripe-react-native/issues/519#issuecomment-1010024121). However, in our app closing of the authentication modal works fine now when using `confirmSetupIntent`, because we implemented the handler for the `safepay` link. It's just not working when using `handleCardAction`.

It looks to me like [in this method](https://github.com/stripe/stripe-react-native/blob/cd323b44a1d02ce3059006465f7b06826350fb5c/ios/StripeSdk.swift#L602) the additional returnURL parameter is missing from the resulting paymentIntent object. Not sure if this is the cause though.

**Comment by Eth3rnit3** [comment]
Any news about this problem?

**Comment by charliecruzan-stripe** [comment]
Fix is incoming
