### ISSUE TITLE
Card details has merged the date and card number 

### ISSUE THREAD

**Issue by SebghatYusuf** [stripe/stripe-react-native#773]
**Describe the bug**
CardField is showing card number and date placeholders merged together.

**To Reproduce**
1. Install the app on lower resolution devices
2. Open cardfield screen (page) 

**Expected behavior**
Card Number should not be merged with the date. 

**Screenshots**

![issue ss](https://user-images.githubusercontent.com/48417629/149565116-4e46d2e5-4fc1-4eb9-acfc-84f14624a25f.png)

**Smartphone (please complete the following information):**
 - Device: [RUIO S6501 A-ONE , realme C25]
 - OS: [Android 10]

**Additional context**
This issue already has been reported to the (stripe-android -- this link)[https://github.com/stripe/stripe-android/issues/4501], they suggested to open the ticket here.

**Comment by charliecruzan-stripe** [comment]
Can you provide the code for `<CardField />` you're using to reproduce this?

**Comment by SebghatYusuf** [comment]
Thanks for looking into this issue, Actually I'm using flutter to develop my app meanwhile, I'm using [flutter_stripe](https://github.com/flutter-stripe/flutter_stripe) package to integrate stripe, but then I got this issue, I've created a ticket on their repo as well, they told me they've limited support for the layout [this comment](https://github.com/flutter-stripe/flutter_stripe/issues/524#issuecomment-1007965371) and asked me to report the issue on android-stripe, and then @skyler-stripe asked me to open the issue here.

**Comment by charliecruzan-stripe** [comment]
I see, can you provide a reproducible demo of this using the React Native library, not the Flutter library?

**Comment by SebghatYusuf** [comment]
@charliecruzan-stripe 
unfortunately, I can't because even using flutter_stripe (Flutter) the issue is happening on some small screen android devices (I don't have one, but one of our app testers got this issue), I couldn't reproduce it using the iOS simulator tried to scale up the font but everything seemed to be okay. 
I feel reproduction would not be much hard, having the <CardForm> in a page with some margin/padding around it so the form should not have enough space. 
Still, I'm not sure, I'm not very good with React Native to reproduce the issue.
