### ISSUE TITLE
FATAL EXCEPTION: DefaultDispatcher-worker-7 when adding a payment method

### ISSUE THREAD

**Issue by Rc85** [stripe/stripe-react-native#776]
**Describe the bug**
App crashes with fatal exception when adding a payment method using `CardField`

**To Reproduce**
1. Add payment method using `CardField`

**Expected behavior**
Should create a payment method

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8

```
react-native 0.66.4
@stripe/stripe-react-native 0.2.3
```

**Additional context**
```
FATAL EXCEPTION: DefaultDispatcher-worker-7
Process: com.my_takeouts, PID: 12455
java.lang.AbstractMethodError: abstract method "void com.stripe.android.ApiResultCallback.onSuccess(com.stripe.android.core.model.StripeModel)"
	at com.stripe.android.Stripe$dispatchResult$2.invokeSuspend(Stripe.kt:1661)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
It was working fine until I try to implement Google Pay. Updated my `app/build.gradle`, `AndroidManfiest.xml`, and `build.gradle`.

Added `mavenCentral()` to `buildscript -> repositories`. 
Added
```
implementation 'com.google.android.gms:play-services-wallet:19.0.1'
implementation 'com.stripe:stripe-android:19.1.0'
````
to `app/build.gradle`
Added `<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />` to AndroidManifest.xml.

Implemented Google pay using `initGooglePay` in `useEffect`. Then, I have a button that calls `createGooglePayPaymentMethod` to create payment method.

Then I tried adding a 3DS card and thought maybe it's the authentication model crashing my app. Then I tried using `4000 0000 0000 0077` like I regularly would, and it's still crashing. The only other thing I remember changing was the `urlScheme` prop in `<StripeProvider>`, but changing it back didn't fix anything.

**Comment by Rc85** [comment]
Removed `implementation 'com.stripe:stripe-android:19.1.0'` And issue is gone.

**Comment by ZentPeople** [comment]
Hi I am also facing the same issue. on removing implementation 'com.stripe:stripe-android:19.1.0', won't there be any issue?

**Comment by Rc85** [comment]
> Hi I am also facing the same issue. on removing implementation 'com.stripe:stripe-android:19.1.0', won't there be any issue?

I believe Stripe has there own package in the library. When you add the implementation in your build.gradle, you're overriding the one Stripe uses. Correct me if I am wrong.
