### ISSUE TITLE
One click checkout

### ISSUE THREAD

**Issue by crystalii** [stripe/stripe-react-native#778]
Hello!

Does this SDK have support for one-click checkout by Stripe?

**Comment by charliecruzan-stripe** [comment]
hi @crystalii - I think what you're looking for is implemented on [this screen of our example app](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICompleteScreen.tsx), using `presentPaymentSheet`. Let me know if that works for you
