### ISSUE TITLE
Client-Only integration

### ISSUE THREAD

**Issue by iamhaaamed** [stripe/stripe-react-native#784]
is it possible to client-only integration with stripe-react-native? If it is, how to do?

**Comment by r1jsheth** [comment]
You can use `checkout`

**Comment by charliecruzan-stripe** [comment]
If by client integration you mean with no server code, no that's not currently available. The reason for requiring an endpoint is explained here: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-add-server-endpoint
