### ISSUE TITLE
ApplePay not working on real device: Payment not completed @0.2.3

### ISSUE THREAD

**Issue by jonaxd1** [stripe/stripe-react-native#789]
**Describe the bug**
ApplePay is working on Simulator, but on a real device is not. I had a valid credit card in my wallet and Test Mode on Stripe Dashboard. I already checked that the amount value is a string on carItems.

I got this error: 
```json
{
  "code": "Failed",
  "message": "Payment not completed",
  "domain": "RCTErrorDomain",
  "userInfo": null,
  "nativeStackIOS": [
    "0   app_name_dev                      0x0000000104e8dd2c RCTJSErrorFromCodeMessageAndNSError + 116",
    "1   app_name_dev                      0x0000000104e2a1b4 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 144",
    "2   app_name_dev                      0x00000001055249b4 $sSo8NSStringCSgACSo7NSErrorCSgIeyByyy_SSSgAGs5Error_pSgIegggg_TR + 320",
    "3   app_name_dev                      0x000000010552e694 $s19stripe_react_native9StripeSdkC15applePayContext_15didCompleteWith5errory0D008STPApplegH0C_AG16STPPaymentStatusOs5Error_pSgtF + 740",
    "4   app_name_dev                      0x000000010552eb68 $s19stripe_react_native9StripeSdkC15applePayContext_15didCompleteWith5errory0D008STPApplegH0C_AG16STPPaymentStatusOs5Error_pSgtFTo + 116",
    "5   app_name_dev                      0x000000010517ca10 $s6Stripe18STPApplePayContextC39paymentAuthorizationControllerDidFinishyySo09PKPaymentfG0CFyycfU0_yycfU_ + 204",
    "6   app_name_dev                      0x00000001050bd664 $sIeg_IeyB_TR + 48",
    "7   libdispatch.dylib                   0x000000010838c6d4 _dispatch_call_block_and_release + 32",
    "8   libdispatch.dylib                   0x000000010838e3b4 _dispatch_client_callout + 20",
    "9   libdispatch.dylib                   0x000000010839e898 _dispatch_main_queue_callback_4CF + 1224",
    "10  CoreFoundation                      0x0000000180e95d84 16FAA70C-278C-3561-859E-CEC407C2DC7C + 335236",
    "11  CoreFoundation                      0x0000000180e4ff5c 16FAA70C-278C-3561-859E-CEC407C2DC7C + 48988",
    "12  CoreFoundation                      0x0000000180e63468 CFRunLoopRunSpecific + 600",
    "13  GraphicsServices                    0x000000019c9ee38c GSEventRunModal + 164",
    "14  UIKitCore                           0x0000000183805088 CD7F7BA2-A2C6-3727-AFF6-9BAAB60CC6AB + 5349512",
    "15  UIKitCore                           0x0000000183583958 UIApplicationMain + 2092",
    "16  app_name_dev                      0x0000000104c4d414 main + 104",
    "17  dyld                                0x0000000108189aa4 start + 520"
  ]
}
```

**To Reproduce**
```js
const { error, paymentMethod } = await presentApplePay({
	cartItems: [{ label: 'Example item name', amount: '14.00' }],
	country: 'US',
	currency: 'USD',
	shippingMethods: [
		{
			amount: '20.00',
			identifier: 'DPS',
			label: 'Courier',
			detail: 'Delivery',
			type: 'final',
		},
	],
	requiredShippingAddressFields: ['emailAddress', 'phoneNumber'],
	requiredBillingContactFields: ['phoneNumber', 'name'],
});
if (error) {
	console.log("ERROR APPLE PAY 1: ", JSON.stringify(error));
	console.log("ERROR APPLE PAY 1: ", JSON.stringify(paymentMethod, null, 2));
	SimpleToast.show(error.message);
}
```

OR

```js
const { error, paymentMethod } = await presentApplePay({
	cartItems: [{amount: "10.65", label: "Americano"}, {amount: "3.55", label: "Americano"}, {amount: "14.20", "label": "Store Name"}],
	country: 'US',
	currency: 'USD',
	requiredBillingContactFields: ['phoneNumber', 'name'],
});
if (error) {
	console.log("ERROR APPLE PAY 1: ", JSON.stringify(error));
	console.log("ERROR APPLE PAY 1: ", JSON.stringify(paymentMethod, null, 2));
	SimpleToast.show(error.message);
}
```

**Expected behavior**
Payment status "succeeded"

**Screenshots**
![IMG_2891](https://user-images.githubusercontent.com/34318586/152066535-63d1a043-e9de-47fc-b5b9-4c3f5f9b4f30.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser: -
 - Version: -

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 15.2.1
 - Browser: -
 - Version: -

**Additional context**
My Credit Card is from Mexico. I tried to change the Currency and Country to MXN-MX, but still is not working

**Comment by jonaxd1** [comment]
> Is this on a live app? or a dev app?

What did you mean? The app is in development, is testing on TestFlight. But I get the same error running directly from XCode on a real device. (In the simulator it works).

**Comment by KeithM23** [comment]
We're also getting this error in our App (on 0.2.3 and 0.3.0) when on a real device. 

Looking into the iOS code the error seems to be during a request to the tokens endpoint on stripe's Api to exchange the pk_token to a stripe token. 

On a simulator this does a 'faked/simulated' type of request by the looks of it with the following::

```
POST /tokens

{
    "pk_token": "",
    "pk_token_instrument_name": "Simulated Instrument",
    "pk_token_payment_network": "AmEx",
    "pk_token_transaction_id": "ApplePayStubs~4242424242424242~0~USD~8FD09737-BE88-4CE9-A06C-9B464B2AD449"
}
```

where the uuid (by the looks of it) can be randomised to always generate a valid token from the tokens endpoint in postman/similar. This means this always works on a simulator however on a real device (even in TEST mode) this does an actual request with the following:

```
POST /tokens

{
    "pk_token": "{
       "version":"EC_v1",
       "data":"<data>",
       "signature": "<signature>",
       "header":{
          "ephemeralPublicKey":"<ephemeralPublicKey>",
          "publicKeyHash":"<publicKeyHash>",
          "transactionId":"<transactionId>"
       }
     }",
    "pk_token_instrument_name": "<Card Brand> <Last4>",
    "pk_token_payment_network": "<Card Brand>",
    "pk_token_transaction_id": "<transactionId>"
}
```

This call looks fine but is returning the following:

```
400 Bad Request (Sample request id: req_til4hkZqSsqJbT)

{
    "error": {
        "message": "The certificate used to sign your request is invalid. For help troubleshooting, please visit https://stripe.com/docs/apple-pay/apps#troubleshooting.",
        "type": "invalid_request_error"
    }
}
```

To use this looks like an error in building the request parameters that are expected on this endpoint as the same call works on Web. Comparing this to the Web version, the web request adds in a few extra attributes into it's call, namely

header[applicationData]
guid
muid
sid
key

and various card[XXXX] fields

Our thinking is the lack of one of the above / in particular how the pk_token is missing 'applicationData' in the header field is the cause of it.

Could this be treated as a P0 as if true means Apple Pay is not working?

Please note above is what we have seen from debugging this and we have no special knowledge of stripe's code so it may be completely wrong. We also made builds on a real device that sent the fake/simulated data that the simulator sends and this passes as expected but obviously isn't usable in production. We tried using the 'applicationData' values and other params sent on Web without any luck/success.

**Comment by karlr-stripe** [comment]
That error from the sample request ID would indicate that you haven't set up your Stripe account by uploading your Apple Pay processing certificate(created through your Apple Developer account), rather than any particular issue with the SDK itself I believe. 

https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#register-for-an-apple-merchant-id 
https://stripe.com/docs/apple-pay?platform=react-native#merchantid 

At a high level, the iOS SDK(which this ReactNative library bridges to) interacts with Apple's libraries to obtain a native  PkPayment  object, which contains the encrypted card details. To decrypt it, it's passed to Stripe's API for your account that has set up certs as documented above.  If you haven't set that up or your app is using a different Apple Pay Processing Certificate than uploaded to your Stripe account then you'd get that error.

The simulator doesn't need this, and the web integration works entirely differently(no requirement to upload your own certs) and has no connection here. For mobile/React Native, it's required to set things up as described there.

**Comment by KeithM23** [comment]
@karlr-stripe thank you so much this was our issue, don't know why we assumed the certificate was a stripe issue.

**Comment by jonaxd1** [comment]
Same here. Apple Pay Certificate was missing to upload to Stripe. Thank you.

**Comment by charliecruzan-stripe** [comment]
We should catch this error and surface it more visibly, going to re-open this issue

**Comment by vidurajith-darshana-sentura** [comment]
I had the same error, cause of amount set to a number value.

await presentApplePay({
                cartItems: [{ label: pack.name, amount: '100'}], //amount should be a string value
                country: 'HU',
                currency: 'HUF'
            });

**Comment by hezhengjian** [comment]
> 我有同样的错误，原因是金额设置为数字值。
> 
> await presentApplePay({ car​​tItems: [{ label: pack.name, amount: '100'}], //amount 应该是一个字符串值 country: 'HU', currency: 'HUF' });
You saved me. You don't know what I went through, but thank you.

**Comment by nabihahmad** [comment]
I am running on version 0.24.0, and still getting the error "Payment not completed". However, the problem is not happening with all our customers. Some Apple Pay payments are going through, others are failing. With that in mind, I don't think that my issue is due to a missing CSR on the Stripe portal. I actually have it uploaded since the first release of the feature. I am also sending the amount as a string. However, the issue is still happening intermittently with my customers. What do you advise me to do?
