### ISSUE TITLE
App crashes when calling confirmPayment method.

### ISSUE THREAD

**Issue by droplessjake** [stripe/stripe-react-native#791]
**Describe the bug**
The app crashes without error when calling the confirm payment method.
We used to have no issue until we recently updated to gradle 7 and JDK 11, I think this may be key here.
All other stripe functionality in our app however does still work.

**To Reproduce**
1. Call confirmPayment, pass in the clientSecret and the paymentMethodId
2. App crashes

**Expected behavior**
Payment confirmation is returned.

**Smartphone (please complete the following information):**
 - Device: any android
 - OS: Android (tested on 10 and 11)
 - Version:
    - React 0.66.3
    - Gradle 7.1.0
    - JDK 11
    - targetSdkVersion = 30
    - compileSdkVersion = 31

I call the function like so:
```
await confirmPayment(clientSecret, { type: 'Card', paymentMethodId: stripePaymentId });
```
passing in 
```
clientSecret: pi_3KOo2rGa9Fuy5tMh1oCnnquD_secret_fCBKA6qKkxSIeFiIJu4wDUt08
stripePaymentId: pm_1K4kgiGa9Fuy5tMhnpTBHWhI
```

**Comment by charliecruzan-stripe** [comment]
Could you investigate the native device logs by running `adb logcat` at the time of the crash, and see if there's a useful exception or error message logged?

**Comment by droplessjake** [comment]
@charliecruzan-stripe It looks to me like here is likely of interest
```
02-02 19:33:38.789 11038 11254 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
02-02 19:33:38.789 11038 11254 E AndroidRuntime: Process: uk.co.dropless, PID: 11038
02-02 19:33:38.789 11038 11254 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.stripe.android.ApiResultCallback.onSuccess(com.stripe.android.core.model.StripeModel)"
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at com.stripe.android.Stripe$dispatchResult$2.invokeSuspend(Stripe.kt:1661)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8057)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
02-02 19:33:38.789 11038 11254 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by droplessjake** [comment]
Worth noting too, that the payment IS succesful, I can see it in stripe dashboard, it seems to just be crashing at the point of success.

**Comment by droplessjake** [comment]
@charliecruzan-stripe any update?

**Comment by droplessjake** [comment]
Turns out our solution was to downgrade `wechatpay`, something that got updated during our move to gradle 7 and JDK 11.
<img width="466" alt="Screenshot 2022-02-03 at 09 20 53" src="https://user-images.githubusercontent.com/83917938/152314674-1bd201a9-f554-4524-950c-fc36c09d8ec1.png">

All is good now 👍

**Comment by DilipLohar123** [comment]
Confirm 2 think

1. SetOption =>
stripe.setOptions({
      publishableKey:STRIPE_PUBLIC_KEY , // use public key only
      // merchantId: 'MERCHANT_ID', // Optional
      androidPayMode: 'test', // Android only
    })
    
    2. On confirm payment 
      stripe.confirmPaymentIntent({
      clientSecret: paymentIntent.client_secret, //should be add client_secret not paymentintent Id
      paymentMethodId: paymentIntent.selectedCardId, // your cart id
      return_url: BASE_URL,
    });

**Comment by intelecision** [comment]
was this issue resoled as i am getting the same proble
