### ISSUE TITLE
initPaymentSheet - Apple reject the application going to the store.

### ISSUE THREAD

**Issue by Mihai-github** [stripe/stripe-react-native#793]
**Is your feature request related to a problem? Please describe.**

Apple rejected the app going to the store because: 

Specifically, the following information is not specified on the payment sheet.

- Product description and specifications
- Merchant's name

**Describe the solution you'd like**

A way to add some custom text or something that will allow me to put the **product description specifications** and **merchant's name** on the **initPaymentSheet**. Right now I cannot find anything that will allow me to add this time of customization to the **initPaymentSheet**

**Describe alternatives you've considered**

Props that will show and tell the user what firm is gonna pay and what is he/she buying on the initPaymentSheet.

**Additional context**

Screenshot from Apple testing the app:

![pay](https://user-images.githubusercontent.com/56633911/152519213-2de39c6f-ea70-420b-b935-bf4646cf049c.png)

**Comment by charliecruzan-stripe** [comment]
You can provide the Merchant's name to `initPaymentSheet` via the  `merchantDisplayName` param. Did Apple specifically say the product description needed to be present in the payment sheet? We haven't received any other reports of that. See [this other issue](https://github.com/stripe/stripe-react-native/issues/691)

**Comment by Mihai-github** [comment]
@charliecruzan-stripe Yes, this is a screenshot from them and this part:
> Specifically, the following information is not specified on the payment sheet.
> 
> Product description and specifications
> Merchant's name

Is also something that they told us. 

As you said I've already added for merchantDisplayName some info inside it about what the user is "paying" and waiting for a response from Apple... but the merchantDisplayName has a max of 35 chars from my testing so for something long will not show everything (this is an edge case I know).

One question if you know and can give some info.... with `initPaymentSheet` for Apple Pay I have an issue regarding the amount it says "AMOUNT PENDING" when we are using `setupIntentClientSecret` not `paymentIntentClientSecret` (Photo below):

![image](https://user-images.githubusercontent.com/56633911/153176017-66118e26-cf8f-44bd-8154-111dc00a9b01.png)


If possible I would like to control the "amount" but I do not see an option for that as far as I can see right now...
Also, I know there is the `presentApplePay` option where I can say the amount, but if I have to go that route it complicates the development process because we are using only `initPaymentSheet` to collect payments with also Google Pay and Apple Pay.

**Comment by charliecruzan-stripe** [comment]
The amount should be set when you're creating the PaymentIntent (on your server)

**Comment by charliecruzan-stripe** [comment]
Were you approved by Apple in the end @Mihai-github ?

**Comment by marchingband** [comment]
I have this same issue, Apple rejected my app stating I must show:
- Product description and specifications
- Merchant's name on the payment sheet
