### ISSUE TITLE
ld: library not found for -lCocoaAsyncSocket 

### ISSUE THREAD

**Issue by haewhybabs** [stripe/stripe-react-native#795]
**Describe the bug**
Build the project on Xcode returning the following error

ld: library not found for -lCocoaAsyncSocket 

**To Reproduce**

1.Xcode version 12.4
2. Remove the swift content in the library search paths $(inherit)
3. build

2 Pod File
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'siteat' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'siteatTests' do
    inherit! :complete
  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end

**Screenshots**
<img width="1440" alt="Screenshot 2022-02-07 at 11 26 50" src="https://user-images.githubusercontent.com/36129532/152770995-db7119eb-2a8d-4739-887f-e355c7932c8b.png">

**Desktop (please complete the following information):**
 - iOS

**Comment by charliecruzan-stripe** [comment]
Can you elaborate on what & why you're doing when you say:

> Remove the swift content in the library search paths $(inherit)

**Comment by charliecruzan-stripe** [comment]
Looks like you were following this troubleshooting guide: https://github.com/stripe/stripe-react-native#undefined-symbols-for-architecture-x86_64-on-ios (only do that if you run into that error there), I would also make sure you added the Swift file and bridging header mentioned in that troubleshooting section
