### ISSUE TITLE
Wrong type definition for presentGooglePay

### ISSUE THREAD

**Issue by LaVielle** [stripe/stripe-react-native#799]
[The Google Pay docs](https://github.com/stripe/stripe-react-native/blob/master/docs/GooglePay.md#present-google-pay-sheet) for `presentGooglePay` say we can optionally pass the `forSetupIntent` param.
The types look fine if we import presentGooglePay via the hooks (useStripe, useGooglePay), but the types are wrong if we import `presentGooglePay` directly.
Specifically, the params for `presentGooglePay` (in [functions.ts](https://github.com/stripe/stripe-react-native/blob/master/src/functions.ts#L383)) are of type `SetupIntentParams` when they should probably be `PresentGooglePayParams` (all in [GooglePay.ts](https://github.com/stripe/stripe-react-native/blob/master/src/types/GooglePay.ts#L27))

Doing this:
```
await presentGooglePay({
  clientSecret: intent.client_secret,
  forSetupIntent: true,
  currencyCode: 'USD,
})
```
give this TS error:
```
TS2345: Argument of type '{ clientSecret: any; forSetupIntent: boolean; currencyCode: string; }' is not assignable to parameter of type 'SetupIntentParams'.   Object literal may only specify known properties, and 'forSetupIntent' does not exist in type 'SetupIntentParams'.
```

**Comment by charliecruzan-stripe** [comment]
thanks for pointing this out! currently doing an audit of the Typescript definitions here and issues like this are super helpful. We'll have it fixed asap!

**Comment by LaVielle** [comment]
@charliecruzan-stripe Thanks for your enthusiastic reply, that's refreshing 😊

Since we're at it, another improvements to the typings that I would find very useful would be if the `StripeError` interface would be more precise, especially for `stripeErrorCode`.

My use cases are:
- show custom error message based on `stripeErrorCode`
- ignore error logging for some `stripeErrorCode`s

For example, this error returned by `confirmSetupIntent`:
```
{
   "stripeErrorCode":"card_declined",
   "declineCode":"generic_decline",
   "localizedMessage":"Your card was declined",
   "message":"Ihre Karte wurde abgelehnt.",
   "type":"card_error",
   "code":"Failed"
}
```

Here I expect `stripeErrorCode` to be a subset of all the possible errors listed in the [Error codes Docs](https://stripe.com/docs/error-codes) (eg. `amount_too_large` makes no sense for a setup intent).

So it would be very nice if the `StripeError` would accept another generic parameter that would clearly define what values can be expected for `stripeErrorCode` (and other keys too). Now it's just a loose string.
