### ISSUE TITLE
unable to see element if i do not use height property in CardForm

### ISSUE THREAD

**Issue by aliMurtaja** [stripe/stripe-react-native#802]
I want to use CardForm Component in my app.

<CardForm
   onFormComplete={(cardDetails) => {
   console.log('card details', cardDetails);
     setCard(cardDetails);
   }}
   style={{height: 200}}
 />

in Above I am not able to see stripe elements untill and unless provide the height property in style Attrible.

is there any solution that i see the element if i Not provide the height.

**Comment by charliecruzan-stripe** [comment]
Hi! Can I ask why you _don't_ want to provide the height? This is a fairly common practice with UI elements in React Native, I think

**Comment by aliMurtaja** [comment]
I added the button just below the CardForm, and if I select the country for which postal-code required, then this postal-code field doesn't show because of the below button.

is there any solution for that...

**Comment by charliecruzan-stripe** [comment]
Hm, well one option would be to place your components inside of a `ScrollView` so that you can give `CardForm` the appropriate height, or you could use `CardField` which allows you to collect card details on just one line.
