### ISSUE TITLE
All place-holder doesn't show

### ISSUE THREAD

**Issue by aliMurtaja** [stripe/stripe-react-native#808]
I used cardForm component in my app

the problem is that when i switch the app them from light mode to dark, All element will disappear.

is there any solution for that

**Comment by charliecruzan-stripe** [comment]
duplicate of https://github.com/stripe/stripe-react-native/issues/771

**Comment by gauravag23** [comment]
You can check color scheme and set cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}as per light or dark theme.

             <CardForm
                    cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}
                 
                />
