### ISSUE TITLE
CardField always returns generic Card details not complete

### ISSUE THREAD

**Issue by ziga-hvalec** [stripe/stripe-react-native#815]
**Describe the bug**
When using cardField and calling createToken when card number, exp date or cvc are invalid(highlighet in red), createToken always returns message "Card details not complete" and code "Failed". 

**To Reproduce**
1. enter invalid card n umber, exp date or cvc into CardField
2. Call createToken
3. Look at error message

**Expected behavior**
I would expect to receive correct error message for the invalid field(card number, exp date or cvc)

**Screenshots**
<img width="331" alt="Screenshot 2022-02-16 at 13 56 58" src="https://user-images.githubusercontent.com/72733684/154269190-108ab079-bb61-44b1-8b07-68f9071e202e.png">
<img width="795" alt="Screenshot 2022-02-16 at 13 56 18" src="https://user-images.githubusercontent.com/72733684/154269078-2577c03f-f9ec-44b1-97f8-80da06d0b596.png">

**Desktop (please complete the following information):**
 - OS: android and iOS
 - Browser /
 - Version 0.2.4

**Smartphone (please complete the following information):**
 - Device: iPhone 13 simulator, iPhone 8, Google Pixel 6
 - OS: 15.2, 15.2, 12
 - Browser /
 - Version /

**Comment by charliecruzan-stripe** [comment]
The best way to handle this case is to listen to the CardField's `onCardChange` callback, and check:

```
  validExpiryDate: ValidationState;
  validCVC: ValidationState;
  validNumber: ValidationState;
```

Or, you can disable whatever button you have whose onPress triggers `createToken` until the `complete` field in CardField's `onCardChange` callback is `true`. Let me know if that doesn't work for you!
