### ISSUE TITLE
Card element payment issues on android

### ISSUE THREAD

**Issue by Sascha1251** [stripe/stripe-react-native#826]
**Describe the bug**
When using the "stripe-react-native-example" application (https://snack.expo.dev/@charliecruzan/stripe-react-native-example) on android, the WebhookPayment (Card element only) payment does not work. After I enter an email address, the credit card information, and press pay, I get an error with the following information:
"You must provide cardDetails, token or paymentMethodId"

Entering the same information on an iPhone 8 Plus works fine and the payment is successful

**To Reproduce**
1. Open the application in the expo go app
2. Select "Accept a payment"
3. Open "Card element only"
4. Enter an email address, the credit card information e.g. (4242 4242 4242 4242, 08/25, 555)
5. Press pay

**Expected behavior**
I would expect the payment to succeed, without any errors

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 9

**Comment by charliecruzan-stripe** [comment]
That example uses `"@stripe/stripe-react-native": "0.1.1"`, have you tried a newer version?

**Comment by Sascha1251** [comment]
Hey @charliecruzan-stripe,
thanks, I missed checking the version, as it was mentioned in the expo documentation I didn't check the version. A newer version is working fine on android as well. Therefore I'm closing this issue.
