### ISSUE TITLE
Supported payment methods for PaymentSheet

### ISSUE THREAD

**Issue by Sascha1251** [stripe/stripe-react-native#828]
**Describe the bug**
For me, it's not clear whether the payment option "giropay" is supported when using the Payment sheet (if I understand it correctly, in the documentation it's being referred to as "Mobile Payment Element").
In the readme of this project it says: 
"PaymentSheet currently accepts the following payment methods: Card, Apple Pay, Google Pay, SEPA Debit, Bancontact, iDEAL, and Sofort."
However, in the stripe documentation, it lists "giropay" under the Mobile Payment Element as a valid option. (see  https://stripe.com/docs/payments/payment-methods/integration-options#payment-method-product-support) 

Therefore I'm wondering whether it's supported or not.

Thank you for your help.

**Comment by charliecruzan-stripe** [comment]
giropay is indeed supported, we will update the docs as we have a few other payment methods either in the works are already available in the payment sheet!

**Comment by Sascha1251** [comment]
Okay, interesting as I didn't manage to get the option in the payment sheet.
When I add "giropay" to the "payment_method_types" when creating a payment intent, it was not shown in the payment sheet.
I've also enabled it as a payment option in the dashboard.

Maybe it's somehow related to that issue: https://github.com/stripe/stripe-react-native/issues/829
Nevertheless, the payment option was not even shown on android.

**Comment by charliecruzan-stripe** [comment]
Updated here: https://github.com/stripe/stripe-react-native/commit/059caeb4738cd52b21b43204d617ae2f01880823
