### ISSUE TITLE
Add multiline card element

### ISSUE THREAD

**Issue by bg-stripe** [stripe/stripe-react-native#83]
We have a multiline card input element on Android already. 
We will be building a similar multiline element in the iOS SDK in the coming 1-2 weeks. 

When the iOS multiline element is done, we'd like to add React Native bindings for the multiline card element.

**Comment by thorsten-stripe** [comment]
Has been added to `stripe-ios`: https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#2160-2021-05-27

**Comment by bg-stripe** [comment]
also added to `stripe-android`: https://github.com/stripe/stripe-android/commit/d68e386704716574a50eafbe06d935b94721be1c

**Comment by 034502219988** [comment]
@bg-stripe  hi. when will this be released?

**Comment by tgensol** [comment]
@thorsten-stripe, any idea when that could come to RN ? That the main missing feature that prevents me from using stripe-react-native over tipsi-stripe

Thanks ☺️

**Comment by thorsten-stripe** [comment]
This is actively being worked on and we're hoping to release it by the end of the month.

**Comment by 034502219988** [comment]
ok thanks.

**Comment by shabareesh** [comment]
Hello, when will this feature be available?

**Comment by onsah** [comment]
Hello, does this mean we will have split card elements or we will have a combined element with fields separated by lines?

**Comment by vaibhavgadekar** [comment]
> This is actively being worked on and we're hoping to release it by the end of the month.

@thorsten-stripe is this released ??

**Comment by tanloiit2010** [comment]
@bg-stripe @thorsten-stripe I would like to style as below. can I achieve this with CardForm or CardField?
![Screen Shot 2021-08-19 at 19 09 51](https://user-images.githubusercontent.com/5616333/130066544-db48c7bc-26f1-414a-af9f-d4dcf0503cf4.png)

**Comment by smeetagrawal** [comment]
Hi, I am trying to implement CardForm component and I had faced an issue when input fields are getting filled by user.

Packages used 
"react": "16.13.1"
"react-native": "^0.61.4"
"@stripe/stripe-react-native": "^0.2.0"

```
<SafeAreaView style={styles.safeView}>
	<ScrollView>
		<View style={styles.safeView}>
			<View style={styles.cardContainer}>
				<CardForm
					autofocus
					onFormComplete={(cardDetails) => {
						console.log(cardDetails);
					}}
				/>
			</View>
		</View>
	</ScrollView>
</SafeAreaView>
```
*Issue image reference*
[https://putul.io/UrHSJ0gHp](url)

Can you please provide me some solution for this @thorsten-stripe

**Comment by arekkubaczkowski** [comment]
@smeetagrawal please create a separate issue for this

**Comment by smeetagrawal** [comment]
> @smeetagrawal please create a separate issue for this

Ok, created new issue for it and waiting for the feedback and solution, so I can use it in my project.

**Comment by shikhars371** [comment]
> @bg-stripe @thorsten-stripe I would like to style as below. can I achieve this with CardForm or CardField? ![Screen Shot 2021-08-19 at 19 09 51](https://user-images.githubusercontent.com/5616333/130
<img width="635" alt="Screenshot 2022-08-08 at 4 01 13 PM" src="https://user-images.githubusercontent.com/8435048/183398609-6d1dadc5-23bf-45e1-bbdc-72aa837639d0.png">
066544-db48c7bc-26f1-414a-af9f-d4dcf0503cf4.png)

any luck in getting this UI? i cant able to customise the CardField please help

**Comment by dlato97** [comment]
> 

@thorsten-stripe Hi, is there any news about it?

**Comment by avivash** [comment]
Any update on this?
