### ISSUE TITLE
Creating issue only in android 

### ISSUE THREAD

**Issue by yashgoelantiersolutions** [stripe/stripe-react-native#831]
**Describe the bug**
installed 0.3.0 version in react native . in Ios everything working fine . But in android firstly i get issue this 
**/Users/ant-user/.gradle/caches/transforms-3/d8d82bcc80c152fc128bd7e4077e3ce7/transformed/material-1.5.0/res/values-v31/values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found.**

 But after increasing  versions of 30 to 31  
    
    compileSdkVersion = 31
    targetSdkVersion = 31 
    
    
 thats issue fixed and i successfull build the app. 
### **But after this while using InputText of React Native i geeting this issue**

**To Reproduce**
1. install 0.3.0 version and increase sompileSdkVersion and targetSdkVersion to 31 (Beacause without this you will get linking errorsas in screenshot 1st)

 **1st screenshot** 
 
![Screenshot 2022-03-04 at 5 02 06 PM](https://user-images.githubusercontent.com/83455754/156757094-654ec502-22bf-49fe-b78c-753289e1e638.png)

2. After successful installation import InputText in component like this
**import {TextInput} from "react-native";
and use in the design code**

3. You will get error as show in screenshot 2nd 
 
**2nd screeshot**

![image](https://user-images.githubusercontent.com/83455754/156757155-7e4646c8-4b10-4d79-b9b1-aea9153f9905.png)

  "dependencies": {

 ###    **"@stripe/stripe-react-native": "^0.3.0",**

###     **"react-native": "0.67.1",**

**Smartphone (**
 - OS: android

**Comment by yashgoelantiersolutions** [comment]
@charliecruzan-stripe  Please look into this

**Comment by isidoro98** [comment]
@yashgoelantiersolutions  Was facing this same issue yesterday. Find the temporary solution here: https://github.com/facebook/react-native/issues/31572#issuecomment-912017067

React native will 0.68 fix it and allow you to drop the fix, hope this helps :)

**Comment by zuhair-naqvi** [comment]
Wow, I was just about to post the same issue here! thanks @yashgoelantiersolutions  and @isidoro98

**Comment by yashgoelantiersolutions** [comment]
> Wow, I was just about to post the same issue here! thanks @yashgoelantiersolutions and @isidoro98

@zuhair-naqvi  thank you so much for your help

**Comment by isidoro98** [comment]
@yashgoelantiersolutions feel free to close the issue

**Comment by charliecruzan-stripe** [comment]
Confirming that adding the following to your `android/app/build.gradle` (in `dependencies {}`) is a temporary solution for this until RN 0.68 is officially released:

```
    implementation ("androidx.appcompat:appcompat:1.3.1") {
        version {
            strictly '1.3.1'
        }
    }
```

> Note that you can try React Native 0.68 now as a release-candidate has been released
