### ISSUE TITLE
jumping between card input fields in `CardField` component (even after pulling in related changes on master)

### ISSUE THREAD

**Issue by ryndshn** [stripe/stripe-react-native#833]
**Describe the bug**
We're still experiencing field jumping after updating to the most recent version of this project that contains a recent fix for a related issue [here](https://github.com/stripe/stripe-react-native/commit/97b29e5f717679908d7327f8f30d78b787f72bc6). 

**To Reproduce**
1. Add `CardField`
2. Enter CC information and note the cursor jumping from postal code back to CVC (and erasing CVC input)

**Expected behavior**
Shouldn't jump between fields unexpectedly and shouldn't erase CVC

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1

**Smartphone (please complete the following information):**
 - Device: Android TV emulator
 - OS: Android 7.1.1

**Additional context**

https://user-images.githubusercontent.com/10523324/156857175-005b7101-6b19-4178-9e85-dd00b84188fd.mov

**Comment by charliecruzan-stripe** [comment]
hi! So although the fix has landed on `master`, we haven't released a new version yet. However, we'll release a new version this week 👍

**Comment by ryndshn** [comment]
hey!! thanks for your snappy response :)

i spun up a forked version of this repo and built my app off of the new master changes and found the issue still persists.

the attached video is running the code on master.

**Comment by ryndshn** [comment]
this is my experience when running stripe's example app with the component found [here](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/WebhookPaymentScreen.tsx#L81) (but with `postalCodeEnabled`). guessing this means it's dependent on environment--please let me know what details i can provide!!

https://user-images.githubusercontent.com/10523324/157489561-93c24815-1865-4d3f-bc42-282d583a6c26.mov

**Comment by charliecruzan-stripe** [comment]
Can you try this on a more recent Android version, maybe 9 or higher (and also maybe on a Pixel or similar emulator, rather than on Android TV)?
