### ISSUE TITLE
initPaymentSheet params accept payment button label

### ISSUE THREAD

**Issue by TonySchu** [stripe/stripe-react-native#836]
**Is your feature request related to a problem? Please describe.**
The payment sheet button is is labelled: "Pay $xxx". Calling the cta "Pay" is sometimes not applicable (fund, deposit, donate etc.). 

**Describe the solution you'd like**
Accept a string as a param in the initPaymentSheet() method.

Otherwise it is a great module. Thank you

**Comment by TonySchu** [comment]
![Screenshot 2022-03-09 at 11 44 29](https://user-images.githubusercontent.com/19664656/157426647-8681daf6-affe-4cb0-af0b-f0ecc2bd504f.png)

**Comment by ufukhawk** [comment]
same problem

**Comment by charliecruzan-stripe** [comment]
Will be included in the next release :)
