### ISSUE TITLE
Missing state change after re-attempt 3DS failure at Payment Sheet

### ISSUE THREAD

**Issue by thomasyim02** [stripe/stripe-react-native#838]
**Platform and library version**
Tested on Android 10 (Pixel 3XL - simulator), stripe-react-native 0.3.0 & 0.4.0
Tested on Android 12 (Note 10 Plus - real device), stripe-react-native 0.3.0 & 0.4.0

**Describe the bug**
Following the [guide](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-collect-payment-details) and Example App. Tried to test the error handling of Payment Sheet using 3DS test card. 1st error is able to catch, but if user cancel the payment sheet and run openPaymentSheet again, re-attempts 3DS with 2nd failure, the payment sheet will be cancelled even though the payment sheet is still showing on the screen. If the user re-attempts the 3rd time 3DS successfully, the guideline code is unable to trigger a successful confirmation message because the payment sheet is stated as cancelled.

**To Reproduce**
1. Follow every steps on the guide above (initPS, presentPS)
2. Use 3DS test card and click fail authentication on 3DS page. (1st error handling)
3. Close the payment sheet and reopen it.
4. Use 3DS test card again and click fail authentication on 3DS page.
5. The payment sheet console.log as "The payment has been canceled", which it should not.
6. While the payment sheet is still opening, use 3DS test card again with successful authentication.
7. Missing successful confirmation state.

**Same behavior occurs at Example App.**
1. Start with Pre-built UI (Single-Step) 
2. Pay with 3DS Test Card
3. Click Fail Auth 
4. Catched 1st error 
5. Close PaymentSheet
6. Return HomeScreen 
7. Click Pre-built UI (Single-step) again
8. Pay with 3DS Test Card
9. Click Fail Auth
10. Payment Sheet console.error will state as "Cancelled"
11. While the payment sheet is still opening, use 3DS test card again with successful authentication.
12. Missing successful confirmation state.

**Expected behavior**
The error code should not be only used once. Nor the payment session will be cancelled when the Payment Sheet is still opening.

**Comment by charliecruzan-stripe** [comment]
Not able to reproduce this on the latest version, here's a screen recording. Please let me know if I'm missing a step:


https://user-images.githubusercontent.com/97612659/158250092-a1daed10-38ea-417b-903c-89c1193c0ebe.mov

**Comment by thomasyim02** [comment]
@charliecruzan-stripe Android only perhaps? I added console.log('Debug: ', error) at line 40 as shown at the below video to check the behavior behind the scene.


https://user-images.githubusercontent.com/30122971/158287753-9a3a2f7b-7088-461b-b195-f99efad9cfab.mov

**Comment by charliecruzan-stripe** [comment]
Please include in the original issue description all the relevant information, like your platform and library version.

**Comment by thomasyim02** [comment]
@charliecruzan-stripe
So, will this bug be fixed anytime soon?

**Comment by charliecruzan-stripe** [comment]
I haven't had time to dig into this yet unfortunately

**Comment by thomasyim02** [comment]
@charliecruzan-stripe 
This issue is fixed with the latest version. This can be closed now, thanks!
