### ISSUE TITLE
Apple pay of confirmPaymentSheetPayment return unexpected error

### ISSUE THREAD

**Issue by Haven4LivingMenu** [stripe/stripe-react-native#840]
**Describe the bug**
When I use Apple pay to confirm a payment sheet

const { error } = await confirmPaymentSheetPayment();
return error = {
  code: 'Failed',
  message: 'There was an unexpected error -- try again in a few seconds',
  localizedMessage: 'There was an unexpected error -- try again in a few seconds',
  declineCode: null,
  stripeErrorCode: null,
  type: null,
}

**Expected behavior**
Confirm payment sheet payment

**Smartphone (please complete the following information):**
 - Device: iPhone12 Pro
 - OS: iOS 15.2

**Additional context**
use the @stripe/stripe-react-native@0.2.2 (on Expo)

**Comment by Haven4LivingMenu** [comment]
> **Describe the bug** When I use Apple pay to confirm a payment sheet
> 
> const { error } = await confirmPaymentSheetPayment({}); return error = { code: 'Failed', message: 'There was an unexpected error -- try again in a few seconds', localizedMessage: 'There was an unexpected error -- try again in a few seconds', declineCode: null, stripeErrorCode: null, type: null, }
> 
> **Expected behavior** Confirm payment sheet payment
> 
> **Smartphone (please complete the following information):**
> 
> * Device: iPhone12 Pro
> * OS: iOS 15.2
> 
> **Additional context** use the @stripe/stripe-react-native@0.2.2 (on Expo)

**Comment by cubabit** [comment]
I have the same issue. Some hints on what you did to resolve it would be appreciated
