### ISSUE TITLE
error: Error: Unable to resolve module ../../package.json

### ISSUE THREAD

**Issue by marlon07021** [stripe/stripe-react-native#841]
**Describe the bug**
Getting this error after installing the module. Already tried everything from #770  but no success.

```
error: Error: Unable to resolve module ../../package.json from /Users/user/Turix/turix-rn-mobile/node_modules/@stripe/stripe-react-native/lib/commonjs/components/StripeProvider.js: 

None of these files exist:
  * node_modules/@stripe/stripe-react-native/lib/package.json(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs)
  * node_modules/@stripe/stripe-react-native/lib/package.json/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs)
```

**To Reproduce**
1 - create a new typescript react native project.
2 - install stripe module for react native

**Expected behavior**
Normally running

**Dependencies:**
 ```
 "dependencies": {
    "@apollo/client": "^3.5.5",
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-picker/picker": "^2.3.1",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@reduxjs/toolkit": "^1.5.0",
    "@stripe/stripe-react-native": "^0.4.0",
    "@titelmedia/react-apollo-multiple-clients": "^4.0.5",
    "graphql": "^16.0.1",
    "i18n-js": "^3.8.0",
    "intl": "^1.2.5",
    "lodash.memoize": "^4.1.2",
    "moment": "^2.29.1",
    "react": "17.0.2",
    "react-apollo": "^3.1.5",
    "react-native": "0.67.3",
    "react-native-animatable": "^1.3.3",
    "react-native-appearance": "^0.3.4",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-device-info": "^8.0.1",
    "react-native-dotenv": "^3.3.0",
    "react-native-elements": "^3.2.0",
    "react-native-fbsdk": "^3.0.0",
    "react-native-geolocation-service": "^5.3.0-beta.3",
    "react-native-gesture-handler": "^1.10.1",
    "react-native-google-signin": "^2.1.1",
    "react-native-image-picker": "^4.7.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.1.1",
    "react-native-maps": "^0.29.3",
    "react-native-permissions": "^3.1.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^2.17.1",
    "react-native-simple-events": "^1.0.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^8.0.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "rn-range-slider": "^2.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@babel/plugin-transform-typescript": "^7.16.8",
    "@babel/runtime": "^7.17.2",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/jest": "^25.2.3",
    "@types/react-native": "^0.67.2",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-native-fbsdk": "^3.0.2",
    "@types/react-native-snap-carousel": "^3.8.2",
    "@types/react-redux": "^7.1.23",
    "@types/react-test-renderer": "^16.9.2",
    "@types/redux": "^3.6.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.4.2",
    "eslint": "^8.10.0",
    "jest": "^27.5.1",
    "metro-react-native-babel-preset": "^0.69.0",
    "react-test-renderer": "16.13.1",
    "typescript": "^4.6.2"
  },
  ```

**Comment by Kinzito17** [comment]
I am having the same issue and have also tried everything from [770](https://github.com/stripe/stripe-react-native/issues/770) with no solution. Thanks!

**Comment by marlon07021** [comment]
@Kinzito17 I was in the same situation until today, also I did see your stackoverflow.com question.

https://stackoverflow.com/questions/71417350/react-native-x-stripe-integration-error-unable-to-resolve-module-stripepr

(I'm assuming this is you.)

 Maybe this helps.

Go to the file:

/node_modules/@stripe/stripe-react-native/lib/commonjs/components/StripeProvider.js

and modifiy the import from '../../package.json' to '../../../package.json'.

It's not a solution but a workaround. Hope it helps.

**Comment by Kinzito17** [comment]
@marlon07021 thank you! That stopped the error being thrown, were you able to render a payment page at all? 

Yes, that was my SO post, please feel free to add your workaround as an answer I will happily mark it as the answer. Thanks again.

**Comment by marlon07021** [comment]
Yes, actually I was able to render the `CardField` doing it that way.

**Comment by charliecruzan-stripe** [comment]
You shouldn't need to modify the `StripeProvider.js` file directly. I believe this is an issue with your metro configuration. Could you share the contents of `metro.config.js`?

**Comment by marlon07021** [comment]
```js
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const {getDefaultConfig} = require('metro-config');
const {resolver: defaultResolver} = getDefaultConfig.getDefaultValues();

module.exports = {
  resolver: {
    ...defaultResolver,
    sourceExts: [...defaultResolver.sourceExts, 'cjs'],
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};


```

**Comment by charliecruzan-stripe** [comment]
`sourceExts: [...defaultResolver.sourceExts, 'cjs']` why are you adding in the `cjs` extension?

**Comment by marlon07021** [comment]
I'm using Apollo Client for GraphQL

[https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-354-2021-11-19](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-354-2021-11-19)

**Comment by charliecruzan-stripe** [comment]
hm weirdly enough it seems like it's the `...defaultResolver` line that's causing this. I'm able to reproduce with your metro config, but if i just remove `...defaultResolver,`, it works

**Comment by Kinzito17** [comment]
> Yes, actually I was able to render the `CardField` doing it that way.

Thanks, I got it all working with the `init` & `presentPaymentSheet` as well.

**Comment by Kinzito17** [comment]
@charliecruzan-stripe do you know what side effects taking out the `...defaultResolver` may have?

**Comment by marlon07021** [comment]
I will try it that way @charliecruzan-stripe, just don't know yet how much it will affect the rest of the app by removing all the resolver properties.

**Comment by charliecruzan-stripe** [comment]
> do you know what side effects taking out the ...defaultResolver may have?

No, so I wouldn't recommend that. I should've been clearer: this looks like an odd bug with metro to me, because this works:

```
module.exports = {
  // resolver: {
  //   ...defaultResolver,
  // },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

but if you uncomment the resolver, it doesn't. And conceivably, the two configurations should be identical

**Comment by Adrien-D** [comment]
Any update on this issue ? I'm having the same problem adding `cjs` in `sourceExts` due to Apollo client and I'm a little but stuck

**Comment by fdelacruzsoto** [comment]
@charliecruzan-stripe I recently updated to rn 68 and got this error, I got the error even without `...defaultResolver`.

Here is my metro config, I'm planning to remove eva config in a future release, maybe that will help.

```
const MetroConfig = require('@ui-kitten/metro-config');
const { getDefaultConfig } = require('metro-config/src/defaults/defaults');
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();

const evaConfig = {
  evaPackage: '@eva-design/eva',
  // Optional, but may be useful when using mapping customization feature.
  // customMappingPath: './custom-mapping.json',
};

module.exports = MetroConfig.create(evaConfig, {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
});

module.exports.resolver = {
  ...defaultResolver,
  sourceExts: [...defaultResolver.sourceExts, 'cjs'],
};

```

**Comment by byCedric** [comment]
Hi @charliecruzan-stripe 😄 I think this is an unfortunate path issue caused when transpiling this library. In Snack (specifically Snackager) we also have issues bundling this library to a single JS file.

- In [**./src/components/StripeProvider.tsx**](https://github.com/stripe/stripe-react-native/blob/master/src/components/StripeProvider.tsx#L6)
  → The package json is imported using the **../../package.json** path.
  → This looks good because it resolves to the path **./package.json**.

- In [**./lib/module/components/StripeProvider.js**](https://cdn.jsdelivr.net/npm/@stripe/stripe-react-native@latest/lib/module/components/StripeProvider.js)
  → the package json is still imported using the **../../package.json** path
  → _This is not correct because it resolves to the path **./lib/package.json**, and that [does not exist](https://cdn.jsdelivr.net/npm/@stripe/stripe-react-native@latest/lib/package.json)_
  → It's caused because the transpiled files have a deeper folder structure as opposed to the normal source files.

So technically speaking, the transpiled **StripeProvider.tsx** is importing a non-existing file. either copying the `package.json` to **./lib/package.json**, or updating this path when transpiling should fix this.

Hope this helps ❤️😁
