### ISSUE TITLE
Addition to GooglePay.md

### ISSUE THREAD

**Issue by sheldoncoates** [stripe/stripe-react-native#850]
I would change this myself but I'm not able to contribute to the codebase.

In the Google Pay setup documentation can you add a link to the following [set up guide](https://developers.google.com/pay/api/android/guides/setup)? I was running into issues where `isGooglePaySupported()` would always return false and it was because I didn't have the setup described in that link completed.

I think it will make future devs lives easier with it added.

**Comment by charliecruzan-stripe** [comment]
done in https://github.com/stripe/stripe-react-native/commit/730d850d0d25e0df9e1d4e67d89333836560d3f2, thanks for making an issue for this!
