### ISSUE TITLE
Camera doesn't close on iOS if you try to scan card the close the payment sheet without completing the scan.

### ISSUE THREAD

**Issue by ahmadworks** [stripe/stripe-react-native#865]
- On iOS, Open payment sheet
- Go to add new card
- Tap on Scan card to open camera view
- Don't scan a card and tap anywhere to close the payment sheet
- Now you will keep seeing camera indicator visible on your iPhone.

- Repeat the steps again but now close the camera window before closing the sheet and everything will work fine.

**Comment by charliecruzan-stripe** [comment]
Hi! We think this will require a fix to `stripe-ios`, but I'll keep this open just to track

**Comment by charliecruzan-stripe** [comment]
this was fixed in https://github.com/stripe/stripe-ios/commit/c2437b39ad29062cd5201a405a536e95c08c14fe 😄
