### ISSUE TITLE
 isGooglePaySupported throws IllegalStateException

### ISSUE THREAD

**Issue by pavelbely** [stripe/stripe-react-native#866]
**Describe the bug**
 isGooglePaySupported throws `IllegalStateException: Can not perform this action after onSaveInstanceState`

**To Reproduce**
```
<..>
useEffect(() => {
    async function initialize() {
      if (!(await isGooglePaySupported())) {
        console.warn('Google Pay is not supported.');
        return;
      }

      const { error } = await initGooglePay(config);
      if (error) {
        setInitialized(false);
        return;
      }
      setInitialized(true);
    }
    initialize();
  }, [initGooglePay]);
```

produces
```
androidx.fragment.app.n1 in n at line 2
androidx.fragment.app.n1 in W at line 5
androidx.fragment.app.d in z at line 12
androidx.fragment.app.d in h at line 1
com.reactnativestripesdk.StripeSdkModule in isGooglePaySupported at line 8
java.lang.reflect.Method in invoke
com.facebook.react.bridge.JavaMethodWrapper in invoke at line 18
com.facebook.react.bridge.JavaModuleWrapper in invoke at line 2
com.facebook.react.bridge.queue.NativeRunnable in run
android.os.Handler in handleCallback at line 883
android.os.Handler in dispatchMessage at line 100
com.facebook.react.bridge.queue.MessageQueueThreadHandler in dispatchMessage at line 1
android.os.Looper in loop at line 237
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4 in run at line 8
java.lang.Thread in run at line 919
```

**Smartphone:**
 - Device: Samsung SM-G960U
 - OS: Android 10
 - React Native: 0.65.1
 - Stripe-react-native: 0.3.0

**Comment by charliecruzan-stripe** [comment]
Can you provide a full reproducible demo? We have this same code in our example app and it's not throwing any error for me.

**Comment by perle-rare** [comment]
Hi @charliecruzan-stripe , for me , instead of throwingan exception, it's always returing false and show Alert (Google Pay is not supported) , even for a device with GPay Configured (Note : this same device is working for google py bia Browser)
Any help please ?
Thanks

**Comment by charliecruzan-stripe** [comment]
Yes, I would add breakpoints [here](https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/GooglePayPaymentMethodLauncherFragment.kt#L38) and see if you can see why Google is saying your device doesn't support it.

**Comment by pavelbely** [comment]
@charliecruzan-stripe unfortunately I can't reproduce it.

But I confirm it happens every day to some of our users, I can see this exception in our error logs.

**Comment by perle-rare** [comment]
hi @charliecruzan-stripe , I just add-it based on stripe documentation, and Also I added 
```
dependencies {
  implementation 'com.google.android.gms:play-services-wallet:18.1.3'
}
```
Testing now, and getting back tou asap , 
Thanks

**Comment by charliecruzan-stripe** [comment]
Sure thing, I'm updating the React Native docs to include this now 👍

**Comment by antoinerousseau** [comment]
This is missing in the React Native instructions of the docs :)
https://stripe.com/docs/google-pay?platform=react-native#react-native-setup

**Comment by charliecruzan-stripe** [comment]
It's removed from the docs, as I mentioned above, it shouldn't be necessary with the current version of stripe-react-native, but let me know if that isn't the case for you!

**Comment by antoinerousseau** [comment]
@charliecruzan-stripe I was able to remove the dependency implementation (unnecessary), but this line was needed in `AndroidManifest.xml`. It doesn't work without it.
```xml
<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
```

**Comment by charliecruzan-stripe** [comment]
Please see https://github.com/stripe/stripe-react-native/issues/730
