### ISSUE TITLE
Handle PII token creation on createToken 

### ISSUE THREAD

**Issue by tfaieta** [stripe/stripe-react-native#878]
**Is your feature request related to a problem? Please describe.**
We would like to be able to create a PII token 

**Describe the solution you'd like**
Add and handle the case for creating a PII token similarly like it has been done for `BankAccount` and `Card`: https://github.com/stripe/stripe-react-native/blob/e2d0a08f432c6e564a4eba16aca282fcc660f1db/ios/StripeSdk.swift#L567-L586

**Describe alternatives you've considered**
iOS SDK has the method implemented so it seems doable? We were curious of if there were plans to add it in or if there were issues around it but couldn't find much related: 
https://github.com/stripe/stripe-ios/blob/3fdd5cb4ac44f651d7cc8ee31e4406806f37effa/Stripe/STPAPIClient%2BPayments.swift#L103-L121

**Additional context**
Thanks for all the work you all do in providing this library to us developers! 👍 🥳

**Comment by tfaieta** [comment]
Just commenting to see if I can get a pulse, I get if this is not going to be worked on or is not doable, just let me know 👍

**Comment by tfaieta** [comment]
@charliecruzan-stripe Any thoughts? Sorry for the direct mention, I'd be open to getting this moving in a PR sometime soon if that sounds good. Just need some direction on if my thinking is correct.

**Comment by charliecruzan-stripe** [comment]
hi @tfaieta , sorry I should've added context here! Got a WIP branch, it's a fairly small change, just got sidetracked since then and haven't picked it back up. I should have a PR up and merged soon

**Comment by tfaieta** [comment]
Thanks so much for the response and looking forward to seeing that 👍
