### ISSUE TITLE
Google Pay Error on Expo. Works well on website not on android.

### ISSUE THREAD

**Issue by Anan7Codes** [stripe/stripe-react-native#880]
I'm getting a request failed, an unexpected error has occured. Please try again later. [OR_BIBED_07] error when I try to pay using google pay on my android app. Card payment works well. Apple pay works well. Gpay works well on my website.

I'm using payment sheets on my expo app.

I'm passing the right paymentSheets parameters.
```
const res = await initPaymentSheet({
                customerId: customer,
                customerEphemeralKeySecret: ephemeralKey,
                paymentIntentClientSecret: paymentIntent,
                applePay: true,
                googlePay: true,
                merchantCountryCode: 'AE',
                merchantDisplayName: "***",
                customFlow: false,
                style: 'alwaysDark',
                testEnv: false
            });
```

I've set my plugins in my app.json file.
```
"plugins": [
      [
        "@stripe/stripe-react-native",
        {
          "merchantIdentifier": "merchant.com.***,
          "enableGooglePay": true
        }
      ]
    ]
```

Am I missing something else?

**Comment by charliecruzan-stripe** [comment]
Can you share the full error object, and the version of this library that you're using?

**Comment by Anan7Codes** [comment]
> Can you share the full error object, and the version of this library that you're using?

I'm using version 0.2.3 & I can't find anything under logs on my dashboard though. I'm only listening to paymentIntents succeeded and charges succeeded events right now for my webhooks. Should I add in the failed once too to get the full error object?

**Comment by charliecruzan-stripe** [comment]
`initPaymentSheet` resolves with an object containing
```
    {
      paymentOption: some object;
      error: some object;
    };
```

So what is the `error`?

**Comment by Anan7Codes** [comment]
> `initPaymentSheet` resolves with an object containing
> 
> ```
>     {
>       paymentOption: some object;
>       error: some object;
>     };
> ```
> 
> So what is the `error`?

This is the the log that I'm getting 

```
Object {
  "paymentOption": undefined,
}
```

**Comment by Anan7Codes** [comment]
> `initPaymentSheet` resolves with an object containing
> 
> ```
>     {
>       paymentOption: some object;
>       error: some object;
>     };
> ```
> 
> So what is the `error`?

This is actually the response that I'm getting :/

Object {
  "paymentOption": undefined,
}

**Comment by charliecruzan-stripe** [comment]
can you run `adb -d logcat -s WalletMerchantError` while going through the flow that triggers the error? that might show us more info

Make sure you're passing a `merchantId` that is valid and has been approved in [Google Pay's Business Console](https://pay.google.com/business/console)

**Comment by Anan7Codes** [comment]
> can you run `adb -d logcat -s WalletMerchantError` while going through the flow that triggers the error? that might show us more info
> 
> Make sure you're passing a `merchantId` that is valid and has been approved in [Google Pay's Business Console](https://pay.google.com/business/console)

Oh no I haven't done the business console step. Wasn't aware of it. Let me do that. Sorry & thank you!

**Comment by charliecruzan-stripe** [comment]
Gotchya, yeah that is what would cause this error for sure. I'm going to close this for now but let me know if that doesn't fix it!

**Comment by jvgaeta** [comment]
@charliecruzan-stripe where do I pass the google merchant id? 

In the expo docs, it states merchantIdentifier is ios only: `merchantIdentifier: iOS only. This is the Apple merchant ID obtained [here](https://stripe.com/docs/apple-pay?platform=react-native). Otherwise, Apple Pay will not work as expected. If you have multiple merchantIdentifiers, you can set them in an array.`

https://stripe.com/docs/google-pay?platform=react-native only mentions merchantIdentifier in the context of apple pay.

**Comment by rishabh-khurana** [comment]
Hey @charliecruzan-stripe  I am facing a similar issue. I can't see any error and my business profile is approved to I need to request access for google api as well ?

![Screen Shot 2022-06-10 at 12 45 45 pm](https://user-images.githubusercontent.com/25672349/172980155-19b21374-1b5e-4dc1-af0a-7068d1db647e.png)

**Comment by CFerndp** [comment]
I had my Business profile and the Google Pay API integration configured as well and suffering the same issue. Any thoughts about this?

**Comment by CFerndp** [comment]
I solved this issue adding the Google Merchant ID. Based on the SDK docs, it's not necessary, but now it's working....
```
initStripe({
      publishableKey: STRIPE_KEY,
      merchantIdentifier: isIos() ? APPLE_MERCHANT_ID : GOOGLE_MERCHANT_ID,
    });
```

**Comment by rishabh-khurana** [comment]
Thanks for your help @CFerndp and @charliecruzan-stripe , I have added the merchant identifier and specified a width and height on the <GooglePayButton />  selector. The button is rendering now, but if I click on the button it gives the following error `Request Failed. An unexpected error has occurred.. Please try again later. [OR_BIBED_07]`

My google pay payments api request is still not approved. Maybe that is what is causing it ?

**Comment by samjayhk** [comment]
Hello @charliecruzan-stripe @CFerndp,

I can confirm both of Google Pay business profile and Google Pay API was approved by the Google Pay teams, and the payment work on Production APK but not Google Play version (Download from Google Play instead of installed by APK). Does anyone know what the problem going on? Thanks!

`[OR_BIBED_07]`
`2022-08-08 10:20:31.013 8999-21249/? E/Volley: [891] dbl.b: Unexpected response code 500 for https://payments-pa.googleapis.com/payments/apis-secure/ui2/buyflowservice/initialize`

**Comment by charliecruzan-stripe** [comment]
@samjayhk please take a look at https://github.com/stripe/stripe-react-native/issues/730, it covers that error code
