### ISSUE TITLE
Is there back support for Charges api?

### ISSUE THREAD

**Issue by ericpolkadoc** [stripe/stripe-react-native#883]
Hi,

We've rewritten our app in React Native, but our server-side APIs are still using the Stripe Charges API.

Is there an older version of stripe-react-native available that works with the Charges api that we can use until our server's apis can be updated?

Thanks!

**Comment by charliecruzan-stripe** [comment]
Unfortunately there is no support for Charges (even on older versions of stripe-react-native), so you would have to move over to the [payments API](https://stripe.com/docs/payments)

**Comment by ericpolkadoc** [comment]
ok thank you for clarifying!
