### ISSUE TITLE
iOS build failed even after removing swift entries like the documentation

### ISSUE THREAD

**Issue by SeongwoonHong** [stripe/stripe-react-native#884]
**Describe the bug**
I'm unable to build the project However, without this library it works fine. I even followed what's mentioned in Trouble shooting section in README but no luck so far.

**To Reproduce**
Run `npx react-native run-ios`
or build on Xcode

**Expected behavior**
Being able to build without any errors when I do `npx react-native run-ios` or on Xcode

**Screenshots**
I've removed all the swift related entries as per README

![Screen Shot 2022-04-12 at 5 22 32 PM](https://user-images.githubusercontent.com/19713918/163056807-17e96f42-aed0-4a9f-90d2-1efb4ab73c9c.png)
![Screen Shot 2022-04-12 at 5 22 41 PM](https://user-images.githubusercontent.com/19713918/163056817-ab1c3a26-82af-4cc8-af5f-005676e90791.png)

I even tried creating multiple swift files as nothing worked but even with one file, it didn't work
![Screen Shot 2022-04-12 at 5 22 55 PM](https://user-images.githubusercontent.com/19713918/163056874-b5667988-b9d9-4490-95f9-29f5a3759f04.png)

![Screen Shot 2022-04-12 at 6 20 44 PM](https://user-images.githubusercontent.com/19713918/163064350-fa976728-19b3-43aa-bf90-d24e5522540f.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Xcode: 13.3.1 (13E500a)
 - React-Native :  0.66.4

Since this is a private repository, please understand me not being able to share my project.

**Comment by charliecruzan-stripe** [comment]
Please provide a reproducible demo, the versions of stripe-react-native & react-native make a big difference. Also, make sure you've checked other issues on the same topic and the fixes shared there (like this one- https://github.com/stripe/stripe-react-native/issues/721#issuecomment-1097491100)
