### ISSUE TITLE
Is there a way to link a credit card to a customer?

### ISSUE THREAD

**Issue by mariovillamizar** [stripe/stripe-react-native#885]
Sorry in advance, I'm new using stripe. I'm trying to figure out how this library works. What I'm trying to do from my app is allow to add credit cards to the users, so there is a screen to list the credit cards and another one to add credit cards.
So what I have done so far is create a payment method using the CardField + createPaymentMethod. (Talking about the CardField it's looking black in my app).

![Screen Shot 2022-04-13 at 12 08 02 AM](https://user-images.githubusercontent.com/10704258/163104500-ba30a57b-45ec-460f-8f1a-e143a00eb919.png)

However I haven't been able to find a way to link the created payment method to a specific stripe customer. So, is it possible?... or should I use this library together with the Stripe Node library? I found a this https://stripe.com/docs/api/payment_methods/attach, so once created the payment method with this library should I call the function of the Stripe Node library?
And then, how can I list those credit cards?

So, is this library intended to work together with the Stripe Node library, or I'm doing everything wrong?

Thank you! 😬

**Comment by charliecruzan-stripe** [comment]
> is this library intended to work together with the Stripe Node library

Yes, our example app uses the Stripe node library :) 

You can either use the Stripe node library to attach the payment method (using the link you shared), or the `confirmSetupIntent` method from `stripe-react-native`. Here's our example screen which collects card details, and attaches them to a customer and makes it ready to be charged in the future: https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/SetupFuturePaymentScreen.tsx
