### ISSUE TITLE
Get error ``Card details not complete`` when trying to use ``confirmSetupIntent``

### ISSUE THREAD

**Issue by usamaabutt** [stripe/stripe-react-native#886]
**Card details not complete**
I have a scenario in which I am using my custom design for collecting card details from users and after getting card data I want to setupIntent for future use.
FYI: I am not using ``CardField`` component. I have the total customized self-design.

**To Reproduce**
1. Install and set it up for Android
2. Get setupIntent key from backend
3. Passing setupIntent and billingDetails to the `confirmSetupIntent` function.
4. See error on console Card details not complete

**Expected behavior**
It should returns setupIntent details.

**Verions**
``"react-native": "0.67.4",``
``"@stripe/stripe-react-native": "^0.6.0",``

**Code snippet**
```
const billingDetails: BillingDetails = {
        email: 'fakeemail@gmail.com',
        name: 'Test',
        phone: '03077633011',
        address: {
          city: 'lahore',
          county: 'pakistan',
          line1: '326 A2 block',
          line2: 'Johar town',
          postalCode: '54700',
          state: 'punjab',
        },
      };
      // Confirm the payment with the card details
      const {setupIntent, error} = await confirmSetupIntent(
        setupIntent,
        {
          type: 'Card',
          billingDetails,
        },
      );
```

**Error response**

```
{
   code: "Failed"
   declineCode: null
   localizedMessage: "Card details not complete"
   message: "Card details not complete"
   stripeErrorCode: null
   type: null
}
```

**Comment by usamaabutt** [comment]
@christopherb-stripe @akerr-stripe @fractalframing anyone can assist here. Thank in advance!

**Comment by charliecruzan-stripe** [comment]
hi- so you're handling the card details directly in your own UI? If that's the case, you're taking on a lot more responsibility when it comes to PCI compliance ([see here for more info](https://stripe.com/docs/security/guide))

But this is true, we don't currently expose that option via `confirmSetupIntent` or `confirmPayment`

**Comment by usamaabutt** [comment]
Thanks, @charliecruzan-stripe for your reply. So, there is no way to use my own custom UI with stripe hooks? 

And

Yes, I have also checked in the package files `useConfirmSetupIntent.d.ts`, `SetupIntent.d.ts` and found for ``type: 'card'`` there is extend interface ``BaseParams`` which is not having card details fields and just has these types for ``billing details``.

```
interface BillingDetails {
        email?: string;
        phone?: string;
        name?: string;
        address?: Address;
    }
    interface Address {
        city: string;
        county: string;
        line1: string;
        line2: string;
        postalCode: string;
        state: string;
    }
```
But the strange thing is using these props it's still not working.

**Comment by charliecruzan-stripe** [comment]
I just want to clarify- you are okay with taking on the responsibility of ensuring PCI compliance?

the billing detail params are all that's required if you make use of the `CardField` or `CardForm` components

**Comment by usamaabutt** [comment]
If yes @charliecruzan-stripe - then what is the way of using customized own UI for collecting card details and setupIntent for future payments?

**Comment by charliecruzan-stripe** [comment]
There isn't one right now, like I said above,we don't currently expose that option via confirmSetupIntent or confirmPayment. There hasn't been much interest in that so far since the cost of taking on your own PCI compliance is a large hurdle. What about the `CardField` or `CardForm` components doesn't fit your use case?

**Comment by usamaabutt** [comment]
Thanks, @charliecruzan-stripe for making it that it's not possible for now to use the Stripe for your own custom design. Because the package has not exposed the card fields for stripe hooks.

**Solution:**
So, I have used the **CardField** component in my custom design screen, and FYI folks who are still not clear how it works with the **CardField** component. Actually, stripe hooks are working under the hood with the **CardField** component you just need to fill the fields for the card number, expiry, and CVC, call the hook and the hook will get these details under the hood. And it works like a charm.

**Comment by charliecruzan-stripe** [comment]
That's correct, if you use the `CardField` component, you can do this quite easily :)

**Comment by tthongprasert** [comment]
Hi again @charliecruzan-stripe 

I use the `CardField` to collect the card details. When I called `confirmSetupIntent`, it returned an error `"Card details not complete"`. What is the problem?


"expo": "~46.0.9"
"@stripe/stripe-react-native": "0.13.1"

**Comment by arun057** [comment]
To everyone who is stuck with this issue, DO NOT dispose (close) of the card field until the payment is confirmed.

**Comment by hafizusman2** [comment]
@arun057 @tthongprasert is your isse get resolved?

**Comment by sergiokano** [comment]
I have the same issue

**Comment by khiemk31** [comment]
same issue. :( 
![image](https://github.com/stripe/stripe-react-native/assets/69030018/411c38b3-1aa0-4ea6-926c-4e542634fbc1)
