### ISSUE TITLE
Set up future payments | Payment sheet does not update default payment method.

### ISSUE THREAD

**Issue by parkerbo** [stripe/stripe-react-native#888]
### Issue Details:
- I have an app where I have a subscription service. I want users to have multiple payment methods available. 
- Using the payment sheet works well. If a user adds a new card, it attaches that payment method to their account. 
- However, when a user then successfully adds their card (or selects an existing stored card) for future payment, it does NOT update the card to be the default option.

**I feel like this  should be possible, to make the most recent payment method (added or selected) to become the default method in the account.**

Any suggested action to find a resolution to this? I feel I am missing something..... Thanks!

**Comment by charliecruzan-stripe** [comment]
Hi! could you provide a couple more details around what you're trying to do? 

I'm assuming you're using `SetupIntents` here, and when using the payment sheet, it _does_ assign the payment method correctly. But then you'd like that payment method as the default method shown in the Payment Sheet UI?

**Comment by parkerbo** [comment]
@charliecruzan-stripe Hey Charlie, thanks for reaching out.

I am using PaymentSheet to capture users card information and store it in their account. I am not charging them, so yes like you mentioned I am using a setup intent.

I think my main question here is - Can I configure the setup intent to make the payment method created be the new default payment method for the attached customer? 

Example:
- User has 2 cards associated with account
- User adds new payment method using payment sheet
- Desired result: new payment method added immediately becomes that users default payment method.

**Comment by adrien-may** [comment]
I had the feeling the newly added card was set as default. I need to double check this then. @parkerbo Did you find a workaround ?

Also, if you want to attach the payment_method on a subscription (when it succeed), did you know you can use somethink like that on your backend ?  

```typescript
    const subscription = await stripe.subscriptions.create({
      // ...
      payment_settings: {
        save_default_payment_method: 'on_subscription',
      },
      / ....
    });
```

I don't know if this answers partially your question. Note that you need to be on latest stripe version, types has been added quite recently.

**Comment by charliecruzan-stripe** [comment]
The concept of a "default payment method" only really exists in terms of subscriptions, so @adrien-may is correct in suggesting the usage of `save_default_payment_method` on the server-side :) Going to close this issue

**Comment by parkerbo** [comment]
Thanks all. My desired result here was a payment method becomes default immediately when it gets added to a customer account. 

I just opted for sending an API request to change the customer's default method, I was just seeing if it was possible to not have that extra step (in my case the card isn't being added via a subscription, but via a SetupIntent)

**Comment by adrien-may** [comment]
@parkerbo What about using a webhook once your newly added card is attached to your customer ?

**Comment by keshavsharma0712** [comment]
@parkerbo Hi, can you please share the API you used for making it default.

**Comment by internetammo** [comment]
this flow is broken stripe, you need to extend the setupintent to allow for adding the payment method as the primary default payment method upon saving. There is currently a huge hassle the only ways I see are to use webhooks to then set this as default after saving or have a hack check and update to do so before create the subscription intent as subscriptions are requiring a default payment. Additionally it would be a good improvement to extend the subscription to allow for creating and saving the default payment in this process or simply not requiring a default payment for the customer and only for the subscription (this is the fastest solution to simplifying the process for integrations)

**Comment by parkerbo** [comment]
@keshavsharma0712 Sorry for late reply. You can update default payment method by updating the Stripe customer. 
See [here](https://stripe.com/docs/api/customers/update#update_customer-invoice_settings-default_payment_method)

Small code snippet example:

`stripe.customers.update(customerId, {
					invoice_settings: {
						default_payment_method: paymentMethodId,
					},
					expand: ["invoice_settings.default_payment_method"],
				}),`

**Comment by keshavsharma0712** [comment]
@parkerbo Hi, I am integrating payment sheet, how do you get the payment method ID from payment sheet. or how are you setting card as default.
