### ISSUE TITLE
Inconsistency between Android and iOS on validation state for CardField

### ISSUE THREAD

**Issue by giorgiofellipe** [stripe/stripe-react-native#895]
**Describe the bug**
There is a inconsistency on validation state for CardField (state control which was added by https://github.com/stripe/stripe-react-native/pull/629).
You can see below what I got on `onCardChange` after typing only the first card number:

iOS:
```
{
   "brand":"Visa",
   "complete":false,
   "expiryMonth":null,
   "expiryYear":null,
   "last4":"",
   "validCVC":"Incomplete",
   "validExpiryDate":"Incomplete",
   "validNumber":"Incomplete"
}
```

Android:
```
{
   "brand":null,
   "complete":false,
   "expiryMonth":null,
   "expiryYear":null,
   "last4":null,
   "validCVC":"Invalid",
   "validExpiryDate":"Invalid",
   "validNumber":"Invalid"
}
```

**To Reproduce**
1. Setup a screen with a CardField
2. Type just the first digit of card number
3. Log what you receive on `onCardChange`

Do it for both platforms and check results.

**Expected behavior**
All platforms should handle the state equally

**Comment by AleCatSS** [comment]
Hello,

Is this ticket still active? It's marked as closed and merged but labelled 'in progress'.

In any case, I can still see an inconsistency between iOS and Android on the brand name:
iOS
`{"brand": "Visa", "complete": false, "expiryMonth": null, "expiryYear": null, "last4": "", "validCVC": "Incomplete", "validExpiryDate": "Incomplete", "validNumber": "Incomplete"}`
Android
`{"brand": "", "complete": false, "expiryMonth": null, "expiryYear": null, "last4": "", "validCVC": "Incomplete", "validExpiryDate": "Incomplete", "validNumber": "Incomplete"}`

I tested on 0.12.0 and 0.13.1.

Thank you

**Comment by wazirkhan786** [comment]
If you are using latest version of stripe-react-native then please add prop to CardField postalCodeEnabled={true} for android and false for ios . It will solve the issue
