### ISSUE TITLE
Google Pay Button Not rendering due to UIManager issue using React Native

### ISSUE THREAD

**Issue by dallascaro** [stripe/stripe-react-native#897]
**Describe the bug**
When I insert the ApplePayButton feature in my react native code using this library it renders on the screen to use. However when I attempt to do the same for the GooglePayButton in my react native code "I have the code running on a MacBook using an iphone emulator rendering as well as my windows 11 machine with an emulator running for android" I receive an error immediately the same one every time upon trying to insert the component.  This is error is as follows: "Render Error requireNativeComponent: "GooglePayButton" was not found in the UIManager. 

**To Reproduce**
1. Install library 
2. import GooglePayButton component
3. Insert GooglePayButton component in the rendering

**Expected behavior**
A rectangular Google Pay Button showing the GooglePay logo

**Screenshots**
![importingGooglePay](https://user-images.githubusercontent.com/56410151/164114757-8ac6a43f-f775-482e-8b25-c7778e8d8f8b.png)
![GooglePayButtonTag](https://user-images.githubusercontent.com/56410151/164114773-539d4fd1-5d1f-4cbe-ba20-846f0bab4631.png)
![googlePayButtonError](https://user-images.githubusercontent.com/56410151/164114779-0708c7ee-9283-4d73-9c70-261b6234b9eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsft Edge
 - Version 

**Smartphone (please complete the following information):**
 - Device: Galaxy S20, Pixel 4
 - OS: Android 12
 - Browser expo app
 - Version 

**Additional context**
Im attempted to google search this on forms or github forms, even went through this libraries issues to see if others have had a problem. Don't fully understand the problem that well, so it very well could be I need to do something on my end to get it working, however ive stuggled to make that work. I don't want to be a bother, just need to know if I should put more time into trying to get this working or move on for other payment options. 

Thank you for taking the time to respond and try to help.

**Comment by charliecruzan-stripe** [comment]
Hi! Unfortunately, Google Pay is not supported inside of the Expo app, see Expo's docs [here](https://docs.expo.dev/versions/latest/sdk/stripe/#google-pay)
