### ISSUE TITLE
Preventing adding duplicate payment method

### ISSUE THREAD

**Issue by ebo7** [stripe/stripe-react-native#899]
**Describe the bug**
I've added a card previously using the payment sheet and when I add the same card with same billing details through the payment sheet again, it doesn't recognize it's duplicate and adds it as  a new payment method.

**Steps to reproduce the behavior**:
1. Open payment sheet through presentPaymentSheet,
2. Add the same card twice with same billing details

**Expected behavior**
The duplicate card should be detected and not added as new payment method

**Smartphone (please complete the following information):**
 - Device: [iPhone 8]
 - Platform Version: [14.5]
 - @stripe/stripe-react-native- 0.2.3

**Comment by charliecruzan-stripe** [comment]
This should be fixed on more recent versions of `@stripe/stripe-react-native` 😃 I would suggest trying at least v0.6.0. 

Related- https://github.com/stripe/stripe-react-native/issues/693

**Comment by ebo7** [comment]
@charliecruzan-stripe

**Comment by charliecruzan-stripe** [comment]
Yes you can install later versions on EAS Build

**Comment by ebo7** [comment]
sorry, 1 more question. I forgot to mention using expo's `managed work flow` with the eas build. Can the later versions be installed?

**Comment by charliecruzan-stripe** [comment]
You should be able to, as long as you use EAS. you cannot install later versions in Expo Go

**Comment by ebo7** [comment]
Seems I can reproduce this issue on 0.70
![Simulator Screen Shot - iPhone 8 - 2022-04-20 at 15 25 58](https://user-images.githubusercontent.com/46511714/164316816-a3b550c6-e11a-40de-9681-686e8aa973d0.png)

**Comment by charliecruzan-stripe** [comment]
How did you test it? By building with `eas build`? When submitting a bug report, it's best to include as much information as possible so that we can reproduce the issue ourselves.

**Comment by ebo7** [comment]
Hello, I built with eas build and still happening

**Comment by charliecruzan-stripe** [comment]
Was able to repro this, as well, thanks for the issue! 

After looking into it some more, it seems like this is expected. It is preventable on the server (see issues below) for now, but we do have it backlogged to fix this in the payment sheet. However, that will require fixes to the underlying native libraries, not `stripe-react-native`. Sorry for the confusion @ebo7 !

See also:
- https://github.com/stripe/stripe-android/issues/427
- https://github.com/stripe-archive/stripe-payments-demo/issues/45

**Comment by aashis-bss** [comment]
how to save card for future use ?

**Comment by charliecruzan-stripe** [comment]
@aashis-bss https://stripe.com/docs/payments/save-and-reuse?platform=react-native&ui=payment-sheet
