### ISSUE TITLE
Add Google Pay for Android

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe/stripe-react-native#9]
Add Google Pay support for Android similar to how Apple Pay is supported for iOS.

https://stripe.com/docs/google-pay

And add a guide similar to https://github.com/stripe/stripe-react-native/blob/master/docs/apple-pay.md

**Comment by konstantinmv** [comment]
Hi all, thanks for your magnificent work for the react-native community!

A question though - do you have any kind of forecast as to when this library will support Google Pay in the same way it supports Apple Pay? 
I've read all the comments and related issues and still haven't understood that part. 
Thanks in advance!

**Comment by thorsten-stripe** [comment]
@konstantinmv were waiting on some required updates in the `stripe-android` SDK which should land by the end of the months and will then work on incorporating it early next month.

**Comment by cinnabarcaracal** [comment]
I would also like to thank you for all the hard work that has gone into this library, and for stepping up to take over the languishing RN Stripe integration space.

We've just finished reworking and upgrading our server, web and app payments processes - which this library has been a major component of.

To my knowledge this is the only outstanding item that is holding us back from releasing new versions of our apps (it's proving to be a bit of a hard sell to our clients that they will loose a payment method during the upgrade, even just temporarily and despite how excited they are for 3DS). We're very excited to release once this final piece comes together

**Comment by jaaywags** [comment]
Any update on this feature as it has been over a month? Thanks :)

**Comment by mshafrir-stripe** [comment]
> Any update on this feature as it has been over a month? Thanks :)

Thanks for checking in. We're planning to release [Stripe Android SDK v17.0.0](https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md#1700---unreleased) tomorrow, which will include `GooglePayLauncher`. `stripe-react-native` will integrate with this release version to offer Google Pay support.

**Comment by jaaywags** [comment]
> > Any update on this feature as it has been over a month? Thanks :)
> 
> Thanks for checking in. We're planning to release [Stripe Android SDK v17.0.0](https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md#1700---unreleased) tomorrow, which will include `GooglePayLauncher`. `stripe-react-native` will integrate with this release version to offer Google Pay support.

That's great! Thank you so much @mshafrir-stripe this  package has been great so far. I've been migrating from tipsi to this the past week and so far everything has been fairly easy to switch over. Y'all did great 😁

**Comment by thorsten-stripe** [comment]
* upgrade stripe-android to https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md#1700---2021-07-15
* docs here: https://stripe.com/docs/google-pay and example here: https://github.com/stripe/stripe-android/blob/master/example/src/main/java/com/stripe/example/activity/GooglePayLauncherIntegrationActivity.kt

**Comment by trex-quo** [comment]
So native Google Pay support (in the same way that Apple Pay is currently supported) will be added in the next version release?
