### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by Hari-krish-v** [stripe/stripe-react-native#905]
Showing Manifest merger failed : Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined
When I add `android:exported` in main>AndroidManifest.xml file then also showing the same error.
Below are the version I used in my project 
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"

**Comment by professorkolik** [comment]
I'm pretty sure you have other dependencies which missing adroid:exported attribute
Had the same problem, check you manifest merger in Android Studio, may be you'll be pointed to the packages which is causing this

**Comment by charliecruzan-stripe** [comment]
Make sure you added it in the [right location](https://github.com/stripe/stripe-react-native/blob/master/example/android/app/src/main/AndroidManifest.xml#L23), I don't think this is a bug with stripe react native so I'm going to close this for now, but let me know if im missing something

**Comment by Hari-krish-v** [comment]
> Make sure you added it in the [right location](https://github.com/stripe/stripe-react-native/blob/master/example/android/app/src/main/AndroidManifest.xml#L23), I don't think this is a bug with stripe react native so I'm going to close this for now, but let me know if im missing something

We added the android:exported like this but we still getting the same error

**Comment by charliecruzan-stripe** [comment]
And if you remove the stripe-react-native dependency, does the error go away?

**Comment by uplsoumen** [comment]
Have anyone get any solution
In Stripe-react-native module manifest
i found this code snippet
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.reactnativestripesdk">
</manifest>
`
Where should i add android:exported here?

**Comment by charliecruzan-stripe** [comment]
[here](https://github.com/stripe/stripe-react-native/blob/master/example/android/app/src/main/AndroidManifest.xml#L24)

**Comment by raldred** [comment]
We have `android:exported` on all our activities, services and broadcast receivers using intent filters.
Still having trouble with stripe.

The manifest merge tool in Android studio is very clear, this is a stripe problem.
> `Error: android:exported needs to be explicitly specified for element <activity#com.stripe.android.payments.StripeBrowserLauncherActivity>`

![image](https://user-images.githubusercontent.com/37096/209354145-c75779a1-cff6-46e8-8ac2-828a696b137e.png)

We were able to fix this by adding the following to our main manifest.

```
<manifest ...
    <application ...
        <activity
            android:name="com.stripe.android.payments.StripeBrowserLauncherActivity"
            android:exported="true" 
            tools:node="merge"/>
   </application>
</manifest>

```

**Comment by charliecruzan-stripe** [comment]
What version are you using? That property is already set: https://github.com/stripe/stripe-android/blob/61470fe5aaa2a1a460937a1e6566cc2b939278d8/payments-core/AndroidManifest.xml#L32-L36

**Comment by abanoubamin** [comment]
I'm facing the same issue, is there any solution?
