### ISSUE TITLE
fingerprint implementation on Card object

### ISSUE THREAD

**Issue by fernan542** [stripe/stripe-react-native#907]
**Is your feature request related to a problem? Please describe.**
How can I validate if card already exists or attached to customer? Because as of now, the customer can add many Cards with the same details. I've read in some SDKs / Library that we can check it using the `payment_method` fingerprint but I'm not able to see it when I access the `Card` object.

**Describe the solution you'd like**
Implement `fingerprint` property to Card object just like in SEPA, Becs, AUBECS and usbankaccount.

**Additional context**
My temporary solution is to use the `last4` property of the Card object.
This ticket originated from https://github.com/flutter-stripe/flutter_stripe/discussions/691

Thank you very much, Stripe team!

**Comment by charliecruzan-stripe** [comment]
thanks for catching this! it's available on iOS, but not android, opening a pr now :)
