### ISSUE TITLE
[Android] React-native - can not build the project due to reactApplicationContext not found 

### ISSUE THREAD

**Issue by ravi-tally** [stripe/stripe-react-native#919]
**Could not build the project**

**Here my package.json configuration**

![Screenshot 2022-05-02 at 7 56 19 PM](https://user-images.githubusercontent.com/85555170/166255053-b53ab5cd-9585-48ee-80e7-8905b595b10f.png)
![Screenshot 2022-05-02 at 7 56 31 PM](https://user-images.githubusercontent.com/85555170/166255058-7308d0a9-06df-4f7d-be49-0b48a6bdab58.png)

**Here my android app build.gradle configuration**

![Screenshot 2022-05-02 at 8 08 58 PM](https://user-images.githubusercontent.com/85555170/166255213-d48bf3a2-c153-4e04-aeb8-e7992791dc3a.png)

![Screenshot 2022-05-02 at 8 26 40 PM](https://user-images.githubusercontent.com/85555170/166256150-9d6ac75f-e233-44d2-90e2-6ec2a8fea56c.png)

**To Reproduce**
1. Add dependancy with **yarn add @stripe/stripe-react-native**
2. Clean the android and re-build the project getting kotlin related error like below

![Screenshot 2022-05-02 at 8 07 04 PM](https://user-images.githubusercontent.com/85555170/166255585-41eebf50-b741-4585-8f10-3f40c7aed347.png)

**Which is related to AddToWalletButtonView.kt**

![Screenshot 2022-05-02 at 8 15 51 PM](https://user-images.githubusercontent.com/85555170/166255677-f6a002c4-bc4a-4020-9900-090a4a908531.png)

As per the documentation, I have setup gradle as 4.x.x and above and compileSDK set to 31 as I have mentioned above, but still I can not run the app properly in android platform.

However, in iOS platform the app working fine.

**Comment by charliecruzan-stripe** [comment]
I see- `getReactApplicationContext` was [introduced in RN 0.64](https://github.com/facebook/react-native/blob/0.64-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/ThemedReactContext.java), and is not present in 0.63. I will update the changelog now to reflect that v0.8.0 requires React Native 0.64 and above.

Is there a reason you're still using RN 0.63? It's also possible we could patch this and make it work on newer versions of react native if that line fails.

**Comment by charliecruzan-stripe** [comment]
closed by https://github.com/stripe/stripe-react-native/commit/8b104327140c1fda696822677e561344d15cc043

**Comment by ravi-tally** [comment]
Yes it works fine after update RN 0.63 to 0.66. Unfortunately now it creates an issue for the iOS side and not able to resolve it. It only comes with this error message nothing else while trying to run the app. @charliecruzan-stripe  can you look into this?

![Screenshot 2022-05-09 at 12 09 33 PM](https://user-images.githubusercontent.com/85555170/167355531-757a149a-b62c-4edb-8745-034155bdb613.png)
