### ISSUE TITLE
confirmPayment hook works different than confirm payment url from stripe api

### ISSUE THREAD

**Issue by manofab** [stripe/stripe-react-native#938]
**Describe the bug**
I am working on a mobile app and I am trying to make a payment with a saved card. For that I am using the confirmPayment hook, provided by this sdk, following this example https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/CVCReCollectionScreen.tsx#L74-L80
The type from confirmPayment hooks makes mandatory to send the paymentMethodId ( which is the saved card id in the end ) and if I don't send it the confirmation will fail telling that the information of the card is not complete. 
But in web, using the following curl it works just fine. 
```
curl --location --request POST 'https://api.stripe.com//v1/payment_intents/pi_YYY/confirm' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Bearer pk_test_XXX' \
--data-urlencode 'client_secret=pi_YYY_secret_TTT'
```
Both mobile and web follow the same approach so my question is why is necessary to send the saved card id on the hooks but not on web. This id is already included in the payment intent.

**Expected behavior**
confirmPayment hooks works as https://api.stripe.com//v1/payment_intents/pi_YYY/confirm url

**Desktop (please complete the following information):**
 - OS: any OS
 - Browser: any Browser
 - Version: any version

**Smartphone (please complete the following information):**
 - Device: any device
 - OS: any OS
 - Browser : any browser
 - Version any version

**Comment by charliecruzan-stripe** [comment]
hi! thanks for the issue. I believe this was fixed [here](https://github.com/stripe/stripe-react-native/pull/931), released in v0.9.0
