### ISSUE TITLE
Error with Apple Pay on production only - merchantIdentifier not being passed to PaymentSheet?

### ISSUE THREAD

**Issue by ScreamZ** [stripe/stripe-react-native#945]
Hello,

I'm currently chatting with the stripe team about the following issue. For some reasons I'm not able to use PaymentSheet with Google pay in production mode only, in test mode, everything goes fine.

When I try I get an "unknown error"

Here is the log of `/v1/tokens` call related, I tested with various cards, and always the same HTTP 500 error from stripe. I guess it's related to some configuration I might be missing ?

```json
{
  "card": {
    "address_city": "Montpellier",
    "address_country": "FR",
    "address_line1": "<My_address_hidden>",
    "address_zip": "34000",
    "name": "<My_name_hidden>"
  },
  "guid": "5993f99b-e209-<Hide_some_characters>-b0a7-1002340d1583118564",
  "muid": "db971b25-024f-<Hide_some_characters>-90a7-16fd1e595ed33c8be9",
  "payment_user_agent": "stripe-ios/22.3.0; variant.legacy; PaymentSheet; STPApplePayContext",
  "pk_token": "******",
  "pk_token_instrument_name": "MasterCard 7319",
  "pk_token_payment_network": "PKPaymentNetwork(_rawValue: MasterCard)",
  "pk_token_transaction_id": "45B74<Hide_some_characters>A78D655A4AC1487DE45122E8A56112F4F7EBB595C4406BBB59E",
  "sid": "8b0fdf2f-5f43-4e3a-ab9b-b18ea8f9f4093c9a38"
}
```

Respond with HTTP 500

```json
{
  "error": {
    "message": "An unknown error occurred",
    "type": "api_error"
  }
}
```

Any idea what could cause that ?

As it seems related to a server issue, I'm not sharing my app version (I'm on 0.9) but I'm using PaymentSheet (like stripe checkout) and Apple Pay

**Comment by ScreamZ** [comment]
@davidme-stripe Thanks for your support, way better than the chat support ahah, even if the guys are really cool on it.

Just to be sure :
> If you have separate Production/Test App IDs in Xcode, the Merchant ID should be added to the entitlements of the production app.
- Does it means that I can't use the ID in test and production at the same time and it will somehow get "locked" between the two ? So i need two merchant ID ?
- Take note that in Stripe documentation u linking they ask for `merchant.com.{{YOUR_APP_NAME}}` where Expo CLI (or in stripe portal i don't remember) ask for `merchant.{{YOUR_APP_NAME}}` 

## Code sample
For the information, here is my implementation code for various places in the meantime i'm trying your manipulation.
```ts
async ({ error }) => {
      if (!error) {
        await mutate(ME_CACHE_KEY);
        goBack();
      }
      if (error && error.code !== PaymentSheetError.Canceled) setError(error);
    },
    [mutate],
  );

  useMount(async () => {
    const {
      data: { client_secret },
    } = await methods.authentication.checkout();

    setClientSecret(client_secret);

    const [{ error: initPayError }, { error: initGpayError }] =
      await Promise.all([
        initPaymentSheet({
          setupIntentClientSecret: client_secret,
          merchantDisplayName: t("app"),
          applePay: true,
          googlePay: false, // TODO: Wait for expo to fix latest react native stripe and test it
          merchantCountryCode: "FR",
          testEnv: Config.STRIPE.TEST_ENVIRONMENT,
        }),
        Platform.OS === "android"
          ? initGooglePay({
              countryCode: i18n.language,
              merchantName: t("app"),
              testEnv: Config.STRIPE.TEST_ENVIRONMENT,
            })
          : Promise.resolve<GooglePayInitResult>({}),
      ]);

    if (initPayError || initGpayError) setError(initPayError ?? initGpayError);
  });

  return (
    <ScrollView
      alwaysBounceVertical={false}
      contentContainerStyle={tw("grow justify-around px-8")}

<AppText
        size="2xl"
        weight="extraBold"
        style={tw("text-text-strong text-center")}

{t("card_payment.title")}
      </AppText>
      <Image
        source={require("@modules/settings/assets/CardCollectorIllu1.png")}
        resizeMode="contain"
        style={tw("h-40 w-full")}
      />
      <AppText style={tw("text-center leading-6")}>
        {t("card_payment.description")}
      </AppText>
      <View style={tw("mt-4")}>
        {error && (
          <AppText
            weight="bold"
            style={tw("text-primary-strong text-center mb-8")}

{error.localizedMessage ?? error.message ?? t("card_payment.error")}
          </AppText>
        )}
        {clientSecret === null ? (
          <Loader />
        ) : Platform.OS === "android" ? (
          <>
            <GooglePayButton
              type="standard"
              style={tw("h-12")}
              onPress={() =>
                presentGooglePay({
                  clientSecret,
                  forSetupIntent: true,
                  currencyCode: Config.STRIPE.CURRENCY_CODE,
                }).then(handlePaymentRes)
              }
            />
            <View style={tw("h-4")} />
            <AppButton
              title={t("card_payment.android_register_card")}
              onPress={() => presentPaymentSheet().then(handlePaymentRes)}
            />
          </>
        ) : (
          <AppButton
            title={t("card_payment.ios_register_method")}
            onPress={async () => {
              presentPaymentSheet().then(handlePaymentRes);
            }}
          />
        )}

        <AppText
          onPress={goBack}
          weight="bold"
          style={tw("mt-4 p-4 text-center text-primary-base")}

{t("actions.later")}
        </AppText>
      </View>
    </ScrollView>
  );
};
```

`app.json`
```JSON
{
"plugins": [
    [
      "@stripe/stripe-react-native",
      {
        "enableGooglePay": true,
        "merchantIdentifier": [MerchantIdentifier],
      },
    ],
  ]
}
``` 

`app.tsx`

```tsx
 <StripeProvider
      publishableKey={Config.STRIPE.PUBLISHABLE_KEY}
      stripeAccountId={Config.STRIPE.ACCOUNT_ID}
      urlScheme={ExpoAppConfig.scheme}
      merchantIdentifier={Config.STRIPE.MERCHANT_IDENTIFIER}
    >
```

**Comment by davidme-stripe** [comment]
> Does it means that I can't use the ID in test and production at the same time and it will somehow get "locked" between the two ? So i need two merchant ID ?

No, you should be able to use the same merchant ID for both testing and production, but you need to make sure the merchant ID in your production app matches the merchant ID in your production Stripe account.

In your code sample, `Config.STRIPE.MERCHANT_IDENTIFIER` in your app.tsx should match the Merchant ID in your Xcode project and the Merchant ID in your Stripe account's [Apple Pay Settings](https://dashboard.stripe.com/settings/payments/apple_pay) page, and `Config.STRIPE.PUBLISHABLE_KEY` should match the [livemode publishable key](https://dashboard.stripe.com/apikeys) for that same account. `merchant.com.AppName` vs `merchant.AppName` shouldn't matter, but it does need to be a consistent ID across all Apple Pay settings.

**Comment by davidme-stripe** [comment]
Thanks for the info, sorry for the confusion! @charliecruzan-stripe, can you help me check if this is being forwarded correctly to PaymentSheet?

**Comment by ScreamZ** [comment]
> Thanks for the info, sorry for the confusion! Is it possible that `Config.STRIPE.MERCHANT_IDENTIFIER` isn't set to `"merchant.stride"`? @charliecruzan-stripe, can you help me check if the `merchantIdentifier` is being forwarded correctly to PaymentSheet?

On my side looks like it's the same key, I used the config key and it still works. Even thought could be nice to enhance the error message on stripe side 😅 U spotted well but the message is clearly cryptic ahah

**Comment by charliecruzan-stripe** [comment]
Yep! I will take a look, thanks for the issue @ScreamZ

**Comment by ScreamZ** [comment]
I'm still getting (from time to time) when I repeat setup intent apple pay the 
```ts
{
  "error": {
    "message": "An unknown error occurred",
    "type": "api_error"
  }
}
```

Not sure for which reasons

Working Log ID:
- req_y0sTt6oJj03KrY

Not working log ID:
- req_GLV6lYzccmnZ8D

**Comment by charliecruzan-stripe** [comment]
I can confirm that the `merchantIdentifier` from the provider is being passed along to the payment sheet correctly. If it wasnt, but you passed `true` to `applePay`, then you'd received an error directly from the RN SDK saying that the merchant id was missing. 

@ScreamZ it looks like you're using Expo- are you building with EAS then? Or how are you using `@stripe/stripe-react-native` v0.9.0?

**Comment by ScreamZ** [comment]
@charliecruzan-stripe I'm using Expo SDK45 with a development client.

I'm building with EAS-CLI, and I'm up-to-date most of the time.

I'm using `0.9.0` 
`- @stripe/stripe-react-native - expected version: 0.6.1 - actual version installed: 0.9.0```

I had to do this because this was patched for SDK45 on this release before brentvane ask explicitly the stripe team to backport the fix of SDK45 plugin on actual 0.6.

Also I can benefit for various changes from 0.9


---
I had your mate at stripe support also telling me the following:
>Hello Andréas,
>
>My name is Mike, I am an engineer at Stripe. Here to help with your ApplePay issue.
>
>After looking further in to your error, it looks like this was caused by your account having two ApplePay certificates with us that were generated with the same CSR. To resolve this we recommend deleting your old certificate and going through our Apple Pay set up process again with a new CSR[1]. Once you have uploaded a new .cer file to us that was generated with a new CSR, this issue should be resolved for you.
>
>I agree that this generic error message is not helpful in this scenario and will raise feedback so that we can hopefully surface a more informative error message for this error in future. Also apologies for the delay in my reply, I had to consult a colleague on this error and meant to send you a heads up message that this response might take a bit longer than usual. Let me know if you have any further questions.
>
>Thanks,
>Mike

**Comment by charliecruzan-stripe** [comment]
Got it, thanks for sharing that! Can you let me know if the issue is resolved after uploading a new .cer file?

**Comment by charliecruzan-stripe** [comment]
heya @ScreamZ , any update on the behavior after uploading the new cert?

**Comment by charliecruzan-stripe** [comment]
sure thing!
