### ISSUE TITLE
Support Stripe Terminal

### ISSUE THREAD

**Issue by sguha00** [stripe/stripe-react-native#95]
**Is your feature request related to a problem? Please describe.**
I'd like to use Stripe Terminal to accept in-person payments via the Bluetooth Chipper reader

**Describe the solution you'd like**
Expose the iOS and Android Stripe Terminal SDK through React Native

**Describe alternatives you've considered**
https://github.com/theopolisme/react-native-stripe-terminal

**Additional context**

**Comment by peraltafederico** [comment]
@auchenberg-stripe Hello! I hope you're doing well.

I'm currently working on an app that uses Stripe Terminal. We did could support **Chipset 2** by using the unofficial lib [react-native-stripe-terminal](https://github.com/theopolisme/react-native-stripe-terminal) and now we need to support the new **WisePad 3**, the thing is the library doesn't support it. There is an open issue not answered yet here https://github.com/theopolisme/react-native-stripe-terminal/issues/45. 

Any ideas of how could we support **WisePad 3** in react-native? 

Thanks!

**Comment by LukhiKartik** [comment]
Any update? I am using same WisePas 3 but its not working with this library.

**Comment by charliecruzan-stripe** [comment]
This is done ✅  Check out https://github.com/stripe/stripe-terminal-react-native!
