### ISSUE TITLE
isGooglePaySupported crashes the app in android

### ISSUE THREAD

**Issue by pakkibokati2012** [stripe/stripe-react-native#952]
**Describe the bug**
isGooglePaySupported method crashing the app in android but not in iOS. 

**To Reproduce**
1. make a functional component
2. execute isGooglePaySupported function inside useeffect and make some changes to the state 
![image](https://user-images.githubusercontent.com/34542543/169570620-d3f30854-f242-42f9-a804-9739e2a8608b.png)

**Expected behavior**
app should not crash

**Smartphone (please complete the following information):**
 - Device: [e.g. Android emulator Pixel 4 API 32]
 - OS: [e.g. Android 12]

 - Stripe Version [0.3.0]
 - React-Native 0.65.0

**Additional context**
**java.lang.IllegalStateException: PaymentConfiguration was not initialized. Call PaymentConfiguration.init().**

**Comment by MathieuRegis** [comment]
Same error with :
- Android 12
- Stripe Version 0.10.0
- React-Native 0.64.0

**Comment by charliecruzan-stripe** [comment]
Have you called `.initStripe` or wrapped your app in the `StripeProvider` component? The error message seems to indicate that has not happened

**Comment by pakkibokati2012** [comment]
> Have you called `.initStripe` or wrapped your app in the `StripeProvider` component? The error message seems to indicate that has not happened

That is exactly what I was missing. I should have pointed that here in the issue. Thanks

**Comment by jp928** [comment]
Is this solved? Why it is closed?

**Comment by charliecruzan-stripe** [comment]
It is solved- see this comment https://github.com/stripe/stripe-react-native/issues/952#issuecomment-1136393436
