### ISSUE TITLE
Add To Apple Wallet Causing Crash

### ISSUE THREAD

**Issue by gakinson** [stripe/stripe-react-native#953]
**Describe the bug**
We setup our  react native app to add an issuing card to the apple wallet via https://stripe.com/docs/issuing/cards/digital-wallets?platform=react-native .

we retrieve a key and the button appears, but when the button is clicked, the app crashes with the following error:

```
EXC_BREAKPOINT: beginPushProvisioning > objectAtIndex: > stripe_react_native/AddToWalletButtonView.swift > Unexpectedly found nil while unwrapping an Optional value
```

Lines of code where crash happens is https://github.com/stripe/stripe-react-native/blob/1a5492d14cb71cbcc9a43213d5634ffb4901602d/ios/pushprovisioning/AddToWalletButtonView.swift#L100-L101

**To Reproduce**
1. Setup AddToWallet
2. Click on Add to wallet button
4. App crash

**Expected behavior**
Apple wallet is opened and card is added.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: 14.8.1

**Comment by charliecruzan-stripe** [comment]
Hi! happy to dig into this- could you provide code to reproduce this? I've tried it with our [example app](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ApplePayScreen.tsx#L185-L206) and can't reproduce this crash

**Comment by gakinson** [comment]
Hello,

I noticed that you have test enabled. I will mention that test worked fine for me, it was once I removed the test and hooked things up to the production environment of stripe.

**Comment by charliecruzan-stripe** [comment]
Have you gone through the [process of getting Production access for iOS](https://stripe.com/docs/issuing/cards/digital-wallets?platform=react-native#requesting-access-for-ios)?

**Comment by gakinson** [comment]
Okay I had a feeling this was it. I sent an email support request earlier today. Let's see what happens after that has been approved.

**Comment by charliecruzan-stripe** [comment]
Yeah, that would probably cause this if test mode **is** working. As the docs state: "In test mode, you don’t need the com.apple.developer.payment-pass-provisioning entitlement."

**Comment by charliecruzan-stripe** [comment]
Any update @gakinson ?

**Comment by gakinson** [comment]
Still waiting on response from support to get the entitelment.

**Comment by charliecruzan-stripe** [comment]
sounds good 😄

**Comment by gakinson** [comment]
Got the response and everything was enabled, still getting the crash though.

**Comment by gakinson** [comment]
I noticed that there is also the error:
```
2022-06-09 11:55:38.378084-0700 WeSponsoredApp[5499:4712563] [General] com.productwind.wesponsored missing entitlement: com.apple.developer.payment-pass-provisioning
stripe_react_native/AddToWalletButtonView.swift:101: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2022-06-09 11:55:38.379738-0700 WeSponsoredApp[5499:4712563] stripe_react_native/AddToWalletButtonView.swift:101: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

**Comment by gakinson** [comment]
Do you have a specific guide that I can reference to check if I enabled it properly.

**Comment by charliecruzan-stripe** [comment]
It's an Apple-specific entitlement, so I'm going to have to refer you to [Apple's docs](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/ApplePayandPassKitEntitlements/ApplePayandPassKitEntitlements.html) :/ 

> Use this entitlement to enable the in-app provisioning of payment cards. This entitlement allows you to initialize and present a [PKAddPaymentPassViewController](https://developer.apple.com/documentation/passkit/pkaddpaymentpassviewcontroller) object.
> In the entitlement’s file, add the com.apple.developer.payment-pass-provisioning key with a Boolean value of YES. You need special permission from Apple to submit apps with this key enabled. For more information, contact apple-pay-inquiries@apple.com.

**Comment by gakinson** [comment]
Okay got it, yea that is not fully complete.
