### ISSUE TITLE
React Native Stripe is not working with IOS unable to build IOS

### ISSUE THREAD

**Issue by UsamaIkraam0099** [stripe/stripe-react-native#955]
**Describe the bug**
Recently I upgrade React-Native version 0.67 to 0.68.2 and install @stripe/stripe-react-native than im facing errors and unable to build my IOS app. I follow all the installation steps. 
**To Reproduce**
1. install @stripe/stripe-react-native
3. pod install
4. npx react-native run-ios OR you can build through XCode
**Expected behavior**
Should work properly as mention in documentation
**Screen
![Screenshot 2022-05-21 at 1 37 59 PM](https://user-images.githubusercontent.com/77922449/169647386-8c9f160f-6333-4b1b-b233-f955db055867.png)

![Screenshot 2022-05-21 at 1 38 05 PM](https://user-images.githubusercontent.com/77922449/169647326-4c3b75d7-2f61-4781-9162-f31ebe3c053f.png)
![Screenshot 2022-05-21 at 2 30 04 PM](https://user-images.githubusercontent.com/77922449/169647610-f1764305-7dd4-46d2-8c9c-e4b689ddfd51.png)

**Desktop (please complete the following information):**
 - OS: macOs Catalina
 - Version 10.15.7

**Smartphone (please complete the following information):**
 - Device: iPhone 12 (Simulator)
 - OS: iOS12.1

**Additional context**
for implementing stripe in our app i upgrade my react native version to 0.68.2 and i solved all other issues related to android and now Android is working fine but only problem is with IOS.

**Comment by davidme-stripe** [comment]
From looking at your screenshot, it appears that you're using an older version of Xcode. [Xcode 13 is required for all apps submitted to the App Store](https://developer.apple.com/ios/submit/), so the Stripe SDK doesn't support older versions.

**Comment by UsamaIkraam0099** [comment]
@charliecruzan-stripe  hi. The links that you mention I already implement that but not working for me. What I actually done is I upgrade RN 0.67 to 0.68 and faces many issues even android is also not working fine but after comparing diffs Im able to fix that for android but for IOS I also do same process and comparing each file but not working.

**Comment by UsamaIkraam0099** [comment]
> From looking at your screenshot, it appears that you're using an older version of Xcode. [Xcode 13 is required for all apps submitted to the App Store](https://developer.apple.com/ios/submit/), so the Stripe SDK doesn't support older versions.


@davidme-stripe maybe you are right my Xcode version is 12.4 and im using Macbook Pro 2012 so I think its not supporting latest version. So I go back to RN 0.67 and also downgrade @stripe/stripe-react-native version

**Comment by charliecruzan-stripe** [comment]
made note of this in the readme- https://github.com/stripe/stripe-react-native/commit/9872bb35ba8eefc4dabe7e4af3217e0797876a63

thanks @UsamaIkraam0099 !

**Comment by nabeel-ideabits** [comment]
For Expo users run `npx expo prebuild --clean ` it worked for me after trying multiple solutions if upgrading/downgrading isn't an option.
