### ISSUE TITLE
handleNextAction returns a canceled error on android even if the 3ds check is completed

### ISSUE THREAD

**Issue by scesbron** [stripe/stripe-react-native#963]
**Describe the bug**
We are using the "Finalize payments on the server" flow. With this flow, after the payment intent was created on the server we call `handleCardAction` to deal with the 3DS workflow. This is the step 6 of the payment process in the doc: https://stripe.com/docs/payments/accept-a-payment-synchronously#react-native-handle-next-actions

Our code based on this doc was working fine with version 0.2.2. But when upgrading to version 0.9.0 (we had to replace `handleCardAction` with `handleNextAction`) the code no longer works in production on android.

With version 0.9.0, after a successful 3DS check on android, the call to `handleNextAction` returns an `error` value with status `Canceled`.

**To Reproduce**
Steps to reproduce the behavior (only on android):
1. Have an app setup with "Finalize payments on the server" flow
2. Create the payment on the server an receive a requires action response because we need 3DS check
3. Complete the 3DS process (in production with a real card)
4. Check the retrieve data from the `handleNextAction` call: you have a "Canceled" erro

**Expected behavior**
In this case, we should get a `paymentIntent` object with the "Requires confirmation" status.

**Screenshots**
Here are the latest steps from my 3DS check 

![image](https://user-images.githubusercontent.com/386514/170195315-202ef109-ac2d-44d0-8c5b-be4ccc3e14ab.png)
![image](https://user-images.githubusercontent.com/386514/170195345-f8749e4f-e5b0-464f-bc7c-462012ba7b7e.png)

**Smartphone (please complete the following information):**
 - Device: all android phones
 - OS: android 
 - Version from 7.0 to 12.0

**Additional context**
I tried to update the version of `stripe-react-native` to see when the changes occurs.

My app is working fine with version 0.4.0 but not with version 0.5.0.

**Comment by charliecruzan-stripe** [comment]
hi! taking a look at this now, thanks for the report

**Comment by charliecruzan-stripe** [comment]
Yeah, pretty sure this is due to our move to the `PaymentLauncher` from `stripe-android`. Unfortunately, when clicking the `close` button on the UI, it's registering as "cancelled", but if you call `retrievePaymentIntent` on that payment intent, it'll come back with the actually correct status. 

This could be more of an issue with 3DS, since from my testing, it looks like the [Webview flow](https://stripe.com/docs/payments/3d-secure#three-ds-cards) still has in the correct result, even on the most recent version of stripe-react-native

**Comment by charliecruzan-stripe** [comment]
upstream issue- https://github.com/stripe/stripe-android/issues/5059
