### ISSUE TITLE
Payment sheet to get card Details?

### ISSUE THREAD

**Issue by ceyanesb** [stripe/stripe-react-native#966]
Hi, I was looking at some apps made in react native and they use the Payment Sheet to get details of the card to generate the token in which the service then can be charged on the backend. I tried to to use the payment sheet to get those details, not to make a paymentIntent but it didn't work. Is this something possible?

**Comment by bensnell-stripe** [comment]
Hi there, for this use-case you likely want to look into using a SetupIntent with PaymentSheet. Take a look through our guide here: https://stripe.com/docs/payments/save-and-reuse?platform=react-native&ui=payment-sheet.

**Comment by charliecruzan-stripe** [comment]
Closing this as the above is a great recommendation - please use SetupIntents with the PaymentSheet :)
