### ISSUE TITLE
CardForm cvc field shows discover logo on Android

### ISSUE THREAD

**Issue by HunterW6713** [stripe/stripe-react-native#967]
**Describe the bug**
The CardForm component on android shows the Discover logo in the cvc field

**To Reproduce**
1. Integrate CardForm component into a React Native app
2. Build app on android simulator or physical device
3. Navigate to screen with CardForm
4. See that Discover logo is in cvc field of the CardForm on Android

**Expected behavior**
A generic icon is rendered inside of cvc field that is not associated with a specific card brand

**Screenshots**
![Screenshot_1653598750](https://user-images.githubusercontent.com/103949189/170579379-be66c12a-9fe3-4225-846e-af59d76df549.png)
72e7.png)

![Screenshot_1653598763](https://user-images.githubusercontent.com/103949189/170579816-15b5f028-01dc-4b9b-86bd-fcfb645d6fef.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3A
 - OS: Android 12
 - React-Native Application

**Additional context**
This problem does not appear to exist in iOS

**Comment by charliecruzan-stripe** [comment]
Hi! This is an upstream `stripe-android` bug, and we're looking into it. thanks for the report!
