### ISSUE TITLE
lateinit property paymentLauncher has not been initialized

### ISSUE THREAD

**Issue by dmtar** [stripe/stripe-react-native#968]
I have a bit of a conceptual question, recently we updated our stripe-react-native dependency from 0.2 to 0.10. At the moment we confirm the setup intent right after the initStripe call, as follows

```
await initStripe({
    publishableKey: 'some-key',
})

const { error, setupIntent } = await confirmSetupIntent('some-client-secret', {
    paymentMethodType: 'Card',
});
```

The above results in the following error, only for android

<img width="361" alt="image" src="https://user-images.githubusercontent.com/37380766/170578780-b8316d46-67cb-41fe-9bf6-f0a626a2357f.png">

If we add a 1 second delay after the initStripe to let it finish, it's all good. But I don't really like this approach.

- What is your suggestion when it comes to "initStripe" in the last possible moment?
- Is there any way to check that the initialisation work that initStripe should do is actually finished, so we can safely continue with confirmSetupIntent?
- I was expecting that the initStripe will resolve it's promise after the paymentLauncher is initialized, but probably I'm missing something in the Kotlin part.

Thanks in advance.

**Comment by charliecruzan-stripe** [comment]
This will be fixed by https://github.com/stripe/stripe-react-native/pull/965 👍

**Comment by dmtar** [comment]
@charliecruzan-stripe Thanks. I will close this one. Can you give me some rough ETA of the fix, probably with 0.12 release?

**Comment by thirstyde** [comment]
gfh

**Comment by thirstyde** [comment]
Please Add Solution
