### ISSUE TITLE
Financial Connections implementation

### ISSUE THREAD

**Issue by remonh87** [stripe/stripe-react-native#978]
**Is your feature request related to a problem? Please describe.**
We got a feature request in the Flutter Stripe repo for the  [Collect a Financial Connections account](https://stripe.com/docs/financial-connections/other-data-powered-products?platform=web#collect-an-account) flow. Are there any plans to implement this?

**Comment by gustavo-olegario-lawnstarter** [comment]
@charliecruzan-stripe is this something that will be released soon?

**Comment by charliecruzan-stripe** [comment]
Hi! Yes, we're planning on prioritizing this over the next couple weeks
