### ISSUE TITLE
google pay is not showing using initPaymentSheet

### ISSUE THREAD

**Issue by shaikhsufiyan** [stripe/stripe-react-native#983]
i am new to expo react native. i am trying to  integrating  google pay with my expo app. by following this link 
 https://snack.expo.dev/@charliecruzan/stripe-react-native-example?platform=mydevice.

Currently using this project for testing. Google pay is already installed in my phone.
 https://snack.expo.dev/@charliecruzan/stripe-react-native-example?platform=mydevice.

The above code is working  fine for the  apple pay. initPaymentSheet detects apple pay successfully but when i try to run same code in android for google pay it doesn't detect google pay. 

My expo SDK version is 45
"expo": "^45.0.0",
 "@stripe/stripe-react-native": "0.6.1",
 "react-native": "0.68.2",

Android version: 11 
Samsung A50 

initPayment payment Sheet Code :-

 const { error, paymentOption } = await initPaymentSheet({
        customerId: customer,
        customerEphemeralKeySecret: ephemeralKey,
        paymentIntentClientSecret: paymentIntent,
        customFlow: true,
        merchantDisplayName: 'Example Inc.',
        applePay: true,
        merchantCountryCode: 'US',
        style: 'alwaysDark',
        googlePay: true,
        testEnv: true,
      });

initPaymentSheet returns paymentOption undefine in android for google pay
and error also undefine.

Please help!!!!

**Comment by charliecruzan-stripe** [comment]
[According to Expo's docs: ](https://docs.expo.dev/versions/latest/sdk/stripe/)

> Google Pay is not supported in Expo Go. To use Google Pay, you must use either [EAS Build](https://docs.expo.dev/build/introduction/), or run expo run:android in your project directory.

**Comment by Tieu-Mai-Nhi** [comment]
@shaikhsufiyan how to fix that, my bro?
