### ISSUE TITLE
is stripe-react-native support affirm?

### ISSUE THREAD

**Issue by pankajsoftyoi** [stripe/stripe-react-native#984]
Is stripe-react-native support affirm??

if yes then can someone please provide some source or docs to integrate support for affirm with stripe in my react native application?

in release note of 0.11.0 defined 
"Added Affirm and AU BECS Direct Debit support to Payment Sheet. https://github.com/stripe/stripe-react-native/pull/940"

but not able to see Affirm option in Payment sheet, event i enabled Affirm from stripe dashboard.

**Comment by Osamasomy** [comment]
Im also wants to integrate affirm in react native. any news?

**Comment by charliecruzan-stripe** [comment]
hi! this is in progress here- https://github.com/stripe/stripe-react-native/pull/1036

**Comment by pankajsoftyoi** [comment]
@charliecruzan-stripe Thanks to add affirm support as payment method with stripe,

Can you please help to show this model same as below image with this affirm integration flow, because when i used latest pull, there is no option or method to show this kind of affirm view or model.

<img width="825" alt="Screenshot 2022-07-21 at 4 26 51 PM" src="https://user-images.githubusercontent.com/106329563/180199809-719e465c-9f56-4967-91d1-aedaa319405c.png">

**Comment by pankajsoftyoi** [comment]
Also can you please help us on one more thing, 
Same as affirm SDK provide promotional text and button to 
show pre-booking amount/month, how can i show this kind of button using stripe-react-native ?

![imgpsh_fullsize_anim (2)](https://user-images.githubusercontent.com/106329563/180388416-3a8c95d9-e4ab-414c-ad12-03a74b1aed1e.jpeg)
