### ISSUE TITLE
Works on simulator but not on actual device

### ISSUE THREAD

**Issue by sduan1** [stripe/stripe-react-native#995]
Hi:
I am following this tutorial: https://stripe.com/docs/payments/accept-a-payment?platform=react-native. I am using EXPO and everything works fine on iphone simulator. However, I get this error when I load the app with my iphone: You did not provide an API key. Could anyone give me some insights on how to debug this problem?
Here is the code:
`import React, { useState, useEffect } from 'react';
import { Alert } from 'react-native';
import { StyleSheet, Text, View, Screen, Button } from 'react-native';

import {useStripe} from '@stripe/stripe-react-native';

function SettingScreen() {
    const { initPaymentSheet, presentPaymentSheet } = useStripe();
    const [loading, setLoading] = useState(false);
  
    const fetchPaymentSheetParams = async () => {
      var formdata = new FormData();
      formdata.append("username", "testcustomer1@gmail.com");
      formdata.append("password", "Dsy980124");
      const response = await fetch('http://molecents-dev.us-west-2.elasticbeanstalk.com/api/shoppingcart/checkout', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body:formdata,
      });
      console.log(response.status);
      const { paymentIntent, ephemeralKey, customer} = await response.json();
  
      return {
        paymentIntent,
        ephemeralKey,
        customer,
      };
    };
  
    const initializePaymentSheet = async () => {
      const {
        paymentIntent,
        ephemeralKey,
        customer,
        publishableKey,
      } = await fetchPaymentSheetParams();
  
      const { error } = await initPaymentSheet({
        customerId: customer,
        customerEphemeralKeySecret: ephemeralKey,
        paymentIntentClientSecret: paymentIntent,
        // Set `allowsDelayedPaymentMethods` to true if your business can handle payment
        //methods that complete payment after a delay, like SEPA Debit and Sofort.
        allowsDelayedPaymentMethods: true,
        publishableKey: publishableKey
      });

    };
  
    const openPaymentSheet = async () => {
        
        var res = await initializePaymentSheet();
        const { error } = await presentPaymentSheet();

        if (error) {
          Alert.alert(`Error code: ${error.code}`, error.message);
          handelPaymentCanceled()
        } else {
          Alert.alert('Success', 'Your order is confirmed!');
        }
    };

    const capturePayment = async () => {
      
    }

    const handelPaymentCanceled = async () => {
      var formdata = new FormData();
      formdata.append("username", "testcustomer1@gmail.com");
      formdata.append("password", "Dsy980124");

      var requestOptions = {
        method: 'POST',
        body: formdata,
        redirect: 'follow'
      };
      try{
        var res = await fetch("http://localhost:8000/api/shoppingcart/cancel_paymentintent", requestOptions)
        Alert.alert('canceled')
      }catch{
        Alert.alert('Error!')
      }
      
    }
  
    useEffect(() => {
      
    }, []);
    return (
        <View>
          <Button
            variant="primary"
            title="Checkout"
            onPress={openPaymentSheet}
          />
          <Button 
          title="Capture"
          onPress={capturePayment}
          />

        </View>
      );
}

export default SettingScreen`

**Comment by charliecruzan-stripe** [comment]
> http://localhost:8000

You can't fetch from localhost on a real device, only simulators. You can use something like `ngrok` to workaround this though :) It's should be fairly easy to setup, then you'll just copy/paste the new URL. 

https://ngrok.com/

**Comment by sduan1** [comment]
> > http://localhost:8000
> 
> You can't fetch from localhost on a real device, only simulators. You can use something like `ngrok` to workaround this though :) It's should be fairly easy to setup, then you'll just copy/paste the new URL.
> 
> https://ngrok.com/
Hi, Thank you for replying. I am not fetching from localhost. I am fetching from an elastic beanstalk app I deployed. That localhost line is a function I never used. I forgot to delete that...

**Comment by charliecruzan-stripe** [comment]
How are you initializing stripe?
