### ISSUE TITLE
Not Able to proceed with confirmPayment() method on Android (React Native)

### ISSUE THREAD

**Issue by rituraj23rails** [stripe/stripe-react-native#997]
I am doing a payment using CardField component and on passing the secret key generated from Backend, I am not able to confirm the payment using **confirmPayment()** method on Android. It blocks there nothing happens over there, I am using the following code:
const paymentIntent = await **confirmPayment**(res.data.client_secret, {
        type: 'Card',
        paymentMethodId: this.state.cardToken,
        billingDetails: {
          email: 'abc@yopmail.com',
          name: 'Jenny Rosen',
          address: {
            line1: '510 Townsend St',
            city: 'San Francisco',
            state: 'CA',
            postalCode: '98140',
            country: 'US',
          },
        },
        shippingDetails: {
          email: 'abcc@yopmail.com',
          name: 'ACC Rosen',
          address: {
            line1: '511 Townsend St',
            city: 'San Francisco',
            state: 'CA',
            postalCode: '98140',
            country: 'US',
          },
        }
      });
     And Creating a method using following code: 
      const { paymentMethod, error }: any = await **createPaymentMethod**({
          type: 'Card',
          billingDetails: {
            email: 'abc@yopmail.com',
            name: 'Jenny Rosen',
            address: {
              line1: '510 Townsend St',
              city: 'San Francisco',
              state: 'CA',
              postalCode: '98140',
              country: 'US',
            },
          },
          shippingDetails: {
            email: 'abcc@yopmail.com',
            name: 'ACC Rosen',
            address: {
              line1: '511 Townsend St',
              city: 'San Francisco',
              state: 'CA',
              postalCode: '98140',
              country: 'US',
            },
          },
        });
![Screenshot 2022-06-16 at 3 32 56 PM](https://user-images.githubusercontent.com/66063196/174046571-3a314758-8fba-403d-ae2a-1bbd56af6c75.png)

I am using the following version:
**"@stripe/stripe-react-native": "0.7.0"**
**"react-native": "0.61.3"**
So, I am not getting any response from this method. Please help!.

**Comment by charliecruzan-stripe** [comment]
Hi! This is a bug on React Native 0.64 and below- could you try upgrade to `@stripe/stripe-react-native@0.9.0`?

**Comment by rituraj23rails** [comment]
@charliecruzan-stripe Yes, but my react-native version of the project is 0.61.3 so won't be able to use this version. That's why i have used "@stripe/stripe-react-native": "0.7.0". Can i get quick fix on this version?

**Comment by charliecruzan-stripe** [comment]
@rituraj23rails can you try applying [this diff](https://github.com/stripe/stripe-react-native/pull/932/files#diff-c641ac1a5a2e0001432149268b54b6d4970a5cfbc3d5d2f202e3e3f9893d047e), either manually or with `patch-package` and let me know if that resolves it?

**Comment by rituraj23rails** [comment]
@charliecruzan-stripe Yes Its working thanks!.

**Comment by charliecruzan-stripe** [comment]
Nice 👍 for now, I recommend using [`patch-package`](https://www.npmjs.com/package/patch-package) to auto-apply that fix to your project until you are able to upgrade your React Native version. There are _lots_ of improvements so if you can find the time to upgrade I would definitely recommend it, but I also know it can be a difficult process. for what it's worth, [this upgrade tool](https://react-native-community.github.io/upgrade-helper/?from=0.61.4&to=0.68.1) helps a lot!

**Comment by rituraj23rails** [comment]
Yes @charliecruzan-stripe I have applied a patch for it.
